- Modules/ConfigOptions.lua
> Adds cap of 50 to shock damage value

- Modules/Build.lua
- Modules/CalcOffence-3_0.lua
Adds average physical hit \* impale modifier \* speed * stacks to `output.TotalDPS`, plus impale effect and impale-only DPS to build overview
> Added total impale DPS calculations to build overview

- Data/3_0/ModCache.lua
- Data/3_0/Skills/other.lua
Forgot to actually export skill and replace dummy mods in ModCache.lua with working generated ones.
> Chains of Command fix

- Data/New.lua
Also fixed many, many oversights of case and signs.
> Added new 3.9.0 unique Astral Projector

- Classes/ImportTab.lua
- Classes/Item.lua
- Classes/ItemsTab.lua
- Classes/PassiveSpec.lua
- Classes/PassiveTree.lua
- Classes/PassiveTreeView.lua
- Data/Uniques/jewel.lua
- Modules/Data.lua
- Modules/ModParser-2_6.lua
- Modules/ModParser-3_0.lua
Added full support for:
* Thread of Hope
* The new jewel ring sizes
* Intuitive Leap-like functionality jewels of all sizes
Also:
* Separated jewel radius index from jewel radius label
* Disabled allocation of jewel sockets though Intuitive Leap-like effects
> Added full support for Thread of Hope

- Data/Uniques/jewel.lua
Implements undocumented changes to threshold jewels introduced in patch 2.6.
> Fixed some threshold jewel mods that were updated in 2.6

- Classes/DropDownControl.lua
- Classes/SearchHost.lua
- Modules/Main.lua
- Modules/SearchTools.lua
This implements a popup style search feature for all dropdown lists. 
Just open a dropdown and start typing. The list will then be filtered and matches will be highlighted.
I tried to be as non invasive as possible to the DropDownControl class, but some changes just had to be made.
Also i normally don't code in lua, so i might have missed some language specific conventions and tricks.
@LocalIdentity 
if this gets merged, don't forget to add the new files to the manifest, as they are not automatically added by the py update script.
> Dropdown Search (Popup style)

- Modules/Build.lua
> Add colors to the resistances' label on the side bar

- Classes/ImportTab.lua
Works with new brand install (ie blank entries). Table is sorted alphabetically.
Welcome comments / advice on location of drop down.
> expose existing gameAccounts array to be used in import build tab. (resubmit)

- Modules/ModParser-3_0.lua
PR for fixing #103. First time working with Lua, PoB and a public repo, so if I did anything wrong, let me know.
> add support for 'ignites you inflict deal damage faster' mod

- Data/3_0/ModCache.lua
- Modules/ConfigOptions.lua
- Modules/ModParser-3_0.lua
Not a very useful thing, just a basic task to familiarize myself with the structure of the codebase. Please let me know if there is anything more needed to be done here that I am not aware of.
> Fungal ground

- Data/Uniques/body.lua
- Data/Uniques/flask.lua
- Data/Uniques/helmet.lua
- Data/Uniques/shield.lua
> Fix "Damage taken as <Elemental> Damage" mod text to only apply to hits

- Modules/ConfigOptions.lua
- Modules/ModParser-3_0.lua
Added support for "if you've stopped taking Damage Over Time Recently" to support "increased Recovery rate of Life and Energy Shield" on the Soul of Arakaali pantheon
> Added support for "if you've stopped taking Damage Over Time Recently"

- Classes/Item.lua
- Data/3_0/SkillStatMap.lua
Add support for Fire DoT multi that is added via quality on Awakened Burning Damage, Burning Arrow and Vaal Burning Arrow
> Support for Fire DoT Multiplier from Gem Quality

- Data/Uniques/amulet.lua
Pride was previously missing from the mod pool of strength auras
> Add Pride to list of Auras on Aul's Uprising

- Modules/Build.lua
Show Energy shield values in the sidebar when selecting minion skills
> Add Energy Shield to sidebar for Minions

- Modules/Main.lua
> Disable rebuilding the legacy (2.6) mod cache

- Modules/ModParser-3_0.lua
(I never included the changes to the mod parser in my original PR).
> Fix mod parser support for War Bringer

- Modules/CalcPerform.lua
"More" modifiers should be multiplied
> Fix incorrect calculation of auras and curses granted by minions

- Modules/CalcActiveSkill.lua
> Fix minion related config options and buff effect calculation

- Data/3_0/SkillStatMap.lua
- Data/3_0/Skills/sup_dex.lua
- Export/Skills/sup_dex.txt
- Modules/ConfigOptions.lua
Fix Nightblade to not work if the player is dual wielding with either a Sword, Axe or Mace
Fix elusive mod persisting if checkbox was ticked and the source to generate elusive was taken away
> Fix Nightblade weapon types and elusive mod persistance

- Data/3_0/Skills/act_dex.lua
- Export/Skills/act_dex.txt
https://feathub.com/LocalIdentity/PathOfBuilding/+10
Same implementation as barrage support
> Added support for Shattering Steel shotgun mechanic

- Modules/ModParser-3_0.lua
> Add support for Touch of Cruelty

- Modules/ModParser-3_0.lua
> Add support for Fasting

- Data/New.lua
- Modules/ConfigOptions.lua
- Modules/ModParser-3_0.lua
> Add Algor Mortis and support for its mods

- CONTRIBUTING.md
Before, the tutorials were overly explicit without stating their prerequisites and assumed skills of developers.
> Add prerequisites to CONTRIBUTING.md

- Data/3_0/ModCache.lua
- Data/3_0/Skills/act_str.lua
- Data/3_0/Skills/other.lua
- Export/Skills/act_str.txt
- Export/Skills/other.txt
- Modules/ModParser-3_0.lua
Adds Intimidating Cry from Farrul's Chase boots.
Also adds support for increased damage per nearby enemy for Rallying Cry
Fix #255
> Add Intimidating Cry and Nearby Enemy multiplier for Rallying Cry

- Export/Bases/sword.txt
No more Oni-Goroshi errors in PoB console about unknown sword type.
> Add "Charan's Sword" type to swords

- Classes/PassiveTreeView.lua
Hold Ctrl to hide tooltip on passive tree
Added tooltip hint
> Hide Tooltip When Holding CTRL

- Data/3_0/Skills/act_dex.lua
- Data/3_0/Skills/sup_str.lua
- Export/Skills/act_dex.txt
- Export/Skills/sup_str.txt
- Modules/CalcOffence-3_0.lua
- Modules/CalcSetup.lua
Mark finally gave us the placement time of Ballistas, which is 0.35 seconds. This makes it so Ballistas use the proper time.
Fixes issue #228
> Update Ballista placement speed

- Modules/ModParser-3_0.lua
> Implements Unhandeled Wandslinger Mods

- Data/3_0/Skills/act_str.lua
- Export/Skills/act_str.txt
- Modules/ConfigOptions.lua
- Modules/ModParser-3_0.lua
Implemented the features as requested in #44.
> Implemented Perforate DPS calculations in Blood Stance

- Modules/ModParser-3_0.lua
> Added minion mod parser for Vicious Bite notable

- Modules/ModParser-3_0.lua
> Add support for Skeletal Atrophy

- Data/New.lua
Adds Profane Proxy Unset Ring unique item to New.lua until we have ranges for parameters.
Fixes #319
> Adds Profane Proxy Unique

- Data/3_0/Skills/act_str.lua
- Data/3_0/Skills/other.lua
- Export/Skills/act_str.txt
- Export/Skills/other.txt
- Modules/ConfigOptions.lua
- Modules/ModParser-3_0.lua
This PR also fixes Multiplier:NearbyEnemy existing and being confounded by Multiplier:NearbyEnemies.
Fixes Issue #266
> Implemented Cry Wolf Notable

- Classes/PassiveTree.lua
- Modules/CalcOffence-3_0.lua
- Modules/ModParser-3_0.lua
- Fixed weapon ailment modifiers
- Other modifier fixes
- Add more parsing for mods that were only in the cache
> Fix 3.10 tree mods and add mods to ModParser

- Data/New.lua
- Data/Uniques/body.lua
- Data/Uniques/gloves.lua
- Data/Uniques/ring.lua
Finalises Algor Mortis, Perfidy and Profane Proxy.
Big thank you to @NickRyder for providing the stat translations that make this PR possible before the items get posted to the trade API.
> Add finalised new uniques

- Modules/ModParser-3_0.lua
> Add support for Dark Ideation

- Data/Uniques/jewel.lua
- Modules/ModParser-3_0.lua
Not sure if the life/mana recovery is working, everything else seems fine though
> Added new variants of incursion jewels and their new mods

- Modules/ModParser-3_0.lua
The only mod not currently working was the following:
+10% to Physical Damage over Time Multiplier while wielding an Axe or Sword
Fixes #390
> Support for Wound Aggravation Notable

- Modules/ModParser-3_0.lua
> Added support for Surefooted Striker notable

- Modules/ModParser-3_0.lua
> Added support for Hit and Run notable

- Modules/ConfigOptions.lua
- Modules/ModParser-3_0.lua
Closes #422 
```
15% increased Elemental Damage if you've Chilled an Enemy Recently
20% increased Elemental Damage if you've Ignited an Enemy Recently
25% increased Elemental Damage if you've Shocked an Enemy Recently
```
> Added support for Sadist notable

- Modules/ModParser-3_0.lua
> Vile reinvigoration

- Modules/ModParser-3_0.lua
resolves issue #387 
note added in with berserker as basically the same as the mod above it
> Mob mentality

- Modules/ConfigOptions.lua
- Modules/ModParser-3_0.lua
Closes #374 
Jewel:
```
New Item
Cobalt Jewel
Implicits: 0
30% increased Totem Damage if you haven't Summoned a Totem in the past 2 seconds
```
> Adds support for Ancestral Might

- Modules/ModParser-3_0.lua
closes #432 
Jewel:
```
New Item
Cobalt Jewel
Implicits: 0
Minions have a 20% chance to Impale on Hit with Attacks
```
> Adds support for Rotten Claws

- Modules/ConfigOptions.lua
- Modules/ModParser-3_0.lua
closes #434 
```
New Item
Cobalt Jewel
Minions created Recently have 10% increased Attack and Cast Speed
Minions created Recently have 30% increased Movement Speed
```
Also adds a new Condition `MinionsCreatedRecently`
> Implements Call to the Slaughter 

- Modules/ModParser-3_0.lua
Closes #445 
```
Astonishing Affliction
Cobalt Jewel
Quality: 0
Implicits: 0
20% increased Duration of Elemental Ailments on Enemies
20% increased Damage with Hits and Ailments against Enemies affected by Ailments
20% increased Effect of Non-Damaging Ailments
```
> Add support for Astonishing Affliction

- Modules/ModParser-3_0.lua
> Add support for Cooked Alive

- Modules/ModParser-3_0.lua
`Warcry Skills have 40% increased Area of Effect`
> Add support for Rattling Bellow

- Modules/ModParser-3_0.lua
> Added support for Powerful Assault notable

- Modules/ModParser-3_0.lua
> Added support for Unwavering Focus notable

- Modules/ModParser-3_0.lua
Closes #373 
Tested with 2H melee, 1H melee, and bows. Damage and AoE only increased on 2h melee
> Added support for Titanic Swings notable

- Modules/ModParser-3_0.lua
> Added support for Eye of the Storm notable

- Modules/ModParser-3_0.lua
> Added support for Assert Dominance notable

- Export/Skills/sup_int.txt
- Modules/ConfigOptions.lua
- Modules/ModParser-3_0.lua
> Add support for Intensity notable

- Modules/ModParser-3_0.lua
> Added support for Precise Retaliation notable

- Modules/ModParser-3_0.lua
> While burning

- Modules/ModParser-3_0.lua
> Wasting affliction

- Modules/ModParser-3_0.lua
This PR implements the "projectiles deal +x% per remaining chain" mod visible on the Follow-Through notable.
Closes #460
> Implement "Follow-Through" notable.

- Modules/ModParser-3_0.lua
Closes #356 
Maim is enabled globally in configuration and there is no support for forking #525
> Add support for Kineticism

- CONTRIBUTING.md
- docs/rundown.md
Some initial documentation on the code base that should answer where everything is located. Does not include parts of the calculation functionality and GUI classes.
> Add initial code base rundown

- Data/Global.lua
- Modules/CalcOffence-3_0.lua
Fixes Claw Damage nodes not working with Rigwald's Curse.
> Fix for Rigwald's Curse and Claw INC Damage Nodes

- Modules/ModParser-3_0.lua
> Support for Disease Vector Notable

- Classes/PassiveSpec.lua
Fix error that occurred when socketing non cluster jewels into jewel sockets created by a cluster jewel
> Fix error when socketing non cluster jewel

- Modules/CalcPerform.lua
- Modules/ModParser-3_0.lua
Somehow the support got removed for it
> Add back in support for unencumbered 

- Modules/ModParser-3_0.lua
The mod on darkscorn and weapons that applied more poison damage, was also applying to attack damage
> Fix more poision damage mod applying to attacks

- Modules/ModParser-3_0.lua
Fix parsing for cool-down of guard skills on the tree
> Fix guard skill parsing

- Modules/CalcDefence-3_0.lua
- Modules/ModParser-3_0.lua
Based of gainasenergyshield calculations
Closes #430
> Added support for Heart of Iron Notable

- Modules/ModParser-3_0.lua
Apllies more consistent formatting to the mod parser.
> Clean up mod parser

- Classes/ImportTab.lua
This will sort the list of the account names case insensitive
> Sort account history in import tab case insensitive

- Modules/CalcPerform.lua
- Modules/ModParser-3_0.lua
- TreeData/3_10/tree.lua
Fix the interactions that Purposeful Harbinger had with some auras and ascendancies. Also updates the tree with the new wording for Purposeful Harbinger and Replenishing Presence
> Purposeful Harbinger Fix

- Classes/Item.lua
> Fix bug where items with variants from old builds would be parsed incorrectly

- Modules/CalcPerform.lua
- Modules/ModParser-3_0.lua
Additionally added parsing for the tree and cluster jewel nodes which conditionally activate based on being under the effects of life or mana flasks.
> Added conditions for "UsingLifeFlask" and "UsingManaFlask"

- update_manifest.py
This change got lost somewhere during rebasing.
> Re-add supported file extensions to manifest updater

- Modules/ConfigOptions.lua
> Fix for the "Elusive" flag recursively checking for itself, causing a stack overflow.

- Modules/ModParser-3_0.lua
Assuming `Evade Attacks` and `Evade Attack Hits` are the same since you can only evade hits...
Closes #428
> Support for Readiness Notable

- Modules/CalcOffence-3_0.lua
- Modules/ModParser-3_0.lua
> Updated vicious skewering

- Modules/ModParser-3_0.lua
Fixed #364 - Master Of Command
> Master Of Command Implementation

- Export/Scripts/bases.lua
- Export/Scripts/masters.lua
- Export/Scripts/mods.lua
- Export/statdesc.lua
Contains the export scripts plus the results of the new export.
> The exporter now includes the mod tags for bases and mods

- Modules/CalcPerform.lua
Attributes are now calculated before life/mana reservation is calculated
- This allows the mod "1% reduced Mana Reserved per 250 total attributes" to correctly retrieve the total attributes
> Fix for Mask of the Tribunal not contributing its mana reservation

- Modules/ConfigOptions.lua
- Modules/ModParser-3_0.lua
> Adds support for Martial Momentum

- Modules/CalcOffence-3_0.lua
- Modules/ConfigOptions.lua
- Modules/ModParser-3_0.lua
Fix issue where Perquils Toe was not working
Fix issue where "Portion of Total Damage" was inaccurate when using a lucky buff and could show values of more than 100%
> Fix issues with lucky hits

- Data/3_0/Skills/spectre.lua
- Data/3_0/Spectres.lua
- Export/Minions/Spectres.txt
- Export/Skills/spectre.txt
Hey,
I've added 2 new spectre types:
- Redemption Sentry
- Baranite Thaumaturge
Would love some help with adding the correct mods etc so they are calculated correctly.
poedb links:
https://poedb.tw/us/mon.php?n=Redemption+Sentry
https://poedb.tw/us/mon.php?n=Baranite+Thaumaturge
> Added 2 new Spectre types

- Data/Uniques/helmet.lua
Fixes a typo with Maw of Conquest.
> Update Maw of Conquest Item Data

- Modules/CalcPerform.lua
> Fix herald dependend mods applying while unbuffed

- Classes/ImportTab.lua
- Classes/Item.lua
- Classes/ItemsTab.lua
- Classes/NotableDBControl.lua
- Data/Uniques/body.lua
- Data/Uniques/boots.lua
- Data/Uniques/gloves.lua
- Data/Uniques/helmet.lua
- Modules/ModParser-3_0.lua
Includes the following UI:
- Button to anoint when editing an amulet
- List of notables with tooltips showing what the notable does and its recipe
- Sorting by the standard power options
> Added UI for anointing amulets

- Modules/ModParser-3_0.lua
The mod is found on the new Doryani's Prototype unique.
In PoB:
> Deal No Non-Lightning Damage mod implementation

- Modules/ConfigOptions.lua
Correcting it to the post nerf elusive numbers: https://pathofexile.gamepedia.com/Elusive
> Update elusive tooltip numbers

- Classes/Tooltip.lua
Fixes PathOfBuildingCommunity/PathOfBuilding#915
> move oil image loading out of tooltip constructor

- Data/Uniques/jewel.lua
The new wording is already understood by the mod parser.
> Update mod on Brittle Barrier

- Data/3_0/Skills/sup_str.lua
- Export/Skills/sup_str.txt
> Fix:20Q Awakened Generosity not increasing supported auras level

- Modules/CalcSections-3_0.lua
> Fix faster bleeding mods not being displayed

- Modules/ModParser-3_0.lua
Adds support for aura duration modifiers
> Add support for First Among Equals node

- Data/3_0/Skills/act_str.lua
- Export/Skills/act_str.txt
> Fix for Berserk quality attack damage not applying properly.

- Modules/CalcOffence-3_0.lua
- Modules/Data.lua
> Add the 75% cap for buff expiration slowness

- Modules/CalcOffence-3_0.lua
- Modules/Data.lua
added hardcaps to attack, cast, trap throwing and mine throwing speeds
as well as rounded cooldowns up to nearest server tick
> Server hardcaps

- Data/Uniques/mace.lua
The new wording is already understood by the mod parser.
> Update mod on Mon'tregul's Grasp

- Data/Uniques/body.lua
- Modules/ModParser-3_0.lua
> Add Mortal Conviction to Skin of the Lords

- Data/Uniques/body.lua
- Data/Uniques/boots.lua
- Modules/ModParser-3_0.lua
> Fix bleed infliction/immunity mods

- Data/3_0/Minions.lua
- Modules/CalcSetup.lua
Removed the 20% more physical damage while dual wielding modifier
> removed 20% more phys damage while dual wielding

- Data/Uniques/amulet.lua
- Data/Uniques/axe.lua
- Data/Uniques/belt.lua
- Data/Uniques/boots.lua
- Data/Uniques/bow.lua
- Data/Uniques/claw.lua
- Data/Uniques/dagger.lua
- Data/Uniques/gloves.lua
- Data/Uniques/helmet.lua
- Data/Uniques/jewel.lua
- Data/Uniques/mace.lua
- Data/Uniques/ring.lua
- Data/Uniques/shield.lua
- Data/Uniques/staff.lua
- Data/Uniques/sword.lua
- Data/Uniques/wand.lua
Please note that the patch notes are incomplete or flat out wrong in many cases.
Might and Influence changes are not updated, as it's not clear yet what the mod pool is.
> Update all old uniques to 3.11.0

- Export/Skills/act_str.txt
- Updates Herald of Purity to provide its new mod of % More Physical Damage
> Update Herald of Purity to 3.11

- Classes/GemSelectControl.lua
- Classes/SkillsTab.lua
> Adding dropdown to select dps field for sorting support gems

- Data/Uniques/shield.lua
Update wording on Tukohama's Fortress. The new wording is already understood by the mod parser.
> Update Tukohama's Fortress

- Data/3_0/Skills/act_dex.lua
- Export/Skills/act_dex.txt
EA now caps to 20 fuses, let's allow this calculation
Closes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/782
> Allow calculating the maximum damage on Explosive Arrow

- Data/3_0/Skills/act_str.lua
- Export/Skills/act_str.txt
- Modules/ConfigOptions.lua
- Modules/ModParser-3_0.lua
- Adds mod parsing for the stats to do with "if you've changed Stance Recently"
- Adds +2 spikes to Perforate if you've changed stance recently
- Adds config option for this stat
> Support "If you've changed Stance Recently"

- Data/3_0/Skills/act_str.lua
- Export/Skills/act_str.txt
Fix Rage not working when Chain Hook was the only source of Rage generation
> Fix Rage from Chain Hook

- Modules/ModParser-3_0.lua
Adds parsing for the Bleed DoT multi per rage mod
> Add support for Rigwald's Command new mod

- Classes/CalcBreakdownControl.lua
- Adds commas to breakdowns and tooltips in the Calcs tab
(this image is taken from #1140 for demonstration purposes but this PR does not include the ailment tables)
(tables and windows get made slightly wider if there will be commas added)
I am not super familiar with gsub, but used it several times in this PR to count various things in strings. If anyone has a better solution for counting stuff, I'm open to it, I just used the first thing that worked.
> Add commas to Calcs tab breakdowns/tooltips

- Classes/SkillsTab.lua
Fixes #1130 defaulting to the proper gem level and quality when the defaults are deleted
> Fixes #1130

- Modules/ModParser-3_0.lua
Added support for the "nearby enemies have less accuracy rating" mod on avatar of the veil
> added less accuracy support on avatar of veil

- Data/Uniques/belt.lua
Adds scaling support for the Projectile Attack Damage mod with Abrasive catalysts
> Fix The Nomad catalyst mod

- Modules/CalcDefence-3_0.lua
- Modules/CalcSections-3_0.lua
reworks the net Regen to better include ES regen, including bypass of es, and also includes more detailed breakdowns
> Net regen rework

- Data/3_0/Skills/act_dex.lua
- Data/3_0/Skills/act_int.lua
- Data/3_0/Skills/act_str.lua
- Export/Skills/act_dex.txt
- Export/Skills/act_int.txt
- Export/Skills/act_str.txt
- Modules/CalcOffence-3_0.lua
Adds in missing AoE numbers for many different skills and fixes some calculations for certain AoE values.
Adds calculations for Molten Strike's projectile range
> Add AoE Numbers for many skills

- Data/3_0/Skills/act_str.lua
- Export/Skills/act_str.txt
- Modules/ConfigOptions.lua
The dropdown for the skill has been on the gem for a long time but people didn't seem to know it existed, so I moved it to the configs page
> Move Pride's Effect drop-down to the configs page

- Data/3_0/Skills/other.lua
- Data/Uniques/belt.lua
- Data/Uniques/helmet.lua
- Data/Uniques/quiver.lua
- Data/Uniques/shield.lua
- Data/Uniques/staff.lua
- Data/Uniques/sword.lua
- Export/Skills/other.txt
Also adds new harbinger skills on these uniques.
> Add upgraded harbinger uniques

- Modules/ModParser-3_0.lua
The mod was changed in 3.11 with new wording
> Replenishing Presence fix

- Modules/CalcOffence-3_0.lua
- Modules/CalcSections-3_0.lua
- Modules/ModParser-3_0.lua
- Adds parsing for and fixes calculations to do with Emberwake's ignite stacking
- Shows burn rate modifiers in ignite duration breakdown
> Fix Emberwake ignite stacking

- Modules/ModParser-3_0.lua
Adds support for damaging ailments you inflict deal damage faster while affected by malevolence
> Watchers Eye fast damaging ailments mod

- Modules/CalcPerform.lua
> Restricts minimum charge count to maximum of the same charge

- Data/3_0/SkillStatMap.lua
- Data/3_0/Skills/act_str.lua
- Export/Skills/act_str.txt
- Modules/CalcOffence-3_0.lua
- Modules/CalcPerform.lua
- Modules/ConfigOptions.lua
- Modules/ModParser-3_0.lua
> Exerted Attacks

- Modules/ConfigOptions.lua
- Modules/ModParser-3_0.lua
Updated according to [poedb](https://poedb.tw/us/Broken_Faith)
Requires ModCache rebuild
> Add support for mods on Broken Faith

- Data/3_0/ModCache.lua
- Modules/CalcOffence-3_0.lua
Fixes #367 
Removes need for old PR #488
> PressurePoints fix

- Modules/CalcOffence-3_0.lua
In `dev` - when PressurePoint Cluster notable got merged in with Exerted Attacks the DoubleDamage sections got put into two places with redefines. This fixes them to only be defined once and properly apply.
> Fixes For New Release

- Classes/PassiveTreeView.lua
> BUG: Ascendancy points showing up on the nearby strong nodes in the heatmap

- Data/Uniques/belt.lua
- Modules/CalcPerform.lua
- Modules/CalcSetup.lua
- Modules/Calcs.lua
- Modules/ConfigOptions.lua
- Modules/ModParser-3_0.lua
Add Alchemists Genius Buff
Add support for Essence Glutton regen on corpse consume
Add support for new Impresence wording
Add support for Brewed for Potency cluster notable
Add Wither chance for Eternal Suffering cluster notable
Add support for Chilling Presence  cluster notable
Add support for Forbidden Words  cluster notable
Add support for Lead by Example  cluster notable
Add support for Disciples  cluster notable
Add support for many Ailment immune nodes
Add support for Overwhelming Odds jewel
Add partial support for Rolling Flames jewel
Fix The Torrent's Reclamation Implicit
> Add parsing for a bunch of nodes

- Data/3_0/Skills/other.lua
- Export/Skills/other.txt
- Modules/ConfigOptions.lua
Add the action speed buff from slipstream provided by the skills from The Flow Untethered and The Torrent's Reclamation
> Slipstream from Harbinger of Time support

- Data/3_0/Skills/act_dex.lua
- Export/Skills/act_dex.txt
Added -50% explosion multiplier
Added 5 fuse, fixed 10 fuse to use 10
> Explosive arrow fixes

- Classes/CalcsTab.lua
- Classes/PassiveTreeView.lua
> Remove anoint nodes from top node

- Modules/CalcOffence-3_0.lua
Crash was due to the actor was not being set properly when using Dancing Dervish as it is a minion skill that has AoE increases based on the players weapon
> Fix Dancing Dervish Crash

- Modules/ModParser-3_0.lua
fix for issue #1253 - spelling error was cause
> Fix Siegebreaker Belt Bug

- Data/Uniques/gloves.lua
> Reordering mods on Vixen's entrapment to show "Trigger Socketed Curse Spells when you cast a Curse"

- Data/3_0/Skills/sup_int.lua
- Export/Skills/sup_int.txt
Still learning all this stuff, just copied from awakened added lightning damage to work with curses.
> Fix awakened blasphemy quality +1 curse skills

- Data/3_0/Skills/spectre.lua
- Data/3_0/Spectres.lua
- Export/Minions/Spectres.txt
- Export/Skills/spectre.txt
> Add Templar Tactician spectre

- Classes/CalcsTab.lua
May have misunderstood the normal vs misc, but misc appeared to be specifically for this.
> Now uses misc calc to use all changes of adding node

- Classes/SkillsTab.lua
- Modules/CalcSetup.lua
- Modules/CalcTools.lua
Applies gem quality from version selected
> Added dropdown for alt gem quality

- Modules/ModParser-3_0.lua
Need to test once new patch is live and Discharge has a Cooldown.
> Implemented Endless Misery Threshold Jewel

- Classes/SkillsTab.lua
Defaults to Default quality if gem changed
Handles vaal gems
> Generates list for each slot independently when gem is selected

- Classes/SkillsTab.lua
Plus a crash fix on mis-typed gems with secondary supports.
> Fix to only display correct Alternate options for all gems

- Modules/ModParser-3_0.lua
Minor change intended with tree wording updates, if you wanted to push an update but withhold other stuff
> Updating wording of Intensity node

- Data/3_0/SkillStatMap.lua
- Data/3_0/Skills/act_int.lua
- Export/Skills/act_int.txt
Tested as working with Alternate Quality (except Discharge not consuming charge chance)
> Implemented New Discharge

- Data/3_0/Skills/act_int.lua
- Export/Skills/act_int.txt
- Modules/CalcOffence-3_0.lua
> Fixing assassin's mark crit multi mod

- Modules/ModParser-3_0.lua
Also added support for possible future "deal no fire damage" and "deal no lightning damage".
> Implemented Replica Cold Iron Point

- Modules/CalcDefence-3_0.lua
- Modules/ModParser-3_0.lua
added support for missing resistance
> added support for Replica Nebulis

- Data/3_0/Skills/spectre.lua
- Data/3_0/Spectres.lua
- Export/Minions/Spectres.txt
- Export/Skills/spectre.txt
> Add Frost Auto-scout spectre

- Data/3_0/Skills/spectre.lua
- Data/3_0/Spectres.lua
- Export/Minions/Spectres.txt
- Export/Skills/spectre.txt
> Add Syndicate Operative spectre

- Data/3_0/Skills/spectre.lua
- Data/3_0/Spectres.lua
- Export/Minions/Spectres.txt
- Export/Skills/spectre.txt
> Add Artless Assassin spectre

- Data/3_0/SkillStatMap.lua
- Data/Uniques/sword.lua
- Modules/CalcOffence-3_0.lua
- Modules/CalcPerform.lua
- Modules/CalcSetup.lua
- Modules/ConfigOptions.lua
- Modules/ModParser-3_0.lua
In support of Sweep Alternate 2.
Need mechanic-tester to determine if "Double Damage" is exclusive of "Triple Damage" or can we hit a Triple-Double-Crit...
> Triple Damage Implementation

- Data/3_0/Skills/spectre.lua
- Data/3_0/Spectres.lua
- Export/Minions/Spectres.txt
- Export/Skills/spectre.txt
Please add the Cloud Retch Spectre, Uses a mortar like the normal Retch which creates projectile Shards on mortar impact.
> Add Cloud Retch Spectre

- Data/3_0/SkillStatMap.lua
- Data/3_0/Skills/act_dex.lua
- Export/Skills/act_dex.txt
- Modules/ConfigOptions.lua
Added support for Lingering Blades and fixed more attack speed from gem
Fixes #659
> Update Animate Weapon

- Modules/CalcActiveSkill.lua
- Modules/CalcPerform.lua
Fix how the weapon is given to the Skeletons.
> The Iron Mass Fix

- Data/3_0/Skills/sup_str.lua
- Export/Skills/sup_str.txt
Ailment damage effect was overridden by use of wrong key
Alt2 was incorrect
> Fortify fix

- Classes/TreeTab.lua
> Power report resolution fix

- Data/Uniques/jewel.lua
The Unholy Might mod was not appearing as a line on the jewel
> Fix Growing Agony mod not appearing

- Data/Uniques/staff.lua
> Changing wording of Agnerod's staves

- Data/3_0/Skills/sup_str.lua
- Export/Skills/sup_str.txt
> Shockwave is flagged to only show average

- Data/3_0/Skills/act_str.lua
> Bladestorm attack speed now only applies to bladestorm

- Modules/CalcSections-3_0.lua
> Add enemy modifiers section for self-bleed chance

- Modules/CalcPerform.lua
> Adding calc effect of divergant rallying

- Data/3_0/Skills/act_str.lua
- Export/Skills/act_str.txt
> Fixing inversion of static strike repeat benefits

- Modules/CalcDefence-3_0.lua
> Mystic Bulwark Fix

- Data/3_0/Skills/spectre.lua
- Export/Skills/spectre.txt
- Modules/ConfigOptions.lua
Curse changes affected spectres. The config switch also needed to be updated to work with new flags
Fixes #1584
> Fix minion curses

- Data/Generated.lua
> Add Replica Forbidden Shako

- Data/Uniques/amulet.lua
- Data/Uniques/axe.lua
- Data/Uniques/belt.lua
- Data/Uniques/body.lua
- Data/Uniques/boots.lua
- Data/Uniques/gloves.lua
- Data/Uniques/jewel.lua
- Data/Uniques/staff.lua
- Modules/ModParser-3_0.lua
All new mods are supported. I had to only add support for the new mods on Gluttony, as all other new mods were already used elsewhere and supported.
> Apply 3.12 unique balance patch

- Modules/CalcOffence-3_0.lua
> More Accurate Combined DPS Tooltips When Losing DOT Components

- Data/3_0/Skills/other.lua
- Data/3_0/Skills/sup_dex.lua
- Data/3_0/Skills/sup_int.lua
- Export/Scripts/skills.lua
- Export/spec.lua
Some gems had incorrect magnitudes of quality mods
> Fix gem quality export

- Data/3_0/Skills/act_int.lua
- Export/Skills/act_int.txt
> Adding duration as dps mod to storm burst

- Data/Uniques/sword.lua
- Modules/ModParser-3_0.lua
> Issue 1633 - Fix Voidforge wording

- Classes/PassiveSpec.lua
- Classes/TreeTab.lua
> Fixes #1519, #1562 - Thread of Hope socketed in cluster jewel

- Data/3_0/Skills/other.lua
- Export/Skills/other.txt
- Modules/ConfigOptions.lua
- Modules/ModParser-3_0.lua
> Add Contaminate skill from Sporeguard

- Modules/Build.lua
Fixes bug when creating a new build introduced by #1722
> Fix creating new builds

- Data/Uniques/helmet.lua
> Fix The Peregrine variants

- Data/3_0/Skills/act_str.lua
- Export/Skills/act_str.txt
> Fixing dominating blow quality to apply to minions

- Modules/CalcOffence.lua
- Modules/ModParser.lua
> Fixes #1770 - Cold damage can always freeze, no need to double-count it

- Modules/ModParser-3_0.lua
Addresses #1672
All that was missing was a preFlagList entry for the non-vaal skills craft.
> Add preFlagList entry for non-vaal skills craft

- Classes/Item.lua
- Data/Uniques/boots.lua
This PR fixes things like Beacon of Madness and allows us to add Precursor's Rings
> Changing bases with variants

- Data/SkillStatMap.lua
- Export/Skills/act_int.txt
- Export/Skills/act_str.txt
> Adding quality mods to Zealotry and Anger

- Data/Uniques/jewel.lua
Fixes #1740 Also fixes another incorrect variant of Malevolence Watcher's Eyes.
> Remove incorrect Watcher's Eye variant

- Classes/ItemsTab.lua
- Modules/ModParser.lua
Also add some unique Flask effects
> Empire cardiro keystone and Flask tooltips mismatch fixed

- Classes/Item.lua
- Modules/ModParser.lua
- Quality modifiers from crafting bench and Heist Implicit
- importing custom items with quality modifiers 
import preview
imported result
removing quality modifiers
> Full support for weapon and armour quality modifiers

- Classes/Item.lua
Fixes #1787 
That bug uncovered another bug where crafting magic/normal items was impossible.  Hopefully this fixes all corner cases once again, considering I rewrote it 3 times trying to fix them all.
> Fixing bug introduced with variant bases for magic/normal items

- Modules/ItemTools.lua
Fixes things like Bottled Faith crit slider
> Fixing range parsing to include the decimal case

- Classes/GemSelectControl.lua
Adds the gem tooltip before putting the cached gem back in
Added some comments to the block
> Fixes gem tooltip on dropdown hover

- Modules/CalcPerform.lua
- Modules/ConfigOptions.lua
- Modules/ModParser.lua
Frost Bomb
No Frost Bomb, exposure from Corrosive Elements
Fireball with added lightning linked, lightning exposure, no fire exposure
Condition for mana regen
> Ritual - Elementalist Mastermind of Discord

- Modules/CalcPerform.lua
- Modules/CalcSetup.lua
- Modules/ConfigOptions.lua
- Modules/ModParser.lua
Convergence On
Convergence Off
Config option only appears when a convergence source is available
> Ritual - Elementalist Heart of Destruction

- Data/Uniques/jewel.lua
Unending Hunger's Soul Eater mod was changed in game patch 3.9.0. No legacy versions exist.
Fixes #1837
> Update Unending Hunger

- Modules/ModParser.lua
> minor additions and wording changes

- Data/ClusterJewels.lua
- Export/Scripts/cluster.lua
> Fixes #1800 - Removed redundant code and kept ordering consistent

- Classes/SkillsTab.lua
> Adding stat comparisons to alternate qualities on hover

- Classes/SkillsTab.lua
Skills would stay with the default quality when copied
> Fixing copy/paste functionality for alternate quality skills

- Export/Bases/dagger.txt
- Export/Bases/staff.txt
> Re-adding missing mods that were inadvertently removed

- Modules/CalcOffence.lua
> Updating far shot to a new scale

- Data/New.lua
Adds the following uniques:
* Blackflame
* Hand of the Fervent
* Legacy of Fury
* Qotra's Regulator
> feat: add all new uniques known before release

- Modules/ModParser.lua
implemented support for Power & Endurance charge increase in one-line
> Ritual - Conviction Of Power

- Modules/ModParser.lua
> Fix for Follow-Through medium cluster notable

- Data/Uniques/jewel.lua
> Fix Hazardous Research (Should be limited to 1)

- Modules/CalcOffence.lua
> Fixes highest damage type calculation not existing outside of breakdown

- Modules/Data.lua
For some reason I use these a lot
> Add block and spellblock chance to node highlight list

- Data/Uniques/gloves.lua
> Fix small bug on Doryani's Fist

- Classes/GemSelectControl.lua
There may be a bit of bad data out there still, but this fixes those caused by searching, at least.  I'll keep monitoring for new ones otherwise
> Fixes #1960, #1950, #1859 - SkillsTab crashes

- Data/Skills/sup_int.lua
- Export/Skills/sup_int.txt
> Trinity Fix

- Data/Skills/spectre.lua
- Data/Spectres.lua
- Export/Minions/Spectres.txt
- Export/Skills/spectre.txt
> Please add Flickershade spectre

- Classes/PassiveTreeView.lua
- Classes/TreeTab.lua
> Fixes #1619 - Adding text boxes for freely inserting random mods on certain vaal notables

- Modules/ConfigOptions.lua
- Modules/ModParser.lua
Implemented all modifiers except: "Enemies Killed by your Hits are destroyed while Insane"
> Implemented Doppleganger modifiers

- Modules/ModParser.lua
The enchant parses now.
I'm not sure if the mod format is exactly correct, but it works and I copied it from the other chain enchant parsing.
> Added Cobra Lash Additional Chains Helmet Enchant

- Data/Uniques/mace.lua
- Modules/ModParser.lua
Typo fix, kill to hit.
Fixes #2104
> Cameria's Averice Fix

- Classes/Item.lua
However... currently it doesn't respect Influence selection by remove mods that are Influence & Elevated
> Adds Elevated affixes to item crafting

- Export/Scripts/mods.lua
No longer "baz" and "qux" spam.
> Improved Information in Mods GGPK dumping

- Data/Skills/act_str.lua
- Export/Skills/act_str.txt
#2102 fix with bonus Smite Phantasmal quality fix as well.
> Alt quality fixes

- Modules/ModParser.lua
After running a sorted diff on ModCache.lua, this only ends up changing lines that are already unsupported, or fixing lines that needed to be fixed anyway (e.g. 100% increased Spell Damage taken when on Low Mana)
> Adding support for parsing flags/conditions

- Export/statdesc.lua
- Modules/StatDescriber.lua
Need to re-export from GGPK to update the mods on items like Curse on Hit rings and their effect values.
> Implement Specifier 'multiply_by_four'

- Modules/CalcPerform.lua
Makes Skitterbots automatically Chill the enemy, just like they automatically Shock.
Resolves #2091
> Make Skitterbots automatically Chill

- Modules/CalcBreakdown.lua
- Modules/ModParser.lua
> Added support for Blizzard Crown implicits

- Modules/ConfigOptions.lua
- Modules/ModParser.lua
A condition to check if you've gained power charges recently is already implemented.
> feat: add support for goblinedge

- Modules/CalcOffence.lua
- Modules/CalcPerform.lua
- Modules/CalcSections.lua
- Modules/ConfigOptions.lua
- Modules/ModParser.lua
To handle "Legacy of Fury" unique boots.
> Scorched Ground Support

- Data/Uniques/belt.lua
- Data/Uniques/jewel.lua
* Update Leash of Oblation (no legacy variants)
* Update Lord of Steel
> feat: implement all missing uniques changes

- Data/Skills/other.lua
- Export/Skills/other.txt
> Death Aura Fix

- update_manifest.py
Add a CLI to the manifest updater script.
> Improve manifest updater

- Modules/CalcOffence.lua
Forgot source field and hence keyword flag argument is in wrong location making the MORE damage not apply.
> Fix Affliction Charges for Ailments

- Data/Skills/act_int.lua
- Export/Skills/act_int.txt
#2178 
Added Lightning Penetration statMap
> Divergent Purity of Lightning Fix

- Data/SkillStatMap.lua
> Fixes Divergent Cobra Lash

- Modules/CalcOffence.lua
> Fix Attack Speed affecting Mine or Trap Supported attacks

- Modules/CalcPerform.lua
> Fix 'enemy is hexproof' Config Setting affecting marks

- Modules/CalcDefence.lua
- Modules/CalcOffence.lua
Clean-Up the code a tiny bit to provide consistency in how Sum and More are used.
> Sum/More Clean-Up

- Data/Skills/other.lua
- Export/Skills/other.txt
- Modules/ModParser.lua
Triggered curses now correctly receive reduced curse effectiveness and reserve no mana.
Fixes #2194, `ModCache` needs to be rebuilt
> Fix Doedre's Skin

- Data/Uniques/sword.lua
"Cast" became "Trigger" a while back....
> FIX: Cospri's Malice wording

- Classes/CalcBreakdownControl.lua
- Classes/CalcSectionControl.lua
- Classes/TreeTab.lua
- Modules/Build.lua
- Modules/Common.lua
- Modules/Main.lua
New PR of #2005 with clean commit timeline because I don't know how to use git properly
>Not everyone uses the same separators.
>This PR plans to help this by adding options to choose which separator character is used when displaying numbers.
> Added customisation options for decimal and thousands separators

- Modules/CalcOffence.lua
> FIX: Removed Attack flag from dotCfg

- Data/SkillStatMap.lua
- Data/Skills/sup_dex.lua
- Data/Skills/sup_int.lua
- Export/Skills/sup_dex.txt
- Export/Skills/sup_int.txt
> Fix alternate quality Purifying Flame, Hypothermia, Phys to Lightning debuffs

- Modules/ModParser.lua
> Fix Accuracy per quality should be global

- Data/Skills/act_int.lua
- Export/Skills/act_int.txt
This PR tries/seems to fix #1936
Pastebin for testing purposes: https://pastebin.com/UkUK74xu
> Fix: Oos activation frequency with more multipliers to cast speed

- Data/Skills/act_int.lua
- Export/Skills/act_int.txt
Hydrosphere should use skill conversion
Fixes #2275
> Fix Hydrosphere damage conversion

- Modules/ModParser.lua
fix e->a typo on one of the mods.
> Doryani's Prototype: fix typo

- Data/Skills/sup_dex.lua
- Export/Skills/sup_dex.txt
- Modules/CalcOffence.lua
- Modules/CalcPerform.lua
Now DPS based Support recommendations won't include Cast on Death as top dog. If you want large average hit, it still will.
> Cast on Death implementation

- Modules/CalcOffence.lua
- Modules/ModParser.lua
With two actum's equipped (one 20% crit, one 30% crit):
> Add support for Actum crit modifier

- Data/Skills/act_dex.lua
- Export/Skills/act_dex.txt
Fix the spell damage taken parsing
> Fix Divergent Ensnaring Arrow

- Modules/ModParser.lua
Voidfletcher was updated with new text for the void shot mod
> Fix Voidshot Parsing

- Modules/CalcPerform.lua
- Modules/ModParser.lua
Adds lesser brutal and massive lesser shrine effects with Blunderbore
> Add support for Blunderbore's shrine effects

- Data/Skills/other.lua
- Data/Uniques/wand.lua
- Export/Skills/other.txt
Wording change verified via:
[https://www.pathofexile.com/trade/search/Ritual/vjde9CE](https://www.pathofexile.com/trade/search/Ritual/vjde9CE)
> Fix wording on Poet's Pen

- Classes/ModStore.lua
Please let me know if there's a better way to achieve this.
> Fix flask effect incorrect in certain situations

- Classes/ImportTab.lua
- Classes/ItemsTab.lua
- Classes/PassiveSpec.lua
> Handle Cluster Generation based on New Import Format

- Modules/CalcPerform.lua
- Modules/Calcs.lua
- Modules/ConfigOptions.lua
Thought about doing the same for Intensify and Infused Channeling, but those work differently and would take more work than I have time for at the moment.
> Made inspiration charges default to maximum

- Classes/CalcsTab.lua
Marking as a work in progress pending confirmation that this won't cause a bug in JIT (see https://github.com/PathOfBuildingCommunity/PathOfBuilding/commit/fc2586c7e124bb6fa3cb278212284dbe69f73565#diff-599f90130fb0f18f37d5724689eddf0497c23add84a5ac3587a5677cd94506bf )
> Removing garbage collection calls to improve memory

- .gitignore
- src/Launch.lua
- src/Modules/CalcPerform.lua
- src/Modules/Main.lua
- Update some `.gitignore` stuff
- Made APP_NAME global to set window title
> New Structure Fix-Ups

- src/Classes/PassiveSpec.lua
- src/Modules/Main.lua
This PR is big and should be merged "AFTER" #2394 as it builds on it do to the one hard-coded 2_6 tree reliance we had in there.
> Lazy Passive Tree Loading

- src/Modules/CalcPerform.lua
See #1739 for a similar fix specific to only one of the brands
> Fix brand attachment limit for several skills

- src/Classes/Item.lua
- src/Classes/ItemsTab.lua
- src/Data/Generated.lua
> Add support for Precursor's Emblem

- Classes/CalcsTab.lua
- Classes/PassiveTreeView.lua
- Classes/PowerReportListControl.lua
- Classes/TreeTab.lua
A few UI bugs remain, but the core logic is in place.
> Moving power report to a drawer and adding additional features

- src/Classes/CalcsTab.lua
- src/Classes/GemSelectControl.lua
- src/Classes/ItemDBControl.lua
- src/Data/Global.lua
- src/Modules/CalcSetup.lua
- src/Modules/Calcs.lua
Only use FullDPS skill roll-up in Gem Selection, Power Builder and Item Recommendations when "Full DPS" is chosen.
> FullDPS only calculated when used

- src/Modules/CalcOffence.lua
Fixes information about multi-part skills using left-hand side selected dropdown.
> FIX: Generals Skill Part Name in Left Side

- src/Modules/CalcPerform.lua
Crash screenshot:
Sample build:
[8XV9yzjg.zip](https://github.com/PathOfBuildingCommunity/PathOfBuilding/files/6260153/8XV9yzjg.zip)
Original report: https://old.reddit.com/r/pathofexile/comments/mkgczk/path_of_building_community_200_coc_generals_cry/gtg85b7/
> Fix crash with certain CoC triggered skills

- src/Modules/CalcPerform.lua
Gave it the same treatment I gave General's Cry and Saviour
> Fix reliance on a mode for Mirage Archer

- src/Modules/CalcOffence.lua
This removes hard-coded Reflection skill being reliant on "CALCS" calculation.
> Fix: Saviour's Reflection Multi-part Skill behavior

- src/Classes/SkillsTab.lua
From: https://old.reddit.com/r/pathofexile/comments/mkgczk/path_of_building_community_200_coc_generals_cry/gtihgue/
> Fix ability to tab between inputs on the skills tab

- src/Modules/ModParser.lua
Just adding two more mods to appear blue that we will never handle.. b/c why not.
> Unsupported Mod Additions

- src/Data/Skills/act_dex.lua
- src/Export/Skills/act_dex.txt
VD and DD were having their flat spell damage applied to the corpse explosion when this should not be the case
> Fix DD and VD having their spell damage apply to corpse explosions

- src/Data/Skills/act_int.lua
- src/Export/Skills/act_int.txt
> Fix Wintertide brand not getting +1 to attached brand

- src/Data/Uniques/boots.lua
fixes #2473 
https://www.pathofexile.com/trade/search/Hardcore%20Ritual/xXO4fP
> Fix outdated modifier text on Aberrath's Hooves

- src/Modules/CalcPerform.lua
- src/Modules/Data.lua
Created `data.misc.LowThreshold` variable, updated to 0.5
> Update Low Life/Mana threshold

- src/Classes/SkillsTab.lua
- src/Modules/Calcs.lua
Adds support for Count scaling of things like "Raise Spider" from Arakaali's Fang, Fiend Dagger and other Active Skills.
> Add support for count-scaling Active Skills from items

- src/Modules/CalcPerform.lua
> Fix TriggerByBrand interaction with Item-granted Active Skill

- src/Classes/Item.lua
- src/Classes/ItemsTab.lua
- src/Data/Uniques/amulet.lua
- src/Data/Uniques/belt.lua
- src/Data/Uniques/ring.lua
Also found a few bugs/errors for other tags of items I was updating.
> Add support for Accelerating, Noxious, and Unstable catalysts

- src/Classes/Item.lua
- src/Data/Uniques/amulet.lua
- src/Data/Uniques/belt.lua
- src/Data/Uniques/body.lua
- src/Data/Uniques/boots.lua
- src/Data/Uniques/bow.lua
- src/Data/Uniques/claw.lua
- src/Data/Uniques/flask.lua
- src/Data/Uniques/gloves.lua
- src/Data/Uniques/helmet.lua
- src/Data/Uniques/jewel.lua
- src/Data/Uniques/quiver.lua
- src/Data/Uniques/shield.lua
- src/Data/Uniques/sword.lua
- src/Modules/ModParser.lua
PR to gather some 3.14.0 unique updates - no logic added, only text changes.
- Infernal Mantle
- Law of the Wilds
- Null's Inclination
- Signal Fire
- Apep's Slumber
- Mask of the Spirit Drinker
- Sacrificial Heart
- Cowards Chains
- Dance of the Offered
- Story of the Vaal
- Architects Hand
- Rigwald's Quills
- Atziri's Reign
- Vessel of Vinktar
> 314 uniques

- src/Modules/ModParser.lua
This started out as a commit to support "Nearby enemies are crushed", but that isn't actually a flag, but raw stats.  In typing this up, I realized that it's now possible to stack the "Crushed" debuff, and that does need to be reworked into a proper flag.
I can do that in this PR, or leave it for a separate one.
> Adding more flags for parsing enemy modifiers

- src/Modules/ConfigOptions.lua
- src/Modules/ModParser.lua
* 25% increased Armour **per Defiance**
* 50% increased Maximum total Life Recovery per second from Leech **while you have Defiance**
NB: second mod will require support for new leech mods wording.
> Add support for Defiance (berserker Defy Pain)

- src/Modules/ModParser.lua
I left the Crushed mod out on purpose as it needs to be fixed anyway
> Add support for Glimpse of Chaos

- src/Modules/CalcOffence.lua
> Fixes Bow DoT Skills double-dipping on nodes that grant a Dot & Hit

- src/Data/Uniques/body.lua
> added current aura effect variant to victarios influence

- src/TreeData/3_14/tree.lua
Mistake on the provided json tree: https://old.reddit.com/r/pathofexile/comments/mr2w58/where_tailwind/gujtcsh/
> Add Tailwind back to Deadeye and Gathering Winds

- src/Data/SkillStatMap.lua
- src/Data/Skills/other.lua
- src/Export/Skills/other.txt
- src/Modules/CalcPerform.lua
- src/Modules/ModParser.lua
Lifetap incorrectly applied the Blood Magic effect to reservations
Also removed useless flag from Thirst for Blood
> Fix Blood Magic

- src/Data/Uniques/staff.lua
> Fix: added missing implicit on Disintegrator

- src/Modules/CalcOffence.lua
- src/Modules/CalcSections.lua
> Split reservation mod into mana and life reservation mods

- src/Data/Skills/other.lua
- src/Data/Uniques/shield.lua
- src/Export/Skills/other.txt
- src/Modules/ModParser.lua
Old copies in standard use the new wording
> Fix Prism Guardian

- src/Modules/ModParser.lua
Test-PoB: https://pastebin.com/57a2XJYV
Zealotry + Arrogance Support to reserve 50% life
Testsetup **with** the Belt: 
Testsetup **without** the Belt:
> add cowards chains mod parsing

- src/Classes/PassiveTreeView.lua
- src/Classes/TreeTab.lua
Added a tooltip to help fix #160, also
> Fixes #2494 - short circuits out of search function if the lua pattern is invalid

- src/Data/Uniques/amulet.lua
- src/Modules/ModParser.lua
> Fix updated marylenes culling strike mod to the newest version

- src/Modules/CalcPerform.lua
Take PR from #2446 and apply to always simulate, even with just 1 spell.
Cleans up some whitespace.
> Simulation Trigger Enhancements

- src/Data/Uniques/amulet.lua
fixes #2754 
confirmed with: https://www.pathofexile.com/trade/search/Ultimatum/lewZrWwIV
> fixed wording on eyes of the greatwolf

- src/Modules/ModParser.lua
fixes #2757 
Trap:
Mine:
Test PoB: https://pastebin.com/xDNtW68c
> Adds trap and mine speed essence mod

- src/Data/Uniques/amulet.lua
- src/Data/Uniques/body.lua
- src/Data/Uniques/boots.lua
- src/Data/Uniques/helmet.lua
- src/Data/Uniques/jewel.lua
- src/Data/Uniques/ring.lua
- src/Data/Uniques/sword.lua
fixes #2745 
https://www.pathofexile.com/trade/search/Standard/qmZ6J5vfg
> Fix: Mana Reservation mods

- src/Data/Uniques/jewel.lua
fixes #2674
https://www.pathofexile.com/trade/search/Hardcore%20Ultimatum/poyB5DZt0
> Fix: updated conquerors efficiencys reservation mod

- src/Data/Skills/act_int.lua
- src/Export/Skills/act_int.txt
fixes #2688 
radius 18 -> 22 in 3.11
https://www.pathofexile.com/forum/view-thread/2873739
> Fix: changed armabrand radius to newest value

- src/Data/Skills/act_int.lua
- src/Export/Skills/act_int.txt
Fix stat for anomalous gem variant as named changed
> Anomalous Zealotry Fix

- src/Classes/ImportTab.lua
* added website selection dropdown to the import popup
* added support for Ghostbin and Rentry.co import
> added support for pastebin alternative websites

- src/Modules/ConfigOptions.lua
Removed the same ActorCondition from Brittle as well even though it did work because it doesn't break it and I want consistency.
Fixes #2671
> Scorched now works when selected on config tab

- src/Data/SkillStatMap.lua
- src/Data/Skills/sup_dex.lua
- src/Export/Skills/sup_dex.txt
Technically, the wording on the quality mod implies I should use the `AtCloseRange` instead of a scaling melee proximity like the main stat.  This needs to be verified in game, most likely.
> Add support for Divergent Close Combat

- src/Data/Skills/other.lua
- src/Export/Skills/other.txt
- src/Modules/ModParser.lua
Also reorders the other.lua file to be in alphabetical order
> Add support for Gore Shockwave skill

- src/Data/Skills/spectre.lua
- src/Data/Spectres.lua
- src/Export/Minions/Spectres.txt
- src/Export/Skills/spectre.txt
New ultimatum spectre (popular request)
> Add Trial Galecaller spectre

- src/Modules/Build.lua
> Re-Adds separation of Minion and Player breakdown in stat comparison

- src/Modules/CalcPerform.lua
- src/Modules/ModParser.lua
The reservation mod got broken by reservations rewrite
> Fix The Coming Calamity forced reservation

- src/Data/SkillStatMap.lua
The change to make this "% reduced reservation" instead of "mana reservation" broke this alternate quality.
I've added this mod to the list so it's handled properly.
> Fix alternative quality for Precision

- src/Data/ModCache.lua
- src/Data/Skills/minion.lua
- src/Export/Skills/minion.txt
- src/Modules/ModParser.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/2714
> Implement Replica Siegebreaker burning ground

- src/Data/Skills/act_str.lua
- src/Export/Skills/act_str.txt
taken from: https://www.pathofexile.com/forum/view-thread/3130696/page/1#p24135175
> Added missing pride aura radius

- .github/workflows/beta.yml
- .github/workflows/release.yml
- src/Modules/Main.lua
This doesn't automatically check for an update, but I think that's fine, people can check for one manually, and it will only be the first time they check the box
> Implement a beta testing branch and weekly merge from dev

- src/Modules/ConfigOptions.lua
- src/Modules/ModParser.lua
fixes #2696 
Once something is equipped/skilled with 'if you spent life recently', it adds a checkbox to trigger that condition on/off
For a test i created a fake jewel with the exact same stats as the 'Blood Artist' notable, leaving out the condition.
(with condition checked)
Jewel
Test-PoB
`eNrtPWlv20iWn0e_gjCwi11EcepgHcwmu_AVxz1x4lhJ3D1fGkWyaLFNkQpJ2VYG89_3FamDlEilrGSmscBOD2KZevXq3Ucd9Kv_eZwkzr3OizhLXx_gQ3Tg6DTIwji9fX3w-dOb5_Lgf_578OpKleMP0fEsTsw3_z34y6vqs5Poe528PvDogVOq_FaXX5ao6O-AaqrScqyz9FL9keXnWfj64H2W6gPHV2kYl68PPqi7AydIVFG8VxP9-mAUwNgDRxWBTsOT9fOj6gEgO3AmKk5HWXCny_M8m02B5gPnPtYPl1kIgBeXVx-uPzUmjtPmxED4X15dJWqu81GpSqeAfwA78K9u9dsY0N-rZAZ4pHSpOJQYCXLwYueoUzWBf58ycDTVOlwNwIeCCvavhr3K9VkU6aCM7_VJHpcnY5UGay5o37inwl7OkjKeJrHOG4T1UvV2CzlGqA_4U1aq5PRqtIZllHN0yD2OCf9njMrW9kEYcgk_ZBR5nEncN- …
> Adds: functionality for blood artist

- src/Data/Uniques/ring.lua
confirmed with: https://www.pathofexile.com/trade/search/Hardcore%20Ultimatum/qmWq9Hg
> cosmetic change to ngamahus sign, fixes #2838

- src/Data/Skills/act_str.lua
- src/Export/Skills/act_str.txt
- src/Modules/CalcOffence.lua
The breakdown for the added life cost isn't in there, but this seems to work.  There might be a better way to implement this, just hacked it together quick over lunch.
> Fix support for Petrified Blood

- src/Data/Skills/act_str.lua
- src/Export/Skills/act_str.txt
> Fix Anomalous Chain Hook

- src/Modules/ModParser.lua
Solves #2750 
I'm hoping this doesn't break any other parsing, but it follows the way other mods of this type are done, so it should be fine?
> Parse Increased Chaos Damage Over Time Mod found on weapons (#2750)

- src/Modules/ModParser.lua
- src/Modules/ModTools.lua
This might be able to be made a generic replacement line for all of the preceding lines, too
> Fix parsing for Sacrificial Garb implicit

- src/Data/Skills/other.lua
- src/Export/Skills/other.txt
- src/Modules/ModParser.lua
Add support for Fiery Impact from Heist Experimented Mace
> Fiery Impact

- src/Data/Uniques/Special/New.lua
- src/Data/Uniques/amulet.lua
- src/Data/Uniques/body.lua
- src/Data/Uniques/flask.lua
- src/Data/Uniques/gloves.lua
- src/Data/Uniques/helmet.lua
- src/Data/Uniques/jewel.lua
- src/Data/Uniques/mace.lua
- src/Data/Uniques/ring.lua
- src/Data/Uniques/staff.lua
- src/Modules/ModParser.lua
Ward base types don't exist yet, but they also don't break anything, either.  The only unique that needs some more work is Cinderswallow's Urn
> 3.15 uniques

- src/Data/Bases/flask.lua
Only affects flask implicits, charges and durations.
Manual changes.
Only if it's not much trouble and you feel like it's a nice addition before we get these values extracted from ggpk.
> Add 3.15 flask changes

- src/Data/Skills/act_str.lua
- src/Export/Skills/act_str.txt
Fix Anomalous Pride quality didn't increase "chance to bleed".
> Fix Anomalous Pride quality didn't increase "chance to bleed".

- src/Data/Uniques/body.lua
https://www.pathofexile.com/trade/search/Expedition/zb5Qmh4
> updated dendrobate with new gem name

- src/Data/Skills/act_int.lua
- src/Export/Skills/act_int.txt
> Fix Voltaxic Burst enchant

- src/Data/Uniques/gloves.lua
> Update Oskarm's chaos resist

- src/Modules/ConfigOptions.lua
Values are based off of values from Poe.db
> Update Ailment threshold values

- src/Data/Skills/act_dex.lua
- src/Export/Skills/act_dex.txt
From https://old.reddit.com/r/PathOfExileBuilds/comments/otmzrz/esc_my_level_91_explosive_concoction_pathfinder/h7126fw/?context=3
> Add radius to Explosive Concoction

- src/Modules/Build.lua
> Fix error when Main Skill is not-minion but Minion is in FullDPS

- src/Modules/ModParser.lua
Added cold damage over time (non multiplier version) to the mod parser to fix  https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/3093
> A cold damage over time stat to modparser

- src/Classes/PassiveTreeView.lua
> Stop keystones from being edited with timeless jewels

- src/Modules/ModParser.lua
`35% increased Projectile Damage with Hits against nearby Enemies`
> Added full support for Eye To Eye cluster Notable

- src/Modules/ModParser.lua
Adds support for the `all damage from hits with this weapon can poison` and `attack critical strikes ignore enemy monster elemental resistances` mods
> Add support for new base type implicits

- src/Modules/Build.lua
> Add space between similar stat groups.

- src/Data/StatDescriptions/skill_stat_descriptions.lua
- src/Export/Scripts/statdesc.lua
This change made some other changes to "No Physical Damage".  I don't know what skills/items use this wording so I'm not sure how to test it.
> Fix exporter for explosive concoction

- src/Data/Uniques/flask.lua
https://www.pathofexile.com/trade/search/Expedition/VLblTp
> Restoring resistance modifier on divination distillate, fixes #3141

- src/Modules/ConfigOptions.lua
This change adds a configuration option for minions to have onslaught and unholy might. First time PR (to any open source project) with guidance from LocalIdentity. Inspired by https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/3050 Any and all feedback welcome.
> Minion Onslaught configuration toggle.

- src/Data/Skills/spectre.lua
- src/Data/Spectres.lua
- src/Export/Minions/Spectres.txt
- src/Export/Skills/spectre.txt
> Add Demon Harpy spectre

- src/Data/Skills/spectre.lua
- src/Data/Spectres.lua
- src/Export/Minions/Spectres.txt
- src/Export/Skills/spectre.txt
> Add Pale Angel spectre

- src/Data/Skills/spectre.lua
- src/Data/Spectres.lua
- src/Export/Minions/Spectres.txt
- src/Export/Skills/spectre.txt
scourge spectre
Fixes # .
-
-
-
> Add Demon Herder spectre

- src/Data/Skills/sup_str.lua
- src/Export/Skills/sup_str.txt
Multistrike was not applying its damage on repeats bonus to Ailments like it should have been. It was also not applying to Decay when it should have been
Closes #2847
> Fix Multistrike not applying its damage multiplier to Ailments

- src/Data/Skills/spectre.lua
- src/Data/Spectres.lua
- src/Export/Minions/Spectres.txt
- src/Export/Skills/spectre.txt
Does not add support for the web debuff
> Add Pale Seraphim Spectre

- src/Data/Skills/act_str.lua
- src/Export/Skills/act_str.txt
- src/Modules/ConfigOptions.lua
- src/Modules/ModParser.lua
Champion's Inspirational node's life regen per banner stage mod was unsupported. This adds support using the existing config options.
- Add a banner skill
- Allocate the Champion's "Inspirational" node
- Enable the config option "Is Banner Planted?"
- Confirm life regen is added and scaled with banner stages
```
eNrNWlt32jgQfm5_hQ_PLWBuTXvI9pCEpOwJLQ1pu_vUI-wBtBGSa8uk9NfvSDbgUJyM1d092wdqzDe3T6PRjJ3-2-8r4a0hTriSpzW_3qx5IAMVcrk4rX26vXx5Unv72_P-hOnlh_lZyoX55bfnz_r22hOwBoFyNU-zeAH681ZT-ytqipjUS1ByzP5S8ZUKT2vvlYSaN2My5Hr7LRAsSd6zFZzWLlIQPNE1jyUByPB8_8v5kq0i1FzzVozLqQruQF_FKo2s8TWH-7EKETcaTz7c3BZMc1k0jZ4_608E20A81Ux7CX6c1gZIAFvABVvhJ2pjIkVVnbrfbZ90etlnq9Y4LjyNAMKdULP--r8DTmIYzucQaL6G85hrJEkG-wCaZXJVseNUaB4JDvEO79e7ZRLvflLuN0vV3yrNxMVkusO266_2pPvdf0dO6acD_8L18kzgSjhYMbKjheQaHIUniidK_kJ8RdHytVWrGZ …
```
> Add support for Champion's Inspirational banner life regen

- src/Modules/CalcPerform.lua
Fixes issues identified in:
https://www.reddit.com/r/pathofexile/comments/qu61fe/tifu_by_writing_a_build_guide_and_not_knowing_how/
Tested PoB:
https://pastebin.com/FazRKWGC (Corruption notable should have no DPS increase - whereas it does before code change).
> fix: Increased Wither Effect does not affect minions

- src/Modules/CalcPerform.lua
> fix: Fixes possible crash with FullDPS and disabled socket groups

- src/Modules/CalcDefence.lua
- src/Modules/CalcSections.lua
- src/Modules/ModParser.lua
Fixes multiple "chance to defend with X% armour" stacking, now only uses largest.
> fix: stacking Armour Masteries only taking largest value

- src/Data/Skills/act_int.lua
- src/Export/Skills/act_int.txt
The increased spell damage buff was not applying globally like it should have
> Fix Phantasmal Sigil of Power spell damage buff not working

- src/Data/Skills/sup_int.lua
- src/Export/Skills/sup_int.txt
An over-sight from 3 month ago.
> fix: removed a StatMap entry that doesn't exist anymore

- src/Classes/Item.lua
- src/Classes/ItemsTab.lua
Attribute to Tom Clancy is Dead
> Move delve mods to "Add modifier..." menu while crafting items

- src/Classes/Item.lua
Fixes certain attributes and missing modifiers appear on items that are copied from trade site and pasted into PoB. Necessary for PoB Trading future PR which utilizes that feature.
Below you see three "before" and "after" screenshots of the same set of items to showcase issues being resolved while for the complicated cases with many `:` still being appropriate.
> fix: implemented better raw string item parsing

- src/Modules/Calcs.lua
Fixes #3892.
Accounts for instance of culling from skills/gems/ascendancies. Implemented as basically `combinedDPS * (cullingMultiplier - 1)`
> Fix issue where culling DPS wasn't factored in for Full DPS totals

- src/Modules/ConfigOptions.lua
> Add Lifetap's "20% increased Life Recovery from Flasks" modifier

- src/Data/Skills/act_str.lua
- src/Export/Skills/act_str.txt
> Add support for Anomalous Vitality

- src/Classes/ModStore.lua
- src/Data/Uniques/Special/New.lua
- src/Modules/ModParser.lua
> feat: add support for Triple Elemental Damage

- spec/System/TestSkills_spec.lua
- src/Classes/SkillsTab.lua
- src/Modules/CalcActiveSkill.lua
- src/Modules/CalcTools.lua
Fixes #3957 .
Envy linked to Awakened Generosity would revert to the level 1 version when Generosity was leveled to 5
- Used build in issue, verified Envy no longer loses damage
```bash
eNrtW21z2rgW_lx-hYaZ3tk7twFsY5Jwk90hhCTMkJSFpHvvp45iBGgjW9SWSdid_vd7JNlgwIBwu71ftp3ZGvs5LzpvOkf2Xvzy5jM0J2FEeXBZtiq1MiKBx0c0mFyWnx5vTs7Kv_xcuuhjMf04voopk09-Lr27UNeIkTlhQFdGAocTIj6lnJzPwGmGAzElPLjHv_Pwlo8uyw88IGX0jIMRFekvj-EoesA-uSwPPSAuIxx5JBi1V_c10Mc0GHLvhYjbkMczJXZOyes9HwGme9__OHjMCKVBVijo_O6iz_CChEOBBYrgP5fllifonAAU5PaoTwVwxCwGdk6jXN1BA-bCE3KXAdd2YYczQkZLmFWx3V3Ifkg64zFR-rRDKtpTHHjksIRjsfcxE3TGKAkzau3U6pELzK77w8O8NZIb2OQ3KqZXDOxixFeiu5OACmIM73Ma8eAorY3Abe4_08BQ73sc4DaPDOzRo2NihuwMzXADCE8zpNSyT0JIN2Gu7FEEiYQh8Tik9DEyjiHJrKOYsAKUnWERggKChmKVq_Zup5MvWeDp6S7gNXkzY5cFnp7vAnYDYcYuC7Rcd7d6cy7UNmDiuiWqsa8Ge02J7Q …
```
> Fix skills from items getting +1 level from Awakened gems

- src/Classes/PassiveTreeView.lua
Fixes #3559.
An edge case that crashes PoB
- Unable to replicate
-
-
> Check clampFactor for an edge case causing PoB to crash

- src/Data/Uniques/amulet.lua
- src/Data/Uniques/axe.lua
- src/Data/Uniques/body.lua
- src/Data/Uniques/gloves.lua
- src/Data/Uniques/jewel.lua
- src/Data/Uniques/mace.lua
- src/Data/Uniques/sword.lua
Fixes #3682
as well as the item flesh and spirit gauntlets which had the same issue
Extra word, Maximum, removed from certain unique items
- Search item in POB
- make sure the text is correct
> On Kill wording fix

- src/Data/Skills/act_dex.lua
- src/Data/Skills/other.lua
- src/Export/Skills/act_dex.txt
- src/Export/Skills/other.txt
- src/Modules/ConfigOptions.lua
Fixes #543 .
Animate weapon in the configuration tab had a maximum of 50 instead of depending on the gem level.  Since most people will only ever have maximum animated weapons, I've removed the config value
- Tested with chains of command, as that's the only thing that cares about the number of animated weapons
```bash
eNrtPWtz2siyn5dfoXLV3spWwNboLd_knMJvJ34F_NjkS0qgMcgWEtYDG2_5v5-eGQkkkMSAnWTPHjZVXpC6e3p6-j0j8eHfTwNXGOEgdHzv4wbaFDcE7HV92_F6HzeuLg8axsa__1X7cGFF_fPbndhxyZ1_1X77QD8LLh5h9-OGCWiRFfRwdJ2Skr_DtaHlRX3se6fWnR8c-vbHjTPfwxtCx_JsJ0q_dV0rDM-sAf64ceNE3f6GYIVd7Nm70-tnuBv4A8vr4mBDGFiO1_a79zg6DPx4CMNvCCMHP576NoAen16cty4zYztedmzg_bcPF641xkE7siIhhD8fN5ogAquHj5wISFluDHTEja1K2D1rAH8Xg7eHGNsTMLRpqD8T8iLA-7e3uBs5I7wbONFunwhxMdfLwp7GbuQMXYesz4StUq6O5ogjsZT8pR9Z7t5FezEjy0L6HKsNGtnfcUHcXHQJ9HHPcyL …
```
> Get maximum animated weapon from gem level instead of configuration

- src/Data/Skills/act_dex.lua
- src/Data/Skills/act_int.lua
- src/Data/Skills/act_str.lua
- src/Data/Skills/spectre.lua
- src/Data/Skills/sup_dex.lua
- src/Export/Skills/act_dex.txt
- src/Export/Skills/act_int.txt
- src/Export/Skills/act_str.txt
- src/Export/Skills/spectre.txt
- src/Export/Skills/sup_dex.txt
- src/Modules/CalcDefence.lua
- src/Modules/CalcPerform.lua
- src/Modules/ConfigOptions.lua
DUMMY mods not needed, similar solution to #3245 
- Tested each mod to make sure their config option still showed up
- Rallying Cry's NearbyAlly mod had to stay due to it being a multiplier
- The Warlord's Mark from Spectres doesn't make the Rage config option show either way, so that will need to be revisited
```bash
eNrlHG1z2jj6c_kVGmb2pp3LC7aBkFyyN4S8cRtaFtL29tOOsAVoIywqyxB2p__9Hsk2GDAgu5m73V4zkxj7edPz_siil_98mTA0IyKg3L8qWyeVMiK-yz3qj67KH5_ujhvlf_5YuuxiOf4wvA4pU09-LL251NeIkRlhgFdGEosRkZ8SSs6vQGmKfTkm3O_g37i4595V-T33SRkNsO9RmXxyGQ6C93hCrsr9Mfb4vIxw4BLfa60eNIMArqlfRhNM_T53n4m8FzycAm9gNKNk3uEeALY73Q-9pxRr6qdZg-RvLvtT4kpBEIW7HSKxhyU-7XA_kCD96bUWLvnbIYyQz1gwLrygg8VzB4esfKrpdBleENGXWKIAfoGUrqQzAixBBY90QiVIhlkIYtk7UUD3eEQeUrCVA7A3eAK_D4PDMom3BLNOrLN69axSazRsp-b875G6gtwOh0SrrCWobI2x7xosKy9sJ2SS …
```
> Remove Dummy skill mods

- src/Modules/ModParser.lua
Other mods that provide the same impact exist under different conditions, so easy fix.
> feat: add support for Adder's Touch modifier

- src/Classes/Item.lua
- src/Classes/ItemsTab.lua
- src/Modules/ModParser.lua
Fixes #3866 
Adds support for additional life recovery if used while not on full life flask mods
- Confirm full life config unchecked
- Add one of each mod tier to a flask
- Verify effective flask stats appear and calculate correctly
- Check several combinations of prefixes for instant recovery and recovery/duration modifiers
- Confirm additional recovery not included while full life config checked
<pre>eNq9Wt9z4jgSfh7-ChVVc28TAgY2myO7RQjJUBVmOJyZuXtKKbYAbWSJteUkzNX979uSDZgEQ1t7lTxkjPn6h_prqbuV6f3-EgnyxOKEK3lRb56c1gmTgQq5nF_Uv91dfzqr__5brTehevF1dplyYb75rfahZ5-JYE9MXNS7nTrRNJ4z_X2tyrsHVUsq9YIpOaZ_qPhGhRf1L0qyOnmgMuR6_SkQNEm-0Ihd1P0AhOuEJgGT4WD7PgNGlEtfBY9M38QqXYK_dfLE2fNYhYAZjSdfp3cFo1wWjYLTH3oTQVcs9jXVJIFfF_U-rJ3O2RWN4DdooyIFVacnzXa9sV_CXzIWbpDNk1YZcBKz4WzGAs2f2CDmerCgMijYKJOrih2nQvOl4Cwue …
> Add support for additional life recovery flask mods

- CONTRIBUTING.md
- src/Classes/ImportTab.lua
Fixes # .
Update Import/Export Build tab
- change Share functionality of PoB build codes to be a dropdown of export websites, defaulting to Pastebin.com and including the brand-new, lovely pobb.in
-- Import/create build
- Generate code
- Share
- Verify Pastebin is defaulted and pastebin link created and valid
-- Import/create build
- Generate code
- Select pobb.in
- Share
- Verify pobbin link created and valid
```bash
eNrtfetz2kry9ufDX6Gfq3YrKYOj-yWb7BZgbGMDvoDtOF9cAgaQERKWBJicyv_-ds8IkEACmfgcb-2b7J4ExFy7e55-em768p-Xkc1NiedbrvP1QDjiDzjidNyu5fS_Hty2Tgr6wX_-nftyZQaDy15pYtn4y79zf3yhnzmbTIn99cBQD7jA9PokuFsUJT1CUWPTCQbEdermk-udut2vB60BKXmWQy6gmAOubTpdK_h60HAdcsB1bNP3G-aIfD24t4LO4IAz_Q5xuuXV88tOZ2IHlh8ccCPTcppuZ0iCU8-djKHxB9zUIrO624WE1frV5U0r0gLLCVtwanqT4cB0DqAXf3y5ss058ZqBGXA-_PX1oAjCMPvk2BzB31 …
```
> Add build code export to pobb.in

- src/Modules/CalcPerform.lua
- src/Modules/CalcSections.lua
- src/Modules/ModParser.lua
`Skills Supported by Nightblade have 40% increased Effect of Elusive`
> Feat: Add Support for Claw Mastery modifier

- src/Classes/Item.lua
- src/Classes/ItemsTab.lua
- src/Data/Uniques/Special/Generated.lua
- src/Data/Uniques/body.lua
- src/Data/Uniques/staff.lua
- src/Data/Uniques/sword.lua
Fixes https://feathub.com/LocalIdentity/PathOfBuilding/+32
Veiled uniques have been in a half-implemented state for a few years in PoB.  The items most affected include Paradoxica, Replica Paradoxica (which isn't in PoB at all), Cane of Kulemak, and The Queen's Hunger.
This PR adds support for:
- Paradoxica, Replica Paradoxica, Cane of Kulemak, and The Queen's Hunger
- Veiled mods on uniques (sourced from the internal mod data)
- 2 additional alt variant slots to support Replica Paradoxica
A note on The Queen's Hunger.  There was a legacy variant implemented on it for 3.8.0.  That mod was not accurate (even for the patch it was supposed to originate from).  To cut down on complexity, I chose to leave it out in the new version.
- Added new items to test builds
- Verified dropdowns work …
> Add support for several veiled uniques: Paradoxica, Replica Paradoxica, Cane of Kulemak, and The Queen's Hunger

- src/Modules/CalcOffence.lua
- src/Modules/Calcs.lua
> fix: Mirage Archer culling DPS

- src/Classes/ItemListControl.lua
Co-Authored-By: @pHiney 
This is based on #4064.
Abyssal Jewels being deleted when 'Delete Unused' button was used.
* Open a build
* Add a Stygian Belt
* Add an Abyssal Jewel and socket it
* Add another Abyssal Jewel and leave unsocketed
* Select 'Delete Unused', only the unused Jewel will be deleted
https://pastebin.com/RWwqjuxe
> Properly detect equipped Abyssal Jewels when Deleting Unused Items

- src/Modules/Build.lua
- src/Modules/Main.lua
Fixes #4080.
Add option to hide Warnings.
Tested locally OK.
> Add option to hide Warnings

- spec/System/TestAttacks_spec.lua
- src/Modules/CalcTools.lua
Fixes #4084 .
"1% increased spell damage per 16 intelligence" wasn't being applied to attacks when converted to attack damage via the wand mastery node.  Note that this simply restores functionality that was missed by a refactor in #3335
```bash
eNrtPWlv27qyn69_hRDgPJyicap9yWvvhbOnJ07TOF2_BLJNx2pkydWSpQf5729ISha1knZy7obXAq1tzQw5C2eGw0Vv__Gw8KU7FMVeGLzbUnbkLQkFk3DqBTfvtj5dHfXtrX_8vff2wk3mH2Z7qefjJ3_v_e0t-Sz56A75gCcDXuJGNyj5nNPSruG3pRskcxQGQ_dHGB2H03dbo9B3Iy_eksZuMPWSd1vnYYC2pInvxvG5u0Dvtg5S5HtxsiW58QQF0_3iyf7cXSyB-Ja0cL1gFE5uUXIchekSerAl3XnofhhOAe50ePHh8opp3Quy1o-jNJnfpv4WsPC3txe--4iiUeImUgz_vNsagCTcG3TgLuBfoOj6KZAzFc02d8zsj7X1phl5tERoukJSdwxddjTLaAO_iNDhbIYmiXeH9iMvAeaCSdGo3Ia3Luww9RNv6Xso4sOf1EhjzbYAX4WJ6x9cjApY21Isw9xRuzHChN-RL14y3_NBnmvRx1inN4GXoLXRLkIvDoONuGGR2jWR-j6MHBZWlS3HUncchf5pxQ …
```
> Fix issue where certain modifiers weren't being converted properly (e.g. Battlemage)

- src/Modules/CalcDefence.lua
restrict life recoverable to lowlife threshold if "are you always on lowlife" is configured, as well as fix petrified blood with lowlife condition (if set outside of config, like Coward's Legacy)
> Implement Life Recoverable

- src/Modules/CalcPerform.lua
> Fix chilling areas not applying Bonechill

- src/Data/Skills/act_str.lua
- src/Export/Skills/act_str.txt
> Absolution Quality is now a minion mod

- spec/TestBuilds/3.13/Dual Savior.lua
- spec/TestBuilds/3.13/Dual Savior.xml
- spec/TestBuilds/3.13/Dual Wield Cospris CoC.lua
- spec/TestBuilds/3.13/Dual Wield Cospris CoC.xml
- spec/TestBuilds/3.13/Generals Perforate Zerker.lua
- spec/TestBuilds/3.13/Generals Perforate Zerker.xml
- spec/TestBuilds/3.13/Mirage Archer Toxic Rain.lua
- spec/TestBuilds/3.13/Mirage Archer Toxic Rain.xml
Minor spelling correction.
* Loaded builds into POBC
* Crossed fingers
> fix "maxmium" in test builds

- CHANGELOG.md
- changelog.txt
- docs/rundown.md
Minor spelling corrections
- Read the docs.
- Read the docs again.
> minor spelling corrections

- src/Data/Skills/other.lua
- src/Export/Skills/other.txt
Fixes #4235.
https://pobb.in/vi8OImjNh7cB
> Add missing spell flag to triggered spells from Atziri's Rule

- src/Classes/ItemsTab.lua
- src/Modules/CalcActiveSkill.lua
Fixes #4205, plus one additional error found while testing that wasn't reported in that issue.
https://pastebin.com/SZhtycap
No errors occur.
> Fix two nil errors related to equipped items

- src/Data/Uniques/helmet.lua
- src/Data/Uniques/shield.lua
- src/Modules/CalcPerform.lua
Fixes #4178
Fixed the immediate crash, and created variants for old versions of the uniques that had Mortal Conviction
- Hovered over Tukohama's shields, and Malachai's helmets
-
-
```bash
eNq9W21z2rgW_lx-hYaZvdPOBvAbBnKT3SGEJMwNaQppe_dTR7EFaCNb1C9J2Z3-93sk2cG8C7d3k5nE2M85Rzp6zous5Oz3bwFDzySKKQ_Pq2bdqCISetyn4fS8-vHhqtau_v5b5eweJ7P3k4uUMvHkt8qbM3mNGHkmDOSqKMHRlCSfck32F9A0x2EyIzwc4j95dM398-odD0kVPeLQp0n-yWM4ju9wQM6rYw-EqwjHHgn93vK-AgaYhmPuPZHkOuLpXJp9puRlyH3ADIb370cPBaM0LBqFMb85u2d4QaJxghMUw4_zatdL6DMBKNi9pQFNQCNmKRG6GztEwFt4Sm4KWGMXdjwnxF_C6qbrNg0j-9naJXUfkf5kQuTQehFNejMceuSwtWOxw5QldM4oiZazrjd3STzwBLPL-_Fh3QrJNfzzmSazCwY-0tIr0INpSBOiDb_nNObhUaPWAvdSxiAQ9LA8eKSh5hx7nDOfv4SvSLduGO4u9BCHuMdjDU_f0glZQTadXdD-WE_lCKJADymGeU8iCOpEf7RHCWQWxsTjkDiOsXGMSGEe5YyVkOyPywiUMDROlmnA2ZkFRuRrEWg2O7uQl-TbK8w …
```
> Fix crash caused by Mortal Conviction still appearing on some uniques

- src/Modules/ModParser.lua
> Fix parsing of Soul of Abberath self Ignite duration

- RELEASE.md
- fix_ascendancy_positions.py
- tests/test_fix_ascendancy_positions.py
Refactor of the ascendancy position fixer script:
* more idiomatic and easier to maintain
* simpler release procedure for skill trees
Run `pytest`
> Refactor ascendancy fixer

- src/Modules/ModParser.lua
> Add support for reduced mana cost of attacks

- src/Modules/ModParser.lua
Fixes #3698.
https://pobb.in/kszoYPihmjqi
> Add support for Spellslinger reservation enchant

- src/Modules/ModParser.lua
Fixes #4324.
```shell
eNrNfW1z27bS6OejX8HxTO-0Y8XBO8Hc5DxjO7bjJk5cK6mb86UDkqDNhCIdkrLjdPrf7wKkJFIiZVpJ73namdYSFwtg33exoJ7_z9dp4tzqvIiz9MUO3kM7jk6DLIzTqxc7H94fP5E7__Pv0fNzVV6_iw5mcWKe_Hv0r-f2byfRtzp5sePxHadU-ZUuf5-jon8CqhuVltc6S8_Upyw_ycIXO2-zVO84vkrDuJx_ChJVFG_VVL_YuVDplc53HFUEOg0Pmw_i0DyYqjidZMFnXZ7k2ezmxY7YcW5jfXeWhQB1enb-7uJ9Y944bc4L6_7X8_NE3et8UqrSKeA_L3b2YfvqSr9UU_gvYFPJDFBRIinme4x4xGPI23naPXhyo3W4GCQBnvM-2Fdx2QZnewQTtxf-PNdHUaSDMr7Vh3lcHl6rNFiukHl7DAvZN3q7EWezpIxvktjQerFK6W3Y0socGKE-4PdZqZKX55MlLAUaY7QnCXO5dDePy8rFuN4ZLuPy-iABEm8xy-lVGpe6NRCDABDhMo9x5IpNk3YMppIRIvaQRwinZNPg8ywusvQ7CLPFog9nSQKa3BzpYk-gPcQ9yZDr9UtJNvXjdIXEjAssxR7mBHmsb-R-rtW7qBLpCxXGs6Kx4b5BZypVh1lRNgSsD_RNHOkWaC_k0WQY3AVYhGGQZpnnOgerVQ4bYBb7qAH1DBMdZGAZHzPHY4Y09rHdZFuMPJpsM2CLiSZl3hDZPqiX-mvDC_Sai7QcgOvdNI0bQo56VflCf2 …
```
> Add support for "for Attack Damage" modifiers

- src/Modules/ConfigOptions.lua
- src/Modules/ModParser.lua
Adds parsing for action speed
Also adds parsing for all the mods that rely on the presence of a a unique enemy or pinnacle boss
Only made Shaper/Sirus count as Pinnacle bosses
> Eldritch Mod Parsing

- .github/ISSUE_TEMPLATE/bug_report.yaml
People seem to be confused about what a "build code" is
> Clarify build code section in bug report template

- src/Classes/ImportTab.lua
> Change import from website to be 1 click operation

- src/Modules/ModParser.lua
The local weapon mod was not previously parsed
> Add support for Weapon local Overwhelm mod

- src/Data/Uniques/boots.lua
Fixes #4506  .
Level requirement was wrong
> Legacy of Fury level requirement

- src/Data/Skills/act_str.lua
- src/Export/Skills/act_str.txt
Fixes #4343.
Chain Hook was granting +5 Radius per 1 Rage instead of the intended +1 Radius per 5 Rage.
```shell
eNqtWltz4joSfh5-hcuvWwkYCJAUOacIIQlVIcPizMzu05SwG9CJbDG2TML59duSDDgZHGSdTaoSX_r6dau7Jej_-RYxZwNJSnl87XrnDdeBOOAhjZfX7rfnu7Oe--cftf6UiNXXxU1GmXzzR-1LX107DDbArt1LZBMkWYL4vhPV-onP1iQWK-DxhPzFk3seXrtPPAbXmZM4pGJ3FzCSpk8kgmvXD5DZdUgaQBwOD881YURo7PPgBcR9wrM12us6GwqvEx4izXgy_Tp7LiilcVEpGv2lP2VkC4kviHBS_HPtDtB3soRbEuFflEZYhqLa543GZavn9boXbv04o78GCPcM3nnX65SRThMYLRYQCLqBYULFcEXi4KCsVMURWu-89Sn5JGOCrhmFpMBSyvHwm_xmt4z2mQvCbqf-nrRz3ushSpfNy3KQNBMXe6ZGGeUPKlY3DCGtqkIyjpcxFWDDOeU05bGtW0W-Us-GGWO4ZsxoeTSncXUQBgmQrwudZDMS0iw9hL_ZLuOakJgMeXqITq-M8pEu4B1lqQcj34xuhsvNjFJaOYUEC4IwY5DGVmLINfgQcCw6VXRUYSn4YafMgnPk2zBYKPLFoeA0y4MOv4qEXqdVRnkLb2byioS90kwfx8JA3C1suFD955S7qgCMHqaFVdZqnl9cti-7jW6j5ZXCpCD …
```
> Fix Chain Hook Radius per Rage

- src/Data/Skills/sup_str.lua
- src/Export/Skills/sup_str.txt
Fixes #4421.
Cruelty Support grants more Damage to hits, and a buff based on the damage dealt that increases DoT damage. This buff is capped at 40%. Cruelty effect makes reaching that 40% cap easier, similar to how Shock behaves.
Currently in PoB the Cruelty Effect on the support gem scales the actual damage bonus Cruelty provides, bypassing the 40% cap entirely.
We do not currently support Cruelty Effect calculations anywhere in PoB (there is a simple override available under configuration) this PR simply fixes that "bypassing the cap" bug and doesn't change anything else.
```shell
eNqtWl132jgTvu7-Ch_fNwQMhOwhu4cQkrIntLyYtrtXPcIWoI1suZaclP3170i2wWFxGKvLReqPZ75HMyO5w99_RNx5pqlkIr5x2xeXrkPjQIQs3ty4n5f37wfu77_9MpwTtf20vs0Y129---Xd0Fw7nD5TDnSuo0i6oepLycn7BpwSEqstFfGM_C3SBxHeuB9FTF1nReKQqfIu4E …
```
> Fix incorrect Cruelty effect scaling

- src/Data/Skills/act_dex.lua
- src/Export/Skills/act_dex.txt
Fixes #2759 .
```bash
eNrVHNty2kj2OXxFF1XZylQA64KE8NqzhTF2mLETBpzMzr6k2lJjFOtCpJZtMpV_39PdEhJYgkZxbWXjVALi3O99JHzyryffQw8kit0wOG2qHaWJSGCHjhvcnTY_3ly0rea_fm2cTDBdfJifJa7HPvm18eqEv0YeeSAe4DURxdEdoZ8ySvpnoLTEAV2QMLjGX8LoMnROm-_DgDTRLQ4cl2bvbA_H8Xvsk9PmzAbkJsKxTQJnmF8XgD52g1lo3xN6GYXJ8rTZbaIHlzxehw7AjK8nH6Y3BaZuUGQKMr86mXh4RaIZxRTF8M9pcwCq4ztyjn34F6hhLwFSqqJana6mqXpXsSy1eVSOPFsS4uRIHbMSchKR0XxObOo-kGHk0uECB3bOz-xoVZiHQ18nHnWXnkuigmhGFca7Z-RVRakCvgkp9s4nsxzW1Psd0-ibugF2snbjhXSNV8nhT5cuzjwwaw0uDHd8F7iU1ESehG4cBj-gXxG1UsVh4nmQQ3KwoX_rBrWscY0DPAzj3OZmFeSVOycbkJXijGZycFNIJjlIJuWERJDuVA6BCXsQQsphRuwQSsohPA5BKehRj1kNzNGsDkINRjOal5KuXul08rUI2O9XAZ6TpzyY1V30ipD9ykgfB7kOvV3kioCqYVTL9xBS3of2GYbn_ejdZA0Z4KCyBSxWsWtj7xo_uX7iQ929wfckZ2L1qyPkbkEDKBlVqGYPmlX-U0Xnwo3ID5IYhp7zoyQWOIyraPTU6t7GEkXCWtCU7WMGOw7snO …
```
> Fix Vaal lightning strike projectiles not counting as projectiles

- docs/addingMods.md
- docs/modSyntax.md
Some links in /docs lead to nowhere and others used full paths.
> Docs - Fix dead links and refactor to use relative links

- src/Modules/CalcDefence.lua
- src/Modules/ModParser.lua
This mod comes from Nightgrip
https://pastebin.com/tPdaYNh3
> Add support for % of damage taken bypasses ward

- src/Modules/ConfigOptions.lua
- src/Modules/Main.lua
> Improve default item affix quality UI

- src/Classes/SkillsTab.lua
- src/Modules/CalcSetup.lua
> Fix Skill Set manage naming and remove socket group global variable in CalcSetup

- src/Modules/ConfigOptions.lua
- src/Modules/Data.lua
just minor cleanup to boss presets, 
round enemy chaos damage and move boss damage mults to data.bossSkills instead of just being random magic numbers
Ideally these would be generated from the gamefiles and would dynamically set the proper placeholders
> cleanup Boss Presets

- src/Modules/Build.lua
Update Build.lua :
* ascendencies -> ascendancies
* catched -> caught
* highestAtrribute -> highestAttribute
> fix spelling in Build.lua

- .github/ISSUE_TEMPLATE/bug_report.yaml
- .github/ISSUE_TEMPLATE/feature_request.yaml
- CHANGELOG.md
- changelog.txt
- src/Classes/ModDB.lua
- src/Classes/PassiveSpec.lua
- src/Modules/Build.lua
- src/Modules/CalcDefence.lua
- src/Modules/CalcOffence.lua
- src/Modules/CalcSections.lua
- src/Modules/ConfigOptions.lua
* Fixes mostly comments, with some plain-text files, tool-tips, and breakdown text.
* nothing should touch sensitive code.
> fixes various typos in "safe" text

- src/Modules/ModParser.lua
> Support for non critical strikes deal less damage

- src/Modules/ConfigOptions.lua
Traps and mines Tvalues are supported, but could be modified
> Fix spell and correct tooltip

- src/Data/Uniques/ring.lua
> Fix spelling in ring.lua

- src/Modules/Data.lua
> [Kalandra] Update brittle values

- src/Modules/ModParser.lua
> Add support for minions have unholy might

- src/Data/Uniques/amulet.lua
- src/Data/Uniques/body.lua
- src/Data/Uniques/boots.lua
- src/Data/Uniques/ring.lua
- src/Data/Uniques/shield.lua
- src/Modules/ModParser.lua
Blackheart - Perfect
Blood of Corruption  - Perfect (Unsure if we want to keep legacy item levels I don't think so)
Bramblejack  - Perfect
Briskwrap - Perfect
Bronn's Lithe  - Perfect
Chalice of Horrors - Decay might be in other spot.
Cloak of Flame  - Perfect
Corpsewalker - Corpse mods might be in different order
The Covenant  - mana to life mod order might be different (same behaviour as petrified blood)
> [Kalandra] Update batch 3 of Uniques

- src/Modules/ModParser.lua
> [Kalandra] Support for inverted reflection stats

- src/Modules/CalcOffence.lua
- src/Modules/CalcPerform.lua
- src/Modules/ModParser.lua
Adds a "BASE" mod for max shock. It still uses the "OVERRIDE" if one is present to retain backwards compatibility.
> [Kalandra] Add support for stacking max shock

- src/Data/Uniques/amulet.lua
> [Kalandra] nerf to omniscience

- src/Data/Uniques/jewel.lua
> [Kalandra] add minus max res for 3.19 melding of the flesh

- src/Data/Uniques/belt.lua
- src/Data/Uniques/gloves.lua
These changes come from the "Changes since the original post was made" section: https://www.pathofexile.com/forum/view-thread/3293287
> Update unique changes from patch note updates

- src/Data/Uniques/jewel.lua
> Add Keystone names to Timeless jewel variants

- src/Modules/Build.lua
Reducing pvp hit taken should be green (good) for reduction, instead of red
> PvP Hit Taken Colour for changes was inverted

- src/Data/Uniques/Special/New.lua
- src/Modules/CalcDefence.lua
- src/Modules/CalcSections.lua
- src/Modules/ModParser.lua
> Add The Poised Prism and Elevore

- src/Modules/ConfigOptions.lua
Change the wording and fix the capitalisation
> Update Heartstopper config

- src/Classes/Item.lua
- src/Data/Uniques/jewel.lua
- src/Modules/ModParser.lua
Adds support for frenzy, power, life and ailment Grand Spectrum
https://pobb.in/inf9BcVDcjdS
> Add new Grand Spectrum mods and change Grand Spectrum parsing to generic one

- src/Modules/CalcSections.lua
> Remove Main Hand background color from global Ignite Dot Multi section

- src/Data/Uniques/gloves.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4856
I missed the buff to life.
> Fix missing life on Demon Stitcher

- src/Modules/CalcOffence.lua
> Fix caustic ground breakdown

- src/Data/Skills/act_dex.lua
- src/Data/Skills/act_int.lua
- src/Export/Skills/act_dex.txt
- src/Export/Skills/act_int.txt
Also adds radius values for Lightning Conduit, Galvanic Field and Alchemist's Mark
> Fix Lightning Conduit and Galvanic Field scaling with area damage

- src/Classes/ItemsTab.lua
ItemsTab.lua line 481 change might have fixed a bug too (bonus!)
> fix spelling in ItemsTab.lua

- src/Classes/ItemDBControl.lua
- src/Data/Uniques/amulet.lua
- src/Data/Uniques/axe.lua
- src/Data/Uniques/belt.lua
- src/Data/Uniques/bow.lua
- src/Data/Uniques/quiver.lua
- src/Data/Uniques/ring.lua
- src/Data/Uniques/shield.lua
- src/Data/Uniques/staff.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4913.
Changing between the modes hides and shows the uniques correctly.
> Add button to filter unique source

- src/Modules/ModParser.lua
Fixes issue dicovered by @Vilsol in discord.
"tag" being used instead of "tagList" causing only the first tag to be added.
> Fix "tag" being used in place of "tagList" causing only the first tag to be added

- src/Modules/ModParser.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5033
Missing rage field
> Add rage generation flag to chains of empacipation

- CONTRIBUTING.md
- Mention compiling emmyLua form source
- Mention excluding directories from emmyLua language server
- Mention misc tips
- Mention running with wine
- Mention forcing Dev mode off to debug upgrade system
- Mention that emmyLua requires java
> Documentation - Add more tips to CONTRIBUTING.md

- src/Classes/PassiveTreeView.lua
Colors of rings were off when searching for nodes on the tree:
- Searched for nodes again to verify correct colors
- Opened tree in game to verify correct colors
```bash
eNrVfWtz4ziu6Of1r1Clam9119iJ3o_c7j3lvDOTdDJxuntmP0xKselYHVnySHKnM1v57xcg9aAelGQnc865uzuzsQSAJAiAAAhSH_7rx9KXvpMo9sLg446yK-9IJJiGMy94-Ljz-fZkZO_8178GH67dZHE1P1h7Pr751-AfH-jfkk--Ex_wZMBL3OiBJF8yWtodPFu5QbIgYXDpfguj03D2cediHbiRF-9I924w85KPO5_CgOxIU9-N40_uknzcuXGDBxLtSG48JcHssHiBnZh7wQxfLl0vmITTR5KcRuF6BV3Ykb575OkynAHk-eX11c0t17wXpM1PFu4jtL8DQ_jHh2vffSbRJHETKYZ_fdwZAyfcB3LkLuHfQND110BNUxTTsHYNRzEsWzV29pqRJytCZjmSouw6uqHoIujriBzP52SaeN_JYeQlhws3mBZt2iK8TWEv137irXwPmZZ1bdcRYZzViOPUCoBvw8T1j64nBaMsVbUcbdcwNd00lHa8MMnxhC189ZLFgQ9s3aIVxD1_CLyEbIF8HXpxGPCIhq6oqr4rq5qmOJrZgVgRIMNxFM3ZtQxDtjSrrcf1hnXTUgxZVXZtxdJsq4upJVTVcVRVtXdVQ4M_hG …
```
> Fix incorrect timeless jewel ring colors when searching a node on the passive tree

- src/Data/Skills/sup_str.lua
- src/Export/Skills/sup_str.txt
Divergent Fist of War was increasing stun threshold instead of decreasing it
- Create a build using Divergent Fist of War
- Note that it increases the stun threshold
```bash
eNq1W21z4jgS_jz8ChdVe1-uJrwF8nLJbpFAEqrCDAuZmbtPW8IWoB1ZYmw5GXbr_vt1SzY4BDk29s1UJcTqp1-lVqstrn776XPnmQYhk-K63jpp1h0qXOkxsbyuf3m6-3he_-3X2tWEqNXnxU3EOI78WvtwpT87nD5TDri6o0iwpOprwqnzB3BaE6FWVIox-VMG99K7rn-SgtadOREeU8lfLidh-In49Lo-cwFcd0joUuHd7p4bQp8wMZPud6ruAxmttdhnRl_G0gOa0XjyefqUEspEWijo_OFqwsmGBjNFlBPCj-t6H0wnSzogPvwEboRHwKp1cdJsnXcuOr1Wq3lxXm8cBs_WlHpbUPOkd9a2kU4COlwsqKvYM70NmLpdEeHuBDZtuKK044grtuaMBjtjTro2xMMb5hcXNtonqQgfTGY7vu2Ts_Nmp9fsNnu97nk2Tqr39f_G1OqGg0uPkILY0VIwRY8ETyQLpShhXxpqD1HEOayffLTSnzNxlDf6ASWfF2bCTYnHonDL4dQa4DER5FaGu0C1rKo9sgV9RWqlHM7y0U1h-eWjRDUnNIAEofIBUNlCgFjCjLoSklARGUUgKTuOE3YEcjg7BnCEoJna5Z-2Pe …
```
> Fix Divergent Fist of War increasing Stun Threshold

- src/Modules/CalcOffence.lua
The mana cost breakdown is hidden if the base mana cost is equal to the final mana cost, which isn't accurate in all situations
- Concoct a build with equal amounts of increased mana cost and reduced mana cost
- Observe how the mana cost breakdown only shows individual items (i.e. doesn't show the calculations from support gems)
```bash
eNrtfVtz20bS6PPyV6BUlfMiycbccPGx9yvdpbUVyZJsJ35JDTADETYIyAAoWdna_366ByAJUgAFSnQ2OV-SlEIC3T0zPX2fC1__z_dRYt3qvIiz9M0GeWFvWDoNMxWn1282Plwdbnsb__PPwetzWQ7Pot1xnOCbfw7-8dp8thJ9q5M3Gz7ZsEqZX-vy44QU-w1I3ci0HOosPZVfsvwoU282fs5SvWEFMlVxOfkWJrIofpYj_WbjU1yGww1LFqFO1d7s-VkYjpMyLsoNayTj9DILv-ryKM_GN9DpDes21nenmQLAk9Pzs4urRstx2mwZev6P1-eJvNf5ZSlLq4A_bzZ2gAHyWh_HQP5WJmOgY2-8bIe9vNFaPQ52nuuDKNJhGd_qvTwu94YyDfUUj9gvPCGY6EJ_IsopMukmiXU-RWMvHL8L5SorZbJ_fvn4cCrIrAd_YAaHuwnwq …
```
> Fix breakdown of mana cost not showing in certain situations

- src/Data/Skills/act_int.lua
- src/Export/Skills/act_int.txt
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5138
This skilled provided "INC" shock chance instead of "BASE".
```shell
eNrtfftz2zbW6M-rv4Ljmd7pThyHeJFgNtlv5LfbOHEkJ2n3zp0MSIIWE4p0ScqOs9P__R6AlERJfEiysl-7zc7WEUmcA-DgvPF68T9fxpFxJ9MsTOKXe-jA3DNk7CV-GN-83Ht3ffqU7_3PP3svrkQ-ehMcTsJIffln728v9G8jkncyernnkD0jF-mNzN9PUZGPgOpWxPlIJvGl-JSkZ4n_cm-YRCINsz3DFbEf5i_3Xiex3DO8SGTZazGWUGIk_OR-zxCZJ2P_aP7hOg29z1ku0z1jLMJ4mHifZX6WJpNbqG3PuAvl_WXiQ8GLy6s3g-tK7WFc1t53XZlCV_agB397cRWJB5kOc5EbGfyBz0AIcSOPxRj-AkYRTQAdwyaj7IBYGHPL2XtWDzu8ldKfwSB8gBwHNxW-SuVJEEgvD-_kURrmRyMRe_MazSa4TcteTqI8vI1CRbOu8ucrqJHZWPg6yUV0fDWclbUIMzGxDhxOLGTSdrgk727OhzAfHUZA0y1qUbAXN3GYyy2Br5IwS-JH9K8K2jxCkygCaaqWtU3GODrg3DYtmzfyz1EydsN4kTYFKD_oBE0ikK94BocPTESaSl-KWBwl2Xy8iNVU9FUYyIWijf0-Ga5XbgBSuF5J1cwrmYLCyNcDUI3 …
```
> Fix Anomalous Energy Blade Shock Chance

- src/Data/Skills/sup_int.lua
- src/Export/Skills/sup_int.txt
Fixes #2887  .
Added support for Anomalous Predator
https://pobb.in/cKq__YdvA0pe
> Add support for Anomalous Predator

- src/Classes/TreeTab.lua
- src/Modules/CalcDefence.lua
two very minor punctuation fixes
(blame QuickStick for finding them!)
> fix punctuation

- src/Modules/CalcActiveSkill.lua
> fixes non-curse hex skills treated as curse skills #5170

- src/Modules/ModParser.lua
Add support for hex master
- Check curse see infinite duration
- Check bane see regular duration
https://pobb.in/7-4IbRlzpsBs
> Add support for Hex Master

- src/Modules/ConfigOptions.lua
> fix typo in config tab

- src/Classes/Item.lua
- src/Data/Skills/act_dex.lua
- src/Export/Skills/act_dex.txt
https://www.reddit.com/r/pathofexile/comments/zaumlu/psa_atziris_disfavour_does_work_with_cyclone/
Weapon range mods should count towards cyclone aoe
Dual wielding uses average of bonuses based upon testing.
- Dual wielding uses averages
- Primary weapon behaves
- Shield doesn't reduce range
- Melee / Unarmed works.
https://pobb.in/ayWwEGHHbEHk
> Fixes weapon range on weapons not counting towards cyclone aoe

- src/Classes/TradeQueryRequests.lua
Follow-up on #5210
Anonymous trade search is not possible anymore after the latest update.
Fixed relevant code to use POESESSID and we are back to fetching search queries without rate limits again.
> Fix PobTrader HTML parsing for search queries

- src/Data/Skills/act_dex.lua
- src/Export/Skills/act_dex.txt
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5215
This mod is considered area radius and scales radius not area of effect this mean it is area of effect of the square.
> Correctly apply elemental hits area radius mod

- spec/System/TestItemMods_spec.lua
- src/Modules/CalcSetup.lua
- src/Modules/ModParser.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5075
Implements "Reflects your other Ring" mod found on [Kalandra's Touch](https://www.poewiki.net/wiki/Kalandra%27s_Touch)
> Implement ring reflection from Kalandra's Touch.

- src/Data/Uniques/Special/New.lua
Adding support for the maximum one buff is tricky
https://i.redd.it/i03ii94yjq4a1.jpg
> Add  Dawnstrider

- .github/ISSUE_TEMPLATE/accuracy_bug_report.yaml
- .github/ISSUE_TEMPLATE/behaviour_bug_report.yaml
- .github/ISSUE_TEMPLATE/calculation_bug_report.yaml
- .github/ISSUE_TEMPLATE/feature_request.yaml
These got changes between when the new templates were made and released
> Fix issue tags not automatically apply for issues

- src/Data/Skills/act_int.lua
- src/Data/Skills/other.lua
- src/Export/Skills/act_int.txt
- src/Export/Skills/other.txt
- src/Modules/CalcDefence.lua
- src/Modules/CalcOffence.lua
- src/Modules/CalcPerform.lua
> Ailment fix (Revert #5202)

- src/Data/Skills/spectre.lua
- src/Data/Uniques/ring.lua
- src/Export/Skills/spectre.txt
- src/Modules/CalcPerform.lua
- src/Modules/ConfigOptions.lua
- src/Modules/ModParser.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5250
Doom box was still present with curses this hides it unless something has max doom (should be nothing)
This updates fates end to new variant adding a box to implement it's curse effect due to us calculating duration of curses after their curse effect
https://pobb.in/ZGzaagezf0uR
> Update Fated End and doom mechanics

- src/Modules/ModParser.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5305
When updating the mods in https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5184 it was forgotten to check support for the new curse mods.
> Add support for new curse mods without increased effect

- src/Modules/CalcOffence.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5285
It would crash because mana resource is nil because https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5009 would not set the resource to 0 if it was not set to be shown.
> Fix crash when using Hand of the Fervent with a life cost

- src/Classes/TradeQueryRateLimiter.lua
Fixes #5328
Headers aren't applying properly with some implementations of curl.  Other versions will still work fine.
> Fix an issue with headers on some implementations of curl

- src/Modules/CalcSetup.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5356
Energy blade ignored socketgroup disabled / slot.
> Fix energy blade not getting disabled

- src/Modules/ModParser.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5382
Introduced in https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5227
When generic mods were added to be supported the previous addToMinion tag wasn't correctly handled.
This fixes it by adding it to the tagList of rest of stuff. This does mean there are some doubled code but it seems fine for clarity sake.
https://pobb.in/eyluEU-I6WBO
```shell
eNrdHF1v4kjyefkVFtKe7nQJYBsD4ZJdJYRk0CUzLGRm7u5l1TENeGO7GbudhF3Nf7_qbhvbwW23A6uTblbKgru-q7q6qtzJ-c-vnqs94yB0iH_R1FudpoZ9mywcf3XR_Pxwczpo_vxT43yK6PrT8ipyXLbyU-OHc_5Zc_EzdgGvqVEUrDD9klAyfwVKG-TTNSb-PfqNBLdkcdH8SHzc1B6Rv3Bo8s12URh-RB6-aM5tQG5qKLSxvxilzwWghxx_TuwnTG8DEm2ASVN7dvDLPVkAzOR--mn2kGHq-FmmIPMP51MXbXEwp4hqIfy4aF7a1HnGAAp87xzPoUARuRFmKrUlKGAttMIfMrAdGex8g_EiB …
```
> Fix minion specific mod no longer apply to specific minion

- src/Classes/TradeQuery.lua
- src/Classes/TradeQueryRequests.lua
> Feat: add realm support; no support for currency conversion

- src/Data/Uniques/Special/Generated.lua
- src/Data/Uniques/amulet.lua
- src/Data/Uniques/helmet.lua
- src/Data/Uniques/staff.lua
These all drop from the final boss lycia who spawns in the beyond. https://www.poewiki.net/wiki/Sanctum_league
> Add sanctum unique drop locations

- src/Data/Uniques/ring.lua
- src/Modules/CalcOffence.lua
- src/Modules/ModParser.lua
> Add Original Sin

- CONTRIBUTING.md
Added instructions on how to add path to java to settings.json for emmylua in **vscode.**
> Clarified instructions for adding EmmyLua to VSCode

- CONTRIBUTING.md
- src/Launch.lua
- src/Modules/Common.lua
In our docs it states pause will activate the profiler this doesn't seem to be the case this adds this functionality if people want to use it more easily on the entire project or trying to profile a certain computational expensive thing.
I am not 100% sure it profiler actual works well so try it out.
Example while running node power on full dps
```
> Total time: 87.126000 s
-------------------------------------------------------------------------------------------------------------------------------------
| FILE                          : FUNCTION                                        : LINE     : TIME        : %        : #           |
-------------------------------------------------------------------------------------------------------------------------------------
| …
```
> Implement profiler toggling on pause

- src/Classes/TimelessJewelListControl.lua
fix the other spot that #5460 missed
> Update other Militant Faith cost mod

- CONTRIBUTING.md
The link was broken and title was wrong.
> Fixed messed up contents for profiler

- src/Classes/TradeQuery.lua
- src/Classes/TradeQueryGenerator.lua
- src/Classes/TradeQueryRequests.lua
This PR fixes some space-indented files to use tabs as the project default.
No functional changes.
> PoB Trader: fix indentation

- src/HeadlessWrapper.lua
- src/Modules/Main.lua
Renames some things to better reflect what they do.
> Minor renaming to improve clarity

- docs/calcOffence.md
- src/Modules/CalcOffence.lua
Adds a document explaining passes and outputs in CalcOffence.
> Doc to explain passes and outputs in CalcOffence

- src/Modules/Main.lua
There were two problems occuring one it would not respect the default item affix quality as it wasn't loaded the other was not recalculating dps after normalising the quality.
> Fix unique armour/evasion/es/dps being different to added item

- src/Classes/TreeTab.lua
Fix timeless jewel trade search when changing jewel but leaving conqueror on "any"
> Fix timeless jewel trade search when changing jewel

- src/Classes/TradeQueryGenerator.lua
Mod comparison was looking at total damage and not dps
> Item pricing mod calculation does now use dps instead of damage

- src/Classes/TimelessJewelListControl.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5521
New lines were missing causing it to not parse correctly.
> Fixing missing radius on timeless jewels and missing variant on millitant faith when adding via double click on results.

- src/Data/Uniques/shield.lua
Fixes wrong source information.
> Fix Atziri's Mirror's source

- src/Modules/CalcActiveSkill.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5558
Physical skills stuff didn't work
- See it appearing in cast speed.
> Fix missing physical skill keyword flag setting

- src/Data/Uniques/sword.lua
- src/Modules/ModParser.lua
See https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5582
> The Iron Mass 3.20.1b Wording Update

- src/Data/Uniques/helmet.lua
- src/Modules/ModParser.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5583
See https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5582
> Sandstorm Visage 3.20.1b Wording Update

- src/Modules/ModParser.lua
Fixes #5622 .
Implements "You can't deal Damage with Skills yourself" mod from Ancestral Bond.
Note that there may be cases where the mod incorrectly applies due to matching by skillType. But i couldn't think of any.
> Implement "You can't deal Damage with Skills yourself" mod from Ancestral Bond

- src/Data/Uniques/helmet.lua
> Fix missing mana on mindspiral

- src/Data/Uniques/amulet.lua
Was using legacy values https://www.poewiki.net/wiki/Warped_Timepiece
> Fix movement speed on Warped Timepiece

- src/Classes/ItemsTab.lua
> Improve eldritch mod sorting and grouping

- src/Classes/TimelessJewelListControl.lua
- src/Classes/TreeTab.lua
- src/Modules/Build.lua
Using the timeless jewel trade search trade feature requires editing the search if looking for any specific devotion modifiers.
- Searched for some jewels
https://pobb.in/SEoJW9C_I091
(Devotion modifier section is only shown when Militant Faith is selected)
> Enable searching for Militant Faith devotion modifiers

- src/Modules/CalcOffence.lua
- src/Modules/CalcSections.lua
This fixes #5380.
- make a build with bleed, poison, ignite, shock, and freeze
- check the chance for each of those ailments
https://poe.ninja/pob/SVP
> Fix ignite chance display

- src/Data/Uniques/helmet.lua
Also adds the Avoid elemental damage mod that was previously missing
> Fix values of mods on Devouring Diadem

- src/Classes/TradeQuery.lua
Style update, no functional changes.
Renamed constants to fix spellchecker errors
> PoB Trader: rename constants to conform spellchecking

- src/Modules/BuildSiteTools.lua
As per request by @Dav1dde this updates it to be the default
https://discord.com/channels/676181894152454150/676187672355799062/1063912783344840826
> Update pobb.in to default

- src/Data/Skills/act_int.lua
- src/Export/Skills/act_int.txt
- src/Modules/CalcOffence.lua
- src/Modules/CalcSections.lua
- src/Modules/ModParser.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5249
Partially fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5290 (Still Needs Reflect Implementing)
Enemy Regen Support wasn't implemented
A couple x can y wasn't parsed.
Make sure I haven't broken minions again by poking that code.
https://pobb.in/UNSHTAxYVwW_
> Add support for enemy regen and sanctum x can y.

- src/Data/Skills/act_int.lua
- src/Data/Skills/act_str.lua
- src/Data/Skills/other.lua
- src/Export/Skills/act_int.txt
- src/Export/Skills/act_str.txt
- src/Export/Skills/other.txt
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/2245
Tested both arcane cloak and wiki states with source molten shell doesn't works so presuming others also don't.
https://www.poewiki.net/wiki/Molten_Shell
> Fix buff effect scaling guard absorption rate

- src/Modules/CalcPerform.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5658
This code wasn't copied across.
> Fix Rational Doctrine Not gaining highest mods when using Crystallised Omniscience

- src/Modules/CalcOffence.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/2819
The calculations were incorrect as multiplying these effects produced incorrect numbers.
https://pobb.in/_Xr9Jb_4GCrq
> Fix Double/Triple Damage calculations

- help.txt
looks like this atm
the text size is pretty small and theres no word wrap, maybe it would be a good idea to increase the text size and implement word wrap?
> add Help Section for Timeless jewels

- CONTRIBUTING.md
> Improve development setup documentation

- CONTRIBUTING.md
* better clarification for noobs
* Update CONTRIBUTING.md
---------
Fixes # .
-
-
-
> Improve development setup documentation (#5801)

- help.txt
- src/Modules/Main.lua
This just word wraps automatically making it much easier to add lines without having to manually word wrap it
Possibly should add "keyword" that lets a dev set indent level (instead of default to 4 spaces) as well as one to set text size (instead of default to 18 for titles and 12 for everything else) as the text size might be a bit small. Could also make the box bigger based on percentage of window size and scale text size based on that? but those are probs better saved for another PR
> Add word wrap to help section and cleanup some lines

- src/Modules/ConfigOptions.lua
- src/Modules/ModParser.lua
Masteries supported:
- Inflict Fire, Cold and Lightning Exposure on Enemies when you Suppress their Spell Damage
- Prevent +1% of Suppressed Spell Damage per Hit Suppressed Recently
-2% chance to Suppress Spell Damage per Hit Suppressed Recently
- You have Phasing if you have Suppressed Spell Damage Recently
- Chance to Suppress Spell Damage is Lucky
- +50% to Critical Strike Multiplier against Stunned Enemies
<pre>eNqtG11zosj2efMrKKvu0zWRbySV7JYxTuJOTDKaTGbvy1QLrZK04EKTxNna_35PN6BobITgTJUB-nz36XNOH5qzP97nRHrFYeQF_nlDOZEbEvadwPX86Xnj8eHLcbvxx-9HZ_eIzu4mF7FH2MjvR7-d8WuJ4FdMAK8hURROMf2eUdJ-AqUF8ukMB_4APQfhVeCeN24DHzekMfJdj2Z3DkFRdIvm-Lzx5FFn1pBQ5GDf7a6fJ4Bz5PmjwHnB9CoM4gVn--rht0HgAkx_cH83fMgx9fw8U5D5t7N7gpY4HFFEpQh-zhsdUB1N8bVHgRQiMdAxdftEN9VGqxDjIg4jeonmcFkWc7TA2F0BKyeG1tZNJf0VId2HuDeZYId6r …
> [3.21] Support for Spell Suppression and Stun Masteries

- src/Modules/ModParser.lua
- 25% increased Maximum total Life, Mana and Energy Shield Recovery per second from Leech
- Inherent Attack Speed bonus from Dual Wielding is doubled while wielding two Claws
- 3% chance for Hits to deal 300% of Physical Damage as Extra Damage of a random Element
<pre>eNrtXFtz4rgSft78ChdV5-kQ8P2SSvYUIZfJbkhYyMxs9mVKsQV4YluMLeeyW_vfT0u2wSHIsTEPe6rOzFQCVn8tdbf6JsQc_-clDKQnHCc-iU46Sk_uSDhyiedH85PO57uLQ7vzn58PjseILm5np6kfsJGfD3465q-lAD_hAHAdiaJ4jumXgpP2DTgtUUQXmEQj9J3El8Q76dyQCHekBxR5Pi3euQFKkhsU4pPOBEVzHHcklLg48obrgYwyRH40Je4jppcxSZd83icfP4-IBzRXo_Ht5K40qx-VZ4VF_3Q8DtArjqcUUSmBHyedAciO5vgMhfATuKEgBVaqrPUUS9VsR5dNxen0K8GnaZzQDQ6KrPQMG7C6JWuykMN0ibG3BvVUyxCRjmN8Ppthl_pPeBj7dLhAkVua0OrJigi7C_0oDai_DHxmj0ItIvpP79nLsoj4jlAUnI2na7aG05N13XJM3VFtpxpH6AonnOE0AK2WZ1BkvWfLqmLJpmXKQjG--nTxDquZWs_WTce0FNN …
> Add support for Leech, Claw, and Elemental Masteries

- src/Modules/Build.lua
- src/Modules/Main.lua
Adds an option to disable autosaving while on developer mode, this should not showup outside of developer mode
> Add option to disable autosaving on developer mode

- src/Data/Uniques/Special/New.lua
Doesn't implement healing mod as we don't have configurable chaos taken per second.
> Add Tainted Pact

- spec/System/TestDefence_spec.lua
- src/Modules/CalcDefence.lua
* Fix petrified blood / progenesis calculations final v2.maybe
* Improve max hit calculations with damage conversion into different size pools
* Expand max hit breakdowns by including pools that were harmed in the making of a max hit
Fixes #5706 #5707.
https://pobb.in/B3GvKlnjyZvZ
> Fix/improve some EHP / max hit stuff:

- src/Modules/CalcDefence.lua
Fixes #5549
This probs needs more testing to make sure theres no issues but seems fine with basic tests of varying of life/mana/es and mom%/bypass%
> Fix EB MoM With Bypass for dot pool and max hit

- src/Modules/CalcDefence.lua
> use slot concatenation rather than checking specific slot

- src/Data/Uniques/helmet.lua
> The Assailum Unique Helmet now Grants Level 30 Snipe Skill (previously 20).
> Update assailum to 3.21

- src/Modules/CalcPerform.lua
Fixes #5886 and Unholy Might not applying to minions
```bash
eNqtHGtz2rj2c_MrPMx0Znf2JmAbCMkku0MSkjITWhaS9t5PHWEL0Fa2qC0npTv97_dIssGA5UdMd6ZrrPOWzhPRq79-eNR4wUFImH_dMM9aDQP7DnOJv7huPD_dn_Yaf_15cjVGfPlpfhMRKlb-PHl3JZ8Nil8wBbyGwVGwwPxzQsn-CpRWyOdLzPwR-ocFD8y9bnxkPm4YM-S7hCefHIrC8CPy8HVj6gByw0Chg333dvs-BlyiADkcB4-Caz_ibMRcWOVBBKseIv6UOd8wfwhYtJJCvRD8qmCGo_GnyVNKJOKnRQKN3l2NKVrjYMoRN0L467rRdzh5wQAKUj0Sj3CgiGgE5M4bTQ0K2BIt8IcUbKsA9iYKQn6HPHgsxpmuMHY3YJYObBzgwXyOpfy3AeG3S-Q7JchXhR1FlJMVJTjYwJtnHR3GhwPiZktL_olxRO_G02JBFCQrYfEvhC9vKFiwFF0BPVz4hOPS4GNGQuZXkroU8G1EKTheKdgJDnHwgjgpKcgt82bEL2mTEfLRLQu3tja7eaBjHIAr8x2MVgHCFDsMvD-NYlslmGSjark9kjkuD1lJkRihqjRv02MwLQtXmfDbBJpAICsHOWURLQnJtwHGyjn539OAZrung7zDP0rQG_q8HNc0oNnp6Lm-MC4zXKngMPgw3lK1zy_ObLNlt9s961zrc-PlOiQOoiP0g3iRBwH3CX3DfkoLS38CF0vuQ5DR4fa01rw …
```
> Fix several minion buffs not being calculated correctly

- src/Classes/ItemsTab.lua
- src/Classes/TradeQueryGenerator.lua
Added missing crucible item support for ItemsTab Saving and for Trade Compare
> Enhance crucible modifier parsing support

- src/Data/Uniques/Special/New.lua
Doesn't add parsing support as not sure if we want to support this mod.
> Add Bloodnotch

- src/Modules/ModParser.lua
Support "Warcries have 10% chance to Exert 3 additional Attacks"
- Allocate mastery
- Add warcry (Intimidating Cry in build)
- Add attack skill (Boneshatter in build)
- Validate exterted attacks increased
- Validate double damage is equal to warcry uptime
<pre>
eNrVW91z4jgSf978FS6q7ukSwMZ8JBV2i0CS4S5kWMjM3D1NCVuAdoTF2HIS5ur-92tJNhiCjI39crtVGYP68yd1q9UWt3-8r6jxiv2AMK9bMav1ioE9h7nEW3QrX14erjqVP36_uB0jvvw8vwsJFSO_X_x2K58Nil8x7VasisGRv8D8ayyp8R0krZHHl5h5I_QX8x-Z2608Mw9XjBnyXMLjTw5FQfCMVrhbGYSYkoBXDBQ42HP7u5GIdIl85HDsPwm9vZCzEXNhdI5oAMMrRLwpc35g_uizcC3teiX4TRENR-PPk5eEVcRLWgVO_XY7pmiD_SlH3AjgT7fSA2zQAg_QCv6CNERDEGXaZrtqm03L6tQbtl2ppTLfhX7Az5MwXWPs7piqpt1u6mjHPr6fz7HDySvu-4T3l8hzdhq1fEdo7ep1GvUopJysKcF-wjSt_E8fxF93dLQvjCM6GE93cltWq2p3Gtdt22xd2-l8jG_56jrKb4Qv7yigeoYWwTtceITjM5nHjATMK-BfklXrYj-kFK …
> Add support for Warcry Mastery

- src/Modules/ModParser.lua
Supports the hits dealt portion of Bomb Specialist with an averaged more multiplier.
Supports the less damage with Triggered Spells portion of Perfect Crime
**Bomb Specialist**
- Allocate Bomb Specialist
- Add Wave of Conviction
- Add Righteous Fire
- Validate WoC has 10% more
- Validate RF has 0% more
**Perfect Crime**
- Allocate Perfect Crime
- Add wand with trigger craft
- Add Arc to wand slot
- Validate Arc has 35% less
<pre>
eNq1W-Fz2joS_9z8FR5m3szdTALYgEMyyXtDSNIyE1IO0vbep46wBehVtqgth9JO__dbSTYYgoyNfe1Ma6z9rXZXu6vVIm7--uFR4xUHIWH-bc2sN2sG9h3mEn9-W_v08njRrf3159nNCPHFx9ldRKgY-fPs3Y18Nih-xfS2ZtUMjoI55p8TTq2vwGmJfL7AzB-if1jwnrm3tWfm45oxRb5LePLJoSgMn5GHb2uTBXLZqmag0MG-208NoCnjOAqAeoEC5HAcPImpexFnQ-YCxQzREJh5iPgT5nzD_H3AoqUU7ZXglSIaDEcfxy8pwYifFgz0enczomiNgwlH3Ajhn9taD8yD5vgD4cAK0Qj4mFb7sn …
> Add support for Saboteur Ascendancy

- src/Modules/CalcSetup.lua
> Fix crash in the Trader from not having jewel data

- src/Data/Uniques/axe.lua
- src/Data/Uniques/helmet.lua
- src/Data/Uniques/wand.lua
- src/Modules/ModParser.lua
These wordings were incorrect didn't check the others yet because trade site was being annoying.
> Fix formless inferno, Uul-Netol's Kiss and tulborn

- src/Data/Skills/sup_int.lua
- src/Export/Skills/sup_int.txt
- Checked it works with CDR
- Checked it common elemental hit setups to make sure it's largely independent
```bash
eNrVHGtz2kjy8_Irpqjaq2ytjdELhM_eLT8T7ozDgpO9_ZQapAGUjDREGtlht_Lfr2dGEgIjIQFbV5dUGaHp7unX9EuyL3795lP0TMLIY8FlU2u1m4gEDnO9YHbZ_PB0f2o3f_2lcTHEfP5-eh17VKz80vjhQl4jSp4JvWwagMZxOCP8Y0rK-AT3Fjjgc8KCAf7MwrfMvWw-soA00QQHrsfTbw7FUfSIfXLZHM-xy16aCEcOCdyb3AKeME7iEKDnOMQOJ-GD2Psq5mzAXICYYhoBMR97wZg5Xwh_G7J4ATI10bNHXhRQfzB8P3rKMeYFecZAsB8uhhQvSTjmmKMIflw2r0A_eEbeeRxIYRoDHU0ze3ar19Gt5lkp0nUcRvwW-3BZA3m8IMRdwReBAUcbkC2rZ9q9jmFoXcM2i_CGIbmbTonDvWdyE3r8Zo4DZ8VfIVt1YQcx5d6CeiTMc1gizQZxrd0uAn5iHNPb4XgFaxtGr9WxDA2wTLscj60sWbjD7x6fX1PQ7h679GeBx0kesdO2zZZm2nbXMnqWUbbpa2TdNHWjZbe1nm2ZZinykHkRCw5QzB5M38SUQlTIYxZqdUQiEj5j7q0zWQh_w_yJF6wboaI6bhijEEyC1Satjt4tgh7gAN-wiFdxPgE7JCGEKL6GsgthTBwGUa3-LttxCzEfv …
```
> Add support for Prismatic Burst

- src/Data/SkillStatMap.lua
- src/Data/Skills/act_dex.lua
- src/Data/Uniques/helmet.lua
- src/Export/Skills/act_dex.txt
- src/Modules/CalcOffence.lua
- src/Modules/ConfigOptions.lua
- src/Modules/ModParser.lua
Added support for the helmet enchantments
Update Assailum with the max stages mod and removed the less damage mod
Test build: https://pobb.in/pSF-5V2oqc_t
> Fix Snipe Support + update Assailum

- src/Classes/TradeQuery.lua
- src/Classes/TradeQueryRequests.lua
Add hostName for future garena or qq hosts
> Add hostName for future garena or qq hosts

- src/Classes/SkillsTab.lua
> Add ability to sort by EHP change for gems

- src/Data/Skills/act_int.lua
- src/Export/Skills/act_int.txt
This assumes vaal firestorm has the same aoe as firestorm (why else would it have a local modifier to impact aoe rather than just have a different impact aoe?) if not then that needs to be fixed
> Implement vaal firestorm burning ground and aoe

- src/Data/Skills/act_dex.lua
- src/Export/Skills/act_dex.txt
- src/Modules/CalcDefence.lua
increases ehp by around 2.7 hits in all cases it is supposed to and less in cases its not (working correctly)
increases max hit by the same as 90% less taken (as its only 1 hit it always applies)
does not work on max hit breakdowns yet
> Add support for Vaal Arctic Armour

- src/Data/Uniques/amulet.lua
- src/Data/Uniques/body.lua
- src/Data/Uniques/boots.lua
- src/Data/Uniques/claw.lua
- src/Data/Uniques/helmet.lua
- src/Data/Uniques/jewel.lua
- src/Data/Uniques/shield.lua
- src/Data/Uniques/wand.lua
- src/Modules/Build.lua
Went through the ones I hadn't gone over yet. Also fixes a bug where we were display attributes of 14 as these are hidden ingame.
> Fix the remaining issues on 3.21 unique changes

- src/Modules/CalcDefence.lua
- src/Modules/ModParser.lua
This crucible mods wasn't yet supported.
Works with config
> Add support for hits against you overwhelm pdr

- src/Data/Skills/act_str.lua
- src/Export/Skills/act_str.txt
Only the Bladestorm skill part should be receiving the 100% chance to bleed
Fixes #6114
> Fix Bladestorm Attack part having 100% bleed chance

- src/Classes/TradeQueryGenerator.lua
> Fix Trader crash when sorting results by some stats

- src/Classes/TreeTab.lua
> Fix crash when searching for Timeless Jewel and using filter nodes

- src/Data/Skills/act_str.lua
- src/Export/Skills/act_str.txt
KeywordFlag.FireDot scales both the Fire dot damage as well as Ignite damaage. Changed it to use mod flags so it only affects the Fire dot damage
> Fix Exsanguinate stages scaling Ignite damage with Crucible conversion mod

- src/Data/Uniques/body.lua
- src/Modules/ModParser.lua
GGG changed the wording on the mod at some point
Fixes #6150
> Fix Cospri's Will poison mod not working

- src/Modules/BuildList.lua
Currently you need to press enter to search the build list. This PR makes it happen instantly.
> Make build search immediate

- help.txt
Fixes #6093 .
Item Tab section added to Help documentation.
> Add Help documentation for Items tab

- src/Modules/CalcOffence.lua
It seems git didn't do a good job at merging this section of the code and decided to duplicate the code.
> Fix mana cost doubling issue

- src/Modules/CalcTriggers.lua
Fixes #6340
Confusion with lua syntax caused me to incorrectly initialize triggeredSkills causing a crash.
> Fix Crash when using a weapon with a crafted Trigger mod

- src/Modules/ConfigOptions.lua
The configs weren't showing up as the stats they were mean to affect were not added to the ifStat
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/6397
> Fix Pierce and Chain count config not appearing sometimes

- src/Data/Skills/sup_dex.lua
- src/Export/Skills/sup_dex.txt
Fixes #6422
The less duration mods was not parsed correctly.
> Implement Sadism Support less ailment duration mod

- src/Modules/CalcTriggers.lua
Fixes #6332.
Unseen Strike from The Hidden Blade lost its cooldown but retained maximum trigger rate cap of 2/s. Implemented by adding a triggerRateCap variable in skillData. I've considered using the existing hitTimeOverride variable but decided to keep these separate since they're sort of different and it also makes the breakdowns easier to handle.
> Impl trigger rate cap override

- src/Data/SkillStatMap.lua
- src/Data/Skills/sup_int.lua
- src/Export/Skills/sup_int.txt
- src/Modules/ConfigOptions.lua
Adds a config box to active the Fresh Meat buffs
- Added Fresh Meat, checked crit chance, crit multi, attack speed, and movement speed before and after checking the config
- Also checked crit chance with default quality
```bash
eNqtW1132jgTvu7-Ch_uG8Jn0h6yewgkTc5JWl5I292rHmEL0EaWqC0nYX_9O_owGLCMHDsXrbHmmS9pRqMRDP56C6n3gqOYcHbVaJ2dNzzMfB4QtrxqfH-6_XjZ-OvPPwYTJFbfFtcJoXLkzz8-DNSzR_ELpoBreAJFSyx-pJw6v4DTGjGxwpw9on959IUHV42vnOGGN0csICL95FMUx19RiK8aMx_ADQ_FPmbBaPfeEK5QhHyBowcpdZgI_sgDGBVRAqMhImzG_WcsvkQ8WSulXgh-1TT3j5Nv06eMSoRlVQKLPgwmFG1wNBNIeDH8c9UY-oK8YCAFrR5ISARwRDQBdheNpgUCvkRLfJehPT9Be51EsRijEB5PY2ZrjIMtWdtGNonwzWKBlf6jiIjRCjHfgX1Z2seECrKmBEdb-tZZz4a4O2LeOreyf-IC0fFkdloRTckdPP6TiNU1BQ868ZXU90tGBHYmn3ASc1ZKayfiUUIpBJ4T7RTHOHpBgjgqMuLhnDBHnzwihkY83vm63S4ineAIQlnsIc5PAGbY5xD9WUi36yAkH2qV9kAW …
```
> Add support for Fresh Meat Support

- src/Modules/CalcPerform.lua
Fixes https://www.reddit.com/r/pathofexile/comments/15zn4nx/path_of_building_community_2320_322_tattoos_gems/jxhwrhv/
> Add a null check for src instance in slot match

- src/Classes/TreeTab.lua
Fixes https://old.reddit.com/r/pathofexile/comments/15zn4nx/path_of_building_community_2320_322_tattoos_gems/jxhv38t/
This is horribly inefficient, but fixes the problem for now.  May look into a faster way of doing this.
> Fix editing tattoo under timeless jewel influence

- src/Modules/CalcTriggers.lua
#6448 but for trigger rework on beta.
> (BETA) Fix null deref at slotMatch

- src/Modules/CalcOffence.lua
Fixes https://www.reddit.com/r/pathofexile/comments/15zn4nx/path_of_building_community_2320_322_tattoos_gems/jxi6dlq/
> Fix crash caused by usage of incorrect breakdown table

- src/Data/Skills/sup_str.lua
- src/Export/Skills/sup_str.txt
- src/Modules/CalcTriggers.lua
Implements the [Flamewood Support](https://www.poewiki.net/wiki/Flamewood_Support) trigger.
> Implement Flamewood Support trigger

- src/Modules/ConfigOptions.lua
I forgot to include both the stats into a block
Fixes #6469
> Fix Chain count box not appearing sometimes

- src/Data/Global.lua
Forgot to increment the number for the new skill types that were added
> Fix gems not benefitting from Supports sometimes

- src/Data/Skills/minion.lua
- src/Data/Skills/other.lua
- src/Export/Skills/minion.txt
- src/Export/Skills/other.txt
Created a custom skill for the minion as there as no skill for the damage to apply to
> Add Support for Guardian's minion RF skill

- src/Classes/ImportTab.lua
- src/Classes/Item.lua
Fixes #6442  .
Importing energy blades didn't work as expected, since the abyssal socket count gets overwritten if there aren't any abyssal socket mods.
This is a pretty hacky solution, so I'm open to suggestions
- Imported the character "Strong_and_intelligent" from https://www.pathofexile.com/account/view-profile/Xeverous/characters
- Verified editing an energy blade weapon causes no crash
- Verified abyssal sockets appear properly after import
- Verified creating an energy blade character from scratch still works as expected
```bash
eNrtfWtz20ay6OfwV6BUtfeLaXveA_jae4qSrEeOZcuSH5t8SQ2AgYgYBGgAlCxv7X-_PQOQBCiAIkXFNzknuxWZJKZ7ZvrdPQ-8_K9vk8S51nkRZ-mrPfwM7Tk6DbIwTq9e7X38cPTU3fuvfw5enqty_C7an8WJefLPwU8v7Wcn0dc6ebXn4T2nVPmVLj_NUdHfANVUpeVYZ-mZ-j3Lj7Pw1d7bLNV7jq_SMC7n34JEFcVbNdGv9j7oyTRR-Z6jik …
```
> Fix issue with abyssal sockets on imported Energy Blade

- src/Modules/Build.lua
- src/Modules/CalcTriggers.lua
Fixes a variety of crashes mentioned on discord. Adds channel time required to trigger a skill to the sidebar.
> Fix trigger rework issues

- src/Modules/CalcDefence.lua
Fixes #6482
Maximum resistance was being calculated before resistance conversion.
> Fix melding being calculated before res convert

- src/Modules/CalcTools.lua
> Fix + level to specfic gem mods not working for vaal versions of that skill

- src/Modules/CalcOffence.lua
> Stop totem duration from using skill duration

- src/Modules/CalcTriggers.lua
> Prevent tawhoa chosen attacks from being exerted.

- src/Classes/ConfigTab.lua
Fixes #6131
There was a boss skill refactor back in 3.20 and the index "Uber Atziri Flameblast" was changed to "Atziri Flameblast". Any build 3.20 or earlier that has that value saved in the config crashes, so this PR adds a quick gsub during load so we set the right skill. Could always add a nil check in the ConfigOptions where it crashes instead, but this is more direct.
<pre>eNrtfWtz20ay6OfDX4FS1d5KypI8bwBe-5zSy7YSy1YkOz7JrVupATAQEZOAAoCSlS3_99szAIkHAQKUlGySTbKrkER3z0xPT0-_ZvD8fz7PZ9aNSrMoiV_s4H20Y6nYT4Iovnqx8-H9yz1n53_-e_L8XObTd-HhIprpJ_89-a_n5rM1Uzdq9mLHFTtWLtMrlX-_JEV_AlLXMs6nKonP5M9J-ioJXuy8n6rDNIrVt0Bmx_JkHET5i52DWZTKHcufySx7K-cK4NT8eibTHUtmvoqDo-rJafzLIsqiPIGHcxnFl4n_SeWv0mRxDQOAjtxE6vYsCTTo2fm7i_e1bkRx2Y0LOZOfVDbdgaH81_PzmbxT6WUucyuDP9Af4Ii8Uq-jHMjJ2QJoORi5guzDf2zqELHztBvz8lqpYIV …
> Fix crash related to boss skill preset

- src/Data/Uniques/wand.lua
Fixes missing variant (i hope).
Mismatched number of variant information
> Add missing variant  to Tulborn

- src/Data/Uniques/ring.lua
> Fix typo in Death Rush ring

- src/Data/Uniques/body.lua
Fix typo in Ashrend body armour
> Fix typo in Ashrend body armour

- src/Modules/CalcTriggers.lua
Removes missing trigger config logging as it was spamming the console quite heavily.
> Remove logging for missing trigger config

- src/Modules/ModParser.lua
> Fix Ahuana's Bite 'Chill as though dealing' mod

- src/Modules/Build.lua
I've not been able to reliably trigger the crash but this does seem to fix it.
I'll edit this section if i find out more.
> Fix mainOutput crash

- src/Modules/CalcTriggers.lua
> Fix missing config causing cast speed to not apply to activation freq of arcanist brand

- src/Modules/CalcTriggers.lua
> Fix damage flag causing dual wield attack rate penalty to apply to spells

- src/Modules/CalcPerform.lua
The mod should apply to all damage taken, not just cold damage
Fixes #6609
> Fix Ahuana's Bite only increasing Cold damage taken

- src/Classes/ItemsTab.lua
Fixes #5778 
Moving the tooltip from the button to the enchant on hover for faster comparison. Also adding a remove button because why doesn't this exist?
<pre>eNrFW21z2kgS_hx-hYqqvbqrKwMSCANn7xbGr3V24gMnufuUGqQBtBk0RBrZZrfy3697RgKBGVlCqrsk5QDTT79NT093C5_99rpkxjMNQo_753Wz0aob1He46_nz8_rnp-uTXv23X2tnj0QsPs0uIo_hyq-1D2fytcHoM2WAqxuCBHMqviSc2t-A04r4YkG5_0B-58ENd8_rH7lP68aU-K4nkncOI2H4kSzpeX3iALhukNChvjvafh4TLkhAHEGDe5Q6jAR_4C6siiCC1SXx_Al3vlNxE_BoJZV69uiLorl7ePw0fkqp5PlplcCiD2ePjKxpMBFEGCH8OK8PwTFkTi_JEn4CN8IiYGW22_1Gx-z3Tdvq9Lr1Zib4IgpCcRyHyYpSdwtqdOy2raN9DOjVbEYd4T3TUeCJ0YL4zlaiFleU9iFiwlsxjwYpxbSI2zfMzVZLR_zEBWGXj5Mtbb_TbfQ6XfxntvvZOC42OK2Er55YXDBw6hFS7ua-J2gaaLV7ja7Za3c6NmKzhB4Amz270enaZh9k6kMAwY_cC7lfwjFHKD2KGIODnkZqvTqmIQ2eifB2ldTSj_hy6vm7m5DTHcOAkk8zFehj4npRmOKgAz0Qn4x4uI2PbhblIw0g-Ygd …
> Add support for item enchantment comparison on hover

- src/Modules/CalcTriggers.lua
> Disable skill rotation for CWDT

- src/Modules/ModParser.lua
Fixes #6612 .
Wording changed on Uul-Netol's Vow, this PR updates the parser for it.
> Update wording on Uul-Netol's Vow

- src/Classes/TreeTab.lua
Fixes the way I use import tree and the recent change to where the import tree has been moved too. I feel the tree you are importing into is not obvious.
as above
- Open a new/existing build.
- Select tree tab if not open already.
- Press Ctrl-M.
- Select "Import Tree" button.
- Note that the "Import" button is disabled.
- Type in a Name.
- Select the tree link edit box and paste in the import URL (you can type it if you wish).
- Note that the "Import" button is enabled.
- Select "Import" button.
- Note that the new tree/Spec is created and selected as active.
- Open a new/existing build.
- Select tree tab if not open already.
- Press Ctrl-M.
- Select "Import Tree" button.
- Note that the "Import" button is disabled.
- Type in a Name.
- Select the tree link edit box and type in something …
> Importing a new tree spec will create a new tree spec always

- src/Modules/CalcTools.lua
> Fix +1 Socketed Skill gems mods not working

- src/Modules/CalcTriggers.lua
Fixes extra icdr needed breakdown line being inaccurate.
Fixes ignoresTickRate flag applying to both triggered and trigger.
> More accurate icdr suggestions

- src/Classes/ItemDBControl.lua
Fix league and type dropdown in ItemDBControl not being loaded after #6635
- Dropdowns now load and are sorted
> Fix league and type dropdown in ItemDBControl

- help.txt
Fixes # .
Adding notes to help section from [this issue](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/6093)
- N/A just docs
> updates help section

- src/Modules/CalcPerform.lua
I have been unable to get mine auras to work properly, this is definitely not the best solution, but should probably be added until someone can get them to work properly, and does work as long as the carry (/build being imported into) does not also have the same mine
> Prestack mine auras for party tab export

- src/Modules/ConfigOptions.lua
> Update tooltip wording for Magmatic Strikes

- src/Modules/ConfigOptions.lua
> Assume 1 stage by defualt for sigil of power

- src/Modules/ConfigOptions.lua
> Show warcry calc mode for Fist of War

- src/Data/Skills/act_int.lua
- src/Export/Skills/act_int.txt
When I changed the gem to use the percent stats I forgot to also change it for the guard value
Fixes #6700
> Fix Arcane Cloak not affecting max hit

- src/Data/Skills/other.lua
- src/Export/Skills/other.txt
> Fix Summon Sentinel of Radiance having 2 burning area skills

- src/Data/Skills/minion.lua
- src/Export/Skills/minion.txt
Fixes #6735
Another missing skill type tag on minion skill.
> Add Multicastable to IceElementalSpearSummoned

- src/Modules/CalcOffence.lua
The jewel doesn't exist in league but I've had people message me to support it for standard
Fixes #5070
> Fix Mantra of Flames not counting stacks from Trauma or Voltaxic Burst

- src/Modules/CalcPerform.lua
- src/Modules/CalcTools.lua
- src/Modules/CalcTriggers.lua
> Fix minion trigger skills when minion is triggered

- src/Classes/TreeTab.lua
If you select devotion modifiers on Militant Faith, then switch to a different jewel type (such as Brutal Restraint), generate any search results, and try to copy trade URL, it throws the following error:
This happens because the current ``TreeTab.lua`` tries to generate ``devotionFilters`` based on ``devotionVariant1`` / ``devotionVariant2`` being set &mdash; which _is_ necessary to check, but doesn't actually imply that ``data.timelessJewelTradeIDs[timelessData.jewelType.id].devotion`` is usable.
- Create new build
- Open Timeless Jewel Finder
- Select Militant Faith Jewel Type
- Select any Devotion Modifiers
- Select any non-Militant Faith Jewel Type
- Add any desired nodes and search (to populate the search results)
- Copy Trade URL
Before this PR the above error will occur, after …
> Fix timeless jewel devotion filter generation

- src/Modules/CalcDefence.lua
Fixes #6843 .
This was tested and confirmed, though I believe ggg should change this so making draft until confirmation gg wont change it
also would need to be fixed for #6803
> Remove the normalisation of taken as if over 100%

- src/Data/Skills/act_dex.lua
- src/Export/Skills/act_dex.txt
self debuff duration (eg ailments on self) are reduced
> Add support for divergent temporal rift

- src/Export/Scripts/statdesc.lua
minor technical change (almost all the difference is whitespace), I spent a while looking to see if I could make the two the same, but it breaks too many things, and could not think of a good way to optimise them without significant performance degradation outside `run all`
The two files currently 
<https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/dev/src/Export/statdesc.lua#L3-L89>
<https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/dev/src/Export/Scripts/statdesc.lua#L3-L87>
> Update stat descriptions export to be more similar to the exporter one

- src/Modules/CalcPerform.lua
Fix issue introduced in #6757
It was never applying the recovery of flasks to the player, this fixes that
> Fix master surgion

- src/Modules/Main.lua
minor QoL for dev branch, 
considering adding more dev stuff in there, or some method to apply/link sections from contributing to it
> Apply blue colour to dev branch help sections to highlight them

- src/Classes/CalcBreakdownControl.lua
- src/Classes/ModStore.lua
- src/Data/ModCache.lua
- src/Modules/CalcDefence.lua
- src/Modules/CalcOffence.lua
- src/Modules/CalcPerform.lua
- src/Modules/ModParser.lua
New stats with added support:
* More accuracy vs enemy
* Warlock Phys damage gain and ES conversion mod
* Assassin Ruthless "All damage can poison"
* Changed wording on Chieftain explode
> Add support for new tree nodes

- src/Classes/PassiveSpec.lua
- src/Classes/PassiveSpecListControl.lua
- src/Classes/PassiveTreeView.lua
- src/Modules/Build.lua
built ontop of  #6880 (merge that first)
adds basic support for selecting an alternate ascendancy
> Support for alternate ascendancies

- src/Data/BossSkills.lua
- src/Export/Scripts/bossData.lua
Built on #5754 and #6652 those must be merged first
only the last commit is unique
This fixes the issue for `Sirus Meteor` when using something to convert his damage like `Kaom's Binding`
> Update Boss skills to use conversion rather than hardcoded elemental

- src/Data/ModMap.lua
- src/Modules/CalcDefence.lua
- src/Modules/ModParser.lua
This adds support for enemy impale chance, which currently only comes from the map mod, and them dealing that damage to the player
It also fixes some reflect taken mods as impale damage is reflect damage
> Add support for enemy impale and fix some reflect mods

- src/Classes/ImportTab.lua
Fixes #6913
Short term fix for the new ascendancy, passing a hardcoded "0" until we know how the data comes through on import later on in charData
> Fix importing passive tree

- src/Modules/CalcDefence.lua
Variable name was wrong so nothing was counting
Fixes #6914
> Fix Phys Damage taken As not contributing to eHP

- src/Data/Skills/act_int.lua
Converts to the new 3.23 stat of extra radius
> Fix Ball Lightning quality stat

- src/Data/SkillStatMap.lua
- src/Modules/CalcOffence.lua
The gem was not disabling Unleash calculations when it should have
> Fix Blade Vortex gaining damage from Unleash

- src/Data/Uniques/Special/New.lua
This PR doesn't include parsing for all mods, but many are parsed by default
> Adding new uniques, sans "That Which Was Taken", which will need to be generated

- src/Classes/PassiveSpec.lua
> Fix Ascendant nodes counting towards allocated passive skill total

- src/Data/ModCache.lua
- src/Modules/CalcSetup.lua
- src/Modules/ModParser.lua
Fixes #7029
Tinctures in the Flask 5 slot are disabled when using a Micro-Distillery Belt. ~~This PR adds a way to exclude certain keywords when parsing mods that Disable Items.~~ This PR adds a way to exclude itemTypes when parsing mods that Disable Items.
I could have done a simpler check in CalcSetup where if slotName is Flask 5 and the item is a tincture -> do not disable. This would mean not changing the ModParser/Cache, but I thought this was a little more flexible and gives us a solution going forward if a situation like this comes up again. Happy to go the fewer changes route though.
- Compare DPS of Before fix build with "Don't disable items" config with after fix build without config checked.
- Check the tooltip to see accurate enable/disable stats
- Verify other items like …
> Fix Tinctures when using Micro-Distillery Belt

- docs/modSyntax.md
- src/Data/Skills/act_dex.lua
- src/Export/Skills/act_dex.txt
- src/Modules/ConfigOptions.lua
add storm rain of the fence, and conduit
> Storm Rain Transfigured gems

- src/Modules/Data.lua
Adds all Vaal variants of Transfigured Gems to Gem Selector in Skills Tab
> Add Gems for all Vaal Transfiguration Variants

- src/Data/Skills/act_str.lua
- src/Export/Skills/spectre.txt
I accidently removed the stat by mistake
Fixes #7052
> Fix Rage not working when using Warlord's Mark

- src/Classes/ImportTab.lua
Tested character import `account: leovi` `character: CorruptedSteel`
Uses Vaal Caustic Arrow of Poison in Body Armour
> Support Vaal Transfigured Gem imports

- src/Data/ModCache.lua
- src/Modules/CalcPerform.lua
- src/Modules/ModParser.lua
The mods were previously using the Ailment..Base variable and only applying the largest value when instead they should have been summed together.
I'm not certain on the order of operations though so the rounding may be slightly off
Fixes #7089
> Fix "damage taken by at least x%" Ailment mods not stacking

- src/Data/Skills/act_dex.lua
- src/Export/Skills/act_dex.txt
The skill should not have any stages as it simply just damages in an area around you each cast
> Fix Blade Blade of Dagger Detonation having a stages box

- src/Modules/Data.lua
We assume that something with the update luaJit is causing the issue when inserting new keys while iterating
Fix done by Nostrademous
Fixes #7108, #7118
> Fix occasional crash when loading build on Beta branch

- src/Data/Uniques/Special/Generated.lua
> Add support for That Which Was Taken jewel

- src/Classes/TradeQueryRequests.lua
> Fix Crash on Beta branch when using trade search

- src/Classes/CalcBreakdownControl.lua
- src/Classes/CalcsTab.lua
- src/Classes/ConfigTab.lua
- src/Classes/DropDownControl.lua
- src/Classes/EditControl.lua
- src/Classes/GemSelectControl.lua
- src/Classes/ItemsTab.lua
- src/Classes/ListControl.lua
- src/Classes/PopupDialog.lua
- src/Classes/ScrollBarControl.lua
- src/Classes/SkillsTab.lua
This PR does two things:
1) Adds the mouse scrolling from anywhere functionality into Popups like Item Trader, superceding #7289 
2) Centralizes scroll up and scroll down input keys to the ScrollBarControl so everything using a scrollbar has consistent behavior
I saw a variety of events for our scrollbars, some checking only WHEELDOWN/WHEELUP and other doing this and PAGEDOWN/PAGEUP so I figured it would be a good idea to refactor that out somewhere and have everything use it so all scrollbars use the same buttons. I thought about adding DOWN/UP, however some of our classes already have conditions for this like DropDownControl and GemSelectControl. Wheel and Page are the general keys not used in any other way right now, but it'll be very easy to add other inputs to all scrollbars without …
> Refactor scrollbar input events

- src/Data/ModCache.lua
- src/Modules/ModParser.lua
Some values were saved as strings which broke the compare function
> Fix crash when hovering over some breakdowns

- src/Modules/Data.lua
Fixes #7340
Hopefully the final fix for the uniques that break Utula's Hunger.
Unique List:
- Deidbell
- Deidbellow
- Forbidden Shako
- Haemophilia
- Hiltless
- Malachai's Awakening
- Obliteration
- Oni-Goroshi
- Prism Guardian
- Sin Trek
- Slavedriver's Hand
- The Druggery
- The Eternal Struggle
- The Jinxed Juju
- Valyrium
- Validate Utula's life mod not affected by any of the above uniques equipped
<pre>eNrtfW1z2ziW7uf2r2C5am-lK-1EAPWam8yWEzsvM3HHayed3U9TtARb7FCkmqTseKb6v18cgBRBCiCOAO3uremerumWhXMeHh7iAfAAIPTy37-vkuCe5UWcpa-OybPBccDSebaI07tXx18-vz2ZHv_7X45eXkbl8tPt602cQMlfjn54KT4HCbtnCfc7Dsoov2PlLzVS-HeOtI7Scsmy9CL6NcvfZYtXxz9nKTsObqJ0EZf1X_MkKoqfoxV7dXw9587HQVTMWbp403xfGS6jPJqXLP8IVz3dlNlFtuClZb7hpasoTq-z-TdWvsuzzVoEdR-zB2nz4eLy09VnJaQ4VUPid_TDy8skemT5dRmVQcH_9er4lCcmumPv45JDRcmG44yPn_ …
> Fix Utula's Hunger interaction with multiple uniques

- src/Data/ModCache.lua
- src/Modules/ConfigOptions.lua
- src/Modules/ModParser.lua
For some reason the CanWither flag isn't working to enable to the wither stack effects. This is kinda messy but I couldn't think of a cleaner way
> Fix Wither stacks not working with Unholy Might

- src/Data/Uniques/Special/New.lua
Adds the `Grace of the Goddess` unique Prophecy Wand
The wisps mod is not yet supported
> Add Grace of the Goddess unique wand

- src/Export/spec.lua
Fixes GGPK Essence export script by updating essence related DATs
> Essence Exports

- src/Export/spec.lua
> Drop Level Min & Max became a DropLevel list

- src/Classes/CalcsTab.lua
- src/Classes/PassiveTreeView.lua
While creating the node power heatmap, if you are generating Offence/Defence and switch to anything else before it's done, the colours go away completely and seemingly nothing is happening until the power calc is done in the background and everything pops in. This is also the case if generating any stat and switching to Off/Def during.
This PR fixes this so that the colours in the heatmap generation do not break when switching so users are aware that PoB is still thinking.
<pre>eNrtHFlv4zb6efIrCANdtGgOHZbiZJMuHOcEkpnUTma2TwNGom02tOhKVBK36H_fj6QkS74kWe7bpkBrS9_N76bRs_98TBh6I2FEeXDeMg-NFiKBx30ajM5bz0_XB53Wf37ZO3vEYvxleBFTJt_8svfpTH1GHsNR9BlPyHmrj4MRCVsIRx4J_N78xWcekBZ6o-T9gfvw_e7h8Uv_qYUYeSPsvNVpoSkOxJjw4AH_zsMb7qc4E0yDAfdeibgJeTwF-VpI4HBExNdUYvs7SPyCA5-KFCujRoMCNW-MQ-wJEt5Lxt1YcC2PCGPSApU-n …
> Fix heatmap colouring when switching power stat

- src/Classes/PassiveSpec.lua
Just an update
- 3.24 : https://poeplanner.com/AwAAAwAfAAAAAAQAwyFl-daQ1rcAAAAAAQBAR-DIBAAA______________________8AAAMAAAADAP____________88AAAAABQAH4sIAAAAAAAAAwMAAAAAAAAAAAA=
- 3.23 : https://poeplanner.com/AwAAAwAdAAAAAAQAwyFl-daQ1rcAAAAAAQBAR-DIBAAA______________________8AAAMAAAADAP____________88AAAAABQAH4sIAAAAAAAAAwMAAAAAAAAAAAA=
- These nodes are active
> Fix Tree export to PoE Planner

- src/Classes/ItemsTab.lua
Fixes #7512 
Delve mods can only appear on regular jewels, so this removes the option from cluster jewels
```bash
eNrtfWtznDq26OfpX0G5au6X2A56IFBuMqfaj9hO7MSx89r54hIg3MQ0OED7kan573dJomloQ7vbj332OXfP1GTaoLUkLa33ktDr_7oZJ9aVzIs4S9-soU17zZJpkIVxev5m7cvntxve2n_9a_D6WJSjj9HWJE7Um38N_vFa_7YSeSUTgLMBrhT5uSy_TnGRM3h2KdJyJLP0SPzM8r0sfLP2IUvlmuWLNIzL6V9BIorigxjLN2snIj2X-ZolikCm4fbsxY4UobxVjUciF0Ep80PV93BSZkdZCA0ikRTweizi9DQLLmS5l2eTyzdreM26iuW1aXRwdPzx5HNjXHHaHBdM7B-vjxNxK_PTUpRWAf-8WRsCfcS53BFj-BewiWQCqJDHCPM2mW1j1117uRB0a5IX5UPgTy-lDGsQsok9j_W1_ZyVcgxPAzmWafk5Hs_6sjex4zGPUtux4Vdvd8e53I0iGZTxldzO43J7JNJghobbmzbvg-1o77mbxHPJIoijSVLGl0ms1ryCcjYd2geyf3dM7gJ6iGTn-LRuyhD2ONp0Xc9zbU4Xw2XljHp9Lb_F5WgrgRV6QC8K9uA8jUv5QODjLC6y9BHza4L2TnF7kiQg8Uu1PZGFzK9EGbeH1Y87G_tx-iDqHYlUbGfFbI34opbHMgdtUrYA7HsATmWQgQJqgh …
```
> Disallow delve mods on cluster jewels

- CHANGELOG.md
- changelog.txt
Ryuuk -> Ryuukk
MattiaCiccone -> Ciccooz
wkingston1248 -> Random-Panda
> fix typo and use github name x2

- src/Classes/Item.lua
- src/Data/ModCache.lua
- src/Data/Uniques/Special/Generated.lua
- src/Data/Uniques/Special/New.lua
- src/Data/Uniques/amulet.lua
- src/Data/Uniques/helmet.lua
- src/Data/Uniques/mace.lua
- src/Data/Uniques/ring.lua
- src/Data/Uniques/staff.lua
- src/Data/Uniques/sword.lua
- src/Modules/ModParser.lua
Update values from uniques shown off before the league started
Remove The Perandus Pact from generate and add new mods
Add:
* Veruso's Ambition
* The Utmost
* The Tempest Rising
* The Devourer of Minds (charge mod not supported)
* The Hand of Phrecia
* The Apostate
* Grattus Signet
* Circle of Ambition
> Add and update new 3.24 uniques

- src/Modules/CalcOffence.lua
- src/Modules/CalcTriggers.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/7625
Manaforged calculations used rounded mana cost. Additionally the formula considered mana cost as a continuous value and not discrete chunks (skill uses).
```
https://pobb.in/g-a58sUT0t-p
```
> Fix manaforged trigger rate calculations

- src/Modules/CalcSetup.lua
Fixes #5523
https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5445 made kalandra's touch ring implicits work again based on a misleading reddit post and internal discussion. Due to the confusion regarding which mods should work and which should not all were allowed to let the end user decide manually. This pr filters the implicits on the kalandra's ring making on mod of type ExtraSkill apply. Additionally it resets changes made to item property counters made by kalandra's touch to prevent the ring's properties to count towards items such as Shadowstich while still allowing the ring to copy those.
- Test https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/7179
- Test https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/7182
``` …
```
> Fix kalandra's touch implicits and mult interactions

- src/Classes/CalcBreakdownControl.lua
- src/Modules/ModParser.lua
Fixes #7616 .
Crash on MH inc. crit chanche / MH crit Chance hover in Calcs Tab when `Perandus Pact` with `increased Global Critical Strike Chance` mod used in build.
- Import build
- Go to Calcs
- Hover over MH Inc. Crit Chance and/or MH Crit Chance
```
eNrtfVtz2ziy8PPqV7Bcdc5LHAd3gvMle0q-xjN24vElmcyLCyRBiwlFOiRlx7O1__1rgJREyqQs2_Kcnd2T2vWIBLobaHQ3uhsXvv2fH-PEudF5EWfpuw28hTYcnQZZGKdX7zYuzvdfy43_-fvg7YkqRx-j7UmcmJK_D_721v52En2jk3cbHt9wSpVf6fLTFBW9BFTXKi1HOkuP1dcsP8jCdxvnI72dx6n-BdBsOL5Kw7h8t_EhS_WGEySqKD6osX63sTvRSVyUG44qAp2GO_OSnZEaXwMFqD5SuQpKnR-ZRgwnZXachVAjUkkB2MYqTs-y4JsuD_Jscg2d23BuYn1bVTo8Pvl4et5oYZzWLRz6vs6huxvQy7-9PUnUnc7PSlU6BfyBYmCWutK7agx_AaNKJoAOI4qYtyURl1Jib-PNUuDtSV6UT8Nwdq11OAPytpAkBIu-2ie53osiHZTxjd7J4xKYlwZzmsLdkhz3AT8J4HiSlPF1Eut8BsS2CO0DeX-PBEaor_J5Vqpk9-Rs3n3KPYK2uMclZ …
```
> Fix breakdown crash when using Crit Chance Perandus Pact

- src/Data/Uniques/shield.lua
This was changed in 3.24.0
https://www.poewiki.net/wiki/Mutewind_Pennant
> Update Mutewind Pennant Shield

- src/Modules/ConfigOptions.lua
Also correctly moves other option to be in alphabetical order
Fixes #7557
> Move "Insane" config to skills section

- src/Modules/CalcSetup.lua
- src/Modules/Common.lua
Fixes #7543
The `cacheSkillUUID` function used the address of the group pointer for finding the index of the group a given skill belongs to. This failed for skills coming from items as the group table is recreated in the process of creating a new env. Causing incorrect cache reuse, causing all kinds of issues.
- Test build provided from issue and minimal repro version.
```
eNq1XFtz4joSfp78ChdV-7Qk8U2-pJLdAnLjHJhkIJc55yUlbAGeCJux5RBma__7tmQbHAYbO7DzkLGt7q8vklrqlpLzf7_PqPRGwsgL_IuGciI3JOI7gev5k4vG48P1sdX497-Ozu8xm96N27FHecu_jr6ci2eJkjdCLxqG3pAYDieEPWVQ2gtAzbHPpiTw-_hHEN4E7kXja-CThjTCvuux7M2hOIq-4hm5aAyn2A0WDQlHDvHdzrrhIfSc14iREMinOMQOPPa48FbMgn7gAskY0wjQZtjzh4HzSthNGMTzi4bakN48skiIuv37u8FDTjPPz2sGln05v6d4ScIhw0yK4MdFowUOwhNy6zGAwjQGHLlxWkrbjsOIXeIZPO7mGc4JcXeT3YfkajwmDvPeSCf0WGeKfacCfF3afkyZ …
```
> Fix faulty uuid calculation causing cache miss

- src/Modules/CalcMirages.lua
Fixes Tawhoa's Chosen not showing trigger rate on calcs tab (caused by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/7239). Fixes icdr calculation.
```
eNqtW0tz4jgQPmd_hYvzJIB5BKZgt0jIqypMWEhmdk9TwhagHVlibTkJ--u3JdnGIcjY2HPIGNT99UvdajUw-OPdo9Yr9gPC2bDWvGjULMwc7hK2GtZenm_Pe7U_fv9tMEVi_bS8CgmVK7__djZQzxbFr5gCX80SyF9h8T1Gav0EpA1iYo05m6B_uH_H3WHtG2e4Zi0Qc4mIXzkUBcE35OFhbYJ8FLrYr1kocDBzr3dL12uClwIRBgxrIHME9h-l9FEo-IS7QCL8EOA8oJlz5xcWdz4PN0q5V4LfNM3DZPo0e06pRlhaNbDsbDClaIv9uUDCCuDPsDYCB6EVHiMP_gIaoiFANRsX3V6_32717IZtd2r1TOar0A_EaQjzDcZuwtS46HdNlFMf3yyX2BHkFV_7RFyvEXN28homvqK0k5AKsqFERiq25cKo__0n8H7TRPvMBaLj6TztI7trt9rdRvey3exm83FxXP8fRKyvKHj0BCmS92HFiMAnMk85CTgrYV-a1RyikFJI01y0Mxxg_xUJ8lEtMzb3FoSd5L2Rj9HTUm_QGXJJGEyw8HGQ4NgXLWMOiN1Wa9lmY_5NE_Z7JsIxft9p3zZRPTCRgwqEpgm7GUJfufTzcSe …
```
> Fix tawhoa not showing trigger rate on calcs page

- src/Modules/Build.lua
- src/Modules/CalcSetup.lua
- src/Modules/ConfigOptions.lua
Updates the rewards from helping/killing bandits as well as Fellshrine Reward from the Through Sacred Ground quest.
~~Marking as draft for now as i'm not entirely sure whether the questPoints from acts are correct.~~ Reviewed by Regisle on discord. Should be ready to merge.
> Update bandit rewards and Fellshrine Reward

- src/Data/ModMap.lua
Just updates the wording of map mods (using my map mod exporter)
will add T17 map mods in a future PR
> Update map mods

- src/Classes/Item.lua
from https://www.pathofexile.com/forum/view-thread/3531661#itemchanges
RIP:
> Update quality multiplicative

- help.txt
- src/Classes/ItemSetListControl.lua
- src/Classes/ItemsTab.lua
- src/Classes/PassiveSpecListControl.lua
- src/Classes/SkillSetListControl.lua
- src/Classes/SkillsTab.lua
- src/Classes/TreeTab.lua
- src/Modules/Build.lua
Fixes #7667
Fixes #4569 
This is Subtractem's PR #6659 with my changes on top to account for allowing the same set to be used multiple times. Exact name match still works of course. Links are designated by identifiers within braces, comma-delimited. I JUST got this working so it's messy but we want people looking it over.
<pre>eNrtPdty2ziyz6uvYKlqz0tkGwABXnKS3ZLl6ya-jGUnk7y4QBK0mFCkQlK-TGr-_TRASiJlUZZseepkljtbjkSgG0DfuwFQ7_59Pwy1W5GkQRy9b-Nt1NZE5MZeEN28b19dHmxZ7X__q_XunGeDM393HISy5V-tf7xTn7VQ3Irwfds22lrGkxuRfZqg0q8B1YhH2UDE0Qn_FieHsfe-fRpHoq05PPKCbPLNDXmanvKheN_uD7gX37U1nroi8nqzhsskcL-nmUig-4An3IWPH-Xg3XEWn8QedPF5mAK2IQ-ifux-F9lhEo9H79u0rd0G4i7vdHxyfnZxWZpZEJVnBiv7x7vzkD-IpJ_xTEvhz_t2FwjEb8QeH8JfwMbDMaBiNrPRtt7eWQq0O07SbD3I_kgIb9Z52zYty6rrfJ6Ifd8Xbhbcil4SZL0Bj9zZUJhs26wO9jn9T8ZhFozCQHJiAlP …
> Add support for linking sets through Loadouts

- src/Classes/TreeTab.lua
- src/Data/ModCache.lua
Fixes #6567
Added a total tattoo counter to Replace Modifier popup. Text turns negative/red when number is >= 50 and the Add button is disabled (if we want to, maybe too aggressive).
Empty build with 50 tattoos set
<pre>eNrtHdty4jj2ufsrXFTtWzr4hjFTZKZIyIXapMNCunv3qUuxBWgiLNaWk2a-fiXLBodBjo1d6xd1VSdgnXN0LjoX2c7R8I9fa6y9wjBCJLjoGOd6R4OBR3wULC86355uvridP37_PJwCunpcXMYI85HfP38aJp81DF8hvuj0OxoF4RLS7xkl6yejtAEBXUESPIA_SXhL_IvOVxLAjvYMAh_R7JuHQRR9BWt40Zl7DLmjgciDgX-1v54CrkAIPArDez7rKKbkgfhslIYxG10DFMyJ9wLpbUjiDROmo70i-CZgJg_Tx9lTjiUU5FliEn0aTjHYwnBOAdUi9uOiM2KKAUs4Bmv2k1EDOIZcSbZhWgN70OsPXMvsdAuRL-MwoqdRmG8g9HNIUsBpCK8XC-hR9AqvQkSvViDw9tPpMryqsA8xpmiDEQxzXPVkGHd_I-5aMtgnQgEeT-c5us7AdvuZkorxCP2Y_x-Iri4xU-gJs3DcyTJAFJ6IPCUoIkEN-fKochPFGDPvLAU7gxEMXwFF79mS0ybrZxScpL0HEIArEpWwEYecwpA5P62EMIceYfGi6hwV …
> Show total tattoo count when adding tattoos

- src/Classes/TradeQuery.lua
- src/Classes/TradeQueryGenerator.lua
Fixes #7139 
Adds abyssal sockets to item trader under their respective items. Follows socket/jewel tradeQuery logic with the exception of only Abyss jewel option. Total possible number of slots in the popup increased so I had to tweak the scrollbar magic.
Easy to test with any abyss unique like Darkness Enthroned, but I am adding a build that has every possible socket and abyssal socket active to show off the item trader scrolling is all good. The build has a no gear itemSet and no socket treeSet to play around with the total number of slots.
<pre>eNrtPWtT48ayn-NfoXLVuZXU2qDRyxIXcsqAYUlg8WJYQr5sCXtsK8iSkWSMk9r_frpnJOuBJEuYnHuTsJvayDP9mp6e7p4ePfb__TyzhSfq-ZbrHDTJjtgUqDN0R5YzOWjeXJ-09ea_f2zs981gejk-XFg29vzY-G6fXQs2faL2QVNXmkJgehMafIlIyV-B1Nx0gil1nQvzN9c7dUcHzU-uQ5vCvemMrCD6NbRN3_9kzuhBczAE5 …
> Add Abyssal Sockets to Item Trader

- src/Classes/TreeTab.lua
Fixes #6946
Adds a Remove All Tattoos button to the Reset popup on the TreeTab.
- Checked a few different Ancestor builds with lots of tattoos by making a copy of the tree, removing the tattoos from one and using the hover comparison to confirm changes
https://poe.ninja/builds/ancestor
<pre>eNrtfdty28ay6HP4FShVZb-YsjBXANnO2qWbJcWWpUhynOTFNQAGIiIQoAFQsrJq_fvpHoAkSBEUKMrJco7jKkUCunume_o6N7z6v8_DxLrVeRFn6Y9b5KW9Zek0yMI4vf5x6_3V62136__-1Xt1rsrBWbQ3jhN886_ed6_M71aib3UCeDbglSq_1uUvE1rsIzwbqbQc6Cw9VX9k-VEW_rj1Lkv1luWrNIzLyV9BoorinRrqH7cuVHqt8y1LFYFOw_3ZiwOtQn2PwAOVq6DU-Vtse3dcZqdZCACRSgp4PVRxepkFN7o8yrPxCPq2Zd3G-q4Curo4PGz0Kk6bvQK2vnt1nqh7nV-WqrQK-PHj1i5IR13rAzWEn0BLJWMg5AoiPP5Scuk6RLhbOyuR98Z5UT6NwuVI63CKJF4yIWkb7HmuD6NIB2V8q_fzuNwfqDSYtYij1IK5BNpzVwGfjpMyHiUxjtW0b1S2oRyvQf4qK1VycH45BeVCEkbIS8od …
> Add support for removing all Tattoos

- src/Classes/CalcsTab.lua
Minor change, useful for future updates to it, and I am planning on doing other things around it so using this as a placeholder PR
The idea is to update the formulas used for this, and potentially move the function to data to be with the list to be easier to update, as one reason it probably hasnt been updated is due to how "out of the way" it is
> Move power calcs offence, defence calc to its own func

- src/TreeData/3_25/tree.lua
- src/TreeData/3_25_ruthless/tree.lua
Fixes #7722
node pathing was wrong, also reordered nodes so they are in order of in->out
> Fix tree pathing

- src/Data/Uniques/belt.lua
https://www.pathofexile.com/trade/search/Standard/gQjaOGaFQ
> Add missing strength roll to Kaom's Binding

- src/Modules/CalcPerform.lua
- src/Modules/ModParser.lua
Implements parsing for `Warcries Exert twice as many Attacks` from the Berserker ascendancy
> Implement handling for double exerts mod from berserker ascendancy

- help.txt
- src/Classes/ConfigSetListControl.lua
- src/Classes/ConfigTab.lua
- src/Classes/ItemSetListControl.lua
- src/Classes/PassiveSpecListControl.lua
- src/Classes/SkillSetListControl.lua
- src/Classes/TreeTab.lua
- src/Modules/Build.lua
- src/Modules/ConfigOptions.lua
Fixes #2794
Fixes #899
Add ConfigSets, similar to skill, item, or tree sets. This includes a change to the Config xml to use the ConfigSet elems with Input/Placeholder children vs a dump of one set of Input and Placeholder elems. Backwards compatibility accounted for. There's probably some refactoring/cleanup I can do, but I wanted it out there for feedback.
- Test new build can create, delete, copy, rename
- Test new build saves and loads and loads correct activeSet
- Test older builds that do not have the new xml structure and validate save successfully
- Test importing and exporting old/new structure builds
- Test custom mods carry over
Here's an older build with multiple config changes including Custom Mods <pre>https://pobb.in/HmQ8HnyI9fhT</pre>
Loadouts Update:
Added ConfigSets to …
> Add support for multiple configurations

- src/Modules/Build.lua
Before this change the information about selected loadout in dropdown is lost on closing and reopening build. With this change it tries to match selected loadout with active tree.
https://pobb.in/j3Z597YrowzK
> Preselect current loadout based on currently selected tree

- src/Data/Uniques/amulet.lua
- src/Data/Uniques/sword.lua
update uniques to changes in <https://www.pathofexile.com/forum/view-thread/3532389>
> Update Settlers uniques

- src/Modules/CalcDefence.lua
fixes issue introduced from bad merge resolution in #6809 removing a line it shouldnt
> fix crash from avoidance chance

- src/Data/ModCache.lua
- src/Modules/ModParser.lua
The match was cutting off the `ing` on the end of the word
> Fix "damage with Bleeding" mod not working

- src/Data/Skills/act_str.lua
- src/Export/Skills/act_str.txt
I incorrectly applied to the Phys damage bonus to melee damage instead of melee skills
> Fix War Banner not granting damage to Bleed

- src/Data/SkillStatMap.lua
I forgot to change the mod to the MORE variant
Fixes #7808
> Fix Valour incorrectly granting increased Aura effect instead of more Aura Effect

- src/Data/Skills/act_dex.lua
- src/Export/Skills/act_dex.txt
The mod was removed by accident in #6976
> Fix Blood Rage not granting Attack damage leech

- src/Data/Uniques/ring.lua
Elemental Catalyst is not applying to the new taming.
- Add Taming
- Catalyse it
https://pobb.in/WbBXp-M1TW_U
> Fix elemental catalyst not applying to new The Taming

- src/Modules/CalcPerform.lua
The mod is not meant to scale as it's not a buff
> Fix Seismic Cry more AoE mod scaling with Buff Effect

- src/Modules/Main.lua
initialedgeSearchHighlight  -> initialEdgeSearchHighlight
> use camelCase

- src/Data/Skills/other.lua
> Update Death Aura damage with 3.25 changes

- src/Modules/Build.lua
Fixes: #7835
https://pobb.in/3LAWvD5YpWP7
> Relax matching for loadout names and allow groups at any spot

- src/Data/Skills/act_str.lua
- src/Export/Skills/act_str.txt
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/7891 .
- Changed effect type from aura to buff (as per GGG answer https://www.pathofexile.com/forum/view-thread/3532389#47)
https://pobb.in/8dZkMwwDh6Fe
> Fix Flesh and Stone less damage taken scaling from Aura effect

- src/Classes/Item.lua
- src/Classes/ItemsTab.lua
- src/Modules/CalcPerform.lua
Based on the Q&A tinctures do have quality and it increases the effect by %MORE
> Fix quality not applying to Tincture duration

- src/Modules/CalcOffence.lua
The mod was not recalculating the AoE function sometimes
Fixes #7899
> Fix Seismic Cry AoE mod not applying sometimes

- src/Modules/CalcOffence.lua
The mod wasn't checking to see if their was a source of CritMulti override
Fixes #7917
> Fix Maligoro's Virtuosity not working with Perfect Agony

- src/Modules/CalcPerform.lua
fixes issue caused by #7853
cant use a full modlist becouse its recursive for copy table
> Fix Partytab Mine Export Crash

- src/Data/Skills/sup_str.lua
- src/Export/Skills/sup_str.txt
- src/Modules/CalcOffence.lua
Simpler implementation of Fist of War AoE.
Build Code: `https://pobb.in/lLadZBag9Gey`
> Fix AoE from Fist of War not applying to supported skills

- src/Data/Bases/staff.lua
- src/Data/Uniques/staff.lua
Updated all the implicits to match the new block values
Fixes #7921
> Update unique Staves with block changes

- spec/System/TestImpale_spec.lua
Wanted to do more than just rename the variable, but I will just do this to fix the failing tests
> update impale tests

- src/Export/Classes/GGPKData.lua
command propt has a limitations in character and the cmd fails silently
this PR allow to extract Data, It and Medatada independently instead of together
Data:
Metadata:
It:
> Fix cmd extraction files with Bun

- src/Classes/ExtBuildListControl.lua
- src/Modules/Build.lua
- src/Modules/BuildList.lua
This feature needs a lot more consideration before implementation.  This PR is intended as a temporary fix while we focus on league-specific changes and updates.
> Remove remote build list functionality pending redesign

- src/Classes/ConfigTab.lua
Fixes #7984
- Loaded given build
- Exported and reloaded build
- Created, renamed, deleted config sets
https://pastebin.com/Xx3EAYWC
> Fix issue where empty configs were not loaded properly

- src/Modules/CalcPerform.lua
fix quality for tinctures
Fixes # .
-
-
-
> Fix quality for tinctures

- src/Data/Uniques/Special/Generated.lua
The phys taken as mods are now legacy
> Add tag to Legacy Watchers eye mods

- src/Data/Skills/other.lua
- src/Export/Skills/other.txt
The damage effectiveness should have been 1 not 0
Fixes #7895
> Fix Added Damage not applying to Monster Explosions

- src/Modules/CalcOffence.lua
The Poison stacks mod was applying twice causing massive DPS increases
Fixes #7965
> Fix Poison stacks applying twice to Poison DPS

- src/Modules/CalcTriggers.lua
> Fix Svalin relateed nil dereference

- src/Modules/CalcTriggers.lua
Fixes #8019
Currently warcry triggers simply use the uptime ratio to scale source rate. This does not take into consideration maximum exerted attacks count that a single use of a given warcry allows for.
This pr changes the calculation to first calculate the amount of exerted attacks that current source rate allows for during duration of a single warcry cast capped by max amount of exerts. Then it sets the new source rate to the calculated amount of exerted attacks per every use of warcry (cooldown + duration).
Additionally this pr replaces the hard coded tick time constants with the variables from the data table in trigger simulation and fixes issues with some skills that cannot exert attacks still triggering the warcry effects.
- Test Battlemage's cry
- Test …
> Fix Warcry trigger rate calculations

- src/Modules/CalcPerform.lua
I can't think of a better way to handle this
Fixes #8017
> Fix Autoexertion not applying Mana reservation to Warcries

- src/Modules/CalcOffence.lua
Updates the breakdowns and makes the single poison config work again
> Fix Poison stacks not being capped by skills and config option

- src/Data/Uniques/Special/New.lua
The unique item was updated in 3.25.0d, checked wording using item ingame and trade, mod works as is
> Update Sap of the Seasons to add new cap

- src/Modules/CalcDefence.lua
Tested with the build in #8073 and many of the values were off by one
Messaged the player in game and changing the round -> floor fixed all the final values
> Fix Ward rounding final value incorrectly

- src/Modules/CalcPerform.lua
Order of operations error
Fixes #8052
> Fix Divine Blessing not removing reservation from skill

- src/Modules/CalcMirages.lua
Added support for overexertion. Also allows any other support gem that would increase Exerted damage to work
Fixes #8038
> Fix Overexertion not applying to skills linked with Generals Cry

- src/Data/ModCache.lua
- src/Modules/CalcPerform.lua
- src/Modules/ModParser.lua
adds support for some warcry power modifiers, the minimum 10 power, and the %increased power
> Add support for some warcry power modifiers

- RELEASE.md
- help.txt
Updates RELEASE.md and help.txt to explain how to update the Timeless jewel "look up tables"
> Explain Exporting Timeless jewels in RELEASE.md and dev help txt

- src/Modules/CalcPerform.lua
This makes the rallying cry values showup as part of the buff, and makes it possible to support for party tab
This does change rounding a bunch, but I believe the values were incorrect before, the values now line up with the math better in the few cases I tested but it likely needs more testing
The other issue is the value isnt rounded internally, I can fix this but unsure if it matters, and so did not for performance reasons
> Fix Rallying Cry damage rounding

- src/Modules/ModParser.lua
Fixes #8234 .
Path of building is not adding rage when Bloodscent is added.
- Take Bloodscent.
- Check configuration tab.
- Play with Rage value - DPS changes.
```
eNrtfVlznEjW6HPXryAUMffFWsgV8LXni9Iut2TJWuz2vDgSSFRYFJSBkqyemP9-TyZQBVVQQtvM9Hc9HSMXcE6ezJNnzfXd__wcR8atTLMwid-voU1zzZCxl_hhfP1-7epyf8Ne-5-_D96diXx0GmxPw0h9-fvgt3f6txHJWxkBngl4uUivZf65Kot8g3cTEecjmcQn4nuSHiT--7WPSSzXDFfEfphXT14ksuyjGMv3axcj4Sd3a4bIPBn7O_MPl2no3WS5TAF8JFLhwc9jRX04zZOTxAeQQEQZlDYWYXyReDcyP0iT6eT9Gl4zbkN5VwAdnZydnl_WahbG9ZpB0357dxaJe5le5CI3Mvjzfm0IHBLXcleM4S-UJqIpFEUIohzhTcIZQZyuba1E3p6mWb5YAjM5YfamwzmyEOkq4WIipT9D4puEWjbHXdBnqdwLAunl4a3cScN8ZyRib07TNjdt6vAu7KdhnEyjPJxEoeqeEott4k6UwyUaSoI6gC-TXES7ZxczWIxMalom2rQtm2G8Gi_JZ3idFLYj4G-dAnIo3XQshm2bm5bThfclzEdLuKp2mFO-aTNiI7QK9-g6DnP5hKYp5LMkzJL4GXx5QoN3plEE-l_H7GTqucxk …
```
> Fix Bloodscent not making rage eligble.

- src/Modules/ModParser.lua
GemProperty mods were not being affected by scale. I don't think we have any cases where this would matter in POB1 but thought i'd make a pr here too.
https://github.com/PathOfBuildingCommunity/PathOfBuilding-PoE2/issues/223
> Fix GemProperty mod not being affected by scaling

- src/Modules/BuildSiteTools.lua
Add poedb.tw to import website list
> Add poedb.tw to import website list

- spec/System/TestDefence_spec.lua
- src/Modules/CalcDefence.lua
- src/Modules/Data.lua
Back port of https://github.com/PathOfBuildingCommunity/PathOfBuilding-PoE2/pull/552
> Improve EHP accuracy

- src/Classes/BuildListControl.lua
Closes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/1823
Implements lua side code for https://github.com/PathOfBuildingCommunity/PathOfBuilding-SimpleGraphic/pull/63 allowing for deletion of folders with contents.
> Implement ability to delete folders with contents

- src/Modules/Calcs.lua
> Fix "Full Poison DPS" value capping to one stack

- src/Modules/CalcOffence.lua
Should be fine to insta-merge as they're only comments.
threshhold
Controlls
> fix-typos-comments

- src/Data/Uniques/Special/New.lua
Fixes #8464
Got some variants crossed when implementing the wording on these jewels
```bash
eNrtHNly27r1Of4KjGbalyq2uGhz7duRd_faiSo5SfN0ByIhiTVEKCRoR-nk33sAkBRFC1wktdOH5MGRiLPjbDgkdfa37wuKXkgQesw_bxjHrQYivsNcz5-dNz493bzvNf7229HZEPP5x-lF5FGx8tvRuzP5GVHyQuh5ow9oHAczwj8npKw_4NoS-3xOmP-I_8WCW-aeNz4wnzTQBPuux5NvDsVh-AEvyHlj7AByA-HQIb57ub4eA85xgB1OggfBdhBx9shcWJ1iGsLyAnv-mDnPhN8GLFqCOg304pFXBXT_OPw4esrI5PlZmUCnd2dDilckGHPMUQh_zhsDMA2ekTuPAylMI6DTt1vH7cZJIfxFFIT8Ci_gYzW88ZIQNwU1jm2z1-4a8V8d0jAg19Mpcbj3Qi4Dj1_Ose-sGbZ0eHVhHyPKvSX1SFAOf_eGtNHSAj8xjunVcLyGtWzruFxxhcd4uThfPD6_oGDbHbgI3PuZ73GyI_KQeSHz99Avi6rfoYhSiMlKsCMSkuAFc29TLD1ttph4_k7We8Q-vmTheo8sswh0SAIIeb6B0SpBGBOHQZbIotjt41Qys9epwHE7HS3rB29KqkPW0ipGqCvNbnpcj6vC1Sa8m0AjyJXVIMcsohUh-TpjmVqoK_I9k6y0KfreX3PstPUR9i0LaLTberYvjMtqV6aGTAfXd8MUstuzj3t9 …
```
> Fix various issues with Legacy of Phrecia ascendancies

- src/Data/Uniques/Special/New.lua
Adds jewels for the new ascendancies
Adds 2 mods to other ascendancies that GGG noted on twitter
> Add Wildspeaker, Blind Prophet, Aristocrat and Puppeteer jewels

- src/Data/ModCache.lua
- src/Data/Uniques/Special/New.lua
- src/Modules/ModParser.lua
Still needs parsing check afterwards
Someone double check my spelling :D
> Add Ancestral Commander, Behemoth, Bog Shaman, and Scavenger Ascendancy Jewels

- src/Data/Uniques/amulet.lua
Eyes of the Greatwolf DoT mod Wording fix
Fixes # .
This mod is currently not recognised. 
-
-
-
> Fix Eyes of the Greatwolf DoT Multi wording

- src/Classes/ImportTab.lua
Fixes #8498 .
Refactored influenceInfo table from last week didn't get updated everywhere
- Imported the character in the issue, verified influences were present
> Fix influences not importing correctly

- src/Data/ModCache.lua
- src/Data/Skills/other.lua
- src/Export/Skills/other.txt
Regenerating the ModCache wiped out the ascendancy mod because they didn't come from the unique jewels anymore.
> Add new Harbinger skills

- src/Modules/Build.lua
- src/Modules/ConfigOptions.lua
Partially Closes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/8453
Adds a warning for when more than one Aspect skill is enabled. Having more than one Aspect active is impossible in game.
```
eNq9HGtz2zbyc_QrOJq5m3Z6tkTqEdtntyO_PWPHquQkd586EAlJaCBCIUE7aqf__XYBvqQIFCmq18wkJLFvYBe7C6jnv3xbcOuVBiET_kXTPm43Leq7wmP-7KL58eX26KT5y8-N8yGR8-fpZcQ4jvzceHeuni1OXykHvKYlSTCj8lNCqfMbUFoSX86p8J_I7yK4E95F84PwadOaEN9jMnlzOQnDD2RBL5pjF5CbFgld6ntX2fcYcE4C4koaPCLXQSTFk_BgVAYRjC4I88fC_ULlXSCiJYjQtF4ZfdMwD0_D59FLTiTm50UCjd6dDzlZ0WAsibRC-OuiOQDDkBm9Jgv4G6gRHgEpu3_c7_adXrNViHUZBaGsiDpeUupl0MdtxwQ5DOjNdEpdyV7pVcDk1Zz4bsaobcKrCvsUccmWnNEgJ5ZR_vvviBtBX4Qk_Ho4ztvm9P2p_X4HhpC7Bf_M5PySgykr0Uesh5nPJK2MNhQsFP5e2uSRzDMRcQ5-Vwp2REMavBLJ1gUy0xaLCfMr2moQUPI81StwRDwWhU9UBjRMKTjHtgn3ifjkSoTZPNpOEeiQBhAN5BpG …
```
> Add a warning when more than one Aspect skill is active

- src/Modules/CalcDefence.lua
Adds information on what resources would be used (and what would be left) after taking a configured enemy's hit.
<pre>eNrdXetz20aS_xz-FVOsypVdJiW8Seqk3aJelrKSrYhynNwX35AYkohAgAYGkugt_-_XPYMXaQAEH3ayZ285EtDdM_2b7p7ueWCP__kyc8kTC0LH906a6oHSJMwb-bbjTU6aHx4u293mP__ROL6jfPp-fBo5Lr75R-OnY_EzcdkTc4FPAT5OgwnjvyWy9E_wbE49PmW-d0v_9IO3vn3SfOd7rEmG1LMdnvw2cmkYvqMzdtK8pQGNbBY0CQ1HzLPPsle_RJMJCzwaceCYAt2Is-AGO9CPuH_r20Azpm4IAmfU8Qb-6JHxt4EfzU-anSZ5ctizJLq-vXt__5DrnOPlOwfa_XR859IFCwacchLCPyfNM382dDxmn98NQBZ1IxCkNA-LiQc8WE90zz7n6VTTLKM8Zy-1xOXpVNMqo7z2eC1xeTpV08p79-RzGPL1Mh98Tt2Lq7tMqq5pZu_AMDuW1lFLW7ibLkJnRN1b-uLMotmVwx_oI_NyYhTFLG31xplMuQdmW8quaZ2eWsZ-6QSsirNT2u0z37W35JxSPyxlVapYb5wxy5HCn1IjnbPREZJfe6P1Y4eEH7yAhSx4Yna9FpDnno18iC906LL6TFlDdyyAMMDzrNWtTZgXN7mow3RLPVrDnxEqJK0FFRIWd6SU5cJjwWQxmDrMzbA1K1DKMy …
> Add resource lost information to enemy damage breakdown

- src/Export/Main.lua
copy-pasta from pob2 repo
Ref: [#529](https://github.com/PathOfBuildingCommunity/PathOfBuilding-PoE2/pull/529)
> feat: exporter: add clear output button

- src/Modules/ModParser.lua
Aquamarine Flask has 60% reduced effect of freeze on you. Worky now.
- Checked that it only applies when flask is activated.
> Add support for Aquamarine Flask "reduced effect of freeze on you"

- src/Data/ModCache.lua
- src/Modules/ModParser.lua
<pre>eNqtW-tz2roS_9z-FR5m7qebAn7wOkN6hoSkyZmQcCBp7_nUUWwBamSL2nISeuf-73cl2WAoMjYmfcRY-9uXVivt2vT_fPep8YrDiLDgvGbWmzUDBy7zSDA_rz09Xn_q1v78_LE_RnzxMLuICRUjnz9-6Mtrg-JXTAHXqxkchXPMv6as7O_AaokCvsAsGKEfLPzCvPPaPQtwzXhGgUd4-smlKIrukY_Pa1MXwDUDRS4OvMvN_YRwgULkchzeCbGDmLMR82CUhzGM-ogEU-a-YP4lZPEStKoZrwS_KZrb0fhh8phRiQRZlcCkD_0xRSscTjniRgT_ndcG4Bk0xzeEAytEY-DT7Tn1rmm1ao1cyEUcRnyIfLgsDJ0uMfbW1Gbdzv7oQOMQX81m2OXkFV-GhF8uUOBuZLZ1uLK0o5hysqQEhxkNtabc_MbcbDZ1xI-MIzocTze0Zs-uN7uHTFc4tpkby-l0691e19QhvhG-AEBWlt3umHWAOPmyBPKCwvwcoafA3s4DwvGR4DEjEQsqeCgLPeiky5hSWORZjHbqJjjC4SviZFs9Lf0l859JsO3FgjMwCDF6mKlYnyCPxNEI8xBHG8N0yBEK0CWLMnHSyiMd4xCyD99CNA8ApthlkLCyENuuF1m_GYn7-WhF35EZLk5ZyqoEUFab4-y4mhalK834OIUmkLSLUU5ZTAtS8k3etLVUQ_yeWeLaKL0NMrGcszZ_ZgnNVksv9pVxufEeMkMmlKubcWYpNetNq-W0WnbbMrVLcLxYRcRFdITeiR_7sD08ohe …
> Add support for Cold Dot Multiplier Per Overcapped Cold Res Mastery

- CONTRIBUTING.md
Brings the section up-to-date with version `0.9.22` of the EmmyLua VSCode extension.
> Update EmmyLua VSCode debugging tutorial

- CONTRIBUTING.md
* consolidated debugger snippet insertion instructions
* fix(?) snippet indentation (spc->tab)
> Update EmmyLua VSCode debugging tutorial 2

- src/Classes/ModStore.lua
- src/Modules/CalcSetup.lua
Fixes #8744
Needs to be handled later to work with nodes on the tree.
Not sure if removing the restriction for scaling a mod below 0 will cause issues elsewhere
> Fix Runegraft bonus for Boots / Gloves not working

- src/Modules/CalcOffence.lua
Fixes a visual bug introduced in  #8763
Aura effect values were wrong in the Calcs tab if you had the aura mastery for 10% increased effect of auras on you.  This was introduced because of the logic for Hand of Phrecia, but really needed to just be updated for auras that affect enemies
- Equip Hand of Phrecia, see Pride still doesn't function
- See aura effect value change between Pride and a self aura
```bash
eNrtPWt32zayn6tfweNz9n6JExNvIjfZe-Rn3MaJYzlJs196QBK02FCkSlJx3D373-8ApCRSJiX5kex22320FjkYAPPCzGBAvPi_r5PE-aLzIs7Slzvombvj6DTIwji9ernz_vL4qbfzf38fvDhX5fhttD-LE_Pm74MfXti_nUR_0cnLHUl3nFLlV7r8MEdFfgFUU5WWY52lZ-rXLD_Jwpc7b7JU7zi-SsO4nP8KElUUb9REv9z5GJfBeMdRRaDT8GD5_CjRE52WKomLEhqMVa6CUuevTffDWZmdZSFARSopAN9ExekoCz7r8iTPZlOYFtlxvsT6uoI6PTt_e3HZGFycNgcHk_vhxXmibnQ-KlXpFPCPlzsH2cSPUx0eno8Al0 …
```
> Fix Aura effect scaling when using Hand of Phrecia and  "effect of auras on you" mods

- src/Data/ModCache.lua
- src/Modules/ModParser.lua
Fixes #8837  .
This is a partial revert of #8409, where it was ported over from PoB2.  PoE2 doesn't have a concept of socketed gems, so the PR wasn't directly translatable.  It also missed adding the `keyOfScaledMod` parameter to gems from all skills (lumped in a different section in the PoB2 codebase)
- Import the build from the issue
- Equip March of the Legion and ensure levels don't go down when at +5
- Equip Admiral's Arrogance and ensure scaling doesn't bump it above 3 and increasing it to 5 gives it an extra level
- Manually add other level mods like these and ensure they stay at level 10:
```
Grants level 10 determination
Socketed gems are supported by level 10 increased area of effect
```
```bash
eNrtfWtz27a26OfqV3A8c-7sTmWbeJLMTfYZ2Y4dd9uJYzlt2i8dkAQtJhSpkJQdp9P_fhYAUiJlUpZsZ5_bO …
```
> Fix issue where socketed gem modifiers were scalable by Runegraft of the Bound

- src/Data/ModCache.lua
- src/Data/Uniques/flask.lua
- src/Modules/ModParser.lua
We didn't update Cinderswallow when it was changed in 3/26 to add some new mods and remove old ones
Fixes #8884
> Update Cinderswallow and support new mods

- src/Data/Skills/act_str.lua
- src/Export/Skills/act_str.txt
The skill critically strikes every 3rd use but we were not calculating that at all
> Fix Glacial Hammer of Shattering missing crit chance every 3rd use
