PathOfBuildingCommunity/PathOfBuilding

Data/3_0/SkillStatMap.lua

Toxic Rain and (Vaal) Rain of Arrows
Should solve #31.

Fix for skills with 'cannot_pierce' stat

---

Classes/CalcsTab.lua
Classes/ItemDBControl.lua

* Use minion stats for item sorting and tree highlighting if a minion skill is selected, player stats otherwise. Should solve Issue #5 
* Items are now sorted by the highest bonus they can provide given all possible slots that the item can be equipped in.

Hotfix minion dps sorting

---

Classes/Item.lua
Classes/ItemsTab.lua
Data/Uniques/jewel.lua

And new tag for items: `Has Variants: x` where x is a number of... interchangeable mods or even mod sets?.. For ordinary uniques it is 1 -- legacy variants, for Synthesis Rings and Eyes of Greatwolf (things with 'Has Alt Variant' tag) it is 2, and Watcher's Eye is 2 or 3. Items with x less than 3 should be working as is, so there (probably) no need to set it explicitly for everything in Uniques/*.txt.
However, it probably shouldn't be in next release because I didn't properly tested it, especially compatibility with builds and items created in non-fork pob.

Triple watchers eye

---

Data/3_0/Skills/sup_str.lua
Export/Skills/sup_str.txt

Fix for issue #25 
Sidenote: VaalArcChains CanBeLucky gets overwritten(=removed) when exporting skills, might be missing in txt file

Rage support no longer grants added physical damage if unarmed

---

Data/3_0/Skills/spectre.lua
Data/3_0/Spectres.lua
Export/Minions/Spectres.txt
Export/Skills/spectre.txt

This PR adds Crazed Driver and a bunch of bow-skill-using spectres.
I've made a best-effort with skills like Elemental Hit and Explosive Arrow that the UI doesn't support yet. Unfortunately the Export scripts *also* don't seem to play nice with multiple copies of a skill so this is the best option without deeper modifications. At least Explosive Arrow should be more straight-forward once the patch drops anyway.

Add a few new spectres

---

Data/Uniques/staff.lua

Implements https://feathub.com/LocalIdentity/PathOfBuilding/+73
Also readded Dying Breath's old version which can still be obtained and is able to grant more block chance.

Fixed some regressions regarding staves

---

Data/Uniques/jewel.lua
Modules/ModParser-3_0.lua

Karui and Maraketh Timeless jewels will now add extra attributes to passives in radius.
Eternal Timeless jewels will now remove all normal passive modifiers in radius.
Keystones are still not supported.
Also fixed some jewels not displaying correctly, including Timeless jewels.

 Added support for deterministic passive modifications from Timeless jewels.

---

Classes/CalcBreakdownControl.lua
Modules/CalcSections-3_0.lua

Currently there is no breakdown for the row "Base from Armours" for ES/Armour/Evasion in the Calc tab. This commit adds that.

Add breakdown for "Base from Armours" row for ES/Armour/Evasion

---

Classes/EditControl.lua

Added ctrl-right and ctrl-left to edit control, mainly for notes tab.
tested on text "The quick'tab'brown'space''space''space''space'fox, is silly." , along with other random text supplied by build builders.
Tests include have the cursor start in the middle of the four spaces.
Integrates with selecting text.

Add ctrl-right and ctrl-left to edit control - skip word

---

updatemanifest.py

* Works with arbitrary file extensions
* Doesn't lock files after use
* Can't be run as a script accidentially
* Doesn't shadow built-ins
* Uses f-strings

Refactored manifest updater

---

Data/Uniques/ring.lua

In 3.5.0, Malachai's Artifice has been changed to remove the "Socketed Gems have 40% reduced Elemental Equilibrium effect" mod from all variants.

Remove legacy variants on Malachai's Artifice

---

Modules/CalcActiveSkill.lua

Fixed Rage and Chain Hook not applying Rage attributes. This was due to their mods not being added to a global mod list. 
Side effect of this is that Withering Steps and Withering Touch now correctly add Condition:CanBeElusive/Condition:CanWither to the global mod list.

Rage Support Fix

---

Modules/Data.lua

mods are given source values in 
`processMod(t._grantedEffect, mod)`
however since `verData.skillStatMap` is a shared table containing mods that are also meant to be shared between skills no skill specific source should be written to those instances.
the already present 
`copyTable(map, true)` did only do a shallow copy. So changing it to `copyTable(map)` will do a recursive copy and allow us to set skill specific stuff down the road.
Another subtile bug was doing the shallow copy, setting it to `t[key]` but later on returning the unmodified `map`. That is why `map` gets overwritten here, so we can use it as iterator for the deeply copied mods, that got now relevant, and as the proper return value that it always should have been

make deep copy of skill stats so they can have distinct sources

---

Modules/CalcOffence-3_0.lua

When I added in the new elemental ailments stuff a while ago I left in two lines that set your "chill chance", a non-existent stat, to 100%. This is leftover from the first way I tried implementing the Calcs tab stuff where I basically just copy and pasted the Freeze calcs and changed them to say Chill instead, but the final implementation doesn't need these lines.
ANYWAY, these lines come after the parts that check for whether you can apply each ailment, so even if you can't chill like when you're using Elemental Focus, the Calcs tab would show you could chill. This fixes that.

Fix Elemental Focus Support and Chilll

---

Classes/Item.lua

Items copied into the items page will keep their quality unless the item has less than 20% quality.
This adds support for quality mods on items that have had a perfect fossil used on them to raise their base quality above 20% or has a quality enhancing mod as an affix.
Previously, items would import as 20% no matter what

Copied items will now retain quality if above 20%

---

Modules/ModParser-3_0.lua

My first commit. Picked something I thought was easy. Hope I got this right.
Looks like the mana reserved mod was just not set up on this modifier.

Fixed "Socketed Skill Gems get a X% Mana Multiplier" modifier not working on skills which reserve mana

---

Data/3_0/ModCache.lua
Modules/ConfigOptions.lua
Modules/ModParser-3_0.lua

Added "# of Summoned Minions" combat configuration to support 'per minion' modifiers. Only affects Necromancer Bone Barrier notable at this moment. Also cleaned up the related duplicates in ModCache.

Added support for 'per minion' modifiers for Necromancer Bone Barrier notable

---

Export/Skills/spectre.txt

Enfeeble and Temporal Chains cast by minions should have weaker effect on rares and uniques.

Fix minion curses not applying weaker effect to rares and uniques

---

Data/3_0/SkillStatMap.lua

Fixes bug under https://github.com/Openarl/PathOfBuilding/issues/1848
Increased melee damage quality stat missing in SkikllStatMap. Only affected gem was Shockwave Support.

Fixed Shockwave Support quality stats not included in damage calculation

---

Classes/PassiveTree.lua

Fixes #92 
Sanctuary is both a notable and an ascendancy notable. The notableMap indexes all notables, including ascendancy notables, by notable name. This gave an unexpected result where the Inquisitor Sanctuary node was allocated  #instead. notableMap is currently used only for granting passives via anointment. Since notables in ascendancy classes cannot be granted via anoint, I've decided to remove them from the map. If there are use cases in the future for ascendancy notables, then we can create ascendancyNotableMap or allNotableMap maps.

Fixed Sanctuary anoint incorrectly allocating Inquisitor notable passive

---

Data/3_0/SkillStatMap.lua

Close Combat could previously be supported by all weapon types when it is specifically only meant to work with Axes and Swords

Close Combat can now only be supported by the correct weapon types

---

Classes/GemSelectControl.lua

Fixes a bug where when searching for gems, it would assume all gems had a max level of 20, which meant that things like awakened gems and Blood and Sand were previewing as way more damage than they actually give. Now it uses the gem's set defaultLevel.

Fix default gem level for gems with a max level below 20

---

Modules/ConfigOptions.lua
Modules/ModParser-3_0.lua

Adds support for the mods on the Asssassin notable "Opportunistic" that count nearby Rare or Unique Enemies, using a counter config option. The counter also adds to the generic "nearby enemies" counter, though I'm not sure if that's an interaction that would ever come up.
It also has support for the crafting bench mods for "While there is a Rare or Unique Enemy Nearby". These mods will now be enabled like it always has if the enemy is set as a boss, but will now also enable if this new counter is >= 1. This is an extremely niche case that may not ever actually be used, but I figured this counter should correctly imply everything it should. If I missed any other niche cases, let me know.

Improve support for Assassin notable "Opportunistic"

---

Modules/CalcPerform.lua

Fixes #165, but found 2 bugs overall with the calculations.
- Active totem limit was only calculated based off one skill, meaning that if you had multiple skills with different active totem limits, only one of the skills with have the correct value.
- Increases to maximum number of ballista totem were ignored

Fixed incorrect calculations of Active Totem Limit

---

Export/Minions/Minions.txt
Export/Skills/act_int.txt
Export/Skills/minion.txt

This adds skitterbot minions and fixes #108 . They don't do anything but can be supported by Infernal Legion. I also added the Skitterbot Wait skill because they get a Default Attack if no other skills are present. I thought that might be misleading as they cannot attack.

Add Skitterbot minions

---

Classes/Item.lua

ParseRaw was failing to flag certain mods as EXPLICIT when they contained a ":" character such as Pure Talent jewel.  Looks like this fix was the last piece for supporting the mods on Pure Talent.

Fixes Item Parsing For Explicits That Contain ":"

---

Modules/Build.lua

Moves the resistances over max next to their prospective resistances in the left pane.
Removes old labels for resistances over max

Consolidate resistances into single line in sidebar

---

Data/3_0/SkillStatMap.lua

Adding missing mods in skillstatmap. Tested in-game with zealotry which shares the same mod, but as an aura effect instead. The interaction is working as expected.
Fixes https://github.com/Openarl/PathOfBuilding/issues/1856

Fixed Cast On Critical Strike support quality stat not included in damage calculations

---

Data/New.lua
Modules/ModParser-3_0.lua

Adds support for "increased Adrenaline duration". "increased Fortify duration" is already supported, but both are not shown anywhere as they are not that interesting for build planning. Also adds a display-only modifier for "You can have two different Banners at the same time". Currently, there are no checks in place to limit banners to one without this item. So I think that superficial support of this mod is less confusing to players than it being unsupported but them still able to have two banners active at the same time.
Related issue to resolve this: #280 
Close #273

Add Perfidy and support for its mods

---

Modules/CalcPerform.lua
Modules/ModParser-3_0.lua

Added 'Unencumbered' condition and auto-setting it based on weapons/gloves; implemented parsing of 'while you are Unencumbered' for items.
To test you can create a Unique Jewel with:
```
Hollow Palm Simulator
Cobalt Jewel
LevelReq: 1
Implicits: 0
You count as Dual Wielding while you are Unencumbered
Adds 14 to 20 Physical Damage per 10 Dexterity while you are Unencumbered
60% more attack speed while you are Unencumbered
```
Add put it in a Jewel Socket and compare DPS when random gloves or weapons are included and removed. Also, in Dev Console you can see the Condition being present or not.
GGG stated that while weapons are Disabled per Dancing Dervish Unique Item special condition as long as you don't have gloves equipped you will also be considered Unencumbered.
UPDATE: Commit 2 - you …

Unencumbered Implementation

---

Classes/Item.lua

Timeless jewels use the ":" character when defining the level requirement and this was not correctly parsed resulting in [304](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/304)

Fixes parsing "Requires Level:" on items

---

Modules/CalcPerform.lua

Looks like an oversight. There should be no spaces in conditions names.

Fix AffectedBy conditions

---

Modules/ModParser-3_0.lua

Fixes #153 
as well as a bunch of other issues.
Main fix is to prevent modifiers that have a "with this weapon" affecting Spells (which don't use the weapon). Now only skills that have an "Attack" tag will be affected.
The code "bor(KeywordFlag.Poison, ModFlag.Attack)" should have been "bor(KeywordFlag.Poison, KeywordFlag.Attack)". This fixes skill-type reporting for Bleeding and Poison mods affected by this. ModFlag.Attack maps to "Aura" in the keywordsFlag arg position and not "attack".
A test PoB to see it working is: [https://pastebin.com/V2u8Ki9W](https://pastebin.com/V2u8Ki9W)
You can swap between Essence Drain and Split Arrow in the Calcs tab Socket Group Drop Down to observe the Poison box "Total More" being modified which is coming from the Bow item.
Mouse Hovering over the 60% …

Fix "with this weapon" modifier handling

---

Modules/CalcOffence-3_0.lua
Modules/ModParser-3_0.lua

Adds support for a new mod Crown of Eyes in 3.10 which will cause increases and reductions to spell damage to apply to attacks at 150% of their value. It does this with a new flag and piggybacks on the implementation of the existing mod.
Kinetic Bolt also has this mod, so this will make it easier to support that part of the skill.

Support new Crown of Eyes mod

---

Modules/CalcOffence-3_0.lua
Modules/ModParser-3_0.lua

Fixes #425
Adds "LightningNoCritLucky" flag
- This enables the "lucky hit" calculation for the non-crit pass when the damage type is lightning.

Support for Supercharge Notable

---

Modules/ModParser-3_0.lua

Fixes #378
Adds parsing for "spells cast by totems deal " prefix
Fixes restrictions on "attacks used by totems have " and "spells cast by totems have "
- These are now restricted to attacks and spells respectively.

Support for Ancestral Inspiration Notable

---

Modules/ModParser-3_0.lua

Partial implementation of #272 that aims to support the new Secrets of Suffering Keystone's `Cannot Ignite, Chill, Freeze or Shock` mod.
Ideally would be modular so that mods like `Cannot Chill or Shock` or `Cannot Ignite,Freeze or Shock` can be supported but this is enough to temporarily support the keystone.

Secrets of Suffering Partial Implementation

---

Modules/ModParser-3_0.lua

Fixes #394
The only mod not currently working was:
Attack Skills fire an additional Projectile while wielding a Claw or Dagger
Note that the "green text" in the tooltip does not show the change in number of projectiles, however it does show up in the calcs section.

Support for Fan of Blades

---

Data/3_0/Minions.lua
Data/3_0/SkillStatMap.lua
Modules/CalcPerform.lua
Modules/ModParser-3_0.lua

Adds support for `per Summoned Sentinel of Purity` and `maximum number of Sentinels of Purity`
```
New Item
Cobalt Jewel
Implicits: 0
+1 to maximum number of Sentinels of Purity
1% additional Physical Damage Reduction per Summoned Sentinel of Purity
```

Adds partial support for Disciples and Pure Agony

---

Classes/PassiveTreeView.lua
Classes/Tooltip.lua

The new 3.10 tree data already contains oil recipes and stores it into the "recipe" member of node.
- When PassiveTreeViewClass:AddNodeName() is called, the recipe is stored into the tooltip
Added support for rendering recipes in the tooltip
- The tooltip size accounts for the rendered recipe
- The recipe is rendered using both text and images
- The size of the text and images is based on the size of the first line of the tooltip

Notable oil recipes are rendered with text and image

---

Modules/ModParser-3_0.lua

ModParser has this mod implemented as "Projectiles gain damage as they travel further", but the mod itself uses the correct word "farther". Now this mod parses correctly.

Fix typo in Ascendant Deadeye/Longshot notable

---

Modules/ConfigOptions.lua
Modules/ModParser-3_0.lua

closes #421 
Jewel:
`Regenerate 1% of Energy Shield per second if you've Cursed an Enemy Recently`

Adds support for Sap Psyche

---

Modules/ConfigOptions.lua
Modules/ModParser-3_0.lua

Adds support recently using brand skills:
Jewel:
`25% increased Brand Activation Frequency if you haven't used a Brand Skill Recently`

Adds support for Chip Away

---

Modules/ConfigOptions.lua
Modules/ModParser-3_0.lua

closes #448 
Tested with jewel:
`5% increased Movement Speed if you've thrown a Trap or Mine Recently`

Adds support for Guerilla Tactics

---

Modules/ModParser-3_0.lua

```
Septic Spells
Cobalt Jewel
Quality: 0
Implicits: 0
8% increased Cast Speed
Spell Skills have +10% to Damage over Time Multiplier for Poison
20% chance to Poison on Hit with Spell Damage
===
8% chance to Knock Enemies Back on Hit with Spell Damage
```
With #511 closes #439 and also adds support for Burden Projection

Add support for Septic Spells

---

Modules/ModParser-3_0.lua

SkillType.MeleeSingleTarget = Strike tag on gems. Looked up all gems and its the same list as whats on the wiki
Tested on various melee skills and looks to be working. Even works with default attack
Closes #359

Added support for Strike Leader Notable

---

Modules/ModParser-3_0.lua

The modifier `Spell Skills have +10% to Damage over Time Multiplier for Poison` from Septic Spells parses but doesn't work. It creates something like 10% dot multi for spell poison which is impossible as dot damage is not spell damage.
Partially resolves #439

Fix parsing of mods applied to spell skills

---

Modules/ModParser-3_0.lua

closes #397 
closes #398 
Jewel:
```
Tempered Arrowheads
Cobalt Jewel
Implicits: 0
Bow Skills have +10% to Damage over Time Multiplier
Bow Skills have 20% increased Skill Effect Duration
10% increased Duration of Ailments inflicted while wielding a Bow
```
I tested this with a poison phys bow w/ split arrow. The only gem I could think of that has Bow and Duration tags is Mirage arrow.

Adds support for Tempered Arrowheads and Broadside

---

Modules/ConfigOptions.lua
Modules/ModParser-3_0.lua

closes #467 
Jewel:
```
Life from Death
Cobalt Jewel
Implicits: 0
Regenerate 2% of Life per second if a Minion has Died Recently
```

Adds support for Life from Death

---

Modules/ModParser-3_0.lua

Fixes #447 
Tested with Flammability Curse enabled as a skill and the following Jewel socketed:
```
New Item
Ghastly Eye Jewel
Quality: 0
LevelReq: 0
Implicits: 0
Enemies you Curse take 5% increased Damage
5% chance to Dodge Attack Hits from Cursed Enemies
```

Implemented Evil Eye Notable

---

Modules/ModParser-3_0.lua

Fixes #382 
It was implemented as the same as Condition:Channelling because we don't want to clutter the ConfigOptions window with even more count boxes and 1 second is not long.
Test using Incinerate with below Jewel
```
New Item
Ghastly Eye Jewel
Quality: 0
LevelReq: 0
Implicits: 0
50% increased Critical Strike Chance while Channelling
+30% to Critical Strike Multiplier if you've been Channelling for at least 1 second
```

Implemented 'if you've been channelling for at least 1 second'

---

Modules/CalcPerform.lua

From the patch notes:
`Elusive now grants 30% increased movement speed (from 40%), 15% chance to dodge attacks (from 20%) and 15% chance to dodge spells (from 20%).`

Updated elusive to match the new values in 3.10 patch notes

---

Modules/ModParser-3_0.lua

Was unsupported. Now enables Rage as expected.

Add parsing for "Bloodscent" notable

---

Modules/ConfigOptions.lua
Modules/ModParser-3_0.lua

Support burst life regen found in Time of Need, the new Surging Vitality notable, and the Hunter prefix on Body Armour.
Specifically adds support for: "every 5 seconds, regenerate (%d+)%% of life over one second"
Adds a configuration option to choose how life regen is calculated
- Minimum: Does not include burst regen.
- Average: Averages out burst regen over time.
- Burst: Includes full burst regen in the calculation.
Fixes #436
Configuration:
Minimum:
Average:
Burst:

Support for Surging Vitality notable (burst life regen)

---

Modules/CalcOffence-3_0.lua

- Changes the display on ailment threshold to use a float so it doesn't overflow, like is very easy to do with Vaal Arc
---------
On the current build it is very easy to see this error on a Vaal Arc build, where the ailment threshold overflows and shows a negative number:
With this PR that number now uses a float, which stops it from overflowing quite so easily:
This is easiest to see on Shock with Vaal Arc, but I also changed Chill, Freeze, and Shock to all use floats now.

Change ailment thresholds in Calcs tab to use floats to prevent overflows

---

Modules/CalcOffence-3_0.lua

I noticed a few days ago that, when I had 50% increased ignite duration and 50% increased burn rate, the ignite duration breakdown wouldn't show everything it should:
This PR makes it so this breakdown checks for a modifier to ignite duration instead of checking to see if ignite duration is something other than 4 seconds.

Make Ignite Duration breakdown show more consistently

---

CONTRIBUTING.md

The instructions for setting up a development environment recommend
Visual Studio Code, but the debugging instructions lack crucial detail.
For example, they mention copying a generated code snippet and checking
UI boxes, but neither of those are part of the Visual Studio Code
debugging setup.

Add detailed debugging instructions for VS Code

---

Classes/ImportTab.lua

The import dialog saves the selected index of the league dropdown, but
only applies it as a filter when the dropdown value changes. It breaks
the following flow:
1. Import -> Start
1. Change league filter to something other than "All" (e.g. SSF).
Character list is filtered as expected.
1. Finish character import of jewels and items and hit "Done"
1. Start another import via Import -> Start
1. League dropdown still has your selection from step 2 (SSF), but the
character list has all characters.
The bug is that the import dialog remembers the league selected index so
it appears the filter is applied, but the logic does not pass the league
when creating the character list. It only does this when the league
dropdown value changes.
Fix is to pass the league in both scenarios.

Fix league character filter on subsequent imports

---

Modules/ModParser-3_0.lua

When running jewel functions they get called for each node and `nil`. Sockets coming from cluster jewels are not in range of any nodes (which is correct) and the unique effect from Might in All Forms didn't have checks for that case. This would also cause a crash when trying to use the jewel.
Fixes #612

Fix sorting getting stuck

---

Classes/PassiveSpec.lua
Export/spec.lua

Fixes an issue where medium cluster jewels with 4 passive skills would render incorrectly if there was 2 notables and no jewel sockets.
Close 655

Fix medium cluster jewel rendering

---

Classes/Item.lua
Classes/ItemsTab.lua

When an item is re-crafted from the chosen prefixes and suffixes, the entire explicit mod list is cleared.
- This would also clear out crafted and custom mods, so they would be lost.
- The fix is to save off the crafted and custom mods before clearing, then re-add them after the explicit mod list is regenerated.
How to reproduce the original issue:
1) Craft a new item using the "Craft Item..." button
2) Use the default options
3) Add a prefix using the first prefix dropdown
4) Click the "Add modifier..." button and choose a crafting bench or custom modifier to add
5) Add another prefix or suffix using the dropdown
Result: The crafted modifier will disappear from the item, even though the "Remove" button is still there.

Fix for crafted and custom modifiers disappearing from custom items when prefix or suffixes are changed

---

TreeData/3_10/tree.lua

All 4 instances of this character in tree.lua are now replaced with the ascii apostrophe character.
This affected the following notables:
- Precise Retaliation
- Sap Psyche
- Vile Reinvigoration
- Dark Discourse
Fixes #745 
Before:
After:

Fix for tooltip display issue caused by a unicode apostrophe character being used for some cluster notable descriptions

---

Modules/CalcPerform.lua
Modules/ModParser-3_0.lua

This fixes a bug where having either multiple instances of the Replenishing Presence notable on your tree would not stack with themselves or the Guardian Unwavering Faith ascendancy

Replenishing Presence fix

---

Classes/ImportTab.lua
Classes/PassiveSpec.lua
Modules/Build.lua
Modules/Main.lua

Display basic information about the current build in the title of the
window. Three flavors exist, depending on the state of the app:
Path of Building
Application is starting or in the build management view (e.g. if you hit
"<< Back" in the UI)
Path of Building - Unnamed build (CleverName, Gladiator, SSF Delirium)
Build is imported from GGG. The title takes effect when the passive tree
is imported. Importing just the items from a build will have no effect.
Path of Building - Imported Build (Gladiator)
Build is imported from a Path of Building code, PasteBin, or from a
local XML file. Note that "Imported Build" is literal; Path of Building
does not store the original character name or league in its data.
This can also occur if you import a character from GGG, back out to the
build …

Show build name in title bar

---

Data/Uniques/jewel.lua
Modules/ModParser-3_0.lua

Fix Thread of Hope not working correctly when imported from characters

---

Data/Uniques/bow.lua

The first variant got lost somehow.

Fix bug with variants of Doomfletch's Prism

---

Classes/CalcBreakdownControl.lua

Cluster node ids are a bit strange
- The cluster jewel uses a modified id that's used on the actual tree
- The source uses the original id in the tree.lua file
- The fix is if the source id isn't found on the current spec, then the original tree data is referenced instead.

Fix for crash when viewing a breakdown which includes a cluster node source

---

Modules/CalcPerform.lua

env.minion was nil and wasn't being checked
- The fix is to use the castingMinion which is guaranteed not nil, and will be equal to env.minion when it is intended to be used.
Reproduction steps:
- Create new build
- Add new socket group
- Add "Summon Lightning Golem"
- Select Configuration tab
- Check "Enable Wrath Aura"
- Select Skills tab
- Delete "Summon Lightning Golem" socket group
- Add new socket group
- Add "Storm Brand" to group
- Add "Arcane Surge" to group
- Click to try to add another gem to group
- Observe crash

Fix for crash as described in issue #753

---

Classes/TreeTab.lua
Modules/Build.lua
Modules/Main.lua

- Adds a config option to toggle the functionality of #688 , which shows the build name and ascendancy in the window title
- Also fixes a problem with #688 I noticed, where the window title wouldn't change if you selected a new passive tree with a different ascendancy in the dropdown menu
- Is toggled on by default
- Updates the window title automatically when the option is changed
- The spacing of the new option in the box lines up and has the same spacing and everything as the other config options
I tested a few different situations to make sure it doesn't cause any errors or crashes. The following all worked fine:
- Starting PoB when settings.xml does not exist
- Starting PoB when settings.xml exists but doesn't have the new option in it
- Changing Ascendancies with the option both on …

Add config to toggle build name in titlebar

---

Classes/PassiveSpec.lua
Classes/PassiveTreeView.lua
Data/Uniques/jewel.lua
Modules/CalcSetup.lua
Modules/ModParser-3_0.lua

Added `PassiveSpecClass:SetNodeDistanceToClassStart` function to calculate the allocated distance from each allocated jewel socket to the class' node start.
- Uses as similar algorithm to other pathing functions in the file
- This is Dijkstra's algorithm
Allocated jewel node tooltips show the distance to start to help the user determine the best socket to use.
Added Split Personality to the uniques list
- Allows selecting both properties similar to Watcher's Eye
Used the jewel scale modifier which was already implemented for abyss jewels in stygians
- This modifier can now also come from the jewel itself
- The cached distance to the class' start is used to calculate the scale

Implementation of Split Personality Jewel

---

Modules/Common.lua
Modules/Data.lua

Through watchstones, it is possible to reach a higher maximum area level than before.
Also "disenchanted" all magic numbers used in the calculations.

Update experience multiplier to take new game mechanics into account

---

Classes/ImportTab.lua
Classes/SkillsTab.lua
Data/3_0/ClusterJewels.lua
Data/3_0/Gems.lua
Data/3_0/Skills/sup_dex.lua
Modules/Data.lua

Comes from Openarl's 1.4.169 update that included changes to the importer to fix Stormbind and Barrage Support not importing correctly when importing a character's skills. Also fixes the importer for cluster jewels that contain 2 lines for the enchant

Fix gem/cluster jewel importer

---

Modules/CalcSetup.lua

If the granted skill is not a support gem, then "Support" is prepended to the skillId and the lookup is attempted again.
- This changes Barrage to SupportBarrage
Fixes #692

Fix for Hungry Loop attempting to support the skill with the Barrage skill instead of the Barrage support

---

Modules/ModParser-3_0.lua

"if dexterity is higher than intelligence" and "if strength is higher than intelligence" were marked as "StatThreshold" instead of "Condition"
- This caused the conditions to always pass

Fix for Fractal thoughts dex>int and str>int conditions not working

---

Modules/ModParser-3_0.lua

The Vaal timeless jewel changes all the nodes in its radius anyway so disabling the stats they give makes sense

Change Vaal Timeless Jewel to disable stats from nodes in radius

---

Modules/CalcSetup.lua

The base mine throwing time was updated from 0.25 -> 0.3s in 3.10

Update Mine Throwing time for 3.10 changes

---

Classes/CalcBreakdownControl.lua
Classes/ModStore.lua
Modules/ModParser-3_0.lua

This works essentially the same as PerStat, with the following differences:
- Does not work off of thresholds, so fractions of a stat can be used. PerStat is for "1 per 25 int" whereas PercentStat is for "0.1% of life"
- Specifies the percentage as-is, and divides by 100 for you in the calculations.
- Displays as a percentage in the calcs breakdown, e.g. "+0.1% of life"
Converted some mods which were previously changed to use "PerStat" to now use the now more appropriate "PercentStat"
- This fixes calculation issues with mods like the "Rite of Ruin" ascendancy node for Berserker, where 999 life was 0 degen and 1000 life was 50 degen at 50 rage stacks.

Added "PercentStat" tag option for mods.

---

Data/3_0/SkillStatMap.lua
Data/3_0/Skills/other.lua
Export/Skills/other.txt
Modules/CalcOffence-3_0.lua
Modules/ConfigOptions.lua
Modules/ModParser-3_0.lua

- Adds the Snipe skill from the unique helmet Assailum
- Adds a config option to set the number of stages on releasing Snipe
- Triggerable skills socketed into Assailum gain more Hit and Ailment damage appropriately for each Snipe stage
- Triggerable skills socketed into Assailum deal 33% less damage
---------------
The current implementation is perfectly functional and to my knowledge is mathmatically correct. One issue is that it causes socketed skills to only show average damage instead of a DPS number. Since the actual attack rate of triggered skills is dependent on the attack rate of the Snipe skill, it's wildly inaccurate to simply give a DPS multiplier based on Snipe stages. I couldn't figure out a way to make other skills use the attack rate of another skill, but maybe that …

Support Assailum and Snipe skill

---

Classes/ConfigTab.lua
Classes/ModDB.lua
Classes/ModStore.lua
Modules/CalcOffence-3_0.lua
Modules/CalcPerform.lua
Modules/ConfigOptions.lua

This means that the Master of Metal, Watcher's Eye with impale stacks, and the Deep Cuts notable now display the real DPS change when hovered as long as the "# of Impales on Enemy" stacks config is blank or large enough.
Changes to impale:
- Removed the clamp to 9 stacks from the config
- If the config value isn't set, the calculated maximum number of impales is used
- If the config value is 0, then 0 impales are used
- If the config value is too large, then it is clamped down to the maximum number of impales
- The "Stacks on Enemy" value in the Impale section is now properly displayed
Added some useful utility functions:
- modStore:ReplaceMod will find an exact match to the mod and update the value
- modStore:HasMod will check to see if modStore:Sum would find any matching mods to sum …

Fix for Master of Metal using 0 impale stacks if the configured number of stacks was blank

---

Classes/DropDownControl.lua
Classes/ImportTab.lua
Classes/Item.lua
Classes/ItemsTab.lua
Modules/ItemTools.lua

Changes are relatively straightforward, since multiple influence was already supported for items, just not the crafting UI.
Here's what it looks like:

Added second influence dropdown in item crafting for creating dual-influenced items.

---

Classes/Item.lua
Classes/ItemsTab.lua
Data/Uniques/amulet.lua
Data/Uniques/belt.lua
Data/Uniques/ring.lua
Modules/ItemTools.lua

When crafting rare jewelry, there is now a catalyst dropdown and quality slider
- The new mod tags are used to determine if a catalyst affects a mod
- The base implicit mod is also affected, but only if the item is newly crafted after this commit.
- Also affects crafting bench and essence mods

Catalyst support for crafted rare items

---

Modules/ConfigOptions.lua

Fixes issue where 'While Channeling' bonuses, in particular the bonuses from new Cluster Jewel notables, only applied to the channeling skill and not any non-channeling skills that may be triggered while channeling

Add "Are you Channelling" Checkbox

---

manifest.xml

Changes:
* Change icon of `Path of Building.exe`  to Path of Building Community icon
* Re-add `vcredist_x86.exe`
* Remove `UpdateUAC.exe`, as it is no longer needed
* Recompute file hash for replaced executable

Update runtime files

---

manifest.xml

Changes the remote manifest to serve all future application updates from this repository.
Existing installations that already target this repository will be updated seamlessly.

Serve all app updates from this repo

---

Classes/ModDB.lua
Classes/ModStore.lua

The fix is to have ReplaceModInternal recurse into the parent mod list when looking for a mod to replace.
- The logic to add the mod if it doesn't exist has been moved to ReplaceMod if the function returns false.

Fix for the "Show power" calculation thinking all nodes have more power when the impale stacks are configured to be higher than the max.

---

Classes/CalcBreakdownControl.lua

For now, the tree is not shown at all, since the source node is the "abstract" node from tree.lua rather than the generated node from the cluster jewel.

Fix for crash when hovering a source in the calcs when the source is a cluster jewel node.

---

Modules/CalcOffence-3_0.lua

Fixes issue where armour values were being doubled
Fixes issue where "Enemies have -X% to Total Physical Damage Reduction against your Hits" was applying to impale physical damage reduction

Fix Enemy Armour calculations

---

Data/3_0/ClusterJewels.lua

2 cluster jewel bases were not importing correctly due to the order of their mods being being different from in game

Cluster jewel not importing correctly

---

Classes/CalcsTab.lua

Added "local" to some variables in `CalcsTabClass:CalculatePowerStat()`

Fix for creation of global variables where they were unnecessary

---

Classes/Item.lua
Classes/ItemsTab.lua
Data/Uniques/amulet.lua

This adds proper support for parsing talisman tiers from item data.
Removing talisman tier data from Data\uniques\amulet.lua is also technically an option, but that leaves parsing for existing items in a broken state.
Current behaviour (1.4.169.2):
----
Fixed behaviour:

Fix talisman tier parsing

---

Data/Uniques/helmet.lua

The 2000% increased damage cap added in 3.5.0 applies to all versions of Indigon, legacy versions without the cap do not exist.

Update Indigon Item Data

---

Export/Skills/act_str.txt

Consecrated Path seems to use (literally) the same internal mod as Ground Slam 
Fixes #724

Fix Consecrated Path not applying more damage to close targets

---

Modules/Main.lua

I noticed that for some reason, when I restarted PoB, the build name was showing in the title bar even though I had it turned off. Turns out that in my original PR I neglected a simple thing that would make it actually use the value that was in the Settings.xml file when the program started. I saw that it this "== "true"" was there for the thousands separator toggles, but thought it was unneeded for some reason.
In all the testing I did, the toggle always worked just fine! Just forgot to check that the setting actually saved when I restarted the program.

Correctly save and load choice for build name in titlebar

---

Modules/CalcOffence-3_0.lua

My PR #158 had a mistake where skills which display average damage(Divine Ire, certain triggered skills, etc.) had wildly incorrect sorting for things that sort by Combined DPS, including adding support gems. That's because it was only ever considering the average hit damage, and not considering any bleeds or ignites or poisons or anything, as the only thing that ever got added to the CombinedDPS value was the base hit damage.
This second PR adds a CombinedDPS total to ShowAverage skills, which isn't shown anywhere, but makes sorting by Combined DPS function like it did before my original PR.

Fix DPS sorting for ShowAverage skills

---

Modules/ConfigOptions.lua

Feeding Frenzy had it's values changed with 3.10 but the tooltip was not updated

Fix Feeding Frenzy Tooltip

---

Modules/ConfigOptions.lua
Modules/ModParser-3_0.lua

fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/947
This applies for the "more damage while there is at most one rare or unique enemy nearby" effect for **Opportunistic** which currently does not have its damage mod applied.
https://pathofexile.gamepedia.com/Opportunistic

Support the zero case for "there is at most one rare or unique enemy nearby"

---

Data/3_0/Skills/act_dex.lua
Data/3_0/Skills/sup_dex.lua
Export/Skills/act_dex.txt
Export/Skills/sup_dex.txt
Modules/ConfigOptions.lua

Addresses [issue #564](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/564)
The bug also applies for Nightblade support. I also went ahead and updated the tooltip which appears to be the pre-nerf tool-tip https://pathofexile.gamepedia.com/Elusive

fix elusive calculations from gems

---

Modules/CalcDefence-3_0.lua
Modules/CalcSections-3_0.lua
Modules/ModParser-3_0.lua

**Previously**, "you take x% reduced Extra Damage from Critical Strikes", found on the Sanctum of Thought notable, body armor corruptions, the Belt of the Deceiver, etc. was an unhandled red-text mod.
**Now**, these mods are handled, totaled up in a "Crit Reduction" field under Other Avoidance in the Calcs tab.
**Note**: I would have liked to handle the "while you have no Power Charges" condition on Ahn's Contempt modularly rather than as a special case, but the parser kept getting hung up on "critical strikes" and trying (unsuccessfully) to interpret the mod as something else. If this functionality is desired overall, and that refactor would be valuable, advice on how to better structure it would be appreciated!

Total up "reduced Extra Damage from Critical Strikes"

---

Modules/ModParser-3_0.lua

**Previously**, the first mod on Elementalist notable "Liege of the Primordial", "Summoned Golems are Immune to Elemental Damage", was a red-text unhandled mod.
**Now**, allocating this passive sets the three elemental resistances for all golem-type minions to 100%.

Handle Liege of the Primordial golem elemental immunity

---

Modules/ModParser-3_0.lua

**Previously**, the mod "Immune to Elemental Ailments while you have Arcane Surge" in the Hierophant's "Arcane Blessing" notable was an unhandled red-text mod.
**Now**, if the user has Arcane Blessing allocated and Arcane Surge active, the appropriate ailment avoidances will be set to 100%.
**Note**, if/when Scorch, Brittle, and Sap are implemented (see e.g. #891), we could consider including avoidance chance readouts for those as well.

Handle Arcane Blessing ailment immunity

---

Classes/SkillsTab.lua

Previously it said "Socketed in: None" for belts. The side effect is that skills can now be socketed in belts which is incorrect most of the time but it's not checked anyway (you can socket gems in Kaom's Heart for example)

Fix item slot not being displayed for belt skills

---

Data/3_0/Skills/act_int.lua
Export/Skills/act_int.txt

Stormbind's more damage per improvement only applies to hits and ailments. Fixes #932
I'm not familiar with the export scripts (and they're going to be used again soon anyway for 3.11) so I haven't updated the incorrect skill gem description in skill_stat_descriptions.lua.

Stormbind damage per improvement fix

---

Data/3_0/Skills/other.lua
Export/Skills/other.txt

When setting the number of stages, the DPS for the skill was not reduced by the time taken to channel the skill

Fix Snipe Stages

---

Modules/ConfigOptions.lua

**Previously**, even if you specified a number of Bleed stacks on the enemy when using Crimson Dance, you also needed to separately check "Is the enemy Bleeding?" for relevant effects.
**Now**, if you have bleed stacks filled in, the enemy will also be considered to be Bleeding, where relevant. Checking/unchecking "Is the enemy Bleeding?" with a number in the stacks field has no effect.
**Note**, if you use the default maximum-stacks setup rather than filling in a number, you still need to toggle the Bleeding box manually. Still trying to figure out if it's possible to have that behave better, but as is, it's at least a tiny improvement!

Specifying bleed stack sets "enemy is Bleeding"

---

Data/3_0/Pantheons.lua

Fixes #898 by replacing strings referring to old Pantheon-related map bosses with the names of those used on the current Atlas.

Update pantheon upgrades for 3.10

---

Classes/ItemsTab.lua
Modules/CalcDefence-3_0.lua
Modules/CalcOffence-3_0.lua
Modules/CalcSections-3_0.lua
Modules/ConfigOptions.lua

- Removes all references to "<stat>RecoveryMod" and changes them to "<stat>RecoveryRateMod" where necessary
-----------
For some reason in the code there were a lot of references to a "LifeRecoveryMod", as well as for ES and Mana, that I don't understand. Maybe at some point in the past the mod was "Increased Life Recovery" instead of "Increased Life Recovery Rate"? I don't remember that being the case and the 2.6 ModParser also refers to these mods as RecoveryRate, so I have no idea! But either way, I cleaned it up and they now all correctly refer to RecoveryRate instead.
This started when I noticed that the Calcs tab breakdowns for life/ES/mana regen are supposed to have a separate breakdown for recovery rates, but those breakdowns in CalcSections just referred to "LifeRecovery", etc. …

Clean up all uses of Life/ES/Mana Recovery Rates

---

Modules/ModParser-3_0.lua

- Adds parsing for the Tailwind mod on Hunter influenced boots
-----
Of course, there's a Tailwind toggle that's always available on the Config screen, but adding it as a proper mod like this lets you more easily compare boots with and without Tailwind. It also makes it so the mod shows up as blue, which isn't ugly.

Add parsing for Tailwind mod on Hunter influenced boots

---

Classes/ConfigTab.lua
Modules/ConfigOptions.lua

- Adds tooltip functionality to config options that use ifOption
---------
For some reason, there is just no code that allows an ifOption config option to have a tooltip. It seems to be the only thing that has this problem on the config page.
I ran into this limitation when initially implementing Shock, and worked around it by just making the tooltip for the Shock checkbox really long to make it clear exactly how it works. But when I ran into the same issue for my PR to implement alternate ailments(#891), I figured out how to fix it very easily. Here is that fix. As an example, this finally lets me split the Shock tooltip up and make it less wordy since it's much clearer now:

Allow ifOption config options to have tooltips

---

Modules/ItemTools.lua

Issue before the fix:
1) Too many percent signs added to the first mod.
2) The slider would start editing the second mod instead of the first.
After the fix, the slider works as expected:

Fix for Dying Sun not changing "increased" to "reduced" properly for the first mod.

---

Data/Uniques/amulet.lua

This was introduced as a typo when the tags were added.

Fix for Willowgift missing an open parenthesis on a mod

---

Modules/CalcPerform.lua

Hybrid flasks count as both life and mana flasks. This is relevant for certain passive skills. Fixes #858

Fix hybrid flasks not counting as life/mana flasks

---

Modules/ModParser-3_0.lua

The node connected to Twin Terrors was previously not being parsed

Support Attack Crit Multi

---

Modules/Data.lua

The maximum area level is one level lower than currently in PoB, as there are only three different kinds of unique watchstones that grant "+1 to Monster Level of Area".

Fix experience multiplier

---

Classes/ItemsTab.lua

This change sorts the crafted mods in the "Add Crafted Modifiers" modal by prefixes then suffixes and also adds a (prefix) or (suffix) tag. Essences were also updated to keep formatting a little more consistent
Note: for some of the longer mods, the tag may be truncated or hidden
Crafted - Before:
Crafted - After:
Essences - Before:
Essences - After:

Sort crafting options by prefix/suffix, add tag

---

Data/Uniques/helmet.lua

It had some mods you get when copying it to the clipboard.

Fix item format on Speaker's Wreath

---

Classes/TreeTab.lua

Fixes cluster jewels to be allocated when upgrading the tree to a new version

Fix allocation of cluster jewels on tree update

---

Data/Global.lua
Modules/CalcActiveSkill.lua

Some nodes that were meant to only apply to brands, were mistakenly applying to other skill types too

Fix Brand keyword flag

---

Data/Uniques/amulet.lua

The reservation is not affected by fertile catalyst - tested in game. Not sure if that's a bug.
Fixes #980

Update Hyrri's Truth

---

Modules/ModParser-3_0.lua

A small node on the 3.11 Harpooner impale themed cluster introduces the mod "10% increased Effect of Impales you inflict with Two Handed Weapons".
This PR adds support for the mod,as shown here:

Support for 2H weapon impale effect mod                             

---

Modules/CalcPerform.lua

Crab barriers would always use the maximum amount for calculations, leading to ignoring user input in configuration.
Fixes #1025
(As a value of '0' is interpreted by the mod database as nil, this means you technically never calculate your damage reduction with zero crabs)

Fix calculations of crab barriers

---

Data/3_0/SkillStatMap.lua
Export/Skills/act_int.txt
Modules/CalcPerform.lua
Modules/ConfigOptions.lua
Modules/ModParser-3_0.lua

- Adds a couple of stats, found on Brand skill gems, to SkillStatMap
- Makes it so the # of Brands Attached config option instead calculates its limit in CalcPerform, where it can look at your BrandsAttachedLimit
- Adds parsing for Runebinder's addition brand attached mod
----------------
I realized that Wintertide Brand will have a base limit of 2 Brands attached to the enemy instead of the standard limit of 1 Brand attached, which meant that with the Runebinder keystone you could get to 3 Brands attached. The config option had a hard limit of 2 Brands attached to the enemy due to using m_max(val, 2) to determine the value of BrandsAttachedToEnemy. This PR changes it so that the config option instead gives a useless stat which is then used in CalcPerform, along with a new …

Slight generalization of Brand mods

---

Export/Skills/act_int.txt
Modules/ConfigOptions.lua
Modules/ModParser-3_0.lua

- Adds More Activation Frequency to the hit rate calculation for Brand skills, as 3.11 introduces at least two sources of that stat. This new hit rate calculation should also be used on the new Brand skills
- Adds parsing and a config option for one of those sources, the reworked Hierophant node
- Preemptively adds the new Brand skills to the SkillList which makes the Brand config label/option show up
On this branch:
Compared to on live:

Allow More Activation Frequency for Brands

---

Modules/CalcPerform.lua
Modules/ConfigOptions.lua
Modules/ModParser-3_0.lua

- Adds support for configuring Power on Warcry skills. Power is set to 20 automatically if the target is a Boss
- Supports the new Cry Wolf mod which gives 10 minimum Power
At this point the only thing this really does is remove references to WarcryNearbyEnemies and let you set the WarcryPower multiplier. This is simply a base upon which to properly implement the new Warcry buffs when the final 3.11 ggpk is available.

Support Power for Warcry skills

---

Data/Uniques/body.lua

The mods on Queen's Hunger were malformed, most likely due to copying and pasting them from the clipboard.

Fix mods on Queen's Hunger

---

Export/Skills/act_str.txt

Updated/replaced tectonic slam's conditional damage modifier with area effect multiplier for 3.11

Updated tectonic slam for 3.11

---

Export/Skills/act_int.txt
Modules/ModParser-3_0.lua

- Adds parsing for the Herald of Thunder hit frequency mod on Storm Secret
- Changes Herald of Thunder to not be an average hit skill since the hit frequency is shown on the gem and known now

Implement Storm Secret unique ring

---

Modules/CalcPerform.lua
Modules/Data.lua
Modules/ModParser-3_0.lua

It is correctly limited to 40% in calculations. This value is hardcoded, as parsing it again would not be useful as it stands.
Level 20 Precision: +701 accuracy.
Expected at 40% buff effect: 981.4 accuracy
Expected at 24% buff effect: 869.2 accuracy
3 Purposeful Harbinger allocated, 4 heralds enabled (+40%):
3 Purposeful Harbinger allocated, 1 herald enabled (+24%):
3 Purposeful Harbinger allocated, 0 herald enabled (+0%):

Correctly parse the new purposeful harbinger line

---

Modules/CalcPerform.lua
Modules/ModParser-3_0.lua

Enable calculations of Femurs of the Saints Unique staff (https://pathofexile.gamepedia.com/Femurs_of_the_Saints)
Calculation uses the ActiveZombieLimit, ActiveSkeletonLimit, ...
Unfortunately the minion count is dependent on active minion skill.
Maybe this can work as a small fix in the mean time.

Fix femur mods

---

Classes/ModDB.lua
Classes/ModList.lua
Data/Global.lua
Modules/ModParser-3_0.lua

"for poison" now uses the MatchAll flag so that the following type of text will work:
- "Spell Skills have +5% to Damage over Time Multiplier for Poison"

Added KeywordFlag.MatchAll option to force all KeywordFlags to match rather than just any.

---

Data/Uniques/staff.lua

The Judgement Staff as meant to have Spell block and not Attack block

Fix Staff Implicits

---

Modules/ModParser-3_0.lua

Cap was accidentally set at 50 instead of 100 corpses consumed recently

Fix Corpse Pact cap being too low

---

Data/Uniques/belt.lua
Modules/ModParser-3_0.lua

- Adds parsing for the new keystone "Immortal Ambition"
- Also adds actual mod parsing for the one line on Immortal Ambition that would not be parsed if Timeless Jewels ever got more in-depth implementation
- Updates Soul Tether in the unique DB and adds a variant for pre-3.11
I parse Immortal Ambition as a list of mods since it seems that keystone mods on items are generated based on the actual keystone on the tree, and Immortal Ambition is not on the tree.

Update Soul Tether to 3.11

---

Data/3_0/SkillStatMap.lua

For scorch, brittle and sap, the Unbound Ailments Support will not
increase their effects or durations.

Fix Unbound Ailments Support not working with new ailments

---

Data/3_0/Skills/sup_str.lua
Export/Skills/sup_str.txt
Modules/CalcDefence-3_0.lua
Modules/CalcPerform.lua
Modules/ModParser-3_0.lua

- Fixes Rage Support not making Rage work
- Fixes Rage Regen not enabling Rage properly
- Removes the limit on Rage Support's added physical damage, since that limit is handled in CalcPerform now
I'm including the act_str.lua file this time since I'm not sure if the Skills will need re-exported otherwise. Fixes #1072

Fix a couple of cases where Rage did not work correctly

---

Data/3_0/Skills/spectre.lua
Export/Skills/spectre.txt

The defualt attack is actually a spell not an attack, so it has been changed accordingly

Fix Baranite Thaumaturge default attack

---

TreeData/3_11/tree.lua

Some apostrophes break the tooltip viewer

Fix apostrophes in some tooltips

---

Data/3_0/Skills/act_dex.lua
Data/3_0/Skills/act_int.lua
Data/3_0/Skills/sup_dex.lua
Export/Skills/act_dex.txt
Export/Skills/act_int.txt
Export/Skills/sup_dex.txt
Modules/CalcOffence-3_0.lua
Modules/CalcPerform.lua
Modules/ConfigOptions.lua
Modules/ModParser-3_0.lua

- Moves Withered calculations to CalcPerform
- Every source of Withered now properly enables the debuff and config option
- Implements support for increased effect of Withered
- Also implements the new Abhorrent Interrogation unique gloves
(the penetration list still shows since CalcSections.lua says to show it but it does nothing)
Short description of what functionally changed:
- Effect of Withered is now applied in CalcPerform
- Sources of Withered just need to give the Condition:CanWither flag now. This let me remove a bunch of lines in the skill data files that were now unnecessary
- The config option shows up due to a dummy variable in CalcPerform(instead of being done by the source of Withered like before)
- Added a couple of if statements to handle the new unique gloves in …

Fix all sources of Withered, implement Abhorrent Interrogation unique gloves

---

Modules/CalcOffence-3_0.lua
Modules/ModParser-3_0.lua

- Adds parsing and support for Eye of Malice unique helmet
This required changing CalcOffence to support modifiers to enemy resistances other than simply adding or subtracting. Tested on a few builds and couldn't find any other effects of this change (comparing DPS numbers and the effective DPS multiplier).

Implement Eye of Malice unique helmet

---

Data/Uniques/body.lua

Since 3.2.0, Shroud of the Lightless cannot drop with 2 Abyssal Sockets. It doesn't make sense for the default number of sockets to still be 2 after two years of it not even being able to drop that way, so now it defaults to 1 socket.

Update default number of Abyssal sockets on Shroud of the Lightless

---

Classes/ItemsTab.lua

Normally, a UI control will inherit the shown/hidden status of its anchor. However, if the "collapse" boolean is set to true on the anchor, instead it will inherit its anchor's position when the anchor is hidden. This was erroneously set to true for the displayItemSectionEnchant section, making it and all subsequent sections ignore the shown/hidden property for the overall item editing display.
Fixes #1073

Fix for the removable crafts remaining after editing an item.

---

Data/3_0/SkillStatMap.lua

The quality stat on Charged Mines support, Increased Mine Damage, wasn't in SkillStatMap. Now it is.

Fix Charged Mines quality

---

Data/3_0/Skills/other.lua
Export/Skills/other.txt

The skill is triggered and should only show average damage

Fix Avian Tornado showing DPS numbers

---

Data/3_0/SkillStatMap.lua

The quality for Wintertide Brand was not working as the mod was not mapped

Fix Wintertide Brand gem quality

---

Data/3_0/Skills/act_str.lua
Export/Skills/act_str.txt

Vaal Molten Shell now grants more armour as of 3.11

Vaal Molten Shell More Armour

---

Classes/CalcBreakdownControl.lua
Modules/CalcOffence-3_0.lua

- Adds tables to the Ailment Threshold calculations for Shock and Chill
- By default Shock shows 5%(the minimum), 15%(the global "standard"), and 50%(default maximum)
- If you have a Shock applied to the enemy there will be a note that the enemy is already Shocked and for how much. If you have a mod that increases Maximum Shock, it will also be reflected in the table
- By default Chill shows 5%(the minimum), 10%(the global "standard"), and 30%(hard maximum). In a separate commit I also added support for my Bonechill PR #1127, which can be reverted if my Bonechill PR is not committed at the same time as this PR(though the stuff I added just does nothing if the output.BonechillEffect doesn't exist)
- Also one final commit to update ShockMax to use my new position, on the player instead of …

Add tables to Ailment Threshold calculations

---

Data/3_0/Skills/act_int.lua
Export/Skills/act_int.txt

- Implements hit rate modifier, affected by increases and reductions to cast speed, for Orb of Storms
Since 3.3, Orb of Storms has had a hit time given on the gem and has been affected by increases to cast speed, but that entire time PoB has always used the time to cast the Orb as its hit rate (which is nearly twice as fast as a level 20 skill actually hits).
The description of the skill says "Modifiers to cast speed will increase how frequently it does this", but despite using the word "modifiers" here, only increases and reductions apply to its hit rate in-game based on my testing.

Add hit rate to Orb of Storms

---

Data/Uniques/shield.lua

The Surrender and The Anticipation were missing their upgrade paths

Unique upgrade paths missing

---

Modules/CalcPerform.lua

One of my previous Brand PRs #1021 created an issue where if you had multiple Brand skills enabled, the BrandsAttached multipliers would be added onto for every Brand skill. If you had two Brand skills and config set for 2 Brands attached, it would instead track that you had 4 Brands attached because both skills added 2 to the multipliers.
This PR changes it so the multiplier count is instead set to whatever the highest BrandAttachLimit you have is. It also adds a special case for Wintertide Brand because, despite that skill being the original point of doing my previous PR, the limit of 3 wasn't actually supported anywhere.

Fix incorrect number of Brands attached to enemy with multiple Brand skills enabled

---

Data/Uniques/belt.lua

A typo prevented these tags from applying.

Fix life and elemental catalysts not applying to Doryani's Invitation

---

Data/3_0/Skills/other.lua
Export/Skills/other.txt
Modules/ConfigOptions.lua
Modules/ModParser-3_0.lua

As of 3.11 Spectral Wolf grants added phys damage per active wolf. I had to manually change the level 20 stat line as it seems GGG may have forgotten to add a stat to it.

Add support for Spectral Wolf buff

---

Data/3_0/Skills/act_str.lua
Export/Skills/act_str.txt
Modules/ConfigOptions.lua

Adds support for herald of ash overkill damage from config
The damage only shows up if a value is given to config otherwise it wont have a damage overtime portion

Herald of Ash damage

---

Data/3_0/Skills/sup_int.lua
Export/Skills/sup_int.txt
Modules/CalcPerform.lua
Modules/ModParser-3_0.lua

- Causes all generic buffs to be scaled by "\<buff name\>Effect", which will not affect anything unintended because any other "\<buff name\>Effect" mods are scaled in unique ways ie Curses and Tailwind, and other buffs use BuffEffect with skillTypes or skillNames ie Heralds and Golems
- Adds "ArcaneSurgeEffect" parsing to use that new scaling
- Changes the div on the Mana Regen from Arcane Surge, because for some reason when the mod was equal to 1%, like at level 20, it wasn't being scaled (but was being scaled at all other values). The .0001 extra makes effectively zero difference after rounding
There is another open Arcane Surge PR over at #826 , but it's *significantly* more complicated than what I did here, so I'd like to open this one anyway. It's been open for a couple of months and …

Correct Arcane Surge scaling

---

Modules/CalcPerform.lua
Modules/ConfigOptions.lua
Modules/ModParser-3_0.lua

The Bannerman/Revelry aura mod was previously applying to all auras which was incorrect as it should only apply to aura debuffs

Add proper support for Bannerman and Revelry

---

Data/3_0/Skills/act_str.lua
Export/Skills/act_str.txt

Whoever did the StatMap on Earthshatter mistakenly put "skill(" at the start of its AoE mod instead of "mod(". There's also no indication that the AoE mod only applies to the main slam, so I removed the type = skillPart on it.

Fix Earthshatter AoE mod

---

Data/Uniques/gloves.lua

- Splits withered mod into two lines, like how it is when you copy/paste the item from trade website or from in-game
- When I originally added the item I never bothered to look at how it was entered in the unique DB, only looked at the one I copied from the trade website. My bad!

Split mod on Abhorrent Interrogation gloves

---

Classes/CalcBreakdownControl.lua

- Supports the Skill Hit Damage tables, which have "to" in between two numbers that were not previously getting commas
- Supports cases where there is a note in parentheses after a number (like in my auto shock PR #1168)

Support a couple of places where commas were not showing up in Calcs breakdowns

---

Data/Generated.lua
Data/New.lua
Modules/Data.lua

Adds the unique itself as well as full support for its mods.
Note that out of all 171 skills gems currently in the game, Forbidden Shako can only roll 131 of them.
Awakened gems and some select others are excluded.
The same skill gem can roll twice. This matches ingame behaviour.
Since there is more than one generated unique now, I've refactored Megalomaniac as well.

Add Forbidden Shako

---

Modules/ConfigOptions.lua

The Shaman's Dominion node gives global crit chance but this was only applied if the main skill was a totem skill

Shaman's Dominion global crit chance

---

Data/Uniques/ring.lua

The ignite duration mod is meant to be a range not a static value as of 3.9

Emberwake ignite duration

---

Launch.lua
Modules/Main.lua

Current behaviour is to detect standalone version if the directory the launch script is located in is the same as the one the runtime is in. In an effort to assimilate standalone and installed versions, a new less accidental detection method is needed to set the default build save path as expected, using a sentinel file only present in future installed versions. The current detection method has to be kept for backwards compatibility.

Changes needed to detect new-style installation

---

Classes/ItemsTab.lua
Modules/Data.lua

When hovering a cluster jewel notable in the prefix/suffix dropdowns, the tooltip now shows the following:
- What the notable does
- Comparison if the notable is allocated
- What cluster jewel types this notable appears on

Improved tooltip for cluster jewel notables

---

Classes/CalcsTab.lua
Classes/PassiveTreeView.lua
Classes/TreeTab.lua

Did some hacking on the heatmap to show the top node and the best nodes per-point.  This is a first step towards providing a list of the best nodes to take to improve your various stats.  Easy changes from here would be to show more than the topmost choice, and show a few more; allow the user to input a limit on how far away to search; color scaling tweaks; and changes in the UI.
Choice UI:
Random tree with life power selected, production build:
Top stat checked (Showing Discipline and Training, in this case):
Per point checked:
Both checked (Now showing Herbalism):

Top node and per-point heatmap changes

---

Modules/CalcOffence-3_0.lua

Unnerve does not increase the DOT DPS of skills like Essence Drain, [as per Mark_GGG](https://www.pathofexile.com/forum/view-thread/2784387#p22947950).
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/843

Disable Unnerve for DOT

---

Modules/ModParser-3_0.lua

Implements Armour Increase based on Warcry Power in 5 power increments per 25% increase with a limit of 100%.

Support for Warning Call cluster notable

---

Modules/CalcPerform.lua
Modules/ModParser-3_0.lua

Saqawals Nest is meant to provide a 2x buff effect multiplier to nearby allies

Fix Saqawals Nest not scaling Aspect of the Avian properly on Allies

---

Modules/CalcPerform.lua
Modules/ModParser-3_0.lua

- Fixes a crash on Vessel of Vinktar that was caused by setting the Shocked flag on the flask then scaling the flag by flask effect
- Changes Vinktar and Wake of Destruction to give BASE ShockOverride instead of OVERRIDE, which was a change I made to other ShockOverride sources late in the last PR and missed here
The "Shocked" flag on the enemy is now set anytime you have ShockOverride BASE. Every source of ShockOverride has some other condition on it (using flask, on shocked ground, or Summon Skitterbots) so this is only a functional change for Vessel of Vinktar.

Fix Vinktar crash and a couple of OVERRIDE -> BASE

---

Data/3_0/Skills/act_str.lua
Export/Skills/act_str.txt
Modules/CalcOffence-3_0.lua

The damage per minion was not capped to 5 nearby allies and the config was also not showing up properly

Fix Rallying Cry damage cap and config

---

Classes/ConfigTab.lua

https://pastebin.com/DdCqH823 crashes in the production version as it's an old tree looking for the new Chieftain node config 'have you lost an endurance charge recently?'

New node crash fix

---

Modules/Build.lua
Modules/CalcSections-3_0.lua
Modules/ConfigOptions.lua

- Changes many labels in the Config and Calcs tabs to be more consistent with the game and other labels (many capitalization changes, adds missing colons, rephrased a couple to be a proper question, fixed a few typos, this is a big list)
- Tooltips like the calculation modes and the boss dropdown, with multiple mod lines in a row, have new formatting
- Tooltips have been made more consistent in general and several have been reworded for clarity (buff tooltips now all use the word "grants", for example)
- Makes Resist Over Max show up in tooltips again, without putting it as its own line in the sidebar

Fix UI wording consistency and polish

---

Modules/CalcSetup.lua
Modules/ConfigOptions.lua

Pride was not setting the correct flag for min or max effect when you opened an old build, so it would appear that Pride was not working at all

Fix Pride not working with old builds

---

Modules/CalcSetup.lua
Modules/ModParser-3_0.lua

- Support mods on the unique jewels Fertile Mind, Fortress Covenant, and Quickening Covenant which say "Notable Passive Skills in Radius Instead Grant:"
Everything's functional, but one quirk is that the mods don't show the node as the source, but instead the jewel: 
This is how other unique jewels like Coated Shrapnel also work, though:
I couldn't get it to show the proper node source to work after fiddling with it for longer than I care to admit, so I decided to leave it as is.

Support "Notable Passive Skills in Radius Instead Grant"

---

Data/3_0/SkillStatMap.lua
Data/3_0/Skills/act_int.lua
Data/3_0/Skills/sup_int.lua
Export/Skills/act_int.txt
Export/Skills/sup_int.txt
Modules/CalcOffence-3_0.lua
Modules/CalcPerform.lua

- Fixes weird infinite DPS bug
- Stops the damage multiplier from applying to minions
My solution is a little hacky but works. Now CwC gives a useless INC/BASE on the support, then actual damage mods are applied based on the useless values in CalcPerform after filtering out minion skills. Tested on a few builds with a few different minion types, all worked correctly. Those useless mods could actually be used in the future if there's ever a full triggered spells rework, for something like Mjolner's lightning damage for socketed triggered spells mod.

Fix minion skills supported by CwC and Arcanist Brand

---

Classes/ImportTab.lua

Fixes item import process still following shaper/elder era format, effectively "ignoring" conqueror influences.
Add modifier > Pre/Suffix now works without hand-editing the imported item.

Fix imported Conqueror influences

---

Modules/Build.lua
Modules/CalcOffence-3_0.lua

Total number of ticks becomes a potentially useful stat with new brands, to hit breakpoints. Unclear if having such a direct calculation is correct.

Adding brand activation count stat

---

Classes/ModStore.lua
Data/3_0/Skills/act_dex.lua
Export/Skills/act_dex.txt
Modules/CalcSetup.lua
Modules/ConfigOptions.lua
Modules/ModParser-3_0.lua

Finished last missing part of #458 
This PR also introduces the ability of limiting multiplier variables from other actors.
Test it with this jewel:
```
New Item
Cobalt Jewel
Implicits: 0
+5 to Maximum Virulence
```
To verify the limitTarget stuff, try disabling it and seeing how the functionality changes.

Adds support for Virulence Stack Changes

---

Data/3_0/Skills/act_dex.lua
Export/Skills/act_dex.txt
Modules/CalcOffence-3_0.lua
Modules/ModParser-3_0.lua

- Adds support for Burning Arrow's stacking Fire DoT debuff
- Uses SkillParts to switch between 1 and 5 stages
- Supports the helmet enchantment for debuff effect
------------
Note: getting this working also involved moving around and adding some things in CalcOffence. I had to move the DoT calculations to be below the Ignite calculations and add a new "preDotFunc" function, both of which were so it could check Ignite DPS for the debuff damage. I also needed to make it so that if a skill has an existing DoT output before the DoT calculations, it would go through the DoT calculations section and give a Total DoT output, so that the debuff damage will actually be displayed in the sidebar and calcs page. 
According to my testing with other Ignite builds, Chaos DoT builds, a Bleed build, and …

Support Burning Arrow Debuff

---

Modules/ModParser-3_0.lua

There was no way to simulate lucky hits on a character for the purpose of having an aurabot

Add Lucky Hits Override

---

Modules/CalcOffence-3_0.lua

- Woops
In my original Eye of Malice PR, I tested with a Cold DoT build and then added Fire Trap to that build to test the fire resistance calculation. Had no idea that resistance for ignite is calculated elsewhere. Figured it out when I tried to use it on an ignite build. Now it works.
I went ahead and did the same change to Poison and Decay, which also had their own separate resistance calculations. So now if there are ever sources of "Nearby Enemies have x% increased Chaos Resistance", it should apply without any work beyond the mod parsing.

Fix Eye of Malice not applying to Ignite damage

---

Data/Uniques/amulet.lua

The mana reservation mod on Impresence was reworded, which causes ones imported from a character to not be recognised properly.

Update mods on Impresence

---

Modules/CalcSections-3_0.lua

- PoisonDotMultiplier -> ChaosDotMultiplier
When I did the original PR I did everything for Ignite first, then copied it all for Bleed and Poison. Made this mistake while doing the Poison part at like 2 AM. I only made this mistake in the breakdown, not in CalcOffence, so this is just a display bug fix.

Fix Chaos DoT Multiplier not showing up in Poison DoT Multi breakdown

---

Data/3_0/Skills/sup_str.lua
Export/Skills/sup_str.txt
Modules/CalcOffence-3_0.lua

Seismic Cry was dividing the same number by 100 when it should have only been divided once.
Fist of War didn't have the correct ModFlag on the gem and was had an incorrect multiplier applied

Fix Seismic Cry damage and Fist of War ailment calculations

---

Data/3_0/Skills/spectre.lua
Data/3_0/Spectres.lua
Export/Minions/Spectres.txt
Export/Skills/spectre.txt

Some spectres were not using the correct mob to export the skills from
Fix life multiplier on Enhanced Vaal Fallen
Fix bomb base effectiveness on Baranite Thaumaturge
Fix mortar skill on Baranite Sister

Fix Spectre Errors

---

Data/3_0/SkillStatMap.lua

There was an incorrect stat map for Second Wind support that added 1% extra increased CDR to skills supported by it

Fix Second Wind Cooldown

---

Data/3_0/Skills/act_int.lua
Data/3_0/Skills/minion.lua
Export/Skills/act_int.txt
Export/Skills/minion.txt
Modules/ConfigOptions.lua

Carrion Golem now support the proper attack speed and damage multipliers for its combo attack as well as the 50% more increase from nearby non-golem minions

Add proper support for Carrion Golem

---

Modules/CalcOffence-3_0.lua

Fixes an issue where the "(with a x% shock on the enemy)" note wasn't showing up on attack builds. This note:

Fix current shock note not showing in Shock effect breakdown for attack builds

---

Modules/CalcOffence-3_0.lua

Issue was that `actor.strDmgBonus` is never initialized in the event that the Conditional Flag "NoAttributeBonuses" is set. This caused a crash when considering all support gems for a spell when "Iron Grip" or "Iron Will" was considered.
#1263

Fix Issue 1263

---

patch_fork.ps1

Remove old fork patching script as this method of installing the fork is deprecated.

Remove Powershell update script

---

Export/Classes/GGPKFile.lua
Export/Scripts/skills.lua
Export/Skills/act_dex.txt
Export/spec.lua
Export/statdesc.lua

Heist patch

---

Modules/ModParser-3_0.lua

- Adds ModParsing for the mod on Expedition's End, "Freeze Chilled enemies as though dealing x% More Damage"

Support Expedition's End

---

docs/rundown.md

Was looking into ` CONTRIBUTING.md` and noticed the reference to `rundown.md` seems that the ` rundown.md` contained some references to files that no longer exist. Also added the missing references.

chore: Update rundown.md

---

Modules/CalcDefence-3_0.lua

Negative accuracy behaved the same as positive accuracy of the same value for the chance to hit calculation.  I've simply treated it as zero for that calculation to make it accurate again.

Negative accuracy fix

---

Modules/ModParser-3_0.lua

Currently Catalysts (Defense) does not scale mods provided by Corrupted Souls

Implemented Corrupted Soul granted by Replica Soul Tether

---

Modules/ConfigOptions.lua

Change checks for Deathmark to checks for Predator, re-enabling the "Is the enemy Deathmarked?" option in Configuration (now states "Is the enemy marked with Signal Prey?" to reflect naming changes by GGG)

"Is the enemy Deathmarked?" fix

---

Data/3_0/Skills/act_dex.lua
Export/Skills/act_dex.txt
Modules/ConfigOptions.lua

- Updates Skill Parts on Shattering Steel and the new Splitting Steel
- Adds Steel Shard mechanics to Shattering Steel and Lancing Steel, along with config option
- Adds Steel Wards from Shattering Steel
------------
Notes:
- For Shattering Steel's distance scaling, I assumed that the scaling starts at 10 units and reaches zero at 70 units. I assumed this based on the wording. "At the start of their movement" is used on Point Blank to mean "Less than 10 units", and "as they travel farther" is used on Far Shot and the Longshot notable to mean "Peaks at 70 units".
Missing features:
- Call of Steel is missing entirely, primarily because it's missing from the gem/skill files. Since it can't know impale damage from any skills, it would be pointless to have anyway aside from checking the use …

Update Steel skills

---

Data/3_0/Skills/act_str.lua
Export/Skills/act_str.txt

Vitality changed from %hp to flat hp regen, this was not reflected in the statMap for the skill gem. It now is.

Vitality fix

---

Classes/PassiveSpec.lua
Classes/PassiveTreeView.lua
Classes/PowerReportListControl.lua
Classes/TreeTab.lua

This PR (my first on PoB) adds a new button to the bottom of the passive tree that displays a sorted table with the efficacy of every node on the tree, given a selected heat map. Clicking a node in the list will focus and zoom-in on the node clicked, to make finding it easier.
Feedback very much appreciated.
I believe this would be helpful to users upvoting this request as well: https://feathub.com/LocalIdentity/PathOfBuilding/+14
The new button:
Once clicked, a report is presented, based on your current heat map. Example:
Here's a report for a %-based stat:
- The formatting used for numbers in the table relies on formatting rules defined for the sidebar. Not every heat map has a corresponding entry in this table and sometimes it defaults to formatting that is less than optimal. Not a …

Add a "Power Report" Feature: Displays report of passive node efficacy based on currently selected heat map

---

Modules/CalcPerform.lua
Modules/ModParser-3_0.lua

Supreme Ego was also applying to various aura-like effects. Requires `ModCache` rebuild.
Fixes #1457

Fix Supreme Ego applying aura effect incorrectly

---

Modules/CalcOffence-3_0.lua

Fixes #1520
We now round down after support gem mana multipliers and round down mana cost reduction amounts before including them to match how POE does it.

Fixes Mana Cost Increase/Reduction Rounding

---

Modules/CalcOffence-3_0.lua
Modules/ModParser-3_0.lua

- Fixes the Projectile Count output to be accurate when there's a more/less modifier (ie Molten Strike/Spectral Shield Throw threshold jewels)
- Adds parsing for Spectral Shield Throw's additional shards helmet enchantment. Will also parse any future skill that happens to use "additional shard projectiles"
The new formula is correct on Molten Strike and Spectral Shield Throw in the following situations I tested:
- Base
- LMP
- GMP
- GMP + Dying Sun
- GMP + Dying Sun + Beltimber Blade x2
- GMP + Dying Sun + Beltimber Blade x2 + SST's +3 Shards helmet enchantment

Update ProjectileCount formula for accuracy, parse Spectral Shield Throw helmet enchantment

---

Classes/TreeTab.lua
Modules/CalcSetup.lua

Fixes #1492
The new notable name doesn't show up in the anoint UI, but does grant the new stats instead of what is listed in the anoint UI.  For sorting purposes, that will probably be my next fix.

Timeless jewel notables' stats apply when anointed

---

Data/3_0/SkillStatMap.lua

This fixes a crash that occurs when adding Phantasmal quality to Raise Zombie

Fix crash related to phantasmal raise zombie

---

Data/3_0/Skills/act_int.lua
Export/Skills/act_int.txt
Modules/CalcOffence-3_0.lua

#1498 
Now accounts for penetration correctly as being from the resist used
Adding 2 parts for single target vs area so single target does not have the area flag

Hexblast fixes

---

Classes/ImportTab.lua
Classes/SkillsTab.lua

Poe Ninja internal export format clashed with the way i implemented this the first time around:
> Something has broken the way that I (in poe.ninja) import builds. I guess it is related to the changes around alt qualities. My process involves generating an import for pob that looks like this: 
`<Gem level="19" quality="0" enabled="true" nameSpec="Armageddon Brand" enableGlobal1="true" enableGlobal2="true" />`
and this has worked so far, but now what I get back from pob (and that I put in the pob code on poe.ninja character page) contains this:
`<Gem enableGlobal2="true" quality="0" level="19" enableGlobal1="true" qualityId="Default" enabled="true" nameSpec="Brand"/>`
Notice how the first word is missing from the nameSpec, so Armageddon Brand becomes Brand which is invalid.
Fixed it by …

fix(alt-qual): unify method to parse quality and name

---

Modules/CalcDefence-3_0.lua

Fixed Power of Purpose (Legion keystone) not granting double armour
Fixed "increased Evasion Rating and Armour" modifiers not applying to armour originating from conversions

Fix Power of Purpose and Armour Conversions

---

Modules/CalcBreakdown.lua
Modules/CalcOffence-3_0.lua

Adds a small note showing which elemental resistance Hexblast is using for its Chaos damage (at the top of the tooltip where it says "Enemy Resistance:")
-------
Unless you have some amount of Phys/Fire/Cold/Lightning damage, it's not possible to see all of the enemy's resistances and thus it might not be clear which element Hexblast is actually using. This PR adds a small note to more clearly show which element it's using.

Add note to Effective DPS mod tooltip to Hexblast

---

Modules/CalcOffence-3_0.lua

Fixes a bug where increased resistance modifiers like on Eye of Malice were not being considered on Hexblast
---------
Simple issue where whoever implemented Hexblast's resistance shenanigans apparently copy/pasted some stuff and forgot to change a "damageType" to "damageTypeForChaos". Basically only affected Eye of Malice, I believe, but it's a big chunk of damage that was missing from builds that tried to use that interaction.
Fixes #1508

Fix Hexblast interaction with increased/reduced resistance modifiers

---

Modules/CalcOffence-3_0.lua

Removes ModFlag.Melee from the Exerted damage mods in CalcOffence, as this was preventing them from applying to ailments

Remove ModFlag.Melee from Exerted mods

---

Data/Uniques/ring.lua

Emberwake was missing catalyst tags on one of its mods.

Fix catalyst tags on Emberwake

---

Data/3_0/Skills/spectre.lua
Data/3_0/Skills/sup_int.lua
Export/Skills/spectre.txt
Export/Skills/sup_int.txt
Modules/CalcActiveSkill.lua
Modules/ConfigOptions.lua
Modules/ModParser-3_0.lua

Fixes mods on the tree that referred to 'curses' not correctly applying to hexs and marks
Fix Projectile weakness mods on spectres
Fix +1 curse gems from Awakened Blasphemy

Fix Curse mods on the tree not applying correctly

---

Classes/ImportTab.lua
Classes/SkillsTab.lua

- if quality is nil or default try to parse
- if first word matches any alt qual return gem name minus first word
and set appropriate quality
- else set to gem gemTypeLine + Default (this was the missing case!)
- if we dont even have a gem name return whatever we put in
also removed the left over method from my first iteration
Tested with the following snippet:
```lua
local alternateGemQualityList ={
{label = "Default", type = "Default"},
{label = "Anomalous", type = "Alternate1"},
{label = "Divergent", type = "Alternate2"},
{label = "Phantasmal", type = "Alternate3"},
}
function GetBaseNameAndQuality(gemTypeLine, quality)
if gemTypeLine and (quality == nil or quality == 'Default') then
local firstword, otherwords = gemTypeLine:match("(%w+)%s(.+)")
if firstword and otherwords then
for _, …
```

fix(load-quality): when overriding quality also pass existing qual

---

Modules/CalcOffence-3_0.lua

Adds TotalPoisonDPS to the combineStat list for Average Hit attack skills
Before:
After:
--------
I noticed that if I tried to sort gems by Poison DPS on an Assailum build I'm planning, it wouldn't even attempt to suggest gems and would just sort gems alphabetically. Through some investigation I found out that the gem sorter couldn't see TotalPoisonDPS on Average Hit attack skills(even though that stat was being calculated) because main hand and off hand stats weren't being combined, and the gem sorter was checking for the combined stat. It other words, it was checking for "output.TotalPoisonDPS", but only "MainHand.TotalPoisonDPS" and "OffHand.TotalPoisonDPS" existed. Now the combined stat exists and the gem sorter works properly.

Add TotalPoisonDPS to combineStat list for Average Hit attack skills

---

Modules/Main.lua

Default SOCKS5 proxy mode does name resolving locally. This will not work under some network conditions. This merge request adds the support of SOCKS5 host name mode which allows cURL to send the host name to the proxy server and resolve it remotely.

Support SOCKS5 Host Name Mode Proxy

---

Modules/CalcSetup.lua
Modules/ModParser-3_0.lua

Double-influenced Shaper/Elder items were counted twice
Fixes #1129 Requires `ModCache` rebuild

Fix Siphoning Charges limit

---

Data/3_0/Skills/act_str.lua
Export/Skills/act_str.txt
Modules/ModParser-3_0.lua

- Supports the debuff stacks of Infernal Blow, using SkillParts
- Supports the helmet enchantment that makes the debuff deal a higher % of damage
-----------
Currently I have it set up that the stack SkillParts are only calculating the damage of stack explosions. My question is, should that be the case? Which of these options sounds best for the 6 stacks explosion:
1. Show the DPS of 6 stacks explosion and does not count the melee DPS (this is the current implementation)
2. Show the average damage of the 6 stacks explosion
3. Shows the combined DPS of 6 Stacks explosion + Melee
Also, should there even be a part for the 1 stack explosion? I figure it would be useful to know how much damage it's dealing so it's easy to optimize this explosion for the largest hits possible for clear speed. …

Support Infernal Blow

---

Classes/ListControl.lua
Classes/PowerReportListControl.lua

This will almost definitely conflict with #1570, but I can merge that PR into this one if it's easier that way
Columns with headings are only used in the power report and the exporter, that I found.  Currently making a column sortable is an explicit setting, but I can make a generic sorter if that's preferred.
I also removed some extraneous code that wasn't needed now that we have sorting.  I can add back the "Only notables" checkbox if desired

Adding column sorting for ListControl

---

Modules/CalcOffence-3_0.lua
Modules/ModParser-3_0.lua
Modules/ModTools.lua

Minion damage conversion to player is now a flag and mod pair like cast speed/spell damage
Added tag conversion support so minion damage while player affected by herald works, and limits like on Indigon are correctly converted to have a max associated with the conversion rate
Added ModTools method to get the 'tags' from a mod
Herald enabled
Herald disabled
Indigon Kinetic Bolt at 16000 mana
16000 / 200 = 80 * .25 = 2000% * 150% conversion = 3000%
Prodigal perfection

Mod tag conversion

---

Modules/CalcBreakdown.lua
Modules/CalcOffence-3_0.lua

Fixing this minor bug where 'nil' was being displayed on the DoT breakdowns

Removing unused variables and 'nil' being displayed in DoT breakdowns

---

Modules/Build.lua
Modules/CalcTools.lua

Some gems have new requirements scaling since last balance change.
The lowest stat requirement value should be 14.

Fix gem requirements

---

Data/SkillStatMap.lua
Modules/CalcOffence.lua
Modules/CalcPerform.lua

When elemental focus is used currently, you can still inflict scorch, brittle, and sapped.  Now that is disabled for your main skill.

Adding logic to disable alt ailments when ele focus is used

---

Data/Bases/dagger.lua
Data/Bases/staff.lua
Data/Bases/wand.lua
Export/Bases/dagger.txt
Export/Bases/staff.txt
Export/Bases/wand.txt
Export/Scripts/bases.lua

This takes care of many mod issues laid out in the issue.  The only remaining issue is Convoking Wand appears twice, but PoB takes the last one so it still works.  It's easily fixed, but I have to specify each and every type to do so

Fixes #1741 - Adding separation of rune daggers, warstaves, and convoking wand

---

Modules/ItemTools.lua

It broke when the source file encoding changed and caused some items to be pasted incorrectly.

Fix item text sanitization

---

Data/Generated.lua
Modules/Data.lua

Complete requested refactoring of keystone data. Now all non-timeless jewel exclusive keystones are present and the ones that cannot roll on Skin of the Lords are excluded before generating it instead.

Refactor keystone data

---

Modules/CalcPerform.lua

Addresses cases when Arcanist Brand is used as a support with Runesmith, or Brand Loyalty and Runebinder.
Makes damage increase per brand attached scale properly (10% for two brands attached to the enemy instead of 5% as previously).
STR: 
1. Take minimal reproducible build: https://pastebin.com/FY4bQej3
2. Set `# of brands attached to the enemy` to `2`
3. Check `Effective DPS Mod`
Please, let me know if I missed something

Use brand limit from the Arcanist Brand instead of the main skill

---

Classes/SkillsTab.lua
Data/Skills/other.lua
Export/Skills/other.txt
Modules/CalcSetup.lua
Modules/ModParser.lua

Supersedes #929 
Doesn't work with keystones as they are treated differently than other nodes.
Fixes #88 
Requires `ModCache` rebuild

Add support for skills granted by tree nodes

---

Classes/GemSelectControl.lua

Also changes default skill gem quality to 20% for the tooltip to be more useful.

Add tooltip to skill gem drop-down

---

Modules/CalcOffence.lua
Modules/ModParser.lua

Initial implementation.
Tested to work additively with Spellslinger.
Tested by spoofing a wand that has "Battlemage" as a modifier.

Ritual - Implemented Battlemage

---

Modules/CalcSections.lua
Modules/ConfigOptions.lua
Modules/ModParser.lua

Adding Rupture stack config
Adding rupture deadeye parsing
Currently implemented as player mod, running into issues with the damage taken to make it more accurate as an enemy mod

Ritual - Rupture stacks

---

Modules/ModParser.lua

Tree power was suggesting taking EE when you had Malachai's Artifice.  Until we support the socketed skill getting EE alone, this assumes Malachai's Artifice gives you EE (i.e. exactly what it was doing before, just without letting you have it twice).

Fixing Elemental Equilibrium on Malachai's Artifice so you can't have both it and EE

---

Data/Skills/act_str.lua
Export/Skills/act_str.txt

Anomalous Flesh and Stone grants 10% increased Evasion and Armour at 20% quality
Only the Evasion was working before, now the Armour does as well.

Fixed Anomalous Flesh and Stone by adding Increased Armour

---

Data/Skills/act_int.lua
Export/Skills/act_int.txt

In game version 3.6.0, Dark Pact's base radius was changed from 24 to 26 units.

Fix Dark Pact radius

---

Classes/Item.lua

Take items like this cluster jewel for example:
````Cataclysm Glimmer
Large Cluster Jewel
Unique ID: f974de4732542e96894c8a41a6e15b2d81bdca1cf02bc3bb14cff9eb57c3d111
Item Level: 71
LevelReq: 54
Implicits: 4
{crafted}Adds 8 Passive Skills
{crafted}2 Added Passive Skills are Jewel Sockets
{crafted}Added Small Passive Skills grant: Mace or Sceptre Attacks deal 12% increased Damage with Hits and Ailments
{crafted}Added Small Passive Skills grant: Staff Attacks deal 12% increased Damage with Hits and Ailments
Added Small Passive Skills also grant: +5 to Dexterity
1 Added Passive Skill is Calamitous
1 Added Passive Skill is Martial Prowess
1 Added Passive Skill is Weight Advantage
````
The `{crafted}` text shows up on the second line.  This PR removes that.  I tested a few other multiline …

Remove crafted text on multiline mods

---

Classes/SkillsTab.lua

Fixes #1809 I don't think there is any use case for changing these inputs before selecting a gem.  Please correct me if I'm wrong or if you think of one while reviewing this PR.  I'll also ask in the issue to make sure I'm not removing functionality that the user uses right now.

Fixes #1809 - Disables controls before gem is selected

---

Classes/GemSelectControl.lua
Classes/SkillsTab.lua

I ended up adding multiple entries to the list, one for each qualityId.  I'm most nervous about this slowing down the dropdown box more than it was before.  It definitely adds to the memory footprint, unfortunately, but I made that a conscious choice to keep the code looking clean.
There might be a better way to have the gemId keys, but a simple string-based tuple kept the code clean enough and refactoring to a minimum.

Adding all alternate qualities to dropdown via a checkbox

---

Modules/CalcDefence.lua
Modules/CalcSections.lua

Current copy is "Taken From Block", which implies that the number is how much damage you take when you block.
Instead, I changed the copy to "Block Effectiveness", because the number (35%) is how effective each block is.
I'm honestly not sure if this is better (I think it's better, but other folks could disagree), but it resolves #1743.

Adjusted 'Taken From Block' to show damage taken

---

Modules/ModParser.lua

Adds support for "Physical Damage taken from Hits" wording found on the Persistence Notable.

Add support for Persistence Notable

---

Modules/Build.lua

Fixes an error that occurs when the build last saved in `Settings.xml` was deleted outside of PoB.

Small PR to fix dev builds that fail to load their build

---

Classes/Item.lua

This else statement was put in specifically for Pure Talent, so I made that more explicit.

Fixes #1887 - Allowing colons when naming a magic item

---

Classes/GemSelectControl.lua
Classes/SkillsTab.lua

…tance
Sets gemInstance.level, not gemData.level
With a current lvl 20
With a current lvl 10
With a current empower
With a current awakened

Fixes gem tooltip errors

---

Modules/ModParser.lua

Fixing parsing of instruments of virtue
Fixing crit chance handling to not exclude the case when stats are equal

Fixing inquisitor mods

---

Modules/CalcOffence.lua
Modules/ConfigOptions.lua
Modules/ModParser.lua

Did so by implementing the following:
- If you have a source of pierce add a box to the configuration tab "# of times Skill has Pierced:"
- Create a PiercedCount stat that is the minimum between your maximum # of pierces and the value in the configuration box
- "for each enemy pierced" adds a PerStat tag for PiercedCount

Add support for "Projectiles deal #% increased damage for each enemy pierced"

---

Data/SkillStatMap.lua

This block was duplicated, causing an error for divergent critical damage support

Fixes #1933

---

Modules/ConfigOptions.lua

Also fixes a similar issue with Alchemist's Genius
While doing this change I found a similar issue with the Vaal Arc buff for lucky hits.  I'll file a separate issue against that one, since I couldn't fix it in this PR.

Fixes #1941, #1861 - Fanaticism and Convergence persisting after deallocating nodes

---

Data/Uniques/helmet.lua

In patch 3.13.0, the base type of Hrimnor's Resolve got changed from Samite Helmet so Samnite Helmet, causing it to not show up anymore in the unique item database.
Fixes #1972

fix: rename base type of hrimnor's resolve so it shows up again

---

Export/Skills/act_int.txt
Modules/CalcOffence.lua

Tested with Essence Drain and Creeping Frost, they're still behaving the same.
Previous code was assuming all skills with dotIsArea had identical skillFlags for each part.

Fixes #1991 - Flame wall secondary damage isn't affected by area damage

---

Classes/ConfigTab.lua

I believe the previous commit changed this on accident, as part of #1365 , and we've gotten a few issues related to it, so I changed it back.
Direct link to commit: https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/1365/commits/1a1ae201e79a5e4b0bfc67bd0124b10c147b7efe

Fixes #1994 - Config options based on mainEnv skill, not calcsEnv selection

---

Classes/GemSelectControl.lua
Classes/SkillsTab.lua

set gemInstance.qualityId to 'Default' if missing (from older builds)

Fix QualityId Related Crashes

---

Data/SkillStatMap.lua
Modules/ModParser.lua

If only Ballista Totem Support would add the SkillType.Ballista flag, I would use that one instead of ProjectileAttack, but here we are...

Fixes #2032 - Added ProjectileAttack flags to Ballista totem # modifiers

---

Data/Skills/sup_dex.lua
Data/Skills/sup_str.lua
Export/Skills/sup_dex.txt
Export/Skills/sup_str.txt

Noticed Impale Support also wasn't applying phys damage reduction correctly, so I fixed that as well.  Divergent Intimidating Cry was also having issues, but it seems those are more involved than Impale, so I'll file a separate issue for that.

Fixes #2012 - Divergent Fortify Support + Impale Support

---

Modules/CalcActiveSkill.lua

This fix should address my concerns from #2020.
All minion/spectre skill definitions provide the `levelRequirement` entry as they're all generated from the export scripts.

Use correct field for minion skill level requirements

---

Modules/ConfigOptions.lua

- Sets the maximum Awakening Level to 9, which is possible now with an Atlas Passive that gives +1 to Awakening Level. This number is only ever used for ailment calculations but I figured it should still be updated.

Update max Awakening Level

---

Classes/ItemSlotControl.lua

Slots with names like "Weapon 2 Abyssal Socket #1" will match the first group of digits as the slotNum for abyssal sockets, which is checked against the abyssal socket count on the parent item when considering whether an abyssal socket is active or not.
This fix ensures that we if possible match against the end of the string by anchoring the match, falling back on matching anywhere if that's not possible. This ensures that the match for items like "Weapon 2Swap" is still correct.
This addresses the problem demonstrated in #2049 and ensures that the `slotNum` is correctly parsed. Unlike the first fix suggested by me in the issue, this also keeps the right `slotNum` for items where the only number isn't at the end of the name.

Find right slotNum when slotName contains multiple numbers

---

Data/Skills/act_str.lua
Export/Skills/act_str.txt
Modules/CalcPerform.lua

Warcry non-damaging effects now disregard uptime when using Max Hit mode.
Fixed incorrect base armour for Ancestral Cry, and added divergent quality armour increase.
Fixed Enduring Cry life regen (outdated statMap key prevented `CalcPerform` from getting the correct value, so the skill never contributed to life regen).
Finally, removed a redundant `extraExertions` (it's already defined in line 801).

Warcry fixes for #1644, #1883, #2029, #2058.

---

Modules/ConfigOptions.lua

#1845 updated the computed value of Tailwind from 10% to 8% but omitted the tooltip in the config options. This fixes that cosmetic problem.
Unmodified resubmission of #2066 as I've reforked from the correct PoB repo.

Update Tailwind config tooltip with new 8% value

---

Data/Uniques/boots.lua

> Now grants 1 to 80 Chaos Damage to Attacks per 80 Strength (previously per 50 Strength). This affects all versions of the item.
https://www.pathofexile.com/forum/view-thread/3009157
CTRL + F ``Replica Alberon's Warpath``

Update Replica Alberon's Warpath boot per 3.13 patch note

---

Data/Uniques/gloves.lua

Looks like they were incorrect from the start

Fix Offering to the Serpent

---

Data/Skills/sup_int.lua
Export/Skills/sup_int.txt

Added support for the Anomalous Quality Minion Life gem.
The quality was previously adding a flat 1 health per second regeneration instead of 1%
Fixes #2108

Anomalous Quality Minion Life Support

---

Data/Skills/sup_int.lua
Export/Skills/sup_int.txt
Modules/CalcPerform.lua
Modules/ModParser.lua

This probably needs some more work to take into account the values at other gem levels, but it's not in the GGPK, so that might be hard to acquire in our current implementation

Added Phantasmal Might buff as Summon Phantasm's level 21 value

---

Export/Classes/GGPKData.lua
Export/Scripts/bases.lua

This ended up being more involved than the referenced issue, but these changes allow us to avoid human error in setting tags on bases manually.  The actual .lua files that changed as a result of this are mace.lua and flask.lua, the rest got "changes" in that the tags were reordered.
I elected to leave the #baseTags directive in the .txt files there for now (combining the datamined tags with those manually specified), but can be easily be removed in another commit if desired.

Fixes #2059 - Implemented automatic generation of base item tags from the ggpk

---

Data/Skills/act_str.lua
Export/Skills/act_str.txt
Modules/CalcDefence.lua

Fixes #1701 
Should Iron Reflexes get renamed on the Calcs tab to be something other than "Evasion to Armour" or is it fine having 2 "Evasion to Armour" lines when you have both Iron Reflexes and Divergent Determination?

Added Evasion to Armour conversion for Divergent Determination

---

Modules/Main.lua

The idea here is to support custom URI schemes, which pass the URI data to the executable.
The pastebin code is extracted from the second parameter if it's of the form: "^pob:[/\\]*pastebin[/\\]+(%w+)[/\\]*"
- The build is loaded from pastebin, decompressed, and then loaded at startup instead of the build specified in the Settings.xml
This is best used with the new PathOfBuilding executable which will always pass the lua script as the first parameter (and thus all other params are pushed forward by one)
- However, this can be tested with the old executable by specifying the path to the Launch.lua as the first parameter, and then the "pob://pastebin/XXXXXXXX/" as the second parameter.
If you have the new [PathOfBuilding.exe](https://drive.google.com/file/d/1r8s6i-smrkqLKY-KJ_pQHsncz_twV8zs/ …

Ability to load a build from commandline.

---

Data/Skills/act_dex.lua
Export/Skills/act_dex.txt

- Removes the No Stages/Max Stages skill parts from Cyclone, as the stages box takes care of that function now

Remove SkillParts from Cyclone

---

Data/ModCache.lua
Modules/CalcPerform.lua
Modules/ModParser.lua

#2176 
Previously Supreme Ego was using the same implementation as Ichimonji even though they have different wordings and effects.
"Your Aura Buffs do not affect allies" vs "Auras from your Skills do not affect Allies"
I separated out Supreme Ego with its own, new flag "SelfAuraSkillsCannotAffectAllies" and added it to the ExtraAuraEffect logic in ClacPerform but not the ExtraAura logic so it doesn't disable non-skill auras now.
I then checked all 85 references to ExtraAura in ModCache to make sure I wasn't breaking anything and found one Banner node erroneously tagged as an ExtraAura and not ExtraAuraEffect.

Supreme Ego now works with non-skill Auras

---

Data/SkillStatMap.lua

Apply the charge distance multiplier, ramping from 0 to 60 units of distance.

Shield Charge: support charge distance multiplier

---

Modules/Build.lua

There is no reason to build the ascendancy drop down every single frame and select the appropriate ascendancy to display. This PR merges it with Class Dropdown 1-time population and just uses that to create the drop-down and then set the proper index.

Build:OnFrame Improvement

---

Classes/ItemsTab.lua

Opted to just show the highest mod in situations where the highest mod didn't have a value for the slider

Fixes #2197 - Intimidate/Unnerve mods throwing error

---

Classes/ItemsTab.lua

It's impossible to restrict crafted mods for imported/copied items, so with this we should be able to close
https://feathub.com/LocalIdentity/PathOfBuilding/+41

Added group restrictions to crafted mods for crafted items

---

Classes/PassiveTreeView.lua

Implemented the search changes that were talked about in issue #2173
The only thing I'm not sure about is the search function I had to make, looping over multiple searches. Because of LUA's non-conformance to standard POSIX RegExp, there seems to be no easy way to do a "match all in any order" (Which I didn't realize when starting this project). I did some testing, and it seems to match between in-game search and PoB search.
Please, by all means, compare results and let me know if any inconsistencies are found, or if I missed some hidden functionality of the PoE search bar.

Implemented PoE matching search function. Resolves #2173

---

Data/Skills/sup_str.lua
Export/Skills/sup_str.txt

Shockwave secondaryGrantedEffect "SupportBluntWeaponShockwave" was not calculating proper DPS due to using attack rate rather than trigger cooldown. This fixes it.

Fix for Shockwave secondary trigger rate

---

Modules/ConfigOptions.lua

#1976
Previously the checkbox if you've lost an endurance charge in the last 8 seconds was hard-coded to the Chieftain ascendant node, cleaned that up for Divergent Endurance Charge on Melee Stun.

Divergent Endurance Charge on Melee Stun Checkbox Fix

---

Modules/ModParser.lua

Added support for "you take no extra damage from critical strikes while elusive" from Mistwalker

Take no Extra Damage from Critical Strikes while Elusive

---

Classes/ImportTab.lua

Unfortunately, we don't support Unicode characters, but this import page does technically work without breaking.
Since there is a Chinese frontend for PoB that does support Unicode, I'm submitting this PR.  I could add a toggle in Settings.xml to disable it by default

Add support for importing from Garena and Tencent realms

---

Modules/ModParser.lua

This is the diff for `Data/ModCache.lua` after this change (note some of the added lines are because my dev branch is behind upstream, I believe)
```diff
7920a7921
> c["Cannot Recharge or Regenerate Energy Shield"]={{[1]={flags=0,keywordFlags=0,name="NoEnergyShieldRecharge",type="FLAG",value=true},[2]={flags=0,keywordFlags=0,name="NoEnergyShieldRegen",type="FLAG",value=true}},nil}
9008,9011c9009,9012
< c["Enemies Cursed by you have Malediction if 33% of Curse Duration expired"]={nil,"Enemies Cursed by you have Malediction if 33% of Curse Duration expired "}
< c["Enemies Cursed by you take 25% increased Damage if 75% of Curse Duration expired"]={nil,"Enemies Cursed by you take 25% increased Damage if 75% of Curse Duration expired "}
< c["Enemies Frozen by you take 20% increased …
```

Add generic mod parsing for enemy modifiers

---

UpdateCheck.lua

Preparatory update for 2.0.0.
With the runtime files no longer being located in a zip file, whitespace is file names like `Path of Building.exe` becomes an issue.
This PR ensures that file names will always be URL safe.
I've taken care to test this PR in various update scenarios, including updating the runtime, vendored libraries and the updater itself.
My main motivation for modifying the downloader function signatures is that string splitting/slicing in Lua is painful.
Since there are no more zip files in this repo to be downloaded, I'd like to remove the respective parts from the updater in a future PR.

Escape file names in URLs the updater visits

---

Classes/ItemsTab.lua

This PR fixes an (unwanted) interaction in the crafting menu that could reliably crash Path of Building. It removes the bench craft option for any jewel type.
To reproduce this error: Craft an item, select any type of  jewel, for example a cluster jewel. Press 'Add modifier'. Then with the source being the bench craft, click in the modifier section. Can take up to 10+ seconds and several clicks.
Afaik
Jewels cannot be bench nor essence crafted.
Flasks can be bench crafted (catarina) but not essence crafted.
'if self.displayItem.base.subType ~= "Abyss" or (self.displayItem.type ~= "Jewel" and self.displayItem.type ~= "Flask") then'
This condition always evaluated to 'true' apart from when the item was an actual abyss jewel, which then in turn enabled the bench crafting option with an empty …

Fix: remove 'add bench craft' options from items that cannot be bench crafted

---

Data/Uniques/amulet.lua

25 -> 70 
https://pathofexile.gamepedia.com/Yoke_of_Suffering
#2285

Fix: yoke of suffering equipment level requirements

---

Data/Skills/act_str.lua
Export/Skills/act_str.txt

Because of it being a debuff the term "Enemy~" causes it to not be applied due to how line [1865 of CalcOffence.lua ](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/cbfca046c220c93af5466f7e43cd3c9b150e1304/Modules/CalcOffence.lua#L1865)works.

Divergent Pride Fix

---

Modules/ModParser.lua

[v2] Rely on both Condition:Taunted and Condition:UsedWarcryRecently
~~Adding a config entry "is the enemy taunted by your warcries" felt a bit overkill.~~
~~Another option was to check for the presence of any warcry before enabling the mod, but that too felt overkill.~~
~~I decided to simply use the taunted config option already available instead.~~

Support "enemies taunted by your warcries take x% increased damage"

---

Modules/CalcPerform.lua

This PR fixes the calculation for the amount of ballistas summoned while wielding any type of Iron Commander. #2269 
Test PoB: https://pastebin.com/zEWqd9zY with 28 active ballistas.
**Before**
**After**
The calculation for activeTotemLimit happens too early in CalcPerform.lua thats why bonuses from Hierophant's Ritual of Awakening or the Iron Wood notable only took +1 summoned totems/ballistas into account that are found in the skill-tree.

Fix: BallistaLimit with (Replica) Iron Commander

---

Data/SkillStatMap.lua
Modules/CalcOffence.lua

Since the original calculation of uptime includes the variables for warcry speed, cooldown time, etc., the overall uptime could be estimated by just multiplying that by the additional cooldown usages. Since additional cooldown usages will allow us to retrigger the warcries (assuming they are not used rapidly in succession), it will provide a higher uptime of the warcry.
Without second wind (lvl 1):
With second wind (lvl 1):
With second wind (lvl 1, anomalous 20 quality)

Include additional cooldown usages in warcry uptime calculations

---

Data/SkillStatMap.lua
Modules/CalcOffence.lua

Fixes self-cast skills not have DPS if linked to an unsatisfied trigger or a support gem that enforces "showAverage" flag.
To Test: make a new build and add Freezing Pulse and Cast on Crit as the skills. See how on `dev` you don't get a DPS in left-hand-side bar or in Calcs.
Retest same setup with this PR and see how it works now.
Additionally, you can see the Cast Rate fix in play for skills like Frost Bomb being incorrect since prior to this PR their cooldown is not considered as a limiting factor to how fast they can be cast.

Fixes Cast Rate for Self-Cast Skills that have Cooldown & Display DPS

---

Modules/Build.lua
Modules/CalcOffence.lua

Adds 1-line Culling DPS after all the ailments (if any) if Culling exists in the build stating DPS impact of Culling. This clears up why the Combined DPS value is different from Total DPS value in such builds.

Add Culling DPS left-hand-side Display if build includes culling

---

Modules/Data.lua

Previously ServerTickRate was set to `30`. Per GGG the ServerTickTime is actually hardcoded to 0.33 exactly, making the ServerTickRate = 1/0.033 or 30.303030 (repeating).

Updated ServerTickRate; Added ServerTickTime

---

Modules/Build.lua
Modules/CalcDefence.lua

Fix phys. damage reduction going below zero. Also show phys damage reduction if it is zero (to avoid confusion and should be a pretty rare case)
As per: https://www.reddit.com/r/pathofexile/comments/fcojvn/question_regarding_enemies_have_to_total_physical/fjcel7v/
With "You are crushed" (and no other source of phys dmg reduction:
With "You are crushed" and four endurance charges:
With "you are crushed", four endurance charges and 40% increased physical damage taken:
Without "you are crushed" and some armour:

Fix Physical Damage Reduction able to go below zero

---

Modules/CalcBreakdown.lua
Modules/CalcOffence.lua
Modules/ModParser.lua

Adds support for admiral lowest resist mod. Also refactors code a little so that Hexblast works with same code.
Hexblast linked with added cold/lightning without EE on Sirus:
Hexblast linked with added cold/lightning with EE hit as fire on Sirus:
Ground slam with added cold/lightning without EE on Sirus:
Ground slam with added cold/lightning with EE hit as cold on Sirus:
Ground slam with added cold/lightning with EE hit as cold on Sirus with The Admiral equipped:

Add admiral lowest resist

---

Modules/CalcPerform.lua
Modules/ModParser.lua

Malediction is a debuff that inflicts 10% increased damage taken and 10% reduced damage dealt.
As of now, it is only implemented for the Occultist node as an enemy 10% increased damage taken mod.
However, The Dark Seer is another source of Malediction and cannot be implemented the same way as we don't want those 10% to stack.
This commit turns Malediction into a flag and adds support for The Dark Seer's mod that inflicts it.
[v2] use modDB rather than enemyDB in doActorMisc(env, actor)

Add support for The Dark Seer's Malediction debuff

---

Classes/ItemsTab.lua
Modules/ModParser.lua

Added support for Steelskin and Arcane Cloak enchants.
Fixed enchanting dialog filter. It was based on the gem name instead of the effect name. In cases where only secondary effect had an enchant (like Vaal Molten Shell and Molten Shell) the enchants were not displayed.
Fixes #2238

Add enchants and fix enchanting UI

---

Data/SkillStatMap.lua

This PR fixes #2357 
before:
after

Fix: changed divergent nightblade from base crit to inc crit%

---

Data/Spectres.lua
Export/Minions/modmap.ini

Seems like we can use `SkillStatMap.lua` for these mods instead of adding them manually, but this works for now

Add support for Flickershade spectre chaos damage conversion

---

src/Data/Skills/sup_dex.lua
src/Export/Skills/sup_dex.txt

Removed duration flag from Mirage Archer as it adds it natively anyways from the Mirage Archer Gem Support
```
requireSkillTypes = { SkillType.SkillCanMirageArcher, },
addSkillTypes = { SkillType.Duration, },
excludeSkillTypes = { SkillType.Vaal, SkillType.Totem, SkillType.Trap, SkillType.Mine, SkillType.Minion, },
```

Fix Mirage Archer Duration Flag

---

LICENSE.md
runtime/lua/lua-profiler.lua
src/Modules/Common.lua

PR #2359 introduced `lua-profiler` to PoB. Third-party libraries should be vendored in the `runtime/lua/` directory. `src/Modules` is for core domain objects, not auxiliary libraries.
Even though we don't distribute this library to end users, we still distribute it to our contributors. Since the licencing info in the vendored library is insufficient, we have to perfect it ourselves. There is a caveat to my approach: The licence text will show up in end user distributions. If you think this is a problem and could maybe find a better solution, please let me know.

refactor: vendor lua-profiler correctly

---

src/Modules/CalcOffence.lua

GC's mana cost and cooldown are important information that shouldn't be left out.
The cooldown is a direct impact on long-term dps and is especially important for non-channeled skills that don't rely on attack speed with GC. It's also a nice thing to know if your charge generation depends on GC via the cluster node "Mob Mentality", or if you use "Escalation" for life recovery on warcry, etc.. many things depend on cooldown.
Mana cost is less important but still, if you are tight on mana, it's important to know if you have enough to cast GC.
@Nostrademous

General's Cry: keep manacost & cooldown information

---

src/Data/Skills/act_dex.lua
src/Data/Skills/act_int.lua
src/Data/Skills/act_str.lua
src/Data/Skills/other.lua
src/Export/Skills/act_dex.txt
src/Export/Skills/act_int.txt
src/Export/Skills/act_str.txt
src/Export/Skills/other.txt
src/Modules/CalcActiveSkill.lua
src/Modules/CalcPerform.lua

I only corrected the mods I was able to test. This includes the amounts of guards, Arcane Cloak mana consumption, Cyclone movement speed penalty and crab barriers.
It is ready to be merged but should be expanded upon after additional testing.
Fixes #1797 #2353 partially #2245

Fix incorrect application of Buff Effect

---

src/Data/Uniques/claw.lua

The Replica Last Resort unique Claw now grants 25% increased Attack Speed when on Low Life (previously 50%). Existing versions can be updated to the new values with a Divine Orb.

replicas last resort now grants 25% ias when on low life

---

src/Data/Uniques/jewel.lua

The Vigil unique Jewel now grants Fortify with a base duration of 8 seconds (previously 12 seconds)

update the vigils fortify duration to 8 seconds

---

src/Classes/GemSelectControl.lua
src/Classes/PassiveTreeView.lua
src/Modules/Build.lua
src/Modules/CalcActiveSkill.lua
src/Modules/CalcOffence.lua
src/Modules/CalcPerform.lua
src/Modules/CalcSetup.lua
src/Modules/Calcs.lua
src/Modules/Common.lua

General's Cry + Dominating Blow seems to be a troublesome combo that really stress-tests my implementation of creating a copy of an active skill to give to mirage units.
This fixes the latest crash.
TODO - fix General's Cry DPS to not be players, but minions in the case of Dominating Blow

Generals Cry crash fixes

---

src/Modules/ConfigOptions.lua

Physical Aegis checkbox had the same name as Innervate checkbox causing them to merge state

Fix Physical Aegis checkbox getting mixed with Innervate

---

src/Modules/CalcOffence.lua
src/Modules/Calcs.lua

I previously added a check using `skillFlags.DoTCanStack` but the location I did it in still allowed 1 stack from Mirage Archer to be included in calculations. This fixes it at the FullDPS roll-up level and the reported Mirage Archer DPS contribution.
Tested with Burning Arrow

Fixes Mirage Archer applying DoT stacks when they shouldn't

---

src/Classes/ItemsTab.lua
src/Modules/ItemTools.lua

Fix non-integer catalyst scaling issues

---

src/Data/Skills/act_str.lua
src/Export/Skills/act_str.txt

The Stages box was multiplying damage on all aliments instead of just the phys dots

Fix Exsanguinate stacks applying to all DoTs

---

src/Modules/CalcOffence.lua

Fix error when comparing bows with Mirage Archer for Ignite/Bleed

---

src/Data/Skills/act_str.lua
src/Export/Skills/act_str.txt

Fix Punishment Curse doesn't affect the DPS while select "Enemy is on Low Life"
Issue #2607 Punishment Curse DPS calculation/For Effective DPS:Is the enemy on Low Life check bug

Fix Punishment Curse doesn't affect the DPS while select "Enemy is on Low Life"

---

src/Modules/CalcPerform.lua

The actual change is tiny - moving the division by 100 out of call to `modf` allows for 2 more decimal places of precision
Also renamed some variables to not confuse them with actual costs.

Update reservation rounding

---

src/Data/Skills/act_int.lua
src/Export/Skills/act_int.txt

Overrides the cast rate to the Skill Cooldown. Matching functionality on Shockwave Support.
Fixes #1277
The numbers are still off because it's unrealistic that you're casting Vortex perfectly on cooldown timings but it's a whole lot closer than 0.
https://pastebin.com/spzjUTKW For a test build if you need it.

Vortex's initial hit is now supported

---

src/Modules/CalcPerform.lua

env.player does not track Calculation Mode. This fixes calcSkillDuration always passing
if env.mode_effective then
as false.
#2689 
This fix affects Blight, Penance Brand and Scorching Ray.

Fixes Maximum Stack logic to use "Effective DPS" mode and include debuffs

---

src/Modules/CalcPerform.lua
src/Modules/ModParser.lua

This implements the Redblade Banner's "Warcries have infinite power" mod
What i still don't like about this, is that the 
is shown as empty. But the calculations are happening correctly under the hood. Is it possible to populate this box when equipping the shield? The other problem is, that the warcry power box only shows in the configuration tab when a Warcry is added as a skill, so its invisible with only the shield equipped.

Warcries have infinite power

---

src/Classes/SkillsTab.lua

Same as #2779 but for seeing impact to FullDPS from alternate gem qualities on mouse hover.

Fixes FullDPS comparison for Alternate Gem Qualities

---

src/Modules/BuildList.lua

Added a Search Field just down principal buttons and a "Search" button and a "Clear" button.

Add search field below principal buttons

---

src/Classes/TreeTab.lua

Fixes error when powerReportList is not initialized but TreeTab:Draw() is called and screen width requires multiple lines

Fixes error when powerReportList is not initialized

---

src/Modules/ModParser.lua

The "The Agnostic" keystone is calculated based on the maximum mana and not the unreserved mana.
Related Issue: #2548

Fix The Agnostic calculation

---

src/Classes/ItemsTab.lua

Before:
After:
Verified the displayed stat comparison is correct.

Fix fullDPS comparison of enabling/disabling flasks

---

src/Classes/SkillsTab.lua

Many times when using PoB I want to know if the Gemcutter's prism vendor recipe is worth doing. That is, I'd like to compare the 0 quality gem DPS to the 20 quality gem DPS. Currently, this can be accomplished by adding another gem with the same level and 20 quality, and using the "enabled" tooltip to compare the DPS:
However, this gets a little tedious when you want to compare every gem in a six link. 
This commit creates a simple tooltip for the quality field which allows people see the DPS difference at a glance. It uses the exact same statCompare tooltip that the "enabled" field uses, so it's a very small change.
I only saw #2687 after making my own version. But the main difference is that this change doesn't add new fields (only a tooltip), and only compares with 20 quality, rather …

20 Quality gem DPS tooltip comparison (aka. Is GCP vendor recipe worth doing?)

---

src/Data/Skills/other.lua
src/Export/Skills/other.txt
src/Modules/ModParser.lua

The version triggered by Unyielding Flame has lower cooldown (3 instead of 10) since version 3.3.0c

Add unique variant of Commandment of Inferno

---

src/Modules/CalcDefence.lua

The Pious Path node was granting energy shield recovery even though Agnostic sets the maximum energy shield to 0

Fix Interation between Agnostic and Pious Path

---

src/Classes/TreeTab.lua

Passive tree node tooltips: add space before custom mods

add space and newline before any custom mods

---

src/Data/SkillStatMap.lua
src/Data/Skills/act_dex.lua
src/Data/Skills/act_int.lua
src/Data/Skills/act_str.lua
src/Data/Skills/sup_dex.lua
src/Data/Skills/sup_int.lua
src/Export/Skills/act_dex.txt
src/Export/Skills/act_int.txt
src/Export/Skills/act_str.txt
src/Export/Skills/sup_dex.txt
src/Export/Skills/sup_int.txt
src/Modules/CalcOffence.lua

I decided to gather them together instead of spamming a dozen PRs.

Various gem fixes and improvements

---

src/Modules/ModParser.lua

Previously:
60% more Attack Speed while you are Unencumbered
14 to 20 Added Attack Physical Damage per 10 Dexterity while you are Unencumbered
Now:
40% more Attack Speed with Melee Skills while you are Unencumbered
Adds 14 to 20 Attack Physical Damage to Melee Skills per 10 Dexterity while you are Unencumbered
Fixes #2934

Fix Hollow Palm Technique

---

src/Classes/NotesTab.lua

I'm not a huge fan of how this looks right now, so I'm open to suggestions on how to display this better.  Another option would be a group of buttons that would change the color.  More user-friendly, but also a lot more work.

Add documentation for color codes to Notes tab

---

src/Modules/CalcPerform.lua

Was not rounding correctly to 2dp cause of a misplaced bracket in a previous PR that was merged

Fix Mana Reservation Rounding

---

src/Modules/Build.lua

The new level requirement guide had an off by one error beyond act 10 and strange level dips at the act thresholds

Fix level progress calculations

---

src/Classes/PassiveTree.lua

Did some investigation into these scenarios, found the download of the passive tree wasn't working.  Downloading this way leaves the ascendancies in the wrong locations, so could be worth incorporating that script here

Fix for downloading tree data if missing

---

src/Data/SkillStatMap.lua
src/Data/Skills/act_dex.lua
src/Data/Skills/act_str.lua
src/Data/StatDescriptions/skill_stat_descriptions.lua
src/Export/Skills/act_dex.txt
src/Export/Skills/act_str.txt
src/Modules/CalcOffence.lua
src/Modules/CalcSections.lua

Shield Crush
Explosive Concoction
Spectral Helix
Note: Explosive Concoction involved directly editing the src/Data/StatDescriptions/skill_stat_descriptions.lua because I couldn't figure out where to put changes in order for that to generate into that file during an export. You might want to put them in the right place before accepting the pull if that isn't future proof.
Credit me as tcid please.

Added more new gems

---

.github/ISSUE_TEMPLATE/bug_report.yaml

Markdown rendering mangles the build code.

Prevent build code from being interpreted as markdown

---

src/Classes/SkillsTab.lua

Default gem level can be 0 in builds saved before #2298 
Fixes #2908

Sanitize default gem properties when loading a build

---

src/Data/Skills/act_dex.lua
src/Export/Skills/act_dex.txt
src/Modules/CalcActiveSkill.lua

Currently Explosive Concotion allows for off hand weapons to be used as statsticks when the mainhand weapon is either empty or disabled
Currently PoB will give an error saying `Off Hand weapon is not usable with this skill` which doesn't allow for an accurate representation of actual DPS
This change allows for skills to get the canStatStick flag, which will check the main hand weapon condition first, and then reset the weapon2 flags allowing them to be used.

Fix Explosive Concoction not working with off hand weapons

---

src/Modules/CalcOffence.lua

I fixed this particular issue, but I'm wondering if we need to convert percentage costs into flat values (if we can) due to things like Sacrificial Zeal and -flat mana cost modifiers.

Fix Manabond not  being affected by reduced mana cost nodes

---

src/Data/Uniques/helmet.lua
src/Modules/ModParser.lua

https://www.pathofexile.com/trade/search/Expedition/PWq3z4mhL
Second bleed mod is somehow not parsing, although 'infliction' & 'per frenzy' are in the modparser. I copied the affix directly from trade, so i don't think its a typo.
Maybe someone knows what I'm doing wrong?

Add Usurper's Penance

---

src/Modules/CalcPerform.lua

Fix for issue https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/3057
With this it no longer sets maximum inspiration charges for the minions, it however still lowers the mana cost for the player to cast it like intended.
Non-minion skills still keep their default maximum inspiration charges as well.
(redo of https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/3059 as it was based of master, not dev)

Don't set max inspiration charges for minions

---

src/Modules/CalcPerform.lua
src/Modules/ConfigOptions.lua

Since Elusive is a decaying buff and you cannot always have it at full effect, this new config option allows you to set a lower elusive buff effect than the automatic maximum calculated buff effect.

Modify Elusive effect

---

src/Data/Rares.lua

This feature adds new base types from heist, ritual, and expedition league into the rare templates, since rare templates haven't been updated in awhile.
Also to help with the convenience of creating your rare items from the rare template section, added some affixes that stack with the implicit of the base type. 
Ex. Vermillion ring's template now has life and strength stat. Useful for the user to stack a specific stat or scaling with fewer clicks.
This also fixes some rare templates that weren't possible in-game such as the affixes of +5 staffs not being possible to get on a warstaves, and 2H weapons not using the 2H affix for elemental damage with attacks.

Add new base types to rare template, modify existing rare templates

---

src/Data/SkillStatMap.lua
src/Modules/CalcOffence.lua
src/Modules/ModParser.lua

This gets a bit wonky when allocating blood magic + Lifetap in that it double counts the base mana cost, but I can't cap it at 100% converted, either, because of petrified blood.  No one should be taking Lifetap + Blood Magic anyway, I'd assume, so I left it alone

Fix Lifetap not changing mana cost

---

src/Data/Skills/act_dex.lua
src/Data/Skills/act_int.lua
src/Data/Skills/act_str.lua
src/Data/Skills/sup_int.lua
src/Export/Skills/act_dex.txt
src/Export/Skills/act_int.txt
src/Export/Skills/act_str.txt
src/Export/Skills/sup_int.txt

Numbers given by Openarl
ImmolationSigil - Wintertide Brand: 20
BlackHole - Void Sphere: 38
Disintegrate - Crackling Lance: 10? I think?
FrostGlobe - Frost Shield: 22
CircleOfPower - Sigil of Power: 30
Firewall - Flame Wall: A little birdie tells me this is a stat on the skill
ViciousHexExplosion - Impending Doom: 20
DoomBlast - Hexblast: 29
Bloodreap - Reap: 25
VoltaxicBurst: 22
RageVortex: 18
Absolution: 25? Not 100% sure
ForbiddenRite: 8
Manabond: 18 (circle) 23 (rectangle)
BladeTrap: 16
StormRain: 10 (explosion) 12 (beam)
ShieldCrush: 29
Boneshatter: 14
ExplosiveConcoction: 18

Add radius numbers for a number of skills

---

src/Modules/CalcSetup.lua
src/Modules/CalcTools.lua

Normally there is an active skill gem in a socket group which creates a skill and `calcLib.validateGemLevel` is called on it and all supports. If there is no active gem, the calculation is not run. This resulted in no validation taking place.
Fixes #2921 
I also switched the logic to prefer the highest available level up to the requested one over the default level. For example, if you manage to get a lvl 42 active skill it'll be clamped to 40, where before it would get set to 20.
The validation logic seems very pessimistic but at least it should be correct for non-sequential tables.

Fix gem levels not being properly limited

---

src/Modules/CalcPerform.lua
src/Modules/ModParser.lua

From: https://discord.com/channels/645607528297922560/680796887259021342/875478517486321694 and https://discord.com/channels/645607528297922560/680796887259021342/871321272167067688
Sample build to test with:
```text
eNrFW91z2kgSfw5_hYqqeyNGo29RZLcwxjYb2-HASe6eUmNpAK0HiUgjbGdr__frGQkQBOxGuavLgyKJX3_39HQPuPv784JrK5ZmURJ_aJIzvamxOEjCKJ59aH6-v3zvNX__rdEdUTH_ND3PIy4_-a3xrqvuNc5WjANdUxM0nTHxZc3J_AacljQWc5bEt_TPJL1Kwg_NuyRmTe2BxmEk1k8Bp1l2RxfsQ3MSAHFTo1nA4rC_fV8AFzSKJ0nwyMRVmuRLJXYVsafbJATM8Hb0aXxfERrFVaGg87vuiNMXlk4EFVoGlw_NHphOZ-w6EsCK8hz4EI9YZy4hht1sv0p0QRdwPYFusmQs3OLPLMOzXVJe__9Eo5QNplMWiGjF-mkk-nMaB1v7jpp1KvY25yJa8oilFQ2PUlz_xJzo-jHwfSIovxhNNljD9o0zy7Kcwvb_DV2yTZ6jmn2NxPycQ1RqSJG0w1kcCVaTeJREWRL_gn1V0qMm9pPFQxTXsnBN2lvNTiW9pTHtJ9k2BIZ5DHoTTdkO9KgpgwkON4YCgENKNUcshbomcARS2ZMIJiKt-O6oxux7FXi …
```

Fix exposure not applying from Corrosive Elements notable

---

src/Data/SkillStatMap.lua

The mod reads `100% more Damage with Hits at Maximum Charge Distance` , respect the hit flag.

Fix Shield Charge distance ramp not applying only to hits

---

src/Data/Uniques/Special/Generated.lua
src/Modules/Data.lua

Alternating Scepter has the implicit "Secrets of Suffering" which is currently not parsed. Add it to the list of keystones.

Fix Secrets of Suffering from Alternating Scepter

---

src/Data/Uniques/mace.lua

Fix "Bitterdream not updated to use Inspiration support instead of Reduced Mana support"

Fix "Bitterdream not updated to use Inspiration support instead of Reduced Mana support"

---

src/Modules/BuildList.lua

Fixes #3616.
Build list crashing when a build file is missing the `Build` node
- Open folder containing a corrupted build file
https://pastebin.com/Y4r4zn4s
_Paste into a build folder_

Fix build list loading crash

---

src/Classes/Item.lua

- Small and medium curse cluster jewels have identical enchants (passives skills grant...) so ModParser reads the small clusterJewel and sets the data in a table and then overwrites this when it loops around to the medium cluster jewel because the key is the same.
- Because of this the small cluster jewel has clusterJewelSkill of "affliction_curse_effect" when it should have "affliction_curse_effect_small" so when we validate cluster jewels, small curses are thrown out because "affliction_curse_effect" is not a valid skill for small and as far as I'm aware we cannot change the skills in ClusterJewels.lua to change/add the skill.
- line 3608 of ModParser is where we are creating the list of skills for cluster jewels, but it seems much messier to throw logic into that rather than right …

Fix Small Curse Cluster Jewels rendering on the tree when socketed

---

src/Modules/CalcTools.lua

Fixes #3648.
`+1 to Level of Socketed Active Skill Gems` modifier not applying +1 level to gems with matching tags (active_skill)
- Create new build
- Add Body Armour with `+1 to Level of Socketed Active Skill Gems` mod on it
- Add `Wave of Conviction` to skills, socket it into Body Armour
- Confirm that the gem is getting a +1 to it's level from Body Armour
https://pastebin.com/nPixCag5

Add support for gem level modifiers of socketed active skill gems

---

src/Data/SkillStatMap.lua
src/Modules/CalcOffence.lua

Fixes #1266 .
The attack speed cap should not apply to channeled skills and should be multiplied by the number of repeats a skill has if the skill is using spell echo or multistrike

Fix attack/cast rate cap

---

src/Modules/CalcOffence.lua
src/Modules/ModParser.lua

Closes #3461
Should have been done as a per stat in the first place as it removes unneeded code in calc offence

Fix Spell Suppression mastery giving double Crit chance

---

src/Data/Skills/sup_str.lua
src/Export/Skills/sup_str.txt

The Multistrike gem was always looking for the melee flag to apply the attack speed multiplier to a skill. For skills such as Molten Strike, Lightning Strike, Wild Strike, Static Strike and Frost Blades that had skill parts that disabled the melee flag, this also disabled the attack speed bonus
Closes #964, #1949, #2695

Fix Multistrike not applying attack speed to certain skills

---

src/Modules/ConfigOptions.lua

The multiplier variable was different on the gem and the configs page so it wasn't working at all

Fix Voltaxic Burst's # of Casts currently waiting

---

.gitignore
src/Classes/DropDownControl.lua
src/Classes/TreeTab.lua

Fixes # .
I actively dislike the clipping of text in some areas.
This fix is for the Tree Spec names 
I hate this
- New variable droppedWidth defaults to control width in case the parent doesn't manage the dropped width
- checked that the text is is not clipped
- checked that there was no left over white on screen
- checked that mouse hover went all the way out to the new width
- checked that the tooltip moved out to the new width
- checked that the tree spec could be selected anywhere on the line, all the way out to the new width.
- checked that controls whose parent don't manage the dropped width, are unaffected (sort by name on Items Tab is a good example)
Solution chosen because the parent control manages the list, not the drop down control
N/A

Add Autowidth to dropdown control, dropped text only

---

spec/TestBuilds/3.13/Dual Savior.lua
spec/TestBuilds/3.13/Dual Wield Cospris CoC.lua
spec/TestBuilds/3.13/Generals Perforate Zerker.lua
spec/TestBuilds/3.13/Mirage Archer Toxic Rain.lua
spec/TestBuilds/3.13/OccVortex.lua
src/Modules/CalcDefence.lua
src/Modules/CalcSections.lua
src/Modules/ConfigOptions.lua
src/Modules/ModParser.lua

Implements support for 'X% chance to defend with Y% armour' and 'defend with Y% armour while not on low energy shield' masteries. Leaves old "20% chance to defend with 200% armour" intact although I updated the armour calc function to be better scalable.
- Set Config Tab "Armour calculation mode" to Average or Max (and verify Calcs Armour "MORE" output)
- Set Config Tab "Armour calculation mode" to Minimum (and verify Calcs Armour "MORE" output not included)
- Set Config Tab "Are you always on Low Energy Shield"
https://pastebin.com/FNAVbwC6

feat: support for two Armour Masteries

---

src/Modules/CalcDefence.lua

This fixes a bug introduced in #3295 where damage taken modifiers (such as "90% less Damage taken" and "90% reduced Damage taken") were applying to EHP twice instead of once, resulting in 99% less Damage taken.

Fix EHP double dipping on damage taken modifiers

---

src/Modules/Data.lua

My friend wanted an option to sort uniques by evasion.
- Sort by evasion or armour
- See high defensive uniques

add armour and evasion to unqiue sorting

---

src/Modules/ModParser.lua

- Parsing for this mastery creates a mod for "BleedDamage" which is not correct. Changed to "Damage" with KeywordFlag.Bleed
- Allocate mastery, check bleed DPS before and after checking enemy is poisoned
<pre>eNq9Wltz2sgSfg6_QkXVvmFAFwS47N3CGCeuMg4LTnzOU2osNTDxSEOkEZhs7X_fnpEAgbkMyp5DqhxJfH3v6ekecfXHW8CMOUQx5eF12azWywaEHvdpOLkuf3m6u2iV__i9dDUgYvp5fJNQJr_5vfThSl0bDObArsstJBMkmoD4umJlf8NnMxKKKfCwT77z6CP3r8uPPISy8UJCn4rVncdIHD-SAK7LtwkwGouyQWIPQr-7-SaFBoSGI-69gvgY8WSGGpeNOYVFn_uIue8PPg-fcmJpmBeLan-4GjCyhGgkiDBi_HNd7qD1ZAK3JMC_yI2wBFnZzapr23XLalltxzbLtf3EoxmAvyZC97X-n8hBBL3xGDxB59CNqOhOSehtbGhUm4co96DNqtuwj-H7CRN0xihEOZrGIYpP7wRY7UPYJy4Iux2M1tCWWbVaTdtq26bZaJr_Gzou1nT1Q8gbhrHIS3Ab9arltNuHmackO9lkNUxJ1moc9NczFdN30po2ethu2vW6MugY7f0kpAIKOEMSDziNefgLnjzPRV0evNCwkKkr0s58cq6ufRKSLo83UT8Yiwc6hi3kwfz …

Fix bleed damage against poisoned enemy mastery

---

src/Data/Uniques/helmet.lua

Fixes #3706 
The old Tornado skill has been rename to Twister
- Equip saqawals
https://pastebin.com/6tPFnYY6

update saqawals flock to 3.16

---

src/Data/Uniques/belt.lua
src/Modules/ModParser.lua

Fixes #3708 .
Darkness Enthroned has a new "Abyss" word added to the mod
- Saw red wording before the fix
- Verified the mod is now parsed again after the fix
- Checked for other mods that gave increased effect of normal jewels
https://pastebin.com/Zs5uTYg8

Update wording for Darkness Enthroned

---

src/Classes/Item.lua

Fixes #3713 .
Two-Toned boots had a special hack that got overridden when updating items for the base percentile values
- Paste the provided boots text into PoB custom items
- Verify the armour values match the resistance implicit
N/A

Fix Two-Toned boots getting the wrong base type

---

src/Classes/Item.lua

Fixes #3703 .
Base evasion percentile was rounding a couple times to add one more evasion
This item should stay at evasion rating 898, where it rounded up to 899 before
```
Cataclysm Guardian
Zodiac Leather
Evasion: 898
Unique ID: d837fa50e819dabad1b1d63f824a1b629d5686b2c0e533db5a269655df32d09c
Item Level: 72
Quality: 20
Sockets: G G-G-R-R-G
LevelReq: 65
Implicits: 2
{crafted}Quality does not increase Defences
{crafted}Grants +1 to Maximum Life per 2% Quality
+24% chance to Suppress Spell Damage
+19 to Evasion Rating
+139 to maximum Life
10% increased maximum Life
+22% to Fire Resistance
{crafted}Gain 9% of Maximum Life as Extra Maximum Energy Shield
```

Fix rounding on base percentiles

---

src/Modules/CalcPerform.lua

Fix Poet's Pen trigger name so it matches definition in other.lua
Trigger name's don't match and as a result PoB can't find a triggering skill to calculate fullDPS.
Fixes # .
-
-
-

Poet's Pen total dps calc not working.

---

src/Data/Uniques/body.lua

PoB currently lists Brass Dome's max resistance roll as being from 1% to 2%, when it is actually 1-5% in-game.

Fix new max res range for Brass Dome

---

src/Modules/Data.lua

Fixes: https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/3743
Magebane on Skin of the Lords doesn't properly allocate the Magebane keystone.
- Equip Skin of the Lords, Magebane variant
- Confirm Dexterity now applies to Spell Suppression instead of Evasion Rating
```
eNq9WltzGjkWfg6_QkXV7suWY2guviyeKbCxQ5WdMGDHO_uSEt0CNFZLHbUawmz1f9-j7gYJDLbozK5TZeNzk85F3zmS0_n1R8jQgsiYCn5VrX-sVRHhvggon11Vnx5vT86rv_5S6Qyxmn-Z9hLKNOeXyodO9hkxsiAM9KpIYTkj6uvaUuMbWIowV3Mi-AP-Q8g7EVxVPwtOqmiCeUDV-jef4Tj-jENyVR37oFxFOPYJD64NPRcMMeVj4b8QdSdFEmXLLihZPogAZAYPwy-jR2tRyu1FYc8fOkOGV0SOFVYohm9X1S64jmfkBofwHaxhlhAdhvPz1lm96WXfG9XT_crjiJDAUvL-f4JDSfrTKfEVXZBrSdX1HHPfOFA7pHes7EPCFI0YJdLaVeuQxqdXxi8uDsk-CoXZzXC8EfU-em3PhP1_oyfU-34_UzXvMUhEiVW07mDGqSIllYeCxoL_hH-26uHUinBCeSkP16rdxexY1QfM8bWIHVJwT6fETbI_dpMbw …
```

Fix casing of Magebane keystone in data

---

src/Data/SkillStatMap.lua

Fixes Level 5 (or higher) Awakened Elemental Focus that gives +1 level to elemental gems to only apply to elemental gems, it was applying to all gems.

fix: Awakened Elemental Focus +1 level

---

src/Modules/CalcOffence.lua

Fixes #3756.
Enemy Physical Damage Reduction was not capped and could result in over 100% mitigation leading to negative numbers in DPS later in the damage calculation.
Followed steps of #3756 to see problem and apply solution and check solution fixes problem.

fix: Enemy Physical Damage Reduction should be capped at 90%

---

src/Data/Skills/sup_str.lua
src/Export/Skills/sup_str.txt

Linking Rage Support to Ancestral Totems breaks their unique Buff Effect, this fixes that.
Note that this is still implemented as a buff which means unless you have some other method of gaining Rage the support gem won't do anything on its own for your Ancestral Totems. Divergent Rage Support could allow you to generate Rage while linked to an Ancestral Totem, but that functionality is not yet implemented. This would require Divergent quality to grant ``Condition:CanGainRage`` directly to the player.
- Load showcase build
- Check DPS of Ancestral Protector with/without Rage Support
- Check Aura and Buff Skills under Calcs
https://pastebin.com/zxCDqzCg

Fix Rage Support with Ancestral Totems

---

src/Modules/CalcPerform.lua

When using the elementalist node for "-x% to affected resistance" it would not stack with the added base exposure from the elemental mastery or tree notables "Exposure you inflict applies an extra x% to Resistance"
Instead it was ignoring it and just using the base exposure from the skill/exposure source

Fix Elementalist exposure node not working with exposure mastery

---

src/Modules/ModParser.lua

In 3.16 they changed the wording of the used flask charges mod on some flasks

Fix parsing for charges used mod on flasks

---

src/Modules/ModParser.lua

Enemies you Curse are Unnerved was not parsed when it should have been auto applied if you had a curse in your build

Add support for Master of Fear notable

---

src/Data/Uniques/jewel.lua
src/Modules/ModParser.lua

Survival Instincts and Survival Secrets were changed substantially between the initial preview and actual 3.16 patch notes. This commit adds all of the missing changes to the Survival Jewels.
Fixes #3795

Update Survival Jewels

---

src/Data/Skills/act_int.lua
src/Export/Skills/act_int.txt

Bone Offering default quality was missing from the statMap and did literally nothing (both for minions, and players with Mistress of Sacrifice).
- Check cast speed of minions (and player with Mistress of Sacrifice) with 20/20 Bone Offering active.
- Apply changes from this PR.
- Check cast speed of minions (and player with Mistress of Sacrifice) with 20/20 Bone Offering active.
https://pastebin.com/m5YRrgJk

Add missing Bone Offering quality effect

---

src/Classes/ImportTab.lua

This is a complementary improvement to PR #3813
Pressing the Return key in the import field (marked below) checks if the code is valid and emulates the import button click.
Also, the import field is automatically selected when the import popup fills it. 
This way we can just quickly paste build link into the popup, press Return to submit popup, press Return again to import build from the import field. Overall smoother keyboard experience.

Add QoL improvements for import tab

---

src/Data/Minions.lua
src/Export/Minions/Minions.txt

Current POB has SRS as 100% physical damage and no conversion. But 3.16 patch notes says 'Summoned Raging Spirits now convert all of their Damage to Fire Damage.'
1. Added summon raging spirit as skill by itself
2. Checked the dropdown box to see if conversion worked
https://pastebin.com/Y304YR0Z

Fix Summon Raging Spirit to 100% fire conversion

---

src/Modules/Build.lua

Fixes # 
Alternating Keying and Mousing
Too much mouse action to get to import
- Have PoB open at file list (not in a build)
- Copy a url from a website (https://pastebin.com/uuqgZPkp is the one i've been using)
- Alt-Tab back to PoB
- Ctrl-N
- Ctrl-I
- Ctrl-I
- Ctrl-V
- <enter> to close popup
Then, groan, we have to go back to the mouse to click 'Import'.
Nobody asked for it, but i'm liking it.
P

Ctrl I for import

---

src/Data/Uniques/body.lua

3.16 variant of Brass Dome had an incorrect stat. Presumably, it was using the statline from a teaser, rather than the actual release.
Launched PoB, equipped brass dome, verified that life went down but melee damage did not.
https://www.pathofexile.com/trade/search/Scourge/Ag0aIQ

Correct stat on Brass Dome

---

src/Modules/ModParser.lua

"Pure Talent Viridian Jewel" not working for Marauder. #3830
"Marauder: Melee Skills have 15% increased Area of Effect" is red when hovering over jewel
and no AoE is affected.
-    Check that Pure Talent's Marauder text is no longer Red.
Select the Marauder Tree
-    Check that Smite's AoE changes from 17 to 18 and back to 17 when Jewel is added and removed.
-    Check that Vitality's AoE doesn't change when Jewel is added and removed.
Select the Duelist tree.
-    Check that Vitality's and Smite's AoE don't change when Jewel is added and removed.
Checks should show Melee only skills are affected by Marauder only.
https://pastebin.com/JhS5TSTN

Add Special Case modifier for Pure Talent jewel and Marauder

---

src/Classes/ItemsTab.lua

Fixes #3812 .
QOL: Add hotkey to edit equipped item
- Open a build. Supplied build has an abyssal jewel.
- On the item tab, hover over an equipped item and type _**e**_ and the item will be opened for editing.
- Only triggers on 'e'. Ctrl-E appears to be the DropDownControl's reset command.
- Check that _**e**_ doesn't respond on any other control(s) on the tab.
- Works on any item that the item list will allow to be edited (leverages it's double click method)
- Won't work if item slot is 'None'.
https://pastebin.com/4NMG77XY
Is there a good way to notify people to the functionality ?

Add hotkey to edit equipped item

---

src/Classes/PassiveTreeView.lua

The `renderConnector` function was allocating memory for the `connectorColor` table and the nested `getState` function. Moving them to the upper scope reduces memory used per `PassiveTreeView:Draw` call from ~250kB to ~600B
- Measure allocated memory (using `collectgarbage("count")`) before and after the call to the drawing function

Refactor rendering of tree node connectors

---

src/Data/SkillStatMap.lua
src/Data/Skills/sup_dex.lua
src/Export/Skills/sup_dex.txt
src/Modules/CalcPerform.lua

Fixes #2618. 
Withering Step removes the Elusive Buff from other skills that grant it (e.g., Nightblade support) and hence only one skill-based Elusive Effect buff should be present when Withering Step is part of the build.
Added support for `display_removes_and_grants_elusive_when_used` SkillStatMap which created a global flag that is checked in CalcPerform to handle the calculation separately when present.

fix: Fix Elusive Buff effect from Skills with Withering Step

---

src/Classes/Item.lua

This item wasn't recognizing magic two-toned boots as a proper base
```Item Class: Boots
Rarity: Magic
Two-Toned Boots of the Brute
--------
Armour: 126
Energy Shield: 26
--------
Requirements:
Level: 70
Str: 62
Int: 62
--------
Sockets: B 
--------
Item Level: 73
--------
+9% to Fire and Lightning Resistances (implicit)
--------
+12 to Strength
```
- Created the above item in PoB

Fixed copying magic Two-Toned Boots from trade

---

src/Classes/ImportTab.lua

This moves the account history list functionality to "Start".
After walking a few dozen newbies through PoB-ing their character, this is the main point of confusion. Almost all of them see the "Passive Tree and Jewels", "Items and Skills", and "Done" buttons and click "Done" (without clicking the other 2). As far as I'm concerned, this button is a trap.
- Tried importing a character
- Made a new build and confirmed my account was in the account history

Relabel character import "Done" button to "Cancel" 

---

src/Classes/ImportTab.lua

Importing a character for the first time sets the main skill to the first one. This instead sets the main socket group to the one with the most gems (only when importing a character onto a build with no skills).
- Imported a character and confirmed a reasonable skill got chosen
- Imported from a code and confirmed the saved skill (which was not the largest socket group) was restored
It looks like there's a bug since the CoC triggering skill isn't set correctly, but, AFAICT, that's an existing issue on `dev` at 6a356a5f ( but not on 2.13.0; see #3900)

Add feature to guess the main socket group when importing a character

---

src/Data/Uniques/Special/race.lua
src/Data/Uniques/race.lua
src/Modules/Data.lua

Fixes missing race uniques, #3843.
QOL: for adding racing uniques
- open a build or a new one
- go to items
- choose 'Endless Races' from the league dropdown
Build from the reddit post
https://pastebin.com/33KXG5WE

Add starter race uniques

---

src/Modules/CalcPerform.lua
src/Modules/ModParser.lua

Even with flasks not activated with Mageblood they are considered.

Add support for Mageblood

---

src/Data/Global.lua
src/Data/Skills/act_int.lua
src/Export/Skills/act_int.txt
src/Modules/Build.lua
src/Modules/CalcOffence.lua
src/Modules/CalcSections.lua
src/Modules/Data.lua

This adds full support for brand attachment range to the calcs breakdown, skill sidebar, and node/item comparisons.
Previously none of this was calculated, and we simply displayed how much % increased Brand Attachment Range you had in the calcs breakdown (nothing else).
https://pastebin.com/bsnxhrzm

Add full support for brand attachment range

---

src/Modules/CalcPerform.lua

Fixes #3900 - see build and how to test error.
My code for determining cost-on trigger logic when the logic was a modifier on an item (e.g., `Socketed Gems are supported by Level 18 Cast on Critical Strike`) was incorrect as it defaulted to 0 which changes boolean math results in Lua.
- Load various trigger-based builds

Fix triggering skill not properly selected when trigger support came from an item

---

src/Modules/CalcOffence.lua

Fixes #3850.
Trap and Mine skills are flagged ``skill("showAverage", true)`` preventing them from displaying their actual DPS.
This hasn't been necessary for a long time (see #2177) and is making DPS calculations for trap and mine builds unnecessarily tedious &mdash; exceptionally so if you're dealing Poison Damage (see #3850).
Some cooldown traps should display their DPS instead of just Average Hit (Lightning Spire Trap and Seismic Trap have special DPS scaling with Trap Throwing Speed), but adding support for that should probably be a separate PR due to the increased complexity.
- Load example PoB.
- Check all trap and mine skills. Anything with a cooldown should display Average Hit only, and anything without one should display Combined DPS.
https://pastebin.com/DPR7Mrfd

Add ability to show DPS for non-cooldown traps and mines

---

src/Modules/CalcPerform.lua

Fixes #3734.
Players can get negative maximum Life modifiers on Scourged items. With enough of these items equipped PoB throws various different errors and fails to load the build. PoE handles this by enforcing a lower bound of 1 for player maximum Life, and this PR adds the same functionality to PoB.
https://pastebin.com/KqPukQKa

Fix bug where maximum Life could be negative

---

src/Modules/Build.lua

Fixes repeated XML `PlayerStat` values as well as values that don't meet evaluation conditions from being saved.
```
<PlayerStat stat="AverageDamage" value="84768.780421338"/>
<PlayerStat stat="Speed" value="1.6375"/>
<PlayerStat stat="Speed" value="1.6375"/>
<PlayerStat stat="Speed" value="1.6375"/>
```
```
<PlayerStat stat="AverageDamage" value="84768.780421338"/>
<PlayerStat stat="Speed" value="1.6375"/>
```

fix: remove duplicate and not pertinent values being saved in XML

---

src/Modules/CalcPerform.lua

Fixes #3211.
I checked a few of my own builds and didn't notice any inconsistencies with mana or life reservation values before and after this change, I'd appreciate additional testing on that front though.
Legacy builds with 100% reduced mana reservation end up reserving very small (but non-zero) values. I fixed this by just completely rewriting the ``reservedFlat`` and ``reservedPercent`` formulas to match current behaviour in PoE and fix this edge case. As a bonus the formula is also significantly less confusing to look at.
https://pastebin.com/qVpv8y1b

Fix incorrect reservation on some legacy builds

---

src/Data/Uniques/amulet.lua

Fixes (one part of) #3063.
Sidhebreath in ``\Data\Uniques\amulet.lua`` had no Implicit count, showing the implicit as an explicit mod instead.

Fix Sidhebreath missing implicit

---

src/Data/Uniques/amulet.lua

Blightwell:
``Now grants “50% slower start of Energy Shield Recharge during any Flask Effect” (previously 30%), and “150-200% increased Energy Shield Recharge Rate during any Flask Effect” (previously 400%)``
Solstice Vigil:
``Unique items that previously granted a specific skill 100% reduced reservation now cause that skill to have no reservation. This change applies to existing items``

Update Blightwell and Solstice Vigil to 3.16.0

---

src/Data/Uniques/sword.lua
src/Modules/ModParser.lua

Partially fixes #3063.
Fate of the Vaal and Story of the Vaal had several different modifiers that weren't parsed at all. They also had a modifier that GGG changed at some point to exclude alternate ailments, requiring an update to ``sword.lua``.

Add missing Fate/Story of the Vaal modifiers

---

src/Modules/CalcOffence.lua

Fixes #2886.
Equipping The Admiral disables generic Elemental Damage taken modifiers, and can use the wrong (specific) Element Damage taken modifier (e.g. Lightning instead of Fire in situations where The Admiral should pick Fire, but you're dealing Lightning damage).
https://pastebin.com/ePjVp82H

Fix elemental damage taken when using The Admiral

---

src/Classes/ImportTab.lua

Some people (@pHiney, @zao) didn't like the new label (introduced in #3898) because it implied it would undo the import
- Started importing a character and clicked close

Relabel character import "Cancel" button to "Close"

---

src/Classes/PassiveSpec.lua

There is an (apparently very rare) error that can occur when converting old passive trees to the current version where extreme amounts of garbage data exists in the EditedNode section of the XML, but the converted tree is completely empty, causing an error when PoB checks whether or not a (non-existent) node listed under EditedNodes is conquered. Checking if the node actually **exists** first fixes this error.
- Import the build referenced below.
- Convert the passive tree from 3.14 to 3.16.
- Attempt to save the build. Prior to the fix in this PR, the build will fail to save.
https://pastebin.com/pqX8Z44x

Fix converted passive tree save error

---

src/Classes/ImportTab.lua

Adds https://pobb.in to the automatic import list of pob.
* Example build: https://pobb.in/qO1_QpuQLeDd
* POB download URL: https://pobb.in/pob/qO1_QpuQLeDd
Note: IDs can contain `[a-zA-Z0-9_-]` (same character set as base64).
pastebin.com compatible post API is currently not implemented, but as far as I can tell there is no way to share to other pastebins currently anyways.
(Broken Font is a Linux issue)

Add pobb.in to website import list

---

src/Modules/ModParser.lua

Fixes #3170.
Soul of Solaris depends on the ``# of nearby Enemies`` config option but does not actually make said option visible on its own. This PR fixes that by checking **both** ``Multiplier:NearbyEnemies`` (which enables the config option) and ``Condition:OnlyOneNearbyEnemy``.

Fix Soul of Solaris not displaying "Nearby Enemies" config option

---

src/Classes/ItemListControl.lua
src/Classes/ItemsTab.lua
src/Classes/PassiveSpec.lua
src/Classes/PassiveSpecListControl.lua
src/Classes/TreeTab.lua

This fixes two different bugs involving jewel socket data saving/loading where certain information would erroneously persist across different skill trees.
Socket Bug &numero; 1:
- Load the example PoB provided.
- Switch from the passive tree "First" to the passive tree "Second" using the Passive Tree Manager.
- Save and reload the example PoB.
In 2.13.0, you'll see this (both bug &numero; 1 and bug &numero; 2 are visible here):
After my fix is applied, you should see an empty socket (as intended):
This bug is caused by some erroneous socket data saving logic in ``TreeTabClass:Save``.
Socket Bug &numero; 2:
- Load the example PoB provided.
- Switch from the passive tree "First" to the passive tree "Second" using the Passive Tree Manager.
- In 2.13.0 you'll see a cluster jewel socketed …

Add improvements to multiple passive tree jewel socket management

---

src/Classes/Item.lua
src/Data/Uniques/boots.lua

Fixes a typo that prevented internal modifier representation for Pure Talent from parsing correctly (web-based copy/paste worked).
Fixes logic to prevent internal modifier representation on items if the modifier cannot be parsed and no implicits exist (e.g., Inspired Learning).

Fix various item parsing bugs

---

src/Data/Skills/act_dex.lua
src/Export/Skills/act_dex.txt

Fixes #856.
Elemental Hit has two damaging components: the basic attack hit (a strike or projectile), and a secondary AoE hit.
PoB currently only provides calculations for the first part, and ignores the second part. Implementing this fully has.. admittedly limited usefulness, but people **have** requested it and I don't see any harm in accurately representing how the skill actually works in-game. For comparison we already have another skill implemented that does the exact same thing: Wild Strike.

Add separate calculations for Elemental Hit area component

---

src/Classes/GemSelectControl.lua
src/Modules/Common.lua

To find skills by using multiple skills tags
The solution keeps the previous ability to search for a skill name or a skill tag just using a simple search term
This adds the ability use a search term to find a skill name and add multiple skill tags. 
All tag search terms start with colon (:)
Use minus (-) to remove a tag.
All searches are case insensitive
EG: 
- to find all spells with fire in their name, use; `fire:spell `
- to find all fire spells, of any name, use;` :fire:spell `
- to find all fire spells, of any name, but no auras, use; `:fire:spell:-aura`
`int` can be used for intelligence
`dex` can be used for dexterity
`str` can be used for strength
Illogical searches can be used that will result in "No Matches"
EG: 
- `anger:-aura`
All tag terms are 'AND'd together. There is no …

Add ability to search skills using multiple tags

---

src/Data/Skills/other.lua
src/Export/Skills/other.txt

Fixes #3796.
``activeSkill.skillData["LifeReservedBase"]`` in ``skills["BloodSacramentUnique"] `` returns ``nil`` with 2x Essence Worm equipped. The correct value is ``math.huge``, as the in-game behavior with 2x Essence Worm equipped is all reservation values are set to ``2^32-1``:
https://pastebin.com/Rb3DwUyL

Fix infinite reservation error with Relic of the Pact

---

src/Modules/Build.lua
src/Modules/CalcSetup.lua

The bandit Kraityn's passives were updated from 3% Attack Dodge Chance to 10% Chance to Avoid Elemental Ailments in 3.16.
Wiki for reference: https://www.poewiki.net/wiki/Deal_with_the_Bandits#Version_history
This change updates Kraityn's passive to be in line with the latest patch.
- Ran PathOfBuilding locally with introduced change
- Verified that ignite, shock, chill, and freeze ailment avoidance had a line with value 10 / Bandit when Kraityn was selected.
- Verified that the bandit dropdown worked as intended and that the text fit in space available as much as possible.
https://pastebin.com/E1jvWMJt

Updated Kraityn's passive attributes based on 3.16

---

src/Data/Skills/act_dex.lua
src/Export/Skills/act_dex.txt
src/Launch.lua
src/Modules/CalcOffence.lua

Fixes the broken Charged Dash DPS Calculation by replacing it with calculations for each of the 3 phases of channelling, allowing the user to specify the number of stages for the release.
It also adds a "hitTimeMultiplier" similar to "hitTimeOverride" in CalcOffence, due to CD only hitting every other attack, which I thought could be useful for some other skills.
I'm brand new to the code base, and this is my first PR, so lmk if there's anything I should be doing differently.

Fix Charged Dash DPS

---

.github/release.yml
.github/workflows/release.yml

Release notes were often missing or the script broke in the process.  GitHub has introduced their own release note generation, so this PR switches to using that. https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
- Ran locally using `act`
- Tested scripts individually

Reworked release note script to use GitHub release note generation

---

src/Modules/Calcs.lua

In a MH 1-hand sword, OH Squire, with Frost Blades as Weapon 1 skill and new skill group tied to Weapon 2 and including both Weapon 1 and 2 to FullDPS I could get this error to pop up when looking at gem recommendation.
This fixes it.

fix: when doing gem recommendations this can cause a crash

---

src/Classes/CalcsTab.lua
src/Classes/TreeTab.lua

Fixes #3895
Fixes #3464 
Fixes #3599 
Fixes #3738 
The button to `Show Power Report` is enabled prior to Cluster Notables power initialization resulting in their `node.power` not existing. The first time a DPS assessment is completed subsequent re-runs or other DPS sorts do not affect it as the cluster notables are now initialized.
It was a race-condition problem.
- Tested builds that I could trigger error on before and after.
https://pastebin.com/Yv86ABaz

Fix: Power Report generating error pop-up

---

src/Classes/PassiveSpecListControl.lua

Fixes #3961.
When Managing Passive Trees (Copy, Rename, New, Delete). The title of the popups are sometimes incorrect.
- on Tree tab, choose "Manage Trees ..."
- Choose a Passive Tree and select Copy, Rename, New, and Delete and confirm the titles match the action 
- Changed "Delete Spec" to "Delete Tree" as Spec is an internal name.
-
The alternative was to set Copy, Rename, and New to "Set Name" for consistency.
N/A

Fix Passive Tree Management Titles

---

src/Modules/CalcDefence.lua
src/Modules/ModParser.lua

Fixes #3620
This adds support for Strength of Blood less damage taken based on max life leech rate.
https://pastebin.com/TxUzDmsC

Add support for Strength of Blood less damage taken

---

src/Data/Uniques/ring.lua

Fixed the implicit Chaos mod from 9-13% -> 17-23% for Blakcflame, Circle of Nostalgia, Death Rush, and Ming's Heart 
Fixes: #3973

Update Chaos Resistance roll on unique rings

---

src/Data/Uniques/bow.lua

The Crimson Storm now has 60-80% increased Physical Damage (previously 140-170%).
From the archnemesis TODO spreadsheet.
- Launched path of building in development mode and refreshed it
- Made sure that the values of each variant corresponds with the correct added phys damage percentage for Current and Pre 3.17.0
Selecting a variant shows both (Current) and (Pre 3.17.0) suffixes
An example of a suffix.

Update Crimson Storm changes

---

src/Data/Skills/act_dex.lua
src/Export/Skills/act_dex.txt

Fixes - none in particular, but I did find it noted here: https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/2887.
Divergent Blood Rage shows as being supported but doesn't actually apply life leech when dealing elemental damage.
- Added Blood Rage to a build that only does elemental damage
https://pastebin.com/z43F9vzW

Fixed divergent Blood Rage not applying life leech

---

src/Data/Uniques/Special/New.lua
src/Modules/CalcPerform.lua
src/Modules/ConfigOptions.lua
src/Modules/ModParser.lua

Added Configuration Option for `Covered in Frost`.
Auto re-use `Covered in Ash` and `Covered in Frost` modifiers with this ring if equipped in correct slot.

feat: added Polaric Devastation ring and mod support

---

src/Modules/ModParser.lua

Fixes #3673 
Fleshcrafter unique has several minion related modifiers. This adds support for ignoring enemy resistances and not bypassing ES.
The conversion mod is not easily supportable. The current calculation order is: conversion > reservation > defence(resists) while it needs to know the resists before conversion.
- Equip Fleshcrafter and a minion spell
- Check minion stats
https://pastebin.com/9HDdd0Bc

Add partial support for Fleshcrafter

---

src/Classes/ImportTab.lua

Fixes #3870.
Whitespaces were not being removed from the character name on the import tab
- Open a new build
- Select import
- paste in " xyllywyt "
- Select Start
- Note characters are listed
- Select Done
- Note the spaces that were there (in character name) are gone.
N/A
I have not tested special character names cause i don't know one

Remove trailing and leading spaces from the import character name

---

src/Modules/ModParser.lua

Fixes #3903
Transcendant flesh rounds crit multiplier down in-game, where PoB rounds to the nearest integer
- Only tested Transcendant Flesh on the provided pastebin, no other jewels (pending confirmation that rounding works the same for all)
`https://pastebin.com/000Lyg18`

Transcendent Flesh rounding not matching in game

---

src/Modules/CalcOffence.lua
src/Modules/ModParser.lua

Adds support for:
`40% more Attack Damage if Accuracy Rating is higher than Maximum Life`
Implementation:
I had to separate the check into MainHand and OffHand as different Accuracy Ratings can exist between the two.
Tested:
Test Build:
`https://pastebin.com/9En0skth`
Just Use different Weapon and Shield combos in the build.
Stat is added manually to the `Le Heup` ring.

feat: Add support for new Precision Technique Keystone

---

src/Modules/CalcPerform.lua
src/Modules/Data.lua

Fixes #2808.
Curse on Hit from corruption implicits are always applied after Curse On Hit Support gems, and trigger mark when you hit mods on rings. Curses from rings appear to override curses from gloves. The earliest alphabetically-named curse has highest priority, up to the curse limit. Curses are applied in alphabetical order according to their internal name. Despair's internal name is Vulnerability and Vulnerability's internal name is NewVulnerability.
TL;DR:
- If you have Curse on Hit gloves: the curse from your gloves should always override Hextouch + Elemental Weakness.
- If you have a Frostbite on Hit ring, a Vulnerability on Hit ring, and Elemental Weakness on Hit gloves: Frostbite should override Vulnerability, and Vulnerability should override Elemental Weakness.
- If you have …

Fix incorrect curse priority

---

.github/workflows/beta.yml

The beta branch would consistently run into issues with a git piece or a release notes piece failing.  This PR does away with the release notes portion and just makes a straight copy of dev each week, force-pushing it onto the beta branch
- Running it on my fork: https://github.com/Wires77/PathOfBuilding/commit/b77d5dd6c5e4c2ab10230896a1932d2859cd63b2 https://github.com/Wires77/PathOfBuilding/actions/runs/1764102168

Beta branch auto-update fix

---

src/Classes/ModStore.lua
src/Modules/CalcDefence.lua
src/Modules/CalcOffence.lua
src/Modules/CalcPerform.lua
src/Modules/ModParser.lua

Mods that use the "MAX" of any value weren't always getting the right value and used defaults with the wrong assumption of how the function worked.  This also fixes Battlemage not working
- Checked battlemage
- Checked The Scourge
- Checked Elusive, with and without increased effect
https://pastebin.com/7ytUa8Sa

Max mods not using proper default

---

src/Modules/CalcSections.lua

Nodes that gave `+ to Armour and Evasion` were not listed in the breakdown list
Mainly seen on Vanguard belts and Champions Unstoppable Hero node

Fix breakdown for Armour and Evasion sources

---

src/Data/Skills/other.lua
src/Modules/CalcPerform.lua

This PR does two things:
1. Updates Damage Range &  Added Damage Effectiveness (it's 1.0 if not specified by default) of Icestorm skill from Whispering Ice to GGG Patch Notes
2. Fixes trigger conditions for CoC, CoMK and CwC with actives on item versus via gem reguiring same socket group versus same slot name.
PasteBin:
Whispering Ice: https://pastebin.com/tewrkNEj (fails to detect trigger in dev, works with PR)

fix: Whispering Ice & Trigger Conditions

---

src/Modules/ConfigOptions.lua
src/Modules/ModParser.lua

This mastery was not updated to use the use the `ArmourDefence` and `MAX` node parsing. So it was modifying the flat armour value on a character which is not how it works in game.
Also added the condition check for `LowEnergyShield` and `FullLife` to only appear when needed
Build Code:
https://pastebin.com/QF2sbh7y

Fix 'defend with % armour' mastery to not effect total armour value

---

src/Classes/CheckBoxControl.lua
src/Classes/ImportTab.lua
src/Classes/SkillsTab.lua

When importing a character, default the 3 delete checkboxes to checked.
Just an inconvenience since you generally are not importing characters onto builds with existing content.
- Imported a character twice
- Checked the skills tab "Sort gems by DPS" was still checked and adding a new support gem offered reasonable options

Delete jewels, skills, and equipment by default

---

src/Data/Skills/act_dex.lua
src/Export/Skills/act_dex.txt

Fixes #2434.
Explosive Arrow gains: ``+2 to Explosion Radius per Explosive Arrow on Target, up to +12`` -- we had the +2 Explosion Radius per Fuse but *did not have any cap* meaning at 20 fuses you gained +40 radius instead of the expected +12 radius.

Cap Explosive Arrow Bonus Explosion Radius

---

src/Data/Skills/act_dex.lua
src/Export/Skills/act_dex.txt

Fixes # .
- Open PoB
- Select Vaal Blade Vortex as a gem
- Check the amount of hits/sec in the DPS calculator
N/A

Fix Vaal BV hit rate override being too high

---

src/Classes/ItemsTab.lua
src/Classes/SkillsTab.lua
src/Data/Global.lua
src/Modules/Calcs.lua

I noticed a problem with a lot of stat compares with FullDPS stuff. Old system just checked if the baseline had `.FullDPS` value to determine it should use it. But if you added skill to FullDPS and then removed them the baseline would still have the parameter. 
This is a safer way to do it.

fix: redo how useFullDPS is calculated

---

src/Classes/ItemListControl.lua

Fixes #3845.
To clean up POBs, delete all unused items.
- Open any build or start a new one
- Add some items so they are marked unused
- Select 'Delete Unused' button
- Confirm all unused are deleted but no wanted items are deleted.
- Press Ctrl-Z to bring back deleted items one by one if you need (easy way to confirm the previous point)
Any build

Add 'Delete Unused' button on the items tab

---

src/Data/Skills/act_dex.lua
src/Data/Skills/act_int.lua
src/Data/Skills/other.lua
src/Export/Skills/act_dex.txt
src/Export/Skills/act_int.txt
src/Export/Skills/other.txt
src/Modules/Build.lua
src/Modules/CalcDefence.lua
src/Modules/CalcPerform.lua

Re-Add Stages option to:
- Winter Orb
- Incinerate
- Blight
- Penance Brand
- Charged Dash
Updates the default stage to always be `1` which can be over-written with `stagesMin = X`

Fix: SkillPart Stage DropDown

---

src/Classes/ItemsTab.lua
src/Modules/ModParser.lua

This adds support for generic/life/mana/utility flask charge generation
(such as Pathfinder, flask charge generation nodes in ranger area and
masteries) and also Traitor keystone.
It also adds support for uptime what accounts for duration breakpoints
so it is accurate.
Example POB:
https://pastebin.com/2DdA2JZt

Add support for flask charge generation and uptime

---

src/Modules/Build.lua

Adds breakdown of the skills in FullDPS selection into the Build XML Save file. This is primarily intended for consumption by third-party tools like PoE.Ninja and pobb.

feat: Put FullDPS breakdown into XML Build Save file

---

src/Classes/ItemListControl.lua
src/Classes/ItemsTab.lua

This PR optimizes bulk item deletion with``ItemsTabClass:DeleteItem(...)`` by avoiding unnecessary cluster jewel graph rebuilds. It also adds a feature that more comprehensively addresses the same goal, allowing certain function calls to be deferred until after the calling loop is completed.
This is meant to address certain performance concerns raised while reviewing #3949.
Demo/Test Build: https://pastebin.com/imuaU4Lh
Before: Clicking ``Delete Unused`` freezes PoB for over 20 seconds and leaks ~900MB memory.
After: Clicking ``Delete Unused`` processes in a few hundred milliseconds and leaks ~30MB of memory.

Improve bulk item deletion performance

---

src/Modules/CalcDefence.lua
src/Modules/CalcOffence.lua

Fixes several cases of physical damage reduction calculations not being capped for max or min.
Physical damage reduction should be capped at 90% and have a minimum of 0%, in some calculations it wasn't being capped leading to inaccuracies
Updated:
-Ailment
-Damage over time
-Impale
-Player
-Verified damage calculations for new min and max on updated formulae
```
eNrVWltz2kgWfg6_oouq2Upqy4AEOB4vnimMsUOVcRhwkt2nVFtqoMctNZFaOGQq_31PdwsQDpijnjzsZqoyQnznfvpcmnR-_xoJsmRJymV8UfVqjSphcSBDHs8uqh_ur0_Oqr__VumMqJq_n15mXOhvfqu86phnItiSiYvqr0CmaDJj6uOaVfMzvFvQWM2ZjIf0T5ncyPCieidjViUPNA65Wn8KBE3TOxqxi-okAOIqoWnA4rC3fW-BEeXxRAaPTN0kMltcVP0qWXL2NJQhYAbD0fvxfUEoj4tCQelXnZGgK5ZMFFUkhb8uql2wnc7YO66AFRUZ8GlU6_uxkwVj4XHYKGH96ZQFii9ZL-GqN6dxwI7TlcUOM6H4QnCWbPBerX2I4l4qKq5Gk-O8LVJuHdJq-K1a6xD8E1dzQBdZHye4FOBKlDY …
```

Fix missing physical damage reduction caps

---

src/Data/Uniques/belt.lua

Fixes #4046 
URL: https://www.pathofexile.com/trade/search/Standard/85dmBM2cV

Fix: correct two modifiers on Survivor's Guilt (unique belt)

---

src/Modules/CalcOffence.lua

Swapping the columns in the table makes it more intuitive to read. The new order is read as "X ailment threshold results in Y shock".

Swap ailment threshold and effect in breakdown

---

src/Modules/ModParser.lua

Fixes #4058.
GGG changed how some critical strike multiplier spell nodes were written on the 3.17 tree. I'm not sure whether or not they were attempting to exclude Poison Damage applied by Spells with this change. It's not immediately obvious anyway, and all of the 3.16 nodes affected by this change **did** apply to Poison Damage.. so pending further testing I'm leaving it as-is.

Parse new "for spell damage" mod

---

src/Classes/ImportTab.lua
src/Modules/Main.lua

PoB currently does not remember the last selected export website.
Stores the last website in the settings.xml:

Add feature to remember last used export site in settings

---

src/Classes/ItemListControl.lua

Fixes #4045.
This fixes a bug where the "Delete Unused" button in the items tab would delete Abyss Jewels socketed in equipment slots, as they were never being checked due to flawed logic. It also optimizes FindSocketedJewel behavior in a few different locations, making the Delete Unused button more responsive.
- Test deleting unused items and monitor speed + accuracy (what was deleted)
- Test deleting several different items, one at a time
- Test deleting all items
https://pastebin.com/ng1CBVN1

Fix unused Abyss Jewel deletion

---

manifest.xml
src/Classes/ImportTab.lua
src/Modules/BuildSiteTools.lua
src/Modules/Main.lua

When passing a pastebin build via the command line, PoB will automatically load the build.  This PR adds support for other websites as well, and organizes the code a bit to be able to reuse the same code in the ImportTab
- Shared a build to pastebin/pobbin
- Tested importing that same build via the ImportTab
- Tested making a shortcut to the executable using `pob:/pastebin/zwZMM8sf` or that same build code generated above as a parameter

Allow import on startup for sites other than pastebin

---

src/Export/spec.lua

Duplicated column name in BuffDefinitions caused flask export to fail

Fix flask export

---

src/Modules/CalcOffence.lua

Fixes #4092, #4113
Recent change to general's cry made all active skills calculate as if they were not channeled.  This fixes this by using the correct 'Channel' skill type.

Fix issue where General's Cry would set attack rate to 1 for certain skills

---

src/Classes/ImportTab.lua
src/Classes/Item.lua
src/Data/Uniques/Special/Generated.lua
src/Modules/ModParser.lua

Fixes #4117:
Provides Support for:
- Copy/Paste of Forbidden Flame/Flesh from PoE Trade `https://www.pathofexile.com/trade/search/Archnemesis/rjD3VPESQ`
- Parsing of Character Import with from PoE with Forbidden Flame/Flesh item requirements block
- Updated PoE changes to the item (they changed from it being a `Prismatic Jewel` to `Cobalt` for Flesh and `Crimson` for Flame, they changed the modifier string very very slightly
To Test:
Use PoE.Ninja to find a character that has Forbidden Flame or Flesh and import.

Fix issue importing Fobidden Flame/Flesh

---

src/Modules/CalcSetup.lua

Fixes #4093 
As described in the issue, with a sword equipped and Energy Blade gem skilled if you go to Config Tab and checkmark "Is Energy Blade active?" you would get a Lua error. This was a result of two different PRs working off each other where one changes the item form to include class restrictions, the other not accounting for new form when spoofing an item to support Energy Blade.
`https://pastebin.com/PmcZ9BMk`

Fix Energy Blade incompatibility with new Fobidden Prismatic Jewels

---

src/Modules/CalcOffence.lua
src/Modules/ModParser.lua

For things like Rolling Flames, Galesight, Flamesight, and Thundersight, as well as for mods on Touch of Anguish and Painseeker, ailments would have a lower chance than their base chance
- Verified ailment chances stayed the same for existing standard setups
- Ensured crit chances stayed equal to non-crit chances in all cases (until GGG introduces "ailments can't be inflicted with crits")
```bash
eNrdW1tz2kgWfg6_oouqrcpUAOsOuOyZAowddu2EASezOy-pttSAxi01kVq2yVb--57uFiAwl0bJ7sNOphxdzr2_PpeWc_HbS0TRE0nSkMWXVbNhVBGJfRaE8fSy-un-ut6q_vZr5WKI-ezjpJuFVLz5tfLmQl4jSp4IBb4q4jiZEv55Kcn-ApLmOOYzwuI7_BdLblhwWf3AYlJFDzgOQr688ylO0w84IpfVP0Luz6oIpz6Jg976eZ-SiMQc0zDlVRThMB4z_5Hwm4Rlc6n-KSTPdywA2sHd8OPovqA8jIvKwfY3F0OKFyQZc8xRCj8uqx0IAZ6SKxzBT5CGaQaiPK_VsMxWy2saVsu2q2e7mcdzQoIVk9nw9hEOE9KfTIjPwyfSS0Lem-HYX6tr …
```

Fix an issue where chance to inflict an ailment on a critical strike could be lower than on a non-crit for alternate ailments

---

src/Modules/ModParser.lua

Adds parsing for `with Physical Skills` and `Minions have x% increased Attack and Cast Speed while you are affected by a Herald`
Fixes #4122

Add support for 2 new cluster jewel mods

---

.github/release.yml
.github/workflows/beta.yml
.github/workflows/release.yml

This also builds in the regex used to massage the release notes into the format our users are used to.  I've also added the extra labeling we want to use to differentiate different types of issues

Add support for using existing release notes link to work off of

---

src/Modules/ConfigOptions.lua

Delirium scales mob `Damage taken` and mob `Damage dealt` by certain values discovered in this post
https://www.reddit.com/r/pathofexile/comments/pkgeg8/delirium_scaling/
Changed it to be `Less player damage` as that is effectively the same as `Less damage taken` I believe. I could be wrong here

Add Delirium effect scaling

---

src/Data/Skills/act_int.lua
src/Data/Skills/act_str.lua
src/Export/Skills/act_int.txt
src/Export/Skills/act_str.txt

The configuration for Kinetic Bolt was setting the value of the spell damage/cast speed scaling mods as increases, rather than max values as they're read in CalcOffence. This lead to them being always treated at 100% scaling rather than the correct 200% for spell damage and 2.5%*quality for cast speed.
- Add a no-implicit wand with Hits Can't be Evaded (to ignore Accuracy), 100% of Physical Damage Converted to Lightning (to ignore Armour)
- Add Anomalous Kinetic Bolt
- Add custom modifier "100% increased Spell Damage"
- Confirm DPS triples instead of doubles and shows as 200% increased on calc sheet
- Add custom modifier "100% increased Cast Speed"
- Confirm attack speed increases with quality at correct rate
- Verify other similar "applies to" mods are correctly overridden (Crown of …

Fix Kinetic Bolt and Earthquake not fully scaling with Spell Damage/Cast Speed

---

src/Data/Skills/act_dex.lua
src/Export/Skills/act_dex.txt
src/Modules/ConfigOptions.lua

Fixes #4158 .
"CanEnsnare" wasn't a global buff so it wasn't applying as a secondary skill.  Changed this to an "ifSkill" check instead.  Was trying to use "ifEnemyMult", but it wasn't working.

Fix ensnare stacks not showing for Ensnaring Arrow

---

src/Modules/CalcOffence.lua

Fixes #4123 
The wording "damage with bows" only applies to hits, not DoT. This fixes that.
- Checked build before and after change. Before change, ignite DPS changes. After, it does not. Other DPS is adjusted appropriately.

Bow Proj Speed as damage only applies to hits

---

src/Data/Uniques/ring.lua

LINK: https://poedb.tw/us/Mark_of_the_Elder
This modifier: `(60-80)% increased Attack Damage if your other Ring is a Shaper Item` should be scalable by `Abrasive Catalyst (attack)`

Fix missing catalyst on 'Mark of the Elder' ring

---

src/Modules/CalcDefence.lua

Corrected spelling of Effective Hit Pool Description "Total incomming damage" > "Total incoming damage".
Fixes # .
Spelling of the word 'incoming' was incorrect.
I fixed it by removing one of the extra 'm's.
I guess any build as this section is expanded by default? But here's mine:
[https://pobb.in/qbvAT81qUrA7](https://pobb.in/qbvAT81qUrA7)
I..uhmm wait how am I meant to get an after screenshot? It's not fixed yet? Time travel's not real!

Corrected spelling of Effective Hit Pool Description

---

src/Classes/ImportTab.lua

Fixes #4166 .
Tencent added authentication to their character pages, so characters can't be imported without logging in.  This PR adds logic to show the session ID box when this occurs, as @cofedream in the linked issue says using a session ID works to get through.
I couldn't actually test this myself as I don't have a Tencent account, but the fix seems to work for those who need it and is pretty innocuous.

Display session ID box when 401 is encountered on Import

---

src/Data/Skills/act_int.lua
src/Export/Skills/act_int.txt

Flame Surge had a duration component (Burning Ground) added in 3.16, but the related duration flag was never added.

Add missing duration flag to Flame Surge

---

src/Modules/Main.lua

Fixes #4202.
Build names should appear in the window title first as listing them after the app name makes differentiating multiple PoB instances somewhat tedious and has no benefit.
Displaying build names in the window title is already configurable so anyone that (for whatever reason) wants the window title to always display "Path of Building" first can simply turn the "build name in window title" option off.

Swap subtext and appname positions in window title

---

src/Classes/PassiveTreeView.lua

Fixes #4201.
Comparing a 3.17 passive tree to a 3.12 passive tree and hovering over certain skill nodes causes nil errors to occur, as the nodes being compared don't necessarily *exist* in both trees. The fix for this is fairly simple: check if the node actually exists before checking if the node is allocated.
See linked issue.
No error occurs.

Fix nil error when comparing passive tree skill nodes

---

src/Data/SkillStatMap.lua

Fixes #4222.
3.17 changed trap support from giving increased damage to giving less damage. As part of this, the stat changed name. This did not however remove the old stat from other gems, notably in their quality.
This adds the stat back in, and fixes the less damage mod to actually be less damage, not reduced.
- Created a build with a fireball trap before and after change.
- Verified damage goes down.
- Added cluster traps, verified that damage goes up with quality.

Add increased trap damage back as a stat

---

src/Modules/CalcPerform.lua

Fixes #4165 (comment within) .
Battlemage's Cry had the spell damage conversion commented out and wasn't applying.  Didn't see problems with it, so this PR simply uncomments it and converts to using the same 'MAX' calculation as other spell damage conversions.
- Tested with Phantasmal Earthquake to ensure only the highest one applies
```bash
eNrVWm1z2rgW_tz8Cg0ze-fuDAG_YF6yZHcIIQm7oWUhabefOsIWoI1ssbYcSnf63_dINmBSIELdmTu3H1pjP-f96Jwjqe1fPocMPZM4oTy6LNkVq4RI5POARrPL0uPDzXmz9MvPZ-0hFvN306uUMvnl57M3bfWMGHkmDOhKSOB4RsT7NSf3E3Ba4EjMCY8G-E8e3_LgsvSWR6SEJjgKqFj_8hlOkrc4JJelsQ_EJYQTn0RBd_s-A4aYRmPuPxFxG_N0cVlySuiZkuWAB4DpD4bvRg8FoTQqCgWd37SHDK9IPBZYoAT-uix1wHQ8I9c4hL-BG2YpsHLcSq3eajoNr1l3rEapup94vCAk2BC5lfoh4DAmvemU-II-k25MRXeOI38rzjpEdyp2kDJBF4ySeIO3K94hirtvmLdah7APXGB2PRxvoM1apday3UbLtS235h2n4-J1 …
```

fix: battlemage's cry spell damage to attacks not applying

---

src/Modules/ModParser.lua

Also fixes a different mod that was also incorrectly applying to cast speed too
Fixes #4263

Fix Challenger Charges affecting Cast Speed

---

src/Modules/ModParser.lua

Fixes #4254. There are a few other modifiers in ``ModParser.lua`` that *might* benefit from the same change, but I'm not familiar with them and don't know if it's actually necessary to apply a global limit.

Apply global limit to Expansive Might notable

---

src/Data/Skills/minion.lua
src/Export/Skills/minion.txt

Fixes https://www.reddit.com/r/PathOfExileBuilds/comments/t42sth/all_dancing_duo_pobs_out_there_may_be/
Removed the old dps multiplier from dancing dervish cyclone
-
-
-

Fix Dancing Duo Cyclone dealing twice as much damage as it should be

---

src/Classes/ConfigTab.lua

Default configuration options were erroneously being saved to build XML data. This fixes that by forcing ``ConfigTabClass:GetDefaultState()`` to return more sensible results instead of ``nil`` whenever it either can't find the requested configuration option or there isn't any ``defaultState`` set.
See also: https://discord.com/channels/676181894152454150/676187672355799062/944201516355567627

Prevent saving default settings to XML

---

src/Data/Skills/sup_int.lua
src/Export/Skills/sup_int.txt

Despite the internal name of the stat, blastchain mine's less damage applies to all damage on supported skill, not just mine damage. This fixes blastchain mine not properly reducing damage on trap skills it supports.
- Checked damage of Fireball + Blastchain Mine and Explosive Trap + Blastchain Mine before and after change.
https://pobb.in/3EvK8Krq_V1r

Fix blastchain mine not applying less damage to all gems

---

src/Classes/ConfigTab.lua

Fixes #4179 .
On lower widths, the "Enemy Stats" section on the Config tab wouldn't move and would thus be unusable.
- Resized app, saw sections moved appropriately
N/A

Move columns vertically when screen width is too low

---

src/Data/SkillStatMap.lua
src/Data/Skills/sup_str.lua
src/Export/Skills/sup_str.txt
src/Modules/CalcOffence.lua
src/Modules/CalcPerform.lua
src/Modules/CalcSections.lua

This adds support for ReservationBecomesCost skill modifier what makes
Divine Blessing and Spell Totem mana cost work correctly.
Fixes #4078 
Example pob:
https://pastebin.com/mSyAeaki
Verification in game:

Add support for ReservationBecomesCost modifier (Divine Blessing/Totems)

---

src/Data/Uniques/jewel.lua
src/Modules/Data.lua
src/Modules/ModParser.lua

According to my dialog with OpenArl we should have been using the PassiveJewelRadii.DAT values for jewel rings. This PR correct the values to those using the data.jewelRadii approach (in order to preserve backward compatibility) and adds support for the new ring size `Massive` which is to be 2000 to 2400 (although can change prior to 3.18 release)

Feat: Add support for Massive Radius

---

src/Modules/CalcSections.lua

Fixes #3944
Ward does not regen at all, and even if it did it wouldn't use ES Regen.
- Allocate Zealot's Oath with any life regen, verify that ES regen doesn't show up under ward

Remove ward regen from breakdown

---

src/Classes/ImportTab.lua

Fixes #4295 .
Cannot import an energy blade
- Open https://www.pathofexile.com/account/view-profile/Celavie/characters
- Import Swosh_swosh (std League)  --- (OP may have put his sword back in the character named in the issue)
- 
as shown in issue
The Problem is with the data coming in (Code 1), comparing it against the weapon data (Code 2). The only valid entry is the first one. All others must fail. Can it be guaranteed that the weapon type is the first entry ? Probably not. So i just just added a validity check.
Code 1
```lua
{
displayMode = 0,
name = "Two Handed Sword",
values = {}
}, {
displayMode = 0,
name = "Elemental Damage",
type = 10,
values = { { "102-2042", 6 } }
}, {
displayMode = 0,
name = "Critical Strike Chance",
type = 12,
values = { { "7.00%", 0 } }
}, {
displayMode = 0, …
```

Fix Energy Blade Import

---

src/Modules/CalcOffence.lua
src/Modules/CalcSections.lua

Decay hasn't been updated since pre-3.0.0. It has the wrong base duration (10 seconds instead of 8 seconds), and scales with skill duration in PoB when the duration only scales with debuff expiry rate modifiers (such as Temporal Chains) in-game.
See also: https://old.reddit.com/r/pathofexile/comments/u33tmx/decay_not_lasting_as_long_as_pob_says_it_should/
https://pobb.in/68HafczBnlPu

Fix Decay breakdown

---

src/Classes/PassiveTree.lua

Allows for ` ` (space) to exist in the name of the Node in the Scion : Ascendant node name

Fix: planning for new unique Forbidden Flame/Flesh Scion notable

---

src/Data/Skills/act_dex.lua
src/Data/Skills/act_int.lua
src/Data/Skills/act_str.lua
src/Export/Skills/act_dex.txt
src/Export/Skills/act_int.txt
src/Export/Skills/act_str.txt
src/Modules/CalcActiveSkill.lua
src/Modules/CalcPerform.lua
src/Modules/ModParser.lua

Setting the maximum number of stages now sets the limit for both `Stages` and `StagesAfterFirst` multipliers.
Previously to use a `StagesAfterFirst` multiplier you also had to have a `MaxStagesAfterFirst`. Now you only need `MaxStages` for any skill
This also fixes the issue where on loading explosive arrow, the skill would have 0 damage as the `base = -100` value was applying incorrectly
- Verify all skills that have been changed still functionally work the same as before
https://pastebin.com/cvMfUXzt

Unify Max Stages to not use StagesAfterFirst anymore

---

src/Modules/ModParser.lua

This is easily verifiable in game and I assume whatever sources left
that apply to all reservation of skills also follow same pattern so I
just edited "mana reservation of skills" directly.
How to verify in game:
Grab herald or anything that isnt aura, allocated Supreme Ego, observe that reservation do not changes. Then grab any aura and observe that reservation changes.

Fix supreme ego more mana reservation of skills to only affect auras

---

src/Modules/Build.lua

Fixes 2531. Sort of.
No existing "Ctrl+" shortcut for 'Notes' tab. 
-Open PoB in dev
-Press shortcut `CTRL+6`

Add keyboard shortcut for Notes section "Ctrl+6"

---

src/Classes/ItemsTab.lua

Before only if selected item was same as slot item it would be
prioritized in tooltip. But if selected slot is same it should be
priorized as well.
Before:
After:
Example pob: https://pastebin.com/kHcpj6gc

Properly sort items based on affected slot in tooltips

---

src/Classes/ItemsTab.lua
src/Modules/Main.lua

Add "Show tooltips only for affected slots" configuration option that
will show tooltips only affected slot instead of all slots (this
significantly reduces clutter when viewing jewel sockets for example).
Without config enabled (current behaviour)
With config enabled:
Config window:

Add configuration option for showing tooltips for all slots

---

src/Classes/ImportTab.lua
src/Modules/Build.lua

With import type autodetection the popup is no longer necessary and this
can be done in a lot more elegant way.
Supersedes #4246
Fixes #4163
No input:
Pasted URL:
Pasted code/after URL is fetched:
URL fetch failure:
Invalid input:

Remove import popup and allow both code and URLs in import

---

src/Classes/ItemsTab.lua

Certain modulo operations were being used to calculate flask charges generated by modifiers like the Flask Mastery "Utility Flasks gain 1 Charge every 3 seconds" &mdash; creating **severe** and unrealistic breakpoints related to flask duration.
~~Removing those modulo operations and using averages instead when calculating flask uptime provides significantly more consistent results.~~
Edit: After talking with deathbeam I decided to show both the average and minimum flask uptime, as there is some merit in the minimum uptime value when combined with the "use at full charges" flask enchant. Hiding the average or minimum uptime value may be worth considering based on which flask enchant is detected.
https://pastebin.com/KU3n2Agt

Add average flask uptime estimate

---

src/Classes/EditControl.lua
src/Classes/NotesTab.lua

This adds support to zoom in and out in any `EditControl`.
Main usage for this is the `Notes` section, which can be kinda hard to read on high resolutions.
Many build authors meanwhile use this area to describe detailed step-by-step leveling guides with a build and having the screen open while reading is probably an regular usecase. Beeing able to zoom in here might help alot of ppl.
For now I only enabled zooming for the notes. Not sure whether other editors (like editing details in the crafting screen) would benefit from it also.

Add zoom support by using shift + mouse

---

src/Modules/CalcSections.lua

Some new users to PoB would not understand why their curse effect was not being applied at full effect to bosses. This PR adds the bosses 'less curse effect' stat to the breakdown so its clearer to see why it is the case
https://pobb.in/F97WIYdi-nGm

Show Boss 'less curse effect' in resistance breakdown

---

src/Classes/ListControl.lua
src/Classes/SkillListControl.lua
src/Classes/SkillsTab.lua

I wanted to ease the tedium of enabling/disabling multiple skill groups typically found in build guide pobs and went a little further in the process.
This PR adds the following shortcuts to the skill list in Skills Tab:
- `Right Click`: enable/disable skill group
- `ALT + Right Click`: include/exclude skill group in FullDPS calculation
- `ALT + Left Click`: select skill group as the main skill
also `[FullDPS]` and `[Active]` tags are added to skill group labels to indicate their configurations
This is the current process when you want to switch between different skill sets, it requires a lot of clicks:
https://user-images.githubusercontent.com/5316261/168825159-9e81d81e-dfa0-4443-9493-336b5141016d.mp4
Also, you have to hunt for enabled FullDPS boxes if you have multiple sets of the same …

Add mouse shortcuts to skills tab

---

src/Modules/CalcPerform.lua

The mastery is meant to apply last when considering other sources of +min exposure
Fixes #4286

Fix Exposure mastery stacking incorrectly

---

src/Data/SkillStatMap.lua
src/Modules/CalcPerform.lua
src/Modules/ModParser.lua

The increased effect of auras from arrogance support is meant to be additive with curse effect for curses supported by Blasphemy
Also fixes aura effect for non-curse auras

Fix Arrogance Support not working with blasphemy curses

---

src/Modules/Data.lua

Outer ring has a radius of 480 more than the inner instead of the usual 360
Verified by looking at game files
Fixes #4403

Fix Massive Thread of Hope outer radius

---

src/Data/Skills/act_dex.lua
src/Export/Skills/act_dex.txt

Fixes #4356.
Viper Strike was corrected in two separate ways for counting poison stacks back in January, 2022. 
1) I added coded for tracking `stackMultiplier` so you can set number of "hit" instances a skill provided for things that stack (e.g., Poisons, Impales, etc.). 
2) I corrected code for how `stats` were combined for skills that had the `skillData.doubleHitsWhenDualWielding` set to not average (i.e., "divide by 2") but rather combine the two hits.
Implementing both fixes resulted now in Viper Strike applying 4x the amount of stacks it was doing, rather than just 2x.
- Loaded build code: https://pastebin.com/RyQx3EUp
- Compared "before" and "after" Calcs Tab for `Max Poisons Stacks` breakdown
-
https://pastebin.com/RyQx3EUp

Fix: Double Counting Dual Wield Poison Stacks

---

src/Modules/BuildSiteTools.lua

Small fix. The current matchURL pattern doesn't catch `-_` while the regexURL correctly does.
Sample URL: https://pobb.in/_wHfwMSjZWm6

Fix pobb.in match pattern used while importing

---

src/Modules/Build.lua

To reproduce:
1. Checkout an old version of PoB
2. Try to load a current build (e.g. https://pastebin.com/fmCLSfnD )
3. Notice crash because the build code exits early before initializing some dropdown values
This simply moves the initialization code before any of the savers trigger

Fix crash when loading build containing a newer tree

---

src/Modules/Build.lua

Fixes #2366 .
This is done on a case-by-case basis instead of globally because there are only a few dropdowns that have this issue, and the ability to view tooltips with a dropdown open is still a desirable feature.

Remove tooltip if covering dropdown is opened

---

src/Modules/CalcDefence.lua

Fixes #4425 and #4427 .
nil value check missing brackets causing crash for gain on block
also fixes sirus pen being ignored

fix crash when mana unreserved is nil

---

src/Data/Uniques/ring.lua

the mings heart unique, has "variant one" dropped from the first energy shield mod due to a misplaced bracket
I have no idea why the first line of the file thinks its modified

Fix Ming's Heart variant typo

---

src/Data/Skills/act_str.lua
src/Export/Skills/act_str.txt

Fixes #4501
Determination skill is missing proper stat for alt quality stun avoidance mod. This PR adds it.

Fix Determination aura alt quality mod

---

src/Modules/ConfigOptions.lua

Fixes #4333.
Corrosion isn't disabled when mod is hidden because of no source.
This issue also affects vaal arc lucky buff and feeding frenzy but after trying for a bit I couldn't figure out how to fix them as well.
- Disabling the mod correctly decrease dps.
https://poe.ninja/pob/B5I
4 Stacks in config
Without mod it vanishes

Fix corrosion not being disabled when mod is not present.

---

src/Modules/CalcDefence.lua

The "Increases and Reductions to Armour also apply to Energy Shield Recharge rate at 20% of their value" mastery does not currently scale with % Evasion and Armour, or % Global Defences modifiers.
In-game testing indicates that this is incorrect. All modifiers to % Armour are meant to apply to Energy Shield Recharge rate with this mastery allocated, not just pure % Armour and hybrid % Armour / % Energy Shield modifiers.
https://pobb.in/OIzAQlu7GjUW

Fix Energy Shield Recharge mastery

---

src/Modules/CalcOffence.lua

Fixes #4391.
Due to the weighted average formula and cast on death trigger time being 60 seconds this results in an extremely low stack potential when we should just get one ignite stack.
- See ignite dps in appropriate range ~30k
https://poe.ninja/pob/AnD

Fix ignite with cast on death

---

src/Data/Uniques/Special/Generated.lua

Fixes #4399.
Variant index's didn't lineup due to double damage being omitted.
- Try to select fire dot multi and or minion damage and it produces the correct mod.
https://poe.ninja/pob/An5

Fix Paradoxica

---

src/Classes/SkillsTab.lua

Video demonstration of the two bugs this PR addresses: https://www.youtube.com/watch?v=_kFGidpU7cQ
Vaal skill gems grant both a vaal skill, and the matching non-vaal equivalent. PoB controls whether or not these skill-parts are enabled via checkboxes &mdash; enableGlobal1 and enableGlobal2 respectively. 
----
Bug no. 1:
If you have two vaal skill gems with different toggle states and delete whichever one is above the other, the toggle states from the deleted gem will persist in that gem slot, overriding the expected toggle states from the gem that was not deleted. This is bizarre and counterintuitive, as everything else about the deleted gem is removed/replaced.
I fixed this by adding enableGlobal1 and enableGlobal2 to the list of gem slot variables that are updated whenever a gem is …

Improve skill gem state persistence

---

src/Data/Skills/spectre.lua
src/Export/Skills/spectre.txt

Fixes #4459.
https://poedb.tw/us/Pale_Seraphim#PaleSeraphimHellscapePaleElite2Spectre
https://poedb.tw/us/Thunder_Web
https://pastebin.com/0EDzuR16

Add Pale Seraphim "Thunder Web" debuff

---

src/Classes/PassiveSpec.lua

Fixes #3839.
Anointed notables were not being saved to editedNode data (as they are not actually allocated on the passive tree, and were being excluded from the editedNode saving process as a result) preventing changes made to conquered anointed notables from saving to build XML.
- Load showcase build.
- Right click the anointed Robust notable and assign it any conquered modifier.
- Save the build and restart Path of Building.
- Load the build you just saved and verify whether or not the anointed notable is still conquered.
https://pastebin.com/7SuQUibq

Save anointed notables to legion jewel editedNode data

---

src/Modules/CalcOffence.lua
src/Modules/CalcPerform.lua
src/Modules/ConfigOptions.lua

Fixes #3172.
----
At 100% reduced cooldown recovery rate, the cooldown for any given skill should be infinite. This is correct, and how things work in both PoB and in-game currently. If you go *beyond* 100% reduced cooldown recovery rate however, in PoB currently that results in massive **negative** cooldown values:
I fixed this by copying what PoE does: reduced cooldown recovery rate beyond 100% simply doesn't do anything further.
----
All warcry-related "average uptime" calculations were using the wrong duration multiplier. Specifically they were using the duration modifier stat when the actual skill duration was expected. This leads to things like Enduring Cry providing half it's expected buff effect:
I fixed this by replacing:
```lua
local full_duration = …
```

Fix warcry duration and cooldown calcs

---

src/Classes/CheckBoxControl.lua

Fixes #4418 #3811.
Incorrectly aligned clicking on text for associated check box.
- Clicking on the boxes and text now properly lines up.
https://pastebin.com/aX9t1W7r

Fixes labels having an incorrect font size and alignment for checkmark boxes.

---

src/Data/Uniques/Special/Generated.lua

Phase Acrobatics was removed from the game in 3.16.
Impossible Escape was introduced in 3.18, meaning there's no situation where Impossible Escape should ever roll Phase Acrobatics.
I added Phase Acrobatics to ``excludedItemKeystones`` (similar to Mortal Conviction, which was already present) to fix this.
This also removes Phase Acrobatics keystone option from Skin of the Lords. This does not affect builds that already contain uniques with Phase Acrobatics. In 3.16 GGG swapped Phase Acrobatics for Acrobatics on existing items.
Minor formatting errors in ``\src\Data\Uniques\Special\Generated.lua`` were also fixed (mostly mixed tabs and space indentation, converting 4 spaces to tabs).

Remove Phase Acrobatics from Impossible Escape

---

src/Modules/CalcPerform.lua

Flat reservation values in-game round to the nearest integer. In Path of Building we were rounding them to two decimal points, leading to invalid warning messages about reserving too much mana.
I tested this in-game and flat reservation values do in fact round, it's not truncated or floor/ceil.
https://pastebin.com/naUVAL39

Fix Flat Reservation Rounding

---

src/Data/Uniques/Special/Generated.lua

Watcher's Eye still read the grace and haste dodge mods as the variant name, when they instead give a chance to suppress spells, now
Just search for watcher's eye

Rename old dodge chance mods on watcher's eye

---

src/Modules/ModParser.lua

Fixes #4455 .
Description of the problem being solved:
Ghastly Eye Jewel can have a mod that reads "d% increased cast speed if a minion has been killed recently". From in-game testing this seems to proc under exactly the same conditions as "if a minion died recently".
However, the mod does not get parsed by POB because we only look for the string "if a minion died recently". It is inconvenient because any build that relies on this jewels needs manually modify them each time they are imported to calculate their cast speed properly.
- Create a new build
- Path to a jewel socket
- Create a custom item with the following stats 
Enthralling Leer
Ghastly Eye Jewel
Unique ID: 437aad3ec28997fc919c9d100102fb765eb5ca2a27b28d2bafa334010211790a
Item Level: 74
LevelReq: 28
Implicits: 0
+30 to maximum …

Add support for "% increased cast speed if a minion has been killed recently"

---

src/Data/Uniques/ring.lua

In the game, Icefang Orbit's 25% chance to Poison on Hit does not scale with Noxious Catalysts; only (40-60)% increased Damage with Poison does. PoB currently allows both mods to scale with Noxious Catalysts. This change brings PoB in line with the game.
Even though Venopuncture is basically the same ring and was released at the same time, its 25% chance to cause Bleeding on Hit does scale with Abrasive Catalysts in the game; therefore, its behavior in PoB has not been changed.
- Running PoB in dev mode and visually inspecting the Icefang Orbit item and poison calculations
https://pastebin.com/Gr0E7yFB

Stop Noxious Catalyst from scaling Icefang Orbit's chance to poison

---

src/Classes/ItemsTab.lua
src/Modules/CalcPerform.lua
src/Modules/ModParser.lua

Sentinel mod:
Magic Utility Flasks applied to you have 25% increased Effect
Example pob: https://pastebin.com/z7LJP8ch

Add support for Magic Utility Flasks applied to you have inc effect

---

src/Modules/ConfigOptions.lua
src/Modules/ModParser.lua

Also fix shocked ground boot implicit and do not hardcode value for
scorched ground.
Example pob: https://pastebin.com/p6LsbM4h
Brittle boots with 60% ailment effect

Add support for brittle/sapped ground and alt ailment boot implicits

---

src/Classes/ItemsTab.lua

Pasting "Doppelgänger Guise" into the custom item creation box shows as "Doppelg?nger Guise".  This is true for many letters as the old way was only checking for ö -> o.  Also fixed a small issue when copying an item from poe.ninja that wouldn't show the item as unique

Fix unicode sanitization issues

---

src/Data/Skills/act_str.lua
src/Export/Skills/act_str.txt

Fixes #4347.
Smite's area hit is not a melee attack.
This is further supported by the wiki saying this as well. https://www.poewiki.net/wiki/Smite
- Applying melee modifers no longer effects the area hit.
https://poe.ninja/pob/BMs

Fixed smite area hit being classed as melee

---

src/Data/Uniques/boots.lua
src/Data/Uniques/helmet.lua
src/Data/Uniques/ring.lua

Fixes #4511.
Skyforth's reservation wording did not match in-game. Skyforth also had legacy variants when none exist in-game. Both of these issues were fixed.
Victario's Flight and Mindspiral were updated to use the Recoup keyword (added in 3.12) that replaced "Mana gained over 4 seconds when hit" globally.
Attack dodge no longer exists anywhere in PoE (as of 3.16) and was replaced with movement speed on Mutewind Seal specifically.

Update Skyforth, Victario's Flight, Mindspiral, Mutewind Seal

---

src/Classes/TreeTab.lua

The seeds in ``TreeTabClass:FindTimelessJewel`` needed to be multiplied by 20 for ``jewelType.id == 5`` to generate valid Elegant Hubris jewels.

Fix Elegant Hubris seed generation in FindTimelessJewel function
