PathOfBuildingCommunity/PathOfBuilding

src/Data/Uniques/jewel.lua
Fixes # .
The source in the tooltip text for all unique Delirium jewels indicated that they are from Simulacrums. This is incorrect - only Megalomaniac, Voices and Split Personality are from Simulacrums. The rest are from Kosis and Omniphobia encounters in maps.
These are:
[Calamitous Visions](https://www.poewiki.net/wiki/Calamitous_Visions)
[Kitava's Teachings](https://www.poewiki.net/wiki/Kitava%27s_Teachings)
[Natural Affinity](https://www.poewiki.net/wiki/Natural_Affinity)
[One With Nothing](https://www.poewiki.net/wiki/One_With_Nothing)
[The Front Line](https://www.poewiki.net/wiki/The_Front_Line)
[The Interrogation](https://www.poewiki.net/wiki/The_Interrogation)
[The Siege](https://www.poewiki.net/wiki/The_Siege)
- Updated the text in `src/data/Uniques/jewel.lua`
=> Update source text of unique cluster jewels

src/Classes/ButtonControl.lua, src/Classes/CalcSectionControl.lua, src/Classes/CalcsTab.lua, src/Classes/CheckBoxControl.lua, src/Classes/ConfigTab.lua, src/Classes/ControlHost.lua, src/Classes/DropDownControl.lua, src/Classes/EditControl.lua, src/Classes/GemSelectControl.lua, src/Classes/ListControl.lua, src/Modules/Build.lua, src/Modules/CalcSetup.lua, src/Modules/ConfigOptions.lua
`ControlHost` remembers the currently active control in `selControl` and can inform it's controls via additional parameter `noTooltip` passed to `Draw` methods whether they should draw tooltips. Additional parameter in `DrawControls` allows to pass the active control to lower levels in cases of nested controls (e.g. `CalcSectionControl`)
This frees some space in the side panel. Loading old build should work correctly and the attributes are saved in the `Build` node as well for backwards compatibility.
=> Fix overlapping tooltips, move bandit and pantheon options into the Config tab

src/Classes/ImportTab.lua
Fixes missing enter function for keyboard style import.
Pressing Ctrl-N, Ctrl-I, Ctrl-V, [enter] failed to complete the import.
- Using https://pastebin.com/WMichBY3, use the keys listed above to prove the import works (main skill is Dark Pact)
- Using https://pastebin.com/WMichBx3, use the keys listed above to see that the normal error routine(s) are still being observed.
- Using the mouse, paste https://pastebin.com/WMichBY3 into import edit box and select 'Import' button and see import occurs without the two click process
Noted in tests
N/A
N/A
=> Add enter function for Import Edit control

src/Data/Uniques/helmet.lua, src/Data/Uniques/shield.lua
Updated Maw of Conquest to use the Recoup keyword added in 3.12.
Updated Thousand Teeth Temu to use the correct reflect recovery wording. This new wording was added somewhere between April 2017 and April 2021, it doesn't appear to be documented anywhere though.
=> Update wording on Maw of Conquest, Thousand Teeth Temu

src/Modules/CalcPerform.lua
Fixes #2229.
when using x aura or similar modifier doesn't consider you using the base aura of the vaal aura.
- Add spell suppression haste watchers
- Enable Vaal Haste
- See spell suppression chance go up.
https://poe.ninja/pob/Am6
=> Fix a bug where if affected by a vaal aura you weren't considered affected by the regular aura

src/Modules/CalcDefence.lua, src/Modules/CalcSections.lua
Fixes #3847.
Add Self Curse Effect to Calcs panel.
Also removed some unnecessary multiplications
- Hovering the curse effect shows the effect breakdown.
https://poe.ninja/pob/Bio
=> Add self curse effect to calcs tab.

manifest.cfg, update_manifest.py
Currently, new files have to be added to the manifest manually. This PR automates the inclusion of new files in certain directories, based on the configured include/exclude directives.
Run the script and verify that the output matches the existing script. Note that this only works if no files have changed since the last release. You possibly need to check out a specific commit to test this script.
Might add automatic tests in the future, but this script is hard to mock.
=> Refactor manifest updater

src/Modules/CalcOffence.lua, src/Modules/CalcPerform.lua
Fixes #4332.
This fixes sources that reduce mana reserved to zero not applying globally on infinite mana reservations such as 100 reduced mana efficiency. This primarily is for essence worm.
- Mana & life reserved is now correctly at 0 when looking in the panel.
- 100% reduced efficiency and greater now correctly display inf this coincides with ingame.
-  Greater than 100% reduced acts as 100% reduced (infinite reservation)
https://poe.ninja/pob/BMq
Essence worm + memory vault (socketed in essence worm)
2 Essence worms not socketed (160% reduced efficiency)
2 Essence worms socketed
=> Correctly handle 100% reduced reservation efficiency and greater.

src/Classes/SkillsTab.lua
Currently when you copy/paste socket group with auras etc there is no
way to actually enable them because enableGlobal1/2 is not set.
Fixes #3609
- Create new socket group with random aura reserved
- Copy and paste this socket group
- Notice that the new socket group is not reserving any mana even though it has aura active
This also applies to buffs and blessings.
=> Fix socket group copy/paste

src/Classes/ModStore.lua, src/Modules/ModParser.lua
Fixes #4483 offering effect boot mods
Fixes flask regen mod
Fixes increased defences from armour pieces mod
Adds support for slotNameList
=> Fix more Eldritch mods

src/Classes/Item.lua
Fixes #4223.
Flask duration is round to 1 decimal place ingame
- Flask duration are now correct to what is seen ingame display 2 dp but round to 1.
https://pastebin.com/tQKeZPGz
=> Fix Flask Duration to match in game values

src/Classes/PassiveSpec.lua, src/Classes/TimelessJewelListControl.lua, src/Classes/TimelessJewelSocketControl.lua, src/Classes/TreeTab.lua, src/Modules/Build.lua
Pending testing this should be ready to merge, as all core features are implemented.
Demo: https://www.youtube.com/watch?v=LlcJafb6C8I
=> Further Timeless Jewel search improvements

src/Data/Skills/act_str.lua, src/Export/Skills/act_str.txt
Fixes #4508 .
Herald of Purity minions were missing a duration tag
=> Fix Herald of Purity minions missing a duration

src/Classes/SkillsTab.lua
Fixes #2810 .
See issue
- Create a gem
- Support it with alt quality gem
- Support it with Awakened gem
- Support it with alt quality gem
- Delete first alt quality gem
- Verify the only alt quality option for the awakened gem is "Default"
- Verify the other alt quality gem has their normal alt quality options
=> Fix alternate quality dropdown options not changing on gem deletion

src/Classes/ModStore.lua, src/Modules/CalcPerform.lua, src/Modules/ModParser.lua
Fixes #4290.
Add support for Supreme Ego and disable auras if they reserve more than maximum mana.
Greater than 100% reduced reservation and essence worm will behave weirdly with this patch so #4514 should be merged first.
- Checking various auras ingame it seems any skill that have the aura tag will be effected by the mod this means tempest shield, blood and sand aren't affected at all.
- Any skill of your that apply any aura to anything but you will not work, blasphemy, pride, smite aura, etc.
- I haven't tested the mine auras but I presume they won't work. The current code disables them as well the aura effect only is based on one mine which I am not sure is correct but they are disabled with supreme ego anyway so it doesn't matter.
- A curse in profane proxy won't work either but I …
=> Add Support for Supreme Ego

src/Classes/Item.lua, src/Classes/ItemsTab.lua, src/Modules/Main.lua
Fixes #1355.
Adds a fairly straightforward configuration option that allows users to set a default item affix quality/percentile value.
This affects the ``{range:0.5}`` value on generated rares and uniques (implicits, prefixes, suffixes).
This also affects modifiers you add while crafting, though in a slightly different manner (it selects the actual point on the slider bar, not the ``{range:0.5}`` value).
Demo video: https://www.youtube.com/watch?v=7OvykjdKgNY
=> Add Default Item Affix Quality option

src/Classes/ItemsTab.lua
``self.items`` in ``ItemsTab.lua`` was being copied recursively whenever an UndoState was created, storing way too much information and eventually crashing PoB entirely due to Out of Memory errors.
Limiting that recursion to a certain depth fixes the problem, and doesn't seem to break anything (fingers crossed).
Fixes #3733, #4311.
Demo video: https://www.youtube.com/watch?v=F5ejSSiNgwA
=> Fix Out of Memory crash in Items Tab

src/Classes/ConfigTab.lua
Return placeholder value when checking default state
Currently code thinks that the default state is 0 when saving numbers, this means when i am changing placeholder for for example lightning pen from 5 to 0 it wont save and then dissapears on reload.
- Set enemy to Guardian/Pinnacle Boss
- Set enemy lightning pen to 0
- Save build
- Close build
- Reopen build
- Enemy lightning pen is still 0
=> Fix saving of changed placeholdered values

src/Classes/SkillSetListControl.lua, src/Classes/SkillsTab.lua
Adds support for skill sets for socket groups. This is useful for adding
different sets for different character state or progression (e.g
Acts/Starter/High Budget etc).
Fixes #2060
Example:
"Arc set"
"Crackling lance set"
The build values/reservations and active skill is properly updated.
Example pob:
https://pastebin.com/u6zGbcp0
The format the data is stored in:
=> Add support for skill sets (socket group sets)

src/Modules/ModParser.lua
Ailment immunity after getting the devotion threshold wasn't supported
- Added a timeless jewel with that node to the build
- Noted that the mod wasn't supported
```bash
eNqtW-tz2kgS_xz-iimutuq2Ftt6I7z2bmGMH2vsOICT27q6co3FAEpGM4o0skOu_L9fjx4gMI9BvnwgQupfd09Pv6ZlTv78EVD0TKLY5-y0rh9qdUSYx0c-m5zWH4YXB279zz9qJ_dYTD-OzxKfyid_1D6cpNeIkmdCAVdHAkcTIj4XnMxH4BRiJqaEs1v8lUeXfHRav-OM1NETZiNfFN88iuP4DgfktD7wAFxHOPYIG3UW9zPCAPtswL1vRFxGPAlTsc8-ebnlI6C5vr3_2B-WhPqsLBR0_nByT_GMRAOBBYrh47TehqXjCTnHAXwCN0wTYGUf2k3DcO2mbsnP-tF68CAkZDQH6YfGJsL7iHTHY-IJ_5l0Il90pph5C3HaJty-tLcJFX5IfRKVtLI3Ia7eMG-1NtEOucD0_H4wJ3UOHddpWrmRduC42K3_F19MzygYtIIUib2eMF-QiuB77secvWN9ZejmLUoohehRo-XBk88qWeMWM9zhsYLNe_6YqFF2B2p0fQgjNUqp5T2JINCFurJ7AXIJA-JxSCb7yNgHUlpHNWEVkN1BFUAFQQOxyCTWxkRyTn7MqYyNvK6ZUKA6J89cpEWgSGBNbWvwda_u57QMs40peD …
```
=> Add support for ailment immunity mod on timeless jewels

src/Classes/Item.lua, src/Modules/ItemTools.lua
Fixes #4345.
Conditions get scaled by catalysts when they shouldn't.
This solves catalyst scaling issues on Bear's Girdle, The Magnate and other similar items.
I have very limited lua programming experience so please feel free to make sure it works properly and this change won't break other stuff.
I think this might partially fix #4466 and the reason it stop scaling at all is due to a passing issue that the mods aren't scaling anymore.
https://pastebin.com/6Rc64wEM
=> Fix multi number mods scaling the wrong number with catalysts

src/Classes/SkillsTab.lua
- Properly create undo state while 100% preserving same indices
(probably unnecessary but I noticed that I was relying on ordered
index)
- Move getting displayId from displayGroup at start of restore undo
method (like before) so it can get the position before the values are
replaced and instance comparison is no longer possible. Without this
change display group always resets on undo
- Add random gem to new socket group
- Add another random gem
- Undo
- Display group is reset
This PR fixes the last part.
=> Fix undo resetting active display group

.busted, spec/System/TestBuilds_spec.lua
The build tests have been failing and will continue to unless we find a painless way to keep them in-sync.  For the time being, this disables that test so we can at least still see the results of the (admittedly few) existing tests
=> Exclude failing build tests

.github/workflows/installer.yml
Fixes #4456 .
The PoB standalone file and installer have to be manually created and uploaded to each release by a maintainer.  This isn't always consistent because it's a manual action.  This PR does all that through GitHub Actions
- Ran a successful build on my personal repo: https://github.com/Wires77/PathOfBuilding/runs/7293463450?check_suite_focus=true
- Validated that the files appeared as expected here: https://github.com/Wires77/PathOfBuilding/releases/tag/powershell
=> Automate installer upload

src/Classes/CalcSectionControl.lua, src/Classes/CalcsTab.lua
This fixes loading and saving of collapse state for sections/subsections
in calcs. I assume at some point collapsing for subsections was added
but the loading/saving code was never adjusted.
https://pastebin.com/Mb2wy4hX
```xml
<Calcs>
<Input number="2" name="skill_number"/>
<Input string="EFFECTIVE" name="misc_buffMode"/>
<Section id="SkillSelect" subsection="ViewSkillDetails" collapsed="false"/>
<Section id="HitDamage" subsection="SkillHitDamage" collapsed="true"/>
<Section id="Warcries" subsection="ExertingWarcries" collapsed="false"/>
<Section id="Dot" subsection="SkillDamageoverTime" collapsed="false"/>
<Section id="Speed" subsection="AttackCastRate" collapsed="false"/>
<Section id="Crit" subsection="Crits" collapsed="true"/>
<Section …
```
=> Fix saving of section/subsection collapsing in calcs

src/Classes/TreeTab.lua
Extremely minor technical fix.
``[%.| ]`` to ``[. ]`` -- the period doesn't need to be escaped inside a set and the pipe character is just invalid here (I was thinking of alternation from regex and could have sworn I read it was valid syntax somewhere, but apparently this doesn't actually exist in Lua patterns).
https://gitspartv.github.io/lua-patterns/?pattern=%5B%25.%7C%20%5D
https://gitspartv.github.io/lua-patterns/?pattern=%5B.%20%5D
=> Remove invalid Lua pattern text

src/Classes/TreeTab.lua
Allows you to search for timeless jewel node stats in the dropdown list (rather than just by name).
Credit goes to @Regisle, I just split this off so it can be merged independent of the rest of #4566.
=> Search timeless jewel node stats in dropdown

src/Modules/CalcPerform.lua
Auras disable sometimes due to multiple iterations of reservation calculations
As reserve base is calculated with reference to the previous reserve base calculation it grows until the aura gets disabled. This changes it to use the currently calculated flat resource to reserve.
- Toggling supreme ego now correctly shows dps increase not decrease.
-  Looking at variables they do not grow on iterations.
https://pobb.in/yyfVaqMYkCpz
=> Fix auras disabling due to multiple iterations of reservation calculations

src/Modules/CalcSetup.lua
Anointed notables were not being modified by legion jewels conquering them.
https://pobb.in/4E9kvFxQhsxf
=> Fix anointed notables not being conquered

src/Modules/Data.lua
Fixes #4562. Node IDs need to be validated before ``loadTimelessJewel(...)`` attempts to do anything with them for Glorious Vanity.
https://pastebin.com/ATj6THEm
=> Skip invalid nodeIDs for Glorious Vanity

src/Modules/Data.lua, src/Modules/Main.lua
Under certain conditions PoB is denied write access to ``GetScriptPath()``. This generally means the user updates PoB using something other than our built-in updater. In this scenario we cannot write the ``*.bin`` TimelessJewelData files to disk, and if we try to do so it breaks quite horribly. Luckily we don't actually need to write those files to disk, so we can just skip it.
See: https://aur.archlinux.org/packages/path-of-building-community-git#comment-873655
Additionally ``changelog.txt`` sometimes does not exist. If we attempt to read from it with ``io.lines`` before verifying the file actually exists, an error is thrown.
See: https://aur.archlinux.org/packages/path-of-building-community-git#comment-868605
=> Skip writing uncompressedFile if denied access, and skip reading changelog.txt if it doesn't exist

src/Classes/SkillsTab.lua
Generally we don't want to save ``nil`` to a string in the build XML, as simply discarding it is more efficient and results in a smaller file size. It also avoids unnecessary string reparsing, as almost regardless of how you read a missing build XML variable.. if it's not there: it's ``nil``.
=> Prevent saving nil groupCount to build XML

src/Classes/PassiveSpec.lua, src/Classes/PassiveTreeView.lua
Fixes #3762.
Masteries were not initialized correctly upon import.
``self.allocNodes[id].allMasteryOptions = false`` was not set by ``PassiveSpecClass:AllocateMasteryEffects(...)``, breaking the mastery dropdown list tooltip (as it attempts to index multiple ``node.mods[i]`` when only one is valid).
=> Fix broken mastery import state

src/Classes/EditControl.lua, src/Modules/CalcDefence.lua, src/Modules/CalcSetup.lua, src/Modules/ConfigOptions.lua
Fixes #4571. Supersedes #4585.
Character EHP was ``nan`` for all new builds, as various different configuration options were not initialized correctly until after you poke some settings in the configuration tab.
This also caps enemyLevel to characterLevel for normal enemies when left at their default placeholder level. This does not affect boss enemies, as capping their level doesn't really make sense.
=> Fix "NaN" EHP initialization error and cap enemyLevel

src/Classes/ButtonControl.lua, src/Classes/DropDownControl.lua, src/Classes/GemSelectControl.lua, src/Classes/ItemListControl.lua, src/Classes/ItemsTab.lua, src/Classes/ListControl.lua, src/Classes/SharedItemListControl.lua, src/Classes/SkillsTab.lua
#4441 was preventing item list tooltips under the items tab, the "save" button when editing item text, and gem select controls from displaying tooltips when they were not the currently focused control element.
This restores that behavior, as the ``noTooltip`` functionality (as far as I can tell, anyway) is not necessary to prevent overlapping tooltips for those specific controls.
There are a few other cases where similar changes might also be beneficial (such as the equipped items list), but I wasn't able to get those elements working with a ``forceTooltip`` option.
=> Allow certain controls not require focus to display tooltips

src/Classes/SkillsTab.lua
This is leftover from the original format where skillSet was saved on
Skill instead of being wrapped in SkillSet
=> Remove leftover skillSet field on Skill when saving to XML

src/Data/Skills/act_int.lua, src/Export/Skills/act_int.txt
When GGG changed the file format to use Constant stats they removed the previously unused stat of `base_maximum_energy_shield` so it made Vaal Discipline no longer count towards mods like `Auras from your Skills grant x`. This adds a Dummy stat to fix that issue
The stat name is `EnergyShieldRechargeNotDelayedByDamage` so when it shows up under the `Aura and Buff Skills` section, it is clear to users what the mod is
=> Fix Vaal Discipline not counting towards Aura count

src/Classes/SkillsTab.lua
Fixes a bug introduced by #4493 where the toggle state of ``enableGlobal1`` and ``enableGlobal2`` were linked to the overall skill enable state for non-vaal skill gems, causing the ``Enabling this gem will give you`` tooltip text to never be visible.
Note that you will need to toggle the skills enable state if loading an old build where these variables were previously linked, as it doesn't go out of its way to correct existing data (as it technically doesn't cause any issues with the actual build, it only affects this one tooltip).
https://pobb.in/28v14DODnY7L
=> Fix enable skill tooltip visibility for non-vaal active skill gems

src/Modules/CalcSetup.lua, src/Modules/ConfigOptions.lua
1) The check for if an enemy was a standard boss for setting an enemy level cap was using the label, not the value, and thus wasn't working.
2) The level cap was being calculated after configoptions took effect, leading to a situation where changing what boss you were targeting used the previous boss' level cap. 
- Set boss to "No"
- Set boss to either pinnacle option
- Boss damage is set to whatever is the cap for a monster of the same level as your character (18 for uber pinnacle on a level 1 character)
- Set boss to "No"
- Set boss to either pinnacle option
- Boss damage is set to the default level of the boss, or whatever you set it to if what you set it to is higher.
=> Fix default level for pinnacles

src/Modules/CalcDefence.lua
Fixes #4267
This is my first ever PR for POB, please be kind :)
It looks like when trying to calculate the base amount of evasion rating to be converted to armour, it doesn't include stats gained from `ArmourAndEvasion` type mods. 
As an example (and more spesifically to the issue linked above): mods such as `+# to Armour and Evasion Rating` do not lead to extra armour from the `Gain 5% of Evasion Rating as Extra Armour` mastery from the tree.
I made a belt that just has `+# to Armour and Evasion Rating` and equiped it. Hovering over the `Total` section of Armour in the Calcs tab - It should show a correct base value that is sourced from `Conversion`. 
In my example POB, with just the `Gain 5% of Evasion Rating as Extra Armour` mastery from the tree, it should convert %5 of the base …
=> Fix evasion to armour conversion calculation not including "armour and evasion" base stats

src/Modules/Build.lua, src/Modules/Main.lua
Fixes #4605.
Character levels were not restricted to a valid range (1-100) leading to various crashes in ``ModDB.lua``.
This PR prevents invalid default character levels from being saved under options and forces character levels to fit within the valid range (1-100) when loading build files.
=> Prevent invalid character level values

src/Modules/CalcOffence.lua
Attacks with Trypanon weren't correctly being modified by crit chance effects
=> Fix Trypanon crit chance calculations

src/Classes/Item.lua, src/Modules/ItemTools.lua
Introduced in https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/4484.
Due to applyRange() being called to scale mods visually and actual mod scaling being done by applying applyRange() on ranges and applyValueScalar() on everything else. This meant some mods weren't being scaled. This updates applyRange() to support singular mods and remove direct usage of applyValueScalar()
- Applying crit catalyst now scales Marylene's Fallacy less critical strike chance visually.
https://pobb.in/pNGoft1qYVy9
=> Fix catalysts visually not scaling certain mods.

src/Classes/ModDB.lua, src/Classes/ModStore.lua
Ingame when applying a more multiplier it truncates all of the partial more multipliers then multiplies and rounds to the nearest percent.
https://pobb.in/9I_Oedp2IMk5
=> Fix total more multipliers not being round to nearest percent as done ingame.

src/Modules/CalcDefence.lua
The mod was not using any evasion rating from gear when Iron Reflexes was allocated even though it should have been.
This also fixes the evasion rating from gear appearing in the armour section when it should have been in the evasion section imo
=> Fix Evasion as Extra Armour with Iron Reflexes

src/Modules/BuildSiteTools.lua
This is a preparation for a future feature of pobbin to support importing codes from different URLs (e.g. user scoped): `https://pobb.in/u/example/cool_build`
This also allows the wesbite to restructure (or introduce new) URLs without breaking PoB in the future
- Testing the Import Tab with verification on stdout
- Testing the protocol import (first commandline argument)
Missing `/pob/` segment:
Fetching the build (not implemented on pobbin so the 404 is expected):
=> Makes pobbin matching less restrictive

src/Modules/Build.lua
Fixes #1649  .
Solution for issue: Unreserved life: 0 does not turn red in POB #1649
The function buildMode:FormatStat is set to only highlight values when they are below 0. In:
`local color = (statVal > 0 and "^7" or statData.chaosInoc and "^8" or colorCodes.NEGATIVE`
I added an if-condition to after the color assignment to check if it was for the label Unreserved Life, and value 0 and then also set it to colorCodes.NEGATIVE. 
This also made it logical to also update the warningtext/function in displayStats to "Your unreserved Life is less than 1" and make the warning show at 0 aswell.
More general solutions could be to have a flag/evaluation function in the stats-definition which is being read/called in FormatStat, but it might be overkill if it's only needed for Unreserved Life …
=> Change sidebar to show red numbers for unreserved life of 0

src/Modules/CalcDefence.lua
The placeholder physical damage value ``enemyDamage = round(data.monsterDamageTable[m_min(env.build.characterLevel, 83)] * 1.5)`` in ``CalcDefense.lua`` was incorrectly applying to bosses and boss skill presets, when it was only meant to serve as a fallback value for normal enemies when the the enemy stats configuration section is uninitialized.
This leads to things like the Shaper Ball skill preset inexplicably dealing physical damage (which is fixed by this PR).
Long term we should handle uninitialized configuration settings in a different way, as having placeholder values duplicated like this is far from ideal. @Regisle said he would look into a proper fix for this at some point.
=> Fix placeholder physical damage applying to bosses

src/Classes/ConfigTab.lua, src/Modules/Build.lua, src/Modules/CalcDefence.lua, src/Modules/ConfigOptions.lua
Force rebuild to initialise boss presets and remove phys fallback in calcDefences
supersedes #4612
> The placeholder physical damage value enemyDamage = round(data.monsterDamageTable[m_min(env.build.characterLevel, 83)] * 1.5) in CalcDefense.lua was incorrectly applying to bosses and boss skill presets, when it was only meant to serve as a fallback value for normal enemies when the the enemy stats configuration section is uninitialized.
> 
> This leads to things like the Shaper Ball skill preset inexplicably dealing physical damage (which is fixed by this PR).
This also makes old builds load as pinnacle boss not uber, and no longer sets enemy level for none/boss (instead letting it be based off character level again, it will still be 83 for most builds)
open a new build (or load an old …
=> force rebuild to initialise boss presets and remove phys fallback

src/Classes/NotableDBControl.lua, src/Modules/CalcDefence.lua
Fixes node power when infinities are involved (eg ehp)
This works for both anoints and passive tree
before:
after:
This also re-implemented max hit sorting, using SecondMinimalMaximumHitTaken
=> Node power sorting

src/Classes/ConfigTab.lua, src/Modules/Build.lua, src/Modules/CalcSetup.lua, src/Modules/ConfigOptions.lua
Fixes the issue where when changing the enemy level in the config tab (or by changing boss preset) it would use the old value, this is because enemy level was calculated after config tab had "rebuilt"
This still needs to rebuild configTab whenever the player level is changed to be fully correct, but is progress
=> Fix config tab being 1 change behind enemy level

src/Data/Uniques/Special/Generated.lua
Title ^
removes around 44 lines of duplicate text
=> cleanup impossibleEscape by combining similar variant lines

src/Data/Skills/act_int.lua, src/Export/Skills/act_int.txt
Fixes #4678 .
Some mods on the incinerate gem had their text displayed in red even though they were being handled correctly.
=> FIX: Add an emtpy stat to remove confusing red text on incinerate

src/Data/Skills/act_int.lua, src/Export/Skills/act_int.txt, src/Modules/CalcPerform.lua, src/Modules/ConfigOptions.lua, src/Modules/StatDescriber.lua
- Scorching Ray didn't have an option to only stack to the maximum you could, like Blight.  Also removed some dead code.
- Frost Shield and Sigil of Power didn't get their stage maximum from the skill, so the code was fixed for future proofing.  Incidentally, this also added support for anomalous Sigil of Power.
- The description for Frost Shield and other skills were using the wrong rounding value, so even if the value was correct, the gem description wasn't
- Removed dead config code for an old Frostbolt alternate quality
```
eNrFG11z2rj2ufsrPLwnBAhptkN2hwBJmAkNF9L23qeOsA-gjWxRW07C_vo9kmxwiGVkZWduHlpjne8vnSPbvT9fQ-Y9Q5xQHl01WqdnDQ8inwc0Wl01vj3enFw2_vzjt96UiPXD8jqlTK788dunnrr2GDwDQ7yGJ0i8AvE9p9T5iZQ2JBJr4NGE_MXjWx5cNb7yCBregkQBFfkvn5Ek-UpCuGrMfURueCTxIQoG-_saMCQ0mnP_CcRtzNMNMml4zxReJjxAmP …
```
=> Fix buff stages on Scorching Ray, Frost Shield, and Sigil of Power

src/Classes/TimelessJewelListControl.lua, src/Data/Uniques/Special/Generated.lua, src/Data/Uniques/jewel.lua
The PR changes the way veiled mods are chosen for auto-generated uniques. Also adds support for an additional weapon type to fix Cane of Kulemak missing some mods
Remove Master specific mods from Paradoxica that are no longer possible to roll
```
(Prefix) Always Hits
(Prefix) Bleed On Hit Gained
(Prefix) Cold Added As Chaos
(Prefix) Fire Added As Chaos
(Prefix) Lightning Added As Chaos
(Prefix) Physical Added As Chaos
```
The mod pool for Kane of Kulemak contained many 1 handed mods and master specific mods that were not possible to roll
```
(Prefix) Always Hits
(Prefix) Chaos Damage And Chaos Skill Duration
(Prefix) Cold Damage And Base Chance To Freeze
(Prefix) Fire Damage And Chance To Ignite
(Prefix) Lightning Damage And Chance To Shock
(Prefix) Minion Damage And Minion Maximum Life …
```
=> Fix veiled mod pool on autogenerated unique weapons

src/Modules/CalcOffence.lua
When using Ballista totems in a bleed build with multiple totems. The Bleed stack potential was not taking into account the number of maximum active totems and was instead only using the attack rate of 1 totem
Also hooks into the config to allow people to set the number of totems attacking
- Test Build with range of totems
- Test builds with no totems to make sure they don't break
https://pobb.in/1OlRQukcLrpc
=> Fix Bleed DPS when using multiple totems

src/Data/Skills/act_dex.lua, src/Export/Skills/act_dex.txt
Fixes #4655.
Anomalous grace wasn't giving sap, brittle and scorch avoidance.
- Avoidance now appears in calcs tab as expected.
https://pobb.in/PKCTOaKmWIsY
=> Fix alternate ailments not working with anomalous grace.

src/Export/spec.lua
updates spec.lua to include better fields for timeless passives, these arnt actually used by PoB for the moment, but can be used to help generate timeless jewels, and are needed if PoB moves away from a LUT approach to determining what timeless jewels do
=> Update timeless schema

src/Modules/CalcDefence.lua
Fixes #4240.
The calculations for armour mitigations are very vague/confusing and have minimal breakdowns.
Spell suppression isn't included if it is guaranteed against spells.
Certain breakdown sections don't hide when irrelevant.
Generalised and separate resistances and base damage reduction. This makes it much easier to handle large changes to this in the future and allowed explicit references to damage types to be removed.
With 100% chance spell suppresion will appear in breakdown and get removed from other eHP calculations.
Transcendence Armour Stacker + Phys to ele https://pobb.in/S8lGNPQF8Af8
Regular Build https://pobb.in/3XXONK_WLL2U
Enduring cry transcendence https://pobb.in/h5VqofF3ymJH
=> General improvements to "Damaging Hits" section and armour breakdown.

src/Modules/CalcOffence.lua, src/Modules/CalcPerform.lua, src/Modules/CalcSections.lua, src/Modules/ConfigOptions.lua
Remove bonechill config as it is always based on either enemy chill or
chilled ground/skitterbot chill. Its basically just boolean that scales
with chill effect on target so it cannot be different from actual chill
on enemy.
Fixes #3083
=> Always use configured or base chill for bonechill and remove bonechill config

src/Modules/CalcDefence.lua, src/Modules/CalcSections.lua, src/Modules/ModParser.lua
This will have merge conflicts with #4637
edit: conflicts solved
=> Apply spell suppress early if 100% and add gain on suppress

src/Classes/TreeTab.lua
Fixes #4691 and #1265 .
The bottom toolbar in the Tree tab does not always wrap to two lines at the right time.
Problem in #4691 was caused by the fact that the node power selector/button could be shown even if "Show node power" was not selected: 
but in the logic for wrapping, it was assumed that these two items where hidden.
This was caused by the fact that during initial load, the two items does not check if show node power is selected (this check is only when the box is clicked).
I added logic in the draw-function to make sure that the visibility was set correctly. I also changed the if-statement for wrapping since it did take into account "Node Power", but not take into account if "Compare" is clicked or not.
Load PoB both with or without "Show Node Power" selected in the build.
With …
=> Fix bottom bar wrapping in the tree tab

src/Modules/ModParser.lua
This correctly increases ailment effect, the only source of this is Fury of Nature which is a ranger special forbidden node
A bug I encountered was that Affliction charges do not seem to apply to base shock/chill from elementalist, as they are added after its calculated ([added here](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/ad39bdc61b752eca2d86ff3a28a97a35a1120b7a/src/Modules/CalcOffence.lua#L440-L450))
=> Add support for more Ailment effect

src/Modules/ModParser.lua
fixes heart of oak in ranger area
=> Condition used Life flask in the past 10 seconds

src/Modules/CalcPerform.lua
Fixes #4265 .
Currently reservation efficiency in the calcs tab shows the whole float value. I think a percentage rounded to two decimal places would be nicer.
-Check various aura setups
From issue:
```
eNrdXelz2ziW_zz6KziumqmkIjsEwDOTzJZ8u9tXLCfp9Id0gSRoMaZIhaR8ZKr_930PIClSl2kls7O7TndikcAD3oHfOwBSb__rYRxrdyLLozR5t0V29C1NJH4aRMnNu60P14fbztZ__bP39pIXo4twdxrFeOefvb-8lb9rsbgT8bstl21pBc9uRPGxIsX-AFITnhQjkSZn_GuaHaXBu63zNBFbmseTICqqT37M8_ycj8W7rU9R4Y-2NJ77Ign2ZtcPYjEWScHjKC-2tDGPkmHq34riKEunk3db9pZ2F4n7szSAtidnlxdX143Bo6Q5OEz-L28vY_4osmHBCy2Hv95tDUAG_Ebs8zH8DdR4PAVSxCAmMXcsh9Ct18s7DidCBHUHukMsw1nV9jotxBiu-pKZ62g8G0nfIY5FbJ0Saluma60icZmJgzAUfhHdib0sKvZGPPEbE2Y7-sqpbtL-bBoX0SSORDbrs6r98SJ5XV8jCx7vXw7rtky3mMl2iGFZIAhrfb-0mEluVcuTmyQqRHMI03Vtneg7rkUtgz3Rb84SXJ2auq7vUNekDnlqds8fdW8ax7C0mh1XcraXjr0oE …
```
=> Display reservation efficiency as percentage with two decimal places instead of a full float multiplier

src/Classes/GemSelectControl.lua, src/Classes/SkillsTab.lua
Fixes #4517  .
When hovering over the expanded alternate quality box there is a tooltip describing the effect of the quality when hovering with the mouse. When hovering over the "closed" box, there is no tooltip.
I removed the if-statement 
Modified the tooltipFunc in the qualityID to display the selected item if the listbox is closed.
https://pobb.in/ivbVY__36yk8
=> Display effect of active gem variant when mousing over the "Variant" drop-down selector and small behaviour change to gemSelectControl

src/Classes/Item.lua
Previously, PoB would automatically assign an armour's quality to 20% when importing it from the game, but that causes issues with the calculation of the base percentage value (since it calculates it as if the armour already had 20% quality).  This was only an issue with armours that had 0% quality.
- Copied a myriad of different armours from the trade site, comparing their values
```
Item Class: Body Armours
Rarity: Rare
Spirit Suit
Exquisite Leather
--------
Evasion Rating: 945 (augmented)
--------
Requirements:
Level: 67
Dex: 170
--------
Sockets: G 
--------
Item Level: 86
--------
+43 to Evasion Rating
14% increased Evasion Rating
+40% to Fire Resistance
+47% to Cold Resistance
8% increased Stun and Block Recovery
Attacks have +1.5% to Critical Strike Chance
+75 to maximum Life …
```
=> Imported items were getting incorrect variable percentages because of default quality coming in as 20

src/Modules/ModParser.lua
Ideally Tawhoa in Chieftain would be properly implemented, but I'd rather it be unparsed than parsed and adding a skill that does nothing.
=> Removes parsing off an unimplemented line

src/Modules/CalcDefence.lua, src/Modules/ModParser.lua
adds support for new juggernaut node 8% of armour applies to elemental damage, this also modifies the other 2 sources of "armour applies to", as we dont know the wording I used the wording from transcendence for now and am keeping this draft till we know the full wording
=> Jugg armour applies to ele damage

src/Classes/PassiveSpec.lua
Fixes error: When upconverting between trees, if a Mastery lost a mod from its pool that was allocated it would throw an error.
Crash on up conversion related to mastery index selections that went away but were allocated on the tree being upconverted.
- Using Reggie's 3.19 Tree upconvert the build link provided below (without this PR)
- See crash
- Add this PR, see that no crash, plus that Mastery allocation (`Reservation Mastery` -> `15% increased Mana Reservation Efficiency of Skills`) is no unallocated and Passive Skill Point is refunded.
https://pobb.in/SzBELuhWm4p0
=> Fix: Selected Mastery Tree Upconversion Error

src/Data/Uniques/gloves.lua, src/Data/Uniques/mace.lua, src/Data/Uniques/ring.lua, src/Data/Uniques/shield.lua, src/Data/Uniques/wand.lua
Matua Tupuna: perfect
Meginord's Vise: unsure affix order
Ming's Heart: perfect
Mokou's Embrace: attack and cast speed two affixes or one affix? it was 2. GGG patchnote " It also now has 25-40% increased Attack and Cast Speed while Ignited (both previously 20%)" ambigous
Mon'tregul's Grasp: perfect
Nycta's Lantern: perfect
Obliteration: perfect
Ondar's Clasp: perfect
=> [Kalandra] Batch of unique update. All remaining from M to O

src/Data/Uniques/amulet.lua, src/Data/Uniques/body.lua, src/Data/Uniques/boots.lua, src/Data/Uniques/bow.lua, src/Data/Uniques/gloves.lua, src/Data/Uniques/ring.lua, src/Data/Uniques/shield.lua
Tear of Purity: perfect
Thief's Torment: perfect
Thousand Ribbons: perfect
Thousand Teeth Temu: perfect
Thunderfist :unsure of affix position
Timeclasp: unsure of affix position
Vaal Caress: perfect
Victario's Flight: do we want to support "Quicksilver Flasks you Use also apply to nearby Allies"?
Warped Timepiece: unsure of affix position
Wheel of the Stormsail: unsure of affix position
Windscream: perfect
Wondertrap: perfect
Voltaxic Rift: should be perfect: Hits with this Weapon Shock Enemies as though dealing 300% more Damage already implemented, max effect of shock is implemented in https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/4750
Tavukai: perfect
=> [Kalandra]Batch of uniques update. All missing starting with T

src/Data/Uniques/amulet.lua, src/Data/Uniques/body.lua, src/Data/Uniques/boots.lua, src/Data/Uniques/bow.lua, src/Data/Uniques/gloves.lua, src/Data/Uniques/ring.lua, src/Data/Uniques/shield.lua, src/Data/Uniques/wand.lua, src/Modules/CalcPerform.lua, src/Modules/ModParser.lua
Ralakesh's Impatience: perfect
Rainbowstride: perfect
Rashkaldor's Patience: I think we dont support "always freeze, shock, ignite" mods
The Rat Cage: perfect
Rathpith Globe: perfect
Repentance: unsure of affix order
The Restless Ward: perfect
Retaliation Charm: do we want to support the two conditional mods? "10-20% chance to gain a Frenzy Charge on Hit while Blinded" and "10-20% chance to Blind Enemies on Hit with Attacks"
Reverberation Rod: unsure of affix order
Rigwald's Crest: spectral wolves atk will be pulled from ggpk? patchnotes states they attack faster now
Rise of the Phoenix: perfect
Roth's Reach: perfect
=> [Kalandra]Batch of uniques update. All missing starting with R

src/Data/Uniques/amulet.lua, src/Data/Uniques/body.lua, src/Data/Uniques/boots.lua, src/Data/Uniques/bow.lua, src/Data/Uniques/gloves.lua, src/Data/Uniques/ring.lua, src/Data/Uniques/shield.lua, src/Modules/ModParser.lua
Doedre's Tenure: perfect
Doomfletch: perfect
Dusktoe: perfect
Emperor's Vigilance: perfect
Foxshade: perfect. implemented "increased Movement Speed while on Full Life"
Giantsbane: implemented arrow pierce 2 additional targets; unsure affix order
Gruthkul's Pelt: perfect
The Highwayman: perfect
Hrimsorrow: perfect
Hyrri's Truth: unsure about affix order; bow attacks have culling strike implemented
Icetomb: perfect. I assume we won't support chance to Freeze Enemies for 1 second when Hit
The Ignomon: unsure about affix order
Infernal Mantle: perfect
Kaom's Sign: unsure about affix order
Kikazaru: perfect
Kintsugi: perect
Lightning Coil: perfect
Lochtonial Caress: perfect
=> [Kalandra] Batch of uniques update. All missingfrom D to L

src/Data/Uniques/flask.lua
Fixes #3728 .
1. The current version doesn't have the "50% increased Life Recovered" affix.
2. Wording fix from "increased Amount recovered" to "increased Life recovered
1. 
2.
1.
2.
=> Fix: Blood of the Karui Life recovered and wording 

src/Data/Uniques/amulet.lua, src/Data/Uniques/body.lua, src/Data/Uniques/boots.lua, src/Data/Uniques/gloves.lua, src/Data/Uniques/helmet.lua, src/Data/Uniques/wand.lua, src/Modules/CalcOffence.lua, src/Modules/ModParser.lua
Alberon's Warpath - Not 100% sure on mod wording or order for skeleton warriors permenant.
Allelopathy - Has item level bug due to multi base variant.
Ambu's Charge - Not 100% sure on mod ordering or wording.
The Anvil - 100% accurate
Apep's Rage - 100% accurate
Araku Tiki - Wording could be slighly different but all should be passed 
"on reaching Low Life" is treated as "while on low life" which isn't 100% accurate.
Asenath's Mark - 100% accurate
Ashcaller - Cover enemies in ash on hit could be in different spot but other sources seem to be at top of item.
Ashrend - 100% accurate
The Beast Fur Shawl - 100% accurate
Uses some mod passer changes from https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/4541
=> [Kalandra] Update batch 1 of uniques.

src/Data/Uniques/dagger.lua, src/Data/Uniques/mace.lua, src/Data/Uniques/sword.lua, src/Modules/ModParser.lua
Rigwald's Charge - Perfect
Marohi Erqi - Perfect
Heartbreaker - Perfect
Replica Heartbreaker - Perfect
Ephemeral Edge - Energy Blade mod location is unknown.
Clayshaper - Golem mod location is unknown
Brain Rattler - Perfect (unless mod rewording move mod).
=> [Kalandra] Update batch 2 of uniques.

src/Data/Uniques/axe.lua, src/Data/Uniques/belt.lua, src/Data/Uniques/body.lua, src/Data/Uniques/boots.lua, src/Data/Uniques/bow.lua, src/Data/Uniques/claw.lua, src/Data/Uniques/gloves.lua, src/Data/Uniques/helmet.lua, src/Data/Uniques/jewel.lua, src/Data/Uniques/mace.lua, src/Data/Uniques/quiver.lua, src/Data/Uniques/ring.lua, src/Data/Uniques/shield.lua, src/Data/Uniques/staff.lua, src/Data/Uniques/sword.lua, src/Data/Uniques/wand.lua
Fated Uniques can no longer be acquired.
The following unique items can no longer drop. May they rest in peace in Standard.
The Cheap Construction
Replica Cheap Construction
Chitus' Needle
Glitterdisc
Izaro's Dilemma
Izaro's Turmoil
Rotting Legion
Spine of the First Claimant
The Peregrine
Viper's Scales
Worldcarver
Verified correct by double checking all fated unquies. 
There were some fated uniques that were renamed or put into different drop pools and so are likely not considered fated anymore including "The Iron Fortress", "Atziri's Reflection" and "Winterweave".
=> [Kalandra] No longer obtainable uniques

src/Modules/CalcDefence.lua, src/Modules/ModParser.lua
Supports the new arrow dancing node.
https://pobb.in/CHrt82oluDbf
=> [Kalandra] Add support for Arrow Dancing

src/Data/Uniques/mace.lua
> The Replica Bitterdream Unique Sceptre now causes Socketed Gems to be Supported by Level 15 Immolate, Unbound Ailments, Ice Bite, Inspiration, and Innervate (previously either Level 1 or 10). This change affects existing items, though you will need to use a Divine Orb to fix the description on the item.
Old items mods no longer exist elementral peneration is likely to remain on the item at level 1 from this wording.
=> [Kalandra] Update replica bitterdream

src/Data/Uniques/ring.lua
Ngamahu's Sign - Perfect - now adds 20-25 to 30-35 Fire Damage to Spells and Attacks (previously 8-10 to 12-14).
=> [Kalandra] Update Ngamahu's Sign

src/Modules/ModParser.lua
Add support for piecewise parsing triple damage mods. Remove unnecessary explicit triple damage mod parser entry.
(The Magnate unique a after 3.19 Kalandra changes)
=> Add support for piecewise parsing triple damage mods.

src/Data/Uniques/mace.lua
https://twitter.com/pathofexile/status/1556027248834412544/photo/1
Variants have been removed due to legacy version being changed to the current version 
> The Bitterdream Unique Sceptre now causes Socketed Gems to be Supported by Level 15 Bonechill, Hypothermia, Ice Bite, Cold Penetration, Added Cold Damage, and Inspiration (previously either Level 1 or 10). This change affects existing items, though you will need to use a Divine Orb to fix the description on the item.
=> [Kalandra] update bitterdream

src/Classes/SkillSetListControl.lua
When removing it from table this causes crash when rebuilding skill set
dropdown.
Fixes #4771
Signed-off-by: Tomas Slusny <ts6234@intl.att.com>
- Create new build
- Add socket group to default skill set
- Copy default skillset and set its name to anything you want
- Try to delete default skillset
- Pob is no longer crashing
=> Set skillset to nil instead of removing it from table and reordering it

src/Data/Bases/sword.lua, src/Export/Bases/sword.txt
This makes PoB compliant with raw text item representation as provided on Path of Exile trade and for item imports. Thrusting swords got the same treatment as how we handle Rune Daggers.
This is also necessary for proper parameter scraping in the PoBTrader PR when comparing items pulled from the trade site and how we parse the raw item text.
=> Fix: Thrusting should be a base subType

src/Export/Main.lua, src/Export/spec.lua
Removes erroneous ``}`` in spec.lua and adds a sanity check in ``Main.lua`` to ensure ``self.datSources`` is actually a table before attempting to call ``next(...)`` on it.
=> Fix two export script errors

src/Export/Classes/Dat64File.lua
Fixes potentially mis-calculating size of data against row boundary when processing a DAT file of type String or Key
=> Fix: correct size for raw data read bounds checking

src/Data/LegionPassives.lua, src/Modules/Build.lua, src/Modules/CalcDefence.lua, src/Modules/ModParser.lua
Adds "1 Rage regenerated for every 25 Mana Regeneration per second" and "Mana Recovery from regeneration is not applied" wording
Displays Rage Regen beneath Mana Regen
- 2 Test Images with and without clarity to showcase the rage generation depends on total mana regen instead of the mana regeneration increase modifiers from now old chainbreaker 
https://pastebin.com/nNhMWJ2t
=> [Kalandra] Add new chainbreaker wording and displays Rage Regeneration

src/Modules/CalcOffence.lua, src/Modules/CalcPerform.lua, src/Modules/ConfigOptions.lua, src/Modules/ModParser.lua
Fixes #4143
The magnitude of guaranteed ailments was only using generic mods, which did not include any modifiers that came from skill gems or from conditionals such as highest damage type.
This PR does the following:
1) Highest damage type is no longer calculated, but rather a config option that appears when selecting a passive that adds that flag.
2) If such a passive is selected and the mainskill is able to hit and inflict its ailment, base value for that ailment uses the skill's modlist instead of the generic one. This is because all sources of base ailments are affected by generic mods which are included in the skillmodlist, but skills that hit also include the skill modifiers.
- The highest damage type requires selection in the config tab which could be missed.
- The skill gem …
=> Fix base ailment calcs

src/Modules/ModParser.lua
Fixes #4269
An issue was previously raised about Longshot not affecting spells. Based on the wording, it should. It looks like the rejection of the issue was based on outdated information from the fandom wiki, which I'm guessing originated from Far shot (which came before Longshot) indeed specifying that it only affects attacks.
=> Longshot affects all projectiles that hit

src/Classes/GemSelectControl.lua
I reverted two of the commits from Pull Request #4633
The solution to #4517 is still intact
But #863 is still not solved
The changes was meant to give a consistent behavior when clicking outside of a expanded selection box, or when pressing escape. 
There was still issues when the selected skill is filtered out (as described in #863) and it added some other issues (such as partial searches not updating to the full name in some occasions).
=> reverted changes to escape/onfocuslost in gemselectcontrol

src/Modules/ModParser.lua
It assumes that the pantheon is active when life flask is not active as simplified condition.
https://pobb.in/mc1bE8B0gDzM
=> Add support for Ryslatha life flask charge generation

src/Data/ModCache.lua, src/Data/SkillStatMap.lua, src/Data/Skills/other.lua, src/Export/Skills/other.txt, src/Modules/ModParser.lua
Fixes #744  .
Enabling Mistress of Sacrifice in the Necromancer ascendancy does not apply apply blood offering to the player when Bloodbond is equipped.
Blood offering was not shown, since the effect of Mistress of Sacrifice was set (in ModParser.lua) to affect:
"Bone Offering", "Flesh Offering", "Spirit Offering"
I added "Blood Offering" to the list and rebuilt ModCache.lua, this causes Blood Offering to be applied if Mistress of Sacrifice is enabled (and Bloodbond equipped)
https://pobb.in/neMBDf3Zut_4
=> Fix Blood offering stats not calculated #744

src/Modules/CalcPerform.lua, src/Modules/ConfigOptions.lua, src/Modules/ModParser.lua
This adds support for ``{ type = "Multiplier", actor = "enemy", var = "ChillEffect" }`` and ``{ type = "Multiplier", actor = "enemy", var = "ShockEffect" }`` in ``ModParser.lua``, and is intended to enable parsing for various modifiers that scale based off of the effective shock and/or chill value on enemies.
=> Add support for chill and shock effect mod parsing

src/Modules/CalcPerform.lua, src/Modules/ConfigOptions.lua
This is an improvement on #4770 that simply uses the current shock and chill values from the output directly, rather than trying to reconstruct their values and duplicate a bunch of code.
=> Improve shock and chill multipliers

src/Classes/CalcsTab.lua, src/Classes/ConfigTab.lua, src/Classes/ItemsTab.lua, src/Classes/PassiveSpec.lua, src/Classes/SkillsTab.lua, src/Classes/TreeTab.lua, src/Modules/Build.lua
Fixes #4619  and #2271
The Generate button in "Import/Export Build" ran buildMode:SaveDB, which runsdifferent Saver functions to generate the build XML . However it did not run the function that saves the file.
The problem is that the modFlags that are used to see if the build is unsaved is reset already in the Save functions. This causes the save button to be disabled, looking like the build is saved, but not really saving.
I created a new function to do the reset-logic and moved that to when buildMode:SaveDBFile is run (since that is when the file is actually saved).
I defined all the modFlags separately to reset in the reset function (i was initially thinking about creating a reset-function in each "saver"-class and iterating over them, however it does not cover all the cases and the …
=> Fix "save" on generate #4619

src/Modules/CalcPerform.lua
The upcoming Lightning Conduit skill has a new flag to add it's castTime to the trigger CD if it's triggered.
While we don't know what the actual stat name will be, we can implement the logic given that we will be treating it as a flag.
Sorry for the long flag name but it's basically what the skill image states.
```
["some_stat_name_we_will_get_from_ggpk"] = {
flag("SpellCastTimeAddedToCooldownIfTriggered"),
},
```
Tested with a CoC + Cyclone trigger setup. CoC has a default trigger rate of `0.15`
=> Feat: add support for Lightning Conduit's New Trigger Flag

src/Modules/CalcOffence.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4807.
Energy shield leech cap wasn't applied for imortal ambition.
- Turning on full life (enables immortal ambition) doesn't change the leech rate due to already being at leech cap.
https://pastebin.com/fB3ZVaJt
=> Restructure leech to apply cap later.

src/Modules/CalcOffence.lua, src/Modules/ConfigOptions.lua
This makes Elementalist Shaper of flames apply automatically again if fire is the highest, though this would allow for multiple to be the highest, the problem is the dropdown doesn't configure a default "does not deal damage" so making it an override rather than adding a condition would be a bit harder
also moves the config option to a more appropriate place
partial revert of #4790
=> Revert Elementalist highest ignite change

src/Modules/CalcDefence.lua, src/Modules/ConfigOptions.lua
This completes support for overwhelm from https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/4637 and fixes a couple other minor issues introduced.
This mod currently is only found on Steel-infused archnemis monsters at a value of 10%.
https://www.poewiki.net/wiki/Archnemesis_modifier
https://pobb.in/RObJNxM58-RU
=> Add support for enemy overwhelm and fixes some issues.

src/Modules/CalcOffence.lua
This adds burning and caustic ground to total dot dps, and thus also combined dps, to make it easier to see what your total dps is, as well as so it shows up as a damage boost for gem sorting
=> Add burning and caustic ground to total dot dps and thus also combined

src/Data/Skills/sup_str.lua, src/Export/Skills/sup_str.txt
This fix is very temporary, it should apply to shield crush but not any of the other shield skills
there is not shield ModFlag, but even if there was it would incorrectly apply it to the other shield skills
=> Temp multistrike fix for shield crush

src/Data/Skills/act_int.lua, src/Export/Skills/act_int.txt, src/Modules/CalcOffence.lua
Fixes scorching ray dps not stacking when a totem in fulldps with count higher than 1
fixes #2485 and #3126
=> Fix scorching ray not stacking as totems

src/Data/Skills/act_dex.lua, src/Export/Skills/act_dex.txt
Fixes #4791 .
Tornado ignored its inherent hit rate and instead behaved like a normal spell.
Now Tornado uses a fixed 0.25 second interval to apply damage. Cast speed does not scale its damage.
https://pastebin.com/y8C8NXjN
=> Fix: Tornado calculates DPS with hit rate instead of cast rate

src/Data/Uniques/Special/New.lua, src/Modules/CalcDefence.lua, src/Modules/ModParser.lua
Not working locally, but the code should make sense, so I'm opening this in the hope of it being a PEBKAC error.
=> [Kalandra] Kaoms spirit

src/Modules/CalcOffence.lua
The breakdown for shock needs to look at globalOutput for its maximum shock, not its output local to the current damage pass.
=> Use correct max shock in breakdown

src/Classes/TreeTab.lua, src/Modules/Build.lua
Fixes a bug where the timeless jewel socket index could become invalid between sessions.
This also removes some unnecessary timeless jewel data that was being saved to build XML but never actually used for anything.
=> Fix timeless jewel socket index bug

src/Modules/Main.lua
Unique items were missing their modifier range sliders if ``defaultItemAffixQuality`` was missing from ``Settings.xml``, as it was never initialized in ``main:Init()``, only loaded via ``main:LoadSettings(...)``, meaning any player that has never opened the Options menu would have those sliders default to ``nil`` and break.
=> Fix missing unique sliders

src/Classes/Item.lua
Various different items were being given ``{range:0.5}`` labels in their modifier line output even when there was nothing in that line that could possibly have a range value applied.
This PR simply checks for a valid range in that line before appending any range label.
The Lua pattern used is copied from ``ItemsTab.lua``: ``haveRange = modString:match("%(%-?[%d%.]+%-[%d%.]+%)"),``.
=> Filter out unused modifier line ranges

src/Data/Uniques/amulet.lua, src/Data/Uniques/boots.lua, src/Data/Uniques/helmet.lua, src/Data/Uniques/ring.lua
> Added the following notes:
>  The Replica Alberon's Warpath Unique Boots now has +13-19% to Chaos Resistance (previously +9-12%), and 25% increased 
Movement Speed (previously 20%). Existing versions of this unique can be updated to these new values using a Divine Orb.
> The Replica Leer Cast Unique Helmet now has +60-100 to maximum Life (previously +20-30) and +60-100 to maximum Mana (previously +20-30). Existing versions of this unique can be updated to these new values using a Divine Orb.
> The Replica Doedre's Damning Unique Ring now grants +5-20 to Intelligence (previously 5-10), +5-20% to all Elemental Resistances (previously +5%), and +5-20 Mana gained on Kill (previously +5). Existing versions of this item can be updated to the new values with a Divine Orb.
> The Replica Hyrri's …
=> August 18th Replica Adjustment

src/Classes/TimelessJewelListControl.lua, src/Classes/TreeTab.lua, src/Modules/Build.lua
This PR shifts ``timelessData`` to a system where only the ``id`` for each relevant table is stored in build XML and on load each relevant structure is rebuilt. This fixes #4889.
This also adds keystone names to generated timeless jewel variants, to match the changes in #4882.
=> Rebuild all timeless data on load

src/Data/Uniques/flask.lua, src/Data/Uniques/ring.lua
Fixes #4891.
Ventor's Gamble and Soul Ripper were using outdated/custom formatting like this:
``+(-25 to 50)% to Fire Resistance``
.. instead of the formatting every other item uses:
``+(-25-50)% to Fire Resistance``
This appears to be a relic from 6+ years ago when Openarl was working on PoB &mdash; back then **everything** was formatted this way: cfdb7c0198f6e96e1b065979309a7473f3bd7d4b.
This will not automatically update existing items in builds, meaning if someone has Ventor's Gamble or Soul Ripper still in their build with the outdated formatting, the Lua pattern used in #4836 will still prevent that slider from working as ``{range:x}`` is never applied to them. Do we want to add support for these outdated items?
=> Update Ventor's Gamble and Soul RIpper

src/Data/Skills/act_int.lua, src/Export/Skills/act_int.txt
This fixes issues with unleash and other future dps multiplier being overridden by by the skills internal dps multiplier
fixes #4867
does not fix bladeblast, but that likely needs a rework to use a count box instead of its preset number of stages anyway
=> Apply dps multiplier fix to spells

src/Modules/CalcOffence.lua
Gain on kill was not correctly combined for attacks, and thus did not show up
=> Fix gain on kill not working for attacks

src/Data/Uniques/helmet.lua
Old:
The Deidbell Unique Helmet no longer has 20% increased Melee Damage, or Adds 10 to 20 Physical Damage to Attacks. Instead, it now causes Skills which Exert an Attack to have a 20-30% chance to not count that Attack.
New:
The Deidbell Unique Helmet no longer has 20% increased Melee Damage, or Adds 10 to 20 Physical Damage to Attacks. Instead, it now causes Skills which Exert an Attack to have a 20-40% chance to not count that Attack.
The wording of this mod is also extremly like to be different in the final version.
=> Deidbell patch note change.

src/Classes/TreeTab.lua
In the timeless jewel search UI, given the following desired nodes:
```
vaal_notable_curse_1, 777, 0, 111
vaal_small_aura_effect, 888, 0, 999
```
.. switching from ``vaal_notable_curse_1`` to ``vaal_small_aura_effect`` in the "search for node" dropdown list will incorrectly copy data from ``vaal_notable_curse_1`` to ``vaal_small_aura_effect``, setting the minimum node weight for both desired nodes to 111.
``controls.nodeSlider.val``, ``controls.nodeSlider2.val``, and ``controls.nodeSlider3.val`` were not properly constrained to valid slider values &mdash; they need to be between 0 and 1 (inclusive); 500 for example is not a valid position for ``controls.nodeSlider3.val``, that value is 500 times bigger than the maximum that slider can represent.
This PR fixes both issues.
=> Fix timeless jewel node weight bugs

src/Classes/SkillsTab.lua
Selecting a vaal skill from the drop down also enabled the normal version but does not update the checkbox for it.
- Test a few vaal skills
https://user-images.githubusercontent.com/91493239/185367217-a092a9e6-163a-4688-91b5-2ac3d129a880.mp4
=> Fix checbox not updating when selecting vaal skills

src/Classes/TreeTab.lua
This fixes a regression I accidentally caused in #4893. The code restored is required to correctly load the saved socket timeless jewel socket.
=> Fix regression in #4893

src/Classes/Item.lua, src/Classes/ItemsTab.lua, src/Export/Scripts/mods.lua
needs feedback and testing
thoughts on changes
currently I have exarch/eater show up based on base type of the item, do I want to swap this to checking for influence instead?
I also have exarch/eater check if a mod of their type already exists in the list and replace that instead, do I want to add logic for clearing implicits to it/synth if wrong type? (eg if none of the implicts are exarch/eater wipe the list and add the mod
same with synth, if none are synth replace the whole list?) if so do I want this to be default logic, or add a button, or add a toggle?
how do I sort exarch/eater mods, they are a mess atm, it would help if I could combine groups similar to how affixes work but I am not sure its possible for this kinda addition, I could add slots for implicit on crafted items that …
=> Add eldritch implicits

src/Export/Scripts/mods.lua
fix export of watchers eye, was being skipped because not a synth/delve mod of "GenerationType 3"
=> fix watchers eye export

src/Classes/Item.lua
The grand spectrum multiplier was missing for minions.
Fixes #4964
Showcasing both minion and player mods working simultaneously
https://pobb.in/6TICxfDd81dt
=> Fix parsing of Grand Spectrum for minions

src/Data/Skills/act_int.lua, src/Export/Skills/act_int.txt
Frostblink's stats `ice_dash_cooldown_recovery_per_nearby_normal_or_magic_enemy` and `ice_dash_cooldown_recovery_per_nearby_rare_or_unique_enemy` were unhandled. This fixes that and uses Configuration pane's `Is the enemy a Boss?` to set appropriate condition to determine which CDR to use.
=> Add support for Frostblink CDR from nearby enemy

src/Modules/CalcOffence.lua, src/Modules/CalcSections.lua
Aura effect on Self from Sublime Vision, Purposeful Harbinger or from the Aura mastery were not counting towards the value in the Aura effect breakdown
This PR does have the issue where if you have something like Generosity linked to a skill, it correctly does not add  aura effect on self mods to the total aura effect value but it does still show them in the breakdown table. I'm not sure how to have them disappear from the table when the aura does not affect the player
=> Fix Aura effect on Self not counting towards Aura effect breakdown

src/Data/Uniques/ring.lua, src/Modules/ConfigOptions.lua, src/Modules/ModParser.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4943.
Stormfire wasn't updated or shock mod supported.
The legacy mod doesn't exist anymore so support wasn't added for that.
- Changing number of shocked enemies changes to damage up to the cap.
https://pobb.in/Lp6GjQSfj18x
=> Update stormfire and add support for mod.

src/Modules/CalcSetup.lua
Fixes #4873 .
In rare cases when two identical radius jewels overlapped on a node the radius jewel function (jewel mods) would be applied to that node twice.
Note that this pr focuses the the mentioned issue. There may be other edge cases that i was not able to find where the same solution may need to be applied. Only rad.type == "other" jewels are checked for duplicates and the name of the jewel is used for the check so this may cause issues with radius jewels that have different function but the same name (kind of like [Combat Focus](https://www.poewiki.net/wiki/Combat_Focus_(Crimson_Jewel))). I was not able to find any currently existing jewels that are both of type other and have other versions with different functionality under the same name but this may change in the future.
- Test …
=> FIX: fix jewels applying to the same node twice if overlapping

src/Classes/CalcsTab.lua
These values were changed in
3f5e2a6d865044f72ca9425f19a37a2f3c6977d8 but this part of the code wasnt
updated, this causes crash when importing builds.
Fixes #4951 
https://pobb.in/u/thedeathbeam/occu-poison-hexblast-starter
This issue does not happen on release but happens on dev branch
=> Use Life/EnergyShieldRegenRecovery for power builder

src/Modules/CalcOffence.lua
caustic and burning ground were applying caps incorrectly, such that you would get an incorrect final dps, also these dont need to be capped like this because total dot dps is capped so showing how much burning/caustic ground you have can be useful
=> Remove Dot Ground incorrect caps

src/Modules/Build.lua, src/Modules/ModParser.lua
Fixes #4895 .
This adds support for the line "Nearby Allies have Culling Strike" found on Kingmaker and displays the CullingDPS in build.lua
https://pobb.in/OFv7I1Qf4weN
=> Add support for "nearby allies have culling strike"

src/Modules/CalcOffence.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4839.
Previously energy blade was recalculated using iterative wording this lead to the stacking to extreme damage in full dps.
This gets the energy blade base stats each time.
https://pobb.in/txiSPk0YgskI
=> Fix energy blade applying each iteration.

src/Modules/CalcDefence.lua, src/Modules/CalcPerform.lua, src/Modules/CalcSections.lua
Correctly applies elusive as avoid hits rather than avoid damage from hits, and applies projectile avoidance latter if theres no damage type specific avoidnaces
=> Improve avoidance calcs

src/Modules/ModParser.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5058
- Using a spell no longer gets lucky damage
- Using an attack still gets lucky damage
=> Fix Lucky Attack Damage Applying to spells

src/Modules/ModParser.lua
Fixes [#5044](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5044) .
The `"(%d+)%% increased ice spear critical strike chance in second form"` mod applies only to the second skill part of ice spear: "Second Form, 1 Projectile.". It should apply to both: "Second Form, 1 Projectile." and "Second Form, All Projectiles." skill part 2 and 4.
=> Fix ice spear enchant not applying to all projectiles skill part.

src/Data/Skills/sup_str.lua, src/Export/Skills/sup_str.txt
We were explicitly mentioning shield crush as it is the only multistrikable shield skill. Shields don't seem to be an attack type. But use a RequiresShield skilltype to display this. This swaps the explict shield crush condtion but doesn't elegantly resolve this issue. as it still requires two lines.
https://pobb.in/fpdwOfPuAyFI
=> Generalise Multistrike implemenation for shields.

src/Modules/CalcPerform.lua
Increasing the stages of blood sacrament doesn't increase the life reserved.
- Increasing the stages increases the reservation.
https://poe.ninja/pob/Bvt
=> Add reservation scaling with stages for blood sacrament

src/Data/Skills/act_str.lua, src/Export/Skills/act_str.txt
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/1540
These stats don't apply globally or atleast shouldn't.
=> Fix some stats with bloodstorm conditionals being considered a buff

src/Modules/CalcPerform.lua
Fixes #5020 .
Shock effect currently does not apply to shocked ground created by the player.
=> Shock effect should apply to shocked ground

src/Modules/CalcOffence.lua
crash when checking support gems if the skill can be a trap/mine, this also fixes action speed with them and cooldown tvalue
=> fix crash for pvp when checking support gems

src/Modules/CalcOffence.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5017
When brittle range was lowered from 15->6 the formula was also rescaled ingame but not in pob.
=> Update Brittle Formula

src/Classes/ImportTab.lua
For many users, after loading the account's characters, there are many characters to select from. They then have to select the current league to reduce the clutter.
Set the "All" league last so that for most people the current league
where they play in should be the first option in the dropdown.
- In the import menu, select an account and click Start
- The League dropdown should default to Kalandra (for most softcore players I guess)
- The character dropdown will only contain characters from the current (Kalandra) league
=> Re-order the leagues dropdown in the import menu

src/Modules/CalcPerform.lua
Fixes #5000  .
The issue is that mods from active skill gems are not in env.modDB and thus the Sum function returns 0. Looking for ailment mods in env.player.mainSkill.baseSkillModList resolves the issue but i'm not sure if it's the correct approach to solving this.
=> FIX: Ailement mods from skill active skill gems not applying

src/Modules/CalcDefence.lua, src/Modules/ModParser.lua
Fixes #4999 Partially.
Implement some currently unsupported reflected mods.
- Hexes you inflict have -19 to maximum Doom 
    Implemented
- Adds 7 to 13 Cold Damage to Hits against you per Frenzy Charge
- The rest of generic damage against you
    Implemented with piecewise parsing using the "against you" key word.
    Might potentially cause issues in the future if "against you" is used in different contexts.
- #% of Physical Attack Damage Leeched by Enemy as Life
-  15% of Damage Leeched by Enemy as Life while Focused
- The rest of other leech types
    Not implemented.
    I don't see where it would be used currently as enemy calculations are limited and  i'm not sure how to implement cleanly.
- Curse Enemies with Flammability on Hit, with 44% reduced Effect
    Implemented
- …
=> Implement parsing for some currently unsupported reflected mods.

src/Modules/CalcDefence.lua
Fixes #3418
In the Calcs > Energy Shield > Total breakdown, global source were missing their increased/reduced multiplier. The Total number is correct, it just was missing the information in the breakdown.
- Imported build with global ES sources and increased ES modifiers
- Opened the Energy Shield > Total breakdown on the Calcs tab
https://pastebin.com/YXgXm3JY
Or just allocate Foresight
=> Show Increased Global Energy Shield on Calcs

src/Modules/ConfigOptions.lua
Brittle config option description was using the old +15% value and Scorch effect config was using "Brittle" as source
=> Update Brittle config description to new value and fix Scorch source

src/Modules/CalcSetup.lua
Reverts PathOfBuildingCommunity/PathOfBuilding#4948
The solution seems to cause more issues than it solves. Likely it is not how it works in game. More testing is needed.
=> Revert "FIX: fix jewels applying to the same node twice if overlapping"

src/Classes/ImportTab.lua
When copying a link from Google Sheets (in htmlview) it copies a redirect link instead of the direct link. We can simply parse the link out of the google redirect url just like we do for YouTube.
- Tested loading builds copied from google sheets.
https://www.google.com/url?q=https://pobb.in/Ol4vcjp6bBun&sa=D&source=editors
=> Add google sheets parsing to build import

src/Classes/ModDB.lua
Fixes ##5053 .
Nodes coming from timeless jewels do not have their source property set. When running sum on a modDB with such a mod and the source property set in the cfg causes a match call to be called on nil which causes the crash.
=> FIX crash when generating fall back weights caused by missing source

src/Modules/CalcActiveSkill.lua
Fixes #4851
In some cases support gems that required skillTypes flags added by support gems lower in the socket group would not work.
- Test some gem setups
=> Fix support gems not adding their flags if they themselves require a flag added by a support gem lower in the supportList

src/Classes/TradeQuery.lua
Fixes #5025 .
Settings were not saved to settings.xml after entering a new session id making it non persistent.
The session id can be saved using the save button in the options popup as a workaround.
=> Fix POESESSID not saving to settings.xml when pressing the save button in the "Change session ID" popup.

src/Modules/ModParser.lua
Due to a mistake in ModParser rebuilding ModCache and then typing something in the unique items search bar would cause a crash. This fixes it.
=> Fix mistake in ModParser.

src/Data/Skills/act_int.lua, src/Export/Skills/act_int.txt
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5098
#% more Damage with Hits per 5% Shock Effect on Enemy
Should have the hit tag.
=> Fix Lightning Conduit More damaging with hits missing hit tag.

src/Classes/GemSelectControl.lua, src/Classes/SkillsTab.lua
Fixes #4630.
This replaces the old gem level selection and "match gem level to character" level options with a dropdown selection that has four options:
- Normal Maximum: All gems default to their highest valid non-corrupted gem level.
- Corrupted Maximum: Normal gems default to their highest valid corrupted gem level. Awakened gems default to their highest valid non-corrupted gem level.
- Awakened Maximum: All gems default to their highest valid corrupted gem level.
- Match Character Level: All gems default to their highest valid non-corrupted gem level that your character meets the level requirement for. This hides gems with a minimum level requirement above your character level, preventing them from showing up in the dropdown list.
=> Extend default gem level functionality

src/Classes/ConfigTab.lua
Instead highlight them in red to let user know its an error.
Closes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4407
Closes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4468
Closes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/1945
Closes #4841 
https://pobb.in/jJf-KmAMp90k
=> Do not hide config options that are configured without source

src/Modules/CalcPerform.lua, src/Modules/ConfigOptions.lua, src/Modules/ModParser.lua
Fixes #5077.
Soul Ascension should limit Soul Eater stacks to 50
- Equip Soul Ascension
- Configure Soul Eater stack to above 50
https://pobb.in/lqwVyRxzuw_m
=> Add support for Soul Eater stack limit

src/Modules/CalcOffence.lua
The list of sample Brittle effects was using values fitting pre-nerf range
https://pobb.in/GS_k1kWBScby
=> Adjust sample Brittle effects

src/Modules/CalcDefence.lua
Missing resistance calculations were using totem's maximum resistance instead of player's
- Equip Replica Nebulis
- Get fire resist close to max
- Observe amount of increased fire damage
https://pobb.in/go2n11_TF6bs
=> Fix missing elemental resist calculation

src/Modules/ModParser.lua
Fixes #5057 .
Mods scaled by Devotion can apply to minions but they have none of it. Should be looking at player's Devotion instead.
[https://pobb.in/Pav3tyBwN_5_](https://pobb.in/Pav3tyBwN_5_)
=> Fix Devotion not working with minion mods

src/Modules/ModParser.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/99
Global energy shield implicit with wording "#% increased maximum energy shield" was applying locally even though all instances of this mod apply globally.
- Switching between nothing, the local variant and global see appropriate energy shield changes.
https://pobb.in/IpxDlGdH-nb6
=> Fix global energy shield being mistaken for local

src/Modules/CalcDefence.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5111
Currently pob treats resistances as floats and rounds when displaying. Game truncates floats.
=> Truncate resistances.

src/Modules/ConfigOptions.lua
changed mana cost to skill cost
Fixes # .
-
-
-
=> Correct Fanaticism tooltip

src/Modules/CalcSections.lua
DoT Multi for poison wasn't showing up as a breakdown for spells
- Add any physical or chaos spell
- Add herald of agony
- Add some DoT multi
```bash
eNq1W9132jgWf-78FRyeKdjYGJhDZg4hpGE2NGxI292nHmEL0ERYjC0noX_9Xkk2GIIcG3vz0Brrful3P3Ql24M_3za09oKDkDD_qm42jXoN-y7ziL-6qn97uv3cq__5x2-DGeLrh-V1RKgY-eO3TwN5XaP4BVPgq9c4ClaYf08kWT9B0hb5fI2ZP0V_s-AL867qX5mP67UF8j3Ck18uRWH4FW3wVX3uAnO9hkIX-97ocF8RbhDx58x9xvxLwKKtVPtC8OuUeUAzmc4eHp9SSomfVgo2fxrMKNrhYM4Rr4Xwz1V9CFNHK3xHOIhCNAI5pmM0DcPoGabRMe166zzjfIuxt-dp68hA8DGl2XRSf10d3yzA4-USu5y84FFA-GiNfBfvpTg6vqK004hysqUEBykLOzqOJ8YRvZnND_N2HJhPzzDMbqdt2dl87ICxoaP8Qfj6mgJgF2gRvJOVTzi-gHnGSMj8NKPTa9p25wN6tIHoOUBnOc1eP8u-92oss91s93NDmGa1O03H0no3ohRSNU2vRX3ENgviH4Oe065hgNHDUsXqI_JIFB7Q0Eb3FPloxMJ0zulI78kSH5FqJzGe56N7BI_loxRmznAAtYjnYxDGFmKINcyxy6DeFdFRhCU1j8uUXcA5nl …
```
=> Add missing poison multiplier breakdown for spells

src/Modules/ConfigOptions.lua
3.20 removes reduced curse effect on bosses.
=> Remove curse effect on bosses

src/Classes/SkillsTab.lua
I think this issue is best described with pictures.
=> Fix inconsistent display of additional quality and gem levels in skill group tooltip

src/Modules/ModParser.lua
Like with grasping vines "inflicts" mean it also has 100% chance to poison with all damage
Fixes # .
-
-
-
=> Glorious Madness poison chance mod

src/Classes/ItemDBControl.lua, src/Data/Uniques/amulet.lua, src/Data/Uniques/axe.lua, src/Data/Uniques/belt.lua, src/Data/Uniques/body.lua, src/Data/Uniques/bow.lua, src/Data/Uniques/claw.lua, src/Data/Uniques/dagger.lua, src/Data/Uniques/gloves.lua, src/Data/Uniques/helmet.lua, src/Data/Uniques/jewel.lua, src/Data/Uniques/mace.lua, src/Data/Uniques/ring.lua, src/Data/Uniques/shield.lua, src/Data/Uniques/staff.lua, src/Data/Uniques/sword.lua
Implemented all changes to existing unique item mods and availability from the 3.20 patch notes.
- Manual inspection through item tab
=> Update existing uniques for 3.20

src/Modules/CalcOffence.lua, src/Modules/CalcPerform.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5097
Negative charges and conversion is being fixed in the next update.
The self curse bug wasn't a problem in PoB
> Fixed a bug where having negative values of damage conversion would grant extra damage of the initial damage type.
> Fixed a bug that allowed the total value of minimum power, frenzy or endurance charges to go negative, which could cause skills to act as if players had more charges than they actually did.
- Negative charges result in zero discharge damage
- Negative Conversion doesn't increase damage
https://pobb.in/tpMBPfRjjSiK
=> Fix conversion and charges being negative

src/Modules/Main.lua
When editing an item from the rare template list, implicit mods were not affected by catalysts
- Used the crystal belt rare template
- Added Tempering Catalyst
- Noticed the energy shield implicit changed properly after my fix
N/A, import from the rare template list instead
=> Fix rare templates not getting implicit mod tags

src/Classes/Item.lua
Fixes #5109
The short-cut to strip a repeat of the base name of an item appear as a modifier when copy/pasting from trade website was incorrectly implemented to short-circuit entry into the subsequent `if` block by setting `specName` to a value.
This caused certain parameters of quirky items like a Fishing Rod, Timeless Jewel or Ring of subtype Ring (basically any item with a subType equal to the main base item Type) to not be properly initalized.
- Verified creation of all items reported in Issue #5109 without error
- Verified that copy/paste from PoE Tradesite does not treat the subType of the item as a modifier.
Just make any build and Item -> `Craft item...` OR `Create Custom...`
Would throw error when mousing over `Base` of Fishing Rod
=> Fix: crash on crafting certain quirky items

src/Classes/TradeQueryRequests.lua
PoB Trader Related: 
When you click the `Price item` button with a correct URL it no longer worked. We used to fetch search parameters over HTML to circumvent extra API calls for query fetching, but this is now disallowed. As a result, this code switches us back to using the GET API standard. However, apparently the GET API standard has also changed to force league name specification now being required. 
This PR fixes both of these so we have the ability to retrieve items given a URL now.
=> Fix: Fetching Search Query via HTML is no longer allowed

src/Classes/TradeQueryGenerator.lua
PoB Trader: Base and Abyss jewel subTypes were not properly limit weighted search to those item category subtypes. This fixes it.
Fixes: #5024, #4896
For tree sockets that can take any type of jewel, the itemCategory was not being reset based on user set query specification options.
Needed to add the last 5 lines (if .. end) here:
```
elseif slot.slotName:find("Jewel") ~= nil then
itemCategoryQueryStr = "jewel"
itemCategory = options.jewelType .. "Jewel"
if itemCategory == "AbyssJewel" then
itemCategoryQueryStr = "jewel.abyss"
elseif itemCategory == "BaseJewel" then
itemCategoryQueryStr = "jewel.base"
end
```
to force the search to only consider a more limited subType pool.
- Did the searches and opened up website based filters to very the proper item category was specified …
=> Fix: Weighted Search Category fix Jewels

src/Classes/PassiveSpec.lua, src/Modules/CalcSetup.lua
Fixes #4850 
When building a new tree for removing/adding nodes it was not updating the values of the multipliers for notables, masteries, or mastery types.
Mastery types are reworked to count how many are allocated per type instead of simply being true, while notables and masteries are simply adjusted so they properly include a potential new/removed node in the count.
- Checked elementalist Bastion of Elements (allocated notable), unclear if it works since it does not show up on tooltip regardless, but it still adds to calc tab as it should
- Attribute masteries (allocated mastery), works great
- Trickster Polymath, works great, though recover on kill does not show up on tooltip
(With no other masteries selected)
(With Polymath and no other masteries)
(With no other masteries selected) …
=> Passive count multipliers preview on nodes

src/Classes/ItemsTab.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5108
When clicking the implicit button it would crash on jewels due to there being no actual mods.
=> Fix jewel implict button crashing

src/Classes/TradeQueryRequests.lua
This makes `Find item` work better and makes SC/HC temporary leagues work in a future-proof manner.
=> Fix: Over-write URL league name to use League Dropdown Selection

src/Classes/Item.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5096
Corrupted abyss jewels can now have 6 affixes. This pr updates that.
Note that if a user manually removes the corrupted tag the extra suffix and prefix mods are not removed.
=> Update affix limit for corrupted abyss jewels.

src/Classes/ItemsTab.lua
Spacing and anchoring was funky in this file, so I fixed it.
=> Fix UI spacing on Items tab

src/Classes/TradeQuery.lua, src/Classes/TradeQueryRequests.lua
in Trader for a give item slot, when we parse the URL we take out the `league` and `queryId` using a regex. Then we use the League DropDown selection when we do the fetch and search for items (which might not match the league regex'ed out) by concatenating together a new URL. 
However, the URL in the control element for that item slot does not get updated with the League drop down. 
This leads to the return of the `Price item` function potentially having different item returns then if you CTRL+click the URL to bring it up in the web-browser.
This PR fixes this, by auto-correcting the URL in the control element for that item slot to the correct league name so when it is CTRL+clicked it results in the same query against the same league.
=> Fix: make URL update to league selection

src/Classes/ItemsTab.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4942
The box had to much space before and wouldn't resize
Prior
=> Fix Item Corruptor having empty space

src/Modules/CalcDefence.lua, src/Modules/CalcSections.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5163.
According to the mentioned issue life recharge ([Eternal Youth](https://www.poewiki.net/wiki/Eternal_Youth)) is not affected by "You cannot Recharge or Regenerate Energy Shield" from [Shavronne's Revelation](https://www.poewiki.net/wiki/Shavronne%27s_Revelation).
This pr stops "You cannot Recharge or Regenerate Energy Shield" from removing life recharge.
=> Fix shav's revelation removing life recharge.

src/Data/Uniques/ring.lua, src/Modules/ModParser.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5112
Implements 'Your Blessing Skills are Disabled' for Essence Worm.
=> Implement 'Your Blessing Skills are Disabled' for Essence Worm

src/Data/SkillStatMap.lua, src/Data/Skills/act_dex.lua, src/Data/Skills/spectre.lua, src/Data/Spectres.lua, src/Export/Minions/Spectres.txt, src/Export/Skills/act_dex.txt, src/Export/Skills/spectre.txt
Fixes #4987.
Ref #4558 
Add spectre Deadly Tarantula https://poedb.tw/us/Deadly_Tarantula#DeadlyTarantulaSpiderThornViperStrikeFlickerStrike
-
-
-
https://pastebin.com/NL0RcVfz
=> Add spectre Deadly Tarantula

spec/System/TestDefence_spec.lua, src/Modules/CalcDefence.lua
Fixes #1645 ~~#4847~~.
Max hit taken should not depend on enemy damage. This aims to fix that by changing how max hit is calculated.
- Flat damage reduction (i.e. endurance charges) checked at low, mid and extreme values
- Overwhelm checked at low, mid and extreme values
- Damage taken as checked at low, mid and extreme values
- Transcendence and/or unbreakable checked
- Damage taken-as was kept in mind
- Math?
- Spreadsheets
https://pobb.in/KAH_0AClx7EI (stolen from poe ninja)
Damage reduction for reported phys max hit (88% taken as phys = 108690) results in 2608539 / (2608539 + 5 * 108690) = 0.82758 reduction. Plugging that back in for damage received from physical portion of the "max hit" results in 108690 * 0.17242 * 1.1 (Aspect of Carnage) = 20614 damage. This character has total …
=> Max hit improvement

src/Classes/ItemsTab.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5166
This adds a preview of item mod when hovering over selection like how cluster jewel notables currently behave
It uses default item affix percent to determine what to preview for ranges.
=> Added Mod Tooltip

src/Data/Skills/act_int.lua, src/Data/Skills/other.lua, src/Export/Skills/act_int.txt, src/Export/Skills/other.txt, src/Modules/CalcDefence.lua, src/Modules/CalcOffence.lua, src/Modules/CalcPerform.lua
> We've also changed Monster-inflicted sources of Chill and Shock effect to be multiplicative, rather than additive. This is to allow sources of reduced effect of ailments to be able to stack, and provide immunity.
~This might not effect all instances of these interactions and just the one stated in the patch notes related to players with 100% reduced shock/chill that we currently didn't support (enemy effect) and so might need to be updated / changed based upon further information.~
This now currently assumes only enemy application behaves multiplicatively and we are not impacted by this when attacking enemies.
=> Convert all ailment effect to assume enemy and self behave multiplicativly

src/Classes/ImportTab.lua
yep, I'm back with more newbie-friendly character import tab UX
nobody that left their characters tab private knows how to unhide their characters
- hid my characters tab
- tried to import from my account
- clicked the new "Privacy Settings" button
n/a
=> Add button to go to privacy settings

src/Data/Skills/act_str.lua, src/Export/Skills/act_str.txt, src/Modules/Build.lua, src/Modules/CalcOffence.lua, src/Modules/CalcSections.lua, src/Modules/ModParser.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5001
- Increased Attack speed per trauma
- Skill Duration
- Extra repeats not gaining trauma
- Helm Enchant
- Server Tick Rate Cap
- Breakdown
- #5069
e.g. this build is missing a lot of effective duration https://pobb.in/Q6FSp4NO2LIF
- #5070 
- The calculated value is assuming you have reached maximum steady state of taruma this can take over a minute in many cases due to the iterative growth from attack speed per trauma. The build code starts at 8 APS but is effectivly 2 APS due to awakened multistrike this means assuming no growth 400 seconds to reach the ~800 stacks estimated by the build but due to the attack speed per it will be significantly less and only reaches the attack speed cap near the end of the ramp …
=> Calculate maximum sustainable trauma stacks

src/Classes/ModList.lua, src/Modules/CalcOffence.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5007.
Mana cost was applying to mana and divine blessing wasn't handled correctly with blood magic or life as extra cost of mana
There are some really weird rounding issues. That I don't know how to fix so these calculations are often off by one when gem mana multipliers are in play.
Lifetap / Petrified Blood Implemenation could be converted to be more generic as if in the future we saw mana to es conversion or similar.
- Total cost only applies for the resource with no conversions
- % cost correctly still doesn't apply for bloodmagic divine blessing
- flat aura and extra mana cost behave correctly
- Blood magic still overrides life as extra cost of mana.
https://pastebin.com/tft9bXja
Petrified Blood
Blood Magic
=> Fix Skill Costs

src/Modules/CalcOffence.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4962.
Arcanist brand is a support and active gem. It support gems and gives them the brand skill flag.
We use this to tell if a skill is a brand for calculations.
This means a skill can have the brand flag and not be a brand.
This changes it so we pick brands by name instead.
- Adding orb of stroms and arcanist brand no longer crashes and brand stuff no longer appears on triggered skill.
https://pobb.in/deAifYYBO5VR
=> Fix arcanist brand giving brand skill flag to gems breaking stuff.

src/Data/Skills/act_dex.lua, src/Data/Skills/act_int.lua, src/Export/Skills/act_dex.txt, src/Export/Skills/act_int.txt, src/Modules/ConfigOptions.lua
=> Fix dangling enemy radius config

src/Modules/CalcPerform.lua, src/Modules/ModParser.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5076
Implements new mod (as of the launch of 3.19 kalandra) on [Victario's Flight](https://www.poewiki.net/wiki/Victario%27s_Flight):
`Quicksilver Flasks you Use also apply to nearby Allies`
Minor tweaks to the way flasks are handled.
Potential TODO:
- Generalize application of flask mods to better support future party play tab.
=> Implement  "Quicksilver Flasks you Use also apply to nearby Allies" mod on Victario's Flight

src/Modules/CalcDefence.lua, src/Modules/CalcSetup.lua, src/Modules/ModParser.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5087
The spell suppression from dagger mastery applied regardless of equipped weapon. This pr also prevents radius jewels from applying to mastery nodes.
=> Fix dagger mastery and radius jewels applying to masteries.

src/Modules/CalcActiveSkill.lua, src/Modules/CalcSetup.lua, src/Modules/Calcs.lua
Fixes #4631 .
Overrides were not propagating through the call to initEnv in copyActiveSkill which was causing issues with dps comparison. Fixing that issues caused dps comparison to only work correctly when an odd number of skills was selected for full fps due to flask toggles being applied multiple times to a single env instance because of caching in calcs.calcFullDPS. Toggling flasks only when a cached env is not present seems to resolve the issue.
- Tested with and without The Saviour and got expected behavior
=> Fix dps comparison not working correctly when using the saviour and using overrides

src/Data/Uniques/axe.lua, src/Data/Uniques/staff.lua
> Yes, it has been moved back to Uber Atziri. Pledge of Hands has moved from Uber Atziri to regular Atziri.
=> Update pledge of hands and atzri's disfavour sources

src/Modules/CalcDefence.lua, src/Modules/CalcSections.lua, src/Modules/Data.lua
Fixes: #4992 #5161 #5178
For reference: https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4993
eHP has breakpoints. This means when you have very low hits to death eHP won't change on moderate increases in health or damage reduction e.g. 20%.
This also refactors how infinite eHP is determined and when to stop. This is done by checking the current damage mitigated and if over a threshold declare infinite hits. Stopping is now determined if passing over a threshold of maximum number of iterations (number of times running the damage mitigation passes).
Guard skills were causing weird breakpointing behaviour due to iteration multiplier causing effective differences between speedup iterations and iteration multiplier iterations. This removes this from guard skill as the logic …
=> Remove overkill damage and fix some bugs in eHP

src/Data/Uniques/Special/race.lua, src/Data/Uniques/claw.lua, src/Data/Uniques/sword.lua, src/Modules/ModParser.lua
GGG is updating "Gain # Resource per enemy hit by attacks" to "Grants # Resource per enemy hit"
=> Update Grants wording change on uniuqes and support

src/Modules/Calcs.lua, src/Modules/ConfigOptions.lua
While calculating Full DPS for `Absolution` the `Count` increases not only the number of minions (which is correct) but also multiplies the dps of the spell itself (which is incorrect)
1. Add `Absolution` active skill
2. Increase count
3. Check `Include in Full DPS`
[https://pobb.in/-aL0wEIoqGe_](https://pobb.in/-aL0wEIoqGe_)
=> Fix Absolution spell hit counted multiple times in the Total DPS

src/Modules/BuildSiteTools.lua
Our current pob link matching pattern is not covering some pobb.in URLs.
This PR fixes the pattern to cover urlsafe base64 characters (used by pobb.in)
Following link is currently unloadable via the "Open" button on the page (using pob protocol link)
https://pobb.in/-bUISrt3agGa
=> Fix parsing for some pobb.in links

spec/System/TestItemMods_spec.lua
=> Fix typo breaking tests

src/Modules/CalcPerform.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5162 .
Scorching ray applies exposure when at maximum stages. https://github.com/PathOfBuildingCommunity/PathOfBuilding/commit/222a1c53e97dd4edc9997213d689e9b682f4d055 moved the logic that calculates maximum sustainable stages for a few skills to after buffs/debuffs are applied to take arcane surge cast speed buff into consideration causing mods that use stage count as thresholds to not be added when they should.
```LUA
mod("FireExposure", "BASE", nil, 0, 0, { type = "GlobalEffect", effectType = "Debuff", effectName = "Fire Exposure", effectCond = "ScorchingRayMaxStages" }),
```
=> Fix Scorching Ray exposure not applying when using calculate maximum sustainable stages option.

.github/workflows/spellcheck.yml
Current state:  proof of concept / testing / review.
Questions / suggestions / comments welcome.
* Automatically run [cspell-action](https://github.com/streetsidesoftware/cspell-action) on `pull-requests` made to `dev`.
* Trigger manually to fully check a branch/tag/SHA.
* Use `cspell` config/dictionary files from a secondary repo (temporarily [nightblade/pob-dict](https://github.com/Nightblade/pob-dict)).
I've been regularly running `cspell` locally on the `dev` branch and at the moment it reports zero spelling issues.  Keen observers will notice there are still ... a few.  These *should* only be pre-existing errors that are yet to be addressed, GGG errors, or idiomatic PoE/PoB words.
Further detail available upon request.
=> Add spell check github action

src/Classes/TradeQueryGenerator.lua
This is a "safety" fix. It definitely doesn't hurt have it and probably will fix a few niche edge-cases where one of the output parameters perhaps doesn't exist.
=> Fix: add 'or 0' in case of 'nil' in compDPS

src/Classes/TradeQuery.lua, src/Classes/TradeQueryGenerator.lua
Pobtrader has a few issues on the latest release:
- Query options modal has overlapping items
- League selection is broken which affects the poe.ninja currency rate fetching (looks like they changed stuff with the introduction of Ruthless)
Also included an option to limit prices on calculated weighted search, a bunch of people were asking for it.
=> Add price cap to the trading tool and fix several bugs in it

src/Data/Skills/act_str.lua, src/Export/Skills/act_str.txt
Based on info I got from GGG, this corrects the radius values for: `Sweep` and `Frozen Sweep` (which are not the same apparently)
=> Fix: Use actual Sweep Radii

src/Modules/CalcOffence.lua
Fixes #5293
Traps had their own cooldown variable which needs to be used to take into account cooldown in mana cost per second calcs.
=> Use trap cooldown for mana cost per second

src/Data/Skills/minion.lua, src/Export/Skills/minion.txt
Fixes #5302
The minion instability minion skill is missing the area flag causing it to ignore area supports such as conc effect after merging https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/4628
- Test minion instability with skills listed on [wiki](https://www.poewiki.net/wiki/Minion_Instability)
- Tested with spell echo
=> FIX: add area flag to Minion Instability.

src/Modules/CalcOffence.lua, src/Modules/CalcSetup.lua, src/Modules/ModParser.lua
Finishes #5279 by adding critical strike cap as a mod that can be altered.
- Tested with new Winds of Fate unique
- Tested lucky crits, works as intended (50% becomes 75%)
https://pobb.in/nktSfdXr-NLo
=> Add modifiable critical strike chance cap

src/Classes/TradeQueryGenerator.lua
minWeight is now calculated correctly for builds that use TotalDot or CombinedAvg DPS
=> Fix an issue where the trade generator wasn't generating a sufficient minimum weight for some builds

src/Classes/ImportTab.lua
Fixes #5287 .
Fetching private characters stopped working because the Import Tab used the session ID from the user's settings, but didn't save it there if you were importing for the first time.
- Imported a private character
=> Fix Import Tab not properly using your session ID

src/Modules/CalcOffence.lua
Resolves: https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5268
There are still significant rounding issues after this patch relating to auras and divine blessing. Pet Blood is likely still problematic.
This fixes mana cost for skill afaik but other costs are incorrect still, see https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5268 for a longer disscussion
=> Improve accuracy of mana cost calculations

src/Modules/ModParser.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5254
Introduced in https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5014 + https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5203
The mod parser would crash if it tried to parse "Spells Triggered this way have 150% more Cost +1 to Strength and Dexterity"
This is because it would automatically generate strength and dex as table of 3 for the value then it would try and append cost to the table. 
This ensure it needs to explicitly match a valid resource and extends / simplifies the creation of these tables.
=> Fix crash related to base cost mod parsing and overhual resource relating parsing to be more generic

src/Modules/CalcSetup.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5258 https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4982
preDamageFunc and other similar gem functions were getting called twice between comparisons, it uses previous dpsMultiplier in calculations this resulted in the numbers being ^2 on the second calculation always making every node seem more powerful then it should. This fixes it so it always wiped so this assumption / reuse of stacking multipliers is fine.
https://pobb.in/TfhBprEH-M3D
=> Fix fullDPS having signifcantly larger numbers on second pass

src/Modules/Data.lua
#5029 renamed "Barrage" to "Barrage Support"
Importing characters with Barrage Support socketed dropped the gem
Imported my own character (raylu/rayluWand)
This doesn't affect XML imports
=> Fix importing characters with barrage support

src/Classes/ItemsTab.lua
Fixes #5332 .
Previous spacing fixes set the wrong anchor in portrait mode
- Load PoB in portrait mode
- Add sockets to verify spacing
See issue
=> Fix spacing issue in portrait mode on the Items tab

src/Modules/CalcOffence.lua
Fixes #5348
Both the floor and the + 1 from the initial fuse needs to be after the multiplication by totem.
- Checked max fuses before and after.
https://pobb.in/rM83GxVFJvew
=> Correct max fuse calculation

src/Classes/EditControl.lua
Highlighting and clicking on the protected session ID values resulted in some odd behavior.  This PR also disables copying/cutting from the protected fields
- Messed around with various selection and caret placement in the session ID fields to ensure they looked correct
N/A
Clicked in, hovering
Clicked in
Highlighting
Clicked in, hovering
Clicked in
Highlighting
=> Fix odd edit behavior with protected inputs

src/Classes/ImportTab.lua
Previously, session IDs were saved separately per account you were importing from.  When we changed to saving a single session ID globally, we broke that functionality.  This PR restores the original functionality, but (currently) at the cost of persisting the trade session ID to the import tab.  This is because we don't necessary know if the user is importing from the same account they've used to populate the trade modal
- Create another PoE account
- Set the characters on your main account to private
- Import characters from your main account
- Import characters from your new account
- You should be able to see characters from both accounts and freely swap between them without having to re-enter your session ID
N/A
=> Fix session IDs not saving separately per imported account

src/Modules/ModParser.lua
Add missing mod for Rotting Legion unique
- Ensure mod works
https://pastebin.com/8SMK5FtV
Damage with default zombie limit (6)
Elemental damage reduction with an additional +1 zombie amulet equipped
=> Add rotting legion missing zombie mod

src/Data/Skills/sup_int.lua, src/Export/Skills/sup_int.txt
The Divergent quality is only meant to scale ailment effect and it seems I accidently forgot to remove the "More" damage line when copying the stat from the previous stat
=> Fix Divergent Cast while Channeling adding "More" damage

src/Classes/TradeQueryGenerator.lua
Use default item affix quality rather than 50%
This generates different searches on 0%, 50% and 100% but only minorly different
https://www.pathofexile.com/trade/search/Standard/X94aJB7iP
https://www.pathofexile.com/trade/search/Standard/vDk5blMCE
main difference is order of mods with only slight change to the weights, thus tends to find similar items anyway
=> Use default item affix quality rather than 50%

src/Classes/TradeQuery.lua, src/Classes/TradeQueryGenerator.lua, src/Classes/TradeQueryRequests.lua
Fixes #5365, #5331, #5316
- Improved error handling so that we don't get generic "Invalid POESESSID" errors for unrelated problems. This is not a fix for the issues reported in [#5316](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5316) but we shall get more descriptive errors for similar problems. (Those problems are caused by the active skill not having an actionable DPS value, which is already being worked on by other PRs)
- Added more URL encoding to fix problems caused by league names with spaces. [#5365](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5365)
- Added error handling to catch invalid generator outputs earlier. When the generator cannot find any useful filters to search for, it shouldn't attempt to create a search query.
=> Improve item pricer error handling

src/Modules/ModParser.lua
Adding mod for 'when you warcry' for Mutewind Pennant unique
Have Mutewind Pennant equipped, see a 20% increased cast speed and movement speed with Spark when if you've warcried recently is enabled
https://pastebin.com/dNH8K3Lz
=> Add support for mutewind pennant warcry mod

src/Data/Skills/act_dex.lua, src/Export/Skills/act_dex.txt
Phantasmal reave was capped at 8 stacks, even though it can go beyond that with enough quality.
- Ensured phantasmal reave can go beyond 8 stacks with appropriate quality
https://pastebin.com/rZvUpV1s
=> Add support for Phantasmal Reave radius

src/Data/Skills/act_dex.lua, src/Data/Skills/act_int.lua, src/Export/Skills/act_dex.txt, src/Export/Skills/act_int.txt
Number of waves that seismic (and lightning spire) traps produce does not line up with the number calculated when duration is rounded up to the nearest server tick. Also the reported stats required for next/previous breakpoints when near these rounding points would be incorrect.
- In-game character seismic trap releases 20 waves. With duration rounding it would be calculated 21.02 waves; 20.99 without.
https://pobb.in/WZ-m9QK64sC2
=> Adjusted seismic and spire wave count calculation

src/Modules/CalcOffence.lua, src/Modules/ModParser.lua
Add support for Sandstorm Visage main hand crit -> spell base crit
- Ensured crit chance is not affected when main hand is empty
- Base chance is set to main hand's critical strike chance when a weapon is equipped in the main hand
- Base chance is increased with b
https://pastebin.com/KVyAewuk
=> Add support for Sandstorm Visage crit mod

src/Modules/CalcOffence.lua
Critical cull chance was using just critical strike chance before. This should be based on hit rate because we are measuring DPS rather than a single hit.
Ensure that culling critical strikes take hit rate into account
- Ensured DPS increases on Assassin's Ambush and Assassinate and Marylene's Fallacy
- Ensured max cull is used appropriately with critical culling strike (with Culling Strike gem and Slayer's Headsman)
https://pastebin.com/C97LKLP7
=> Critical cull chance uses hit rate

src/Modules/CalcOffence.lua
Unarmed sets crit to zero when using sandstorm visage
=> Fix unarmed sandstorm visage not setting spell crit to zero

src/Data/Uniques/ring.lua
Fix Heartbound Loop unique modifier missing physical tag
The mod `%d+ Physical Damage taken on Minion Death` on the Heartbound Loop does not have a physical modifier.
When adding the Noxious catalyst in PoB the base value 350 does not change to 420 as expected.
- Create Heartbound Loop unique ring from template.
- Apply Noxious catalyst 
- Verify self hit value changes from 350 to 420 (nice) -> OK
- Import existing ring from game.
- Verify the value is 420 and not 504 -> OK
https://pobb.in/_XqWDTDoH_nN
=> Add missing physical tag to Heartbound Loop

src/Data/Uniques/helmet.lua, src/Modules/ModParser.lua
3.20.1 updated the wording
https://www.pathofexile.com/trade/search/Sanctum/eaawnewtL
=> Update wording on sandstorm visage

src/Classes/Item.lua
3.20.1 The line has changed from "Relic Unique" to "Foil Unique" due to introduction of unique relics.
We parse this line into the rarity variable so the text "Relic Unique" isn't stored in the .xml so this means everything works expect old items codes.
New foil uniques https://www.pathofexile.com/trade/search/Sanctum/1qDlSg
XML save
=> Fix relic uniques mod parsing changing

src/Classes/ItemDBControl.lua, src/Classes/ItemsTab.lua, src/Classes/NotableDBControl.lua
Sort by full dps didn't work on anoints and wasn't appearing it other locations it should be.
https://pobb.in/Y8eF_tUmwnPH
=> Fix sort by full dps not working on anoints and appearing in other locations

src/Modules/ConfigOptions.lua
Introduced in https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5185
There are two config options which do the same thing when looking at this I realised the values weren't updated previously so I updated them and thought this options wasn't already present so accidentality made another instead of updating the original
=> Remove duplicate bleed / poison config option

src/Modules/CalcPerform.lua
Fixes #5242
PoB would not take into account +Flask effect when calculating silver flask onslaught. This change adds a check when calculating onslaught and adds flask effect to the equation if a silver flask is active.
- Checked +flask effect increases relevant stats when a normal or magic silver flask is active
- Checked other flasks are not adding relevant onslaught stats when active
- Checked onslaught from sources that is not a silver flask is not benefited 
- Checked if onslaught is allocated from a non silver flask source and a silver flask that the +flask effect is still properly active
https://pobb.in/MdzvxLSfWxbr
=> +Flask effect works with silver flask

src/Launch.lua, src/Modules/Common.lua
This fixes the profiler trying to be loaded if it is not present and provides warning in console if dev mode is setup.
=> Fix profiler crashing

spec/System/TestItemMods_spec.lua, src/Modules/CalcSetup.lua
Due to not having a access to ring base type it was set as an iron ring in the meantime. This mean it didn't work when it was updated to the "Ring" base type.
=> Fix kalandra's touch not working

src/Data/Uniques/amulet.lua
Legacy variant doesn't exist so no longer worth having as 3.19 change affected existing items. https://www.poewiki.net/wiki/Crystallised_Omniscience
=> Remove legacy Crystalised Omniscience that no longer exists

src/Modules/CalcOffence.lua
Fixes #5377 .
According to this https://www.reddit.com/r/pathofexile/comments/hb61x6/exert_shockwave_support/fv79etg/?context=3 a triggered attack cannot be exerted because it's not performed by "you".
=> FIX: exerts applying to triggered skills

src/Modules/CalcDefence.lua, src/Modules/CalcOffence.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5455
If you had a cowl of thermophile and an annihilating light you could get more than 100% reduced resistance which is capped at 100% ingame or 0% based upon how we implemented it.
=> Fix more than 100% reduced resistances causing negative res to turn postive.

src/Data/Uniques/jewel.lua
3.15: The modifier on the Militant Faith Timeless Jewel that  grants 1% reduced Cost of Skills per 10 Devotion can no longer roll.  Existing items with this modifier have had this replaced with a modifier that grants 1% reduced Mana Cost of Skills per 10 Devotion.
=> Militant Faith update skill cost to mana cost

src/Modules/CalcSetup.lua, src/Modules/ConfigOptions.lua
Fixes #5443 .
Kalandra's touch ignored it's own mods causing  implicit mods to not apply. Also prevents from reflecting the other ring if it's also Kalandra's touch.
=> Fix Implicit mods on Kalandra's Touch not applying.

src/Classes/PassiveTreeView.lua
When Timeless Jewels are added from the "Find Timeless Jewel" section, the jewel number and name are added to the end of the jewel title. This broke the exact match we were doing to display the jewel radius sprite
=> Fix Timeless Jewel tree radius effect not appearing sometimes

src/Modules/Main.lua
Introduced in https://github.com/PathOfBuildingCommunity/PathOfBuilding/commit/8c0ba3e2ef08b0c1e301cfff1e26fdd8ba2cfa27
Mod Cache was not used for tree and item database loading.
=> Fix modCache not being used during startup causing long loading times

src/Data/Uniques/jewel.lua
Every other variant is properly named.
=> Add name to elemental damage Grand Spectrum variant

src/Classes/SkillsTab.lua
Fixes #5476.
https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/4724 changed the way default gem levels are handled. This caused gemInstance.level to be assigned a string (`self.defaultGemLevel`) instead of an int.
=> Fix: Deleting gem level causing a crash

src/Classes/TradeQuery.lua, src/Classes/TradeQueryGenerator.lua, src/Classes/TradeQueryRequests.lua
Fixes #5472 
Some PoB Trader modules are causing memory leaks by leaving OnFrame references behind in the main module.
This fix converts OnFrame subscription to be named, allowing the new class instantiation to replace the old OnFrame reference.
This doesn't solve the dangling reference problem altogether, we still hold one reference each to these classes which potentially prevents GC. Still, reserving memory for only one object is better than a growing memory leak.
Feel free to override if you implement proper lifecycle management.
=> Fix Trader memoryleak caused by OnFrame functions

spec/System/TestDefence_spec.lua, src/Modules/CalcDefence.lua
Fixes #4446
Enemy damage taken multipliers (such as Enfeeble) should apply to max hit. Currently they do not.
- Open pob
- Enable enfeeble
- See max hit change
https://pobb.in/_vySTol7cCuS
=> Apply enemy damage multiplier to max hit taken

src/Classes/Item.lua
Fixes #5363 .
Current best match algorithm only checks the length of the prefix to determine match "quality". This causes issues such as with the item in the mentioned issue. This pr changes the algorithm to use match length instead.
All stock pob items seem to work fine with this change as well as items from random builds i had laying around but it could do with some more testing.
=> Fix issue parsing certain item bases

src/Classes/ListControl.lua, src/Classes/TimelessJewelListControl.lua, src/Classes/TreeTab.lua
Fixes #5401.
Currently, there is no easy way to access the Trade website to find the Timeless Jewels from the resultant list in the Timeless Jewel Finder. This PR creates a button to search the website for jewels in bulk.
- I have interacted with the Timeless Jewel Finder
- I have tested this in a working build.
- I have accessed the URLs created by the Searcher to ensure they are correct under Rakiata
=> add search trade for timeless jewels

src/Classes/TimelessJewelListControl.lua, src/Classes/TreeTab.lua
Adds the option to search by any conqueror, this is useful for trade site as otherwise it will only search for the specific conqueror selected, if you add a jewel to build it will default to the first conqueror, this also fixes the issue where conqueror selection no longer worked
example search with all 3 conquerors: https://www.pathofexile.com/trade/search/Sanctum/5Bgg4q2Ta
=> Add option for any conqueror for Timeless jewels search

src/Data/Skills/minion.lua, src/Export/Scripts/skills.lua, src/Export/Skills/minion.txt
Fixes #5313 .
Some minion skills seem to be missing flags and it's causing issues after https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/4628 was merged.
~~Still need to check that the template minion.txt file does not cause issues with exports.~~
=> Add missing skilltype tags to minion skills.

src/Classes/ListControl.lua
Fixes #5503 .
In #5402 and the restructuring of the Select code, logic was not updated to return true or false properly in SelectIndex.
- Replicated the issue in #5503
- Updated the code and ensured the issue is no longer occurring.
- Tested #5402 features to ensure it did not break any functionality there.
```
https://pobb.in/zK6l9BLGRgph
```
=> Fix issue with SelectIndex not returning proper value

src/Modules/CalcPerform.lua, src/Modules/ModParser.lua
- Move wither effect check after self cast curse condition is set so it properly applies
- Remove the hit flag from parsed mod
Balance of Terror wither on hit is not working currently because the condition is checked too late and the hit flag prevents the config option from showing.
- Open pob using balance of terror
- Check if wither config is present
- Check if wither stacks change damage
- Check if removing balance of terror removes wither config and stacks
https://pobb.in/3P0Ms0CMxrvo
=> Fix wither on hit from balance of terror

src/Classes/TradeQuery.lua, src/Classes/TradeQueryRequests.lua, src/Modules/Common.lua
This PR adds a new working mode called "No Session Mode" to offer features that don't depend on POESESSID availability such as weighted search generation.
Current implementation uses trade API to create the search URL from the generated weighted search query. This step makes POESESSID mandatory. The new implementation creates search URLs with generated query passed as URL parameter (like `/search?q={query:...`) when POESESSID is not available.
This should allow people who don't want to provide their POESESSID to still use the search generation feature.
Feel free to suggest improvements over the current description/title.
Added an alternative league fetch method to get available leagues including the private ones but require POESESSID.
This method is only available in "Session Mode" and we …
=> PoB Trader: No Session Mode, private leagues support and some more

src/Classes/TradeQuery.lua, src/Classes/TradeQueryRequests.lua
Current PoE trade API returns at most 10k results per search which are not guaranteed to include the highest-scored items.
There were attempts to improve the situation by calculating a better min weight limit but that doesn't guarantee a solution.
This PR proposes an iterative approach to solve the issue. The new method keeps repeating the search as long as the results come out capped. Each time, the weight of the highest-rated item of the previous search is used as the new min weight limit.
During my tests, these recursive searches are usually completed within 2 steps. So I added an arbitrary limit of 5 max recursions to prevent any potential runaways.
The new method is only utilized in the search triggered by the query generator for now. Didn't want to make it default for URL-based …
=> PoB Trader: add self adjusting weighted search to prevent result clipping

src/Classes/TradeQuery.lua
This PR adds two features:
Current price-related sorting modes depend upon poe.ninja data which is only available for PC leagues. And it's patchy at the league start even for those.
This PR has some modifications to allow the pricing process to fail gracefully regardless of realm or league and fall back to default DPS sorting if the price data is inadequate.
Poe.ninja price fetching is also disabled for console leagues, preventing redundant requests.
Currently, changing the sorting mode does nothing for already-fetched items and only affects future searches. This felt like a poor user experience since we provide no feedback on the sorting switch interaction.
This PR changes the behavior of the switch dropdown to also update the sorting order of already fetched items.
=> PoB Trader: add dynamic sorting and fall back from price sorting

src/Modules/CalcPerform.lua
Based on this comment the effect is not being applied (and it indeed isnt). If flask is magic it should apply.
https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5407#issuecomment-1369218523
- Allocate master alchemist
- Verify onslaught effect is increased
https://pobb.in/u/thedeathbeam/pf-poison-scourge-arrow
=> Support magic utility flask effect for silver flasks

src/Data/Skills/other.lua, src/Export/Skills/other.txt
Fixes #5548 
Blood Sacrament has a "More" multiplier per 10% of reserved life. Before the fix, it also had a "More" per stage, effectively giving it "more per reserved life per stage", resulting in the first screenshot below
- updated the file and checked the same build
https://pastebin.com/eexWGaQz
=> removing per stage multiplier on blood sacrament

src/Classes/ControlHost.lua
Fixes #5540 .
When dragging an item it was possible to chance focus to a different control causing the item that was being dragged to get stuck to the cursor. 
The item being stuck to the cursor would cause a crash when the focus was switched back to the control from which the item was dragged from or if the item was dropped in to a slot or deleted.
This pr disables the ability to change focus to a different control when the original control is handling item dragging.
=> Fix crash caused by item stuck on cursor when dragging

src/Modules/CalcPerform.lua
Fixes #5545.
The socketGroup property seems to be missing at times. Making as draft as i'd like to investigate further.
The issue seems to be that if a socket group without an active skill is selected the default melee attack is added to active skills and it doesn't have the socketGroup property, causing the crash.
=> FIX: whispering ice crash if triggered

src/Modules/Main.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5541
Introduced in https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5499
If you had a radius jewel in shared items and reload it would crash wiping settings.
This loads shared items in the place where it was loaded before #5499 this avoids the crash due to missing tree info.
- Add timeless jewel to shared items
- Restart and not crash
=> Fix Crash caused by loading shared items too early

src/Modules/CalcDefence.lua
Fixes #5527 .
#5089 fixed spell spell suppression mastery by adding weaponCfg but i did not add the cfg for Acrobatics spell suppression to spell dodge conversion calculation. This pr fixes that.
=> Fix spell supression mastery not working with Acrobatics.

src/Data/Skills/minion.lua, src/Export/Skills/minion.txt
Fixes #5635 .
Caused by #4628 . For some reason some minion skills are missing some skillType tags. This is not the first time this has popped up after #4628 was merged but i'm not sure how to fix it for good.
=> Add missing "Damage" tag to some golem skills

src/Data/Skills/act_str.lua, src/Export/Skills/act_str.txt
Fixes #5609 .
According to the creator of the issue the aura from the vaal version of smite overrides the normal version instead of stacking with it.
=> Stop Vaal Smite and Smite auras from stacking

src/Data/Uniques/sword.lua, src/Modules/CalcOffence.lua, src/Modules/ModParser.lua
The Goddess Unleashed Wording Update
Add support for enemies ***** by you have
Add support for poison / bleed parsing on self
Add parsing support for "if you've used a mana flask in the past 10 seconds"
Point Blank / Far shot distance update per discord.
=> Goddess Unleashed Wording Update, Support enemies x by you have, bleeed/poison on self, used mana in last 10 seconds and distanceRamp updates

src/Classes/ImportTab.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5649
Voidborn Foils have a frameType of 10 instead of regular relics 9 this causes them not to be imported via character importer.
=> Fix imported characters missing voidborn uniques

src/Classes/Item.lua
Fixes  #5580.
Does not save foil colour type, but does assign foil to the item
=> Change foil search to correctly assign foil to voidborn uniques

src/Modules/ModParser.lua
Fixes #5272 .
Adds skillType restriction to minion overwhelm mastery to prevent it from applying to minion spells.
=> Fix Minion overwhelm mastery missing skillType restriction

src/Data/Uniques/amulet.lua, src/Data/Uniques/boots.lua, src/Data/Uniques/helmet.lua, src/Data/Uniques/jewel.lua, src/Data/Uniques/mace.lua, src/Data/Uniques/ring.lua, src/Data/Uniques/shield.lua, src/Data/Uniques/staff.lua, src/Data/Uniques/sword.lua, src/Data/Uniques/wand.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5686
Replica Hyrri's Truth was missing the 3rd variant this adds that alongside update the last variant to always be "Variant: Current" and updating oak
=> Fixing Missing Variant on replica hyrri's truth

src/Modules/ConfigOptions.lua
Fixes #5657 .
Due the the `count` input being used for Blood Charges input box on the config tab setting the blood charge count to 0 resulted in defaulting to max blood charges.
There also seem to be some off by 1 issues with count boxes due to
https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/dec27c9472fc94965921c9662f7ff7d421fe4e9b/src/Classes/EditControl.lua#L692-L695
But not sure how to properly fix.
=> Allow setting Blood Charges to 0

.github/workflows/spellcheck.yml
(Spell checker workflow change)
`extra-en-dict.txt` will include English words not found in CSpell's dictionaries and not specific to PoE or PoB.
=> add support for `extra-en-dict.txt`

src/Data/Global.lua
Fixes https://www.reddit.com/r/pathofexile/comments/114iwvv/comment/j8wtil6/?utm_source=share&utm_medium=web2x&context=3
Strong Arm had fishing tag when it shouldn't
https://pobb.in/rGt2T3q_9b7j
=> Avoid Collison of weapon melee and fishing rod.

src/Modules/CalcOffence.lua, src/Modules/CalcSections.lua, src/Modules/ModParser.lua
This just allows PoB to parse "%inc dps" or "%more dps", mainly for use in custom mods, common practice is to add a custom mod as "more damage" but that incorrectly messes with certain ailment calculations, so just allowing the user to straight input dps
=> Allow for custom mod dps multiplier

src/Classes/ImportTab.lua, src/Modules/Build.lua, src/Modules/ConfigOptions.lua
Fixes #5587 .
When importing a new character act 10 resistance penalty was applied but the selector in config tab was still set to "none". This pr implements estimation of the resistance penalty on import based on existing player progression estimation code and changes the selector to default to act 10 penalty to better reflect the default applied values.
=> Estimate resistance penalty on import

src/Modules/CalcOffence.lua, src/Modules/CalcPerform.lua, src/Modules/ModParser.lua
Mirages are not "you" and thus can deal damage even when Ancestral Bond is allocated. 
Note that i'm not sure if General's cry is handled correctly here. The damage values may be inflated due to not being handled like Mirage archer.
=> FIX: Ancestral Bond - mirage interaction.

src/Classes/ItemDBControl.lua
This hides race uniques by default, they still show up if you change source to any/unobtainable
The alternate method would have been to mess with league source so that race events are hidden for "any league"
=> Make race uniques not show up as obtainable

src/Modules/CalcBreakdown.lua, src/Modules/CalcOffence.lua
Refactor all resistance calculations in CalcOffence.lua into one place so that it has consistent caps, overrides and such. Also fix effective DPS section for dot breakdowns as it was mostly just broken.
Fixes #5647.
Enemy resistance calculation logic was duplicated many times and most of the time it had some parts (mostly lower cap) missing. 
- Checked each changed calculation section in a build such that it is not immediately broken and has the intended caps
https://pobb.in/vWgZRyaRbKEs
=> More consistent enemy resistance calculations

src/Classes/PassiveSpec.lua
Fixes #5626 .
The `SetNodeDistanceToClassStart` function is currently allowed to path through class start nodes as well as other types of not relevant nodes. This pr prevents that from happening.
=> Prevent pathing through class starts for Split Personality

src/Modules/ConfigOptions.lua, src/Modules/ModParser.lua
Currently the rampage config is always present, this makes it hidden behind a flag and adds support for rampage sources.
- Open new build
- See rampage config missing
- Add rampage unique
- Verify rampage config appears
https://pobb.in/ikepeLfdb4a4
=> Hide rampage config by default and propery parse rampage sources

src/Classes/ItemsTab.lua
Fixes #5592 .
Missing space caused a mismatch of socket names. 
https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/92f13a5d2b23cc2c14fff67c0a2cfd349cc1371d/src/Classes/ImportTab.lua#L916
https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/92f13a5d2b23cc2c14fff67c0a2cfd349cc1371d/src/Classes/ItemsTab.lua#L124
Items Tab:      `Weapon 2Swap Abyssal Socket 1`
Import code:  `Weapon 2 Swap Abyssal Socket 1`
Adding the space in ItemsTab makes the naming more in line with the names of other slots.
Note that this change may cause issues when loading some builds saved with the space-less slot naming but i was not able to create such a build.
=> FIX crash on import if abyss jewel socketed in weapon swap weapon

src/Modules/CalcSetup.lua, src/Modules/ModParser.lua
Fixes #5584 .
The old code used hard coded slot names which did not take into account the "swap" suffix that weapon slots have.
- Test [The Squire](https://www.poewiki.net/wiki/The_Squire)
- Test [Uul-Netol's Vow](https://www.poewiki.net/wiki/Uul-Netol%27s_Vow)
`https://pobb.in/hAVkORH1aWmN`
=> Fix socket group linking not working on weapon swap and generalize socket group linking code.

src/Classes/SkillListControl.lua
Enabled and FullDPS checkboxes don't update when the underlying values are changed using mouse shortcuts.
https://user-images.githubusercontent.com/5316261/212365483-f0c56052-a4dd-4336-a682-84e329e37348.mp4
Added a check to force update UI if the active item is modified.
=> Fix Enabled and FullDPS checkboxes not updating when mouse shortcuts are used

src/Modules/CalcSetup.lua
Fixes #3173.
When creating a new build and adding an item which grants a skill, the `nameSpec` of said skill (gem) in the XML will be empty.
Create such a said build by adding `Abberath's Hooves` or `Whispering Ice` and export it, after decoding the build code the gem has a `nameSpec`:
```xml
<Gem skillId="RepeatingShockwave" enabled="true" enableGlobal2="nil" quality="0" nameSpec="Abberath&apos;s Fury" enableGlobal1="true" count="nil" level="7"/>
```
=> Fix missing nameSpec for skills granted by items on export

src/Modules/CalcPerform.lua, src/Modules/ConfigOptions.lua
As there is no longer way to reset elusive then its very easy to get realistic elusive value on almost all builds (outside of some edge cases where you want to preload with elusive so the config option is still relevant).
https://pobb.in/0sEqAg9NkVOv
=> Use average elusive value by default instead of max one

src/Classes/TradeQuery.lua, src/Classes/TradeQueryRequests.lua
Fixes #5542, #5544
- Fixed a crash caused by sort mode change when jewels are present
- Fixed error message not clearing after successful sort
- Fixed `Import Item` button tooltip not displaying selected dropdown item after sorting
=> PoB Trader: Fix issues caused by sorting mode change

src/Modules/CalcSetup.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5132
Abyssal sockets were wiped when making an energy blade
https://pobb.in/r7rTJXeFmpcy
=> Fix Energy Blade not working with socketed Abyssal jewels

src/Classes/Item.lua
Empty handed profiles from poe.ninja this is caused by us not being able to parse an energy blade item.
https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5016#issuecomment-1386661695 / Prior discussion on discord.
```
Item Class: One Hand Swords
Rarity: Normal
Energy Blade
--------
One Handed Sword
Elemental Damage: 13-265 (augmented)
Critical Strike Chance: 7.00%
Attacks per Second: 1.70
Weapon Range: 11
--------
Requirements:
Level: 72
Str: 100
Dex: 100
Int: 98
--------
Sockets: R-B-G 
--------
Item Level: 60
--------
Adds 13 to 265 Lightning Damage (implicit)
```
=> Fix energy blade not importing on copy paste

src/Data/Uniques/Special/Generated.lua, src/Modules/ModParser.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5408
Adds everything reasonable expect arcane surge which is done in https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/4541
I tried implementing some of these with parts but ran into an issue where ModFlags weren't working with conditional mods.
https://pobb.in/oCMGz_wAhWn4
=>  Add support for more mods on precusor's emblem

help.txt, src/Modules/Main.lua
Just a simple help file containing hotkeys shortcuts and other lesser known features
Any and all info to add is helpful as theres alot of obscure stuff
=> Add a Help section

src/Modules/Build.lua, src/Modules/CalcActiveSkill.lua
Introduced in https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5571
Multi skills primary parts were deleting relevant stuff off srcInstance for secondary effects e.g. blade vortex in vaal blade vortex.
This resolves it by not letting them be deleted and fixes a couple other dangerous indexing nil.
- Add blade blast and observe no crash as well as being able to update stages.
=> Fix crash related to uninitalised srcInstance

src/Classes/SkillsTab.lua
#5181 But i forgot to apply the fix to inactive gems tooltip as well,
=> Fix inconsistent display of additional quality and gem levels in skill group tooltip for inactive gems

src/Classes/SkillsTab.lua
Introduced in #5715 . Used wrong variable.
=> Fix crash caused by indexing incorrect variable for additional level display in tooltip.

src/Modules/ModParser.lua
Fixes #5674 partially .
I could not get `Non-Aura Skills Cost no Mana or Life while Focused` to parse. Other mods should work correctly.
=> Add parsing support for more mods.

src/Classes/Item.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/2068
https://www.pathofexile.com/trade/search/Standard/EVJgXQRS5
local duration multipliers on flasks don't effect total amount recovered.
https://pobb.in/aj_cpx5oNiYg
=> Fix local flask duration effecting total amount recovered

src/Modules/ModParser.lua
Fixes last mod in https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5674 started by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5723
=> Add support for non-aura cost no life/mana while focused

src/Modules/ModParser.lua
Fixes #5708 .
Piece wise parsing of 
`Projectiles deal 15% increased Damage with Hits and Ailments for each remaining Chain`
adds the `ModFlag.Projectile` requirement to the mod which prevents it from being applied to ailments due to mod matching logic requiring all ModFlags to match.
This pr add explicit parsing for the mod that requires `SkillType.Projectile` instead of the ModFlag.
=> Follow Through not applying to poison

src/Modules/CalcSetup.lua
Fixes #5482 , https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/1065 .
#5482 Currently there is no check whether a group is enabled or not when groups are linked together based on the item they're socketed in. This pr adds it.
#1065 Two parts skills (Active and Support in one) such as Arcanist brand currently do not have their support parts applied to linked groups (in the same item). This pr adds a check for the case where `secondaryGrantedEffect` is a support.
=> Fix group disable not disabling support gems and two part skills not applying support part to linked groups

src/Modules/Common.lua
Fixes #5704 .
Due to the `writeLuaTable` function using `tostring` to serialize the values of mods `math.huge` is serialized to `inf` when saved to `ModCache.lua`. Setting a variable to `inf` is equivalent to settings it to `nil` in lua causing it to default to 0.
This is a sort of stop gap solution as this will be an issue with any values of mods that are not trivially serialized to string.
Mentioned issue contains some more discussion.
=> Fix incorrect serialization of math.huge by writeLuaTable.

src/Data/Skills/other.lua, src/Export/Skills/other.txt, src/Modules/CalcDefence.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/2452
This mod wasn't supported.
https://pobb.in/zwjAoWtrwH3k
=> Add support for cat's stealth avoid damage

src/Classes/TradeQuery.lua, src/Classes/TradeQueryGenerator.lua, src/Classes/TradeStatWeightMultiplierListControl.lua
Allow user to change what stat(s) trade "find best" weights by, default is still fullDPS but also some EHP, and also allows for dots, defences like max hit, or other misc stats like movement speed
supersedes #5376
Has a few minor formatting issues but should be fine to merge and fix later
=> Allow Trade to weight by multiple stats

src/Classes/TradeQuery.lua, src/Classes/TradeQueryGenerator.lua
This is built onetop of #5507 and doesnt make much sense for base to have
The purpose of this PR is that if sorting by multiple stats and you apply a weight multiplier to one it has little effect, eg fulldps 0.1 ehp 1.0 if my full dps is 100 times bigger itll almost always still just weight and sort by full dps because the change will be 10x bigger after the weight multiplier
by sorting by the percentage change instead it allows them to weight correctly, eg https://www.pathofexile.com/trade/search/Sanctum/LOJYnzGFn with "fulldps 1.0, EHP 0.5" it weights a 1% increased in dps the same as a 2% increase in EHP, rather than almost completely ignoring changes in ehp becouse the absolute difference was so much lower
=> Update Trader, Item weight and sorting to use percentage change rather than absolute

src/Classes/TradeQuery.lua, src/Classes/TradeQueryGenerator.lua, src/Classes/TradeStatWeightMultiplierListControl.lua
This removes the need to double click to change what stat weight you are changing, and also shows more stats in the "find best"
the tooltip to list the rest of the stats are still broken
=> Minor improvements to trade tool stat weights

src/Classes/ConfigTab.lua, src/Classes/ImportTab.lua, src/Modules/ConfigOptions.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4991 https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4847 https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4949
Level being used for placeholders and other calculations could get out of sync causing confusing behaviour.
=> Fix enemy level getting out of sync due to updating later than expected

src/Classes/TreeTab.lua, src/Data/LegionTradeIds.lua, src/Modules/Data.lua
This doesnt change functionality but makes it easier to modify them in the future
Its very possible to generate the keystone trade ids from the name of the conqueror as its just `explicit.pseudo_timeless_jewel_` + lowercase name of conqueror, but this makes it harder for the "any conqueror " and the devotion ones are problematic to get as they are unique mods, so I have just moved them for now
=> Move Timeless Jewel TradeIds out of Tree Tab

src/Modules/Common.lua
Colour codes at start of numbers were treated as part of the integer to be formatted.
This strips the colours codes at the start of numbers and readds it to the start of the number after formatting this will still be broken / not apply proper formatting of numbers with colour codes inside them e.g. ^12^26^73^37.
https://pobb.in/jcUg9zwq0DjB
=> Fix colour codes and number formating

src/Classes/ModDB.lua, src/Classes/ModList.lua, src/Modules/Data.lua
Fixes #5665.
#4641 introduced rounding for more multipliers and while most likely correct for some mods it causes issues for others like `SupportManaMultiplier` as mentioned the linked issue.  This pr implements support for mod specific precision based on code from #4640 .
Note the values are still slightly off due to rounding in calcPerform but should be close enough to give correct unreserved mana numbers.
=> High precision handling for more multipliers

src/Modules/Common.lua
Hex codes also exhibit issue seen in https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5733 but no examples currently exist. This updates the implementation to also handle them appropriately.
Example uses ^xA0A080 comma could also get added inside hex codes breaking them e.g. ^xBB6600
=> Fix hex codes with number formatting

src/Data/SkillStatMap.lua
Mod wasn't supported.
https://pobb.in/HW9QVwh9Rks3
=> Add support for additonal cooldowns on mirror/blink arrow

src/Data/Uniques/Special/New.lua, src/Data/Uniques/amulet.lua, src/Data/Uniques/axe.lua, src/Data/Uniques/belt.lua, src/Data/Uniques/body.lua, src/Data/Uniques/boots.lua, src/Data/Uniques/bow.lua, src/Data/Uniques/claw.lua, src/Data/Uniques/dagger.lua, src/Data/Uniques/fishing.lua, src/Data/Uniques/flask.lua, src/Data/Uniques/gloves.lua, src/Data/Uniques/helmet.lua, src/Data/Uniques/mace.lua, src/Data/Uniques/quiver.lua, src/Data/Uniques/shield.lua, src/Data/Uniques/staff.lua, src/Data/Uniques/wand.lua
Currently, running HeadlessWrapper with 'vanilla' (non-JIT) Lua 5.1 fails because the interpreter can't handle the [byte order mark](https://en.wikipedia.org/wiki/Byte_order_mark) present at the beginning of some source files:
```
^0Error loading main script: .\HeadlessWrapper.lua:121: LoadModule() error loading 'Data/Uniques/axe.lua': Data/Uniques/axe.lua:1: unexpected symbol near '∩'
```
This change removes the BOM from every file that contains it (all of them are in Data/Uniques), converting them to regular UTF-8/ASCII. Note that since the BOM is a non-printing character, this change is invisible to diffs.
- run HeadlessWrapper from a lua terminal and observe that PoB now starts correctly
- run Path of Building in developer mode and see that it still starts correctly
=> remove byte order mark

src/Classes/ItemsTab.lua, src/Modules/CalcPerform.lua
Recent change on dev added actorCondition = player to flask effect but this wasnt accounted for in these 2 scenarios.
- Check scaled value of flask, for example resistances
- Compare with multiplying the base value on flask by displayed effect in tooltip
- See if the value matches
https://pobb.in/5us8jIL2jQkt
=> Fix flask effect tooltips and onslaught flask effect calculation

src/Data/Skills/minion.lua, src/Export/Skills/minion.txt
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5745.
SkillType tag was missing from the minion skill. It's also not there in the game files so not really sure what's going on with minions skills. Related: #4628
=> Add missing skilltype tag to minion skill.

src/Classes/ImportTab.lua, src/Classes/PassiveSpec.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5767
If you imported into an old tree some nodes wouldn't be allocated.
- Convert Prompt disappears and version updates
- Undo still works
- All tree nodes now allocated.
https://pastebin.com/0sVa0vDb
Import [Kaatseyes](https://github.com/Kaatseyes) Sabo
=> Update Tree version to latest upon import

src/Data/Skills/act_dex.lua, src/Export/Skills/act_dex.txt
Fixes #5764
Projectile modifiers apply to Cremation Corpse Explosion part, whereas only Spell part should be affected.
=> Fix Cremation explosion part skill types

src/Data/Uniques/flask.lua
up to date values for some variants of Vessol of Vinktar
Fixes #5789 .
Vessel of Vinktar variants were legacy, updated to current
1. find vessels of vinktar and select either the proliferation or conversion version
2. notice how its now showing current values(125-150 instead of 80-100), these are selected variations 14 and 15
`https://pobb.in/2BN8ebg_oywD`
=> Update Vessel of Vinktar to have correct mod values

src/Classes/PassiveSpec.lua, src/Classes/TreeTab.lua
https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5768 introduced a bug where due to now supporting undo across tree versions and conversion using a restore on the latest version it now stopped working as it would simply undo to the old version. This now adds an optional parameter to override this.
=> Fix tree conversion

src/Data/Uniques/amulet.lua, src/Data/Uniques/axe.lua, src/Data/Uniques/belt.lua, src/Data/Uniques/body.lua, src/Data/Uniques/boots.lua, src/Data/Uniques/bow.lua, src/Data/Uniques/claw.lua, src/Data/Uniques/helmet.lua, src/Data/Uniques/jewel.lua, src/Data/Uniques/shield.lua, src/Data/Uniques/sword.lua, src/Data/Uniques/wand.lua
Implements changes to unique items and their base types from the Crucible patch notes.
Known unsupported modifiers:
- Nightmare jewel node conversions
- Severed in Sleep wither on hit, crit scaling
- Infinite Pursuit bleed expiry, sun/poison immunity
- Xoph's Inception pierce against burning, damage per pierce
- Formless Flame fire damage from hits
- Formless Inferno minion life scaling
- Xoph's Heart covered in ash
- Lightpoacher spirit charges
- Bubonic Trail abyss jewel scaling
- Manual verification in the item tab
https://pobb.in/SEWlx50vzllT includes all uniques
=> Crucible League: Updated Uniques

src/Modules/ModParser.lua
Adds the 3.21 "Gain Accuracy Rating equal to your Intelligence" mod.
New mastery modifier added in 3.21, needed to be added to our ModParser
- Added custom modifier for +1000 intelligence
- Set character level to 100 with a random bow on it
- Noticed MH accuracy was 238 (29% chance to hit)
- added custom modifier "gain accuracy rating equal to your intelligence"
- Noticed MH accuracy was 1258 (76% chance to hit)
[https://pobb.in/XKDBavRRrvtb](https://pobb.in/XKDBavRRrvtb)
=> Added accuracy equal to int mod

src/Modules/ModParser.lua
Fixes a bug where strength adding to minions was only applying at half value.
"Your strength is added to your minions" was only applying at half value due to a miss-flag.
- Added raise zombie gem
- Custom modifier +1000 strength
- Custom modifier your strength is added to your minions
- In calcs toggle on "Show minion stats"
- Zombies are now getting the full 1020 strength that the player has
[https://pobb.in/mUR8tBJ1boJd](https://pobb.in/mUR8tBJ1boJd)
=> Bugfix: Strength adding to minions at half value

src/Data/Uniques/Special/New.lua, src/Modules/CalcSetup.lua, src/Modules/ModParser.lua
Implements Windowhail unique.
If more mods such as the ones found on the `Windowhail` unique are implemented in the future a more general solution similar to the one used in gem support cross linking will need to be implemented.
https://pobb.in/gQJ3myv4fbUE
=> Widowhail unique implementation

src/Modules/CalcPerform.lua, src/Modules/ModParser.lua
…mastery
- Added support for the new "Minion's accuracy rating is equal to yours" mod that is added in 3.21.
- _Screenshots show this is a nerf to minion accuracy if you don't have enough player accuracy_
- Added Raise Zombie skill
- Added +1000 accuracy rating in custom modifiers
- Added minion's accuracy rating is equal to yours
- Zombie's MH Accuracy is 1040 (1000 flat + 40 from dex)
[https://pobb.in/bSRGKIGq9tCB](https://pobb.in/bSRGKIGq9tCB)
=> 3.21/minion accuracy equals accuracy

src/Modules/ModParser.lua
3.21 tree has trickster and juggenarught updated to use equipped wording this add support.
=> Fix mod parser to support equipped formatting in all cases

src/Modules/ModParser.lua
Primal Aegis can take 20 Elemental Damage per Player Level is on 3.21 tree
=> Add support for potential alt primal aegis wording

src/Modules/ModParser.lua
Fixes #5771 .
The mace mastery that was for all damage will chill was not actually applying to all damage when using a mace. This is now fixed
- Made a build that had that notable, and saw no chilling effect was occuring
- Made code changes
- Pulled up the same build and saw that the chill was occuring
The link in the build was a 404, so made [a very small build](https://pastebin.com/h6LWwngz).
=> Updated support for mace/scepter all damage will chill

src/Modules/ModParser.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5789#issuecomment-1489442264
An overly aggressive pattern was matching the entirety of the unparsed action speed mod. This meant it was missed in the intial implementation this switch the patterns to match smallest string and changes inlificted exposure to only match letters as the exposure type as well as implementing the action speed mod.
=> Fix fire exposure/action speed mod on Balance of Terror

src/Modules/CalcOffence.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5757
Afaik GGG handles more multipliers in the following way
Compute each multiplier type to 2 d.p. then multiply them all so in this case it should be 0.96 * 1.4 with full precision as one is spell damage and other is cold.
This removes the rounding in the main section as it should be correctly handled in the MoreInternal function.
=> Fix more multipliers on skill damage being incorrectly rounded.

.github/ISSUE_TEMPLATE/accuracy_bug_report.yaml, .github/ISSUE_TEMPLATE/behaviour_bug_report.yaml, .github/ISSUE_TEMPLATE/calculation_bug_report.yaml, CHANGELOG.md, changelog.txt, src/Classes/DropDownControl.lua, src/Modules/CalcDefence.lua, src/Modules/CalcPerform.lua, src/Modules/CalcSections.lua, src/Modules/ModParser.lua
* Fixed some spelling issues that are currently ignored.  This will allow them to be removed from `ignore-dict.txt` in a future `pob-dict` update.
* The `ModParser.lua` changes are to support future simplification in the `pob-dict` "ignore" regexes.
Small change-set, shouldn't break anything, but someone might like to double-check my work as I'm having difficulty concentrating for more than a few minutes atm.
=> fix misc spelling issues

src/Data/Skills/act_int.lua, src/Export/Skills/act_int.txt
Ball Lightning has a base projectile speed of 40 unit/s. This was determined through the Projectiles.dat file
=> Fix Ball Lightning Projectile Speed

src/Data/Uniques/gloves.lua
>Fixed a bug where the Entropic Devastation Unique did not have Shaper-influence.
=> Add shaper influce to entropic devastion

src/Modules/ConfigOptions.lua
> Fixed an issue where the reminder text for Profane Ground incorrectly stated hits against enemies have +1% to Critical Strike Chance, when it is really 100% increased Critical Strike Chance. This is not a functional change.
3.21 revealed the tooltip for profane ground as 1% base crit is inaccurate and it is infact implemented as 100% increased crit chance.
=> Fix incorrect profane ground numbers

src/Classes/PassiveSpec.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4781
When we try to generate a url the encoding breaks if there are more than 254 nodes this changes it so they are only added up until this number. As we save a tree url to build file this is also generated making the regular data unsavable as well.
- Having more than 254 nodes allocated testing around with clusters and masteries as well to not observe crash.
https://pobb.in/pvUFgxNk6v1P
=> Fix brainstorm trees not being saveable

src/Modules/Main.lua
Fixes crash mentioned in #5783
Long lines being fed into the WrapString that have no spaces cause crash due to `lastBreak` not being set.
Note that this fix may cause some things to wrap differently but should not cause incorrect wrapping.
=> Fix crash caused by very long lines without spaces

src/Data/EnchantmentHelmet.lua, src/Export/Scripts/enchant.lua
This PR fixes known issues in the enchantment export script, notably:
- Modifying the skillMap table resulted in an enchant incorrectly getting exported under Tornado instead of Tornado Shot
- Shield Charge enchants got exported under the name Table Charge
- Blade Vortex missed an enchant, instead it got exported under Vaal Blade Vortex
These issues should be fixed now, closing #5553.
=> Fix helmet enchant script

src/Data/Skills/act_dex.lua, src/Export/Skills/act_dex.txt
swaps bladeblast to using stages, allowing for more granularity with the number of blades hitting, as well as implements a separation of "per cast" and "per second", so that it will stop suggesting cast speed like spell echo
This also fixes other dps multipliers working with it, allowing for things like unleash to be properly calculated
eg before 
was showing dps loss, 
after shows correct dps gain
=> Improve blade blast using stages

src/Data/Uniques/Special/Generated.lua
Fixes #5617 & fixes #5444.
I also added explicit definitions for all 4 unique mods, though I don't really know which ones people are likely to choose.
=> add fourth unique modifier to Vorana's March

src/Modules/CalcSetup.lua, src/Modules/ConfigOptions.lua, src/Modules/ModParser.lua
This adds support for disabling helm/body/rings/5th flask from things like bringer of rain (disables body)
supersedes #1317
"can't use helmets" isnt properly supported due to being on a passive which isnt fully processed by the time items are added, a substitute ("can't use helmet") was added, but must be applied to an item to work atm, may come up with a workaround to it
=> Add support for items that disable other item slots

src/Modules/CalcDefence.lua
Introduced in https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5814
Eternal Damnation got broken as it needs resistance also calculated before damage reduction.
https://pobb.in/5L9205yhe-CS
=> Fix eternal damnation

src/Classes/GemSelectControl.lua
The `considerAwakened ` variable is never actually set anywhere which causes the sort cache to be rebuilt every time `UpdateSortCache` is called.
=> Fix incorrect variable causing sort cache to rebuild everytime

src/Classes/SkillsTab.lua
On load, if first active skill set did not had id 1 new empty skill set was created and data was lost. Then on save most/all skill sets could be wiped like this.
- Load PoB with first skill set not having id 1
- The skill set should still be present with its name preserved
- Save pob, see that skill set id is still its original ID
- Load pob again, see it still being there
https://pobb.in/VFyFoOxCXlrT
=> Fix skill sets sometimes being deleted after deleting first one

src/Classes/DropDownControl.lua
The coloring is pretty useful for build guides to distringuish different variations.
Colors from dropdowns are stripped and only shown for current selection.
- Have colored dropdown
- Click it see colors
https://pobb.in/nnNpYgb5o2CD
=> Do not strip colors when rendering dropdowns

src/Modules/CalcPerform.lua
Fixes #5729.
The source of the enemy mod was not being set in the pantheon code. This pr sets the source of the enemy mod to the source of the EnemyModifier mod from player.modDB if source is missing on the mod that is supposed to go into enemyDB.
=> Fix crash caused by missing EnemyMod missing source.

src/Data/SkillStatMap.lua, src/Modules/ModParser.lua
Fixes #5488  .
Volcanic Fissure supported by Earthbreaker incorrectly gets +1 totem limit from "Attack Skills have +1 to maximum number of Summoned Ballista Totems" mods such as from Panopticon and Watchtowers.
- Make a build with the skill gems Volcanic Fissure supported by Earthbreaker.
- Allocate Panopticon and Watchtowers.
- Check that the Active Totem Limit under the "Calcs" tab still shows 1.
- As a sanity check, make a build with a bow and a bow attack skill gem supported by Ballista Support with the same passives allocated, and confirm that those still increase active totem limit.
https://pastebin.com/yzzh77Gp
=> Fix skillType tags for maximum Ballista Totem mods

src/Data/Uniques/quiver.lua
Saemus' Gift changed base in 3.17. This corrects the base by adding a new variant.
- Checked the item in the item tab
=> Correct base for Saemus' gift

src/Classes/PassiveSpec.lua, src/Modules/CalcSetup.lua, src/Modules/ConfigOptions.lua, src/Modules/ModParser.lua
Built ontop of #5664 (So that one should be merged first)
Implements limits for jewels as well as an option to ignore the limits
This correctly limits most types of limits, including basic ones (like anima stone), radius jewels (like unnatural instinct), grand spectrums (limit of 3 across all grand spectrums), impossible escape (though this is a little buggy as it doesn't unallocate nodes that are allocated)
This is broken for historic jewels atm though
=> Add support for jewel limits

src/Classes/ImportTab.lua, src/Modules/Build.lua
This PR is an entirely new feature requested directly to me on discord.
When creating a new build, most people do one of two things:
1) Set the character level to a set value (100, 94, 80, etc) which is inaccurate
2) Check the level requirement for the amount of allocated passives and set their character level to that value
This PR automates the second case by using a placeholder system for the character level. 
_New build button_
Character level follows allocated passives.
_Imported character_
Character level is set to the imported character's level and does not follow allocated passives.
_Loaded build from list_
Character level behaviour follows the same behaviour as when the build was saved.
_Manually setting character level_
Mode switches to manual.
_Emptying character level_
~~If …
=> Set character level to level requirement for allocated passives

src/Data/Skills/other.lua, src/Export/Scripts/skills.lua
fixes rigwalds export needing to be fixed manually every time and gives warnings if stat is missing from earlier levels
check that its fine for the unused stat to have a value/statInterpolation of 0
also maybe disable the warnings as they arnt needed for any current stuff?
=> Fix export of skills with different amounts of stats

src/Modules/ConfigOptions.lua
This do not applies -10% to elemental resistances
- Get source of suppressed recently condition
- Check tooltip
https://pobb.in/FmELVkDrp3VP
Tooltip gone
=> Remove incorrect tooltip from "Have you Suppressed Recently"

src/Classes/PassiveSpec.lua, src/Modules/CalcSetup.lua, src/Modules/ModParser.lua
- Added support for the new 3.21 mastery `10% more Maximum Life if you have at least 6 Life Masteries allocated`
- Allocated the other 5 life masteries
- Looked at life amount
- Allocated the last mastery `10% more Maximum Life if you have at least 6 Life Masteries allocated`
- Life incremented the expected amount
[https://pobb.in/zHi7uOahPbS3](https://pobb.in/zHi7uOahPbS3)
=> 3.21 - X% more max life if you have at least X life masteries allocated

src/Modules/ConfigOptions.lua, src/Modules/ModParser.lua
- Added support for the new 3.21 mastery "Gain Adrenaline for 1 second when you change Stance"
- This just adds a new toggle in the Config/Combat section
- Put a point into the new "Gain Adrenaline for 1 second when you change Stance" mastery
- See that Adrenaline has not yet been applied
- Toggle on the `Changed Stance in the last 1s?` toggle
- See that Adrenaline is applied to stats
- Remove point from mastery
- See that Adrenaline is no longer applied
[https://pobb.in/a3Asq0Q_cu0X](https://pobb.in/a3Asq0Q_cu0X)
=> Added support for new Adrenaline on changing stance mastery

src/Modules/CalcOffence.lua, src/Modules/CalcPerform.lua, src/Modules/ModParser.lua
Implements the following attack and lightning masteries:
* Monsters cannot Block your Attacks
* 5% increased Attack Speed per Enemy in Close Range
* This requires setting *both* # of nearby enemies config and "at close range" config to apply
* Nearby Enemies are Intimidated while you have Rage
* Followed the existing example from `"nearby enemies are crushed while you have ?a?t? least (%d+) rage"`
* I originally tried to implement this using a more general `"while you have rage"` entry, but didn't end up getting this to work (I suspect my naive attempt might have been ending up trying to apply while the *enemy* had rage)
* 60% increased Critical Strike Chance against enemies with Lightning Exposure
* In order to handle EE correctly, I created a new Condition applied after the EE …
=> 3.21 attack and lightning masteries

src/Modules/CalcBreakdown.lua, src/Modules/CalcDefence.lua, src/Modules/CalcOffence.lua, src/Modules/CalcSections.lua, src/Modules/ConfigOptions.lua, src/Modules/ModParser.lua
* Deal 10% more Chaos Damage to enemies which have Energy Shield
* 50% reduced effect of Exposure on you
* Hits have 25% chance to treat Enemy Monster Elemental Resistance values as inverted
[Here's](https://pobb.in/9nwzmkfT1p6B) a build that makes use of these.
=> feat: add some more 3.21 masteries

src/Modules/CalcPerform.lua
The current parsing for life/mana flasks was wrong as it was adding conditions like UsingDivineLifeFlask insead of simply adding UsingLifeFlask etc.
- Enable life flask
- Check if heart of oak is giving you regen
https://pobb.in/1GG8yuGg_pUw
=> Fix flask conditions for using Life and Mana flasks

src/Classes/Item.lua, src/Classes/ItemsTab.lua, src/Modules/ModParser.lua
If life or mana flask is enduring (life enduring currently only comes from Master Surgeon) show also flask uptime. Also check if flask is instant or not.
- Equip life flask
- Check master surgeon
- See that flask now shows uptime
https://pobb.in/9puN8BGd3_pp
=> Show uptime for "enduring" life and mana flasks

src/Classes/ConfigTab.lua, src/Classes/EditControl.lua, src/HeadlessWrapper.lua, src/Modules/ConfigOptions.lua
Depends on/built on top/closes https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5712
Closes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5744
Currently in custom mods its hard to tell if I typed the mod correctly or not. With this change the mods are recolored like on items when the input field loses focus.
- Enter properly parsed mod
- Unfocus custom mods input
- See it turn blue
- Same for invalid mod turning red
https://pobb.in/5fQaEhtVLtYj
=> Recolor custom mods like items based on mod being parsed or not

src/Modules/Common.lua
Hex codes were causing problems. This occured in two ways they were partially parsed producing partial codes making garbled text and they were the only part being parsed this caused a crash.
https://pobb.in/2Hzt-5GshxyF
=> Fix hex code crash

src/Modules/CalcDefence.lua
A wrong variable was used resulting in incorrect damage multipliers being used. Most notably with CI 0x multiplier.
https://pobb.in/fUXT_CRhTkse
=> Fix Damage taken conversion using wrong variable (#5859)

src/Modules/CalcDefence.lua
resistance and damage reduction were incorrectly moved causing multiple issues, this moves them back but checks the conditionals earlier
The order of armours was changed as well, this should probs be changed back now that the conditionals are checked earlier
=> Fix issue calculating defences based on overcapped resistances

src/Modules/CalcSetup.lua
Quiver bonuses were multiplied by increase instead of 1 + increase
=> Fix Widowhail increased bonuses calculation

spec/System/TestDefence_spec.lua, src/Modules/CalcDefence.lua
Fixes #5864 .
One more spot had wrong variable in damage taken as conversion calculation
https://pobb.in/JMHXRIQ-wt0h
=> Fix max-hit with 100% taken as conversion

src/Classes/PassiveMasteryControl.lua, src/Classes/PassiveTree.lua
Fixes #5872 
Some mastery descriptions had a line break in them.  Our standard list box doesn't support multiline selections, so I simply removed the line break from any masteries that had them.
=> Fix mastery choices overlapping when they had multiple lines

src/Modules/CalcSetup.lua
Fixes #5867
The way this worked before cleared out all the support gems each time.  With the previous fix, the new table instantiation was moved, so I simply cleared it out again.
=> Fix gems in the Squire counting multiple times

src/Modules/CalcPerform.lua
Mod was being parsed, but resistances were being calculated after minion life already was calculated
```bash
eNqtHGtz2rj28-ZXeJjpzO7sTcA2JjST7A5JSMpM0rKQtPd-2hG2AG1li9pyUrrT_36PJBsMWH7EdGe6xjpv6TwRvfzzu0-NFxxGhAVXLfOs0zJw4DKPBIur1vPT3Wm_9ecfJ5djxJef5tcxoWLlj5NfLuWzQfELpoDXMjgKF5h_TinZfwOlFQr4ErPgEf3DwnvmXbU-sgC3jBkKPMLTTy5FUfQR-fiqNXUBuWWgyMWBd7N9nwAuUYhcjsMHwXUQc_bIPFjlYQyrPiLBlLlfMb8PWbySQr0Q_KpgRo_jT5OnjEgkyIoEGv1yOaZojcMpR9yI4K-r1sDl5AUDKEj1QHzCgSKiMZA7b7U1KGBLtMAfMrCdEtjrOIz4LfLhsRxnusLY24BZOrBxiIfzOZby34SE3yxR4FYgXxf2MaacrCjB4QbePHN0GB8OiJsdLfknxhG9HU_LBVGQrILFvxC-vKZgwUp0BfRoERCOK4OPGYlYUEvqSsA3MaXgeJVgJzjC4QvipKIgN8yfkaCiTR5RgG5YtLW12SsCHeMQXJnvYHRKEKbYZeD9WRTbqsAkH1XL7YHMcXXIWookCHWleZsew2lVuNqE3ybQBAJZNcgpi2lFSL4NMFbByf-WBTS7fR3kLf5egd4o4NW4ZgFNx9FzfWFcZrhKwWH4Ybylap-_P7PNjt3t9q1 …
```
=> Fix Formless Inferno not increasing minion life properly

src/Data/Uniques/belt.lua, src/Data/Uniques/bow.lua, src/Data/Uniques/ring.lua, src/Data/Uniques/shield.lua
Fixes #5637.
Fixes outdated modifier values on Betrayal uniques. 
Updated values showing in PoB.
https://pastebin.com/egTWrahU
=> Update mod values on Betrayal uniques

spec/System/TestDefence_spec.lua, src/Modules/CalcDefence.lua
Prevented life loss (petrified blood / progenesis) + MoM was calculating the effective mana hit pool from a life pool that was not effectively multiplied by prevented life loss effects.
https://pobb.in/uywtG_MOvl8T
=> Fix MoM and Prevented Life loss effect interaction

src/Modules/CalcDefence.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5907
When a hit kills you with PB life loss prevention was being applied to the damage you were taking while dead. This lead to more being mitigated then it should resulting in weird breakpoint behaviours as we transition between 0-1 hit to just over 1 hit producing large amounts of life loss prevention.
https://pobb.in/MrUkxpa_Q25d
=> Stop life loss prevention occuring on overkill damage resulting in breakpointing behaviour

src/Modules/CalcOffence.lua
https://www.reddit.com/r/pathofexile/comments/12a5s10/comment/jerrozh/?utm_source=share&utm_medium=web2x&context=3
Ghost reaver didn't work with mine leech due to being outside the checks.
Test with various combinations of these mods and observe they all work.
https://pobb.in/j4H9pzFkycSC
=> Refactor leech to handle ghost reaver and mines leech

src/Modules/CalcDefence.lua, src/Modules/CalcPerform.lua, src/Modules/Calcs.lua
Minor speed improvement with full dps, but skipping EHP/maxhit calcs where unnecessary
This results in around a 2% speedup per skill in fulldps after the first, a similar thing could be done for minions
(eg with 5 skills total you get around an 8-9% speedup doing something like node power or item sorting)
=> Split calc defence and only run ehp calcs on first pass of full dps

src/Modules/Build.lua, src/Modules/Main.lua
The recent release introduced auto/manual level modes. By default, new builds used auto mode, which would then set character level to 1 regardless of the default character level option.
This PR defaults the mode to manual if the default character level is above 1, otherwise to auto.
=> Set level mode to manual if default level is above 1

src/Modules/Data.lua
Fixes #5940 
Sceptres are mislabeled as "One Handed Mace" in our dataTypes, this PR updates the label to "Sceptre". This affected mace/sceptre behavior for mods using different weapon types.
- Equip 1h mace, sceptre
- Allocate the dual wielding mastery [50071]
- check increased damage
--
- check label on sceptre item
<pre>eNqtW1tz4rgSfp78ChdV540QfCepsFsQyKUmJCxkZs45L1PCFqAdYTG2nITZmv--LV_AIcixsSdTCVj9tbpb3a1uIS7_fF1R5Rn7AWFet6G22g0Few5zibfoNr48XZ92Gn_-cXI5Rnz5OO-HhIqRP04-XUavFYqfMQWc3VA48heYf01Z6d-B1Rp5fImZN0J_M_-Gud3GA_NwQ5khzyU8fedQFAQPaIW7jakD4IaCAgd77tXueUK4RD5yOPbvxbS9kLMRc2GU-yGMrhDxpsz5gfmNz8I1SNVQngl-iWnuRuPHyVNGJOJlRQKVPl2OKdpgf8oRVwL41W30wDJogQdoBb-BG6IhsNJbuqapttFpa5ahmY2zXHA_9AP-joPZPtds07L183OjI-MwXWPsbkFaq63KKMc-Hs7n2OHkGV_5hF8tkefs5jNbUikPUOutTi75KKScrCnB_haiyie4fcffbstonxhH …
=> Fix issue where Sceptres and One Handed Maces were considered the same weapon type

src/Data/Uniques/wand.lua
Fixes # .
I checked https://www.pathofexile.com/forum/view-thread/3361403 poedb and poewiki and nothing indicates Reverberation Rod losing Controlled Destruction.
-
-
-
=> Fix Reverberation Rod to add back Controlled Destruction

src/Classes/PassiveTreeView.lua, src/Classes/TreeTab.lua
Fixes #5903
Show node power causes severe lag. For almost all usecases, it should not enable on load. In addition, if show node power is disabled while power report is showing, it would hide the hide power report button, but keep the report open. 
This PR removes show node power (showHeatMap) from saves and loads. In addition, it hides the power report when the show node power checkbox is toggled to false.
=> Hide the power report on loading a build and unchecking "Show node power"

src/Modules/Build.lua, src/Modules/Calcs.lua
Adds skill names to cost warnings added in #5019 .
=> Add skill names to cost warnings

src/Modules/ModParser.lua
Fixes #5949 .
[Kaom's spirit](https://www.poewiki.net/wiki/Kaom%27s_Spirit) rage regen was calculated as a "PerStat" mod type making it only possible to have integer values of rage regen for every 100 life regen on the character. This goes against the in-game behaviour which lets you have a real number rage regen even with less than 100 life regen. This PR updates the mod type to "PercentStat"
- equip kaom's spirit
- equip lvl 15 vitality
- check life regen in calcs
- check rage regen in calcs
https://pobb.in/kEo6M0wLcbiV
=> Fix kaom's spirit rage regen calculation behaviour

src/Modules/CalcPerform.lua
Theres a reason this did not automatically apply before, you cant be sure on the state of the life pool unless its forced (eg lowlife if you reserve enough), so its up to the user to configure it
This breaks things like agnostic and overvalues "while on full life" things
incorrectly added by #5904
=> Remove the auto application of full pool

src/Classes/PassiveTreeView.lua, src/Classes/TreeTab.lua, src/Modules/Build.lua
Previously, PoB did not prompt the user to save if they modified the search string, despite the fact that the search string is stored in the save.
This PR causes that prompt to happen, allowing users to remove/adjust a search and then save that change without making other changes too.
=> Prompt for saving after altering the passive search string

src/Classes/ConfigTab.lua
- Fix GetDefaultState to properly handle lists (this also saves saving of bunch of default list values to build XMLs)
- Fix control state checks for non-boolean type config options
- Fix coloring of config controls with separate labels
- Enable enduring cry
- Adjust warcry calculation mode
- Disable enduring cry
https://pobb.in/zI8n1DDXYEeA
=> Fix default state validation for lists and color labels properly

src/Modules/CalcOffence.lua, src/Modules/ModParser.lua
Implements `Skills Cost Life instead of 30% of Mana Mastery`
https://pobb.in/Q21ID2STniX-
=> Add support for Skills Cost Life instead of 30% of Mana Mastery

src/Data/Uniques/body.lua, src/Data/Uniques/boots.lua, src/Data/Uniques/helmet.lua, src/Data/Uniques/quiver.lua, src/Data/Uniques/shield.lua, src/Modules/ModParser.lua
These wordings were changed.
Also add support for negative of local life per hit.
=> Fix a few uniques for 3.21

src/Data/Skills/act_dex.lua, src/Export/Skills/act_dex.txt
The modifier "Hits after the first on each Enemy deal 60% less Damage" was already supported through a preDamageFunc, but since we used a static value instead of a proper parse, the modifier still showed as unsupported.
This adds a mapping to the stat in question and uses said stat in the preDamageFunc, not only making it show as parsed, but also allowing it to be automatically parsed in case that number ever changes.
- Compared damage values before and after change, noted they were identical
=> Parse the modifier for less damage on subsequent hits on lancing steel

src/Modules/CalcDefence.lua
Max mana leech rate was only base values, not including increased/more modifiers.
- Checked mana leech before and after change
https://pobb.in/Ni5SaBFkXDSY
=> Correct display of max mana leech rate breakdown

src/Classes/ImportTab.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5986
Due to missing the crucible mod tag the mods weren't coloured.
This adds it so it works correctly.
https://www.pathofexile.com/account/view-profile/johann_94/characters?characterName=elodeday
=> Fix crucible item colour

src/Modules/CalcDefence.lua
Fixes #6000 introduced in https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5904
The number was being multiplied by 50/55 instead of 0.5/0.55
https://pobb.in/qQ5kRuWBCLBG
=> Fix low life recoverable calculation

src/Data/Skills/sup_int.lua, src/Export/Skills/sup_int.txt
Since the stat being mapped is a bool, it automatically take the value of 1 if mapped into a mod. This fixes it by applying a multiplier of -100
=> Fix Prismatic Burst not choosing 1 damage type for DPS

src/Modules/CalcActiveSkill.lua, src/Modules/CalcTools.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4684 https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/2719 https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/2295
Active skill gem mods cannot apply if the skill has the support gem tag this includes a fix added in https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5530 along with one for the item mods to hopefully get it merged faster.
https://pobb.in/iH6RqTU-zfT0
=> Fix active skill mods applying to support gems

src/Modules/CalcPerform.lua
The mastery was incorrectly working with Skitterbots, Pride, Flesh and Stone and Death Aura
=> Fix 'Damage per aura' mastery incorrectly working with some gems

src/Data/Uniques/gloves.lua, src/Modules/ModParser.lua
Need to add support for the blind mod
=> Update Tomb Fist to 3.21

src/Data/StatDescriptions/stat_descriptions.lua
Confirmed by Novynn that the mastery is meant to say elemental on it. Fixing it before GGG make the change to reflect the current state of the game
=> Fix max res Armour Mastery incorrectly applying to max Chaos res

src/Modules/CalcBreakdown.lua
Fixes a display bug of leech calculations when instant leech is in effect.
With the new instant leech mastery, PoB added a breakdown of instant leech as part of the calculations for life leech rate.
The breakdown is located under `Calcs > Leech & Gain on Hit > Life Leech Rate`.
The breakdown however uses `instantLeechProportion * nonInstantLeechPool`, instead of using the total leech pool.
- Visually confirming the displayed calculation
https://pobb.in/U-bPLFcSdcB7
=> Fixed incorrect display of leech breakdown

src/Classes/Item.lua, src/Modules/CalcDefence.lua, src/Modules/ModParser.lua
The base crit mod was not being added to the base crit of the weapon and instead was being treated as global base crit
Your Cold Damage cannot Chill
Minions never deal Critical Strikes
Minion hits can't be Evaded
Minions take 15% increased Damage
Minions take 15% reduced Damage
Minion Critical Strikes do not deal extra Damage
No chance to Block
-1 to Maximum Endurance, Frenzy and Power Charges
Inflict Fire, Cold, and Lightning Exposure on Hit
8% increased Movement Speed if Dexterity is below 100
14% increased Area of Effect if Intelligence is below 100
6% chance to deal Double Damage if Strength is below 100
-20% chance to Block Projectile Spell Damage
+25% chance to Block Projectile Spell Damage
15% chance to inflict Brittle on Enemies when you Block their Damage
15% chance to inflict …
=> Add support for many crucible mods

src/Data/Skills/act_dex.lua, src/Export/Skills/act_dex.txt
This only adds basic support for vaal animate weapon, it does not "convert: the weapon into a random unique, 
IMO the user needs to give it whatever unique they want the weapon to have, having to calculate the effects of all the unique weapons would require hundreds of calculation passes making PoB unusable
though this could be done via dropdown using the list, instead of item set
=> add basic support for vaal animate weapon

src/Classes/Item.lua, src/Classes/ItemsTab.lua
Adding excludeTags param to GetModSpawnWeight so we don't need to modify an item's base tags to remove/ignore a type when checking for applicable mods in special cases, like Crucible.
=> Support excluding tags in GetModSpawnWeight

src/Modules/Common.lua
Regular colour codes weren't being stripped as gsub always returns something and hence the other gsub is never called this calls both.
https://pobb.in/_Q--BVUhrgXZ
=> Fix colour codes leaking into formated numbers

src/Modules/CalcDefence.lua
The Juggernaut Unbreakable node is meant to double the armour received from having iron reflexes and evasion on your body armour
Fixes #6096
=> Fix Juggernaut Unbreakable not working with Iron Reflexes + evasion

src/Modules/CalcActiveSkill.lua
The self cast flag was only checking to make sure that a skill was not supported by totems, mines or traps when it should also be checking to make sure it isn't triggered
Fixes #6100
=> Fix Fanaticism applying to triggered skills

src/Modules/CalcOffence.lua
Unleash is somewhat unusual among repeating damage systems in that it does not modify the average damage of a hit, instead applying a simple DPS multiplier. This made Average Burst Damage inaccurate since it did not account for the less multi on unleash.
We could possibly try to refactor unleash to modify average hit as well, but that's a larger job. This simply adds the repeat penalty to the average burst damage calculation if it's present.
Compared the damage before and after change on:
- Arc + Unleash
- Arc without unleash
- Frozen legion
Arc + Unleash got lower burst as expected, without unleash was unaffected, and frozen legion was unaffected
https://pobb.in/khQPsbXfIEbC
=> Correct burst damage when using unleash

src/Classes/ItemsTab.lua, src/Modules/Data.lua
Added hard-coded list of uniques that have extra caster and/or minion tags that we reference in itemCanHaveMod to add "caster_unique_weapon" or "minion_unique_weapon" tag to the pool of possible crucible mods
=> Support Uniques with Extra Crucible Mod Tags

src/Classes/TreeTab.lua, src/Modules/Build.lua
Adds an option to include unallocated nodes that are a selected distance away as if they were allocated (eg willing to spend x points for y effect)
eg node distance 0 (same as old filter)
vs 2
vs off
This is currently capped at 10 but can be increased/decreased easily in future PR if needed
This will likely need further improvements, like minimum weight per point spent, or indicators for which nodes are allocated etc but for now this can help significantly in specific situations
This PR also colours the Desired nodes/fallback nodes selection buttons based on which is currently selected as well as colouring fallback yellow if you click generate to give feedback that something has changed there
eg
=> Timelessjewel search improvements

src/Modules/CalcOffence.lua
Fixes #5921 
Mods with both Ailment and Weapon1H flags like the Sleight of Hand passive are not applying the increased damage with ailments to poison, bleed, nor ignite.
- Wield one handed weapon(s)
- Custom modifiers for poison, bleed, ignite 100% chance
- Allocate Sleight of Hand passive
- Check Calc breakdown "Total Increased" on each damaging ailment
--
- Tested with 1 One Handed Weapon
- Tested with 2 One Handed Weapons
- Tested with Viper Strike
- Tested with Two Handed Weapon
- Tested with No Weapon
- Tested with Physical Spell
- Tested with passives that give increased damage over time
- Tested with passives that give increased damage with ailments without weapon condition
- Tested with passives that give increased elemental damage with attacks (checking ignite) …
=> Fix Sleight of Hand and other One Handed Weapon + Damage with Ailments passives

src/Classes/TreeTab.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/6083
Confusion around by assuming the jewel socket next to acrobatics was called acrobatics when it was in fact called wind dancer.
This fixes this by instead using the closest keystone for the name.
=> Use nearest keystone for timeless jewel search name

src/Classes/Item.lua
Fixes #6064 
Adds crafted enchantment conditions to modifiers being considered in item conditionals.
- Follow step described in issue #6064 and see problem is solved.
Same as in Issue
=> Fix Life Mastery item condition to include Enchants

src/Classes/PassiveSpec.lua, src/Modules/CalcSetup.lua
Fixes #5965 .
Life masteries were redundantly being counted
- Allocating 6 life masteries, and confirming the 10% More Life is still in effect.
https://pobb.in/4eIZutKXOS1h
=> Generalise count types

src/Modules/CalcPerform.lua
Fixes #6040 .
The marked status was not set for the self skill pre-calculation in Manafroged implementation causing infinite recursion stack overflow.
=> Fix infinite recursion issue with Manaforged arrows

src/Classes/PassiveSpecListControl.lua, src/Classes/SkillSetListControl.lua
Fixes #6052 .
Call to `RenameSpec` did not include title causing crash when trying to render the box containing the title.
=> Fix missing title for tree rename popup causing crash

src/Modules/Build.lua
Fixes #5946
When changing tree to one where ascendant had received extra skill points, the level requirement updated immediately. The extra skill points were then granted after that in Calcs.lua. Since no change happened in allocated points, levelreq did not recalculate. By adding a check that extra points changed, we then recalculate once those extra points are granted.
I also renamed the variable bandit to extra, since it includes ascendant points.
- Swapped between trees for the ascendant, verified that levels were no longer inconsistent.
https://pobb.in/Yig8VJrQQtir
=> Recalculate level requirement when extra skillpoints change

src/Classes/ItemsTab.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/6054
Some mods are ordered as descending but have their value pairs in ascending order.
This inverts the range if it won't be continuous this has a few assumptions 
- We only need to look at first range with a valid min max.
- The min-max pairs will be orientated the same way and will always be strictly ascending / descending.
https://pobb.in/5JWKpx3ekvUd
=> Fix discontinuous mod values occuring with range tier slider

src/Classes/TradeQuery.lua
"Find best" callback had an erroneous sort order hardcoding.
=> Fix trader occasionally ignoring sort selection

src/Classes/Item.lua
The Poison chance for Spells crucible mod was having the `MainHandAttacks` condition applied to it when it should be a global spell mod. Not sure if this breaks something else though
Test with: https://pobb.in/kB_8LRjvFn26
Fixes #6106
=> Fix Poison chance for Spells mod on weapons

src/Modules/Calcs.lua
Fixes #5895, #5944.
Ailment config options did not show up even though current build was capable of inflicting them, causing annoyances when trying to use item/gem sorting to optimize for their effect.
This pr attempts to preemptively enable config options for related enemy conditionals based on used mods to fix this.
This may not be the best way of doing this and may be missing handling for some other situations where a similar issue occurs, but does fix the mentioned issues.
=> Fix ailment conditionals not being preemptively enabled when an ailment can be applied.

src/Classes/ItemDBControl.lua, src/Classes/NotableDBControl.lua, src/Classes/PassiveTreeView.lua, src/Classes/TreeTab.lua, src/Modules/Common.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5221
This has capture groups support. 
~~It could likely be used to refactor ModParser~~(too slow https://github.com/QuickStick123/PathOfBuilding/tree/mod-parser-refactor partially working solution is like 10x slower) and applied in other places.
Tree: "life|mana"
Uniques: "increased (fire|cold|lightning) damage"
Anoints: "critical strike (multiplier|chance)"
=> Add support for regex OR to tree and item search

src/Classes/CheckBoxControl.lua, src/Classes/ConfigTab.lua, src/Classes/DropDownControl.lua, src/Classes/EditControl.lua, src/Modules/ConfigOptions.lua
This highlights borders for controls for changed config options when
they are in non-default state. Useful for quickly checking what options
user configured and prevents forgetting about some config set by
accident (dropdowns in non-default state are especially hard to spot).
Sometimes its pretty easy to configure something by accident (either via missclick or simply forgetting about configuring it before) and it can be hard to tell if the config is in non-default state or not. Also in bigger pobs it can be sometimes hard to see what is the exact config for the pob. This solves that by subtly highlighting borders of changed config controls.
- Create new pob
- Set some control to non-default state
- See border color change
https://pobb.in/5fQaEhtVLtYj
=> Highlight borders for changed config options in config tab

help.txt, src/Classes/ImportTab.lua, src/Classes/PartyTab.lua, src/Modules/Build.lua, src/Modules/CalcPerform.lua, src/Modules/CalcSetup.lua, src/Modules/ConfigOptions.lua, src/Modules/Main.lua, src/Modules/ModTools.lua
This adds support for auras, aura debuffs and curses, all of which should be fully supported other than some condition tags and any stack variables (eg mine auras)
It also adds support for extra auras like tailwind and mana guardian and these seem to work correctly
"function modLib:parseTags" needs to be modified to correctly grab tags like conditions etc
So far the only missing one seems to be Slipstream but this could be because its applied by a minion and none of the minion mods are exported
It also adds support for enemy conditions and multipliers are modifiers, these are not handled well atm but will apply
Conditions are tagged as "Condition:Party:" instead for later filtering
The modifiers added are missing their mod tags (things like conditions etc) and thus always apply
The export …
=> Add support for Supports via Party tab

src/Classes/TradeQueryGenerator.lua, src/Data/QueryMods.lua
Some mods on the trade site are listed as being negative value of increased or similar instead of in reduced format. This adds code to switch these around as well as fixing a bug related to flasks not being parsed correctly and projectile pierce.
The only remaining problems are weird parsing behaviour from trade site (e.g. "Arrows Pierce an additional Target" has ranges for each of the mods but no #), legacy mods(still exist but have a weight of zero or unreleased), missing mods (on trade site) or multi line mods e.g. trigger mod or similar.
=> Support trade inversed mods and improve flask mod's behaviour in trader

src/Classes/ModStore.lua, src/Modules/ModParser.lua
Sublime Vision do not disables Vaal auras.
Closes #6073
Sublime Vision do not disables Vaal counterparts of the aura in game. PoB atm does.
- Grab Vaal Haste
- Grab Haste Sublime Vision
- See that both Vaal Haste and Haste work
- See that other auras are properly disabled
https://pobb.in/HpG-8yknh7lS
=> Allow Vaal auras to work as well with Sublime Vision

src/Modules/ModParser.lua
This adds proper support for the removes format introduced on crucible and fixes the local gain mods misbehaving not being treated as such.
https://pobb.in/worBBlhX4wN1
=> Fix local gain on hit

src/Modules/CalcPerform.lua
Currently with overleech env.configInput.conditionLeeching is modified directly resulting in default value checks failing on it as it was changed to non-default value not by user input. This force adjustment of configInput is unnecessary and it looks like just modifying condList is enough.
- Allocate any overleech source
- Allocate anything that depends on leeching
- Are you leeching should not have any border (or red circle or option being red like in #6125 )
https://pobb.in/883kGHg1K54F
=> Do not modify env.configInput.conditionLeching directly

src/Modules/ModParser.lua
The various effects are enabled if you are using the correct flask.
- Grab master distiller
- Enable bismuth/amethyst/diamond
- See increases in stats
- Disable the flask, see stats removed
https://pobb.in/aBVE51Q5th0V
No support
=> Add support for Master Distiller

src/Classes/TradeQueryGenerator.lua, src/Modules/Data.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/6119
The weights weren't cap / handled properly for infinite eHP this results in issues this could probably be lower or higher but 100% feels like it doesn't completely overwhelm over stats while giving a very high chance you would meet the stat that gives 100% increase. The 100% could be lowered a bit but it is tricky to strike a balance and 100% seems like a decent place to leave it for now.
See it not completely overpower over high increase stats that are desired.
See it still provide some damage mods getting through and it is still definitely suppressing stuff.
```shell 
eNrtfWt3m0i26OfRr2B5rblf4jjUG3KTOUt-uxMnju0knfOlVwGFRQeBGpAd96z572dXARLIIGHL3ffM3E6vlpHYe1fVrv2uKnjzXz-msXWrsjxKk7c7aM_esVTip0GU3Lzd-Xx9_NLZ-a9_jN5 …
```
=> Cap trader stat weight per mod to 100% increased

src/Classes/ConfigTab.lua, src/Modules/CalcDefence.lua, src/Modules/CalcPerform.lua, src/Modules/ConfigOptions.lua, src/Modules/Data.lua
This moves the values to output, though they are still in data for the tooltip funcs
This also improves the tooltip for full life, as you are not automatically considered full life above a threshold due to issues that causes, but the tooltip likely needs further fixes
=> Fix lowlife and full life percent being global (in data)

src/Classes/PassiveSpec.lua, src/Classes/PassiveTree.lua, src/Classes/TreeTab.lua
Fixes #5882, #5489, #6024
Fixing multiple crashes related to masteries while hovering, on import, and when converting from older trees. Adding details to convert success popup to show if any nodes were deallocated during the process.
- Load build, convert to 3.21, see no errors and confirm in the success popup the nodes that were deallocated
- 5489 Load build, open 3.16 tree, hover over fortify/warcry masteries, confirm no crash
- 6024 Load build, validate not allocated, hover over any mastery (Cold Mastery 44179 breaks in live)
5882 <pre>https://pobb.in/ly7av2QtcdVe</pre>
5489 <pre>https://pastebin.com/rCHGQTZ0</pre>
6024 <pre>https://pobb.in/BaVgVdTML0MQ</pre>
Hover over Warcry
Hover over Cold
<pre>https://pobb.in/o75c5diy9XfI</pre>
3.19 section (Resistance Mastery):
Convert before fix …
=> Fix multiple Mastery-related crashes

src/Classes/TreeTab.lua
When disabling show node power partway through a calculations, nodes would lose their power property. This caused a crash unless the disabling happened at precisely the right point to not run into the code I changed. Simply checking that node power exists before using the singleStat of it solved the issue.
- Open build
- Enable show node power
- Switch to full DPS
- Disable show node power
Without this change an error should appear. With it, no error should occur.
https://pobb.in/2xvFigGrZNrL
=> Fix error on disabling node power mid-generation

src/Modules/CalcPerform.lua
non player flask effect was wrong, it didnt have the base flask effect from the flask (things like alchemists or enchant) making it weaker in some situations than it was supposed to be
=> Fix local Flask effect mods not working with Mother's Embrace and Umbilicus Immortalis

src/Data/Bases/dagger.lua, src/Data/Bases/fishing.lua, src/Data/Bases/mace.lua, src/Export/Bases/amulet.txt, src/Export/Bases/axe.txt, src/Export/Bases/belt.txt, src/Export/Bases/body.txt, src/Export/Bases/boots.txt, src/Export/Bases/bow.txt, src/Export/Bases/claw.txt, src/Export/Bases/dagger.txt, src/Export/Bases/fishing.txt, src/Export/Bases/flask.txt, src/Export/Bases/gloves.txt, src/Export/Bases/helmet.txt, src/Export/Bases/jewel.txt, src/Export/Bases/mace.txt, src/Export/Bases/quiver.txt, src/Export/Bases/ring.txt, src/Export/Bases/shield.txt, src/Export/Bases/staff.txt, src/Export/Bases/sword.txt, src/Export/Bases/wand.txt, src/Export/Scripts/bases.lua
We no longer need to specify the base tags for item bases as they are already correctly pulled from the files
Also adds support for the `remove_tag` option only found on fishing rods to fix them receiving weapon mods
Fixes #5451, #6184
=> Fix export of tags for Sceptres and Fishing Rods

src/Data/Minions.lua, src/Data/Skills/act_str.lua, src/Data/Skills/minion.lua, src/Export/Minions/Minions.txt, src/Export/Skills/act_str.txt, src/Export/Skills/minion.txt
The minions needed to be added to the base skill instead of the Vaal version for supports to work on them
=> Add support for Vaal Absolution + Vaal Domination

src/Modules/CalcOffence.lua
Fixes #6008 and fixes #6029.
The life mastery with "Skills Cost Life instead of 30% of Mana Mastery" seems to function more akin to:
"Skills gain additional base life cost equal to 30% of base mana cost. Skills cost 30% less total mana."
In-game, this means that the mastery only lessens mana costs after +/- to total mana cost, but adds life cost before any modfiers have taken effect.
Ongoing discussion on whether or not this is intended: https://www.pathofexile.com/forum/view-thread/3369075
Even if it is not inteded, I think PoB should reflect the game's behaviour, and it is possible to revert the change if it turns out to be unintended.
I have also added a mention of the mastery in the breakdown of mana cost.
- Mana costs without the mastery still gives the expected value
- The Toxic …
=> Fix calculation of hybrid mana+life costs

src/Modules/CalcDefence.lua
When using Ancestral Vision, you can get sources of 0.5 ailment avoidance. PoB currently does not round this value down and instead shows a chance of 99.5 as 100 when it should display 99
=> Round down Ailment Avoid chance value

src/Modules/CalcPerform.lua
The new Crucible mod for x% increased Cooldown Recovery Rate per Power Charge did not work to increase the trigger rate of any of the triggered skills as the trigger skills were calculated before the charge multipliers
=> Fix Trigger skills not gaining cooldown from 'CDR per x Charge' mods

src/Modules/CalcOffence.lua
There's no need to show the crit breakdown for Ignite/Bleed or other ailments if you cannot crit
=> Fix Ailments breakdown showing crit damage while you have Res Technique

src/Modules/ConfigOptions.lua
The previously was no checkbox for minion skills to make the mods apply, so they could never work
=> Fix Energy Leech Support not working for Minions

src/Classes/ItemsTab.lua
Display is borked for Betrayal uniques based on some of the crucible mod changes.
Checking if the crucibleModLines is also not empty as well as nil for the crafted/crucible line-by-line in ItemsTab. I went through the build for the older PR adding this all in and it looks fine.
Seems to happen with Betrayal Uniques that are not weapons/shield. Diadem and Vivinsect and so on
<pre>eNrtXWlz2ziT_jz6FShXzVamItkEDx1eZ97yHe_aiV_ZyezulymKhCROKFJDUnY8U_nv2w3wFsHDUk3tvpOkKrFFdANo9PkAoE7-8XXlkicWhI7vvTugh8oBYZ7l2463eHfw6fFqMD74x8-9k3szWn6cn20cF5_83PvhhP9MXPbEXKA7IJEZLFj0OeGk_Qqc1qYXLZnv3Zm_-cG1b787-OB77IDMTM92ouQ3yzXD8IO5Yu8O7szA3NgsOCBmaDHPPs8e_cdmsWCBZ24ioFhCOytiwS12f7qJ_DvfhjZRsAF-K9PxHnzrC4uuA3-z5qN7ctizaHNzd_9x-pgbm-PlxwZT--Hk3jVfWPAQmREJ4Z93B6cgIXPBLswV_AvcTHcDrFQ6OpzodGgYmgL_HRzVEp9tgjB6HYeHNW …
=> Fix ItemsTab Display for Betrayal Uniques

src/Modules/CalcDefence.lua, src/Modules/CalcPerform.lua, src/Modules/ModParser.lua
This adds or improves the support for some nearby mods
a few things, unsure how to get the arcane surge effect to apply to allies due to the multiplier, shapers presence doesnt seem to do anything, and many of the other enemy "cannot crit" mods should use a flag on the enemy and not just apply an override in the players modDB
=> Improve or add support for more "nearby" mods

src/Modules/CalcDefence.lua
Fixes #6189 .
Spell suppression chance from dagger mastery did not get applied to elemental ailment avoidance when ancestral vision was equipped.
Also minimizes dependence on the dagger mod flag, hopefully avoiding future bugs where one forgets to include the flags. Do note however, if one includes the flags in `weaponsCfg` as part of a calculation, the mastery will be counted twice.
- Allocating the relevant mastery and Ancestral Vision
- Equipping 0, 1 and 2 daggers.
- Allocating Spell Supression Effect and Spell Supression is Lucky, which used to include the dagger mod flag in their calculation.
- Acrobatics does not interfere with Ancestral Vision
```
eNqtW-1z4jYT_3z8FR5mnpnnmRLiF8xLJmmHBHJHm9zlIMm1n24UW4AaYVFbTsJ1-r8_K8kGQ5FjY9qZxKD97ZtWq92N7_yXtwU1XnAYERZc1K2mWTdw4DGfBLOL-sP99Um3_svP …
```
=> Fix Suppression from dagger mastery not applying to ancestral vision

src/Modules/CalcDefence.lua
Fixes #6195 .
Unconditional spell suppresion was being double
- Allocating spell suppress node
```
https://pobb.in/5ZgQ64MSQZGx
```
=> Fix Spell Suppression being doubled with some weapon combinations

src/Modules/ModParser.lua
The Helmet Redeemer mod "Freeze Enemies as Though Dealing #% More damage" was not taken into account
The mod seemed to be defined correctly in other places and for its conditional variants, but i believe the base mod was missing from mod parser 
- Open a build using such a helmet and freezing
- Go to calculations
- Check breakdown of freeze duration includes the mod
- Double-check the mod on helmet is not red anymore
Anything that can freeze and has said mod really
https://pobb.in/5RSEidM5mXto
=> fix missing parsing for Freeze As Though Dealing More Damage

CONTRIBUTING.md
Updated git command for obtaining an Oodle extractor
[This commit](https://github.com/zao/ooz/commit/bdb3c30bc3e6dd47bfcc79a7e485503eb1d58ae4) introduced a submodule to [Zaos ooz repository](https://github.com/zao/ooz). The [current git command](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/d2124ee819e042db401454f5ac3f2091dabbf116/CONTRIBUTING.md?plain=1#LL251C55-L251C55) for cloning the repo does not include submodules, so a fresh install will be missing files.
=> Update "obtaining an oodle extractor" in CONTRIBUTING.md

src/Classes/ModStore.lua
Fixes #6193 .
Blood Magic sets the players mana to 0, which caused a division by 0 when calculating mana reservation for Supreme Ego.
This made Supreme Ego incorrectly apply to all auras at full effect.
- Allocating Blood Magic and Supreme Ego with Hatred Aura enabled, and seing that Supreme Ego has no effect.
- Supreme Ego still functions normally on Hatred, when Blood Magic is not allocated.
- Supreme Ego seems to be the only modifer that cares about the `ManaReservedPercent`-stat, so this should not affect anything else.
```
eNq9W1134jYTvt7-Ch-uScAfGNID7SHfacOGQrLbXu0RtgA3skVsmYT--nck2eCwyNjY581FYqx5RjOj0WhmRPq_f_hEW-Mw8mgwaOjn7YaGA4e6XrAYNF6eb896jd9_-6U_Rmz5NL-MPcJHfvvlS188awSvMRk0DKOhMRQuMPuWsjJ_AKsVCtgS02CE_qXhHXUHja80wA1thgLXY-knh6Ao-op8PGhMHQA3NBQ5OHCvdu8TwiUKkcNw-MinHcaMjqgLoyyMYd …
```
=> Fix Supreme Ego taking effect with Blood Magic

src/Data/Skills/act_int.lua, src/Data/Skills/act_str.lua, src/Data/Skills/spectre.lua, src/Export/Skills/act_int.txt, src/Export/Skills/act_str.txt, src/Export/Skills/spectre.txt, src/Modules/CalcSections.lua, src/Modules/ModParser.lua
Also adds the chaining tag to Dark Pact, Storm Brand, Exsanguinate and many minion skills
Also adds support for the "Arrows chain +x times" mods on quiver corruptions and crucible mods
Fixes #6204
=> Fix Chain count not appearing on Calcs page

src/Modules/CalcTriggers.lua
Doom Blast can be implemented with a few tweaks to the default handler instead of a separate handler func. Lowers the amount of duplicate code
=> Cleanup Doom Blast implementation

src/Classes/SkillListControl.lua
Fixes #2976
Path of Building treats the currently selected Main Skill as active regardless of the Enabled config in the skill group itself. This is to ensure that it can be calculated properly for the build sidebar. However, it also leads to some unintuitive behaviour for the end user, notably that any auras in the skill group are treated as enabled even though the group itself is disabled.
It's probably desireable that the main skill is treated as active, but the user needs feedback that this is the case. This PR changes the display of the main skill's skill tab group to not be coloured, and state that it's forced active, without actually changing the state of the group. This means that changing main skill back off the disabled skill will once again show it as disabled. …
=> Force skill groups to display as active based on main skill

src/Modules/CalcPerform.lua
Fixes #5939 .
No config caused mod conditions to fail and the mod from `Matua Tupuna` `20% increased effect of Non-Curse Auras from your Skills on your Minions` to not be applied. This may also be the case here:
https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/19818870af754cc17b9fa8e16c026670f20932e6/src/Modules/CalcPerform.lua#L2038-L2039
and
https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/19818870af754cc17b9fa8e16c026670f20932e6/src/Modules/CalcPerform.lua#L2230-L2231C71
but i'm not sure if adding the config there could break something so leaving as is for now.
=> Lack of config causing conditional minion aura effect mods to not be applied.

src/Modules/CalcOffence.lua
> Added a new Strength Support Gem - Volatility: Supports attack skills, causing them to deal more Maximum Attack Damage, but less Minimum Attack Damage. Supported Skills also deal increased Damage.
Not support for the gem itself, that needs to wait for gem export, but precursor to make it easier to support
=> Add support for generic damage range for Volatility support

src/Data/Skills/act_dex.lua, src/Export/Skills/act_dex.txt
Fixes #1736 
Lancing Steel was using a DPS multi for its 60% less damage with subsequent hits. This meant that it was treating the skill as if it was hitting 60% less often, rather than doing 60% less damage.
I've split the modifier into two. The DPS multiplier now scales with projectile count, while a less damage modifier is added which is 60% multiplied by the percentage of projectiles affected by the modifier (all except first)
https://pobb.in/mMOVEN0vLM9y
Difference is most notable in the max poison stacks, which should not be affected by less damage dealt
=> Fix Lancing Steel hit rate calculations

src/Data/Skills/act_dex.lua, src/Data/Skills/act_int.lua, src/Data/Skills/act_str.lua, src/Export/Skills/act_dex.txt, src/Export/Skills/act_int.txt, src/Export/Skills/act_str.txt, src/Modules/CalcPerform.lua
Fixes #669
All minion skills implied a recent use of a minion skill if they were set as primary. This adds a flag to permanent minions and excludes them from the implication. You can still use the config checkbox to enable these interactions on non-permanent minions.
- Allocated Enduring Bond, equipped Summon Holy Relic (permanent) and Summon Raging Spirits
- Deallocating Enduring Bond without the config checked does not affect Summon Holy Relic DPS but does affect Summon Raging Spirits DPS
- Selecting the config checkbox for recent minion use changes the DPS of Summon Holy Relic but not Summon Raging Spirits when Enduring Bond is allocated
https://pobb.in/89pQNZf6IFx1
=> Only imply recent minion skill use on non-permanent minions

src/Modules/Build.lua, src/Modules/CalcSetup.lua
Fixes #227
While jewels above the jewel limit don't add stats, it can be easy to miss that they're not being helpful in a finalized build. This adds a warning using the warning system that a jewel is exceeding its limit, lists what jewels are causing it, and in general adds  a framework for adding warnings based on items.
https://pobb.in/9tbjADMh0GyK
=> Add a warning when exceeding jewel limits

src/Data/Skills/act_dex.lua, src/Export/Skills/act_dex.txt
Flamethrower trap had hidden stats such as hit rate which made it impossible to accurately implement DPS for it. I asked GGG directly and got answers on how it works, so here's an implementation.
I added two skill parts, one for a single trap and one that takes into account average active traps to take into account using it as a main skill, due to its cooldown.
https://pobb.in/41YgDbTmv4EF
=> Implement flamethrower trap DPS

src/Data/Skills/other.lua, src/Export/Skills/other.txt
Fixes #5568 
Relic of the pact would error out when you achieved 100% reduced reservation efficiency. I simply added an early return in its initialFunc when life reserved percent is 100 or higher.
https://pobb.in/8o91BmwxqVjO
=> Fix crash on 100% reduced reservation efficiency for relic of the pact

src/Data/Skills/act_dex.lua, src/Export/Skills/act_dex.txt, src/Modules/CalcOffence.lua
Fixes #2486
When "Include in Full DPS" is checked for Explosive Arrow, currently PoB doesn't give it any special treatment and simply takes the "Average Damage" (of an explosion) times Attack Rate (the rate that you apply *fuses*) to get DPS. The correct calculation is Average Damage times Explosion Rate. This change implements a calculation for Explosion Rate, shown as "Hit Rate" in PoB.
The time between explosions (HitTime) is either the skill duration, or the time it take to reach the fuse limit, whichever is lower. The time to max fuses is:
timeToMaxFuses = fuseLimit / (hitChance * attackSpeed * totemLimit * barrageProjectiles)
The calculation is done in `explosiveArrowFunc()`, which lives on the skill itself and kinda looks like a preFunc, but it needs access to information that's …
=> Fix Explosive Arrow Full DPS

src/Modules/CalcPerform.lua
Fixes #6208
Applying the warcry power overrides in the actor misc section, after a lot of other stuff, caused some issues. Notably, it caused the increased spell damage from Battlemage's Cry to not apply correctly without manually setting warcry power, even when Redblade Banner was equipped.
This just moves said overrides to apply immediately prior to where warcry power is first used.
- Checked Battlemage's Cry after change, noted that stats don't change between blank and 50000 warcry power in config
https://pobb.in/2f_873aTBknM
=> Fix Battlemage's Cry and Redblade Banner not working correctly

src/Modules/CalcOffence.lua, src/Modules/CalcPerform.lua
Fixes #6210
When changing weapons between usable and unusable weapons for a given active skill, a crash would occur when the cache contained nil data for speed. This simply adds a fallback 0 for both stats, which never causes any problems because they're always hidden by skill cannot be used.
https://pobb.in/xwrfjKa9XBJ0
- Import above build
- Change weapon to any one handed axe (or any weapon that cannot be used with Lightning Arrow or Kinetic Blast)
=> Fix crash on unusable weapon swap

src/Data/Skills/act_int.lua, src/Export/Skills/act_int.txt, src/Modules/CalcDefence.lua, src/Modules/CalcOffence.lua, src/Modules/ModParser.lua
Fixes #6238 
A while back the game was updated to clarify that immunity or cannot be inflicted with does not equate to avoid chance, likely to clarify how Stormshroud worked. I've gone through PoB and updated all instances that state "cannot" or "immunity" to instead use a flag for immunity which is then applied at the very end for breakdown purposes, which bypasses Stormshroud and similar effects.
https://www.poewiki.net/wiki/Version_3.20.0#User_Interface_Changes
- Added all the relevant mods to custom modifiers box
- Tested them individually to see if they worked as expected
https://pobb.in/J43bkNYrbcBo
=> Fix ailment immune applying 100% ailment avoid

src/Modules/CalcPerform.lua
Fixes #6243
Shock nova has +10% to max effect of shock. However, when using it as a secondary skill, other skills would not be able to set max shock to those 10% higher. This meant that you could not simulate DPS accurately of other skills in situations where your alternate shock nova is able to crit for the max.
This does introduce a potential user error where they use the main skill shock tooltips to try and calculate how much they shock, but there's only so much we can do about that.
- Main skill arc, secondary skill shock nova, set shock to 60%.
- Note that without the change, max shock was set to 50% for Arc and 60% for Shock Nova. Changing shock to 50% did not alter Arc damage. 
- After change, max shock now lists at 60% for both skills. Changing shock to 50% alters damage of both. …
=> Use highest max shock from any active skill, not from main skill

src/Classes/Item.lua
Fixes #5610 .
https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5610#issuecomment-1665732781
The unmet tag was added when copying the jewel from an incompatible class causing POB to have issues parsing the class restriction.
=> Strip unmet tag from imported jewels

src/Modules/ConfigOptions.lua
Fixes #6281 .
Due to the act10 penalty value being nil self.defaultState[var] == nil failing the if statement causing the function to return 0 since the val type is "number".
0 is also the value of the none settings causing it to not be saved.
https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/19818870af754cc17b9fa8e16c026670f20932e6/src/Classes/ConfigTab.lua#L560-L578
https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/19818870af754cc17b9fa8e16c026670f20932e6/src/Modules/ConfigOptions.lua#L135
https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/19818870af754cc17b9fa8e16c026670f20932e6/src/Classes/ConfigTab.lua#L580-L582
=> Fix resistance penalty none not saving

src/Classes/Item.lua
Fixes #6289 .
The `FindModifierSubstring` function used by the `15% increased maximum Life if there are no Life Modifiers on Equipped Body Armour` mastery matched against all possible variants ignoring the currently selected one causing items such as [Skin of the Loyal](https://www.poewiki.net/wiki/Skin_of_the_Loyal) to incorrectly always match a life modifier regardless of the selected variant/keystone.
=> Fix Life Mastery not working correctly with Skin of the Loyal

src/Modules/CalcPerform.lua
Fixes #6285.
Active skills with stages and a reservation had their reservation multiplied by their stage count.
This was done to support the [Blood Sacrament](https://www.poewiki.net/wiki/Blood_Sacrament) skill from [Relic of the Pact](https://www.poewiki.net/wiki/Relic_of_the_Pact), but has unintended interactions with [Spellslinger](https://www.poewiki.net/wiki/Spellslinger). (See #6285)
- Exsanguinate + Spellslinger has a constant reservation, independent of stages
- Blade Blast + Spellslinger has a constant reservation, independent of stages
- Exsanguinate + Blade Blast + Spellslinger has a constant 2x reservation, independent of stages
- Blood Sacrament still scales reservation with stages
- There still seems to be a rounding error on the reservation, with 1 skill + lvl 20 …
=> Fix spellslinger reservation incorrectly scaling with stages

src/Modules/CalcSetup.lua
Fixes #6277
Because GrantedPassive is processed after radius jewels in CalcSetup.lua added nodes were being added to env.extraRadiusNodeList and later processed twice by jewel funcs.
=> Prevent stat doubling for radius jewels coming from GrantedPassive mod

src/Modules/CalcDefence.lua, src/Modules/CalcOffence.lua
Removes unnecessary info from the breakdown if it does not contain "elemental" or "non elemental" damage
Before: (no non-ele, still shows unnecessary clutter)
After:
note, unsure if `elseif percentageElemental <= 0 then` and `elseif percentageNonElemental <= 0 then` are the best way to check for these, they are not strictly 0 or 1 if the other doesnt exist, due to being floats, sometimes the value is something like -1.2*2^-31 (floats are strange)
=> Improve pvp breakdowns

src/Modules/ConfigOptions.lua
Fixes a typo in Uber Boss evasion rating calculation (Configuration -> Enemy Stats -> Uber Pinnacle Boss: Enemy Base Evasion). We should use UberEvasionMean for that, not Armour.
=> Fix default uber boss evasion rating

help.txt, src/Classes/TreeTab.lua
Fixes my annoyance at constantly clicking and scrolling to the bottom of a long list of trees, to find the "Manage Trees" entry and then possibly misclicking and having to do it all again.
Technical solution to a management problem
- Select the trees tab, select Ctrl-M. See that the "manage trees" dialog opens.
- Select other tabs and select Ctrl-M. Confirm that the "manage trees" dialog DOES NOT open.
-
Do we want Ctrl-M or ctrl-m ??
N/A
=> Add Ctrl-M to the tree drop down to open manage trees dialog

src/Modules/ModParser.lua
The node is not limited to attacks
- Click Adjacent Animosity
- See that config option appears
- Configure proj distance, see if projectile spell damage changed
https://pobb.in/JbPN22E_c-Ys
=> Make Adjacent Animosity work with both attacks and spells

src/Modules/CalcDefence.lua
Having no resource resulted in division by zero in calculations of that resource's recovery.
=> Fix division by zero in resource recovery calculations

src/Data/Skills/act_int.lua, src/Export/Skills/act_int.txt
Flameblast is meant to receive the bonus damage per stage from the first stage, not the second onwards
=> Fix Flameblast not gaining damage from first stage

src/Modules/CalcActiveSkill.lua, src/Modules/ModParser.lua
Relies on #6245 being merged first
=> Add support for crucible min stages/cooldown with Incinerate/Flameblast 

src/Classes/Item.lua
Fixes #6222
Two-Toned Boots were hardcoded to Armour/Energy Shield for Normal and Magic rarities when crafting. This PR updates to use the baseName.
- Check Normal and Magic Rarity for each of the three types of Two-Toned Boots
=> Fix defences on normal and magic Two-Toned Boots

src/Modules/CalcOffence.lua, src/Modules/ModParser.lua
Fixes #6237 .
Fixes `Fireball and Rolling Magma have 100% more Area of Effect` mod not being limited to just Fireball and Rolling Magma. Prevents showing breakdown for Area of effect mod if it's 1.
`https://pobb.in/s117D8xMKt65`
=> Stop crucible aoe mod from applying to any skill.

src/Modules/CalcSetup.lua
Fixes #6221 .
With no life masteries allocated `allocatedMasteryTypes["Life Mastery"]` is nil causing the value of the `Multiplier:AllocatedLifeMastery` mod to be nil which causes a crash when taking the `10% more Maximum Life if you have at least 6 Life Masteries allocated` into account for calculations.
`https://pobb.in/1lP4zWwLfT-l`
=> Fix crash when hovering over life mastery mod.

src/Modules/CalcPerform.lua
Fixes #6255 .
The source on the mods from `env.spec.tree.keystoneMap[name].modList` is always set to one from the tree ignoring the fact that the keystone it self comes from an item.
`modObj.mod.source and not modObj.mod.source:lower():match("tree")` is there to fix the source when the keystones actually do come from the tree.
=> Fix incorrect keystone source on keystones coming from items.

src/Classes/TreeTab.lua
Fixes #6090 .
Timeless Jewel find - socket name was missing because no keystone node was nearby.
I added name based on nearby classes, to follow the same pattern as already used for sockets:
- Marauder 26725
- Duelist 54127
=> Add name to top left Timeless Jewel socket

src/Data/Skills/sup_int.lua, src/Modules/CalcOffence.lua, src/Modules/CalcPerform.lua
Fixes #853
The negative fire resistance on ignited targets was applying even on skills that were unable to ignite, such as Flame Surge or anything supported by Elemental Focus. This moves the negative fire resistance effect into CalcPerform and limits it to skills that are able to ignite.
- Checked Flame Surge linked with Combustion
- Checked Fireball linked with Combustion
- Checked Fireball linked with Combustion and Elemental Focus
https://pobb.in/R6siifHKrTth
=> Only apply combustion fire resistance effect with skills that can ignite

src/Classes/TreeTab.lua
Add ability to change to whichever tree version you want. A new spec is created through conversion, keeping as many nodes as it can. Prep for Ruthless tree possibilities. It will not do anything if you select the current spec's version.
<pre>https://pobb.in/hiOrQJswyJzi</pre>
Updated to decimal notation and removed 2.6, gif is not updated but the behavior is unchanged
=> Add support for changing Tree Version

src/Modules/CalcOffence.lua, src/Modules/Data.lua
As of 3.21 this limit no longer exists
`Elemental Ailments other than Freeze are no longer discarded if their duration is lower than 300ms.`
Fixes #6325
=> Remove Minimum Ignite Duration

src/Modules/CalcPerform.lua
Fixes an issue introduced in #6320 
Combustion support was identified using the gemdata of the supports. This breaks for any supports that lack gemdata, which includes ones granted by modifiers on items. Accessing the name via the granted effect removes this nullref crash.
https://pobb.in/k0E4VLKJFSse
=> Fix a crash relating to accessing gemdata for granted supports

src/Data/Skills/minion.lua, src/Export/Skills/minion.txt
Fixes #5936 .
Due to missing skillTypes the Infernal Legion minion skill is currently not compatible with many support gems it should be compatible with.
This pr adds the skillTypes manually since the skill has been added manually but a better solution would to be export it from the game data if possible.
=> Add missing skillTypes to Infernal Legion

src/Classes/PassiveTree.lua, src/Modules/Data.lua
Improves "node in radius" calculation during passive tree loading.
Average time for socket and keystone calculation loops:
Before: 476ms
After: 30ms
Tree loading and startup time is almost half a second faster with this change.
Changes:
- Added quick bounding box check using **maxJewelRadius** before actual distance check
- Distance is only calculated once per node instead of multiple times by moving **jewelRadius** loop
- For keystone check if **nodesInRadius** was already populated because **keystoneMap** contains duplicates
- Serialized **nodesInRadius** to file and checked before/after produced same results
=> Improve node in radius calculation performance

src/Data/SkillStatMap.lua, src/Data/Skills/act_dex.lua, src/Export/Skills/act_dex.txt, src/Modules/CalcOffence.lua, src/Modules/CalcPerform.lua, src/Modules/Common.lua, src/Modules/ModParser.lua
Snipe Support was not acting as a triggered skill for the skills it was linked to, this makes it use the channel time of Snipe to trigger linked attacks
This PR does not disable the damage of Snipe if linked to a skill it can trigger and doesn't take into account the number of stages for how many linked skills it can trigger at once
Relies on #6245 to show the channel time for Snipe
https://pobb.in/AExVimiod0fE
=> Add support for triggered skills with Snipe Support

src/Modules/CalcOffence.lua
Fixes bug report from reddit.
Frozen Sweep is not used by you, the player, thus it can't be exerted. Frozen Sweep is not considered triggered, but does have a skilltype for "Other thing uses skill", for whatever godforsaken reason.
https://pobb.in/7Wy279W1JhCE
=> Exclude frozen legion from exerts

src/Classes/PassiveSpec.lua
When converting a tree to a different version, if the node changed name but not node ID, it would not allow you to allocate the node in the same location until you re-opened the build.
This just temporarily fixes the issue before we find the root cause
Fixes #6345
=> Fix Tree conversion stopping you from allocating some tree nodes

src/Modules/CalcOffence.lua
- Mana usage of skills when 'Do you wait for Max Unleash Seals' was increasing mana cost per second rather than reducing it.
-Example (using the following POB : https://pobb.in/1bHJnA2_Q3Nm):
- Unchecked: 
- 'Do you wait for Max Unleash Seals' Checked:
- Inversion of the value is already done to hitTimeOverride earlier on, so inverting the value again (the removal of which is the change I've made) results in the mana cost being higher than it should:
- Using same POB as the original example (https://pobb.in/1bHJnA2_Q3Nm)
- Unchecked: 
- 'Do you wait for Max Unleash Seals' checked:
=> 'Wait for max unleash seals' mana cost fix 

help.txt, src/Classes/TextListControl.lua, src/Modules/ItemTools.lua, src/Modules/Main.lua
This PR has a few minor tweaks to the help section,
1. making the text size and content box bigger
2. removing section numbers and content of help file and having those autogenerate
3. adding in a hotkey to open it automatically (this can open it to any arbitrary section but currently only to the top, does it if f1 is pressed and no link to wiki is opened)
4. adding fast scroll to help sections and changelog
I am not very happy with the implementation of the hotkey, also would like it to open to a relevant section instead of just the start, and wonder if a should cache the help/version history
=> Help section improvements

src/Data/SkillStatMap.lua, src/Modules/ModParser.lua
Fixes #6360
`TotemDuration` mods were not used anywhere. I converted them to `mod("Duration", "INC", nil, 0, KeywordFlag.Totem)`.
=> Fix totem duration mods not applying

src/Modules/CalcOffence.lua
The block was inside the 2 pass loop so was running twice
Also fixes the issue when you used a custom `more DPS` mod
=> Fix DPS on Vaal Flicker when using 2x 1h weapons

src/Data/SkillStatMap.lua, src/Data/Skills/act_dex.lua, src/Export/Skills/act_dex.txt
Fixes #6375  .
Adding RepeatCounts didn't have any flags to make sure they actually belonged to the skill they were supporting.
- Added Summon Skeletons, supported by Spell Echo and Multistrike
- Verified mana cost is only affected by the repeat count from spell echo and not multistrike
- Regression tested Multistrike with Infernal Blow
See issue
=> Apply RepeatCount according to their SkillTypes

src/Classes/PassiveSpec.lua
Fixes issue where you cannot allocate a node that was ignored for id/name reasons on tree conversions
- Allocate Chieftain Ascendancies on 3.21 (e.g. Valako, Tasalio, Tawhoa, Ramako)
- Convert to 3.22
- Check to see which nodes should have been ignored due to node id/name mismatch, verify not allocated (all but Ramako)
- Verify able to allocate ignored nodes without needing restart
--
- Allocate Dirty Techniques on 3.21
- Convert to 3.22
- Verify Dirty Techniques and two linked nodes are not allocated
- Verify able to allocate all three without needing restart
https://pobb.in/uvWbMkbWLyUZ
=> Fix allocation issue on tree conversion

src/Modules/Build.lua, src/Modules/CalcSections.lua
The channel time stat wasn't using the `lowerIsBetter` flag
=> Fix lower channel time stat using red text

src/Modules/ModParser.lua
The mod was not displaying in the breakdown as it was using the dot flag instead of `DamageTakenOverTime`
Fixes #6398
=> Fix "Enemies maimed by you take inc damage over time` not in breakdown display

src/Modules/CalcPerform.lua
Snipe damage goes negative when the Snipe stages field is empty or 0. This pr sets the minimum stages of self cast Snipe to 1 but without the damage mods. To get the damage mods the user would need to set the Snipe stages box to one (this will result in the same cast rate).
=> Fix Snipe damage going negative

src/Modules/CalcSetup.lua
Looks like node.finalModList is not initalized when hovering trees, this simply null checks it.
Closes #6405
When hovering trees in PoB you get error about finalModList being null.
- Open PoB with multiple trees
- Hover different tree
- Observe crash
https://pobb.in/u/thedeathbeam/pf-poison-scourge-arrow
=> Null-check node.finalModList when hovering trees

src/Data/SkillStatMap.lua, src/Data/Skills/sup_dex.lua, src/Data/Skills/sup_int.lua, src/Data/Skills/sup_str.lua, src/Export/Skills/sup_dex.txt, src/Export/Skills/sup_int.txt, src/Export/Skills/sup_str.txt
basic functionality of these 3 supports, does not yet support alt quality devour, or minimum projectiles on locus mine, everything else either works or does not work on other supports in PoB anyway (eg throw extra mines)
planning on adding alt quality devour support as well as controlled blaze and fresh meat if I get time
=> add devour, volatility and locus mine support

src/Modules/CalcPerform.lua
Added damage was still contributing to the damage of the skill so it was showing DPS numbers even if the skill was actually dealing no damage
Also removes the debug tooltip I forgot to remove from testing
=> Fix Snipe showing DPS values when triggering support skills

src/Data/Skills/sup_str.lua, src/Export/Skills/sup_str.txt
Currently Guardian's Blessing do not makes supported aura not reserve mana in PoB. This implementation mimics Eternal Blessing but with aura limitation
- Enable Guardian's Blessing and link it to aura 
- See that aura no longer reserves mana and costs nothing
https://pobb.in/qNFYY0DNywHf
=> Add support for Guardian's Blessing no reservation for auras

src/Data/SkillStatMap.lua, src/Modules/CalcTriggers.lua, src/Modules/ModParser.lua
The wording for the ascendancy mod from [Tawhoa, Forest's Strength](https://www.poewiki.net/wiki/Tawhoa,_Forest%27s_Strength)
has changed in the latest tree update causing it to not be parsed. Also update the triggerSkill conditions to reflect Tawhoa's Chosen now supporting strike skills as well.
=> Update mod wording and skill conds for Tawhoa's Chosen

src/Data/Uniques/flask.lua
Fixes #6406 .
Wiki says `Cinderswallow Urn now has +90 to maximum Charges, and has 175-200% increased Charges Used.` but the implemented variant has: `Cinderswallow Urn now has +90 to maximum Charges, and has 300-250% increased Charges Used` 
https://www.poewiki.net/wiki/Cinderswallow_Urn
=> Fix incorrect increased usage mod range on Cinderswallow Urn

src/Classes/PassiveTreeView.lua
Fixes #6373  .
Hover box for masteries shows all masteries when it might be more clear to only show available ones.
- Hover over mastery, allocate one
- Hover over same mastery category, find it without the previously allocated mastery
=> Removing allocated mastery from hover list

src/Modules/CalcSetup.lua, src/Modules/CalcTriggers.lua, src/Modules/ModParser.lua
Fixes #6385
The ExtraSupport mod parser logic always added an extra mod for the secondary effect which was not always there. If the secondary effect was a skill not a support as is in the case of Doom Blast the skill would be added to the list of supports which prevents it from appearing in the skills drop down.
=> (BETA) Fix secondary effect skills being added as supports

src/Modules/CalcOffence.lua
The config was not affecting the number of bleeds/ignites affecting the enemy and was instead only affecting the average roll %
Ignite and Bleed roll % was not calculated to be at least 50% roll as a minimum
Ignite was also not taking into account Hit Chance when calculating the average roll
Breakdowns were improved to show the potential when max stacks is more than 1
Fixes #6366
=> Fix Bleed/Ignite Stack potential issues

src/Classes/TreeTab.lua
Small QoL for the version dropdown. On switching to any spec, this will update the dropdown to match the version.
=> Version dropdown QoL

src/Data/Minions.lua, src/Data/Skills/other.lua, src/Export/Classes/GGPKData.lua, src/Export/Minions/Minions.txt, src/Export/Skills/other.txt, src/Export/spec.lua, src/Modules/ModParser.lua
Adds support for the new Guardian minions to show in the sidebar. The level is manually set to 85 right now as we don't support the `minion_actor_level_is_user_level_up_to_maximum` stat yet
=> Add initial support for Guardian Minions

src/Classes/PassiveTreeView.lua
Ascendant nodes don't have an `sd` list, so this adds a check for that when hovering
=> Fix lua error when hovering Ascendant nodes

src/Modules/CalcDefence.lua
Fixes https://www.reddit.com/r/pathofexile/comments/15zn4nx/path_of_building_community_2320_322_tattoos_gems/jxipf1u/
Missing source was causing a lua error when hovering over resistance breakdown in calcs tab. Additionally,  the lack of filtering for base mods on the normal resistance logic block caused the base -60 res mod to be incorrectly taken into account.
=> Fix missing source and lack of base mod filtering on resistance conversion

src/Modules/CalcOffence.lua
I forgot to change the breakdown reference when copying it from Bleed
=> Fix Crash when using Ruthless Support in a Poison build

src/Data/Skills/act_str.lua, src/Data/Skills/sup_str.lua, src/Export/Skills/act_str.txt, src/Export/Skills/sup_str.txt, src/Modules/CalcOffence.lua
Trauma was pulling its duration from the skill instead of the gem
Fixes #6462
=> Fix Trauma duration sometimes using skill duration

src/Modules/CalcDefence.lua, src/Modules/ModParser.lua
The order of calculation in CalcDefence  had to be moved so the leech stuff was done first
=> Fix Strength of Blood not working

src/Modules/ModParser.lua
Fixes #6484
The `Supported` at the end of `Socketed Gems are Supported by Level 20 Elemental Army Support` was breaking parsing of the mod.
=> Fix supported by edge case

src/Modules/CalcSetup.lua
Fixes #6501 .
Error when trying to search for jewels while having Ngamahu, Flame's Advance allocated.
- Verified that searching for jewels works in that case
- Verified that comparison of stats works in this case
-
https://pobb.in/ZDkv-dD8zI83
=> Fixed an error when searching trade for jewels (Issue #6501)

src/Data/Skills/sup_str.lua, src/Export/Skills/sup_str.txt, src/Modules/CalcTriggers.lua
Fixes #6498
Fixes infinite recursion crash when selecting another gem to add to a group with a totem supported Flame wood. Fixes Ancestral Bond disabling Avenging Flame.
=> Fix flamewood crash and Ancestral Bond interaction

src/Modules/CalcOffence.lua
Fixes #6500  .
There was an errant check that Spellblade support multiplier had to be above 100% before applying.  This simply removes that check.
- Checked added spellblade damage before and after removal
=> Fix Spellblade not scaling past level 13

src/Data/Skills/sup_str.lua, src/Export/Skills/sup_str.txt
Tested in game to make sure, and the skill definitely scales with those 2 stats
=> Fix Flamewood support not scaling with spell and projectile damage

src/Classes/PassiveSpec.lua
When we added the fix for the other Timeless jewels, we forgot to include this one
=> Fix Militant Faith jewel not overriding small attribute tattoos
