src/Modules/ModParser.lua

Fixes #6491
Due to a type mismatch the group was being re-created inside of initEnv and the fullDps toggle was being lost.

Fix full dps not working for skills coming from triggerExtraSkill

---

src/Data/Skills/act_dex.lua
src/Data/Skills/act_str.lua
src/Data/Skills/other.lua
src/Data/Skills/sup_dex.lua
src/Export/Skills/act_dex.txt
src/Export/Skills/act_str.txt
src/Export/Skills/other.txt
src/Export/Skills/sup_dex.txt
src/Modules/Build.lua
src/Modules/CalcActiveSkill.lua

Fixes #6493
Mirage archer can be triggered by a skill triggered by mana forged but will not attack. Current the skill is disabled as it finds more than one trigger.

Fix mirage archer and manaforged interaction

---

src/Modules/CalcTriggers.lua

The fix to Flamewood caused many other skill that have the Inbuilt Trigger flag to ignore their source rates.

Flamewood fix breaking doom blast

---

src/Modules/Data.lua

Minor performance improvement, it was having to loop through all minion skills for a devmode check, tbh I dont know how many people use this anyway, so preserving the console print instead of removing it completely

move devMode check out of the loop

---

src/Modules/CalcOffence.lua

The value used in the breakdown box comes from the calcAilmentDamage function. Since the baseMaxVal calculation was last, it would assume 100% crit chance and only show the chance to inflict the ailment on crit
https://pobb.in/XvIhzZoTWsko
Old
New

Fix chance to Inflict ailments breakdown

---

src/Data/Skills/act_int.lua
src/Export/Skills/act_int.txt
src/Modules/CalcOffence.lua

The chance to Shock and damage conversion mods are meant to apply as global buffs per Energy Blade you have equipped, so when dual wielding they should be applying twice
Also fixed the mods to be unscalable as they shouldn't be affected by buff effect
Fixes #6372

Fix Energy Blade alt qualities failing to apply twice when Dual Wielding

---

src/Modules/Common.lua
src/Modules/Main.lua

Sorts ModCache when it's generated.  Was working on some startup optimization involving ModCache and it helps to have it sorted to have useful diffs.  Only adds about 25ms to generation time.
Didn't include the new ModCache file itself. You'll have to generate it to see the sorted file.
- Tested generating ModCache

Sort ModCache when generated

---

src/Modules/CalcTriggers.lua

Fixes issue mentioned on discord. 
Chocolate02:D_Hexes 
Unique item triggers were applying their configs to any skills regardless of whether that skill was triggered or not.

Limit application of unique item configs.

---

src/Classes/Item.lua

Fixes #6533
The find modifier code was checking all variants of unique items for mods, notably breaking Utula's chest with Clayshaper due to the old minion life mod.
This adds a check that a mod line is active for the currently selected variant.
- Checked Utula's chest against clayshaper and any unique that has a life mod on current variant
- Checked Utula's chest against an old clayshaper variant
https://pobb.in/3rBt_2a39lPD

Only check for mods on current variants of unique items

---

src/Modules/CalcTriggers.lua

Fixes  #6554
Disabled skills were considered valid sources for cwc which causes a crash as `source.skillData.triggerTime` is assumed to exist for valid sources.
Disabled skills will now be completely ignored.

Fix crash caused by trigger source being disabled.

---

src/Data/Skills/sup_int.lua
src/Export/Skills/sup_int.txt
src/Modules/ConfigOptions.lua

Guessing it was left over from when Wires copied over the config for Adrenaline
Fixes #6557

Fix Fresh Meat Support incorrectly granting all minions Adrenaline

---

src/Classes/ImportTab.lua

Fixes a bug that was introduced in #6446 where it would duplicate the abyssal socket explicit modifiers on imported items that weren't energy blades. Specifically, Stygian Vise in general and Darkness Enthroned were affected by this.
Checked with Wires, the insert of the mod was only intended for energy blades, so adding a conditional for that.
- Checked imports with both Stygian Vises and Energy Blades with abyssal sockets, both work as expected
Import Strong_and_intelligent from Xeverous (Ancestor League), or BeethovensRagingSpirit from Lordofdiamonds (EOE Moana league)

Only add abyssal socket if the item is an energy blade

---

src/Classes/ModStore.lua

The item states that jewels do not count as equipped for the purposes of the mod in question, so this excludes them from PoB slot checks for item conditions. 
Flasks are also not checked, but already aren't included in the actor itemlist.
- Checked Utulas and life mastery, both work as intended
https://pobb.in/7Z5o3jqxuueW

Exclude jewels from all slot equipment checks

---

src/Classes/ItemsTab.lua

Fixes #6548 
#6056 introduced an error in cases where mods that scaled in a positive direction were inverted incorrectly, such as the shaper body armour mod for crit chance to spells. It used the value 1 to check for discontinuity between tiers, which works for almost all mods, but for mods with a step of less than 1 it caused issues.
Specifically, it inverted the ranges even for positive mods when the difference between minimum and maximum of different tiers was exactly 1, which for the mods in question applied since the first mod starts at 0.5 and the second ends at 1.5.
Optimally we'd somehow fetch the step value, but I don't have the time or energy to delve into the stat descriptions right now. Looks like divide_by_one_hundred is how we'd find the step value though.
This adds a check …

Fix some mod ranges being inverted

---

spec/System/TestItemParse_spec.lua
src/Classes/Item.lua
src/Modules/ItemTools.lua
src/Modules/Main.lua

These changes improve PoB startup time by about 970 ms.
main:Init() average time
Before: 2709 ms
After: 1738 ms
Changes:
- In ParseRaw first loop that creates self.rawLines now done with one gmatch call.
- processInfluenceLine function replaced with lookup table.
- "specName, specVal" parsing done with less string match calls.
- Line flags like "{crafted}" or " (implicit)" are all parsed with just 2 gsub calls instead of the many match calls like before.  These 2 gsub calls also replace the many gsub calls to remove the flags from the line.
- NormaliseQuality was called at the end of ParseRaw then again in Main:Init.  Instead the call from Main is moved into ParseRaw as well.  I'm not sure if NormaliseQuality should have different results if you call it twice in a row but I already …

Optimize loading items, improve startup time

---

src/Classes/TradeQueryGenerator.lua

Useful when leveling or changing gear while not at a high level (for example, trying to buy rings at level 70 sometimes gets you level 80 atlas bases).
Getting suggested items that you're not able to equip because of your level. This could also be expanded to stat requirements.
- Added a new EditControl to the query popup, next to the "Max Price" field.
- If the number is set and higher than 0, add the filter to the query.
- It does not set a default number since most people don't have to worry about this, but it's optional for leveling characters.

Added max level field to the trade query generator

---

src/Classes/CalcsTab.lua
src/Modules/CalcPerform.lua
src/Modules/CalcTriggers.lua
src/Modules/Calcs.lua

Fixes #6467 and potentially #4666
Cost warnings were always calculated even for CALCS and CACHE modes which slowed down heat map generation considerably.
Heat map when in FullDPS mode was incorrectly looking into minion output for full dps variable to compare causing no changes to show up. #6467
I'm not sure what the `forceCache` code implemented in https://github.com/PathOfBuildingCommunity/PathOfBuilding/commit/8fbfe6e1ca5c78fb6e0e1b2b37f791c5cedb87d9 was supposed to accomplish but it's causing issues by caching only partially computed skills.
- Test vaal skills since they were mentioned in https://github.com/PathOfBuildingCommunity/PathOfBuilding/commit/8fbfe6e1ca5c78fb6e0e1b2b37f791c5cedb87d9
- Test caching vars by testing triggers
- Test builds from #6467 and #4666
- Test warnings

Misc FullDPS fixes

---

src/Data/ClusterJewels.lua
src/Export/Scripts/cluster.lua

The legacy clusters still exist in standard and can be crafted but they can deceive people in the temp leagues as they are no longer possible to get
This should make it clearer

Add legacy tag to Clusters that no longer drop

---

src/Classes/CalcsTab.lua
src/Classes/TreeTab.lua

New Feature: User selectable limiter on node depth for Node Power heatmap generation.
Currently, generating the full heatmap can take multiple minutes for certain builds on slower machines. In the vast majority of cases the user doesn't care about nodes more than a certain distance away from currently allocated nodes. By giving the user a dropdown to choose to only check against nodes with a max distance we can dramatically speed up the operation.
Too much choice seemed frivolous so I went with only 5 and 10 . We could easily expand this to more choices if we wanted. More than 10 is often close to the entire tree anyway for many builds.
Generate a Node Power heat map after selecting from the new dropdown to the right of the checkbox on the Tree Tab.
All builds will show this …

Limit Node Depth in Heatmap generation

---

src/Modules/ModParser.lua

minor consistency change, rather than overriding the enemy crit chance in the players modDB, actually setting flags on the enemy itself

update enemy crit chance overrides to actuly use flags on the enemy

---

src/Classes/ImportTab.lua

Fixes #6218 
Adds checkbox beside item/skill import button to ignore weapon swap items and skills. Defaults false; must opt-in.
Can import one of mine, Peechey, SSF, Peechey Gladiator
I've got an item and gem (lacerate) in weapon swap. Import unchecked to bring it in, import checked to verify gone.

Add support for ignoring weapon swap on character import

---

src/Classes/TreeTab.lua

Improvements to version convert: allow users the choice to replace or backup current spec _before_ conversion. Works/looks better with pr 6365 but I want to keep them separate in case we don't add this.
- Convert should replace the current spec and active spec should be the converted spec
- Copy + Convert should have both with active spec => converted spec
- Cancel do be canceling
- Outside of the popup, Convert to latest should still work and show the success popup

Add confirmation popup for tree version convert

---

src/Classes/PassiveSpec.lua
src/Classes/PassiveTree.lua
src/Launch.lua
src/Modules/Main.lua

Improves startup time by about 400 ms.
AddMasteryEffectOptionsToNode was combining all mastery option mod lines into one node.sd and then calling ProcessStats which led to many mod lines being combined in an attempt to parse them.  These combined lines shouldn't be combined for parsing since they come from different mastery options and they also weren't cached so parsing them was very slow.
This change adds a new startIndex parameter to ProcessStats so it can incrementally parse the mastery options as they are added by AddMasteryEffectOptionsToNode instead of parsing them all at once.
Also added new "Startup time: #### ms" print message that measures from start until the first OnFrame call finishes.  I was measuring just Main:Init before but there is some init code in the first OnFrame …

Optimize AddMasteryEffectOptionsToNode, improve startup time

---

src/Modules/CalcPerform.lua
src/Modules/Calcs.lua

https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/6566 removed `avoidCache` variable, moving the `fullDPSSkipEHP` in its place in the `calcs.performs` function arguments. I forgot to correct arguments for a call inside of `calcs.getMiscCalculator(build)` causing the issue.

Fix tooltip stats comparison always showing ehp calcs.

---

src/Classes/ItemsTab.lua

Fixes #6620
Mods that had no range for its value (gain flask charges when hit on flasks, reduced attribute reqs on weapons) the code to flip the ranges crashed. This simply early returns false when one or both of the mods is not a range.
- Tried crafting a flask with charge gain on hit and a weapon with reduced attribute requirements.

Don't try to flip ranges that aren't ranges

---

src/Modules/Data.lua
src/Modules/Main.lua

Only in dev mode, improves startup time by about 1200 ms.
Printing to the initial green console that uses native Windows controls is very slow.  This change delays printing missing minion skills until after the native control console closes.  Fixing the console requires changes to SimpleGraphic.dll so easier to do a workaround in Lua for now.

Improve dev mode startup time

---

src/Classes/CalcsTab.lua
src/Classes/PowerReportListControl.lua
src/Classes/TreeTab.lua

"Show allocated nodes" button is overlapped by "Show/Hide Power Report" button after #6598.
This change adds a dropdown instead that replaces that button and the "Show clusters" checkbox.  The "show allocated" max path filter box was removed.  I think sorting by points column instead is good enough but let me know.
You can also "Show Power Report" immediately now instead of waiting for the first run to finish.
- Tried different power stats
- Sorted by all power report columns
- Toggled off and on "Show Power Report" and "Show Node Power" in various states

Fix "Show allocated nodes" button and convert to dropdown

---

src/Modules/CalcBreakdown.lua
src/Modules/CalcOffence.lua

The block the code was in ran twice as it would run once for each weapon. This divides the rate in 2 when dual wielding before adding it to the multiplier
Also fixes the breakdowns as they were very clustered before and included unnecessary values
Added the noTotal part to multiChain breakdowns so it doesn't show the total value when you don't want to appear
Fixes #6555
Before:
After:

Fix Trauma Rate doubling when dual wielding

---

src/Classes/CalcBreakdownControl.lua
src/Classes/ModStore.lua
src/Data/Skills/act_dex.lua
src/Data/Skills/act_int.lua
src/Data/Skills/act_str.lua
src/Export/Skills/act_dex.txt
src/Export/Skills/act_int.txt
src/Export/Skills/act_str.txt
src/Modules/CalcDefence.lua
src/Modules/CalcOffence.lua
src/Modules/CalcPerform.lua
src/Modules/CalcSections.lua
src/Modules/ModParser.lua

Built on #5959 (merge that one first)
adds support for more link mods, has a few remaining issues 
1) currently vampiric link does not share its leech amount, just make leech, it causes issues trying to get exact leeches with the pass system
2) missing flasks from belt
3) destructive link has issues, basic mainhand crit chance is not calculated (eg default attack) so unable to grab it

Link skill improvements

---

src/Modules/Build.lua

Reduce OnFrame memory allocation from about 4.5 MB/s to 0.1 MB/s when PoB is active and on tree tab.
EstimatePlayerProgress is called many times per frame because it's used for the width of a control several other controls anchor off of.  In the function a local table is created which allocates over 4 MB/s because of how often the function is called.  The memory does eventually get garbage collected but this is extra work that isn't needed.
Moved the table to outside the function and did some other minor refactoring.
- "pointDisplay" control at the top still displays correct points spent and the tooltip shows same progress as before
- Toggling level mode between Manual and Auto still works
Before/After with PoB window active:

Reduce EstimatePlayerProgress memory usage

---

src/Classes/ItemDBControl.lua
src/Modules/Common.lua
src/Modules/Main.lua

Improves startup time by about 1030 ms.
Moved item loading to coroutine.  Item DB controls show "Loading..." until items are loaded.  If ModCache is being generated then items are loaded without a coroutine so they load before cache saves.
Also added new pairsYield utility function.
- Item DB shows items after load completes, filtering and sorting works
- Tested ModCache generation

Add item load coroutine to improve startup time

---

src/Launch.lua

Show version/branch at bottom of error box.  Allows confirming version/branch when people send error screenshots.
- Tested in dev and release master/beta branches

Show version and branch in error box

---

src/Classes/ImportTab.lua

I often help people optimize and fix problems with their builds, and most of the time only want to import their account once.  This has led to me having a large list of account names that I had no intention of importing again in the future.  I know I can remove them manually from the settings.xml file, though I figured this might be a nice feature since this is a more convenient method, and some might not know to do that, 
- Add some accounts to the list by importing them
- Click remove and the selected account will be removed from the dropdown, as well as from the settings.xml file once changes are saved
https://github.com/CrazieJester/PathOfBuilding
And after clicking the X button with CrazieJester selected

Add a remove account button to ImportTab

---

src/Modules/CalcPerform.lua

Minor fix, now checks if it is a varlist instead of just var, but currently only checks the first var instead of all in the list, this only affects stormweaver which should almost always be triggered by shock instead of frozen anyway
The method for grabbing "valid" enemy mods is still very messy and should be cleaned up at some point

Fix Party tab export crash for the node storm weaver

---

src/Data/ModMap.lua
src/Modules/CalcPerform.lua
src/Modules/ConfigOptions.lua

Map mod added in 3.21.0
> Added a series of new "Profane" modifiers that can roll on Maps, Logbooks, Delve Biomes, and Heist Contracts. These modifiers cause Monsters to deal extra Physical Damage as Chaos and cause Monsters to Inflict Withered for 2 seconds on Hit.
edit, added config for wither, unsure how to make it apply maximum if not set, but should be mergable as is

Add Profane Map Mod

---

src/Modules/Main.lua

If you use the hotkey to open the help popup, it will open it at the current tab if it exists (and named correctly) in the help file (eg currently party tab and items tab), 
This could be done better by tagging what the tab is actually called in the help file sections to match that instead of section name, but this works for the 2 tabs we currently have help sections for

Attempt to open help popup at index of current tab

---

src/Classes/ImportTab.lua
src/Classes/Item.lua

Magic items imported from an account weren't getting names imported correctly.  See Discord report here: https://discord.com/channels/645607528297922560/680796887259021342/1150820315878928394
- Imported flasks
I'd love to write some unit tests around this bug, but the item import code needs to be pulled into the Item class or at least made more testable.  I've left that for a separate PR for now.

Fix imported magic flasks missing their implicits

---

src/Modules/CalcMirages.lua

Fixes #6664 .
When calculating the Trigger Rate Cap of Tawhoa's Chosen the duration was added to the cooldown, but this behavior has changed in the game with the current Version (3.22). 
- The Trigger Rate Cap does not add the Duration of the Skill to the cooldown
- The Skill Trigger Rate and the DPS of Tawhoa's Chosen is calculated accordingly.
https://pobb.in/MkLqsOqQ4KPt

remove triggerDuration from Tawhoa's cooldown calculation

---

spec/System/TestItemParse_spec.lua
src/Classes/Item.lua

Fixes a bug with not parsing magic Two-Toned boots with a prefix or suffix when you copy/paste them into PoB, or into "Create custom...".  Added a fix and test case for it.  Also added a few more tests to cover more stuff.
- Added new tests
- Copied magic Two-Toned Boots into PoB
- Crafted all variations of magic/normal Two-Toned Boots

Fix magic Two-Toned Boots and add tests

---

src/Classes/PartyTab.lua

The special case for adding the party members life to the modDB is unnecessary as its grabbed directly out of output anyway, so removing unnecessary code that may cause bugs in the future if that modDB is used

Party Tab, remove unnecessary addition to modDB for player life

---

src/Classes/EditControl.lua
src/Modules/Main.lua

Fixes #6634.
Allow Unicode input in EditControls when running under [PoeCharm](https://github.com/Chuanhsing/PoeCharm).  Added a DetectUnicodeSupport function that uses DrawStringWidth to detect if running under PoeCharm and if so changes the default input filter on EditControl.
I couldn't figure out how to test Unicode input in PoeCharm, even the file boxes it should already work in didn't work for me when I switched Windows languages to try it.  Maybe someone that knows more about PoeCharm can test.
- Tested normal PoB still filters Unicode on those controls
- Tested DetectUnicodeSupport works in PoB and PoeCharm

Fix Unicode input for PoeCharm

---

src/Modules/CalcDefence.lua

if you got the effect high enough PoB assumed you took negative damage, this caps it at 100% taken over time

Fix negative EHP from progenesis by capping its effect

---

src/Data/Skills/sup_dex.lua
src/Export/Skills/sup_dex.txt
src/Modules/CalcOffence.lua
src/Modules/ConfigOptions.lua

Adds config options for amount of momentum (if not average)
If not set it correctly gives you the correct average amount of momentum, taking into account the extra from +1 
(though both the average and the +1 are incorrect if channeling skill)
also grants movement speed per removed momentum charge, (though this is missing a cap)

Add support for Momentum support

---

src/Modules/Main.lua

Better PoeCharm detection that doesn't rely on DrawStringWidth using invalid glyphs.  Checks for global utf8 table instead.
- Tested in PoeCharm and normal PoB

PoeCharm detection now checks for global utf8 table

---

src/Modules/CalcMirages.lua

Full dps calcs check for env.player.mainSkill.mirage table to check if the skill is additionally used by a mirage (Mirage Archer). This causes issues with mirage skills that use the skill directly (such as Reflection from the Savior).
https://pobb.in/6hf3v5bOtZni

Fix crash when using Saviour Mirages in FullDPS

---

src/Modules/CalcTriggers.lua

Fixes #6653 .
Cast While Channeling support requires the source skill to not have the SkillType.SummonsTotem tag. The handler func was not checking that and then used a value which is added by:
```Lua
skill("triggerTime", nil, { type = "SkillType", skillType = SkillType.Channel } ),
```
which did not exist because cwc was not supporting that trigger source.

Restrict trigger source for CwC using CwC gem tags

---

src/Data/ModCache.lua
src/Modules/ConfigOptions.lua
src/Modules/ModParser.lua

Fixes parsing for some mods from the pantheon

---

src/Data/Skills/sup_str.lua
src/Export/Skills/sup_str.txt
src/Modules/CalcOffence.lua

Fixes #6597
Filtering is done in CalcOffence. Don't see much of a point in adding extra filtering using the ModStore.
As the issue mentions this interaction has not been confirmed but would be consistent with other skills.

Fix Fist of War not applying to projectile skill parts

---

src/HeadlessWrapper.lua
src/Modules/Main.lua

Due to modCache being sorted now and the decision being made to include it in pull requests this should be unnecessary and only slows down test runs.

Disable forced ModCache regen for tests

---

src/Classes/CalcBreakdownControl.lua
src/Classes/ModStore.lua
src/Data/Skills/act_int.lua
src/Export/Skills/act_int.txt

Fixes #6688
Divergent Arcane Cloak was scaling the added damage by a per stat instead of a percentage stat.
This supports using a multiplier variable in place of the percentage value.
I also did some testing in-game and Arcane Cloak and other similar effects appear to round up the final value so I changed that logic too
- Test Divergent Arcane Cloak in-game to figure out rounding
- Test build and now have the expected results and gem quality increases the damage in smaller increments
https://pobb.in/uW97FHR2LA7u

Fix Divergent Arcane Cloak

---

src/Data/Skills/act_int.lua
src/Export/Skills/act_int.txt
src/Modules/CalcPerform.lua

Scorching Ray's stacks do not fall off while channeling so the calculation for sustainable stacks was completely incorrect. Replaced with a manual max stacks override

Fix Scorching Ray Max Stacks

---

src/Classes/PassiveSpec.lua

Mastery nodes always get and index of 0.  Some nodes on cluster jewel could also have an index of 0.  Rarely, if Lua happened to iterate through the nodes and reached the mastery node first, it'd try to allocate it and fail, exiting the loop entirely.  Imported nodes should never contain a mastery node for a cluster jewel, so this check was just checking the wrong node for if it's a mastery or not.  This PR corrects that change.
- Verified against one example of this bug: https://discord.com/channels/676181894152454150/676256416218218496/1151613833224400966
No link applicable, because it only happens on character import.  This was one example, but you may have to ask them to reallocate nodes, as their character has changed since testing: gladvold -> diyu_chiefGoBoom

Fix rare bug affecting allocating imported cluster nodes

---

src/Modules/CalcTriggers.lua
src/Modules/Common.lua

Fixes issue [mentioned on Reddit](https://www.reddit.com/r/pathofexile/comments/16hofhg/path_of_building_community_2340_socket_group/k0ey9r0/)
TotalDPS uses HitSpeed if available. It would probably make sense for triggers to do the same.
https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/31c0990987cad6fedd75d5fdbfb4863c4bf3eaf5/src/Modules/CalcOffence.lua#L3128
This may break some interactions but seems to work correctly for Static Strike and Kitava's Thirst.

Use HitSpeed as source rate if avilable

---

src/Modules/ModParser.lua

Fixes #6708
Stat convert jewels are taking the +4 of the tattoo and treating like +4 of each, converting whichever applicable. This PR changes the stat convert jewels to ignore stat tattoo nodes. Timeless jewels are still adding stats to the nodes. This should only affect stat conversion. Other conversion jewels like Green Nightmare should affect tattoos as before.
I thought about adding another field to getSimpleConv and passing true or whatever for the 3 stats when parsed to use in the conditional. Or could check the type of "BASE" as I think that's only parsed by these stat conversion jewels for this function. If you see a cleaner way, lemme know.
<pre>eNrVHGtz2rj2c_MrNMzsTDubBGzMK5PsDiEvbpOWBdLe-2lHMQK0kS0qy0noTv_7PZJscCh2bPDcndsPKVjnraPzkpPT3188hp6ICCj3zyrWca2CiO_yCfVnZ5X78dVRu_L7bwen …

Fix Honoured Tattoo of the Tuatara interaction with Stat Conversion jewels

---

src/Classes/PassiveTreeView.lua

Fixes #6682
Tooltip for nodes that can be allocated with intuitive leap showed stats for path allocation. This pr makes the tooltip only show the difference the hovered node makes. Additionally includes some improved breakdown information.

Tooltip showing path allocation difference for intuitive leap allocatable nodes

---

src/Modules/ConfigOptions.lua

I intended this default to the maximum value when I added it, but wanted to apply it in code, it doesnt seem to place nicely, so doing this with placeholders instead

Set placeholder default of 15 for wither on self from map mod

---

src/Modules/CalcOffence.lua

This was moved in #6380 and the cfg was not updated to use the out of the loop cfg, and so was always nil

Fix dps multiplier cfg

---

src/Data/Skills/act_int.lua
src/Data/Skills/act_str.lua
src/Export/Skills/act_int.txt
src/Export/Skills/act_str.txt

Ice crash, immortal call, petrified blood, stormbind, and glacial cascade all have stats which are supported but are on a different stat to the displayed one, this just turns the text to the correct colour of blue

Fix gem display issues with red text when supported

---

src/Modules/CalcTriggers.lua

Fixes #6730
Prismatic burst, shockwave and combust looked for trigger sources outside of their socket groups. This pr cleans up triggered flags as they are checked in main loop through isTriggered func.

Cleanup trigger source permissions

---

src/Classes/ConfigTab.lua
src/Data/Skills/act_dex.lua
src/Export/Skills/act_dex.txt
src/Modules/CalcTriggers.lua
src/Modules/ConfigOptions.lua

Fixes #6628
Implements intuitive link. There's no good way to get the linked target's source rate currently so this pr implements a float type edit box so a user can enter the target's attack/cast rate.
The float box could filter the user input better but if i can get something working correctly i will make a second pr for that.

Implement Intuitive Link

---

src/Modules/CalcMirages.lua

Can't replicate but should fix #6722
Cached data access was not gated behind an if statement. While this should not cause issues due to the order of things being calculated it's likely causing the mentioned issue.
Additionally added a check for noCache to force cache rebuild when running fullDPS.

Fix potential cache access null deref and check noCache flag

---

src/Modules/CalcOffence.lua

With enough reduced duration in a build, PoB would display your duration as negative instead of 0

Fix negative duration values

---

src/Data/ModCache.lua
src/Modules/CalcOffence.lua
src/Modules/ModParser.lua

The Stats that are conditional against enemies do not contribute to other mods
Tested by using the mastery against Hailrake and using Precise Technique to see if the damage changed
Fixes #6710

Fix Accuracy rating against enemy mods affecting Accuracy Stat

---

src/Data/Skills/other.lua
src/Export/Skills/other.txt
src/Modules/CalcActiveSkill.lua

Fixes the guardian minions level not following the player level, 
Should probs make use of the value of "minion_actor_level_is_user_level_up_to_maximum" rather than hardcoding it to cap at 85

Fix guardian minion levels

---

src/Classes/ItemsTab.lua
src/Modules/CalcSetup.lua

Fixes #6877 #6846
Fixes Widowhail multiplying mods individually by merging mods from the equipped quiver first before adding them to the main mod list. Fixes odd interaction with weapon swaps, not sure what changed but my last implementation had issues. Fixes tooltip calcFunc call setting repItem to False at times causing odd behavior in CalcSetup.
- Test build from #6877
- Test build from #6846

Fix Widowhail multiplying mods individually, oddly interacting with weapon swaps.

---

src/Classes/PassiveSpec.lua

The following exception is thrown when calling `build.importTab:ImportPassiveTreeAndJewels(getPassiveSkillsJSON, charData)` in headless mode.
```
lua: Classes/PassiveSpec.lua:237: bad argument #1 to 'pairs' (table expected, got nil)
stack traceback:
[C]: in function 'pairs'
Classes/PassiveSpec.lua:237: in function 'ImportFromNodeList'
Classes/ImportTab.lua:627: in function 'ImportPassiveTreeAndJewels'
```

Resolves lua: Classes/PassiveSpec.lua:237: bad argument #1 to 'pairs' (table expected, got nil)

---

src/Modules/BuildList.lua

Fixes not being able to see all the filename.
As there is a maximum filename length, widen the filename list to match it.
- Create a build and save it. Keep typing characters until the input box no longer accepts characters.
- Select Save
- You should see the whole name in the list.
N/A
Note the build "**Lightning SRS Champion - expensive bits needed before switching to SRS - The STRONGEST SRS - NoMoreT**" in both screenshots:

Widen filename list

---

src/Data/ModCache.lua
src/Data/SkillStatMap.lua
src/Modules/ModParser.lua

The sacrifice anomalous quality isn't taken into account for cost calculation

Add support for Sacrifice anomalous quality mod

---

src/Modules/CalcDefence.lua

This fixes issues with over 100% reduced damage over time taken, 
Things which cause dots to heal like Tainted Pact and Gluttony of elements should not be implemented as `less taken` anyway and should apply after this step

Prevent negative damage taken over time

---

src/Modules/CalcOffence.lua
src/Modules/CalcPerform.lua

Fixes #6788
Due to affliction charge mods being added after ailment calcs, effect mods from affliction charges were not taken in account.
This pr moves affliction charge mods block into the `doActorMisc` func and moves the calls for player and minion actors above the ailment calcs. While to my current understanding this should not break anything it should be tested at least a bit more before merging.
- Test build from issue.

Fix order of calcs for afflication charges

---

src/Data/ModCache.lua
src/Modules/ModParser.lua

Title, 
In all cases where we have number as the first argument we use `num, _` rather than the other way around, so this fixes those for consistency, this is mainly done as the first argument is a number and the second is a string
This also updates the `NgamahuFlamesAdvance` sudo mod to correctly have access to duration and frequency, even though those are currently unused, just so that in future if this is updated it minimizes the chance for a mistake.

Update a few mods in mod parser to make them more consistent with others

---

src/Modules/CalcSetup.lua
src/Modules/CalcTriggers.lua

Fixes #6790
Support gems coming from ExtraSupport did not have the gemData property set causing a null deref.

Fix missing gemData on triggeredBy sources if coming from ExtraSupport mods

---

src/Modules/CalcTriggers.lua

Fixes #6778
Prevent hit chance from applying twice as it's already included in effective crit chance,

Hit chance applying twice to triggers relying on crits

---

src/Data/Skills/act_dex.lua
src/Export/Skills/act_dex.txt
src/Modules/ConfigOptions.lua

Shrapnel Ballista's projectiles can shotgun, this adds a config option for the amount of shotgunning, defaulting to 1 unless it uses a rain setup and then will default to the maximum
This also adds support for the split projectiles to shotgun apon return, but that requires #6738 and #6744. They are not required for the basic support only for splits and returning

Add support for Shrapnel Ballista's "projectiles can shotgun"

---

src/Export/Main.lua

This allows the exporter to attempt to render frames between the scripts being loaded
This could have been done with a coroutine, but that adds unnecessary complexity in my opinion
This adds around 40 milliseconds on average to export time, which is around 0.1% of the total export time (around 34300 milliseconds on average on my machine), but gives feedback on the export almost 10 seconds earlier (~25 seconds in)
The biggest culprits to the long export are the stat descriptions, which is exported and then processed a second time to be used, as we only export the English versions of stat descriptions, and we process them slightly differently
It takes around 10 seconds to export stat descriptions, and then another almost 14 seconds to obtain stat_descriptions.txt and …

Change Exporter runall to add to a list which is consumed per frame

---

src/Modules/Main.lua

`self.modes[self.mode].viewMode` could be nil, such as when in the build list, this adds a check that it exists to fix crash

Fix crash when opening help sections from build list

---

src/Data/Skills/act_int.lua
src/Export/Skills/act_int.txt

Phantasmal Flameblast grants base radius to the gem as its quality effect. It used the `active_skill_base_radius_+` stat to grant the extra base radius which was stat mapped to `skill("radiusExtra", nil)`.
This would be overwritten by the stat map on the gem that also used `radiusExtra` instead of summing the values together. Changed the statMap on the gem to use `mod("AreaOfEffect", "BASE")` instead so it sums correctly

Fix Phantasmal Flameblast AoE values

---

src/Data/ModCache.lua
src/Modules/CalcDefence.lua
src/Modules/CalcPerform.lua
src/Modules/CalcSections.lua
src/Modules/ModParser.lua

Only current method of having wither applied on you in PoB is the map mod, which this does work for
But even if its not applied to you it shows the calc value on the calcs tab

Implement wither effect on self

---

src/Modules/Calcs.lua

Fixes #6857
https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/63d4f212c99e9c0839022bb1b24fe294d9698c62/src/Modules/Calcs.lua#L172-L174
Does not take into account the case when the active skill comes from the secondary part of a gem like is the case for Flamewood causing the fullDPS count to be ignored.
- Tested build from issue

Fix fullDPS not working with two part skills

---

src/Modules/CalcSetup.lua

Fixes #6862
If a disabled group containing a triggered skill is forced active a crash can occur due to incorrect main socket group selection in CACHE mode. When a wrong socket group is considered main the player.mainSkill will not be in fullEnv.player.activeSkillList 
https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/63d4f212c99e9c0839022bb1b24fe294d9698c62/src/Modules/Calcs.lua#L406-L417
causing the assumption in the manaforged mana cost pre calculation to cause a nil de reference:
https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/63d4f212c99e9c0839022bb1b24fe294d9698c62/src/Modules/CalcTriggers.lua#L509-L512
- Run tests from https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/6574

Fix rare crash ccaused by forcing active an inactive group containing a trigger setup.

---

src/Modules/CalcBreakdown.lua
src/Modules/CalcOffence.lua
src/Modules/ConfigOptions.lua

This makes it so that the enemy resistance configuration options modify the maximum resistance higher than 75, due to all the of ways they can get max res now (eg altars, shrines, expedition, rare mods) with an additional config option to disable it
this way it only adds 1 instead of 4 config options
It also fixes the resist label almost always having `"average inverted "..resistForm` due to missing the nil check, and cleans up the enemy resistance function

Add support for enemy resistance config to increase max res

---

src/Classes/PartyTab.lua
src/Data/Minions.lua
src/Data/Skills/minion.lua
src/Data/Skills/other.lua
src/Export/Minions/Minions.txt
src/Export/Skills/minion.txt
src/Export/Skills/other.txt
src/Modules/CalcPerform.lua
src/Modules/ConfigOptions.lua

Fixes #6739 .
Adds support for minions to apply auras. This still has the issue that only 1 relic is active at a time

Improve support for minions applying auras

---

src/Classes/CheckBoxControl.lua
src/Classes/DropDownControl.lua
src/Classes/EditControl.lua
src/Classes/SkillListControl.lua
src/Classes/TradeQuery.lua

Cleaning up some chaotic code I encountered. No change in functionality.

Code cleanup

---

src/Modules/CalcSetup.lua

Fixes #6667
Due to the way trees interact with jewels ExtraJewelFuncs are added to modDB after jewels are processed. This pr fixes this by recursively calling initEnv again if ExtraJewelFunc were found. Depth is limited to 1.
- Verified the build in the linked issue works correctly.

Recursively process ExtraJewelFunc mods

---

src/Modules/CalcTriggers.lua

Fixes tests failing
Accidentally make combust look only in the same group for a trigger source at some point.

Fix combust looking for a source only in the same group.

---

src/Modules/CalcMirages.lua

If a mirage decides to use a forced active skill the calculations sometimes may not be correct due to incorrect calcs mode used.

Fix rare incorrect calculations bug when mirages use forced active skills

---

src/Modules/CalcPerform.lua

The block was moved in #6801 and this caused the code to not run in time
Fixes #6918

Fix Tailwind not applying

---

src/Data/Skills/act_dex.lua

Fixes #6926 
Update the current version of Splitting Steel Gem Quality to "40% Impale Effect"
Check impale DPS and Gem Description to match "40% Impale Effect".
https://pobb.in/qCJULE33wuEj

Update splitting steel quality impale effect

---

src/Modules/Build.lua

ab069e8f introduced support for enemies with Cannot be Suppressed, but inadvertently broke the displayed suppress chance in the build sidebar. Use EffectiveSpellSuppressionChance to fix that.
Fixes #6929.
Chance to Suppress Spell Damage is Lucky wasn't being properly reflected in the build sidebar.
- Looked at the Spell Suppression Chance stat in the build sidebar before and after allocating the mastery.
https://pobb.in/14WDSIR07DFM

Fix spell suppression chance not displaying Lucky

---

src/Modules/ModParser.lua

Fixes #6943
The description on the both ring Evasion/ES mastery mod was adjusted this patch. 
Wording went from "if both equipped rings have evasion modifier**s**" to "if both equipped rings have **an** explicit evasion modifier", so I just made the **an** and the trailing **s** optional.
- Checked both 3.22 and 3.23, both parsed correctly

Fix Evasion ES Mastery

---

src/Classes/ConfigTab.lua

Sometimes its hard to find config option on big builds or builds with a lot of config options
- Open a buid
- Try searching for something
- Only that thing should be visible
https://pobb.in/dOdIJeTDPAfB

Add support for search input to Configuration tab

---

src/Modules/BuildSiteTools.lua

Pastebin has none of the features sites like pobb.in and poe.ninja have. It does not support mobile viewing of builds and commonly has issues where it flags a build as spam and invalidates the link. The site is also banned in many countries
Importing Pastebin codes will still work though

Remove Pastebin as a build export option

---

src/Classes/ImportTab.lua
src/Classes/PassiveSpec.lua
src/Modules/Build.lua

Supports importing new ascendancy classes from a tree link and the import tab.  Also fixes some typos that snuck through.
Can't really test this yet until the league is live, but you can export a tree link and it'll import again just fine.

Add support for importing new ascendancies

---

src/Classes/ItemsTab.lua
src/Classes/TradeQuery.lua

Saw a couple comments about this over the past few days so I took a crack at it. This saves the search weights to the xml under the Items node with a new element called "TradeSearchWeights". The default Full DPS and Effective Hit Pool still load on new builds or builds without this element, but any build that adjusts these weights should have them loaded as set from then on.
Open to suggestions on elem wording and xml structure.

Save trade search weights to build xml

---

src/Classes/PassiveSpec.lua
src/Classes/PassiveTree.lua
src/Classes/PassiveTreeView.lua
src/Classes/TreeTab.lua
src/Modules/Build.lua

This just adds a warning for now, but might add the actual points used into the display

Count secondary ascendancy nodes used

---

src/Modules/CalcOffence.lua

…
Fixes #6962 .
Currently if ES/second already exists, then it will skip the calculation. This interferes with interaction between EB and Replica Covenant's mana cost as es cost mod. 
Added a condition to calculate the cost despite value already existing and summing together for the breakdown.
Tested with Replica Covenant and EB and ES costs are now accurately reflecting intended behaviour.
Compare to image from linked issue.

Fix: updated the conditions for calcuating costs/s to include mana cost as base es cost and eb interaction

---

src/Modules/Data.lua

Fixes #6769 and fixes #6796
Matching for life mods on other items now exclude `Enemy's life` and `Life From You`. This assumes that other mods like Sin Trek's `Enemies cannot leech life from you` are similarly tagless.
The only source I could find of `Cannot Leech` is from a legacy Infractem pre-2.6, but I've simply modified the specialTag for it to only match that complete line instead of any part of the line. This prevents `cannot leech mana` and Sin Trek's mod from disrupting Utula's.
This PR does not address the Searing Exarch's recoup implicit as seen in issue 6715. This behaviour seems inconsistent, since a life recoup mod on unique items certainly disables Utula. From this I'm guessing that eldritch implicits are excluded from Utula searching, but I don't have this confirmed.
- …

Add Sin Trek and Legacy of Fury to Utula exclude list

---

src/Classes/ConfigTab.lua

Current search and hide all configurations is always on top and overlaps inputs when scrollng

Fix scrolling on search and hide all configurations input

---

src/Classes/ImportTab.lua
src/Classes/PassiveSpec.lua

Fixes # .
Before, GGG didn't supply ascendancy IDs in their unofficial API.  Novynn was kind enough to supply these for us, so this PR switches to use them.
- Imported character to empty build
- Imported a different character over an existing build
- Imported a new character on an old build

Updated import code with extra data GGG kindly provided

---

spec/System/TestDefence_spec.lua
src/Modules/CalcDefence.lua

Fixes #6990.
Negative bypass was rounded up to 0, ignoring some instances of "not bypass"
- Allocating the es mastery and achieving 70% chaos bypass
```
eNrlHNly4zbyefQVKFVly1PxwUOXvXJSsiUfiQ9Fsj2ZvKRgEpKYAQkNCNqjpPLv2wBIiZJFmpSUfdhNqjwS0XejG90N2u0fv_kUvRAeeiw4rZqHRhWRwGGuF4xPq48PFwet6o8_VNp9LCb3o7PIo3Llh8qHtvqMKHkhFPCsKhKYj4l4SkjZvwOpKQ7EhLDgFv_B-CVzT6t3LCBV9IwD1xPJN4fiMLzDPjmtDh1AriIcOiRwzxfPY8AJ5tgRhN9Itp1IsFvmwqrgEaz62AuGzPlCxCVn0RSkqqIXj7xqmOvb_v3gISWSF6RFApU-tPsUzwgfCixQCD9Oqx2wDB6TLvbhJ1DDNAJSxmHdtFqWkfysHuVin0U8FBuSGE4JcedY5qGVBdjnpDcaEUd4L-Sce-J8ggMnxS8LryzsbUSFN6Ue4Smp6lkYV2-INzNhH5jAtNsfpmzUMOt2qxb_tPIRmXhfgU-emJxRsOgmbCTy9TjwBNkUu8-8kAXbqLiEm-mmiFII0kKwAxIS_oKFtyJXJm3mP3vBZga8xQE-Z2EBP0nIPuGQA0QphCFxGKSNsjxKYt54I1IcspQeMUJZaTbTozcsClea8GYCDSBDFoMcsogWhBSLRGVlQnXJtwJQ14EoROuFCXW …
```

Fix negative bypass being ignored

---

src/Classes/TreeTab.lua

There was no check to exclude Charm Sockets from the nodes in radius check
Fixes #6994

Fix Crash when opening Timeless Jewel search

---

src/Modules/ConfigOptions.lua

The description of the Manastorm config option slightly overruns the box.
Manastorm also only has one buff, so there is no ambiguity from this change.
Text edit
Above

Change Manastorm config option to not overrun options box

---

src/Data/Skills/act_int.lua
src/Data/Skills/other.lua
src/Export/Skills/act_int.txt
src/Export/Skills/other.txt

The max flat damage stat did not have the unscalable flag added to it
Had a look and applied it to some other skills that also used a similar limit variable although those would only scale with buff effect so was unlikely to become an issue
Fixes #7003

Fix Pyroclast Mine Aura Effect scaling Maximum Added Flat Damage

---

src/Data/SkillStatMap.lua

GGG changed the stat on all their gems from `number_of_additional_projectiles` to `base_number_of_projectiles`so it now included the 1 base projectile all the skills inherently have
Fixes #6997

Fix projectile count being 1 higher on all skills

---

src/Modules/CalcDefence.lua

The calculation for Escape Artist use the final doubled value after Maji has affected the armour
Fixes #7009

Fix ES from Tricksters Escape Artist when using Oath of the Maji

---

.github/workflows/spellcheck.yml

Move contributor's GitHub logins from `pob-dict.txt` to `contribs-dict.txt`.  This new file will (hopefully) be auto-generated in future.

move contribs to separate file

---

src/Data/Skills/act_int.lua
src/Export/Skills/act_int.txt

Implements Righteous Fire of Arcane Devotion. It's essentially just a copy of the main skill but with only one scaling stat instead of two. The spell damage DoT scaling is already handled by a global gem stat map.

Implement Righteous Fire of Arcane Devotion

---

src/Data/Skills/other.lua
src/Export/Skills/other.txt
src/Modules/CalcSetup.lua

Fixes #6966 
According to the [wiki](https://www.poewiki.net/wiki/Unseen_Strike) Unseen Strike will only use the main hand weapon and the supports socketed in that weapon regardless of which slot it's in.
The fixes causes a small visual inconsistency in the source of the custom group for the skill as it will show as socketed in "Weapon 1" regardless of the actual socketed slot. Fixing this would require relatively significant changes to the group slot logic.
- Tested build from issue
- Tested Hidden blade in both slots

Fix hidden blade not using main weapon and its supports

---

src/Modules/CalcOffence.lua

Fixes #7036
Rigwald's Curse damage conversion was looking specifically for ModFlag Claw.  However, claw damage mods such as "with claws" create a ModFlag of Claw, Hit with no KeywordFlag, whereas something like "Claw Attacks deal increased..." mods create a ModFlag of Claw and KeywordFlag of Hit. 
So this PR has the damage conversion check for ModFlag of Claw, Hit instead, which I assume is safe because the CritChance conversion below it does the same thing at line 595. Although I wonder if this should also add the Attack flag as well, like attack speed does? Unsure if it needs it.
<pre>https://pobb.in/lxBbDeFJcbsE</pre>

Fix Rigwald's Curse damage conversion with specific claw mods

---

src/Classes/PassiveSpec.lua

Fixes #6963
In the changes made to support secondary ascendancy classes, the code to reset the current ascendancy class when changing base class was changed to deallocate the old ascendancy instead of all ascendancies that isn't the new one. This didn't work because selectClass already changes the current class before calling selectAscendClass.
This change is pretty simple, it simply makes the reset a function that is called by both SelectClass and SelectAscendClass. This does mean we're running it unnecessarily in SelectAscendClass when called from SelectClass, but this way avoids breaking any of the other uses so I felt like this was a fair compromise.
- Swapped between various ascendancies. The bug doesn't seem to always appear, but swapping between ascendant and other classes always …

Reset ascendancy class before changing base class again

---

src/Data/Skills/minion.lua
src/Export/Skills/minion.txt
src/Modules/CalcOffence.lua

This is due to the minions use-speed of the skill not mattering for dps, and instead the amount of minions summoned per second
This means getting minion cast speed no longer incorrectly scales the explosion dps, and player cast speed does
Few minor things about this PR
1) do we want minion skill parts for single explosion (always hit time of 1, player cast speed doesnt matter) / summon continuously (current method)
this allows the user to toggle off the value of speed on the player
2) what is the best place to store `skillData.summonSpeed`, is it in skill data like I have put it? and where is the best place to set it in code, I did it after dps, but I could have done it directly after speed for instance

Make minion instability hitspeed based off the summon speed instead

---

src/Classes/SkillsTab.lua

This may break certain build save files, depending on if they were saved with a `skillId` or not (As far as I know they've all been saved with a `skillId` for a while).
This isn't intended to be a permanent solution, but is a solution to release the transfigured gems with and not be stuck supporting a save file format we may not be happy with.

Hacky save fix to not change save format and keep gemId making sense

---

src/Classes/SkillsTab.lua

Fixes the problem introduced by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/7043 where support gems can not be loaded.
However this is not a proper fix and merely a hack on the above mentioned hack for the [coerced gemIds in the new skill export](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/360883f8c41703b3895d6c10cb956f43176628ef/src/Export/Scripts/skills.lua#L629) that came in https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/6984

Fix loading saves with support gems

---

src/Data/ModCache.lua
src/Modules/CalcPerform.lua
src/Modules/ModParser.lua

Oath of the Maji only applies if you have no sockets and have the gear slot equipped.
Could add more items to the list if need for the future
Fixes #7051

Fix Oath of the Maji applying when gear slot is empty

---

src/Data/Skills/sup_dex.lua
src/Export/Skills/sup_dex.txt

I accidently removed it when updating all the base qualities on gems
Fix #7021

Fix Deadly Ailments less hit damage multiplier not working

---

src/Modules/CalcSetup.lua

The code was crashing as it was not making sure that the jewel socket was from the tree before trying to check if it was an expansion jewel socket.
Also moved the multiplier check first, as it is pointless to have the jewel and rarity check if The Adorned is not in the build in the first place

Fix Crash when using the Adorned and items with abyssal sockets

---

src/Data/Uniques/Special/Generated.lua
src/Modules/Data.lua

Shako currently triggers the life modifier check on Utula's. 
This is due to the variant lines with 'life' in it - fixed by adding `Variant: ` into the exclusion pattern.
- Compared Utula and Shako interaction before and after. 
- Also tested the different "socketed gems are supported by <gems with "life" in name>" and seems like there's no issue with the parsing there. 
- Test PoB: https://pobb.in/9vp9FRUvtc0o

fix: shako and megalomaniac displaying variants as explicit modifiers

---

src/Classes/SkillsTab.lua
src/Data/Gems.lua
src/Export/Scripts/skills.lua
src/Modules/Data.lua

Uses the Path of Exile `BaseItemType.Id` for the `gemId` save format attribute in the `<Gem>` element as it always has been. The `skillId` attribute is also kept and maps to the gem's variant primary `GrantedEffect.Id`. Adds a new attribute called `variantId` that maps to the variant of the gem (`GemVariants[n].Id`), eg. Arc, ArcAltX, or ArcAltY. This is to help identify which variant is used rather than relying on every gem variant having its own unique granted effect.
During loading if there is no (known) `gemId` or `variantId` it falls back to looking at `skillId` and eventually by name, as before.
For the a lot of gems `skillId` and `variantId` are the same but it is not true for every case, especially support gems.
Hopefully by relying on the game's identifiers rather than the …

New save format

---

src/Classes/TradeQueryRequests.lua
src/Classes/TreeTab.lua

Fixes #6906 
Adds a trade league dropdown to the timeless jewel search. Given the user does not interact with the dropdown, the current behavior is kept and we create the trade url without the league name which defaults to the current base league. The dropdown is setup to show this same league on load so as to avoid confusion. Once any value is selected, that league specifically is added to the url. 
The realm is hardcoded to PC, which is the same behavior we have today, but we need to supply a realm to get leagues. A lot of this code is similar to what's in TradeQuery.lua (~line 350) but I wasn't sure if there was a clean way to strip that out to reuse. I have it sorting to have Affliction be at index 1, and maybe we'd also like that for the Trade popup in the ItemsTab.
I also added …

Add support for selecting league for Timeless Jewel search

---

src/Data/SkillStatMap.lua

fixes #7076
SkillStatMap for More bleed damage was set as increased damage. 
Simple change from `INC` to `MORE`

Fix Lacerate of Haemorrhage "more damage with Bleeding" using increased

---

src/Classes/ImportTab.lua
src/Classes/Item.lua
src/Classes/ItemsTab.lua
src/Classes/SkillsTab.lua
src/Modules/Common.lua
src/Modules/Data.lua
src/Modules/ItemTools.lua

Chaos Golem of Malestorm was using a special character that can't be rendered.
- Load a file with malestorm old saved
- Paste a malestorm gem
- Add a maelstorm gem in skillTab.
- Import character

Fix tooltip for Summon Chaos Golem of the Maelstrom

---

src/Data/Uniques/helmet.lua

Fixes #7063 .
Devouring Diadem was not updated for 3.22 changes 
From patch notes:
`The Veiled modifier which grants increased Duration of Ailments you inflict while Focused modifier now has values of 36-40% (previously 81-90%). Crafted versions of this modifier have been adjusted accordingly.`

F Devouring Diadem using legacy Ailment duration mod

---

src/Modules/ConfigOptions.lua

Fixes #7066.
Add cooldown bypass option for flicker strike in config and set default to true.
Set default for consecrated path of endurance bypass cd to true. 
Tested build in linked issue

Fix Flicker Strike DPS being limited by cooldown

---

src/Classes/SkillsTab.lua
src/Modules/Data.lua

Fixes #7071 .
All vaal gems are defaulting to their last variant due to the way the variants are populated in `Data.lua`.
Updated the step to also set the variantId when generating the vaal variants.
Resaved and loaded the build in question to verify it's working.

Fix Vaal gems loading incorrect variant after reopening a build

---

src/Data/Skills/act_int.lua

Fixes #7068 .
Pyroclast mines had a SkillName condition that only applied the skill aura effect to pyroclast mines.
Removed the SkillName condition to allow it to affect other skills and minions.

Fix Pyroclast Mine aura not affecting the damage of other skills

---

src/Data/Skills/other.lua
src/Export/Skills/other.txt
src/Modules/CalcSetup.lua

Fixes #7083, #7070
Reverts forcing Unseen Strike to use main hand supports only added in #7038

Revert preffered slot for Unseen Strike / Fix skillData nil crash

---

src/Data/Uniques/amulet.lua

Fixes #7064 .
Replica Dragonfang's Flight was missing tags on the mod lines. Added so that the catalyst dropdown/slider will trigger.

Fix catalysts not working correctly on Replica Dragonfang's Flight

---

src/Modules/CalcSetup.lua

The check for if the jewel came from the tree was coupled to the check to see if it was an expansion jewel so it didn't stop the jewel applying to Abyssal sockets on gear
The only way I could see to get the jewel to apply to outer tree sockets was to make sure it didn't have a parent attribute in the expansionJewel attribute
Fixes #7079

Fix The Adorned not applying to jewels in outer tree sockets

---

src/Modules/Data.lua

Shako is currently disabling Utula's maximum life when it has a mod that has the word life in it including "Proliferation"
These mods only have the Gem tag. 
Hybrid mods from Shaper and Elder seem to have additional tags but these appear to be due to the other line that accompanies them.
E.g. Socketed Gems are Supported by Level X Minion Life (provides the gem tag)
Minions have X% increased maximum Life (hypothesis is that this provides the life and minion tag on the mod)
Proposed solution is to exclude all "socketed gems are supported by" mods from the Utula check.
It was also mentioned that hybrid mods are parsed as two separate lines anyway so the above minion life mod would still fail the Utula check. 
- Checked Hiltless to confirm that socketed gems supported by lifetap has no life …

Fix gem mods on Forbidden Shako not working correctly with Utula's Hunger

---

src/Data/Skills/act_dex.lua
src/Export/Skills/act_dex.txt

The gem did not have the area tag on it.
I added it and separated the skill parts so area modifiers would not apply to the hit portion
Fixes #7091

Fix Frost Blades of Katabasis DoT not being scaled by area damage

---

src/Data/Skills/act_dex.lua
src/Export/Skills/act_dex.txt
src/Modules/CalcOffence.lua

This overrides the attack speed value to only use the speed from the offhand
It does have the issue where changing the attack speed on the main hand weapon shows a DPS change in the tooltip but not when saved.
I'm not sure how to fix the tooltip

Fix Dual Strike of Ambidexterity not using offhand attack time

---

src/Modules/CalcSetup.lua
src/Modules/CalcTools.lua

Fixes #7069
`calcLib.gemIsType` looks for an exact name match to check if the mod can apply. This adds a parameter allowing to match gems that start with the name to match variants.

Allow selectively matching variants for GemProperty mods

---

src/Data/Skills/act_int.lua
src/Export/Skills/act_int.txt

The stats on the gem were also in the SkillStatMap so they were not being restricted to the skill parts they affect

Fix Bodyswap of Sacrifice explosion not scaling correctly

---

src/Modules/ModParser.lua

Body Armour condition was set incorrectly in the Mod Parser `UsingBodyArmour` -> `UsingBody Armour`.

Fix Oath of the Magi not working for Body Armour slot

---

src/Data/ModCache.lua
src/Data/Uniques/Special/New.lua
src/Modules/CalcSetup.lua
src/Modules/ModParser.lua

GGG made a change to allow the jewel to work in Cluster jewel sockets
Also changed the variable name to reflects that it is no longer restricted to regular tree sockets

Update The Adorned to work in Cluster Jewel sockets

---

src/Data/Skills/act_dex.lua
src/Export/Skills/act_dex.txt

Lancing steel less damage multiplier applies to both hit and ailment damage (for both regular and transfigured).
Also fixes Spraying tooltip as it was using wrong skill name as reference
See this for proof: https://www.reddit.com/r/PathOfExileBuilds/comments/18c3yc3/psa_pob_data_is_incorrect_lancing_steel_damage/
Pob:
https://pobb.in/mdmUQv-yXmrb

Fix Lancing Steel less damage multiplier only applying to Hits

---

src/Data/Skills/act_dex.lua
src/Data/Skills/act_int.lua
src/Data/Skills/act_str.lua
src/Export/Skills/act_dex.txt
src/Export/Skills/act_int.txt
src/Export/Skills/act_str.txt
src/Modules/CalcPerform.lua

I didn't realise that "Skill:..." used the internal skill name instead of the one we display to players
Fixes tooltips for:
* Eye of Winter of Finality
* Eye of Winter of Transience
* Infernal Blow of Immolation

Fix crash when checking the breakdown for Transfigured Eye of Winter and Infernal Blow

---

src/Modules/CalcActiveSkill.lua

Fixes #7160
The `copyActiveSkill` function only used by mirage calculations:
https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/9d56a02f42792fb7a069c27a4e190f230665a3d9/src/Modules/CalcActiveSkill.lua#L157-L170
calls `copyActiveSkill` :
https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/9d56a02f42792fb7a069c27a4e190f230665a3d9/src/Modules/CalcActiveSkill.lua#L82
which outside of the `copyActiveSkill` is only ever passed in sanitized activeEffect Tables:
https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/9d56a02f42792fb7a069c27a4e190f230665a3d9/src/Modules/CalcSetup.lua#L1401-L1425
https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/9d56a02f42792fb7a069c27a4e190f230665a3d9/src/Modules/CalcSetup.lua#L1499-L1507 …

Sanitize skills passed to createActiveSkill by copyActiveSkill

---

src/Data/ModCache.lua
src/Modules/ModParser.lua

Fixes #6973
Effect mods applied to culling strike mods.

Make culling strike mods unscalable

---

src/Modules/CalcSetup.lua

Fixes #7140
The ModList holding the to be filtered ExtraJewelFuncs did not have the actor set causing the ItemCondition set on the ExtraJewelMod coming to be evaluated to true as it had the neg tag.

Fix Ngamahu, Flame's Advance adding Strength to Unique jewels

---

src/Data/SkillStatMap.lua
src/Data/Skills/act_str.lua
src/Data/Skills/sup_str.lua
src/Export/Skills/act_str.txt
src/Export/Skills/sup_str.txt

Fixes #7136
https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/6976 mistakenly removed the mods as they were related to qualities. This pr also moves the mod to SkillStatMap.

Fix boneshatter missing self damage mod

---

src/Classes/ConfigTab.lua

Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/7129
Fixes a crash caused by comparing a number to nil. I'm not exactly sure why the code is written the way it is but when the `maxCol` variable is bigger than 1 and `col` defaults to 1 failing this:
https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/46c98d38129d1ecdc89e914d41a698bef22a6cd9/src/Classes/ConfigTab.lua#L726
check the first element of the colY table is never actually set. This pr defaults the first element to 0 following the logic in the loop:
https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/46c98d38129d1ecdc89e914d41a698bef22a6cd9/src/Classes/ConfigTab.lua#L731

Fix odd null compare caused by column alighnement on odd viewport sizes.

---

src/Data/Skills/act_int.lua
src/Export/Skills/act_int.txt

Fixes #7128 .
Vortex of Projection statMap was set to INC. Changed to MORE.
Also cleaned up the statMap for Vortex as it can no longer be cast on Frostbolt.
- Tested PoB from linked issue

Fix Vortex of Projection damage when cast on Frostbolt from increased to more

---

src/Modules/Build.lua
src/Modules/CalcTriggers.lua
src/Modules/ConfigOptions.lua

Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/6492#issuecomment-1727037313 implements https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/7143
At 100% reduced curse duration Doom Blast expiration mode should behave like curse replacement mode since the curse will instantly expire.
Doom blast modes expiration and replacement modes did not allow for curse overlaps. This pr changes the config logic to show the config option when applicable.
Doom Blast expiration and replacement modes used simulation based calculations instead of charge based ones causing unexpected tick rounding during simulation. This pr makes all skills that are the only skill in the current trigger group and ignore server tick rate to use charge based calcs to avoid tick rounding. …

Cap Doom Blast expiration mode and use charge based calcs for skills that ignore tick rate

---

spec/System/TestItemMods_spec.lua
src/Classes/Item.lua
src/Classes/ModStore.lua
src/Data/ModCache.lua
src/Modules/CalcSetup.lua
src/Modules/ModParser.lua

Fixes #7179, https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/7145. Contains https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/7152
Fixes issues with `ItemCondition` condition not working properly when no matching items were found.
Implements handling for explicit keyword in mods using `ItemCondition` .
Fixes Kalandra's Touch not adding to the `CorruptedItem` multiplier even if the other ring was corrupted.

ItemCondition fixes. Kalandra's Touch not adding to influenced items multiplier.

---

src/Modules/Data.lua

This sorts it (very loosly) into 4 categories
-- Everything not in a later category
-- Item mods & jewel data
-- Boss data, skills and minions
-- Remaining Item Data and uniques
and cleans up some of the data, like order of data.misc, and the loose functions/magic numbers of `data.monsterExperienceLevelMap`

Sort and cleanup data.lua to make it easier to manage

---

src/Data/Skills/act_int.lua
src/Export/Skills/act_int.txt
src/Modules/CalcOffence.lua

Fixes #6323
This seems to have been added in https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/1112 as a way of supporting Arcanist Brand with the old trigger calculations. It is no longer needed after the trigger rework has been merged and is causing the linked issue.
https://pobb.in/9-Ym5kqwpX15

Stop adding brand skill flags to skills triggered by arcanist brand

---

src/Modules/CalcTriggers.lua

Fixes https://www.reddit.com/r/pathofexile/comments/188r65t/why_does_pob_cut_my_trigger_rate_for_coc_when/ke93zcv/
It seems the interaction between dual wielding and triggers is incorrect in POB. Not really sure how to implement dual wielding interactions for triggers such as [The Poet's Pen](https://www.poewiki.net/wiki/The_Poet%27s_Pen) or [Cospri's Malice](https://www.poewiki.net/wiki/Cospri%27s_Malice) or if that interaction is even in scope of pob simulations so marking as draft for now.

Only apply dual wield penatly for on weapon triggers requiring attack sources

---

src/Modules/CalcDefence.lua

Fixes #7191 .
Current implementation in `CalcDefence.lua` only converts base fire resistance but based on screenshots from linked issue, increased modifiers also apply. Extrapolating this to apply to more multipliers as well. 
This PR applies increased and more modifiers to cold and lightning resistances using the conversion rate. 
What is the appropriate source for the converted increased and more modifiers? Should it still be the same as the original source or the same as the base conversion "Fire to X Resistance Conversion"? I've opted for the former due to potential confusion when there are multiple items. 
- Confirmed resistances match in game values from linked issue.
Refer linked issue

Fix interaction between Chieftain Tasalio node and increased/more fire resistance modifiers

---

src/Classes/ConfigTab.lua
src/Classes/ImportTab.lua
src/Modules/CalcSetup.lua
src/Modules/CalcTools.lua
src/Modules/Data.lua
src/Modules/ModParser.lua

Fixes #7215.
The check `calcLib.getGameIdFromGemName(skill, true) == calcLib.getGameIdFromGemName(ifOption, true)` causes a match when both function calls return nil. This often happens when using gemName from a parsed mod as those are lowercase while the keys in `data.gemForBaseName` have uppercase letters which is an issue in and of itself causing some trans gems to not be affected while they should be.
- Test Arc and its variants
https://pobb.in/xpExdA_AV6rg

Fix GemProperty mods applying to incorrect gems.

---

src/Modules/CalcPerform.lua

Fixes #7218
`activeSkill.skillData.repeatFrequency` is nil when Penanace brand is disabled by [Gruthkul's Pelt](https://www.poewiki.net/wiki/Gruthkul%27s_Pelt). When doing a second pass on the buffs granted by Penance brand that value is used to calculate max stages causing a crash.

Fix crash when skills granting buffs that rely on buffs are disabled.

---

src/Classes/ImportTab.lua
src/Classes/PassiveSpec.lua

Fixes #6718
On character import, when Delete Jewels is true, we are keeping the state of cluster jewels in a subgraph. This functionality is used elsewhere in the case where you remove a cluster from the tree and then add it back in. We keep the allocated nodes so that it automatically loads back in when the cluster is returned. The problem is when importing, we're keeping the state of the nodes, including any additionally allocated ones, "in case the cluster comes back" and of course it does because it's part of the import data. So we see the cluster again and allocate all the nodes that were there at time of Import, including ones the Import possibly does not have.
So this PR adds a flag that is set true during Import Delete Jewel true that will ignore saving the state of the cluster …

Fix allocated nodes on Cluster Jewels when importing character

---

src/Modules/CalcDefence.lua

Stun and Block duration are meant to round up to the nearest server tick.
People only generally care about the exact value if they are using an Immutable Force where the roll can determine a 1 tick vs 2 tick stun

Round Stun and Block Duration to server ticks

---

src/Classes/TradeQueryGenerator.lua

Fixes #6538
Allow filtering trade queries on number of sockets and/or links. This sets both min and max so it's an exact number match. I added some checks to not show the controls for Flasks or Jewelry when applicable. There is the possibility to search for something with more links than sockets, which would return no results of course but I feel that's on the user not to break. Maybe some check could be added but I wasn't sure if it was worth it. 
Pretty sure we could fairly easily update this to let users set min and max instead of hardcoding both if that's something we wanna do.
I also did some refactoring on how we are updating anchors and popup height.
- Validate trade query filters generated matches the set socket and/or link number.
- Validate socket only filtering and link only …

Add support for filtering on number of sockets and links in Item Trader

---

src/Modules/ModParser.lua

Fixes #7231.
Unnatural Instinct copied all the mods from the node modlist which also included the `Condition:ConnectedTo` mods which are used to determine whether a given tree is connected to a given starting point. Used in Pure Talent.
- Test build provided from issue
- Try allocating the starting point manually

Filter mods applied by Unnatural Instinct.

---

src/Modules/CalcMirages.lua
src/Modules/CalcOffence.lua

Fixes issue mentioned on discord.
Ruthless support applied to skills used by mirages even though the mirage doesn't not use the skill enough times to cause a ruthless hit.
- Test Tawhoa's chosen using consecrated path with ruthless support
https://pobb.in/sZj-egRxyllU

Fix ruthless support applying to mirages that only use the skill once.

---

src/Modules/CalcOffence.lua

Fixes #7241 .
Rage Cost for Vaal Attack Skills displays as 0 with Hateforge equipped. Cause is due to the the finalBaseCost of Souls resource not being shifted to Rage.
- Tested a few Vaal Attack Skills to confirm Rage Cost now displaying correctly.

Fix Rage Cost of Vaal Skills not displaying correctly for Hateforge 

---

src/Modules/CalcPerform.lua

Fixes #7235 .
Currently PoB has a condition that only applies inspiration charges if the main skill is not a minion skill.
I believe this is to stop inspiration charges from affecting minions however this also removes the buff from the player portion of minion skills. 
This PR changes the condition to only apply when the actor is the player.
- Tested with a few minion skills to confirm inspiration charges doesn't affect minion portion but affects the player portion. 
Refer linked issue

Fix Inspiration Charges not applying to Minion Skills

---

src/Classes/CalcBreakdownControl.lua

There is already a sort by type, but this is not used for a lot of breakdowns. Applying a sort by value should make it easier to read the breakdown without disrupting the sort by type.
Fixes #4433 #7228
The calculations breakdown popups are unsorted, making it harder to compare between builds.
- Verified the mods are sorted in various controls

Sort the Calculations Tab breakdown lists by value

---

.github/ISSUE_TEMPLATE/accuracy_bug_report.yaml
.github/ISSUE_TEMPLATE/application_bug_report.yaml
.github/ISSUE_TEMPLATE/behaviour_bug_report.yaml
.github/ISSUE_TEMPLATE/calculation_bug_report.yaml
.github/ISSUE_TEMPLATE/crash_report.yaml
.github/ISSUE_TEMPLATE/feature_request.yaml

Issues are often closed through gh magic words when linked PRs are merged into dev but not yet released. The current issue tracker link in the templates uses gh defaults which only displays open issues.
This PR modifies the issue tracker url params to display both open and closed issues.

Change issue tracker link in Github issues templates to include closed issues

---

src/Export/Scripts/legionPassives.lua

Fixes #7193 .
Small internal error in `AlternativePassiveSkills.dat` which has the row Id swapped around for the Powerful Faith and Frenzied Faith. Created a [bug report](https://www.pathofexile.com/forum/view-thread/3480943) for it.
This PR adds handling to correct errors based on a manual list. 
Note: actual exported file not committed in this PR. 
- Confirmed fix via export and checking the find timeless jewel function
- Check linked issue

Fix Templar notables Powerful/Frenzied Faith displaying incorrect Id

---

src/Modules/CalcPerform.lua

- Splitting doActorMisc into doActorMisc and doActorCharges to enhance logic flow and increase performance. The separation allows for more granular execution, avoiding the need to run the entire functionality of the original doActorMisc function in all cases.
- Calculate charges earlier to enable stats that depend on charge count.
Fixes #7172 
The mod "You can apply an additional Curse while at maximum Power Charges" did not function. The problem is that the charge related calculations got executed after the curse related calculations. Therefore charges were never set when curse related modifiers where calculated.
- Compared multiple builds that use the bugged mod in question
- Verified the impact on dps and if the additional curse is listed at the Calcs page 
- Compared all kinds of …

Fix: Precursor's Emblems curse mod does not work

---

src/Modules/CalcPerform.lua

Fixes #7158 .
Current calculation of Earthquake of Amplification Aftershock occurs before buffs are taken into account. This PR moves the calculation into the second pass after buffs are computed.
- Tested build in linked issue to confirm Malevolence now applies to aftershock damage

Fix skill effect duration from buffs not applying to Earthquake of Amplification Aftershock

---

src/Data/ModCache.lua
src/Modules/ModParser.lua

Fixes #7157  .
The mod parser was applying a limit for each mod occurrence. This PR changes the mod to a global limit. 
- Tested linked build in the issue

Fix poison duration from charms stacking with Noxious Strike

---

src/Data/Minions.lua
src/Data/SkillStatMap.lua
src/Export/Minions/Minions.txt

Fixes #6967
Law of the Wilds was using the wrong base minion for its stats so the damage was very far off.
It was also using the wrong actor level for the minion and I believe it always grabs the level from the `levelRequirement` stat and the `base_display_minion_actor_level` is only used for the tooltip in game but not the actual minion itself.
The only other minion with differing `base_display_minion_actor_level ` vs `levelrequirement` is Vaal Summon Skeletons. I'll will check this assumption with GGG
- Test build to make sure the minion stats changed and it uses the new actor level
https://pobb.in/6GoR-wJPrqTJ

Fix Law of the Wilds using the wrong minion stats

---

.github/ISSUE_TEMPLATE/accuracy_bug_report.yaml
.github/ISSUE_TEMPLATE/application_bug_report.yaml
.github/ISSUE_TEMPLATE/behaviour_bug_report.yaml
.github/ISSUE_TEMPLATE/calculation_bug_report.yaml
.github/ISSUE_TEMPLATE/crash_report.yaml
.github/ISSUE_TEMPLATE/feature_request.yaml

Per Nightblade's suggestion, adding extra text to the github issues templates to emphasise that users should check for both open and closed issues.

Add extra wording to clarify 'Check for duplicate' step in Github templates

---

src/Modules/CalcOffence.lua

Fixes #7263  .
CalcOffence was not processing base fire damage and base cold damage on shield attacks.
- Tested build from linked issue

Fix base damage from transfigured shield skills not being applied

---

src/Data/Minions.lua
src/Data/Skills/act_dex.lua
src/Data/Skills/minion.lua
src/Export/Minions/Minions.txt
src/Export/Skills/act_dex.txt
src/Export/Skills/minion.txt

The "of Bombarding Clones" and "of Prismatic Clones" variants of the skills are meant to use different minions that use different skills

Fix alt Blink/Mirror Arrow using wrong minion

---

src/Modules/CalcMirages.lua
src/Modules/CalcOffence.lua
src/Modules/CalcPerform.lua

Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/6737.
Cleans up handling of mirage skills. Applies various minor fixes.
Supersedes: #6753 Includes: #7238
- Test mirage skills handled in CalcMirage.lua

Mirage cleanup

---

src/Classes/TradeQuery.lua

Since we've introduced saving search weights to the build, I thought it would be a good idea to have a way to reset them without needing to jump into the xml, especially if you have a ton of weights set up.
- Resetting should default to FullDPS and TotalEHP stat weighting
- Resetting should work on init popup load and after any updates are made
- Resetting and then Canceling should revert back to previous weights
- Save and Cancel functionality should be unaffected, outside of the reverting mentioned
~PS: I'm aware if you hit Reset twice you lose the previous weights, but I have not figured out a clean solution yet because you kinda have to hardcode compare to the default list's stats and weightMultis.~
Pushed an update for this, still hardcoding a little gross but I moved the boolean …

Add support for resetting Search Weights in Item Trader

---

src/Classes/ImportTab.lua
src/Modules/Data.lua

#7189 introduced a crash for Vaal Gems that have differences in gemId outside of just having an extra "Vaal" term e.g. VaalDomination vs DominatingBlow.
This PR fixes the issue by creating a lookup table `gemGrantedEffectIdForVaalGemId` as part of the gem data initialisation which as the name suggests maps the `grantedEffectId` from a skill gem to it's corresponding Vaal `gemId`. This does away from the previously used `gsub` and should be more robust. 
- Tested imports of Vaal Reap, Vaal Domination and Vaal Caustic Arrow on builds from poe.ninja

Fix Vaal Gem import to use new lookup table

---

src/Modules/CalcPerform.lua

This needs testing to see if the other minion debuffs still work fine, 
And the pride aura needs its modCond to be satisfied, 
And the aura should not affect the player if it doesnt ingame (eg for watchers eye)

Add support for minion aura debuffs

---

src/Classes/TreeTab.lua

Fixes #1392
Add ability to update every tree that is not latest all at once instead of needing to manually convert each one. All trees that are converted are replaced. As this action cannot be undone, there is a confirmation pop-up.
- Validate all trees are updated to latest version and load successfully
- Validate any tree that is already latest version is unchanged
- Validate window sizing to avoid cropping the "Convert all" button
<pre>https://pobb.in/CyjKf3xPDZbT</pre>

Add support for converting all trees to latest version

---

src/Classes/PopupDialog.lua
src/Classes/TradeQuery.lua
src/Export/Main.lua
src/Modules/Main.lua

Fixes #7229
Add a scrollBar to the Trader popup when the number of sockets reach a certain point. This allows the popup to show on even the smallest window PoB can be resized to. The rows are dynamically shown given they are within the scrollBar height, and in order to do this I had to change the anchoring from the row above it to a static sectionAnchor for all of them. That anchor is what is moved when the scrollBar offsets.
There are still some arbitrary numbers I used to fine-tune the UI so it would hide/show cleaner. The numbers in the hideShowFunc were trial and error, again whatever looked best personally.
I also fixed another odd bug I found where if you deallocate a socket after opening the Trader, and then opened it again, the previous socket controls still existed in the popup. …

Fix display in Item Trader when large number of sockets are allocated

---

src/Classes/TreeTab.lua

Single convert or mass convert would take 3.22 R and convert to 3.23, this PR will fix it and maintain the version, even with mix and matched trees in the specList. 
So 3.22 R should convert to 3.23 R and 3.22 (or anything other than 3.23) should convert to 3.23.
Also had to account for versionSelect for things like 3.23 R to 3.23, which shouldn't really happen but people be peoplin.
Empty trees with 3.22 and 3.23, both versions
<pre>eNrlW1tz4rgSfp79FS7eJwQIJJkiu0VCblXJhAOZmd2nKWEL0EaWKFkmYX_9aUk2OAxyJOw6dap2HjKAur--SN3qbkP_j7eYBissEsLZRaN1dNwIMAt5RNj8ovHt-ebzWeOP33_rj5BcPM0uU0LVyu-_ferr1wHFK0yBrxFIJOZYfs-ROj8BaYmYXGDOHtHfXNzy6KLxlTPcCKaIRUTm70KKkuQrivFFYxICcyNASYhZdLX9PCNcIIFCicWDkjpIJX_kEaxKkcJqjAib8PAFy1vB06VWakXwq6G5fxw9jZ8LKhFWVAks-tQfUbTGYiKRDBL4c9EYgGPQHA9RDH8BDdEUoNpHJ6fdRrOU5TIVif …

Fix converting Ruthless trees

---

src/Classes/CalcBreakdownControl.lua

Fixes #7301 
Supercedes #7297 
This is the quick fix for that crash.  There are more issues with the sorting that should probably be solved, though.

Fix crash when hovering attribute requirements

---

src/Classes/CalcBreakdownControl.lua

This fixes sorting of buffs with completely unrelated stats, as well as keeping elemental resistances grouped as they were before.  Ordering switches depending on which resist you look at, is the only oddity

Fix sorting for unrelated stats

---

src/Modules/ModParser.lua

Mousing over the breakdown causes a crash when using the Flame's advance ascendancy notable due to the mod not parsing the added strength value into a number.

Fix crash when mousing over strength breakdown when using Flame's Advance

---

src/Classes/SkillListControl.lua
src/Modules/ItemTools.lua

Fixes #7307 
Granted skills do not have gemData which we use to load the wiki, this PR uses the grantedEffect.name if the gemData does not exist in the case for granted skills like Arakaali's Fang and Guardian's Summon Sentinels of Radiance etc.
Hit F1 on lots of things
- Warden's Barkskin
- Guardian's RF boi
- Arakaali's Spider boi
One issue that would be a little gross to fix is Necromancer's Bone Armour because it shares the name of the body armour base and for the wiki it wants "Bone Armour (skill)" and it's probably the only special one. For now it loads the body armour but the link to the skill is on the wiki at the top.
edit: here's a working hardcode for Necro in ItemTools
<pre>eNrtHGtz47bx8_lXcDTTTtI5S3yIerh2OrJlnzW17xzJvms_ZWASkhCDhEKC9imd_vcuAFKiHqBIi-mnXGZyErHvXSx2F9Sd_-N7QI1XH …

Fix crash when using opening wiki for skills granted by items

---

src/Modules/CalcSetup.lua
src/Modules/CalcTriggers.lua

Fixes #7316
Pre calculation of current main skill used incorrect env mode causing the wrong skill group to be selected inside of initEnv. This caused the main skill to be missing from player.activeSkillList causing the pre calculation to fail. This in turn caused a nil deref as this line: 
https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/37b004035af610f1f95f06dd9119ca484a3dc941/src/Modules/CalcTriggers.lua#L532-L535
assume that the calculation succeeded.
- Test build from mentioned issue
- Test build from #6862

Fix crash caused by incorrect calc mode used for manaforged source calc

---

src/Classes/CalcBreakdownControl.lua

Fixes #7314 .
Writing this logic, I figured I wouldn't need the explicit check here because you wouldn't be able to have the same stat as a boolean, but I was swiftly proven wrong by transfigured gems

Fix bug comparing non-number types in the Calcs tab

---

src/Modules/Data.lua

Fixes #7310
Fixes #6715
Legacy of Fury's "Enemy's Life" was matching Utula's Hunger's life mod condition. This PR adds a specialExclusion for boots of "Enemy's Life" during item mod's substring matching.
<pre>https://pobb.in/r1Dd4gwvVjgw</pre>

Fix various item mod interactions with Utula's Hunger

---

CHANGELOG.md
changelog.txt

Fix: typo "Soultether" in changelogs

---

src/Modules/Build.lua

Currently the `Save` method of the Build class is saving the Value of the Stat but #6034 introduced child stats into the stat section which means the XML should save the Value of the relevant child stat if it exists.
This PR updates the logic so the XML isn't saving memory address of the StatVal and instead saves the correct value. 
- Tested with a few builds manually
- Ran the PR through the new test tooling that Paliak has been working on. Log 
[dockerlog.txt](https://github.com/PathOfBuildingCommunity/PathOfBuilding/files/14119558/dockerlog.txt)
There are 7 luajit errors in the log which existed prior to making these changes in this PR. Need to be investigated separately

Fix Build Save method to handle child stats correctly

---

src/Modules/Data.lua

Fixes #7329
Add Elevore's "Recover life when you suppress" mod to the specialExclusion list.
- Verify life not affected by Elevore with Utula's Hunger equipped
<pre>https://pobb.in/vfca02PkQB4o</pre>

Fix Utula's Hunger interaction with Elevore

---

src/Modules/CalcPerform.lua

Fixes #7326 .
Currently there is no mod in the modDB to display for overridden maximum charges from Badge of the Brotherhood and the Masterful Form Slayer Ascendancy. 
This PR implements a step in `doActorCharges` to add an `OVERRIDE` mod to the modDB which gets picked up in the tooltip. 
I'm not sure this is the best way of doing things as adding to the modDB during the calcs seems like bad practice. Happy to discuss and implement changes as suggested by others.
Also given how many times doActorCharges is called, this implementation uses a `modDB:HasMod()` call to check if the mod already exists. It seems like `modDB:HasModInternal` has a very unique implementation of source matching:
```lua
(not source or mod.source:match("[^:]+") == source)
```
As such, I've ensured that the sources in …

Fix tooltip for maximum charges granted from overriding sources

---

.github/workflows/spellcheck.yml

In response to workflow warning:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, streetsidesoftware/cspell-action@v2.4.0. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

Chore: spellcheck action: bump versions 

---

src/Data/Uniques/mace.lua

Fixes an error I found.
Remove a space in a variant tag for one Item

Small data error in Replica Bitterdream

---

src/Data/Uniques/claw.lua

Fixes #7374
As long as wiki is correct, current version of [Essentia Sanguis](https://www.poewiki.net/wiki/Essentia_Sanguis) should have block chance and life leech implicit.

Fix life leech and block missing from current version of Essentia Sanguis

---

src/Data/Uniques/bow.lua

Fixes #7373
As long as wiki is correct, [Lioneye's Glare](https://www.poewiki.net/wiki/Lioneye's_Glare) should have Far Shot.

Fix current variant of Lioneye's Glare missing Far Shot

---

src/Modules/CalcDefence.lua
src/Modules/CalcPerform.lua

Fixes #6149
Increased life modifier per over-cap fire res from [The Formless Inferno](https://www.poewiki.net/wiki/The_Formless_Inferno) did not apply as minion life was calculated before resistances. This pr moves the calculation of minion life into `calcs.defence` right under the resistance calculations. The values calculated by `doActorLifeMana` `doActorLifeManaReservation` are not used by code above where the calls were moved so this should not affect any other interactions. I understand this is not great code quality wise but i can't think of any other way of fixing this without moving either the functions calls (this pr) or resistance calculations (https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/6663) and out of the two i think this is a better solution.
My tests …

Fix formless inferno not increasing minion life

---

src/Data/Skills/act_str.lua

Fixes #7367
Mirages created by General's cry would attack with both weapons when the player is dual wielding. According to the issue this is incorrect. This pr uses logic from https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/7038 to force use of main hand.

Force main hand for skills used by General's cry mirages

---

src/Modules/CalcDefence.lua

Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/7357
The usage of slotcfg seems to have been carried forward initially being added in https://github.com/PathOfBuildingCommunity/PathOfBuilding/commit/ae21519533337a168116ec43fe8a080535e6de2b. For player calculations slotcfg will always be:
```
{
slotName = "Weapon 2"
}
```
Due to it only ever being set int the loop above https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/103646b6713ea1a2943a38df459873fa29509991/src/Modules/CalcDefence.lua#L573
This seems incorrect for a global effect and causes the shield only effects to apply causing the mentioned issue.

Remove unnecessary usage of slotcfg for energy shield and ward calculations

---

src/Data/ModCache.lua
src/Modules/ConfigOptions.lua
src/Modules/ModParser.lua

Fixes #7339
~~This pr makes the intimidate effect from the champion ascendancy node only apply when the condition "Enemy is on full life" is set.~~ This pr adds a config option for disabling the effects of Champion's Intimidate. The setting defaults to on so as not to get in the way. Previously the intimidate effect always applied.
```
https://pobb.in/hMz7aKLA9ELG
```

Add a config option for disabling Champion Intimidate effect.

---

src/Modules/CalcTriggers.lua

Fixes #7354
Disables skill rotation simulation for Cast when stunned as according to the issue it can cast multiple skills simultaneously. Related https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/6615
```
https://pobb.in/37-nlZpE8pzO
```

Disable skill rotation for Cast when Stunned

---

src/Data/Minions.lua
src/Data/Skills/other.lua
src/Export/Minions/Minions.txt
src/Export/Skills/other.txt

We previously were using the wrong minion level for Dancing Dervish as the skill itself had a level requirement of 1 so we assumed it would use the level requirement of the weapon but this was incorrect
Since the minion is Unique it is meant to have the Unique monster mods applied to it
The damage taken stat comes from the UniqueAnimatedWeapon.ot file which we previously had never used
Fixes #7294

Fix Dancing Dervish stats (Life, Damage and Damage reduction)

---

src/Classes/TradeQuery.lua

Scrolling with scroll wheel on ItemTrader that does not have a scrollBar still manipulates the screen when there are 2 or more additional slots. So between 2 and 6 sockets for example is an issue.
Gifs will explain. Either no one has found this yet or they don't care.
6 socket aka last without scrollbar, can add one more to see scrollbar and validate scrolling
<pre>eNqtW2t32jgT_tz9FT58JsF37D1k95BALm3S8ELStO-XHmEL8EZYrC0nob9-R5YNDkWOjenpacGaZ26SRjNj0fv7bUmUFxzFAQ3PWtqp2lJw6FE_COdnrceHyxOn9fdff_RGiC3uZ-dJQPjIX3986qWfFYJfMDlrGXpLYSiaY_YtZ2X8BFYrFLIFpuEd-odGV9Q_a32lIW4pUxT6Acu_eQTF8Ve0xGetiQfgloJiD4f-xfZ5RrhAEfIYjm652H7C6B31YZRFCYwuURBOqPeM2VVEkxVY01JeAvwqaG7uRvfjh4JKQVhUCUz61BsRtMbRhCGmxPDPWasPnkFzPEBL-Be4IZIAK_3UNcyuo9uqY7tWt9UpBZ8nUcwO4zBZYexvQNqpaeky0lGEh7MZ9ljwgi-igF0sUOhtBaoyXF3au4SwYEUC …

Fix scrolling on ItemTrader

---

src/Classes/TradeQuery.lua

Fixing the bug I introduced; when we close item trader, I was wiping all controls to fix an edge case with sockets, but this added a bug related to some of the other non-item controls. This PR changes to only clear the item slot controls.
- Open Trader, change league, close Trader, open Trader -> success
- Validate old case, open Trader, see all 21 sockets, close Trader, deallocated one socket, open Trader, verify 20 sockets
<pre>eNqtHNt22jjwufsVHJ5N8P2yJ9k9JECSNhcKpEn2pUcYAW6FTWw5hHz9jiQDjosdG-gDAXnu0sxoRnJP_32bk9orDiMv8M_qyolcr2HfDcaePz2rPwy7Dbv-7z9_nfYQnd1PzmOPsCf__PXllH-vEfyKyVndMeo1isIppj_WpLSfQGqBfDrDgX-LfgXhZTA-q98FPq7XRsgfe3T9yyUoiu7QHJ_VBy4g12socrE_vtiOJ4AzFCKX4vCGsW3FNLgNxvB0gkgEj-fI8weB-xvTyzCIF6BOvfbq4aUAur7t3feHKZk8Py0T6PTltEfQCocDimgtgo-zegtMg6a4jebwCdQQiYGUfKLrqlFvFuKcx2FEKy …

Fix crash when opening Item Trader after selecting a different league

---

src/Classes/CalcBreakdownControl.lua

Adds conditional to breakdown sorting to only apply to sections that have a source so we avoid overwriting the sort of ailments done in CalcOffense.
- Check ailment threshold breakdown for shock, chill, sap, brittle; verify sorted correctly
- Verify effective dps mod for poison and ignite are unaffected
- Roughly check other breakdowns with Base or Source columns to verify unchanged from live
<pre>eNrVHF2T2jjyOfkVLqruLQFs87k1s1sMzGSmaibhhklyey9bwhagjZBYW2bC_vpTS7YxDDI29j5cHhJj9be6W62WnKvffq6ptcVBSDi7btjNdsPCzOM-YcvrxteXu4-Dxm-_vr-aIrH6sriJCIWRX9-_u1LPFsVbTCVewxIoWGLxLaHk_iEpbRATK8zZE_qTB5-4f934zBluWHPEfCKSXx5FYfgZrfF14zsR3qphodDDzB_v399SvMZMIEpCIRFWKECewMEjcB9Fgj9xX0KJIJLk1oiwGfd-YPEp4NHmuuE0rC3Brxrm4Wn65fklIxphWdGkZu-uphTtcDATSFih_Ou6MZIGQkt8TyTzLaKRpGN3-k7TbQ8HdqOVi3QTBaGYoLV8LIE822Ds7-G …

Fix sorting of ailment breakdown sections

---

src/Data/ModCache.lua
src/Modules/CalcActiveSkill.lua
src/Modules/ModParser.lua

Rename the skill name of mod tags in `ModParser.lua` to match the name specified in autogenerated files.
This enables `calcLib.getGameIdFromGemName` to return it's intended value when called on line 681 of `ModStore.lua`.
Fixes #7337 
Reduced skeleton duration modifier doesn't apply.
- Create build with Summon Skeletons
- Socket To Dust
- Calc tab shows reduced duration
```
eNrlHGtv4zju8_RXGAEO2AWmedh5tUh3kSZ9HdqZbNLO7NyXhWIribaynbXldrKL-e9HSXbiPOTIteduDzdAp45FUiRFUiSltPfzV5caLzgIie9dVBrVesXAnu07xJtfVJ4er0-7lZ9_OumNEFt8nF1GhPKRn07e9cSzQfELpheVVsVgKJhj9imhZP0GlJbIYwvsew_odz-48Z2LygffwxVjijyHsOSTTVEYfkAuvqhMbECuGCi0secMNu9jwAUKkM1wcM9n7UfMf_AdGGVBBKMuIt7Et58xuwn8aAnCVIwXgl8lzN3D6OP4McUS8dIsgUTveiOKVjiYMMSMEP67qPRtRl4wgAJX98QlDCgiGgG5TqWmQAFdojm-TcHWj8BeRkHIhsiFx-M4kyXGzhrMVIGNAnw1m2HB_yAgbLB …
```

Fix summon skeletons duration

---

src/Data/ModCache.lua
src/Modules/ConfigOptions.lua
src/Modules/ModParser.lua

Fixes #6785 .
Add support for Everlasting Sacrifice that's granted by Mahuxotl's Machination

Add support for Everlasting Sacrifice

---

src/Modules/CalcTriggers.lua

Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/7388
Precalcualtion of snipe skill used "CACHE" mode causing similar issue to https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/7317 . 
```
https://pobb.in/IzUcwIOEbC1d
```

Fix snipe precalculation using wrong calc mode

---

src/Modules/CalcDefence.lua

Fixes #7386
Update breakdowns to show the 100% increased Armour and Energy Shield on Body Armour from the Armour and Energy Shield Mastery.
- Validate breakdown of armour equals total armour
- Validate breakdown of energy shield equals total energy shield
<pre>https://pobb.in/ROa3CR-0WuiJ</pre>

Fix Armour and ES breakdowns for "100% increased..." Armour and ES Mastery

---

src/Modules/CalcTriggers.lua

Snipe should deal no damage it self when it is a trigger for another skill. Currently Snipe has the base multiplier set to 0 when in trigger mode but that allows for added damage to skill count towards dps.

Fix Snipe doing damage when in trigger mode

---

src/Data/Skills/act_dex.lua
src/Export/Skills/act_dex.txt
src/Modules/CalcOffence.lua

Fixes #6909 and #7260 .
Supersedes  #7321 .
Explosive Trap of Shrapnel was using wrong variables for it's overlap calculations and producing incorrect values.
The +- 30% base radius on both explosive traps was not yet implemented leading to overestimating the damage output.
- The "Average explosions hitting" setting produces a bit lower overlap chance for normal version and not 100% for trans version
https://pobb.in/HFrrt77bxIjn

Implement explosive trap +-30% base tertiary radius, fix overlap chance for transfigured version

---

src/Data/Uniques/gloves.lua

Fixes #7379 
Nightgrip was missing the "taken" keyword and this led to an incorrect calculation of Effective Hit Pool
Imported the build below and compared the equipped Nightgrip with the one selected from the uniques tab, now the Effective Hit Pool is not messed up
https://pobb.in/gVGiXS9lqxya

FIX: Nightgrip missing "taken" keyword in description

---

src/Classes/ImportTab.lua

Fixes # .
When i select `Affliction` no need to display `in Affliction`, reserve that to only if select `All`

Reduce clutter in Import character selection list

---

src/Classes/ItemListControl.lua

Before, when you'd drag an item from the unique list to "All items", it would trigger a rebuild and thus a re-sort of the unique items.  If this sort takes a long time but you're adding several items at once it can get quite frustrating.  The rebuild isn't actually necessary so I removed it.
- Drag item to both items lists, no re-sort happens
- Drag item to item slot, re-sort happens
- Double click item and add to build that way, re-sort happens

Stop sorting unique item list when added item isn't equipped

---

src/Data/Uniques/body.lua

The unique was left out when we were implementing all the new uniques and moving last leagues ones to their respective files

Fix Replica Replica Hyrri's Ire not appearing in unique list

---

src/Data/Uniques/helmet.lua

Devouring Diadem was missing the mod on the last variant which was the default one to display in the unique list

Fix Devouring Diadem missing Mana Reservation mod

---

src/Classes/GemSelectControl.lua

Fixes # .
Sometimes you know ahead of time what you want, either active or support gem
These overlay buttons makes it easy to quickly access either one or the other gem list
[filter3.webm](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/44361234/27f28a60-ebd5-4489-8a86-bae32301bfa5)

Add buttons to filter Active and Support gems in Skills tab

---

src/Classes/GemSelectControl.lua

Update active and support overlays to cull respective gems from GemList in SkillsTab
<pre>eNrtPWlzo0iWn0e_gnDE7Jdy2XlCUls1G77taV8t2XV9cSSQWFQhcAHy0RPz3_dlgiSQQYft3tjZne4OtwTvvcx898tLH__rcRRb9yrLozT5tIG30IalEj8NouT208b11eF7sfFff-t9vJTF8CLcHUexfvO33l8-ms9WIbNbVXye4NMbwPdkEkTFp43zNFEb1p1MiqFKk7MoSbOjNJg894cyk36hslN1r-KdcZGepYH6tBHKOIfX95F6KB-cnF1e9K8AIZZ5fi5H8GgwlEH6sGHJ3FdJsDd7cZVF_s8ciG5YIxklg9T_qYqjLB3ffdpgG1asm_q04dq1bskf9W7ByP7y8TKWTyobFLKwcvjzaWMHGCRv1b4cwV_om4zH0JjNBUVbRLhcbGwvRNwdZ3mxPvbgTqlgiuBsMZtB1zuALzN1EIbKL6J7tZdFxd5QJv6sOUy2XN6F2w4vCFqIcTaOi-gujjS3J1hd8MfPGnDdLtirtJDx_uVgCspczAjaYo7giGKyGC8tpnioC_JLVAx3Y2DuC1rRuCe3SVSoFyBfplGeJnVEYnPM-RbjS1CayoMRRwjzLS4W9vN5c4JwTG28xTmj2BXLWFlHdRzuugw8hMMFtp1OzRjHMbiIOmanHPoqV9m9LKJmJzvh99KRFyVNsa04op1MyYuwtJC-DKJxfqaKTOUzQWx1Ku-ZTORems8UC7uLQC …

Update Active and Support Gem Filtering

---

src/Modules/ConfigOptions.lua

Added checkbox to bypass cooldown of Vigilant Strike as requested in #7434 .
- created empty build and added Vigilant Strike
- checked and unchecked checkbox in Configuration tab
- damage and hit rate properly adjusts
https://pobb.in/7OAriln3G54p

Add config option to bypass Vigilant Strike cooldown

---

LICENSE.md

SimpleGraphic 2.0 draws in many new dependencies. Most of them require us to reproduce the licence text in any and all distributions of the compiled artefacts to be legally able to distribute and use them. See https://github.com/PathOfBuildingCommunity/PathOfBuilding-SimpleGraphic/pull/52

Include licences of new third-party dependencies

---

src/Classes/GemSelectControl.lua

Sorry for breaking dev
This fixes the nil sortCache error when scrolling the gems in SkillsTab. It also refactors the Active/Support overlay code to be ideally more efficient and less code, and I removed the bypass code so we can add in a real fix to sortGemsByDPS and use that instead of adding another overlay that would do the same thing.
- Scrolling gem list should not throw an error
- Any combination of clicking on the GemSelectControl should result in the correct list returning and the cache used appropriately, i.e. click Full will load the first time but never again if constantly clicked, then click Active/Support, validate a faster load and cache again maintained if the same overlay is clicked
<pre>https://pobb.in/K8TJiRBXcSBG</pre>

Fix nil sortCache error in SkillsTab in dev

---

src/Modules/Main.lua

Fixes #7431  .
This requires https://github.com/PathOfBuildingCommunity/PathOfBuilding-SimpleGraphic/pull/46 to function, and adds a workaround for users who have unicode characters in their default user path.
- Popup cannot be closed without specifying a new path
- Popup opens on startup every time until fixing their Documents path to not contain unicode
- Sanitizes input, only allowing Save to be clicked once it contains no ? characters (PoB's unicode representation)
- Save button will load settings.xml and everything else from that path
- Question mark button leads to https://github.com/PathOfBuildingCommunity/PathOfBuilding/wiki/Why-do-I-have-to-change-my-Settings-path%3F
Do the opposite of the workaround in this comment and set your Documents path to something with Cyrillic …

Adding popup to specify new user path if default one fails

---

src/Classes/GemSelectControl.lua
src/Data/Global.lua
src/Data/Skills/sup_str.lua
src/Modules/Build.lua
src/Modules/CalcMirages.lua
src/Modules/CalcPerform.lua
src/Modules/CalcTriggers.lua
src/Modules/Calcs.lua
src/Modules/Common.lua

Fixes issue mentioned on discord. Related https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/7390 https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/7317 https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/6898
Calc modes were a mess with a bunch of vestigial code. This caused many calc issues and potential slow downs as well as odd cache re-use issues.
- Run https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/7162
The mana cost warning diffs in the following output are an example of cache re-use causing incorrect readings. The different in Relfection from The Saviour is caused by a different structure of modDBs and how modDB structures affect rounding of more modifiers.
```diff
--- /dev/fd/64
+++ /dev/fd/65
@@ -690,11 +690,9 @@
<PlayerStat …
```

Fix calc mode issues for triggers and mirages

---

src/Data/Uniques/body.lua

Fixes Replica Hyrri's Ire stats
Replica Hyrri's Ire gives Intelligence, not Dexterity. https://www.poewiki.net/wiki/Replica_Hyrri%27s_Ire

Fix Replica Hyrri's Ire granting Dex instead of Int

---

src/Modules/Main.lua

For some reason we were loading ``Settings.xml`` and then immediately overwriting all of the values loaded with defaults. This fixes that by.. setting the defaults first, then loading.

Fix settings not saving for certain users

---

src/Data/Skills/act_int.lua
src/Export/Skills/act_int.txt
src/Modules/ConfigOptions.lua

Manabond's damage calculation always treated your missing Unreserved Mana as 100% of your Unservered Mana which is not a realistic scenario and gives an inflated DPS value for the skill. A more common scenario is to spend 65% of maximum mana via Arcane Cloak then either regen or mana pot back to 100% in time for the next Arcane Cloak spend, giving a value of around 65%-82% depending on regen vs pot.
1. Loaded a manastacker character and placed a Manabond gem into the active weapon.
2. Added  control over a new SkillData member of Manabond called ManabondMissingUnreservedManaPercentage to ConfigOptions.lua, this value is limited to storing a 0-100 range subset of the user provided value. This range is detailed in the tooltip.
3. Moved Manadbond's LightningMin/Max calculations into a …

Added config variable to control the missing Unreserved Mana% used in Manabond's added base Lightning damage calculation.

---

src/Data/Skills/act_int.lua
src/Export/Skills/act_int.txt
src/Modules/ConfigOptions.lua

Draft PR, I need to validate that the export file change and that all tests pass. I'm looking for some initial feedback on the change for now.
When comparing iitems/skills/passives as a character that uses Arcane Cloak as the primary mana spender to drive Indigon's damage and cost ramp it required constantly re-calculating the "mana spent Recently" value based on current unreserved mana and the Arcane Cloak spend %. 
1. Loaded my 3.23 league character which had the correct items to reproduce this problem.
3. Added a new condition mod "Condition:ArcaneCloakUsedRecently" to ConfigOptions.lua to allow for opt-in on this feature.
4. Added a new baseMod to the Arcane Cloak skill which adds the mana spent to the already existing Multiplier:ManaSpentRecently mod as an additional base amount, I …

Added config toggle to add Arcane Cloak's mana spend to the value provided in the manaSpentRecently modifier.

---

.github/workflows/test.yml

pin cluacov to 0.1.2-1, new version came out 5d ago that does not work with our current setup
tests before the change: https://github.com/PathOfBuildingCommunity/PathOfBuilding/actions/runs/9015748876/job/24776422704
failing tests on 2024-05-19: https://github.com/PathOfBuildingCommunity/PathOfBuilding/actions/runs/9149221543/job/25152630073?pr=7623
working after pinning the version: https://github.com/FWidm/PathOfBuilding/actions/runs/9149394891/job/25152964011?pr=1

fix(ci): pin cluacov version

---

src/Modules/CalcSetup.lua

Fixes #7644
When using `weaponSet` 2 some items with `slotName`s containing swap would get clobbered depending on order in `build.itemsTab.orderedSlots`.
https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/ad60a7a1a3d50ea88c0ba20394a0c618a3fc58af/src/Modules/CalcSetup.lua#L670-L675
If the correct item was added it had the swap stripped. When the non swap counterpart is iterated over item is set to nil which is later assigned to the map with effectively the same key as the existing element removing it from the table.
Additionally this pr uses goto to skip iterations where item is explicitly set to nil. I can't think of any other cases where this change could affect things other than the issue being solved.
```
https://pobb.in/QH3ki1iuOi4L
```

Fix Abyss jewels not working in weapon swap

---

src/Data/SkillStatMap.lua
src/Data/Skills/sup_str.lua
src/Export/Skills/sup_str.txt
src/Modules/CalcTriggers.lua

Implements the Call to Arms gem based on logic for Automation.
```
eNq1W1tz4rgSfp79FS7eJ8QQmMkU2S0CuVWFCQcyM-c8bQlbgHZkiZXlJOyv35ZkG8MgR8Y-PCTG6v76InWr1TaDP94i6r1gERPOrlr-2XnLwyzgIWGrq9a359uPn1t__P7bYIrk-ml5nRCqRn7_7cNAX3sUv2AKfC1PIrHC8nuG1P0TkDaIyTXmbIL-4uKOh1etr5zhlrdALCQy-xZQFMdfUYSvWvMAmFseigPMwtHufkq4RgIFEotHJXWYSD7hIYxKkcBohAib8-AnlneCJxut1AvBr4bmYTJ9mj0XVCKsqBJY9GEwpWiLxVwi6cXw56o1BMegFb4nEqAQTQDnvNUupb1ORCzHKILL93nmG4zDHdmZ7_udno34BxKB2I5QLJ9JVAA_6326_OSf-xcXl51PvQsb-1Tgm-USB5K84JEgcrRGLHDQsSrtJKGSbCjBIqf3z6xG3f8C7p9b4Z-5RHQ8nb-viKHkDtP2g8j1NYVpcMJV1A8rRiR2Jp9yEnNWSWsn4lFCKYSiE-0Mx1i8IEkcFRnxaEGYo09GnNOQv7Kc8vLs_PzSGiYCo6elWYkzFJIknmApcJxz922cE8TQiMe7Oe18LiOdYgFJRO5xnL_DMMcBh7xTZOlCUPYc5Bzntgp8JEvsTlnJlpShqjan2XEzd6WrDHyaQjNIvG6Uc55QR0q5y2WdkiD7u0jo96zLZozfHPAemHSgGuMXLvWm6ZRdbu6nO …
```

Implement Call to Arms gem

---

src/Modules/CalcTriggers.lua

Currently skills triggered by spellslinger only considered the cooldown imposed on them by spell slinger in addition to their own but not the cooldown of the main skill gem. This works fine as as long as the cooldown of the main effect is equal to the cooldown of the support effect as they both will go off at the same time. Problem is there currently exist conditional cooldown recovery mods which could affect only one of the cooldowns making this assumption no longer hold. This pr basically extends the logic from https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/7558 to solve the issue effectively taking a max of the cooldown of the main gem and the effective cooldown of the triggered skill while taking the correct cooldown recovery mods into consideration.
- Tested a few …

Fix spellsinger triggered skill trigger rate not being capped by spellslinger cooldown

---

src/Data/Uniques/Special/Generated.lua

Fixes #7614 .
Forbidden Flesh&Flame doesn't update required class when selecting Duelist Impact.
- Select any not Duelist node on Forbidden Flesh/Flame
- Select Duelist Impact node.
- Check the required class.
- No response

Fix Forbidden Flesh&Flame (Duellist) Impact doesn't update required class.

---

help.txt
src/Classes/TreeTab.lua

Fixes #7406.
Pressing Up or Down arrow keys on my keyboard moves through the Tree Management.

Fix Tree Management Keyboard Shortcut #7406

---

src/Modules/ModParser.lua

… Jewels
Fixes #7610.
Fixes #7604.
- Rebuild the mod cache
- Strength from Ngamahu in Timeless Jewel Radius is not applied. Import PoB from #7604 (https://pobb.in/WMBnC0phfGBr), Strength is 1820, same as in-game.
- Ngamahu does not transform damage type from Timeless Jewel. Import PoB from below (https://pobb.in/1TKnO-VH2o8g), node "Revitalising Frost" should not affect flame dash damage
https://pobb.in/1TKnO-VH2o8g

Fix Ngamahu, Flame's Advance working correctly with Timeless jewels

---

src/Modules/Build.lua

Fixes ![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/4302241/b6cdd96c-a68e-46ad-9c5e-d6c034fe6e63).
In some cases the info line is too long and it can't be read.
- Import build into PoB and see that the line is split into two.
https://pobb.in/dGqxkOSjJK18  -Minion
https://pobb.in/-viTq9zN-nWg  -Player

Split Player and Minion Info lines if they are too long

---

src/Modules/ModParser.lua

Fixes #7585.
- Attack mastery "Stance Skills have +6 seconds to Cooldown" applied to all skills
- Rebuild mod cache
- Hold `alt` to check internal modifiers for the mastery
- Select any skill with no cooldown and there should be no cooldown
- Select any lv1 stance skill and the skill cooldown should be base + 6 seconds
https://pobb.in/JjJvNcZ7BdpJ

Fix Stance Cooldown mastery affecting attack speed

---

src/Modules/CalcOffence.lua

Fixes #7594 
- When a projectile spell with no cooldown is supported by trap support in Black Zenith, the trap cooldown is not being counted and shown.
- Load sample PoB
- All trap skills socketed in Black Zenith should display trap cooldown
- Trap with built-in cooldown should functions the same
https://pobb.in/0Mgib7TyTvw0

Show Trap Cooldown for Trap Supported Spell in Black Zenith

---

src/Modules/CalcTriggers.lua

Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/7590
Because shattershard does not have any cooldown trigger calculation were returning inf rate which was causing issues with leech calculations. This pr applies a trigger cap override to shatter shard using the duration as pseudo cooldown.

Use duration as pseudo cooldown for shattershard

---

src/Classes/TradeQuery.lua

- **Fix error when toggling 'Include Enchants' in trader**
Fixes #6216
Lua Error when toggling 'Include Enchants' in trader
- Open trader, 'Trade for these items'
- Activate Session Mode
- Use trader to 'Find best' on weapon
- Check 'Include Enchants' checkbox -> ERROR 
Any build will do
See linked issue #6216
No error

Fix error when toggling 'Include Enchants' checkbox in trader

---

src/Data/SkillStatMap.lua
src/Modules/CalcOffence.lua
src/Modules/CalcPerform.lua

Fixes Cold Snap quality "% more effect of chill" not being parsed. Furthermore, fixes "more" modifiers on chill effect not being applied to enemy chill effect/bonechill. The latter also fixes #6777 and #5037.
https://pobb.in/u/Arcinde/hhdZhirZpJ8H
Cold Snap mod not being parsed: 
Even after parsing Cold Snap mod, it is not calculated in effect of chill, despite the "chill effect mod" line below showing the correct value
Not calculated in bonechill damage increase
Cold Snap mod is parsed:
Effect of chill correctly incorporates "more":
This value is taken up correctly for the bonechill damage increase of the main skill:

Support Cold Snap more chill effect quality

---

src/Classes/TreeTab.lua

Fixes #7564 .
The "Find Timeless Jewel" function does not properly update the selected league for creation of the trade search url.
Details can be found in the bugreport referenced.
Additionally, the window does not restore the last used league when closing and reopening the window.
- Manually performed tests 
- Manually "broke" the HTTP request for fetching the active leagues in order to test fallback scenarios

Fix timeless jewel trade league url

---

src/Classes/TreeTab.lua

Fixes #7560 .
The "Manage trees" item in the tree compare dropdown doesn't do anything. It should work the same as it does in the tree list dropdown.
Tried locally

Fix manage trees in tree compare dropdown

---

src/Modules/Data.lua

Fixes #7529
Excludes lines starting with "Allocates" from `FindModifierSubstring` used in ItemCondition type mods.

Fix exclude anoint mod lines for item cond match

---

src/Modules/CalcMirages.lua
src/Modules/CalcTriggers.lua
src/Modules/Calcs.lua

There was a bunch of redundant calls to `cacheSkillUUID`. While the function is not super expensive this could maybe slightly speed up trigger related calculations.

Fix remove redundant cacheSkillUUID calls

---

src/Classes/PassiveSpec.lua

Call to Arms tattoo has been converted to Warlord's Call. This caused a dismissable crash on importing a build that had one slotted. Finding which tattoo converts to which is quite hard without adding historical tattoo data or some kind of conversion table.
This pr adds logic that attempts to find the new name by comparing available stats. Failing that it removes the tattoo to prevent crash. Added logging in both cases.
- Try importing the following builds:
```
https://pobb.in/F7sdQa4QPD2_
```
```
https://pobb.in/m8iRz-fn3uuF
```
```
https://pobb.in/9ACP67JVEGy0
```

Fix crash caused by Call to Arms conversion

---

src/Classes/DropDownControl.lua
src/Classes/ImportTab.lua

Fixes # .
Before it was annoying to look at it, and hard to find the right character
Now with proper layout and colors, it's much easier

Redesigned the Import Chararacter menu to improve readability

---

src/Modules/CalcTriggers.lua

7551 changed the order of arguments of `calcs.buildActiveSkill` which 7637 did not take into consideration.

Fix crash caused by 7551 missing from 7637

---

src/Modules/ModParser.lua

Fixes #7582.
Only hits and ailments can check conditions on the enemy. Non-ailment DoT can't benefit from a stat that needs to check the enemy for ES. But the mastery applies to all chaos damage, even non-ailment chaos DoT that doesn't calculate base damage against a specific enemy, like CA's Caustic Ground.
- Import build 
- Confirm that checking `Does the enemy have energy shield` affects poison DPS, but doesn't affect Decay DPS.
```
eNq1W1uT2rgSfk5-hYuq88aA78AW7BbDXE_NbYdJsvuUErYAJbLF2jIz5NT570cXGwyDPDb2ycMErO5P3a3uVqtlhn-8BVhbwyhGJBy1jI7e0mDoER-Fi1Hry8vVWb_1x--fh0-ALh_n5wnCfOT3z5-G4rOG4RpixjdoaRREC0i_ZlDWdwa1AiFdQhLegx8kuib-qPVAQtjSZiD0Ec2-eRjE8QMI4Kg19RhzSwOxB0N_snueEi5BBDwKozs-7Tih5J74bJRGCRsNAAqnxPsJ6XVEkhWTqqWtEXyVNLf3T4_PLzmRUJgXian0afiEwQZGUwqoFrM_o9aYWQYs4A2iDArghOEY1sDqOINWt5Dj …
```

Fix "Deal 10% more Chaos Damage to enemies which have Energy Shield" chaos mastery should be limited to hits and ailments #7582

---

src/Data/Uniques/helmet.lua

Fixes #7658.
Curtain Call PoB description does not match with in-game.
- Check the item desctiption

Fix Curtain Call PoB description does not match with in-game.

---

.github/ISSUE_TEMPLATE/accuracy_bug_report.yaml
.github/ISSUE_TEMPLATE/application_bug_report.yaml
.github/ISSUE_TEMPLATE/behaviour_bug_report.yaml
.github/ISSUE_TEMPLATE/calculation_bug_report.yaml
.github/ISSUE_TEMPLATE/crash_report.yaml
.github/ISSUE_TEMPLATE/feature_request.yaml

Per discussion on discord about reported issues without platform/package disclaimer, adding a dropdown option in the issues templates so users can select the platform that they're using. Defaults to windows as that appears to be the majority of the user base.

Add platform dropdown option to issue templates

---

src/Export/statdesc.lua

Eliminates the need for manually fixing the `Chain Hook` endgame enhancement that GGG has as `{0:+}` whereas we assumed there would always be a second digit post the `:`.
Export Before:
`"Chain Hook has {0:+} metres to radius per 12 Rage",`
Export After:
`"Chain Hook has +0.1 metres to radius per 12 Rage",`

Fixes the GGPK export of ChainHook Enchantment description

---

src/Classes/CalcSectionControl.lua

Empty subsections were not offsetting Y correctly, resulting in incorrectly placed components. 
- Opened the calcs tab and verified that all tables are formatted correctly
An empty build will reproduce the issue

Correct subsection layouting for calcs tab

---

src/Classes/PopupDialog.lua

Fixes #7635
Input events are handled by `PopupDialog` before being passed to its child controls, allowing an input to be handled twice. Now allows child controls to handle/consume events first. 
 
- Using a build with at least 7 sockets, open the item trader dialog and scroll while hovering a dropdown. The dropdown should scroll without the item slot view scrolling. 
https://pobb.in/ZCKPLQT3VO6d

Allow children of PopupDialogs to process input events first

---

src/Modules/Build.lua

Fixes enemy level not updating when player level updates automatically.
https://github.com/user-attachments/assets/064e25c0-a83b-4345-ab5c-05ad35f58f4a
https://github.com/user-attachments/assets/9f34a0bb-fb54-471b-b643-65abb6b86e4f

Fix enemy level not updating in sync with player level when in auto mode

---

src/Modules/CalcPerform.lua
src/Modules/ModParser.lua

Adds support for `Elusive is removed from you at 20% effect` in the AVG calculation value of elusive effect.
TEST POB: `https://pobb.in/EkJN0AL9Z_Fr`

New Notable Support - Incorporeal

---

src/Classes/PassiveTree.lua
src/Modules/Main.lua

Downloading directly was broken recently with enforcement of user agent policies
This was never used anyway as we download the tree files directly from GGG (or their github) and perform preprocessing on them
This will cause issues if it tries to open a tree file and both the lua and the data.json are missing, however the download currently fails anyway so there should be no change

Disable Tree download if file is missing

---

src/Classes/PassiveTree.lua

This is just a temp fix until they add another source of secondary ascendencies or remove the current ones from tree data
note this just removes them from tree data, their selection is still possible, but is being removed in #7672 so didnt want to make merge conflicts

hide alternate_ascendancies as they are unobtainable but still in tree data

---

src/Modules/CalcDefence.lua
src/Modules/CalcSections.lua
src/Modules/ModParser.lua

Adds support for Impale Avoidance in the calcs tab under "Other Avoidance".
- Spec either the evasion mastery with 30% Impale avoidance or add a cluster with the "readiness" node.
- Check the calcs tab under "Other Avoidance" for the correct value.
https://pobb.in/qGxdsl_rJBG4

Add support for Impale avoidance in calcs tab

---

src/Modules/ModParser.lua

Adds support for the "Gain unholy might on block for 3 seconds" staff mastery.
1. Spec the mastery
2. Equip a skill that does physical damage
3. In the config enable "Have you blocked recently?"
4. DPS should increase and the wither config line should appear.
https://pobb.in/O0-W82zpKG5V

Add support for unholy might on block staff mastery

---

src/Modules/ConfigOptions.lua
src/Modules/ModParser.lua

Adds support for the "Hits that stun enemies have culling strike" mace mastery.
1. Spec the mace mastery
2. Enable the config "Do your hits always stun?"
3. Culling DPS should appear in the calcs.
https://pobb.in/ZqK4uobsMgnW

Add support for stun cull mace mastery

---

src/Data/Uniques/mace.lua

Current implementation of The Dark Seer does not have a slider for +1-2 maximum life per level for the current variants. I assume this is because it was incorrectly not mentioned on the patch notes by GGG but can be verified on the wiki and ingame.
https://www.poewiki.net/wiki/The_Dark_Seer
- Add "The Dark Seer" unique sceptre.
- Select variant 9/10 (Life/ES or Life/mana)
- Slider for 1-2 Life should appear in the drop down.
https://pobb.in/ZeywqjufeIon (kinda useless)

Fix the stats of "The Dark Seer" unique sceptre

---

RELEASE.md
fix_ascendancy_positions.py
src/Classes/PassiveTree.lua
src/TreeData/3_19/Assets.lua

Built ontop of #7675 (merge that first)
This PR is a subset of work done last year but those changes were too broad and so I am committing just a subset that are useful now and can easily be built upon (eg preventing needing to load sprites/assets on headless)
This splits future tree sprites data from tree.lua and removes unused zoom information during preprocessing
Doing this on the 3.24 tree reduces the size of the file from 4.91MB down to 3.03MB a 38.3% reduction
The changes to the 3.24 tree were not committed to avoid people who already have it needing to download it again
This also adds a copy of the 3.18 tree assets data into the 3.19 folder, and loads only that if its missing, this removes the need to load the whole 3.18 tree.lua every time

Split Tree sprites data from tree.lua

---

src/Data/SkillStatMap.lua
src/Modules/CalcOffence.lua
src/Modules/CalcSections.lua
src/Modules/ModParser.lua

Adds support for the "non-vaal strike skills target 1/2 additional nearby enem[yi]e?s?" mod.
Adds support for Ancestral Call additional strike targets.
- Select any non-vaal strike skill (e.g. flicker strike)
- Equip a suitable weapon
- You should already see the Strike Targets: 1 in the calcs tab under Skill type-specific Stats.
- Spec the attack mastery for +1 additional nearby enemy strike
- Strike Targets should now be 2.
- Add ancestral call
- Strike Targets should now be 4 (5 if awakened).
https://pobb.in/x3kzZbZIk5J1

Add support for additional strike targets mod & Ancestral Call Support

---

src/Modules/CalcDefence.lua
src/Modules/ModParser.lua

Adds support for flat dmg reduction to projectile attacks.
- Equip any unique / item with the effect (e.g. Lioneye's remorse)
- switch enemy dmg type to projectile or average
- check flat dmg reduction in calcs tab / max hit values.
- (easiest to test by setting 100% less armour in custom config for consistency)
https://pobb.in/5X8h4_yfbG6s

Add support for flat dmg reduction to Projectile Attacks

---

src/Classes/GemSelectControl.lua

Fixes # .
They now properly fit and look better integrated

Cleaner overlay buttons

---

src/Modules/ModParser.lua

support cannibalistic rite attack skills cost life instead of % of mana cost

cannibalistic rite Life Cost

---

src/Data/Uniques/amulet.lua
src/Data/Uniques/axe.lua
src/Data/Uniques/belt.lua
src/Data/Uniques/body.lua
src/Data/Uniques/boots.lua
src/Data/Uniques/bow.lua
src/Data/Uniques/flask.lua
src/Data/Uniques/gloves.lua
src/Data/Uniques/jewel.lua
src/Data/Uniques/ring.lua
src/Data/Uniques/shield.lua
src/Data/Uniques/staff.lua
src/Data/Uniques/sword.lua
src/Modules/ModParser.lua

Contains most of the unique changes listed in the 3.25 patch notes, 
Only ones missing (at the moment) are `The Perfidy` and `The Ravenous Passion` which will be handled by other PRs
`Forbidden Shako` which is auto generated, `Replica Dragonfang's Flight` which should be auto generated
`Hand of the Fervent` and `Lycosidae` are not fully handled, those will be handled in other PRs without needing to directly address them
`The Dancing Dervish` changes are not handled at all

3 25 unique changes

---

src/Modules/CalcOffence.lua
src/Modules/ConfigOptions.lua
src/Modules/ModParser.lua

adds Chance To Ignore Enemy Physical Damage Reduction and all 4 types of sources for it
added config for min/average/max effect
works on minions but uses the player config, so might need to have it showup with minion mod not just player?

Chance To Ignore Enemy Physical Damage Reduction

---

src/Modules/ModParser.lua

Adds parsing for new wording on Deadeye's far shot notable. Uses existing distance numbers taken from another mod with similar wording:
`"projectiles gain damage as they travel farther, dealing up to (%d+)%% increased damage with hits to targets`
Marking as draft as i'm not 100% sure the distance data is accurate.

Add parsing for new dead eye far shot notable

---

src/Modules/Data.lua

Fixes #7621
The mod was not added in the special exclude list

Fix The Apostate not working with Life Mastery

---

src/Data/Uniques/jewel.lua

Seething Fury incorrectly has a Medium Radius Modifier set
Fixes #7711  .
Seething Fury incorrectly has a Medium Radius Modifier set
- Create a new build
- Add the Seething Fury jewel to any jewel slot
- Verify that the Jewel doesn't have a radius
Not possible since the fixed item needs to be added via the item tab

Seething Fury incorrectly has a Medium Radius Modifier set

---

src/Classes/PassiveTreeView.lua

hi, this is my first contribution to pob.
I was inspired by [PoEPlanner](poeplanner.com) and how passive skills that you search for are highlighted along the border of the viewable area. This is great for folks with smaller screens so they dont have to zoom out a ton (and lose all visibility) or pan around frantically looking for the passive they searched for.
anyways, here's what I cooked up:
(the red circle shrinks in size and snaps to the edge of the viewport)

enhance passive tree search with sticky edges

---

src/Modules/CalcSetup.lua
src/Modules/CalcTools.lua
src/Modules/CalcTriggers.lua

Fixes #7471 .
When having a support gem with a pseudo active component (for example Prismatic Burst Support or Flamewood Support) and a compatible support gem both granted by an item with the "Socketed Gems are Supported by" Syntax, the support gem could affect the pseudo active part of the other support gem. This doesn't match the behaviour ingame, since the supports each only affect gems explicitly socketed in the item, not each other.
Items that create this issue are for example Forbidden Shako or Hungry Loop.
Additionally i adjusted the "No ... Triggering Skill Found" Message to more accurately represent the correct skill that is being triggered. Before it would prefer the name of the item, now it prefers the name of the skill.
- Created a Forbidden Shako with a problematic gem setup …

Fix support gems supporting pseudo active parts from gems granted by the same item

---

src/Modules/CalcSections.lua

Fixes #7592.
POB adds a lines that display the "Max Ignite Stacks" in the Ignite Widget when the number of max stacks is above 2 and it removes the informational line when the number of stacks max is 1.
- Equip "Emberwake, Ruby ring"
- Check the Ignite Widget in the Calcs tab
- Remove "Emberwake, Ruby ring"
- Check the Ignite Widget in the Calcs tab
```
https://pobb.in/uUpXDOsGJPe4
```

Fix Ignite Max stack below 2 not displayed in the Ignite calc widget. #7592

---

src/Classes/PassiveSpec.lua
src/Classes/PassiveTreeView.lua

Fixes #151, fixes #7642 
Supersedes #7654
Dependencies for intuitive leap-like nodes were handled by orphan pruning, and the nodes never had their dependencies properly resolved. Adds new logic to properly resolve their dependencies and thus adds support for features such as hover dependency highlighting and deallocated tooltip stat summaries. Also, corrects pathing behavior for nodes going through allocated nodes that are also affected by intuitive leap-like jewels (#7642).
- Created a build with a variety of intuitive leap-like jewels present, some overlapping
- Verified that dependencies were generated correctly in all situations (that I could think of)
- Verified that deallocated node sums and tooltip stat summaries correctly reflected dependencies
- Verified that pathing through …

Correctly generate dependencies for nodes affected by intuitive leap-like jewels

---

src/Classes/CalcsTab.lua

built on #6827 (that should be merged first)
Optimisms the power calcs to cache more of the results, this increases the cache size by around 1.3% for a typical build, and yields up to a 10% speed increase over the multiple builds I tested, with most builds getting a 3% improvement for offence/defence, and around a 7% improvement for a stat specific calc

Power calcs cache optimisation

---

src/Classes/CalcsTab.lua

built on #6828 (that should be merged first)
This creates a distance map to run the power calcs in order of distance, the extra time taken was less than 10 milliseconds and within margin of error
This is being put into draft as theres still a few things I would like to do with this, like use this to show progress on the power report, and to update the power report while its being run, as those seem within scope of this change

Ordered power calc (tree show node power)

---

src/Classes/PassiveSpec.lua

Fixes #7728
The test variant is generated with conquered keystones, which aren't present in the `keystoneMap` (and aren't actual mods).

Fix crash caused by invalid impossible escape keystone

---

src/Data/Uniques/body.lua

Fixes #7734
`Evasion Rating is increased by Overcapped Cold Resistance` was missing from current version of [Replica Perfect Form](https://www.poewiki.net/wiki/Replica_Perfect_Form) (3.23) Also moved the block chance line to be inline with where it is in game.

Fix mod missing from current verison. Move mod line

---

src/Modules/ModParser.lua

Fixes #7729 
Fixed the issue that the Block chance overrride also applied to dual wielding characters
- added condition for using a shield in modparser
mod("ReplaceShieldBlock", "OVERRIDE", num)
mod("ReplaceShieldBlock", "OVERRIDE", num, { type = "Condition", var = "UsingShield" } )
https://pobb.in/d2QlOIfFC96w

Fix for Determined Survivor Block Chance

---

src/Modules/ModParser.lua

Fixes #7748
Fixes incorrect implementation of `non%-unique jewels cause increases and reductions to other damage types in a (%a+) radius to be transformed to apply to (%a+) damage` mod

Fix cheiftain's damage conversion

---

src/Data/Uniques/helmet.lua

Fixes #7743
Fixes the Life roll on the Blood Price unique helm. Previously was added wrong (couldn't find the previous rolls ever on the wiki)
https://www.poewiki.net/wiki/Blood_Price
- select blood price from items
- check life roll not configurable
https://pobb.in/af92Pa-2TY8K

Fix Blood Price Unique stats

---

src/Modules/CalcDefence.lua
src/Modules/ModParser.lua

Fixes #7737
Varunastra was setting incorrect mod flags for weaponcfg used for spell suppression.

Fix incorrect modflags for weaponcfg

---

src/Data/Bases/wand.lua

Updates values based on information from patch notes for 3.25. As seen here: https://www.pathofexile.com/forum/view-thread/3531661#itemchanges
- Open PoB
- Items > Craft Item > Rarity: Rare > Type: Wand > Base: pick any wand that had their value changed > Create
- Values should be there updated
https://pobb.in/a2pxLf2d_SFJ -- It only has one wand there just to show

fix: update wand crit chance and attack speed

---

src/Data/Uniques/Special/New.lua

The value in the livestream was only 5%, which is nerfed from perandus pacts 7%, I assume the rest of the values are also much weaker so I could nerf them all by around 30%, but for now just fixing the crit chance

correct The Light of Meaning crit chance

---

src/Classes/NotableDBControl.lua
src/Modules/ConfigOptions.lua
src/Modules/ModParser.lua

Implements:
- Bastion of faith
- Rising tempest
- Worship The Blightheart
- Adaptive steel
Unsure how to handle:
- Deliberate Brutality
- Vinespike Cordial
Allows for keystones with anoint recipes to be anointed.

Implement support for new anointable nodes

---

src/Data/Skills/act_int.lua
src/Export/Skills/act_int.txt

Fixes #7612 (at least the intention behind it).
Adds a new mode for Spark & Spark alt qualities that uses the maximum amount of possible hits with the given spark duration assuming a 100% hitrate after each 0.66s cooldown period.
Didn't add the mode to Vaal Spark, as its mechanics are different to normal Spark & a DPS number is useless for it anyways.
- Add spark gem
- Select "Maximum Hits" mode
- DPS should go up (baseline x3 without any duration)
- spec some duration on the tree -> DPS should go up as soon as you hit a breakpoint.
https://pobb.in/18bN-kP4WaPe

Add support for spark maximum hits mode

---

src/Modules/CalcPerform.lua
src/Modules/CalcSetup.lua

Fixes #7622  .
widowhail multiplier only applied to the player not the minions as well
- checked widowhail minion pob
- checked widowhail non minion pob (values stay the same)
- minion: https://pobb.in/Q1bvbkFDWk4J
- non minion: https://poe.ninja/builds/necropolis/character/Spirituus/Spirituus_Bait_Again?i=6&search=items%3DWidowhail

fix(7622): store widowhail multiplier & apply to clones

---

src/Data/Skills/act_dex.lua
src/Export/Skills/act_dex.txt
src/Modules/ConfigOptions.lua
src/Modules/ModParser.lua

Adds a second skill part for tornado shot, which deals extra dps based on the combined average number of secondary projectiles which hit
If tornado shot does not return, each projectile tornado shot shoots (and any from splitting) fires 3-4 secondary projectiles, of which 1 can hit the original target again, the chance this happens is configurable, and if not configured increases with the helm enchant
Uses #6738 and #6744 but they are not required to be merged for this to function

Add support for tornado shot secondary projectiles skill part

---

src/Modules/CalcDefence.lua
src/Modules/CalcOffence.lua
src/Modules/CalcPerform.lua
src/Modules/ModParser.lua

Prevents Life Recovery via:
TEST POB:
`https://pobb.in/RYXRt3Jr6ozL`

[3.25] Vaal Pact implementation

---

src/Data/Skills/act_dex.lua
src/Export/Skills/act_dex.txt

Fixes #3035  .
creating a statMap in /src/Export/Skills/act_dex.txt that creates a GlobalEffect "Ambush", with the Melee ModFlag.
Using the already defined Export names for crit chance and crit multi; "vanishing_ambush_critical_strike_multiplier_+" and "ambush_additional_critical_strike_chance_permyriad".
Two-Handed weapons are not excluded on purpose, to still support weapon swapping for skills with duration (Rage Vortex)
-  Tried various skills that don't match the ModFlag to ensure they don't work
-  supported ambush with enhance and checked quality increases to ensure correct scaling
https://pobb.in/WHBCnFfCHtUJ

Added support for Ambush skill

---

src/Modules/CalcDefence.lua
src/Modules/CalcPerform.lua
src/Modules/ModParser.lua

Ynda's Stand, Studded Belt now has its mod "Gain Ward Instead of 50% of Armour and Evasion Rating From Equipped Body Armour" working.
- Equip belt
- Equip body armour with Armour & Evasion
- Half of it is now Ward, other half is Armour and Evasion
https://pobb.in/I-bQmf6nxJI-

added Ynda's Stand belt's Armour Evasion to Ward Conversion mod

---

src/Classes/DropDownControl.lua
src/Classes/ImportTab.lua
src/Classes/SkillsTab.lua
src/Classes/TreeTab.lua
src/Modules/Build.lua

Fixes #7180 
Allow users to keep selected allocated notables safe during Militant Faith search. This feature is only for Militant Faith selected and Filter Nodes true and does not care for node distance, only allocated nodes. This PR should not affect any of the other timeless jewels. The trade URL should be the same as well so users don't have to manually find the safe ones in the list returned, which also means they can use the URL to filter the devotions on the Trade site if preferred.
There are quite a few scenarios here to make sure only Militant Faith is affected
- Regardless of blocked nodes, no other timeless jewel should be affected, so for each other jewel, I've tested one/all allocated notables blocked for Militant Faith and validated those nodes are not blocked for the other …

Add support for blocking allocated nodes when searching Militant Faith jewels

---

help.txt
src/Classes/ItemsTab.lua

Fixes #n/a.
Adds a keyboard shortcut to toggle tooltip generation off/on in the **Items** tab, in response to a user's request to add a manual-calculation mode and button, or something of that nature.
The shortcut, and tip-text, are taken from the **Tree** tab: <kbd>Ctrl</kbd>+<kbd>d</kbd>
This was the simplest code-change (hack) I could see at the time, and while it does solve the user's issue in a roundabout way, I realise there are good reasons why this PR may end up rejected.
A better way might have been to intercept recalculation requests and only recalc when a hotkey is used, but that seemed rather involved at first glance.
Tested with user's build code on current dev branch of pob.
https://pobb.in/LhJE9HFWkVWX  (purely experimental)
edit: updated "After screenshot" to latest …

Add a tooltip stat-diff toggle to Items tab

---

spec/System/TestSkills_spec.lua
src/Modules/CalcPerform.lua

Essentially an improved version of https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5164 that utilizes skill cache functionality. Additionally solves an order of calculations issue with certain effects (such as adrenaline) that get processed in `doActorMisc` causing them to not be applied to maximum sustainable stages calculations.
- Test scorching ray from build from #5162
```
eNq1G1132rjyufsrfHhviCHQpofsHkI-z0kaLqTtvU97hC1AW9libTkJ--t3RvIXFDky9s1DC9Z8j2Y0MzKjP94C7rzQKGYivOi4J6cdh4ae8Fm4uuh8e775-Lnzx--_jaZErp-WlwnjuPL7bx9G6rPD6QvlgNdxJIlWVH7PKPX_BEobEso1FeEj-UtEt8K_6HwVIe04CxL6TGbfPE7i-CsJ6EVn7gFyxyGxR0N_UjxPAdckIp6k0QNyHSdSPAofVpeEx7AcEBbOhfeTyttIJBsl1Qujrxro_nH6NHsuycTCskyg0ofRlJMtjeaSSCeGfy46Y7AMWdE7JoEU4QnQOe10K2EvkyiWVySAj-_jzDeU-jnY4OR8aIKcRvR6uaSeZC90EjE5WZPQs-BQF_Yx4 …
```

Fix maximum sustainable stages calculations ignoring certain buffs/mods

---

.editorconfig

Most editors support editorconfig or have plugins for it, its universal config for specifying whitespace/line-length rules. Especially useful for editors like Neovim who support it out of the box and dont have other concepts of per project whitespace configuration.
https://editorconfig.org/

Add editorconfig configuration

---

src/Classes/CalcSectionControl.lua
src/Classes/CalcsTab.lua
src/Data/Global.lua

It is sometimes difficult to find what you're looking for in the Calcs tab since there are a lot of sections and calculations.
This PR adds a search input to the Calcs tab. When searching, matching labels on the page are highlighted. Both section titles and individual calculation labels are able to be searched. The search box can be focused with `ctrl + f`, as you'd expect.
No automated testing is added for this feature.
- `ctrl + f` focuses the search input and selects any existing text
- Changing tabs with an active search doesn't cause issues. Returning to the Calcs tab with an active search maintains the search as expected.
- Custom highlighting color codes work (set in Options -> Hex colour for highlight nodes)
- Collapsing and expanding sections works while searching and not …

Add search to the Calcs tab

---

src/Data/Uniques/Special/Generated.lua

Generates Skin of the Lords and Impossible Escape variants from tree data, using only keystones that are natively on the tree. 
Previously was generating invalid variants with conquered keystones that had been missed on the exclusion list.

Generate keystone items from tree data

---

src/Modules/CalcOffence.lua

#7662 introduced multiple trap/mine throws, this doesnt take into account cooldown skills, maximum stored uses, or trap/mine limits
giving it many more throws than is possible 
For now this PR just disables it on cooldown skills, but will update the PR to properly calculate the amount thrown based on cooldowns, throw speed, and limits if it hasnt been merged by the time I get around to it

Fix Mine and Trap Throw Count

---

src/Modules/BuildList.lua

Adding Level Sorting for the BuildList.
- Implemented then tested
- Tested both in and out of folders
- Set up tests to confirm Level sorting was working unique to other sorts
New Level Sorting:
In folder -- ![image](https://github.com/user-attachments/assets/6827cc65-6a6f-41e3-8049-03041aa7967f)
Using the other sorting methods, showing Level sorting has unique functionality.

adding build sorting by level

---

src/Modules/CalcOffence.lua

This will now take the pre-determined "pre-armour physical damage" as base damage for impale damage calculation
Fixes #7726 and #7727.
It was previously taking into account the already mitigated (through enemy armour/pdr) physical hit.
- Checked POE Wiki (I know, this might not be up to date) but there it states indeed 
_"impale records hit damage before the defender's [mitigation](https://www.poewiki.net/wiki/Receiving_damage)"_
- Checked the Wiki on PoeDB
_"When a hit applies impale to a target, 10% of that hit's [physical damage](https://poedb.tw/us/Physical_damage) is recorded before any [damage mitigation](https://poedb.tw/us/Receiving_damage) is applied."_
- Used the use cases of #7726 to verify if the damage is indeed correct in all cases.
See #7726
```
https://pobb.in/KBIVH-a04Pk1 …
```

Use pre-armour physical damage as base damage for impale damage calculation

---

help.txt
src/Modules/Build.lua

Common use case: you only want to use 1 config set for all loadouts, but putting every loadout tag in the config name feels a bit silly. This makes the solution a bit more robust and easier to use.
https://pobb.in/NYUDVHBDjQxD

If there is only 1 set, assign it to all loadouts

---

src/Modules/ModParser.lua

Fixes #7764  
Strength of Blood Physical Damage Reduction was applying even if not leeching / having no leech sources.
- Make a PoB without leech
- Add a legion jewel with strength of blood
- PDR should not be applied.
- Add leech
- PDR should be applied now.
https://pobb.in/TVCpOHP366PS (Strength of blood unselected, gave PDR in tooltip before)

Apply Strength of Blood PDR only while leeching

---

src/Modules/Build.lua

Closes #7790
https://pobb.in/tzW3NSwDzqo8

Use Default value for loadout with no set name match

---

src/Classes/TreeTab.lua

Pressing the up arrow or down arrow would change the tree selection dropdown twice per key press when it was hovered or dropped down.  This fixes that behaviour (in a slightly hacky way)

Fix tree selection hotkey double selecting

---

src/Data/SkillStatMap.lua
src/Data/Skills/act_int.lua
src/Export/Skills/act_int.txt

The mod was not in the stat map. Moved it to the SkillStatMap file as it's used on a bunch of gems now

Fix Power Siphon not benefiting from Spell Damage

---

src/Data/Skills/act_dex.lua

Forgot to remove the 2 lines from the stat list
Fixes #7796

Fix Caustic Arrow of Poison still have Flat Damage

---

src/Classes/PassiveSpec.lua

`pathDist` calculation was altered for Intuitive Leap-likes support but I missed that this condition assumes it was incremented already, preventing users from pathing from one of the Path of the X nodes to the class start area.

Fix pathing from Ascendant path node to class start

---

src/Modules/CalcOffence.lua

Fixes https://www.reddit.com/r/pathofexile/comments/1e9kh0w/path_of_building_community_2430_325_tree_build/lef48np/
Perfect agony did not include on enemy effects that increase critical strike multiplier.

Fix Perfect Agony not including on enemy effects

---

src/Data/Skills/act_str.lua

The skill had a constant stat that was adding +2 seconds to it

Fix Enduring Cry having incorrect duration

---

src/Data/Bases/claw.lua

Fixes # .
Updates values based on information from patch notes for 3.25. As seen here: https://www.pathofexile.com/forum/view-thread/3531661#itemchanges
- Open PoB
- Items > Craft Item > Rarity: Rare > Type: Claw > Base: pick any wand that had their value changed > Create
- Critical strike chance should match 3.25 patch notes
Build with a claw that had crit chance changed from 6.3% to 7.5%:
https://pobb.in/WaogEe45sptt

Update Claw base Critical Strike Chance for 3.25

---

src/Classes/PassiveTreeView.lua
src/Modules/Main.lua

Fixes https://www.reddit.com/r/pathofexile/comments/1e9kh0w/path_of_building_community_2430_325_tree_build/lef5dcc/
Adds an option to disable PoE Planner inspired node search highlight. Highlighting is enabled by default.

Add toggle for node search vieport edge highlight

---

src/Modules/CalcPerform.lua

Fixes issue mentioned on discord
When penance brand is supported by cast on death the hit speed is nil. Math operations on nil values result in crash in lua.

Fix crash when trying to add gems to Penance Brand of Dissipation

---

src/Modules/CalcOffence.lua
src/Modules/CalcPerform.lua

The calculation was being based off the uptime of the Warcry instead of the uptime of the exerted attacks it provides
Fixes #7836

Fix Seismic Cry AoE calculation

---

spec/System/TestImpale_spec.lua
src/Modules/CalcOffence.lua

Fixes #7787 .
Impale damage did not respect enemy damage taken modifiers. This bug is a result of fixing impale armour application recently.
Clarify "average physical hit" in impale breakdown as "average physical hit before mitigation".
- Checked changes to impale dps with different "enemies take % more physical damage" modifiers and Pride/Vulnerability
- Tested with minimal example and real build
https://pobb.in/wFfb1O9sTa5M
Change first line in Custom Modifiers and watch dps change. 1000 Hit DPS, 100% impale, 10% more damage taken, ignore all armour.
----
As far as I can tell, the only relevant modifiers are `DamageTaken` and `PhysicalDamageTaken` (Physical reduction and Armour works already), Other modifiers affecting impale, like reflected damage or flat subtractions seem not relevant …

Fix impale not using enemy damage taken

---

src/Data/ModCache.lua
src/Modules/ModParser.lua

Rage effect should be applying to mods that use the `per x Rage` wording as stated in the patch notes
`Rage effect applies to the damage inherently granted by Rage, and other bonuses granted per X Rage if you have any. Bonuses while you have a certain amount of Rage, or other effects that refer to your Rage but do not cause Rage to grant additional stats, are not affected.`
Fixes #7795

Fix Rage Effect not applying to "per x Rage" mods

---

src/Data/TimelessJewelData/LegionPassives.lua

Fixes the Rage on hit notable replacing the wrong stat
Change 40% rarity stat to 12% res efficiency
Fixes #7848

Update Legion Notables with 3.25 changes

---

src/Classes/Item.lua
src/Classes/ItemsTab.lua

Fixes  #7841.
This was accidentally inverted because "reduced" made the number smaller and I wasnt paying enough attention
This also fixes the base value being slightly wrong (0.61 instead of 0.6)

Fix Tincture Mana Burn rate applying inversely

---

src/Classes/ConfigSetListControl.lua

Fixes #7852 .
When you select a config set and hit the copy button, that action copy the top object but keep reference for internal tables.
This MR allow to do copyTable in deep mode

Enable recursive copyTable for ConfigSet Fix #7852

---

src/Modules/CalcPerform.lua

Fixes #7869 .
Arcane Surge cast speed increase was tagged as `ModFlag.Spell`, being the only Speed increase tagged like this.
Changed it to `ModFlag.Cast`, which allows Wilma's Requitals "Increases and Reductions to Cast Speed apply to Attack Speed" to use the Arcane Surge cast speed.
https://pobb.in/vaSKByGO7J4G
Toggling Arcane Surge in config will change the attack speed of Kinetic Bolt after fix.
Tested against an involved Hierophant PoB using Arcane Surge effects, could not find any difference.

Change ArcaneSurge cast speed increase to ModFlag.Cast

---

src/Classes/PassiveSpec.lua

Fixes #7876
Accounts for Intuitive Leap-like jewels which have no radius due to being socketed in a cluster socket.

Fix crash caused by intuitive leap-like being socketed in cluster socket

---

src/Data/ModCache.lua
src/Modules/ModParser.lua

The mod was missing the skillType check
Fixes #7877

Fix Cruel Retort granting Attack/Cast speed to all skills

---

src/Data/Skills/act_str.lua
src/Export/Skills/act_str.txt
src/Modules/ConfigOptions.lua

Adds support for Automatic calc of maximum Rage sacrificed by Rage Vortex
Also allows you to overwrite the value with a config if needed
Fixes #7148

Add automatic calculation for Rage sacrificed when using Rage Vortex

---

src/Modules/CalcOffence.lua
src/Modules/ConfigOptions.lua

Added config options to override the number of trap/mine throws.
- Trap skills now have this option: ![image](https://github.com/user-attachments/assets/198736e2-ef56-468c-934d-c423c6ec3a3e)
- Mine skills now have this option: ![image](https://github.com/user-attachments/assets/b3dfddaf-3016-4d78-984c-5944572dc42c)

Add config options to override the number of Trap/Mines per throw

---

src/Classes/SkillsTab.lua

Fixes #7826
When skill set is switched via switching loadouts, the old display group stays active in the skill tab window
- Navigate to skill tab window
- Click on some gem group
- Switch loadout
- Gem group should reset to first one
https://pobb.in/u/thedeathbeam/pf-poison-scourge-arrow

Show proper skill group when switching loadouts

---

src/Modules/CalcOffence.lua

re Fixes ##7831 .
Impale damage was not respecting "Damage taken from Hits", like new Flesh and Stone.
Impale will keep not respecting "Damage taken from Attacks", as it seems correct. We did ingame testing.

Fix impale not using damage taken *from hits*

---

src/Data/Skills/act_str.lua
src/Export/Skills/act_str.txt

Fixes #7795
Hope I didn't break anything, I just mimicked your changes to other 'per x rage' stats. 
POB for posterity: https://pobb.in/IM7VlUeN5ZoY
has 100 rage (+25 max in custom to simulate new warcry)
and 100% rage effect from lvl 11 berserk + rite of ruin
Before: 
After:

Fix Cleave of Rage area not scaling with Rage effect

---

src/Data/Bases/dagger.lua

Fixes #7878 .
Some rune daggers had wrong Critical Strike Chance.
Patch notes: https://www.pathofexile.com/forum/view-thread/3531661
- Open PoB
- Create new item
- Rune Dagger
- Pick any of the bases changed (Boot Blade, Boot Knife, Butcher Knife, Carving Knife, Ezomyte Dagger, Flashfire Blade, Flickerflame Blade, Imperial Skean, Infernal Blade, Royal Skean, Skean, and Slaughter Knife)
- Check value of Critical Strike Chance to see if it's 8%.
https://pobb.in/ECab6k9t56g5 - Example with boot blade

Fix Critical Strike Chance of some Rune Daggers

---

src/Modules/CalcPerform.lua

I assumed the damage benefit was a part of the buff so had it in the wrong block of code
Fixes #7899

Fix Rallying Cry Exerted damage mod not working with Autoexertion

---

src/Classes/ModStore.lua
src/Data/Skills/act_str.lua
src/Export/Skills/act_str.txt

Needed to switch it to a preSkillType function for the AoE calculation to include the BASE AreaOfEffect value
Also includes support for `divVar` which lets us map a stat to the div value so if GGG ever updates it, we don't need to manually fix it
Fixes #7906

Fix Rage Vortex AoE per sacrificed Rage mod not working

---

src/Data/Skills/act_str.lua
src/Export/Skills/act_str.txt

The previous condition check was checking for mod on the player which would break the mods when applied to minions
This doesn't work with the Party tab still though
Fixes #7913

Fix Banner skills not applying to Minions

---

src/Classes/TreeTab.lua

Fix cancelling tree version conversion didn't revert back to previous value in dropdown

---

src/Modules/CalcOffence.lua

Uses combineStat to cleanup the impale code
Also removed impale chance if not in mode_effective, this is for 2 reasons, firstly the impale is on the enemy and not part of the character, and secondly because its bugged in PoB anyway due to where `impaleStoredHitAvg` is set within mode_effective already and so would show you dealing 0 damage

Cleanup impale

---

src/Modules/CalcOffence.lua

Fixes #7912.
There are some divisible-by-0 calculation errors for monster explosions (such as chieftain, occultist, and gladiator ascendency). The "On Kill Monster Explosion" skill seems to have a cast time of 0, and causes some stats to be `nan` or `inf`.
When the ignite duration is 0 seconds, the ignite DPS becomes `inf`, thus reaching dot cap.
I'm worried that the 0 cast speed for monster explosions would cause any other existing or future issues, but here's the bandage fix for the ignite problem caused by it.
- Any explosion effect (from gear or ascendency) that has fire damage 
- See Calc tab for ignite details
https://pobb.in/dbGiJENwcvZX

Fixed monster explosion ignite divide by 0 calculation error

---

src/Data/Uniques/mace.lua

Fixes #7933.
Dark Seer is missing global chance to blind on hit

Dark seer missing global chance to blind on hit

---

src/Data/Skills/act_dex.lua

Fixes # .
Updating the Skill gem description for Puncture, so it matches the new description announced by GGG. Also makes it match the actual weapon requirement already changed for the skill gem.
-
-
-

- Update skill gem description for Puncture

---

src/Modules/CalcDefence.lua

Fixes #7977 (and the other 5 places people have reported it to me)
Gladiators shield is 50 block doesn't count as coming from the shield itself and so doesn't apply bonuses based on that.

Fix gladiator shield block override from counting as from the shield

---

src/Modules/CalcSections.lua

Fixes #7956.
Damage over time calc section was not showing a value for the Dot Multiplier total despite calculating the damage correctly.
- Created a test build that includes the Blight of Contagion skill and a few damage over time multiplier passives.
https://pobb.in/W2bTRwTfLHG2

Added modType to CalcSections config for DotMultiplier

---

src/Modules/CalcPerform.lua

The condition check was incorrect and the mod was also using the wrong ModFlag

Fix Ravenous Passion helmet not granting Spell damage from Rage

---

src/Modules/CalcPerform.lua

Confirmed with GGG that the mod does not work
`If the skill is prevented from granting buffs to allies, then it cannot be affecting allies, therefore it doesn't get the bonus`

Fix Rallying Cry Exerted damage mod working with Autoexertion

---

src/Classes/TreeTab.lua

The Militant Faith "blocking" now protection inside of Timeless Jewel search was only working for one stat at a time. There exists a chance that a protected node was still being changed.
This PR sets Devotion on all protected nodes and sets a minimum weight on any other desired node. If the user sets their own Devotion stat into the table, that takes priority.
<pre>eNrtXG1v4kgS_rz8ihbSSndaJsFvvGSTPRHI220ywwCZ2b3TKerYDXimsRm7nYQ95b9fdbcNhtDGxnw5KatVBtxVT1dVd1VXlW1O__Eyo-iJBKHre2dV7aheRcSzfcf1JmfV-9Hlh1b1H79VTvuYTT-NzyOX8pHfKj-dis-IkidCz6q6XkUMBxPCviRQxgNAzbHHpsT37vA3P7jynbPqR98jVfSIPcdlyTeb4jD8iGfkrDq0gbmKcGgTz-murseEUxxgm5Hglk_biZh_5zswyoIIRmfY9Ya-_Z2wq8CP5qBNFT255FnS3Nz1Pw1GKZFcLy0SqPTTaZ_iBQmGDDMUwp-zagcsgyekh2fwF9AwjQCqfmQ09epxJst5FISsCN9wToizJNWO9HZDRdoPyMV4TGzmPpFu4LLuFHt2ahoVX1Hau4gy …

Improve Militant Faith Notable Protection

---

src/Modules/CalcOffence.lua

Fixes #7900 .
Implemented a condition to set "ScorchChanceOnCrit" to 100% when "IgniteCanScorch" flag is active. This ensures the Scorch ailment is applied on critical hits when using the Warden's Oath of Summer.
When Ignite was converted to Scorch, the Scorch chance on crit was not updated in Calcs to reflect that Scorch now applies on crit.
- Verify current state, Scorch does not have 100% chance to apply on crit according to Calcs
- Make changes
- Compare pre and post calculations for Scorch and other ailments/alt-ailments
- Deallocate Oath of Summer and gain Scorch from another source to ensure that values are as expected
Provided in original issue:
https://pobb.in/_wT1ioEzlZ-e
Test Build (Remove Oath of Summer node, add Flamesight helmet):
https://pobb.in/_LPrC81NR2su
Provided build: …

Add Scorch chance on crit for Warden's Oath of Summer

---

src/Modules/CalcOffence.lua
src/Modules/ModParser.lua

Fixes # .
Adds support for the line "Life Recovery from Non-Instant Leech is not applied" from the Strength of Blood keystone
- Add source of life leech and source of instant life leech
- Add Strength of Blood of blood to a build
- Verify only Instant Life Leech is part of Life Leech Rate in calcs
https://pobb.in/7kckh4cytUcH
Disabled imperial claws life gain on hit to make instant leech easier to identify

Disable Non-Instant Life Leech with Strength of Blood

---

src/Data/ModCache.lua
src/Data/Skills/sup_str.lua
src/Export/Skills/sup_str.txt
src/Modules/CalcOffence.lua
src/Modules/ModParser.lua

The More mods were being summed together before being multiplier. This also fixes the terrible breakdown names I previously used
Fixes #8005

Fix damage calculation when using both Autoexertion and Echoes of Creation

---

src/Export/Classes/GGPKData.lua
src/Export/Classes/GGPKSourceListControl.lua
src/Export/Main.lua

Dat files stopped appearing in my exporter due to `\r` appearing when Lua used `cd`.  Not sure if anyone else has this bug, but this fix should be relatively safe for everyone.
This also fixes:
- a dead branch that I believe was causing issues loading a saved spec
- Unclear wording and ability to enter both a DAT file location and a GGPK location
- Editing the current DatSource doesn't reload the data
- Old DAT files were sticking around even if the newly parsed ggpk didn't contain them

General Exporter improvements

---

src/Data/Skills/sup_str.lua
src/Export/Skills/sup_str.txt
src/Modules/CalcOffence.lua
src/Modules/CalcTriggers.lua

Fixes #8017
Fixes autoexertion not triggering supported skills.
~~This does not currently fix the support effect not causing warcries to reserve mana. This issue is caused by missing `SkillType.HasReservation` flag causing the reservation calculations to be skipped here~~:
https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/0904a877041149b757a30738005a3403f9838745/src/Modules/CalcPerform.lua#L1532
~~Problem is there's no good way to add the the flag without also making the skill incompatible with the support effect as it excludes skills with that flag.~~
Requires https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/8029 to solve mana reservation issue.

Fix autoexertion not triggering supported skills

---

src/Data/Skills/sup_dex.lua
src/Export/Skills/sup_dex.txt
src/Modules/CalcOffence.lua

Rupture support has 2 mods: 
- up to 29% more dmg taken per Rupture stack
- 25% quicker bleed on enemy per Rupture
Currently, the "more dmg taken" mod is inversed with the "quicker bleed" numerically, and only goes up to 75%. 
For the quicker bleed, I'm not sure where exactly this is calculated but 75% quicker shouldn't mean a 29% duration as this is the case in POB
- Opened the same build and checked that both the more damage taken and duration matched the proper calculation
https://pobb.in/91FAzNjlHslt

Fixes Rupture using the wrong stat for damage taken and Bleed duration

---

src/Classes/ItemsTab.lua

Fixes #7966 .
Due to an incorrect If statement regarding setting quality to nil for Amulets, Belts, etc, items that should have quality set to 20 by default were going into NormaliseQuality() with a nil value for quality, causing it to get set to 0 by default.
- Verify current state, non-quality items had no option for quality, quality items had their default set to 0
- Make changes
- Check a non-quality item such as an Amulet, no option to set quality and no visible quality as expected.
- Check a quality item such as Body Armour, quality is set to 20 as a default.
- Check several other examples of both cases, behavior as expected for both non-quality and quality items that were tested
NA
Amulet Example:
Body Armour Example:
Amulet Example:
Body Armour Example:
Additional Note:
This code …

Fix quality check condition for item types

---

spec/GenerateBuilds.lua
spec/System/TestAilments_spec.lua
spec/System/TestAttacks_spec.lua
spec/System/TestBuilds_spec.lua
spec/System/TestDefence_spec.lua
spec/System/TestItemMods_spec.lua
spec/System/TestItemParse_spec.lua
spec/System/TestItemTools_spec.lua
spec/System/TestSkills_spec.lua
spec/System/TestTriggers_spec.lua

Some code in `spec` has mixed or space indents.

indent space -> tab

---

src/Modules/ModParser.lua

Fixes #8046.
This mod is the only mod that manually has a skillId mapped, so when all the granted effect IDs changed, this needed to change too.
- No crash when hovering the mod

Fix incorrect skillId for elder staff power charge on crit

---

src/Modules/Build.lua

Throws a recoverable error with informative message on zero-length dbXML:

Check for empty build file on load.

---

src/Classes/SkillsTab.lua

Fixes #8067 .
The bug was not specific to overexertion (like the issue states), and rather is present with all gems.
Fixes selecting skills with the keyboard by properly creating an undostate when one should be created.
Also fixes not creating an undostate when first a skill was selected with the keyboard(up, down), but then clicked with the mouse.

Fix issue where PoB did not detect changes when selecting gems via keyboard shortcuts

---

src/Modules/CalcDefence.lua
src/Modules/CalcPerform.lua
src/Modules/ModParser.lua

The calculation for the Armour/Evasion to ward conversion didn't take Tempering catalysts into consideration. This fixes it.
- added the code to make it work
- used the PoB below
- switched the values and the calculations are correct now
https://pobb.in/sF-bEns2KZiF

Fix Ynda's Stand ward conversion mod not taking catalysts into consideration

---

src/Modules/ModParser.lua

Fixes #8105
Mods from [The Light of Meaning](https://www.poewiki.net/wiki/The_Light_of_Meaning) applies to jewel sockets causing them to grants the added mods.
- Test jewel in socket granted by voices
- Test jewel in normal tree large socket
```
eNq1XFmT2siyfh7_CqIj7tM1tvZlwj43xC7QBgIkeCG0lBbQhjYkfv0tCXqZHtOm3X1mItqSKvOrzKyqrKxUoh__V4VBpwRp5sfRzwf0G_LQAZEV237k_nxYLUdd5uH__vPlh2Lknuz0Cj9oWv7z5a8f7XUnACUIfj4w-EMnN1IX5OtHKHwHoRIjyj0QR6Kxj9NxbP98WHqgl_oRmEGYh45pRLaf_3yQ4gg8dKzAyDLJCMHPB9WCIA8dI7NAZPefn3PtA4gKqT0jNawcpEIjA1fksRjbkMQxggyChYYfqbF1APk4jYsE6vbQKX1wuhDxoiIvli8E9KOrgGMjLQ6eET1AJf_6oQRGDVI1N_JOBv9AAaCtDBdMfChBaQQFxEIevr9J2yvSLB8YIbz8PY-aAGD_nkxJwdBxgJX7Jeinft6HElt3wL-XViyC3E8CH6RP9Og38hbH5F_gKHITfhnnRjBQ1N8LcqGM77C45udeL4AWvAu3oebdyM_B3eRK7Gdx9C6p7yLuF0EAV8RdtA …
```

Fix The Light of Meaning adding stats to allocated sockets

---

src/Data/Uniques/jewel.lua

Fixes #8086
As of [3.21.0](https://www.poewiki.net/wiki/Version_3.21.0) elemental damage mod on [Combat Focus](https://www.poewiki.net/wiki/Combat_Focus) is not limited to attacks.

Add variant for post 3.21 Combat Focus

---

src/Data/Skills/act_str.lua
src/Export/Skills/act_str.txt
src/Modules/CalcPerform.lua
src/Modules/Data.lua

Warcry Buffs are scaled and floored before warcry power is taken into account, this causes the numbers to be wrong, especially when also scaled by uptime, tested all warcries ingame except rallying cry and all were wrong and are fixed by this change except for infernal cry (will talk later about it)
This change also removed duplicate buff code for minions to check parents warcry power, and makes it easier to implement party tab support for warcries
The downside of this change is the buff notes are less informative, but that can be changed by changing the notes if we want it to show there
All of them tested on multiple builds but here is an example of a minimum test setup: https://pobb.in/2qs_Nsh4BIBy
As for infernal cry, it seems it is not scaled by warcry effect?
The values now line up …

Scale Warcry buffs by Warcry Power earlier in Calc

---

src/Modules/CalcPerform.lua

The calculation for active totems was done far later than the calc for ArcaneSurgeEffect causing it to not apply
I believe moving this code should't cause any issues
Fixes #8099

Fix Arcane Surge effect per Summoned Totem mod not working

---

src/Modules/Build.lua

When hovering over a gem in the gem selection dropdown while having anything other than full dps selected in the sort gems by dropdown the tooltip would show that the player loses all full dps (see screen shots). This was caused by a funky lua behaviour here:
https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/c76a5fea58a8ccfc7421cb34e2f614808a8246ae/src/Modules/Build.lua#L1864-L1866
The above condition would return false even though self.viewMode was not `"TREE"` see below minimal repro:
```lua
test1 = "test1"
test2 = false
test3 = "justtest"
print(test1 == "test1" and not test2 and not test3 == "test3") -- false -- the condition currently
print((test1 == "test1" and not test2 and not test3) == "test3") -- false
print(test1 == "test1" and not test2 and not (test3 == "test3")) …
```

Fix full dps visual bug on gem dropdown

---

src/Modules/CalcDefence.lua

The Belt mod does not affect the amount of evasion on the body armour for the purpose of Trickster's Escape artist node
This is also verified on the wiki https://www.poewiki.net/wiki/Ynda%27s_Stand

Fix Ynda's Stand not working correctly with Trickster's Escape Artist

---

src/Data/Uniques/mace.lua

The crit chance mod was updated to compensate for the increased base crit on Karui Septres
Fixes #8041

Fix Maata's Teaching using wrong crit chance range

---

src/Modules/Build.lua

Clicking OK takes the user to the build list screen.  Also works for the auto-build-load at startup.

Nicer check-empty-build popup

---

src/Classes/ImportTab.lua

We were seeing large build codes being stored in the XML, as they weren't being differentiated from external build links.  Other than the obvious unintended use case, this could also result in ballooning build file sizes as builds kept building on each other and nesting infinitely deeper.

Fix infinitely nested XML stored as importLink

---

src/Modules/CalcDefence.lua

Fixes #8088
Fix rare case with gain on suppression with no chance to mitigate damage (eg 100% suppress chance with no chance to block/dodge/avoid), this allows gain on suppression to still apply to ehp calcs in this rare case

Fix rare case with gain on suppression with no chance to mitigate damage (eg 100% suppress chance)

---

src/Classes/PassiveTreeView.lua

Fixes #7958 .
Compare passive tree doesn't visually show changed mastery
```
eNrNXFlz6rgSfp75FRTP5sSW5W0qmVuELQsEAmR9SRkjwImxiReWMzX__bYks2SxYwNV985DDka9t_qT1DJz-p_l1CnMiR_YnntWlH6JxQJxLW9ou-Oz4l2_XtKL__n7z9OOGU7ao_PIdujI33_-cco-FxwyJ85ZUUPFQmj6YxLer0XJLyBqZrrhhHhuy3z1_IY3PCveeC4pFgamO7TD9ZPlmEFwY07JWbFl-mY0JH6xYAYWcYeV7VBMOwEKKyR-k2ouR6HX8oYwGvoRjE5N2-151hsJG74XzcChYmFukwWnuWx12t3-jlW2u2sVePXHaccxV8TvhWZYCODPWbEMwTHHpGpO4S9IM50IRIm_kFQ8SeU4j_wgzMHWmxEy3FBKv7CkJpF2fFIbjYgV2nNS8e2wMjFda0dLEl9e2lbkhPbMsWk-NnYpSRwXX4TLidL7Xmg61U5vNzKGJqvp9F74s90Pdjg5dyCUOaRTnsuxa4ckJ1PHswPP3cOPDyyJKYgcB6otE22XBMSfm6H9yZxE2d50YLu5otQyXbPiBRlyQCk7xIcCDnMx9IjlQc3n1ZGTs2mPSHbKXH7EDHmt2c-PWi8rXW7B-xnUBajLRtnzIicjZbjFHiSiJLIqWW4hCidRXbpbjZKCk4XNPVpIP1vHyrl20dnRrVLkRpIiiaomJwL4ZBXYlum0zKU9jaaAnH3zjbg7YhQlecKMJ6ELuJD …
```

Color mastery differences blue when comparing trees

---

src/Modules/ConfigOptions.lua

Fixes #8128 .
"# of warcries used recently" is not shown in all configurations.
Path of Building should atleast give the option when the character has warcries skill gems at the very least
- Add any warcry gem.
- Check configuration tab.

Fix warcry options are not shown in all configurations.

---

src/Classes/TreeTab.lua

Fixes #8170
When removing all tattoos, we were passing the hashOverride node to the RemoveTattooFromNode function and this was changing the actual tattoo data instead of resetting the tree node.
- Add a tattoo
- Remove All Tattoos
- Verify tattoo is still in list
"Tattoo of the Kitava Blood Drinker" in before/after

Fix Tattoos being removed from list when using Remove All Tattoos button

---

src/Data/Rares.lua
src/Data/Uniques/jewel.lua

Perandus pact was given the wrong base due to a copy/paste error, and the other 2 rare templates have old bases that have been removed (I set them to what the std bases were converted to)
I think the rare templates likely need an overhaul with the new top bases added, but leaving that for a separate PR

Fix broken base types on some items

---

src/Data/ModCache.lua
src/Modules/CalcPerform.lua
src/Modules/ModParser.lua

Fixes #8063
This creates a copy of any mods that have melee weapon flag, with the ranged weapon flag instead of the melee weapon flag

Enable Tincture Effects to also apply to Ranged Weapons

---

src/Modules/CalcDefence.lua

Fixes #7955 .
With negative unreserved life your life recoverable was negative, and thus EHP and Maximum Hit Taken made no sense (if you didnt have other pool to cancel it out), this caps life recoverable to have a minimum value of 1 (the minimum possible ingame) so that it doesnt break sorting or sidebar values, this still warns the user to fix their life reserved and life costs

Fix EHP and Maximum Hit taken with negative Unreserved Life

---

src/Classes/ImportTab.lua

Old code removed all spaces, regardless of position or realm type.
New code:
PC:  Remove all spaces from account name
Console:  Trim any leading/trailing space, encode any that remain for URL ("+").

Handle account name spaces in import

---

src/Data/ModCache.lua
src/Data/ModMap.lua
src/Modules/CalcDefence.lua
src/Modules/ModParser.lua

Built ontop of #6809, merge that one first
Only the last commit is unique at the moment
adds support for enemy damaging ailments, either if the enemy has a chance to apply them or above a certain critical strike threshold, this is just so that it doesnt always show the enemy as being able to ignite you
This also correctly scales with unaffected by/immune to, and also will not apply if the duration is 0, but applies regardless of chance if the chance is greater than 0

Enemy damaging ailments

---

src/Classes/PartyTab.lua
src/Modules/CalcPerform.lua

This adds support for exporting and importing warcry buffs to the Party Tab, if the user uses a warcry it will overwrite any buffs from the party tab of the same warcry, (rather than taking the strongest, this is the functionality of a few things like curses) this can be changed in the future (to be more like auras)
This doesnt export/import rallying cry properly atm, I believe I would need to change how we handle it and want to split it into a separate PR as it has a few issues

Add support for export and importing warcry buffs to the Party Tab

---

src/Classes/ListControl.lua
src/Classes/MinionListControl.lua
src/Classes/MinionSearchListControl.lua
src/Modules/Build.lua

Fixes #8054 .
> The list of added spectres is long and continues to grow; it can be tedious and time consuming to find the particular one you wish to use in your build.
Now you can search the list of available spectres by name or by skill. Default is to only search by name, but in a dropdown menu you can choose to search by skill or even name and skill.
Search for skills is just an added bonus i found neat.
The search field only filters the list of available spectres(on the right), not the list of spectres added to the build (on the left).
todo:
- add ctrl + F shortcut to be in line with all other search bars
- open spectre library and search a few different spectre
```
eNqtW1t32roSfm5_hRfvDXeadpHuRSBpslbScCBpz3nqErYA7coWW5aTsH_9GV1sDEGOjJ2H1lgz31ykGWnG9vCv15B6z5jHhEUXjfZZq-HhyGcBiVYXjafH6 …
```

Add ability to search in the spectre library

---

src/Data/Skills/act_str.lua
src/Export/Skills/act_str.txt

The mod was applying a generic DamageTaken instead of just applying to hits
Fixes #8139

Fix Sand Stance "less damage taken" incorrectly applying to DoT

---

src/Modules/CalcOffence.lua
src/Modules/ModParser.lua

Hateforge was counting skill gem multipliers in the rage cost calculation when it only cares about the soul cost of the skill
GGG also changed the wording on the mod so it broke the parsing
Fixes #8143

Fix Hateforge Rage cost calculation

---

src/Data/Skills/act_int.lua
src/Export/Skills/act_int.txt

Allocating Blood Magic removes the output of `ManaUnreserved` so it crashed the preDamageFunc
Fixes #8144

Fix crash when allocating Blood Magic with Manabond

---

src/Modules/ModParser.lua

The Implicit from Synthesis doesn't currently get parsed

Fix Damage while Leeching Life mod not working

---

src/Modules/CalcTriggers.lua

Improves the breakdown for snipe's damage mods by making the parser add the per stage damage note.

Improve breakdown for snipe's damage mods

---

src/Modules/ModParser.lua

Fixes #8194
Snipe's skillid appears to have changed at some point causing the mod to no longer function correctly.
Note that this pr requires regeneration of modcache to function.
- Test snipe as standalone skill
- Test snipe as support

Fix Snipe for Assailum not working

---

src/Data/Uniques/boots.lua
src/Modules/ConfigOptions.lua

Using the Embrace Madness skill grants you 4 unique debuffs that accumulate up to 10 stacks.
We were also missing  1 explicit mod on each variant of the boots

Add support for Debuffs granted by Glorious Madness

---

src/Modules/CalcPerform.lua

While looking at 8266 I realized we can skip the combustion check unless the enemy is ignited in the first place, this has negligible performance improvement, but might aswell do it
Also fixing the minor change with party tab buff exports I saw a while ago but didnt have a good excuse to make a PR to fix

Minor code changes

---

src/Classes/ItemsTab.lua

This fixes eldritch mods to replace the same type of mod (eg eater replaces any old eater mods, exarch replaces old exarch mods)
This worked at some point but now doesnt.
This does not make eldritch mods replace non-eldritch mods, we could easily implement that if maintainer wants it.

Fix Eldritch Implicit Mod Replacement

---

src/Modules/ConfigOptions.lua

Changes the default to pinnacle boss, this has long been requested and is the setting most people like to compare to, this also makes it easier for newer players to compare builds. Especially for EHP (as it does all damage types, and a reasonable amount, not just a small amount of phys)
The downside is that not everyone will understand this setting and this will cause issues for newer players during the campain not understanding why their defenses are so bad (becouse the bosses level is set to 84)

Change default Boss Config from None to Pinnacle

---

src/Classes/Item.lua
src/Classes/ItemsTab.lua
src/Data/ModCache.lua
src/Modules/ModParser.lua

This shows up on heist jewellery to prevent you from removing the downside modifiers on the implicits, this doesnt prevent you from removing them completely (eg via editing raw), but does prevent you from changing them by accident, eg via corrupts

Add support for Items Implicits Cannot Be Changed

---

spec/System/TestTriggers_spec.lua
src/Data/Skills/other.lua
src/Export/Skills/other.txt
src/Modules/CalcTriggers.lua
src/Modules/ModParser.lua

Implements the `Trigger a Socketed Fire Spell on Hit, with a 0.25 second Cooldown` settlers enchant.

Implement settlers trigger enchant

---

src/Classes/ItemsTab.lua

Mana flasks unlike life flasks always show both instant and non instant recovery lines even when the recovery is 0. This pr adds a zero check to make the description work just like for life flasks.

Hide recovery information if recovery is 0 on mana flasks

---

src/Modules/Main.lua

Fixes #7523
If a crash occurs during the loading of a build opened through the `pob://` protocol the mode element in settings.xml is corrupted causing a crash upon restarting POB.
This pr attempts to prevent mangling of settings.xml by validating the mode before saving.

Validate mode before saving settings

---

src/Modules/CalcOffence.lua
src/Modules/CalcTriggers.lua

Fixes #8228
Fix `ManaCostRaw` not being set to 0 when mana cost is converted to life cost fully. Adds a breakdown line to inform the user that the source skill has no mana cost.

Mana cost raw not being set to 0 when using lifetap

---

src/Classes/Item.lua
src/Modules/ModParser.lua

Fixes #8220
I didnt bother looking into this before because I assumed it scaled the mods themselves (the same way heist enchants do), turns out it doesnt, so easy to support

Adds parsing for local elemental inc damage

---

src/Modules/ConfigOptions.lua

Fixes #8216 .
The "# of Warcries Used Recently" option (to configure the damage that Admonisher should give) has disappeared and is appearing in red (saying it's invalid) when importing characters that had already checked it.
- Path to the Admonisher Notable
- Check the Configurations tab to input the number of warcries used recently
Minimal:
```
eNqtW1132jgTvm5_hQ_XacAffO0h3UNC0mTfpGFD2u5e9QhbgFohUVtOwv76dyTZxqHIsbF7kYI1z3xJM5oZYPTny5paTziMCGdnLfu007Iw83lA2PKs9eXx6sOg9efH96MpEqv7xXlMqFz5-P7dSL22KH7CFHBuyxIoXGLxNWXlfgdWG8TECnN2h37w8BMPzlqfOcMta45YQET6zqcoij6jNT5rzXwAtywU-ZgFF7vnCeEKhcgXOLyVYsex4Hc8gFURxrC6RoTNuP8Ti08hjzegVct6IvhZ09zcTe8fHnMqEZZXCUx6N5pStMXhTCBhRfDnrDUGz6AlnqA1_AVuiMbAqnPa9wbd_sAeDjtdB2xvF6LP4zASR7KYbTAOMpR96pgIpyG-XCywL8gTvgiJuFgh5ufkmXBVae9iKsiGEhzmtOqaENe_Me8PTLSPXCA6mc5 …
```

Fix "# of warcries used recently" configuration option unavailable.

---

src/Data/ModCache.lua
src/Modules/CalcOffence.lua
src/Modules/ModParser.lua

Adds support for the following mods:
Gain Arcane Surge after Spending a total of 200 Life
Adds 5% of your Maximum Energy Shield as Cold Damage to Attacks with this Weapon
Adds 5% of your Maximum Mana as Fire Damage to Attacks with this Weapon
Damage cannot be Reflected
Mana Leech from Hits with this Weapon is Instant
Chaos Damage with Hits is Lucky
(7-10)% increased Fire Damage per 1% Fire Resistance above 75%
Mods that still need support:
Haunted by Tormented Spirits
Trigger a Socketed Fire Spell on Hit, with a 0.25 second Cooldown -- Handled in another PR
Gain Flaming, Icy or Crackling Runesurge at random for 4 seconds every 10 seconds
Gain a random shrine buff every 10 seconds
Fixes #8213

Add Support for many Runecraft Enchants

---

src/Classes/TreeTab.lua

Adding multiple Tattoos is a pain when you have to re-enter the name of the Tattoo every time you are trying to add another copy of it
This changes the behaviour so that the last Tattoo that you added to your tree will now be the one that is shown as the default selection when opening the UI. The index is stored per node type so the index from Dex does not interfere with the index from Str

Default to last added Tattoo in Tattoo popup

---

src/Classes/PartyTab.lua

Fixes #8060
Sorry for now seeing this when the issue was made, this now checks if a skill is a valid skill, if not it replaces it with the name of the aura applying it if valid, otherwise replaces it with a text source to prevent crashes (note this makes source show up as empty instead of crashing, eg malformed purity of lightning)
This shouldnt be an issue for any current exports but is for older exports, and likely will be an issue in future (also helps with user edits xmls)

Fix invalid skill ids in party tab source

---

src/Classes/TradeQueryGenerator.lua

Fixes #8127 .
Added feature to exclude mirrored items from trade query.
- Go to "Items"
- Click "Trade for these items"
- Try the checkbox "Mirrored items"

Added ignore mirrored items checkbox to trade query options.

---

src/Data/ModCache.lua
src/Modules/ModParser.lua

Fixes #8276 .
makes the config option show up if your dual wielding, does not check block, as its up to the user to check the box anyway

Fix Dual Wielding Mastery "Elusive on block" not enabling Elusive config

---

src/Data/Spectres.lua
src/Export/Minions/Spectres.txt

Quite a few of the corpse spectres has their buff mods updated or removed. These mods are manually added so needed to be manually updated if GGG changes them

Update Affliction Spectre Buffs with 3.25 Changes

---

src/Classes/ModDB.lua

Fix overrides 0 showing up when eval mod fails
(these 3)
This is likely caused by https://github.com/PathOfBuildingCommunity/PathOfBuilding/commit/8fe92a53602489e67d6584789dd4380b193539ee where it was copied from `SumInternal` and should not have been an "or 0" case

Fix Cooldown breakdown showing overrides for other skills (eg flicker)

---

src/Modules/ConfigOptions.lua

Change config types to `count allow zero`, this allows enemy armour/evasion to be set to 0 (instead of minimum 1), and prevents you from setting enemy block, damage and pen to negative numbers

Allow zero enemy armour in config and fix negative enemy damage

---

src/Modules/CalcActiveSkill.lua

Fixes both current (and all future) `SkillType.DualWieldRequiresDifferentTypes` from being usable if you have two of the same weapon type.

Fix Dual Strike of Ambidexterity and Cleave of Rage

---

src/Data/Uniques/helmet.lua

Im not sure how this got there:
Nearby Enemies cannot deal Critical Strikes
The item does not have that line:

Remove non-existant stat from Cadigan's Crown

---

src/Modules/CalcPerform.lua

Fixes #8208 .
This just doesnt automatically count you as leeching if you have both, all the other interactions still work, and lets you use config to count as leeching

fix Ghost Reaver and Brutal Fervour Interaction

---

src/Classes/Item.lua

Currently some item mods are parsed incorrectly if the user tries to paste an item into PoB after using <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>c</kbd> (Advanced Item Description).
This PR adds an error popup to inform the user of the incompatibility, and provides a remedy.

Add Ctrl+Alt+c error popup

---

src/Modules/Build.lua

PoB doesn't currently take into account the experience penalty for levels 95-99 that GGG applied in [patch 3.1](https://www.pathofexile.com/forum/view-thread/2035872) and the experience multipliers shown in PoB are higher than they should be when you hover the level at top center of the window.
I initially was going to follow the formula shown on [poewiki.net](https://www.poewiki.net/wiki/Experience#Experience_penalties)  `1/(1+[number from patch notes])`. However after reading a couple of reddit posts ([reddit post 1](https://www.reddit.com/r/pathofexile/comments/ypswyu/about_experience_penalty_31_and_experience/), [reddit post 2](https://www.reddit.com/r/pathofexile/comments/8jqm2o/experience_multiplier_changes_from_310/)) of people experiencing less experience gained than you would …

Fix 3.1 xp multiplier calc for levels 95-99

---

src/Classes/TradeQuery.lua

Fixes crash when resetting stat weight multipliers with no previous selection

Fix Trade Query Stat Weight Crash

---

src/Classes/PartyTab.lua

This is mostly an issue when importing a support character with no warcries not clearing warcries if import with no "append" and so the warcry buffs still persist

Fix party tab warcries clearing links instead of warcries

---

src/Modules/ModTools.lua

Party tab is currently the only thing using mod tools to parse strings directly into mod tags, its not automatically turning them into numbers, this is fine in most cases, but the modstore doesnt turn thresholds into numbers and so causes a crash
I made it use a lookup array, this is slower, but makes it easier to add others in future if other tags also need to be numbers and not strings

Fix PartyTab Crash with thresholds

---

src/Classes/Item.lua
src/Classes/ItemsTab.lua

* fixes bricking issues from user-edited item description text
* error popup with early return changed to warning
* ~~only shows once per session~~

Fix Advanced Item Description error popup problems

---

src/Classes/Item.lua

This fixed items such as `Wraithlord` and `Replica Shroud of the Lightless` still having 1 non-abyss socket
Before
After

Fix abyss socket items with no selectableSocketCount (eg Wraithlord)

---

src/Modules/ConfigOptions.lua

Fixes #7870 .
Implement Enemy Damage Type defaulting to "Average" after user swaps off of a Boss Skill Preset other than None.
When users set "Boss Skill Preset" to a boss specific skill, returning to "None" would leave "Enemy Damage Type" as the type associated with that boss. This changes reverts "Enemy Damage Type" to "Average" when the user switches back to "None" from a "Boss Skill Preset" other than "None".
- Gathered stats for test build in several settings before change.
- Gathered stats for test build in several settings post change.
- Compared before/after stats to confirm that settings were being applied correctly, both manually and automatically.
https://pobb.in/kYuRwhP1-Sm0
https://poe.ninja/builds/settlersssf/character/LPBird/Lotus_KANYQR?type=exp&i=0
Boss Skill Preset/Enemy …

Default "Enemy Damage Type" to "Average"

---

src/Modules/CalcDefence.lua

I was seeing strange breakpoints in my EHP. Normally, increasing my spell block chance by 1% would increase my EHP by <1%, but at certain breakpoints, a 1% spell block increase would cause an 8.8% EHP increase.
Checking the breakdown, I saw that my "mitigated hits" went from 5.99 to 6.52 at this spurious breakpoint.
Examining the function `numberOfHitsToDie`, specifically the part that adds back overkill as a fractional number of hits, I found the reason for this. The correction it performs is:
```
numHits = numHits + poolTable.Life / damageTotal
```
where `poolTable.Life` is the negative amount of life after the overkill, and `damageTotal` is the total damage of the last hit.
However, my character has 50% MoM and significantly more mana than life. Therefore, on the overkill hit, 50% of …

Improve EHP overkill approximation, especially for MoM

---

src/Modules/CalcSetup.lua

Fixes #8302.
Properly set hollow palm to dual wield, rather than just setting the condition, that means mods which apply to the main/off hand will give their proper results, rather than potentially being over inflated or not counted at all, 
This also fixes `Ice Crash of Cadence`, but thats likely not intended based on the skill description.
This is a little messy, but its because keystones are not merged until calc perform, and so the best I can do is check for the keystone name, this only runs if the weapon 2 slot is empty, and you are unencumbered (no weapon 1/weapon2/gloves)

Hollow Palm Technique proper Dual Wielding

---

src/Classes/ImportTab.lua

The new PoE patch requires accounts to also have a discriminator, this automatically url encodes them, including the "real account name" retrieved from the website, allowing characters to be imported again.
This saves the account name with the un-encoded value into the list, ~~but currently selects the wrong index from the list~~ edit: fixed that, was an old issue, we sorted the account order after selecting, so it would always have the last value selected.
fixes  #8359 and #8360

Fix import with discriminators

---

src/Classes/ImportTab.lua

Warden was missing from the list as its "new" and so the colour would be `nil`
I would prefer to do somthing like `classColor = colorCodes[charClass:upper()] or (main.tree[latestTreeVersion].ascendNameMap[charClass] and colorCodes[main.tree[latestTreeVersion].ascendNameMap[charClass].class.name:upper()]) or colorCodes.DEFAULT`
instead of the if statements, but the `ascendNameMap` uses the ID not the name, and so raider is the valid class that maps to warden, and requires more extensive changes to work

Fix Warden Import Colour

---

src/Modules/Build.lua

Fixes #8351
Makes loadout matching logic use plain text pattern finding to allow use of reserved characters in set names.

Fix special characters in set name causing crash

---

src/Modules/CalcPerform.lua

Fixes #8288  .
With KEYSTONE: Necromantic Aegis noded and equipment / effects that check for empty offhand, Shields in the offhand slot [Weapon 2] will always be considered empty handed during calculations.
-Load build that both allocates Necromantic Aegis, and has any shield with mods that affect player with any source that checks for an empty offhand; White Wind, Imperial Skean used in this case.
-Check Calculations for presence of White Wind Inc when shield is equiped and unequiped on any non-complex cold damage skill.
-Check Calculations for presence of White Wind Inc when shield is equiped and unequiped with no skill group active to see Minion Hit average changes.
NOTE: Freezing Pulse is set to level 1 and 0 quality for testing. Default settings applied on config section. …

Fixed Off hand detection regarding Necromantic Aegis

---

src/Data/Skills/act_str.lua
src/Export/Skills/act_str.txt
src/Modules/CalcOffence.lua

Calculations fixed, mod inc display edge case issue.
Fixes #8261  .
Calculations of Herald of Ash pulled from all sources of Fire damage over time increases, including but not limited to Global Fire damage increases when not supposed to.
- Testing with two equipments granting 10% Global Fire Damage and 70% Burning Damage increases and calculated with 40 overkill damage. 
- Manual Calculations to confirm number matches changes.
- Only Issue Remains as Inc mods are not filtered. Should open a new issue with this edge case as it far exceeds scope of current issue.
https://pobb.in/vwANN9PgixQd

Fix Herald of Ash overkill damage incorrectly scaling with global damage increases

---

spec/System/TestDefence_spec.lua
spec/System/TestSkills_spec.lua

Due to #8271 changing the default boss preset many tests that relied on enemy stats broke. This pr fixes that by changing the boss configuration back to "None" for affected tests.
Additionally this pr adds an extra test for scorching ray exposure when using the automatic maximum sustainable stages mode.

Fix broken tests after changing default boss preset

---

src/Modules/Build.lua
src/Modules/Calcs.lua

Fixes #8319
The warning calculations did not consdier the case of a skill having both reservation and mana costs. Mana cost would be checked after applying reservation and not before causing the warning to show up in some cases.
This pr adds a check and handling for such cases, as well as using the warnings from output to determine color override for cost labels instead of re-checking pool availability.
```
eNq1W1132jgTvm5_hQ_3DQECTXtI9xAgTc4hDS-k7b5XPcIWoK0ssZachP31q5FsYwhyZOzNRWvQPPMlzWg0Mv0_XkLqPeFIEM6uGq2z84aHmc8DwlZXje-PNx8uG398ed-fIrl-WF7HhMLIl_fv-vrZo_gJU4VreBJFKyx_pJw6vxSnDWJyjTm7R3_x6CsPrhrfOMMNb4FYQGT6yadIiG8oxFeNua_ADQ8JH7NguPs-IVyjCPkSRxOQOoglv-eBGl0iKtRwiAibc_83ll8jHm-0Vk8EPxuiu_vpw-wxpxNheZ2USe_6U4q2OJpLJD2h_rlqDJRn0ArfEqlYIRorPueNZiHtdRwJOUKhenwbM99gHGRkbRvZNMLj5RL7kjzhYUTkc …
```

Fix blasphemy auras triggering mana cost warning

---

src/Modules/CalcSetup.lua

Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/8250
When filtering out mods of type `SocketedIn` the logic modified the table causing the iterator to get out of sync and skip mods.
This pr additionally fixes an issue where Kalandra's touch was not taking item overrides into consideration showing stat difference only for the copied ring.
```
eNrtXW1z2siy_hz_ChVVe7-E2NLoPdfeU9hgm6ztEMBxki-pQRpAtpCIXuyQrf3vt3skQGAkJMPWrZzyqS0HSf02z_T09Ix6dI7_83PiCo8sCB3fO6lJh2JNYJ7l2443Oqnd9s_fGbX__Hlw3KHR-OPwNHZcfPLnwZtj_ltw2SNzgU8EvogGIxZ9nsuSv8O9KfWiMfO9a3rvBxe-fVK78T1WEwbUs51ofmW5NAxv6ISd1Joxc50wqgk0tJhnny2f9Fw6YwEQj2lArYgFV6i7EUf-tW_D8yF1Q5A1oY7X860HFl0EfjwF22rCo8OeEqL2dedjt5-xy_GydkHD3hx3uKJeRCMhhD8ntQbgQ0esSSfwF6RRNwZRkn6o61rtqJDnNA7CqBJjb8qYvaQ9VCWSR9oJWGs4ZFbkPLKzwInOxtSzlnrEP …
```

Fix kalandra's touch skipping mods

---

src/Data/Skills/sup_dex.lua
src/Export/Skills/sup_dex.txt

Fixes #8259  .
The global Rupture debuff was not previously not assigned an effect name. Because of that, multiple instances were allowed to apply, as they had different active skills as their source.
I just assigned an effect name, which caused the standard mergeBuff / match functions to be able to properly identify duplicates and only apply the highest values instead. 
- Checked number of applied stacks, effect on duration and damage for correctness
- Checked that different magnitudes from support gem level work correctly
- Checked that behavior is consistent across different skills
https://pobb.in/70IX7nLOCxOZ

Fix Rupture sometimes applying multiple times

---

src/Classes/ImportTab.lua

This adds another line to the character list retrieval failing to warn about possibly missing a discriminator.
This can actually be detected and so can have its own error / help text, but that requires extra logic, and this should be good enough for now to help ease people into the new account system.

Add discriminator check to account import

---

src/Classes/ImportTab.lua
src/Modules/Common.lua

Fixes #8369.
Accounts with dashes in them (e.g. `Dj-Reck1#9507`) could not be imported.
Those accounts are possible because dashes are allowed in account names for consoles.
- Import `Dj-Reck1#9507`
- Import `Dj-Reck1-9507`
- Import `Tarekis#5639`
- Import `Tarekis-5639`
Hope code looks good to yall. Not a lua dev lol

fix: allow account names with dashed in them to be imported correctly

---

src/Classes/ImportTab.lua

Lua patterns dont support `alternations`, and the capture group I used doesnt "group" the things together within a `[ ]` unlike normal, so this removes the functionality, we can support it in future, but it was deemed as not a worthwhile usecase
This also fixes an issue with the `sessionID` on line 426 if `-` was used instead of `#`, due to account name being changed after and saved with `#`.

Remove url encoding check, as it was broken

---

.github/workflows/builddocker.yml
.github/workflows/test.yml
Dockerfile
docker-compose.yml

Implements a docker container with specific versions of tools needed to run tests. Updates current tests workflow to use it fixing luajit missing issue.
Lines containing references to `ghcr.io/paliak/pathofbuilding-tests:latest` will need to be updated after an image is published under POB org.

Implement a docker container for tests

---

CONTRIBUTING.md

amended:  fix trailing quote typo, add blank line before first example

improve "set up the exporter" tutorial

---

src/Data/Uniques/gloves.lua

Fixes #8388.
Breathstealer's unique modifier is not correct.
- Check out Breathstealer unique modifiers.

Fix Breathstealer's unique modifier

---

src/Modules/CalcSetup.lua
src/Modules/Calcs.lua

Fixes #8389
Environment overrides needed to correctly handle recursive trigger rate calculations were being lost in `calcs.calcFullDPS` causing a crash. This pr causes overrides to be saved unconditionally in `calcs.initEnv` fixing the issue.
See issue

Fix crash caused by lack of envirement override propagation

---

src/Launch.lua

Lua side code for https://github.com/PathOfBuildingCommunity/PathOfBuilding-SimpleGraphic/pull/65
Changes the hotkey from just (print screen) to (control + print screen) in an attempt to prevent potential conflicts with other screen capture programs.

Implement lua side hotkey for screenshots

---

.github/workflows/update-simple-graphic.yml

While not a hard task, downloading the SimpleGraphic artifacts and manually pushing them to each PoB repo is just one more thing that can be automated off of a release task list and ensures it's not forgotten.
https://github.com/PathOfBuildingCommunity/PathOfBuilding-SimpleGraphic/pull/69 notifies this action when the artifacts have been uploaded to the release and creates a PR in this repo updating the DLLs.

Automate creating PR for SimpleGraphic releases

---

.github/ISSUE_TEMPLATE/accuracy_bug_report.yaml
.github/ISSUE_TEMPLATE/application_bug_report.yaml
.github/ISSUE_TEMPLATE/behaviour_bug_report.yaml
.github/ISSUE_TEMPLATE/calculation_bug_report.yaml
.github/ISSUE_TEMPLATE/crash_report.yaml
.github/ISSUE_TEMPLATE/feature_request.yaml

Clarify which PoB edition this is for, and that we need a build code from PoB.

update issue templates

---

src/Data/Uniques/flask.lua

Fixes #8418 .
Cinderswallow Urn mod missing in current version: `Enemies Ignited by you during Effect take (7-10)% increased Damage`
- Check Cinderswallow Urn mods list.

Fixes Cinderswallow Urn mod missing in current version.

---

src/Modules/CalcDefence.lua

Fixes interaction between Block Replacement effect granted from Gladiator's "Determined Survivor" ascendency with Necromantic Aegis. 
Now grants minion base 50% block chance given from Determined Survivor and Ascendant's Gladiator Ascendency.
Fixes #8358  .
While allocating Determined Survivor or Gladiator Ascendancy, it did not grant minions the replaced 50% block chance when Necromantic Aegis is allocated.
- Create both Duelist and Scion with said ascendancies allocated and have any base block shield equiped. 
- Set active skill to Summon Zombie or any summon, set calc mode to view minion
- See if active block chance is 50% rather than base shield block chance.
Duelist: https://pobb.in/PweoXCGVDI6_
Scion: https://pobb.in/5apC4rtoIUyg

Fixed interaction between block replacement effect from Determined Survivor and Necromantic Aegis

---

src/Modules/CalcOffence.lua

Fixed an issue where Critical Hits were not displaying the Critical Mastery Node increasing non-damaging ailment effect mod to critically strike enemies.
Fixes #8321  .
Crit Mastery which increases non-damaging ailment effect modifiers did not add to the calculation menu when in crit-only mode.
- Enforce build with guaranteed crit and guaranteed ailment infliction chances.
- Node Critical Mastery which increases non-damaging ailments by 50%
- See if Calc page increase from x 1.0 to x 1.5
https://pobb.in/zGdTRuRn7dWh

Fixed Non-Damaging Ailment issue with Critical Mastery in Calc Screen

---

src/Modules/CalcDefence.lua

Disables "gain when hit" (eg gain on block) regardless of config, if the build cannot survive a hit from the enemy.
Not the biggest fan of this solution, as it causes a huge spike in EHP for certain builds once they cross that threshold, there is also debate if this number should be higher to incentivise people to get higher max hit, or even if we should add a ramping function to the amount of gain on block depending on how likely they are to survive, eg if they can survive a normal hit but not a crit, only apply 70% gain on block, and if they can also survive a crit then apply 100%, and between those do a ramp function.
Out of 100 builds I have looked at for this, it applies to 6 anyway (vs guardian boss config).

Disable "gain when hit" for builds which cannot survive unlucky hits

---

src/Modules/ModParser.lua

+25 virulence from the herald ascendancy for example

Fix maximum virulence parsing for multi digit increases

---

spec/System/TestDefence_spec.lua
src/Modules/CalcDefence.lua

Back port of https://github.com/PathOfBuildingCommunity/PathOfBuilding-PoE2/pull/694

Fix ES bypass regression

---

src/Data/ModCache.lua
src/Modules/ConfigOptions.lua
src/Modules/ModParser.lua

Closes #8421
This pr adds a checkbox in the config section which defaults to on. This way the current behavior is maintained while allowing the user to disable it if they wish.
```
eNqtHGtv2zjyc_0rCAN7aHGX2JLtJM0lu3BeTYCk9dpJe3dfCkaibW5p0ZWopN7F_vebISVZdk1ZstwFWkmc93CGMyN5z377MRPkhYURl8F50zlsNwkLPOnzYHLefHq8OThp_vZr42xA1fTT-CLmAld-bbw509dEsBcmAK9JFA0nTH1OKXW-AqU5DdSUyeCB_iHDD9I_b36UAWuSZxr4XKV3nqBR9JHO2Hlz5AFyk9DIY4F_uXyeAE5pSD3Fwnvk2o-VfJA-rKowhtUZ5cFIet-Y-hDKeK6FeuHs1cDcPQw-DR9zIvEgLxJo9OZsIOiChSNFFYngr_NmHwxDJ-yWKyBFRQx0jtvu4YnT7bjNViHORRxG6orO4LI87mjOmJ-BO4dd96R37CR_25AGIbsej5mn-Au7DLm6nNLAWzI9suFVhX2IheJzwVmYk7Bnw7j9ibjTbtuAH6Wi4mowysN2D9tuu6vVf1-MJ5fesXL4wtX0QoB1d-CCuHeTgCu2I_JA8kgGNfTLo1pVvIyFgNgsBTtkEQtfqOKrYtlpy9kzD3ay3gMN6KWMlj5yO0WgAxZC7KsVjPYWhBHzJKSLPEoHIm0ZOmU4bqZjZX3Px6w8ZCW …
```

Add checkbox for Sacrificial Zeal

---

src/Classes/DropDownControl.lua

Closes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/8486
Character names are currently drawn over the top of the details on the right of the dropdown. If a name happens to be very long (often happens when using tofu for utf-8) the details stop being legible. This adds a black background behind the detail text to make it more readable.
- Tested by importing pjsdevil#2432 account and previewing characters from Necro Settlers league
- Make sure the mouse over hlighlight works correctly

Add black background to detail text in character dropdown

---

src/Modules/CalcDefence.lua

Closes #8488 
Closes #8475 
Infinite EHP was sometimes caused by floating point precision errors while calculating taking damage to life with life loss prevention.
A case of wrong max hit was caused by taking 0 damage to a bypassed pool (phys taken as chaos with CI)
A case of wrong max hit was caused by max hit approximation partially failing to account for life loss prevention.
https://pobb.in/DKadd4WhKVpp
https://pobb.in/6L8vQXyO3YWQ

Fix several bugs with infinite EHP and wrong phys max hit

---

src/Data/Skills/act_str.lua
src/Export/Skills/act_str.txt
src/Modules/ConfigOptions.lua

Fixes #8426
Molten Strike and it's transfigured version now have calculations for average ball overlap on single targets.
Zenith also has a weighted average of its normal and 5th attack balls to estimate overall ball dps.
- tested on various molten strike builds on poe.ninja and calculations compared to the online calculator
- correctly factors # projectiles, quality, and increased/reduced aoe and projectile speed
https://poe.ninja/builds/settlers/character/turdtwisterx%234882/NeedForSteveUnderground
overlap chance calcs
zenith weighted average for overall ball dps
I had do a bit of a workaround in making an effective multiplier instead of actually averaging the two final dps values for normal and 5th attack balls because afaik there's no way to know those values in the preDamageFunc. The …

Add Molten Strike (+Zenith) ball average overlap calculations

---

src/Modules/CalcActiveSkill.lua

Closes #8478
Some active skills such do not have a `srcInstance` property due to their non-gem origin. This would cause a nil deref when trying to use such as skill as a trigger source for Tawhoa's Chosen.
This pr adds an if check to handle this properly.

Fix Tawhoa's Chosen crash when no active skill is enabled

---

src/Classes/CalcBreakdownControl.lua
src/Classes/PassiveTree.lua
src/Modules/CalcSetup.lua

Fixes # .
Forbidden Flesh and Flame weren't actually allocating the right ascendancy nodes
- Equipped both jewels and saw the correct stats coming from the ascendancy
```bash
eNrtXWtz2ziW_dz-FSxXzdZ0lZOIL4nKOj0lvxL32InHcpLt_dIFS7DFMUWq-bDjnpr_vhfgQwAFCpABf5gt7lZNO-LFAXCIC-CCAM7h334sI-sRp1mYxB_27beDfQvHs2Qexvcf9r_enL0J9v_2y97hFcoXX-6OijAiT37Z--mQ_m1F-BFHH_YdSJaj9B7n32oo93f4bYXifIGT-BL9M0k_JvMP-5-TGO9btyieh3n9r1mEsuwzWuIP-9MFmidP-xbKZjieHzMPcPoIYFZyZ01S9IBQFELCBUrRLMfpBSnGpMiTy2QOxnlaAOwShfE0mT3g_GOaFCso5b71GOKn0ub88urL9Q1TxDBmiwhV_OnwKkLPOJ3mKLcy-J8P-xNgCt3jE7SE_wU0FBWY1P7tYDgeucPxcP_d1oRHRZrlu6eerjCeNwnct0EQdJlepfj07g7P8vARH6dhfrxA8YzJbNyVUGA8fusE28wviygPV1GI0yaJ_XbodyX5tJGB63TZ3iQ5ik6upo3pKHg7cG3bHbmDgRdsT5bkTbJBl-X3MF8cRUDr7pmQpOf3cZjj3dNeJWGWxGy6wH87tsfjgSdJwjcae2S_DdxxMNhays3cbHvw1h4Mf …
```

Fix Forbidden jewels not finding the right ascendancy nodes

---

src/Classes/TreeTab.lua
src/Modules/Build.lua

The alternate tree names made the tree version select too narrow to read, same with the new ascendancy names.

Dynamically expand some dropdowns that were too narrow to read

---

src/Data/Skills/act_str.lua
src/Export/Skills/act_str.txt
src/Modules/ModParser.lua

Fixes #5644 
Labyrinth helm enchant didn't work. I couldn't think of a way to grab the regen total from the totem other than the skill in act_str.lua. For what it is, probably doesn't matter. Helm enchants have been gone for a while now. It's hard coded to 15%, so if they do add a similar mod down the road, it won't accidentally be parsed through this stuff. So it'll be red text, and then we (aka someone smarter) can worry about doing a better job then.
EDIT: Also, the wording was changed at one point. So the issue linked has old wording, which I didn't bother supporting as it would only be relevant for older builds, which at that point they can just replace the old worded mod with the current enchant.
https://pobb.in/Aqrym-Kd-LaU

Add support for Rejuvenation Totem helm enchant

---

src/Modules/ConfigOptions.lua

Closes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/8541
Initially when trying to fix issue https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/8421 i made the config default enabled to maintain current behaviour of it being on the moment Hand of the Fervent was equipped. I was under the impression that the ifFlag would prevent the config application function from running but that doesn't not seem to be the case. I've tried a few different ways of fixing this but i've decided that the best course of action would be to simply make the effect opt in rather than opt out.

Change Sacrificial Zeal to be opt in rather than opt out

---

src/Modules/Data.lua

Fixes #8255 
Foxshade has 2 other "life" mods that shouldn't have the life tag. This excludes the life tag from those few lines, letting the life mastery properly apply. Note that I did not check the function in game myself, but poedb shows no life tags on the mods too.
https://pobb.in/yVpcJzFQ6LgQ

Fix Foxshade life modifiers preventing life mastery

---

src/Modules/CalcActiveSkill.lua
src/Modules/ModParser.lua

Closes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/8484
The 'Your Spells are disabled' mod found on the Gruthkul's Pelt unique chest armor currently prevents curse on hit mods from applying. This is due to the 'chance to Curse Enemies with X on Hit' being implemented in POB as a simple granted skill without making the distinction between generic granted skills and on hit (application) skills (curses). This solution isn't the prettiest but i'd argue it's the most sane given what information is available to the ModStore.
```
eNrtXFtv47YSfl7_CsJAD1p0E1uSb8lJWjhxbkCym9rZ3dOngpHoWCe06EpUErfofz8zpCTLjilLtvft7AKJLM43N5LD4ZDOya9vU05eWBj5IjitW4fNOmGBKzw_eDqtf3m4POjVf_2ldnJP5eTz-Cz2Obb8Uvtwop4JZy-MA65OJA2fmPyacnL-AE4zGsgJE8Ed_a8Ir4R3Wv8kAlYnjzTwfJl-cjmNok90yk7rIxfAdUIjlwXe-eJ9Qj …
```

Fix Gruthkul's Pelt disabling on hit curses

---

src/Classes/ImportTab.lua

When importing a character from Phrecia league, sometimes the ascendancy dropdown would be wrong and cluster jewel nodes would not be allocated
- Started on 3.25 tree
- Imported nikidino8#2454 -> Phrecia -> Manikio
- Saw ascendancy dropdowns properly updated
- Saw cluster jewel nodes filled in
N/A

Fix issues around importing to the wrong tree

---

src/Data/Skills/act_int.lua
src/Export/Skills/act_int.txt

Divine Ire of Disintegration doesn't do damage while channeling, so this PR removes that part from the skill.

Remove channeling part from Divine Ire of Disintegration

---

src/Modules/CalcDefence.lua

Ward is granted even with values above 100 but the conversion for Armour / Evasion on gear is capped at 100%
Fixes #8545

Fix Gain Ward instead of Armour/Evasion mod when total is above 100

---

src/Data/Skills/act_str.lua
src/Export/Skills/act_str.txt
src/Modules/CalcOffence.lua

Herald of Ash was previously scaling with area and spell damage mods which it shouldn't it was also possible for the increased damage values to be negative which is not correct.
Fixes #8538

Fix Herald of Ask damage showing negative values

---

src/Data/Skills/minion.lua
src/Export/Skills/minion.txt

Skill gems should scale the damage from the ground DoT but were not as we did not add any skill tags to the effect
Fixes #5790

Fix Minion supports not scaling Siegebreaker ground DoT

---

src/Data/ModCache.lua
src/Modules/CalcPerform.lua
src/Modules/ModParser.lua

The half strength mod is meant to stack when using both the ascendancy and the helmet
Fixes #8553

Fix The Baron and Rotting Might not stacking correctly

---

src/Data/ModCache.lua
src/Modules/ModParser.lua

+1 Projectiles to attacks when Ewar's Mirage is in off hand.
- Checked frost blades to make sure count goes up.
- Check Ethereal Knives to make sure count did NOT go up as it's a spell.
https://pobb.in/A1e_YHzaJJ3M

Add support for Ewar's Mirage +1 projectile when in off hand

---

src/Data/Skills/spectre.lua
src/Data/Spectres.lua
src/Export/Minions/Spectres.txt
src/Export/Skills/spectre.txt

Added Karui Backburner Spectre. Added custom skill to average out 3 hit combo
https://pobb.in/wew4xU4VnlSD

Add Karui Backburner Spectre

---

.github/workflows/backport.yml
.github/workflows/backport_receive.yml

This pair of workflows does two things:
- Accepts payloads from PathOfBuilding-PoE2 PRs that get merged with the `pob1` label
- Sends payloads to the PathOfBuilding-PoE2 repo when PRs get merged with the `pob2` label

Create workflows for porting changes

---

src/Export/Classes/GGPKSourceListControl.lua
src/Export/Main.lua

A crash would occur when creating a new datSource on a first-time install.  These couple of checks should fix that issue.

Fix missing datSource on new installs

---

src/Classes/Item.lua
src/Classes/ItemsTab.lua

Tinctures were interpreting the CDR mod as a global CDR mod when it's only meant to affect the cooldown of the Tincture itself
The local mod is also additive with the global mod on the tree and was mistakenly being treated as multiplicative with the way we were handling it
They also showed the tooltip for mana burn per second, but the number being shown was the seconds per mana burn. Fixed it to show the rate per second as intended

Fix Tincture CDR mod and Mana Burn rate display bug

---

src/Modules/CalcOffence.lua

Fixes #3074  .
In [CalcOffence.lua ](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/b19fb1472dc79e7b428ad9a3dae563a8c18c7dbf/src/Modules/CalcOffence.lua#L2442)the baseUptimeRatio gets multiplied by the stored uses (from Second wind e.g. and other sources):
globalOutput.IntimidatingUpTimeRatio = m_min(100, baseUptimeRatio * storedUses)
This behaviour is not reflected in the tooltip. I adjusted this for all the relevant war cries. (Intimidating, Battlemages, Infernal, Rallying, Ancestral, Seismic)
- checked in pob
https://pobb.in/2EN00DLD57kd

Adjusted war cry uptime tooltip

---

src/Data/Uniques/staff.lua

Fixes #8579 
The base type "Quarterstaff" for annihilating light was changed from 18% attack block to 22% spell block, but the current variant for the unique was using 22% attack block. Quick fix.

Fix many unique staves with Attack block instead of Spell block implicit

---

src/Data/Uniques/belt.lua

Fixes #8568.
Adds Shaper influence to Tides of Time
- Added Tides of Time from the unique item selection and verified it has Shaper influence by default
- Checked if it interacts correctly with Eternity Shroud's "gain as elemental" per shaper item
-
https://pobb.in/gMEVo5IIByfJ

Add Shaper influence to Tides of Time unique belt

---

src/Modules/Calcs.lua
src/Modules/ConfigOptions.lua

Closes #8564
The Dominating Blow skill has a similar issue to the Absolution skill where increasing count increases not only the "minion count" but also applies a multiplier on the base skill damage.
This commit essentially copies
https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/4653 and applies it to Dominating Blow.
```
eNrNXFtz4joSfp78ChfvA9jcU8k5RW6TbIUJC5mZ3acpYQvQGWExtpyEs7X_fVuSb4BlbOyHZaoSY_fX3eqWWt0tZ67-_NhQ4w17PmHudcNsthsGdm3mEHd13fj2-vB52Pjzj4urKeLrl-VNQKh48sfFpyt5bVD8hingGgZH3grz7xGnzk_gtEUuX2PmTtBfzPvCnOvGV-bihrFArkN49M2myPe_og2-bsxtADcM5NvYdW6T-yHhGnnI5th7FlLHAWcT5sBT7gXwdIOIO2f2L8y_eCzYSqXeCH5XNE-T6cvsNaUScdMqwYg-XU0p2mFvzhE3fPhx3RiDYdAKPxIOrBANgE-nM2h225bVa7RyMTeB5_M7tIHL4tj5FmMnJjebnfRHB5p6-H65xDYnb_jWI_x2jVw7EdrX4crSTgLKyZYS7KU01A7l8Yi52W7riF8ZR_RuOo9pu91Rc9 …
```

Fix Dominating Blow Hit counting multiple times when used in FullDPS

---

src/Modules/CalcTools.lua
src/Modules/ModParser.lua

Closes #8558
Parsing of the Gem-lined Cap Ascendancy Notable mod "+3 to Level on all non-Exceptional Support Gems" was incorrect due to faulty handling of the hyphen causing "non-exceptional" to be split into two keywords: "non" and "exceptional". This caused the mod to not apply as there does not exist a gem tag called "non". This commit fixes this by improving handling of non space characters in the keyword string and implementing handling for the negation part in "non-exceptional" inside of calcLib.gemIsType function.
```
eNq1W1932rgSf24_hQ_PaQBjG9hDuoeEpMk5oWEhbe996lFsAdrKFmvLSdhPf0eSbQxFxsa-fUjBmt_802g0GovRn-8-NV5xGBEWXLW6l52WgQOXeSRYXbW-Pd99GrT-_PxxNEN8_bS8jgkVI58_fhjJzwbFr5gCrmVwFK4w_55y6v0EThsU8DVmwRT9zcIvzLtqfWUBbhkvKPAIT7-5FEXRV-Tjq9YkxpREvGWgyMWBd7MbGYfwnLkhgkF3jULkchw-CunjmLMp8 …
```

Fix Gem-lined Cap Ascendancy Notable not applying

---

src/Data/Skills/other.lua

Fixes #8636
GGG buffed Death Aura in the 3.26 patch notes, increasing its base chaos damage over time. This PR updates the Path of Building implementation to reflect that change — raising the base damage from 1000 to 1250 chaos damage per second (i.e., from 60000 to 75000 per minute in internal values).
1. Modified src/Data/Skills/other.lua, changing:
```
constantStats = {
{ "base_chaos_damage_to_deal_per_minute", 60000 },
},
```
to:
```
constantStats = {
{ "base_chaos_damage_to_deal_per_minute", 75000 },
},
```
2. Launched local build of Path of Building.
3. Created a test build with Death's Oath to see Death Aura changes.
4. Verified that the Chaos Damage per Second reflected the new base value (1250).
5. Compared DPS in item tooltip and skill breakdown panel.
[Level 1 Death Aura …

Update Death Aura damage

---

src/Modules/CalcPerform.lua

One liner to update arcane surge cast speed modifier calculation ahead of 3.26 based on patch notes. Feel free to close if there's a convention of waiting until closer to the release to start making these changes! Just getting my feet wet confirming my dev environment was set up correctly 😄 
Evidence for change:
https://www.pathofexile.com/forum/view-thread/3787013
Validated minimal case by attaching arcane surge to a sample build and confirming cast rate is impacted appropriately.
Tests pass (although as far as I can tell no direct coverage for this mod? I can look into adding some if preferred)

Update Arcane Surge cast speed from 10% to 20%

---

src/Modules/ConfigOptions.lua

Closes #8657
https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/8625 forgot to update the config tooltip.

Update Arcane Surge tooltip

---

spec/System/TestDefence_spec.lua
src/Data/ModCache.lua
src/Modules/ModParser.lua

Increase flexibility in parsing for energy shield being increased by spell block on 3.26 Vile Bastion
The wording on the Ascendency Node is slightly different to what I expected (because I can't read patch notes, sorry for the quick double PR for this 😶‍🌫️)
- Validated with the same build as https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/8643#issue-3133398628 , and then a new build using the Occultist node as well
- Additional validation done by actually selecting the Vile Bastion node on the new tree, and confirming calcs work as expected.
- Added tests for both variants to ensure parsing is working as expected.
Confirmed the new ascendency node is also getting parsed correctly and calculations are impacted appropriately in preview/calcs breakdown

Improve flexibility in Vile Bastion keystone parsing for 3.26

---

src/UpdateCheck.lua

Occasionally, when downloading large updates for PoB, some files would fail.  This would cause the entire update process to have to start over.  This PR identifies files it had previously tried to download and failed that still exist in the Update folder.  If they match what was about to be downloaded, we don't have to download it again.  This means eventually retrying enough times might result in a successful download.
- Update from a super old version, downloading almost every file
- Observe some files failing and the download failing
- On the next attempt, observe files being skipped that were successfully downloaded

Resume failed update feature

---

src/Data/Skills/act_dex.lua

Fixes #8310.
EA max fuse calculation was getting double dip from action speed.
I don't think action speed affects fuse detonation speed or fuse duration.
https://pobb.in/Z23AeT76xtdf
In this extreme example, a `3.00 APS` bow with `100% increased action speed` should only be able to have `(6 + 1)` max fuse instead of 13.

Removed action speed calculation and breakdown display for Explosive Arrow

---

src/Classes/FolderListControl.lua
src/Modules/BuildList.lua

This PR introduces improved folder sorting capabilities:
Build List:
Folders are now sorted by modification time (newest first) when "Sort by Last Edited" is active.
For other sort modes (Name, Class, Level), folders are sorted by name (A-Z).
Files continue to sort based on the selected mode.
Folders are always listed before files.
Save As Dialog:
The folder list within the "Save As" dialog now inherits its sorting behavior from the main build list's current Sort by setting (main.buildSortMode).
If "Sort by Last Edited" is active in the main list, folders in the "Save As" dialog are sorted by modification time (newest first).
Otherwise, folders in the "Save As" dialog are sorted by name (A-Z).

Enable Sorting of folders by date and inherit the sort order in the build save dialog

---

spec/System/TestItemMods_spec.lua
src/Classes/ModStore.lua

Closes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/8664 and https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/2735#issuecomment-2969197233
https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/8652 attempted to fix a problem with globalLimits where ordering of tags in the mod table caused the limit to not apply by moving the limit check into ModStore. This caused the limit to apply only to "Multiplier" type mods that do not actually multiply the mod value. This pr fixes the issue by moving the limit check into a separate loop after applying mod tags.
Ideally, looping over the tags again wouldn't be needed if there was a good way to either move the global limit variables into the main mod body or ensure ordering of mod tags inside the mod table. …

Fix Nebulis and similar mods being treated as uncapped

---

spec/System/TestTriggers_spec.lua
src/Modules/CalcTriggers.lua

Closes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/8659
CWCHandler did not have handling for trigger bots. This PR adds that and fixes a minor breakdown issue in the defaultHandler (lines ended up in the wrong section of the breakdown).
- Check breakdown generation
- Check numbers using the build from issue
See issue

Fix CWC not supporting triggerbots

---

src/UpdateCheck.lua

Fixes #8667 
585a5ee1e105e7a1916fc033da609837206b28a1 implemented the ability to resume failed downloads.  In the process, it changed how scriptPath and runtimePath were assigned, going from "." to the following:
```lua
local currentDir = io.popen("cd"):read() or io.popen("pwd"):read() or "."
```
Unfortunately, io.popen briefly flashes a cmd prompt on Windows.  This is particularly bothersome when automatic update checks  randomly cause these windows to flash.  It took me a while to determine the source of these flashes, and I was concerned for some time that it might be malware.
This pull request changes UpdateCheck.lua to assign those path vars using GetScriptPath and GetRuntimePath, which are used elsewhere throughout the codebase.  In my testing, this was a suitable substitution.  It …

Fix flashing cmd window during update check

---

src/Modules/CalcMirages.lua
src/Modules/CalcOffence.lua

Closes #8693
https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/7369 caused issues with handling for `Uses Off Hand Weapon Attack Time` (UseOffhandAttackSpeed) due to missing offHand weapon calculation.
See issue.

Fix Dual Strike of Ambidexterity causing crash

---

src/Classes/SkillSetListControl.lua

Fixes #8726.
On saving a new Skill Set, the Rename/Copy/Delete buttons are still enabled, but no Skill Set selected. This selects the recently saved Skill Set from the list.

Fix Skill Set allowing editing a nil value after saving new Skill Set

---

src/Data/Skills/sup_int.lua
src/Export/Skills/sup_int.txt
src/Modules/CalcActiveSkill.lua
src/Modules/CalcOffence.lua

Fixes #7449, Fixes #4038
The Summon Phantasm support is meant to use the level of the Summon Phantasm gem to determine the level of the minion, not the level of the active skill which it is linked to
This also removes the minon flag from the support as it does not grant the minion tag to supported skills in game

Fix Summon Phantasm minion level incorrectly using the active gem level

---

src/Modules/CalcSections.lua

Fixes #8079 .
Currently there's no way to see warcries cast speed.
- Add warcry skill gem.
- Select it in 'Calcs'.
- Check 'Attack/Cast Rate' section

Fix Add 'Cast Time' to Calcs page for Warcries 

---

src/Modules/CalcPerform.lua

The calculation in CalcPerform was only taking into account the base stat for the mod which did not account for the more mod on the helm
It also didn't account for maximum number overrides which it now does

Fix The Dark Monarch not scaling "per summoned x" mods

---

src/Classes/ConfigSetListControl.lua
src/Classes/ItemSetListControl.lua

Fixes #8726.
Missed in the original #8738 PR
I missed the Config and Item set menus from the original issue. Oopsie.

Fix crash when trying to edit Config/Item Set after saving a new Set

---

src/Modules/CalcSetup.lua

Fixes #8760
The Runegraft mod only scales mods on items that come from stats, since socketed gem effects are properties of a GrantedEffect, they are not scaled by the bonus effect

Fix Runegraft bonus for Boots / Gloves scaling skill gems

---

src/Modules/CalcOffence.lua

Fixes #8137
Currently it seems the "Ailments never count as being from Critical Strikes" mod line found on the Elemental Overload keystone is implemented by simply never running the crit calculation pass when calculating ailments. This causes the ailment chance to still show up in the breakdown and cause issues with the Perfect Agony keystone which makes ailments only apply from crits.
Marking this as draft for now as this could really use a review by someone more familiar with ailment calculations.
```
eNq9XOtz4jgS_zz5K1xU7acjAT8wJpXsFnlNchsmHGRm7u7LlmIL8EZYjC0nw2zt_34tyS8YZGxM3c5WBqz-9UvdLanlzMVv35dEe8Nh5NPgsqWfdVsaDlzq-cH8svX5-e7Uaf3268nFGLHF0-wq9gkf-fXkw4X4rBH8hslly-i1NIbCOWZfUlbmH8BqhQK2wDQYoT9p-JF6l61PNMAt7QUFns_Sby5BUfQJLfFla-oCuKWhyMWBd50_TwgXKEQuw-EjFzuMGR1RD0ZniEQwvER-MKXuK2YfQxq …
```

Fix Elemental Overload not reducing Ailment chance to 0

---

src/Data/Skills/sup_int.lua
src/Export/Skills/sup_int.txt

The buff did not have the tag to let it apply to Totems
I don't know what this tag is even needed for tbh. It's a relic from Openarl 8 years ago

Fix Phantasmal Might not working when Summon Phantasm was linked to Spell Totem

---

src/Data/SkillStatMap.lua
src/Modules/ConfigOptions.lua

Multistrike would only add repeats to skills with the tag on it, which broke support for minions' skills
It now uses the same criteria that the damage mods do
This also made me realise that the repeat damage config was not working when used with minion skills, as we were only setting the condition on the player
So the average repeat damage and final repeat values were completely wrong, and the double damage with spells line on Awakened Spell Echo was not working at all with minions
Build: https://pobb.in/ymtQ4g2S_2As
Before:
After:

Fix Multistrike + Awakened Spell Echo not working properly with minions

---

src/Modules/CalcActiveSkill.lua
src/Modules/CalcPerform.lua

Fixes #8042
Currently the reservation caused by skills such as Spellslinger and Autoexertion is applied to the triggered skills. This causes issues such as the mentioned where some modifiers are not applied to that reservation. This pr causes the reservation to come from the active part of the trigger skill gem allowing for correct application of reservation modifiers.
This pr makes the assumption that summing up all the raw reservation values and then applying the modifiers is the same as applying the modifiers and then summing as the text on the mentioned gems implies: `This Skill's Mana Reservation is the total of the Mana Reservations of Supported Skills, and cannot be further modified`
I also couldn't think of a good predicate for when to apply this logic so i've made the assumption …

Fix trigger based reservation pooling

---

src/Classes/ItemDBControl.lua

The sort was only using the attribute requirements from the item base instead of including local attribute requirement changing mods like on Akoya's Gaze
Fixes #8799

Fix Item sort option for "Current Usable" not using taking into account attribute requirement mods

---

src/Modules/CalcSetup.lua

Fixes #8797
When rebuilding an env from cache for reuse in future calculations skillData is reset and only select properties are preserved. `attackSpeedMultiplier` was not one of them causing the dps to double in the case of #8797 due to increased attack speed.
This pr preserves `attackSpeedMultiplier` to fix the issue and `soulPreventionDuration` to prevent a potential future issue.

Fix values changing depending on order of skill groups

---

src/Data/Skills/act_int.lua
src/Export/Skills/act_int.txt

Righteous Fire of Arcane Devotion did not provide more cast speed when active.
- Compared a test build with Fireball and Righteous Fire of Arcane Devotion on latest release, dev branch and branch with my fix
- Only edited file in `./src/Export` and then ran GGPK export
https://pobb.in/yeT4ZfjWoCqF

Fix Righteous Fire of Arcane Devotion more Cast Speed mod not working

---

src/Data/Skills/sup_int.lua
src/Export/Skills/sup_int.txt
src/Modules/ConfigOptions.lua

Fixes #8822 .
There were two sections in the Config Tab that let you specify time spent channelling, leading to confusion in the above issue.  This PR removes the skill-specific one and has Focused Channelling rely on the existing ChannellingTime multiplier instead.
**This will break people's builds if they didn't have this box set up for something else.**

Remove Channelling time config box for Focused Channelling - Existing users should update their config

---

src/Classes/ModStore.lua
src/Modules/ConfigOptions.lua

The configs limited the mods by hardcoding the active count value instead of grabbing it from the stat
Fixes #8816

Fix Summon Spider / Spectral Wolf count config not scaling with Dark Monarch

---

src/Modules/CalcPerform.lua

Fixes #8813
Required attributes was not being sorted in the breakdown, but Omni was on it's own. Setting the .source flag fixes this and let's us remove redundant sorting later as it is taken care of within CalcBreakdownControl now #7211.
At least that's the theory. Seems to work, makes sense to me, hope this is right. _cross fingers_
Without Omni
With Omni

Fix Attribute Requirement sorting

---

src/Modules/ConfigOptions.lua

Plague Bearer "Incubating" was the default drop down selection, but it was not applying. By switching to "Infecting", the DPS would stay the same. Then switching back to "Incubating" would lower poison damage by 20% as expected. But after saving and reloading the build, the DPS would be higher again, I guess because it counts as having nothing selected.
https://pobb.in/7ciL29S6yGvx
Screenshots not really helpful here.
Also, plz help my build

Fix Plague Bearer default config not applying

---

src/Classes/ModStore.lua
src/Data/ModCache.lua
src/Modules/ModParser.lua

Fixes #3951.
As far as I know there was no way to search for Item names in Modparser, so I added a condition to "ItemCondition" in ModStore.
- Having Iron Mass in main hand gives the skeletons the weapon as before, as well as off hand not giving the weapon.
- Removed the DUMMY mod so config option only shows up when Iron Mass is in main hand now.
- If you have another mod that uses the same config, it won't apply the triple damage to skeletons when toggled because we require "The Iron Mass, Gladius" to be in the main hand slot.
- "20% more damage if you have hit with your main hand weapon recently" will have the config appear with Iron Mass in offhand, and properly not give the triple damage.
https://pobb.in/SzAJuJj2lVhI

Fix Iron Mass giving Skeletons Triple Damage in Offhand

---

src/Modules/CalcPerform.lua

Linking Enfeeble to High Impact Mine caused sources of Increased Mine Aura effect to scale the curse effect on Enfeeble

Fix Mine Aura effect scaling Curses used with High-Impact Mine

---

src/Data/ModCache.lua
src/Data/Uniques/helmet.lua
src/Modules/ModParser.lua

In 3.26 it was changed so that Devouring Diadem uses prefix veiled mods instead of suffix ones
Also added support for the crit damage mod
Fixes #8863

Fix Devouring Diadem in unique list using suffix veiled mods

---

src/Classes/ModList.lua
src/Modules/CalcSetup.lua

Fixes #8860  .
The way scaling mods on items seems to work in game is that the mod is scaled, rounded towards 0, then added to the existing mod.  i.e. mod + truncate(mod * scale) vs. truncate(mod * (1 + scale))
This is really only seen when the scalar is below 1, which only happens for Runegraft of the Bound (that I could tell)
- Example A comes from the issue.  1 Endurance charge + truncate(1 Endurance charge * -20%) = 1 Endurance charge
- Example B comes from the comment on that issue.  26% Fire res + truncate(-5.2% Fire res) = 21% Fire res
- Example C uses Widowhail to show that it works fine for other scaling items as-is: 35% fire res quiver + truncate(35 * 197% bow) = 103% fire res
Note that I only fixed this for Runegraft of the Bound, because this seems to only apply for scaling …

Fix rounding of scaled mods being incorrect in some cases

---

src/Modules/CalcSetup.lua

Kalandra's Touch now copies the influence from the other ring
Also realised that this has always been slightly broken as it was not using the correct names for the conqueror mods
Fixes #8885

Fix Kaladra's Touch not copying influence from other ring

---

src/Classes/ItemsTab.lua

Fixes #8903 
Implemented a very hacky solution. Will look for a better solution.
Currently, there is a mix of both exclusionary and inclusionary filtering for the `BaseTypes`. 
Ideally it would be refactored to solely be based on inclusionary filtering, preventing this bug from recurring when a new BaseType is added to POE. The best long term solution would be directly associating `sourceId` flags with the item `BaseType`, allowing us to bypass this logic entirely.
Not fully confident on doing this yet, as I am still new to the codebase. If anyone has any good ideas on the best way to approach this, I'd really appreciate it :)
Add modifier to Tincture Causes Crash
No Longer crashes, and invalid `sourceId`'s are no long visible

Fix crash when clicking "Add modifier" button on Tinctures

---

src/Modules/CalcOffence.lua

Fixes incorrect calculation of attack speed while dual wielding.
Fixes #8898
Attack speed while dual wielding is currently calculated using a simple average `(MH + OH)/2`, when a harmonic mean `2 / ( 1/MH + 1/OH)` is the correct way to calculate average of attack speed. A simple average would have to be applied to the attack _time_ to be the correct formula.
More detail is in this reddit thread: https://old.reddit.com/r/pathofexile/comments/1m8ytld/big_misconception_on_dual_wielding_pob_and_wiki/
- Verified dual wielding
- Verified dual wielding with skills that use both weapons at the same time (they also average their attack times)
- Verified 1h + shield/empty offhand stays the same
```bash
eNrtXG1v2zgS_lz_CsLAAXvYTWzJsp0EyS6ctybYpPXaaXv3aUFLtM0LJboSlTS76H-_ISnJsmvqxTLu020XrS3OMxzOcIYzQy …
```

Use harmonic mean for dual wield attack speed calc instead of average

---

src/Modules/CalcOffence.lua

output.Duration is already modified by debuffDurationMult in the duration block above so it doesn't need to be applied here again
Fixes #8901

Fix Temporal Chains double counting towards Brand Ticks

---

src/Data/ModCache.lua
src/Modules/CalcPerform.lua
src/Modules/ModParser.lua

The keystone effects were applied in mod parser so if you had more than 1 copy of the mod in your build it would apply multiple times
Fixes #8895

Fix Shepherd of Souls applying twice with 2 Yaomac's Accord equipped

---

src/Classes/PassiveTreeView.lua

Tattoos are different than runegraft in game, and although unlikely, showing "tattoo" for editing the mastery may cause confusion.
EDIT: The dps is different because my build config wasn't set up the same as I have it in the release build.

Tooltip text "tattoo" or "runegraft" based on node type

---

src/Classes/GemSelectControl.lua
src/Classes/ItemsTab.lua
src/Classes/NotableDBControl.lua
src/Classes/PassiveTreeView.lua
src/Classes/SkillsTab.lua
src/Classes/Tooltip.lua
src/Modules/ItemTools.lua
src/Modules/Main.lua

PoB does not calculate mods that have red text on them but many users do not know this. Adding this reminder text after all the lines should make it more obvious

Add text after red mods to show that PoB does not currently handle them

---

src/Modules/CalcPerform.lua

We were not taking into account the ailment avoidance from Ancestral Vision when determining if the Skitterbots effects should be applied to the player
Fixes #8932

Fix Ancestral Vision not working correctly with The Arkhon's Tools

---

src/Data/SkillStatMap.lua

The repeat stat was looking for a SkillType check on the minion skill but this is not correct. This change might make spell echo repeats affect some spell unintentionally but it's too hard to tell
Fixes #8951

Fix Spell Echo not working with some Minion skills

---

src/Modules/CalcMirages.lua

The `CalcMirages.lua` logic for detecting the active "General's Cry" skill incorrectly compared `env.player.mainSkill.socketGroup.slot` to itself, causing the slot-matching condition to always be true. This could result in the wrong skill being used for cooldown and active property calculations. This small PR fixes it.
- Updated the condition to compare the iterated skill's socket group slot (`skill.socketGroup.slot`) against the main skill's socket group slot.
- Ran the full busted test suite with `--lua=luajit` to confirm no issues.

Correct skill slot comparison for General's Cry detection

---

.github/workflows/spellcheck.yml

Copied from https://github.com/PathOfBuildingCommunity/PathOfBuilding-PoE2/pull/1260

[PATCH] chore: update cspell to run on push

---

src/Classes/ModList.lua
src/Modules/CalcSetup.lua

Fixes #8971
https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/8862 seems to have caused an issue where LIST type mods are duplicated due to how `ModListClass:MergeMod` handles them https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/d2524f92d902fc015e225cf78bce4f48b936462a/src/Classes/ModList.lua#L48-L59
This PR adds a switch to `ModListClass:MergeMod` causing mods which cannot be merged to not be added.

Fix LIST type mods being duplicated

---

docs/modSyntax.md
src/Data/Spectres.lua
src/Export/Minions/Spectres.txt

Fix instances where "unscalable" is mistakenly spelled as "unscal**e**able"
- one instance in the docs (which might have led to the other mistakes)
- others all seem to be in Spectres
It does actually make a mechanical difference, but it's unlikely to ever have caused problems because buff effect scaling is so rare

Fix typos "unscaleable" to "unscalable"
